import type { VocabItem } from "@/lib/types";

// Part A: 70 collocations Hebrew speakers get wrong (verb / adjective choice).
// Part B: 40 false friends and Hebrew-interference words.

export const COLLOCATIONS_TRAPS: VocabItem[] = [
  // ---------------------------------------------------------------- Part A: collocations
  // ----- make
  {
    id: "v-cl-make-a-decision",
    word: "make a decision",
    pos: "phr",
    he: "לקבל החלטה",
    def: "to choose what to do after thinking about it",
    examples: ["We need to make a decision about the apartment this week.", "She made a quick decision and bought the tickets."],
    cloze: "I can't ___ a decision without more information.",
    clozeAnswer: "make",
    collocations: ["make a big decision", "make the right decision", "make a quick decision"],
    band: 1,
    tags: ["collocation"],
    trap: "בעברית 'מקבלים' החלטה, באנגלית make a decision, לא take או receive.",
    colloc: { frame: "It's time to ___ a decision about the job offer.", answer: "make", options: ["make", "take", "receive"], whyHe: "מקבלים החלטה = make a decision." },
  },
  {
    id: "v-cl-make-a-mistake",
    word: "make a mistake",
    pos: "phr",
    he: "לעשות טעות, לטעות",
    def: "to do something wrong by accident",
    examples: ["Everyone makes mistakes when they learn a language.", "I made a mistake on the form and had to start again."],
    cloze: "Don't worry if you ___ a mistake, just fix it.",
    clozeAnswer: "make",
    collocations: ["make a big mistake", "make the same mistake", "make a stupid mistake"],
    band: 1,
    tags: ["collocation"],
    trap: "בעברית 'עושים' טעות, אבל באנגלית make a mistake, לא do a mistake.",
    colloc: { frame: "I think I ___ a mistake in the last answer.", answer: "made", options: ["made", "did", "had"], whyHe: "עושים טעות = make a mistake, לא do." },
  },
  {
    id: "v-cl-make-an-effort",
    word: "make an effort",
    pos: "phr",
    he: "להתאמץ, לעשות מאמץ",
    def: "to try hard to do something",
    examples: ["He made a real effort to be on time.", "Please make an effort to speak only English in class."],
    cloze: "You should ___ an effort to call your grandmother.",
    clozeAnswer: "make",
    collocations: ["make a real effort", "make every effort", "make an effort to do"],
    band: 2,
    tags: ["collocation"],
    trap: "'לעשות מאמץ' = make an effort, לא do an effort.",
    colloc: { frame: "She ___ a big effort to learn Hebrew.", answer: "made", options: ["made", "did", "put"], whyHe: "עושים מאמץ = make an effort." },
  },
  {
    id: "v-cl-make-sense",
    word: "make sense",
    pos: "phr",
    he: "להיות הגיוני",
    def: "to be clear, logical, or easy to understand",
    examples: ["His explanation didn't make sense to me.", "It makes sense to leave early and avoid traffic."],
    cloze: "This sentence doesn't ___ sense, can you explain it?",
    clozeAnswer: "make",
    collocations: ["make sense to someone", "make perfect sense", "it makes sense to do"],
    band: 2,
    tags: ["collocation"],
    trap: "'זה הגיוני' = It makes sense. לא 'it is logic' ולא 'it does sense'.",
    colloc: { frame: "Does the plan ___ sense to you?", answer: "make", options: ["make", "have", "do"], whyHe: "הגיוני = makes sense." },
  },
  {
    id: "v-cl-make-money",
    word: "make money",
    pos: "phr",
    he: "להרוויח כסף",
    def: "to earn money from work or business",
    examples: ["She makes good money as a programmer.", "It's hard to make money from a small shop."],
    cloze: "He wants to ___ money fast, so he works two jobs.",
    clozeAnswer: "make",
    collocations: ["make good money", "make a lot of money", "make money from"],
    band: 1,
    tags: ["collocation"],
    accept: ["earn"],
    trap: "'להרוויח כסף' = make/earn money, לא win money (זה לזכות בהגרלה).",
    colloc: { frame: "You can't ___ money without taking some risk.", answer: "make", options: ["make", "win", "do"], whyHe: "להרוויח כסף = make money. win = לזכות." },
  },
  {
    id: "v-cl-make-progress",
    word: "make progress",
    pos: "phr",
    he: "להתקדם",
    def: "to get better or move forward with something",
    examples: ["You're making great progress with your English.", "We made slow progress because of the rain."],
    cloze: "The team is finally ___ progress on the project.",
    clozeAnswer: "making",
    collocations: ["make good progress", "make slow progress", "make progress with"],
    band: 2,
    tags: ["collocation"],
    trap: "'לעשות התקדמות' / 'להתקדם' = make progress, לא do progress.",
    colloc: { frame: "Have you ___ any progress with the report?", answer: "made", options: ["made", "done", "taken"], whyHe: "מתקדמים = make progress." },
  },
  {
    id: "v-cl-make-a-phone-call",
    word: "make a phone call",
    pos: "phr",
    he: "לעשות טלפון, להתקשר",
    def: "to call someone on the phone",
    examples: ["I need to make a quick phone call before we go.", "She made a few phone calls and found a plumber."],
    cloze: "Excuse me, I have to ___ a phone call.",
    clozeAnswer: "make",
    collocations: ["make a quick phone call", "make a call to", "make a few calls"],
    band: 1,
    tags: ["collocation"],
    trap: "'לעשות טלפון' = make a phone call, לא do a phone.",
    colloc: { frame: "Can I ___ a phone call from your office?", answer: "make", options: ["make", "do", "give"], whyHe: "עושים טלפון = make a phone call." },
  },
  {
    id: "v-cl-make-an-appointment",
    word: "make an appointment",
    pos: "phr",
    he: "לקבוע תור, לקבוע פגישה",
    def: "to arrange a time to see a doctor, dentist, etc.",
    examples: ["I made an appointment with the dentist for Monday.", "You have to make an appointment, you can't just walk in."],
    cloze: "Please ___ an appointment with the doctor this week.",
    clozeAnswer: "make",
    collocations: ["make an appointment with", "make an appointment for", "cancel an appointment"],
    band: 2,
    tags: ["collocation"],
    trap: "'לקבוע תור' = make an appointment, לא fix / set a turn.",
    colloc: { frame: "I ___ an appointment for tomorrow at nine.", answer: "made", options: ["made", "fixed", "took"], whyHe: "קובעים תור = make an appointment." },
  },
  {
    id: "v-cl-make-friends",
    word: "make friends",
    pos: "phr",
    he: "להתחבר, לרכוש חברים",
    def: "to become friends with new people",
    examples: ["It's easy to make friends at university.", "He made friends with our neighbors quickly."],
    cloze: "She's shy, so it takes her time to ___ friends.",
    clozeAnswer: "make",
    collocations: ["make friends with", "make new friends", "make friends easily"],
    band: 2,
    tags: ["collocation"],
    trap: "'להכיר חברים' / 'לרכוש חברים' = make friends, לא find / get friends.",
    colloc: { frame: "Did you ___ any friends in the new office?", answer: "make", options: ["make", "find", "do"], whyHe: "מתחברים = make friends." },
  },
  // ----- do
  {
    id: "v-cl-do-homework",
    word: "do homework",
    pos: "phr",
    he: "להכין שיעורי בית",
    def: "to complete the schoolwork you were given for home",
    examples: ["The kids do their homework right after lunch.", "I forgot to do my math homework."],
    cloze: "You can watch TV after you ___ your homework.",
    clozeAnswer: "do",
    collocations: ["do your homework", "do some homework", "finish your homework"],
    band: 1,
    tags: ["collocation"],
    trap: "בעברית 'מכינים' שיעורי בית, באנגלית do homework, לא make / prepare homework.",
    colloc: { frame: "Have you ___ your homework yet?", answer: "done", options: ["done", "made", "prepared"], whyHe: "מכינים שיעורים = do homework." },
  },
  {
    id: "v-cl-do-the-dishes",
    word: "do the dishes",
    pos: "phr",
    he: "לשטוף כלים",
    def: "to wash the plates, cups, and pots after a meal",
    examples: ["I'll cook if you do the dishes.", "We did the dishes together after dinner."],
    cloze: "It's your turn to ___ the dishes tonight.",
    clozeAnswer: "do",
    collocations: ["do the dishes", "wash the dishes", "load the dishwasher"],
    band: 1,
    tags: ["collocation"],
    accept: ["wash"],
    trap: "'לשטוף כלים' = do / wash the dishes, לא make the dishes.",
    colloc: { frame: "Who's going to ___ the dishes after the party?", answer: "do", options: ["do", "make", "take"], whyHe: "שוטפים כלים = do the dishes." },
  },
  {
    id: "v-cl-do-business",
    word: "do business",
    pos: "phr",
    he: "לעשות עסקים",
    def: "to buy, sell, or work with a company or person",
    examples: ["We've done business with that supplier for years.", "It's a pleasure to do business with you."],
    cloze: "Our company wants to ___ business in Europe.",
    clozeAnswer: "do",
    collocations: ["do business with", "do business abroad", "business partner"],
    band: 2,
    tags: ["collocation"],
    trap: "'לעשות עסקים' = do business, לא make business.",
    colloc: { frame: "They refuse to ___ business with him.", answer: "do", options: ["do", "make", "have"], whyHe: "עושים עסקים = do business." },
  },
  {
    id: "v-cl-do-a-favor",
    word: "do a favor",
    pos: "phr",
    he: "לעשות טובה",
    def: "to help someone by doing something for them",
    examples: ["Can you do me a favor and pick up the kids?", "She did me a big favor last year."],
    cloze: "Could you ___ me a favor and close the window?",
    clozeAnswer: "do",
    collocations: ["do someone a favor", "do a big favor", "ask a favor"],
    band: 2,
    tags: ["collocation"],
    trap: "'לעשות טובה' = do someone a favor, לא make a favor.",
    colloc: { frame: "He ___ me a favor, so I owe him one.", answer: "did", options: ["did", "made", "gave"], whyHe: "עושים טובה = do a favor." },
  },
  {
    id: "v-cl-do-research",
    word: "do research",
    pos: "phr",
    he: "לערוך מחקר, לחקור",
    def: "to study something carefully to find new information",
    examples: ["She's doing research on sleep at the university.", "Do some research before you buy a used car."],
    cloze: "Scientists ___ research on the virus for years.",
    clozeAnswer: "did",
    collocations: ["do research on", "do some research", "research shows"],
    band: 3,
    tags: ["collocation"],
    accept: ["conducted"],
    trap: "'לעשות מחקר' = do research, לא make research. גם research לא ניתן לספירה: לא 'a research'.",
    colloc: { frame: "I ___ a lot of research before choosing the school.", answer: "did", options: ["did", "made", "searched"], whyHe: "עורכים מחקר = do research." },
  },
  {
    id: "v-cl-do-your-best",
    word: "do your best",
    pos: "phr",
    he: "לעשות כמיטב יכולתך",
    def: "to try as hard as you can",
    examples: ["Just do your best, that's all we ask.", "He did his best, but the exam was very hard."],
    cloze: "I'll ___ my best to finish it by Thursday.",
    clozeAnswer: "do",
    collocations: ["do your best", "do your best to", "try your best"],
    band: 2,
    tags: ["collocation"],
    accept: ["try"],
    trap: "'לעשות את המקסימום' = do your best, לא make your best.",
    colloc: { frame: "She always ___ her best at work.", answer: "does", options: ["does", "makes", "takes"], whyHe: "עושים כמיטב יכולתנו = do our best." },
  },
  // ----- take
  {
    id: "v-cl-take-a-shower",
    word: "take a shower",
    pos: "phr",
    he: "להתקלח",
    def: "to wash yourself under a shower",
    examples: ["I take a shower every morning before work.", "He took a quick shower after the game."],
    cloze: "Let me ___ a shower and then we can go.",
    clozeAnswer: "take",
    collocations: ["take a quick shower", "take a hot shower", "take a bath"],
    band: 1,
    tags: ["collocation"],
    trap: "'לעשות מקלחת' = take a shower (בריטי: have a shower), לא make / do a shower.",
    colloc: { frame: "I need to ___ a shower before dinner.", answer: "take", options: ["take", "make", "do"], whyHe: "עושים מקלחת = take a shower." },
  },
  {
    id: "v-cl-take-a-break",
    word: "take a break",
    pos: "phr",
    he: "לעשות הפסקה",
    def: "to stop working or studying for a short time",
    examples: ["Let's take a break and get some coffee.", "She took a ten-minute break every hour."],
    cloze: "We've been working for hours, let's ___ a break.",
    clozeAnswer: "take",
    collocations: ["take a short break", "take a coffee break", "take a break from"],
    band: 1,
    tags: ["collocation"],
    trap: "'לעשות הפסקה' = take a break, לא make / do a break.",
    colloc: { frame: "You look tired, why don't you ___ a break?", answer: "take", options: ["take", "make", "do"], whyHe: "עושים הפסקה = take a break." },
  },
  {
    id: "v-cl-take-a-photo",
    word: "take a photo",
    pos: "phr",
    he: "לצלם",
    def: "to use a camera to make a picture",
    examples: ["Can you take a photo of us in front of the sea?", "I took a lot of photos on the trip."],
    cloze: "Stand there and I'll ___ a photo of you.",
    clozeAnswer: "take",
    collocations: ["take a photo of", "take a picture", "take a selfie"],
    band: 1,
    tags: ["collocation"],
    trap: "'לצלם' = take a photo / a picture, לא make / do a photo.",
    colloc: { frame: "Tourists ___ photos of the old city walls.", answer: "take", options: ["take", "make", "do"], whyHe: "מצלמים = take a photo." },
  },
  {
    id: "v-cl-take-a-risk",
    word: "take a risk",
    pos: "phr",
    he: "לקחת סיכון",
    def: "to do something that might be dangerous or go wrong",
    examples: ["She took a risk and opened her own restaurant.", "I don't want to take any risks with my health."],
    cloze: "Sometimes you have to ___ a risk to succeed.",
    clozeAnswer: "take",
    collocations: ["take a big risk", "take risks", "take the risk of"],
    band: 2,
    tags: ["collocation"],
    trap: "'לקחת סיכון' = take a risk. לא make a risk.",
    colloc: { frame: "He ___ a huge risk when he quit his job.", answer: "took", options: ["took", "made", "did"], whyHe: "לוקחים סיכון = take a risk." },
  },
  {
    id: "v-cl-take-place",
    word: "take place",
    pos: "phr",
    he: "להתקיים, להתרחש",
    def: "to happen, especially an event that was planned",
    examples: ["The meeting will take place on Tuesday.", "The wedding took place in a small village."],
    cloze: "The concert will ___ place in the park.",
    clozeAnswer: "take",
    collocations: ["take place in", "take place on Monday", "the event takes place"],
    band: 2,
    tags: ["collocation"],
    trap: "'להתקיים' = take place. לא be happened / make place.",
    colloc: { frame: "Where did the accident ___ place?", answer: "take", options: ["take", "make", "have"], whyHe: "מתרחש / מתקיים = take place." },
  },
  {
    id: "v-cl-take-part-in",
    word: "take part in",
    pos: "phr",
    he: "להשתתף ב-",
    def: "to be part of an activity with other people",
    examples: ["About 200 runners took part in the race.", "I'd love to take part in the next workshop."],
    cloze: "Every student has to ___ part in the project.",
    clozeAnswer: "take",
    collocations: ["take part in a competition", "take part in a discussion", "take an active part"],
    band: 2,
    tags: ["collocation"],
    trap: "'לקחת חלק ב-' = take part in, עם in. לא take part at / of.",
    colloc: { frame: "Did you ___ part in the demonstration?", answer: "take", options: ["take", "make", "have"], whyHe: "משתתפים = take part in." },
  },
  {
    id: "v-cl-take-advantage-of",
    word: "take advantage of",
    pos: "phr",
    he: "לנצל",
    def: "to use a chance or situation to get something good",
    examples: ["Take advantage of the sale, it ends Friday.", "He took advantage of the free time to study."],
    cloze: "You should ___ advantage of the good weather and go out.",
    clozeAnswer: "take",
    collocations: ["take advantage of an opportunity", "take advantage of someone", "take full advantage"],
    band: 4,
    tags: ["collocation"],
    trap: "'לנצל הזדמנות' = take advantage of. שימו לב: take advantage of someone = לנצל אדם (שלילי).",
    colloc: { frame: "We ___ advantage of the discount and bought two.", answer: "took", options: ["took", "made", "used"], whyHe: "מנצלים = take advantage of." },
  },
  {
    id: "v-cl-take-your-time",
    word: "take your time",
    pos: "phr",
    he: "קח את הזמן, לא למהר",
    def: "to do something slowly, without hurrying",
    examples: ["Take your time, there's no rush.", "She took her time choosing a dress."],
    cloze: "___ your time, we don't need to leave yet.",
    clozeAnswer: "Take",
    collocations: ["take your time", "take your time doing", "no rush"],
    band: 2,
    tags: ["collocation"],
    trap: "'קח את הזמן שלך' = take your time. לא have / make your time.",
    colloc: { frame: "He ___ his time answering the question.", answer: "took", options: ["took", "had", "made"], whyHe: "לא ממהר = take your time." },
  },
  // ----- have
  {
    id: "v-cl-have-a-good-time",
    word: "have a good time",
    pos: "phr",
    he: "ליהנות, לעשות חיים",
    def: "to enjoy yourself",
    examples: ["We had a good time at the party last night.", "Have a good time in Greece!"],
    cloze: "Did you ___ a good time on your vacation?",
    clozeAnswer: "have",
    collocations: ["have a great time", "have a wonderful time", "have a good time with"],
    band: 1,
    tags: ["collocation"],
    trap: "'לעשות חיים' / 'ליהנות' = have a good time, לא make / do a good time.",
    colloc: { frame: "The kids ___ a great time at the beach.", answer: "had", options: ["had", "made", "did"], whyHe: "נהנים = have a good time." },
  },
  {
    id: "v-cl-have-a-look",
    word: "have a look",
    pos: "phr",
    he: "להעיף מבט, להסתכל",
    def: "to look at something quickly",
    examples: ["Have a look at this photo, isn't it great?", "I had a look at the report, it seems fine."],
    cloze: "Can I ___ a look at your notes from the class?",
    clozeAnswer: "have",
    collocations: ["have a look at", "have a quick look", "take a look"],
    band: 2,
    tags: ["collocation"],
    accept: ["take"],
    trap: "'להעיף מבט' = have / take a look at, לא give a look.",
    colloc: { frame: "Let me ___ a look at the menu first.", answer: "have", options: ["have", "give", "make"], whyHe: "מעיפים מבט = have a look / take a look." },
  },
  {
    id: "v-cl-have-an-argument",
    word: "have an argument",
    pos: "phr",
    he: "לריב, להתווכח",
    def: "to argue with someone, often angrily",
    examples: ["We had an argument about the bill.", "They had a big argument and stopped talking."],
    cloze: "My parents ___ an argument about money last night.",
    clozeAnswer: "had",
    collocations: ["have an argument with", "have a big argument", "get into an argument"],
    band: 2,
    tags: ["collocation"],
    trap: "'לריב' = have an argument (או have a fight). make an argument = להציג טיעון, לא לריב.",
    colloc: { frame: "I don't want to ___ an argument with you.", answer: "have", options: ["have", "make", "do"], whyHe: "רבים = have an argument." },
  },
  {
    id: "v-cl-have-breakfast",
    word: "have breakfast",
    pos: "phr",
    he: "לאכול ארוחת בוקר",
    def: "to eat the morning meal",
    examples: ["I usually have breakfast at seven.", "We had breakfast at the hotel before the tour."],
    cloze: "Do you ___ breakfast before or after the gym?",
    clozeAnswer: "have",
    collocations: ["have breakfast", "have lunch", "have dinner"],
    band: 1,
    tags: ["collocation"],
    accept: ["eat"],
    trap: "'לאכול ארוחת בוקר' = have / eat breakfast, לא take breakfast.",
    colloc: { frame: "We usually ___ breakfast together on Saturdays.", answer: "have", options: ["have", "take", "do"], whyHe: "אוכלים ארוחת בוקר = have breakfast." },
  },
  {
    id: "v-cl-have-fun",
    word: "have fun",
    pos: "phr",
    he: "ליהנות, לעשות כיף",
    def: "to enjoy yourself",
    examples: ["The children had fun at the water park.", "Have fun tonight and don't come back too late!"],
    cloze: "We ___ so much fun at the wedding.",
    clozeAnswer: "had",
    collocations: ["have fun with", "have a lot of fun", "have fun doing"],
    band: 1,
    tags: ["collocation"],
    trap: "'לעשות כיף' = have fun. make fun of someone = ללעוג למישהו, לא ליהנות!",
    colloc: { frame: "Go and ___ fun with your friends.", answer: "have", options: ["have", "make", "do"], whyHe: "עושים כיף = have fun. make fun of = ללעוג." },
  },
  // ----- get
  {
    id: "v-cl-get-married",
    word: "get married",
    pos: "phr",
    he: "להתחתן",
    def: "to become someone's husband or wife",
    examples: ["They got married in a small ceremony last year.", "My brother is getting married in June."],
    cloze: "When did your parents ___ married?",
    clozeAnswer: "get",
    collocations: ["get married to", "get married in", "be married"],
    band: 1,
    tags: ["collocation"],
    trap: "'להתחתן עם' = get married to (לא with). married to a doctor.",
    colloc: { frame: "My sister is going to ___ married next summer.", answer: "get", options: ["get", "become", "make"], whyHe: "מתחתנים = get married." },
  },
  {
    id: "v-cl-get-lost",
    word: "get lost",
    pos: "phr",
    he: "ללכת לאיבוד",
    def: "to not know where you are or how to get somewhere",
    examples: ["We got lost on the way to the hotel.", "It's easy to get lost in the old city."],
    cloze: "Use the map so you don't ___ lost.",
    clozeAnswer: "get",
    collocations: ["get lost in", "get lost on the way", "be lost"],
    band: 1,
    tags: ["collocation"],
    trap: "'ללכת לאיבוד' = get lost, לא go lost. (בציווי, Get lost! = תתחפף!)",
    colloc: { frame: "We took a wrong turn and ___ lost.", answer: "got", options: ["got", "went", "made"], whyHe: "הולכים לאיבוד = get lost." },
  },
  {
    id: "v-cl-get-ready",
    word: "get ready",
    pos: "phr",
    he: "להתכונן, להתארגן",
    def: "to prepare yourself for something",
    examples: ["Give me ten minutes to get ready.", "The team is getting ready for the final."],
    cloze: "Hurry up and ___ ready, the taxi is outside!",
    clozeAnswer: "get",
    collocations: ["get ready for", "get ready to go", "be ready"],
    band: 1,
    tags: ["collocation"],
    trap: "'להתארגן' = get ready (for). לא make ready / prepare myself.",
    colloc: { frame: "The kids are ___ ready for school.", answer: "getting", options: ["getting", "making", "doing"], whyHe: "מתארגנים = get ready." },
  },
  {
    id: "v-cl-get-in-touch",
    word: "get in touch",
    pos: "phr",
    he: "ליצור קשר",
    def: "to contact someone by phone, email, etc.",
    examples: ["I'll get in touch with you next week.", "Please get in touch if you have any questions."],
    cloze: "How can I ___ in touch with the manager?",
    clozeAnswer: "get",
    collocations: ["get in touch with", "keep in touch", "stay in touch"],
    band: 2,
    tags: ["collocation"],
    trap: "'ליצור קשר' = get in touch (with), לא make contact / create contact.",
    colloc: { frame: "She ___ in touch with an old friend from school.", answer: "got", options: ["got", "made", "took"], whyHe: "יוצרים קשר = get in touch with." },
  },
  {
    id: "v-cl-get-a-job",
    word: "get a job",
    pos: "phr",
    he: "למצוא עבודה, להתקבל לעבודה",
    def: "to find and start paid work",
    examples: ["She got a job at a bank right after college.", "It's hard to get a job without experience."],
    cloze: "He finally ___ a job at a software company.",
    clozeAnswer: "got",
    collocations: ["get a job as", "get a good job", "look for a job"],
    band: 2,
    tags: ["collocation"],
    accept: ["found"],
    trap: "'להתקבל לעבודה' = get a job. לא receive a job / be accepted to work.",
    colloc: { frame: "I hope to ___ a job as a designer.", answer: "get", options: ["get", "receive", "catch"], whyHe: "מוצאים / מתקבלים לעבודה = get a job." },
  },
  // ----- give
  {
    id: "v-cl-give-a-hand",
    word: "give a hand",
    pos: "phr",
    he: "לעזור, לתת יד",
    def: "to help someone with something",
    examples: ["Can you give me a hand with these boxes?", "He gave us a hand moving the sofa."],
    cloze: "Could you ___ me a hand with the shopping bags?",
    clozeAnswer: "give",
    collocations: ["give someone a hand", "give a hand with", "lend a hand"],
    band: 2,
    tags: ["collocation"],
    accept: ["lend"],
    trap: "'לתת יד' = give someone a hand. לא help me a hand / make a hand.",
    colloc: { frame: "She ___ me a hand with the cooking.", answer: "gave", options: ["gave", "made", "did"], whyHe: "עוזרים = give a hand." },
  },
  {
    id: "v-cl-give-a-speech",
    word: "give a speech",
    pos: "phr",
    he: "לשאת נאום",
    def: "to talk formally to a group of people",
    examples: ["The mayor gave a short speech at the opening.", "I have to give a speech at my sister's wedding."],
    cloze: "He was nervous about ___ a speech in English.",
    clozeAnswer: "giving",
    collocations: ["give a speech about", "make a speech", "give a talk"],
    band: 3,
    tags: ["collocation"],
    accept: ["making"],
    trap: "'לשאת נאום' = give / make a speech, לא say / carry a speech.",
    colloc: { frame: "The manager ___ a speech to thank the team.", answer: "gave", options: ["gave", "said", "did"], whyHe: "נושאים נאום = give a speech." },
  },
  {
    id: "v-cl-give-an-example",
    word: "give an example",
    pos: "phr",
    he: "לתת דוגמה",
    def: "to mention a case that shows what you mean",
    examples: ["Can you give me an example of a good title?", "The teacher gave several examples on the board."],
    cloze: "Let me ___ you an example of what I mean.",
    clozeAnswer: "give",
    collocations: ["give an example of", "give a good example", "for example"],
    band: 2,
    tags: ["collocation"],
    trap: "'להביא דוגמה' = give an example, לא bring an example.",
    colloc: { frame: "Please ___ an example for each rule.", answer: "give", options: ["give", "bring", "say"], whyHe: "מביאים דוגמה = give an example." },
  },
  // ----- go
  {
    id: "v-cl-go-for-a-walk",
    word: "go for a walk",
    pos: "phr",
    he: "לצאת להליכה, לעשות סיבוב",
    def: "to walk somewhere for pleasure or exercise",
    examples: ["Let's go for a walk on the beach after dinner.", "She goes for a walk every morning."],
    cloze: "It's a beautiful evening, let's ___ for a walk.",
    clozeAnswer: "go",
    collocations: ["go for a walk", "go for a run", "take a walk"],
    band: 2,
    tags: ["collocation"],
    accept: ["take", "have"],
    trap: "'לעשות סיבוב' = go for a walk / take a walk, לא make a walk.",
    colloc: { frame: "We ___ for a long walk in the park.", answer: "went", options: ["went", "made", "did"], whyHe: "יוצאים להליכה = go for a walk." },
  },
  // ----- keep
  {
    id: "v-cl-keep-a-promise",
    word: "keep a promise",
    pos: "phr",
    he: "לקיים הבטחה",
    def: "to do what you said you would do",
    examples: ["He always keeps his promises.", "I promised to help, and I'm going to keep that promise."],
    cloze: "She ___ her promise and came to the show.",
    clozeAnswer: "kept",
    collocations: ["keep a promise", "keep your word", "make a promise"],
    band: 2,
    tags: ["collocation"],
    trap: "'לקיים הבטחה' = keep a promise, לא hold / fulfill a promise. 'להבטיח' = make a promise.",
    colloc: { frame: "A good friend ___ his promises.", answer: "keeps", options: ["keeps", "holds", "does"], whyHe: "מקיימים הבטחה = keep a promise." },
  },
  {
    id: "v-cl-keep-a-secret",
    word: "keep a secret",
    pos: "phr",
    he: "לשמור סוד",
    def: "to not tell anyone something private",
    examples: ["Can you keep a secret?", "She kept the secret for twenty years."],
    cloze: "Promise me you'll ___ this a secret.",
    clozeAnswer: "keep",
    collocations: ["keep a secret", "keep something secret", "tell a secret"],
    band: 2,
    tags: ["collocation"],
    trap: "'לשמור סוד' = keep a secret, לא save / guard a secret.",
    colloc: { frame: "My brother can't ___ a secret for a day.", answer: "keep", options: ["keep", "save", "hold"], whyHe: "שומרים סוד = keep a secret." },
  },
  {
    id: "v-cl-keep-in-mind",
    word: "keep in mind",
    pos: "phr",
    he: "לזכור, לקחת בחשבון",
    def: "to remember something important when you decide or act",
    examples: ["Keep in mind that the shops close early on Friday.", "I'll keep your advice in mind."],
    cloze: "___ in mind that the meeting starts at eight.",
    clozeAnswer: "Keep",
    collocations: ["keep in mind that", "keep something in mind", "bear in mind"],
    band: 3,
    tags: ["collocation"],
    accept: ["Bear"],
    trap: "'לקחת בחשבון' / 'לזכור ש...' = keep in mind (that), לא take in mind.",
    colloc: { frame: "Please ___ in mind that he's only a child.", answer: "keep", options: ["keep", "take", "hold"], whyHe: "לוקחים בחשבון = keep in mind." },
  },
  // ----- pay
  {
    id: "v-cl-pay-attention",
    word: "pay attention",
    pos: "phr",
    he: "לשים לב",
    def: "to watch or listen carefully",
    examples: ["Pay attention to the road when you drive.", "The students didn't pay attention to the teacher."],
    cloze: "Please ___ attention, this part is important.",
    clozeAnswer: "pay",
    collocations: ["pay attention to", "pay close attention", "pay no attention"],
    band: 2,
    tags: ["collocation"],
    trap: "'לשים לב' = pay attention (to), לא put attention.",
    colloc: { frame: "You should ___ more attention in class.", answer: "pay", options: ["pay", "put", "make"], whyHe: "שמים לב = pay attention." },
  },
  {
    id: "v-cl-pay-a-visit",
    word: "pay a visit",
    pos: "phr",
    he: "לערוך ביקור",
    def: "to visit someone or a place",
    examples: ["We paid a visit to my aunt in Haifa.", "The minister paid a short visit to the school."],
    cloze: "Let's ___ a visit to Grandpa this weekend.",
    clozeAnswer: "pay",
    collocations: ["pay a visit to", "pay someone a visit", "pay a short visit"],
    band: 3,
    tags: ["collocation"],
    trap: "'לערוך ביקור' = pay a visit (to), לא make / do a visit.",
    colloc: { frame: "The president ___ a visit to the hospital.", answer: "paid", options: ["paid", "made", "did"], whyHe: "עורכים ביקור = pay a visit." },
  },
  {
    id: "v-cl-pay-a-compliment",
    word: "pay a compliment",
    pos: "phr",
    he: "להחמיא, לתת מחמאה",
    def: "to say something nice about someone",
    examples: ["He paid me a compliment on my presentation.", "She loves paying compliments to her students."],
    cloze: "My boss ___ me a compliment on the report.",
    clozeAnswer: "paid",
    collocations: ["pay someone a compliment", "pay a compliment on", "give a compliment"],
    band: 4,
    tags: ["collocation"],
    accept: ["gave"],
    trap: "'לתת מחמאה' = pay / give a compliment, לא make / say a compliment.",
    colloc: { frame: "It's nice to ___ someone a compliment.", answer: "pay", options: ["pay", "make", "say"], whyHe: "מחמיאים = pay a compliment." },
  },
  // ----- catch
  {
    id: "v-cl-catch-a-cold",
    word: "catch a cold",
    pos: "phr",
    he: "להצטנן",
    def: "to become sick with a cold",
    examples: ["Wear a coat or you'll catch a cold.", "I caught a cold on the plane."],
    cloze: "She ___ a cold and stayed in bed all day.",
    clozeAnswer: "caught",
    collocations: ["catch a cold", "catch the flu", "have a cold"],
    band: 2,
    tags: ["collocation"],
    accept: ["got"],
    trap: "'להצטנן' = catch / get a cold. 'יש לי הצטננות' = I have a cold, לא I am cold (= קר לי).",
    colloc: { frame: "Half the office ___ a cold this winter.", answer: "caught", options: ["caught", "took", "made"], whyHe: "מצטננים = catch a cold." },
  },
  {
    id: "v-cl-catch-the-bus",
    word: "catch the bus",
    pos: "phr",
    he: "לתפוס את האוטובוס",
    def: "to get to the bus in time and get on it",
    examples: ["I have to leave now to catch the bus.", "We ran and caught the last bus home."],
    cloze: "If we don't hurry, we won't ___ the bus.",
    clozeAnswer: "catch",
    collocations: ["catch the bus", "catch a train", "miss the bus"],
    band: 2,
    tags: ["collocation"],
    trap: "'לתפוס אוטובוס' = catch the bus, 'לפספס' = miss the bus. לא reach / arrive the bus.",
    colloc: { frame: "I woke up late and didn't ___ the bus.", answer: "catch", options: ["catch", "reach", "arrive"], whyHe: "תופסים אוטובוס = catch the bus." },
  },
  {
    id: "v-cl-catch-someones-eye",
    word: "catch someone's eye",
    pos: "phr",
    he: "למשוך תשומת לב",
    def: "to make someone notice you or something",
    examples: ["A red jacket in the window caught my eye.", "Try to catch the waiter's eye."],
    cloze: "The bright poster ___ my eye as I walked past.",
    clozeAnswer: "caught",
    collocations: ["catch someone's eye", "catch someone's attention", "eye-catching"],
    band: 3,
    tags: ["collocation"],
    trap: "'משך את תשומת לבי' = caught my eye / caught my attention, לא pulled my attention.",
    colloc: { frame: "Her unusual name ___ my eye on the list.", answer: "caught", options: ["caught", "took", "pulled"], whyHe: "מושך תשומת לב = catch someone's eye." },
  },
  // ----- time
  {
    id: "v-cl-save-time",
    word: "save time",
    pos: "phr",
    he: "לחסוך זמן",
    def: "to use less time by doing something in a better way",
    examples: ["Taking the train will save us time.", "I use a shopping list to save time."],
    cloze: "Order online to ___ time and money.",
    clozeAnswer: "save",
    collocations: ["save time", "save money", "save a lot of time"],
    band: 3,
    tags: ["collocation"],
    trap: "'לחסוך זמן' = save time. 'להרוויח זמן' = buy time, לא win time.",
    colloc: { frame: "A dishwasher ___ a lot of time every day.", answer: "saves", options: ["saves", "wins", "keeps"], whyHe: "חוסכים זמן = save time." },
  },
  {
    id: "v-cl-waste-time",
    word: "waste time",
    pos: "phr",
    he: "לבזבז זמן",
    def: "to use time badly on things that are not useful",
    examples: ["Stop wasting time on your phone and study.", "We wasted an hour looking for parking."],
    cloze: "Don't ___ time arguing, just call them.",
    clozeAnswer: "waste",
    collocations: ["waste time on", "waste time doing", "a waste of time"],
    band: 3,
    tags: ["collocation"],
    trap: "'לבזבז זמן' = waste time. 'חבל על הזמן' (שלילי) = a waste of time. לא lose time.",
    colloc: { frame: "I ___ the whole morning waiting for the plumber.", answer: "wasted", options: ["wasted", "lost", "threw"], whyHe: "מבזבזים זמן = waste time." },
  },
  {
    id: "v-cl-spend-time",
    word: "spend time",
    pos: "phr",
    he: "לבלות זמן, להקדיש זמן",
    def: "to use time doing something or being with someone",
    examples: ["I love spending time with my kids.", "He spent two hours fixing the bike."],
    cloze: "We ___ the whole weekend at the beach.",
    clozeAnswer: "spent",
    collocations: ["spend time with", "spend time doing", "spend time on"],
    band: 2,
    tags: ["collocation"],
    trap: "'לבלות זמן עם' = spend time with. לא pass time with. אחרי spend time בא פועל ב-ing: spend time reading.",
    colloc: { frame: "I want to ___ more time with my family.", answer: "spend", options: ["spend", "pass", "make"], whyHe: "מבלים זמן = spend time." },
  },
  {
    id: "v-cl-kill-time",
    word: "kill time",
    pos: "phr",
    he: "להעביר את הזמן",
    def: "to do something while waiting so time passes faster",
    examples: ["We played cards to kill time at the airport.", "I killed an hour in a cafe before the meeting."],
    cloze: "Our flight was late, so we walked around the mall to ___ time.",
    clozeAnswer: "kill",
    collocations: ["kill time", "kill an hour", "pass the time"],
    band: 3,
    tags: ["collocation"],
    trap: "'להעביר את הזמן' (בזמן המתנה) = kill time / pass the time. לא pass time בלי the.",
    colloc: { frame: "I read a magazine to ___ time before the dentist.", answer: "kill", options: ["kill", "waste", "finish"], whyHe: "מעבירים זמן בהמתנה = kill time." },
  },
  // ----- run
  {
    id: "v-cl-run-a-business",
    word: "run a business",
    pos: "phr",
    he: "לנהל עסק",
    def: "to manage and be in charge of a company or shop",
    examples: ["My parents run a small business in Netanya.", "Running a business takes a lot of energy."],
    cloze: "She ___ a successful bakery with her sister.",
    clozeAnswer: "runs",
    collocations: ["run a business", "run a company", "run a shop"],
    band: 4,
    tags: ["collocation"],
    accept: ["manages"],
    trap: "'לנהל עסק' = run a business (גם manage). לא drive / hold a business.",
    colloc: { frame: "It's not easy to ___ a restaurant in this city.", answer: "run", options: ["run", "hold", "drive"], whyHe: "מנהלים עסק = run a business." },
  },
  // ----- break
  {
    id: "v-cl-break-a-record",
    word: "break a record",
    pos: "phr",
    he: "לשבור שיא",
    def: "to do better than the best result before",
    examples: ["She broke the national record in the 100 meters.", "The film broke box office records."],
    cloze: "He ___ the world record by two seconds.",
    clozeAnswer: "broke",
    collocations: ["break a record", "break the world record", "set a record"],
    band: 2,
    tags: ["collocation"],
    accept: ["beat"],
    trap: "'לשבור שיא' = break a record. 'לקבוע שיא' = set a record, לא make a record.",
    colloc: { frame: "The runner ___ the record for the marathon.", answer: "broke", options: ["broke", "won", "cut"], whyHe: "שוברים שיא = break a record." },
  },
  {
    id: "v-cl-break-the-law",
    word: "break the law",
    pos: "phr",
    he: "לעבור על החוק",
    def: "to do something that is not allowed by law",
    examples: ["Parking here breaks the law.", "He broke the law and paid a big fine."],
    cloze: "If you drive without a license, you're ___ the law.",
    clozeAnswer: "breaking",
    collocations: ["break the law", "break the rules", "against the law"],
    band: 3,
    tags: ["collocation"],
    trap: "'לעבור על החוק' = break the law, לא pass / cross the law. 'להפר כללים' = break the rules.",
    colloc: { frame: "Nobody should ___ the law, not even ministers.", answer: "break", options: ["break", "pass", "cross"], whyHe: "עוברים על החוק = break the law." },
  },
  {
    id: "v-cl-break-a-promise",
    word: "break a promise",
    pos: "phr",
    he: "להפר הבטחה",
    def: "to not do what you promised",
    examples: ["He broke his promise and didn't come.", "I never break a promise to my kids."],
    cloze: "She ___ her promise to call me back.",
    clozeAnswer: "broke",
    collocations: ["break a promise", "break your word", "keep a promise"],
    band: 3,
    tags: ["collocation"],
    trap: "'להפר הבטחה' = break a promise, לא cancel / violate a promise.",
    colloc: { frame: "You can't ___ a promise just because it's hard.", answer: "break", options: ["break", "cancel", "lose"], whyHe: "מפרים הבטחה = break a promise." },
  },
  // ----- tell / say / ask / throw
  {
    id: "v-cl-tell-the-truth",
    word: "tell the truth",
    pos: "phr",
    he: "להגיד את האמת",
    def: "to say what is true",
    examples: ["Just tell the truth, it's easier.", "To tell the truth, I didn't like the movie."],
    cloze: "I'm sure he's not ___ the truth about the money.",
    clozeAnswer: "telling",
    collocations: ["tell the truth", "to tell the truth", "tell a lie"],
    band: 1,
    tags: ["collocation"],
    trap: "'להגיד את האמת' = tell the truth, לא say the truth.",
    colloc: { frame: "Did she ___ the truth to the police?", answer: "tell", options: ["tell", "say", "speak"], whyHe: "אומרים את האמת = tell the truth." },
  },
  {
    id: "v-cl-tell-a-lie",
    word: "tell a lie",
    pos: "phr",
    he: "לשקר",
    def: "to say something that is not true",
    examples: ["He told a lie about where he was.", "Children sometimes tell lies to avoid trouble."],
    cloze: "She ___ a lie and later felt bad about it.",
    clozeAnswer: "told",
    collocations: ["tell a lie", "tell lies", "a white lie"],
    band: 2,
    tags: ["collocation"],
    trap: "'לשקר' = tell a lie (או lie). לא say a lie / make a lie.",
    colloc: { frame: "Why did you ___ a lie about your age?", answer: "tell", options: ["tell", "say", "make"], whyHe: "משקרים = tell a lie." },
  },
  {
    id: "v-cl-tell-a-joke",
    word: "tell a joke",
    pos: "phr",
    he: "לספר בדיחה",
    def: "to say something funny to make people laugh",
    examples: ["My uncle loves telling jokes at dinner.", "She told a joke and everyone laughed."],
    cloze: "He ___ a joke, but nobody laughed.",
    clozeAnswer: "told",
    collocations: ["tell a joke", "tell a funny story", "make a joke"],
    band: 2,
    tags: ["collocation"],
    trap: "'לספר בדיחה' = tell a joke, לא say a joke.",
    colloc: { frame: "Can you ___ a joke in English?", answer: "tell", options: ["tell", "say", "speak"], whyHe: "מספרים בדיחה = tell a joke." },
  },
  {
    id: "v-cl-say-sorry",
    word: "say sorry",
    pos: "phr",
    he: "לבקש סליחה, להתנצל",
    def: "to tell someone you are sorry for what you did",
    examples: ["You should say sorry to your sister.", "He said sorry for being late."],
    cloze: "Go and ___ sorry to your brother for shouting.",
    clozeAnswer: "say",
    collocations: ["say sorry to", "say sorry for", "apologize"],
    band: 1,
    tags: ["collocation"],
    trap: "'לבקש סליחה' = say sorry / apologize, לא ask sorry / ask forgiveness.",
    colloc: { frame: "She didn't even ___ sorry after the accident.", answer: "say", options: ["say", "ask", "tell"], whyHe: "מבקשים סליחה = say sorry." },
  },
  {
    id: "v-cl-ask-a-question",
    word: "ask a question",
    pos: "phr",
    he: "לשאול שאלה",
    def: "to say something to get information or an answer",
    examples: ["Can I ask you a question about the schedule?", "The students asked a lot of questions."],
    cloze: "Feel free to ___ a question at any time.",
    clozeAnswer: "ask",
    collocations: ["ask a question", "ask someone a question", "answer a question"],
    band: 1,
    tags: ["collocation"],
    trap: "'לשאול שאלה' = ask a question, לא make / do a question. ואחרי ask אין to: ask me, לא ask to me.",
    colloc: { frame: "Nobody wanted to ___ a question after the talk.", answer: "ask", options: ["ask", "make", "do"], whyHe: "שואלים שאלה = ask a question." },
  },
  {
    id: "v-cl-throw-a-party",
    word: "throw a party",
    pos: "phr",
    he: "לערוך מסיבה",
    def: "to organize a party at your home or a place you rent",
    examples: ["We're throwing a party for Dad's 60th birthday.", "They threw a big party after the wedding."],
    cloze: "Let's ___ a party when you finish your degree.",
    clozeAnswer: "throw",
    collocations: ["throw a party", "have a party", "throw a surprise party"],
    band: 3,
    tags: ["collocation"],
    accept: ["have"],
    trap: "'לעשות מסיבה' = throw / have a party, לא make a party.",
    colloc: { frame: "My friends ___ a surprise party for me.", answer: "threw", options: ["threw", "made", "did"], whyHe: "עושים מסיבה = throw a party." },
  },
  // ----- adjective + noun
  {
    id: "v-cl-heavy-rain",
    word: "heavy rain",
    pos: "phr",
    he: "גשם כבד, גשם חזק",
    def: "a lot of rain falling hard",
    examples: ["Heavy rain is expected tonight in the north.", "The road was closed because of heavy rain."],
    cloze: "There was ___ rain all night, and the street flooded.",
    clozeAnswer: "heavy",
    collocations: ["heavy rain", "heavy snow", "it's raining heavily"],
    band: 3,
    tags: ["collocation"],
    trap: "'גשם חזק' = heavy rain, לא strong rain. גם heavy snow.",
    colloc: { frame: "The match was stopped because of ___ rain.", answer: "heavy", options: ["heavy", "strong", "big"], whyHe: "גשם חזק = heavy rain." },
  },
  {
    id: "v-cl-heavy-traffic",
    word: "heavy traffic",
    pos: "phr",
    he: "עומס תנועה, פקקים",
    def: "many cars on the road, moving slowly",
    examples: ["There's heavy traffic on the highway this morning.", "We were late because of heavy traffic."],
    cloze: "Leave early, there's usually ___ traffic near the airport.",
    clozeAnswer: "heavy",
    collocations: ["heavy traffic", "stuck in traffic", "a traffic jam"],
    band: 3,
    tags: ["collocation"],
    trap: "'עומס תנועה' = heavy traffic, לא big / strong traffic. 'פקק' = a traffic jam.",
    colloc: { frame: "I got stuck in ___ traffic for an hour.", answer: "heavy", options: ["heavy", "big", "strong"], whyHe: "תנועה כבדה = heavy traffic." },
  },
  {
    id: "v-cl-strong-coffee",
    word: "strong coffee",
    pos: "phr",
    he: "קפה חזק",
    def: "coffee with a lot of flavor and caffeine",
    examples: ["I need a cup of strong coffee to wake up.", "Turkish coffee is very strong."],
    cloze: "This coffee is too ___ for me, can I have some milk?",
    clozeAnswer: "strong",
    collocations: ["strong coffee", "strong tea", "weak coffee"],
    band: 1,
    tags: ["collocation"],
    trap: "'קפה חזק' = strong coffee. ההפך: weak coffee, לא light coffee.",
    colloc: { frame: "He drinks three cups of ___ coffee every morning.", answer: "strong", options: ["strong", "hard", "heavy"], whyHe: "קפה חזק = strong coffee." },
  },
  {
    id: "v-cl-fast-food",
    word: "fast food",
    pos: "phr",
    he: "מזון מהיר",
    def: "food like burgers and fries that is made and served quickly",
    examples: ["We ate fast food on the road because we were in a hurry.", "Too much fast food isn't good for you."],
    cloze: "The kids want ___ food, but I'd rather cook.",
    clozeAnswer: "fast",
    collocations: ["fast food", "a fast food restaurant", "junk food"],
    band: 1,
    tags: ["collocation"],
    trap: "'מזון מהיר' = fast food, לא quick food.",
    colloc: { frame: "There's a ___ food place next to the station.", answer: "fast", options: ["fast", "quick", "rapid"], whyHe: "מזון מהיר = fast food." },
  },
  {
    id: "v-cl-high-price",
    word: "high price",
    pos: "phr",
    he: "מחיר גבוה",
    def: "a price that costs a lot of money",
    examples: ["Apartments in Tel Aviv have very high prices.", "They paid a high price for the tickets."],
    cloze: "The ___ price of housing is a big problem here.",
    clozeAnswer: "high",
    collocations: ["high price", "low price", "prices go up"],
    band: 3,
    tags: ["collocation"],
    trap: "מחיר הוא high או low, לא expensive / cheap. הדבר עצמו הוא expensive.",
    colloc: { frame: "I didn't buy the phone because of the ___ price.", answer: "high", options: ["high", "expensive", "big"], whyHe: "מחיר גבוה = high price. expensive מתאר את המוצר." },
  },
  {
    id: "v-cl-big-mistake",
    word: "big mistake",
    pos: "phr",
    he: "טעות גדולה",
    def: "a serious mistake",
    examples: ["Selling the car was a big mistake.", "It would be a big mistake to quit now."],
    cloze: "Leaving without a map was a ___ mistake.",
    clozeAnswer: "big",
    collocations: ["big mistake", "serious mistake", "small mistake"],
    band: 3,
    tags: ["collocation"],
    trap: "'טעות גדולה' = big mistake, לא large / great mistake.",
    colloc: { frame: "Trusting him was a ___ mistake.", answer: "big", options: ["big", "large", "high"], whyHe: "טעות גדולה = big mistake." },
  },
  {
    id: "v-cl-deep-sleep",
    word: "deep sleep",
    pos: "phr",
    he: "שינה עמוקה",
    def: "a sleep from which it is hard to wake someone",
    examples: ["The baby fell into a deep sleep after the bath.", "I was in such a deep sleep that I didn't hear the alarm."],
    cloze: "After the long hike, he fell into a ___ sleep.",
    clozeAnswer: "deep",
    collocations: ["deep sleep", "fall asleep", "sleep deeply"],
    band: 3,
    tags: ["collocation"],
    trap: "'שינה עמוקה' = deep sleep. 'להירדם' = fall asleep, לא fall to sleep.",
    colloc: { frame: "The noise didn't wake her, she was in a ___ sleep.", answer: "deep", options: ["deep", "heavy", "strong"], whyHe: "שינה עמוקה = deep sleep." },
  },
  {
    id: "v-cl-hard-work",
    word: "hard work",
    pos: "phr",
    he: "עבודה קשה",
    def: "work that needs a lot of effort",
    examples: ["Learning a language is hard work.", "Her success came from years of hard work."],
    cloze: "It took a lot of ___ work to open the cafe.",
    clozeAnswer: "hard",
    collocations: ["hard work", "work hard", "a hard worker"],
    band: 3,
    tags: ["collocation"],
    trap: "'עבודה קשה' = hard work, לא heavy / difficult work. 'לעבוד קשה' = work hard (לא hardly).",
    colloc: { frame: "Building the house was ___ work, but worth it.", answer: "hard", options: ["hard", "heavy", "strong"], whyHe: "עבודה קשה = hard work." },
  },
  {
    id: "v-cl-close-friend",
    word: "close friend",
    pos: "phr",
    he: "חבר קרוב",
    def: "a friend you know very well and trust",
    examples: ["She's a close friend from the army.", "I only invited close friends and family."],
    cloze: "He's a ___ friend, we talk almost every day.",
    clozeAnswer: "close",
    collocations: ["close friend", "best friend", "old friend"],
    band: 3,
    tags: ["collocation"],
    trap: "'חבר קרוב' = close friend, לא near friend. close = קרוב (רגשית).",
    colloc: { frame: "Only a few ___ friends know about the plan.", answer: "close", options: ["close", "near", "strong"], whyHe: "חבר קרוב = close friend." },
  },
  {
    id: "v-cl-wide-range",
    word: "wide range",
    pos: "phr",
    he: "מגוון רחב",
    def: "a large number of different things",
    examples: ["The store sells a wide range of shoes.", "We discussed a wide range of topics."],
    cloze: "The hotel offers a ___ range of activities for kids.",
    clozeAnswer: "wide",
    collocations: ["a wide range of", "a wide variety of", "a wide choice"],
    band: 4,
    tags: ["collocation"],
    accept: ["broad"],
    trap: "'מגוון רחב של' = a wide range of, לא big / large range.",
    colloc: { frame: "They have a ___ range of vegetarian dishes.", answer: "wide", options: ["wide", "big", "long"], whyHe: "מגוון רחב = wide range." },
  },

  // ---------------------------------------------------------------- Part B: false friends & interference
  {
    id: "v-cl-actually",
    word: "actually",
    pos: "adv",
    he: "למעשה, בעצם",
    def: "used to say what is really true, often to correct something",
    examples: ["I thought he was Italian, but actually he's Spanish.", "Actually, I've never been to Eilat."],
    cloze: "It looks expensive, but ___ it was pretty cheap.",
    collocations: ["actually, ...", "what actually happened", "not actually"],
    band: 1,
    tags: ["trap"],
    trap: "actually ≠ 'אקטואלי'. actually = בעצם / למעשה. 'אקטואלי' = current, topical.",
    colloc: { frame: "___, the meeting is on Tuesday, not Monday.", answer: "Actually", options: ["Actually", "Currently", "Eventually"], whyHe: "בעצם / למעשה = actually." },
  },
  {
    id: "v-cl-eventually",
    word: "eventually",
    pos: "adv",
    he: "בסופו של דבר",
    def: "in the end, after a long time or many problems",
    examples: ["The traffic was terrible, but we eventually got home.", "He eventually agreed to sell the car."],
    cloze: "It took years, but she ___ finished her degree.",
    collocations: ["eventually found", "eventually became", "will eventually"],
    band: 2,
    tags: ["trap"],
    trap: "eventually ≠ 'אולי' / 'אוונטואלי'. eventually = בסופו של דבר. 'אולי' = maybe, possibly.",
    colloc: { frame: "After many tries, they ___ found a parking spot.", answer: "eventually", options: ["eventually", "possibly", "actually"], whyHe: "בסופו של דבר = eventually." },
  },
  {
    id: "v-cl-sympathetic",
    word: "sympathetic",
    pos: "adj",
    he: "מבין, מגלה אהדה",
    def: "kind and understanding about someone's problems",
    examples: ["My boss was very sympathetic when I explained the problem.", "She gave me a sympathetic smile."],
    cloze: "The nurse was ___ and listened to all my worries.",
    collocations: ["a sympathetic ear", "sympathetic to", "sympathetic toward"],
    band: 3,
    tags: ["trap"],
    trap: "sympathetic ≠ 'סימפטי'. sympathetic = מבין, אוהד, מגלה אהדה. אדם סימפטי = nice, likable, friendly.",
    colloc: { frame: "He's such a ___ guy, everyone likes him right away.", answer: "likable", options: ["likable", "sympathetic", "symbolic"], whyHe: "'סימפטי' = likable / nice. sympathetic = מבין את הצרות שלך." },
  },
  {
    id: "v-cl-control",
    word: "control",
    pos: "v",
    he: "לשלוט, לפקח",
    def: "to have the power to decide what something or someone does",
    examples: ["The teacher couldn't control the noisy class.", "This button controls the temperature."],
    cloze: "He can't ___ his temper when he's tired.",
    collocations: ["control yourself", "control the situation", "lose control"],
    band: 2,
    tags: ["trap"],
    trap: "control = לשלוט / לפקח, לא 'לבדוק'. 'לבדוק מבחן' = check / grade a test, לא control.",
    colloc: { frame: "Can you ___ if the door is locked?", answer: "check", options: ["check", "control", "test"], whyHe: "לבדוק = check. control = לשלוט." },
  },
  {
    id: "v-cl-sensible",
    word: "sensible",
    pos: "adj",
    he: "הגיוני, שקול",
    def: "showing good judgment; practical",
    examples: ["Bringing an umbrella was a sensible idea.", "She's very sensible with money."],
    cloze: "It's ___ to book the hotel early in summer.",
    collocations: ["a sensible decision", "sensible shoes", "be sensible"],
    band: 3,
    tags: ["trap"],
    trap: "sensible = הגיוני, שקול. לא 'רגיש' (זה sensitive) ולא 'סנסציוני'.",
    colloc: { frame: "Saving money each month is a ___ plan.", answer: "sensible", options: ["sensible", "sensitive", "sensual"], whyHe: "הגיוני = sensible. רגיש = sensitive." },
  },
  {
    id: "v-cl-sensitive",
    word: "sensitive",
    pos: "adj",
    he: "רגיש",
    def: "easily hurt or affected by things; needing care",
    examples: ["My skin is very sensitive to the sun.", "Be careful, he's sensitive about his weight."],
    cloze: "This is a ___ topic, so choose your words carefully.",
    collocations: ["sensitive skin", "sensitive to", "a sensitive subject"],
    band: 2,
    tags: ["trap"],
    trap: "sensitive = רגיש. sensible = הגיוני. 'ילד רגיש' = a sensitive child, לא sensible.",
    colloc: { frame: "She has ___ teeth and can't eat ice cream.", answer: "sensitive", options: ["sensitive", "sensible", "sensational"], whyHe: "רגיש = sensitive." },
  },
  {
    id: "v-cl-nervous",
    word: "nervous",
    pos: "adj",
    he: "לחוץ, חרד",
    def: "worried and a little afraid about something that will happen",
    examples: ["I always feel nervous before a job interview.", "She was nervous about the exam results."],
    cloze: "He gets ___ when he has to speak in public.",
    collocations: ["nervous about", "feel nervous", "a nervous smile"],
    band: 1,
    tags: ["trap"],
    trap: "nervous = לחוץ, חרד (לפני מבחן). לא 'עצבני'! עצבני = angry, annoyed, irritated.",
    colloc: { frame: "The boss was really ___ when we came late again.", answer: "angry", options: ["angry", "nervous", "excited"], whyHe: "עצבני = angry / annoyed. nervous = לחוץ." },
  },
  {
    id: "v-cl-excited",
    word: "excited",
    pos: "adj",
    he: "נרגש, מלא ציפייה",
    def: "very happy and looking forward to something",
    examples: ["The kids are so excited about the trip to the zoo.", "I'm excited to start my new job."],
    cloze: "We're really ___ about moving to the new apartment.",
    collocations: ["excited about", "excited to do", "get excited"],
    band: 1,
    tags: ["trap"],
    trap: "excited = נרגש בציפייה חיובית. 'מתרגש' במובן נסער / מודאג = upset. וגם: excited about, לא excited from.",
    colloc: { frame: "She's ___ about her birthday party tomorrow.", answer: "excited", options: ["excited", "exciting", "upset"], whyHe: "נרגש = excited (about). exciting = מרגש (הדבר עצמו)." },
  },
  {
    id: "v-cl-check",
    word: "check",
    pos: "v",
    he: "לבדוק",
    def: "to look at something to see if it is correct or okay",
    examples: ["Let me check my calendar and get back to you.", "Did you check the tickets before we left?"],
    cloze: "Always ___ your answers before you hand in the test.",
    collocations: ["check your email", "check if", "double-check"],
    band: 1,
    tags: ["trap"],
    trap: "לבדוק = check, לא control. 'לבדוק את המבחן' = check / grade the test. control = לשלוט.",
    colloc: { frame: "I'll ___ the weather before we go to the beach.", answer: "check", options: ["check", "control", "examine"], whyHe: "בודקים = check." },
  },
  {
    id: "v-cl-chef",
    word: "chef",
    pos: "n",
    he: "שף, טבח ראשי",
    def: "a professional cook, usually the head cook in a restaurant",
    examples: ["The chef at this restaurant trained in Paris.", "She wants to be a chef one day."],
    cloze: "The ___ came out of the kitchen to say hello.",
    collocations: ["head chef", "chef's special", "a famous chef"],
    band: 2,
    tags: ["trap"],
    trap: "chef = שף, טבח ראשי (הגייה: 'שף'). chief = ראש, מנהל (הגייה: 'צ'יף'): chief of police.",
    colloc: { frame: "The ___ of police spoke to the reporters.", answer: "chief", options: ["chief", "chef", "boss"], whyHe: "ראש / מפקד = chief. chef = שף." },
  },
  {
    id: "v-cl-library",
    word: "library",
    pos: "n",
    he: "ספרייה",
    def: "a place where you can borrow books to read",
    examples: ["I returned the books to the library this morning.", "The city library is open until nine."],
    cloze: "Students study at the ___ because it's quiet.",
    collocations: ["public library", "school library", "borrow from the library"],
    band: 1,
    tags: ["trap"],
    trap: "library = ספרייה (משאילים ספרים). חנות ספרים = bookstore. לא אומרים library על חנות.",
    colloc: { frame: "I bought this novel at a ___ near the station.", answer: "bookstore", options: ["bookstore", "library", "bibliotheque"], whyHe: "חנות ספרים = bookstore. library = ספרייה." },
  },
  {
    id: "v-cl-receipt",
    word: "receipt",
    pos: "n",
    he: "קבלה",
    def: "a piece of paper showing that you paid for something",
    examples: ["Keep the receipt in case you want to return the shirt.", "Can I have a receipt, please?"],
    cloze: "You can't return it without the ___.",
    collocations: ["keep the receipt", "get a receipt", "a receipt for"],
    band: 2,
    tags: ["trap"],
    trap: "receipt = קבלה (הגייה: 'ריסיט', ה-p שקטה). recipe = מתכון (הגייה: 'רסיפי').",
    colloc: { frame: "This cake ___ needs three eggs and some butter.", answer: "recipe", options: ["recipe", "receipt", "reception"], whyHe: "מתכון = recipe. קבלה = receipt." },
  },
  {
    id: "v-cl-fabric",
    word: "fabric",
    pos: "n",
    he: "בד",
    def: "cloth used for making clothes, curtains, etc.",
    examples: ["This fabric is soft, perfect for a baby blanket.", "The dress is made of a light cotton fabric."],
    cloze: "She bought two meters of blue ___ for curtains.",
    collocations: ["cotton fabric", "soft fabric", "a piece of fabric"],
    band: 3,
    tags: ["trap"],
    trap: "fabric = בד, לא 'פבריקה'. מפעל = factory.",
    colloc: { frame: "My father worked in a car ___ for thirty years.", answer: "factory", options: ["factory", "fabric", "fabrication"], whyHe: "מפעל = factory. fabric = בד." },
  },
  {
    id: "v-cl-novel",
    word: "novel",
    pos: "n",
    he: "רומן (ספר)",
    def: "a long story in a book about invented people and events",
    examples: ["I'm reading a novel about a family in Jerusalem.", "Her first novel became a bestseller."],
    cloze: "It's a long ___, almost 600 pages.",
    collocations: ["read a novel", "write a novel", "a historical novel"],
    band: 2,
    tags: ["trap"],
    trap: "novel = רומן (ספר עלילתי ארוך), לא 'נובלה'. נובלה (סיפור קצר) = novella. 'רומן' במובן רומנטי = romance / affair.",
  },
  {
    id: "v-cl-physician",
    word: "physician",
    pos: "n",
    he: "רופא",
    def: "a medical doctor",
    examples: ["You should see a physician about that cough.", "Her father is a physician at Ichilov."],
    cloze: "The ___ examined the patient and wrote a prescription.",
    collocations: ["family physician", "consult a physician", "a licensed physician"],
    band: 4,
    tags: ["trap"],
    trap: "physician = רופא (מילה רשמית ל-doctor). physicist = פיזיקאי. physics = פיזיקה.",
    colloc: { frame: "Einstein was a famous ___.", answer: "physicist", options: ["physicist", "physician", "physical"], whyHe: "פיזיקאי = physicist. רופא = physician." },
  },
  {
    id: "v-cl-argument",
    word: "argument",
    pos: "n",
    he: "ריב, ויכוח; טיעון",
    def: "an angry disagreement; also a reason for or against something",
    examples: ["We had a big argument about who should pay.", "There's a strong argument for taking the train."],
    cloze: "They had an ___ and didn't speak for a week.",
    collocations: ["have an argument", "get into an argument", "a strong argument"],
    band: 2,
    tags: ["trap"],
    trap: "argument = בעיקר ריב / ויכוח (have an argument), לא רק 'ארגומנט' (טיעון). 'רבנו' = we had an argument.",
  },
  {
    id: "v-cl-cabinet",
    word: "cabinet",
    pos: "n",
    he: "ארון (מטבח / אמבטיה)",
    def: "a cupboard with shelves or drawers for storing things",
    examples: ["The cups are in the cabinet above the sink.", "Keep the medicine in the bathroom cabinet."],
    cloze: "Put the plates back in the kitchen ___.",
    collocations: ["kitchen cabinet", "bathroom cabinet", "filing cabinet"],
    band: 4,
    tags: ["trap"],
    trap: "cabinet = ארון (kitchen cabinet). המשמעות 'קבינט' (ממשלה) קיימת, אבל ביומיום cabinet = ארון. 'ארון בגדים' = closet / wardrobe.",
  },
  {
    id: "v-cl-chips",
    word: "chips",
    pos: "n",
    he: "חטיף תפוצ'יפס (בארה\"ב)",
    def: "thin, crispy slices of fried potato sold in bags (US)",
    examples: ["I bought a bag of chips to eat with my sandwich.", "Do you want fries or chips with your burger?"],
    cloze: "He opened a bag of ___ and watched the game.",
    collocations: ["a bag of chips", "potato chips", "chips and dip"],
    band: 1,
    tags: ["trap"],
    trap: "בארה\"ב chips = תפוצ'יפס (חטיף). 'צ'יפס' חם מהמסעדה = fries / French fries. בבריטניה chips = צ'יפס.",
    colloc: { frame: "I'll have a burger with ___, please.", answer: "fries", options: ["fries", "chips", "crisps"], whyHe: "צ'יפס (בארה\"ב) = fries. chips = חטיף." },
  },
  {
    id: "v-cl-suit",
    word: "suit",
    pos: "n",
    he: "חליפה",
    def: "a jacket and pants (or skirt) made from the same cloth",
    examples: ["He wore a dark suit and a tie to the interview.", "She looks great in that gray suit."],
    cloze: "Do I need to wear a ___ to the wedding?",
    collocations: ["a suit and tie", "wear a suit", "a business suit"],
    band: 2,
    tags: ["trap"],
    trap: "חליפה = suit. dress = שמלה בלבד, גבר לא לובש dress. 'להתלבש' = get dressed.",
    colloc: { frame: "She bought a red ___ for the party.", answer: "dress", options: ["dress", "suit", "costume"], whyHe: "שמלה = dress. חליפה = suit. costume = תחפושת." },
  },
  {
    id: "v-cl-grade",
    word: "grade",
    pos: "n",
    he: "ציון",
    def: "a number or letter that shows how good your work is (US)",
    examples: ["She got a good grade on her history test.", "My grades improved this year."],
    cloze: "What ___ did you get on the math exam?",
    collocations: ["get a good grade", "a high grade", "grades"],
    band: 1,
    tags: ["trap"],
    trap: "ציון בארה\"ב = grade (get a good grade). mark = בריטי. לא 'note'. grade = גם כיתה (third grade).",
  },
  {
    id: "v-cl-lecture",
    word: "lecture",
    pos: "n",
    he: "הרצאה",
    def: "a talk given to a group, especially at a university",
    examples: ["The professor's lecture on history was two hours long.", "I have a lecture at ten and then lunch."],
    cloze: "I fell asleep during the ___ on economics.",
    collocations: ["give a lecture", "attend a lecture", "a lecture on"],
    band: 2,
    tags: ["trap"],
    trap: "lecture = הרצאה (באוניברסיטה, בכנס). lesson = שיעור (בבית ספר, שיעור פרטי). class = שיעור / קורס.",
    colloc: { frame: "My son has a piano ___ every Tuesday.", answer: "lesson", options: ["lesson", "lecture", "course"], whyHe: "שיעור = lesson. הרצאה = lecture." },
  },
  {
    id: "v-cl-advice",
    word: "advice",
    pos: "n",
    he: "עצה, עצות",
    def: "what you tell someone they should do",
    examples: ["Can I give you some advice about your resume?", "She asked her father for advice."],
    cloze: "Let me give you a piece of ___: don't sign yet.",
    collocations: ["a piece of advice", "give advice", "take someone's advice"],
    band: 1,
    tags: ["trap"],
    trap: "advice לא ניתן לספירה: לא 'an advice' ולא 'advices'. עצה אחת = a piece of advice; עצות = some advice. הפועל = advise.",
    colloc: { frame: "He gave me ___ about buying a car.", answer: "some advice", options: ["some advice", "an advice", "advices"], whyHe: "advice ללא a וללא s." },
  },
  {
    id: "v-cl-information",
    word: "information",
    pos: "n",
    he: "מידע",
    def: "facts or details about something",
    examples: ["The website has a lot of useful information about visas.", "I need more information before I decide."],
    cloze: "Where can I find ___ about the bus schedule?",
    collocations: ["a piece of information", "useful information", "information about"],
    band: 1,
    tags: ["trap"],
    trap: "information לא ניתן לספירה: לא 'informations', לא 'an information'. פיסת מידע = a piece of information.",
    colloc: { frame: "They sent us ___ about the course.", answer: "some information", options: ["some information", "an information", "informations"], whyHe: "information תמיד ביחיד, בלי a." },
  },
  {
    id: "v-cl-furniture",
    word: "furniture",
    pos: "n",
    he: "רהיטים, ריהוט",
    def: "things like tables, chairs, and beds in a room",
    examples: ["We bought new furniture for the living room.", "The apartment comes with furniture."],
    cloze: "The room was empty, there was no ___ at all.",
    collocations: ["a piece of furniture", "office furniture", "furniture store"],
    band: 2,
    tags: ["trap"],
    trap: "furniture לא ניתן לספירה: לא 'furnitures', לא 'a furniture'. רהיט אחד = a piece of furniture.",
    colloc: { frame: "We need to buy ___ for the new apartment.", answer: "some furniture", options: ["some furniture", "furnitures", "a furniture"], whyHe: "furniture תמיד ביחיד, בלי a." },
  },
  {
    id: "v-cl-news",
    word: "news",
    pos: "n",
    he: "חדשות, ידיעה",
    def: "new information about recent events",
    examples: ["Have you heard the news about the new mall?", "The news is on at eight."],
    cloze: "I have some good ___: I got the job!",
    collocations: ["good news", "bad news", "a piece of news"],
    band: 1,
    tags: ["trap"],
    trap: "news הוא יחיד: The news is good, לא 'are'. ידיעה אחת = a piece of news / some news, לא 'a news'.",
    colloc: { frame: "The ___ about the strike was a surprise to everyone.", answer: "news was", options: ["news was", "news were", "new was"], whyHe: "news + פועל ביחיד." },
  },
  {
    id: "v-cl-people",
    word: "people",
    pos: "n",
    he: "אנשים",
    def: "men, women, and children; more than one person",
    examples: ["Most people in my office speak Hebrew.", "There were a lot of people at the concert."],
    cloze: "Many ___ are waiting outside the clinic.",
    collocations: ["a lot of people", "most people", "young people"],
    band: 1,
    tags: ["trap"],
    trap: "people הוא רבים: people are, לא 'people is'. אדם אחד = a person. לא 'peoples' (זה עמים).",
    colloc: { frame: "___ very friendly in this town.", answer: "People are", options: ["People are", "People is", "The people is"], whyHe: "people + פועל ברבים." },
  },
  {
    id: "v-cl-police",
    word: "police",
    pos: "n",
    he: "משטרה",
    def: "the people whose job is to keep order and catch criminals",
    examples: ["The police are looking for the driver.", "Somebody called the police after the fight."],
    cloze: "The ___ arrived five minutes after the alarm.",
    collocations: ["call the police", "police officer", "police station"],
    band: 2,
    tags: ["trap"],
    trap: "police הוא רבים: The police are here, לא 'is'. שוטר אחד = a police officer, לא 'a police'.",
    colloc: { frame: "The police ___ investigating the accident.", answer: "are", options: ["are", "is", "was"], whyHe: "police + פועל ברבים." },
  },
  {
    id: "v-cl-years-old",
    word: "years old",
    pos: "phr",
    he: "בן / בת (גיל)",
    def: "used with 'be' to say someone's age",
    examples: ["My daughter is six years old.", "He's 40 years old and still plays soccer."],
    cloze: "My brother is 25 ___ and lives in Berlin.",
    collocations: ["be 30 years old", "a six-year-old boy", "How old are you?"],
    band: 1,
    tags: ["trap"],
    trap: "גיל באנגלית עם be: I am 30 (years old), לא 'I have 30 years'. שאלה: How old are you?, לא 'How much years'.",
    colloc: { frame: "___ 32 years old next month.", answer: "I'll be", options: ["I'll be", "I'll have", "I have"], whyHe: "גיל = be, לא have." },
  },
  {
    id: "v-cl-teach",
    word: "teach",
    pos: "v",
    he: "ללמד",
    def: "to give lessons or show someone how to do something",
    examples: ["My mother used to teach math at a high school.", "Can you teach me how to swim?"],
    cloze: "He wants to ___ English in Japan next year.",
    collocations: ["teach someone to do", "teach math", "teach a class"],
    band: 1,
    tags: ["trap"],
    trap: "ללמד (מורה) = teach (taught). ללמוד = learn / study. 'המורה לימדה אותנו' = taught us, לא learned us.",
    colloc: { frame: "My grandfather ___ me how to fish.", answer: "taught", options: ["taught", "learned", "studied"], whyHe: "לימד אותי = taught me. learned = למד." },
  },
  {
    id: "v-cl-study",
    word: "study",
    pos: "v",
    he: "ללמוד (בפועל, למבחן)",
    def: "to spend time learning about a subject, from books or in a course",
    examples: ["I have to study for my exam tonight.", "She studied law at Tel Aviv University."],
    cloze: "Where did you ___ engineering?",
    collocations: ["study for a test", "study medicine", "study hard"],
    band: 2,
    tags: ["trap"],
    trap: "study = ללמוד באופן פעיל (לשבת וללמוד, ללמוד מקצוע). learn = לרכוש ידע / מיומנות. 'אני לומד למבחן' = I'm studying, לא learning.",
    colloc: { frame: "I can't go out, I'm ___ for a test.", answer: "studying", options: ["studying", "learning", "teaching"], whyHe: "לומד למבחן = studying." },
  },
  {
    id: "v-cl-remind",
    word: "remind",
    pos: "v",
    he: "להזכיר (למישהו)",
    def: "to make someone remember something",
    examples: ["Can you remind me to call the bank tomorrow?", "This song reminds me of my childhood."],
    cloze: "Please ___ me to buy milk on the way home.",
    collocations: ["remind someone to do", "remind someone of", "reminder"],
    band: 2,
    tags: ["trap"],
    trap: "remind = להזכיר למישהו (remind me to call). remember = לזכור בעצמך. לא 'remember me to...'.",
    colloc: { frame: "Did you ___ to lock the door?", answer: "remember", options: ["remember", "remind", "recall"], whyHe: "זכרת = remember. הזכרת לי = remind me." },
  },
  {
    id: "v-cl-lend",
    word: "lend",
    pos: "v",
    he: "להשאיל, להלוות",
    def: "to give something to someone for a short time",
    examples: ["Can you lend me 50 shekels until Sunday?", "I lent him my car for the weekend."],
    cloze: "Could you ___ me your charger for an hour?",
    collocations: ["lend someone money", "lend a hand", "lend something to"],
    band: 2,
    tags: ["trap"],
    trap: "lend = להשאיל (לתת). borrow = לשאול (לקחת). Can you lend me a pen? = Can I borrow a pen? לא 'borrow me'.",
    colloc: { frame: "Can I ___ your umbrella? It's raining.", answer: "borrow", options: ["borrow", "lend", "loan"], whyHe: "לשאול ממישהו = borrow. להשאיל = lend." },
  },
  {
    id: "v-cl-borrow",
    word: "borrow",
    pos: "v",
    he: "לשאול, ללוות",
    def: "to take and use something you will give back later",
    examples: ["Can I borrow your pen for a second?", "She borrowed money from the bank to buy a car."],
    cloze: "I ___ this book from the library last week.",
    clozeAnswer: "borrowed",
    collocations: ["borrow from", "borrow money", "borrow a book"],
    band: 2,
    tags: ["trap"],
    trap: "borrow = לשאול / ללוות (לקחת). borrow something from someone. לא 'borrow me' — להשאיל = lend me.",
    colloc: { frame: "The bank ___ us the money for the apartment.", answer: "lent", options: ["lent", "borrowed", "took"], whyHe: "הבנק הלווה לנו = lent. borrowed = לווינו." },
  },
  {
    id: "v-cl-tell",
    word: "tell",
    pos: "v",
    he: "לספר, להגיד ל-",
    def: "to give information to a person",
    examples: ["Please tell me what happened at the meeting.", "He told us a funny story."],
    cloze: "Did you ___ your parents about the trip?",
    collocations: ["tell someone something", "tell the truth", "tell a story"],
    band: 2,
    tags: ["trap"],
    trap: "tell + מישהו (tell me). say + משהו (say something / say to me). לא 'say me' ולא 'tell to me'.",
    colloc: { frame: "She ___ that she was tired.", answer: "said", options: ["said", "told", "spoke"], whyHe: "בלי מושא ישיר (מישהו) = said. told me that = עם מישהו." },
  },
  {
    id: "v-cl-listen",
    word: "listen",
    pos: "v",
    he: "להקשיב",
    def: "to pay attention to a sound or to what someone says",
    examples: ["I like to listen to podcasts on the way to work.", "Listen carefully, I'll say it only once."],
    cloze: "Do you ___ to music while you work?",
    collocations: ["listen to music", "listen to someone", "listen carefully"],
    band: 3,
    tags: ["trap"],
    trap: "listen to = להקשיב (בכוונה), תמיד עם to. hear = לשמוע (בלי כוונה). listen to music, לא listen music.",
    colloc: { frame: "Did you ___ that noise outside?", answer: "hear", options: ["hear", "listen", "listen to"], whyHe: "שמעת (בלי כוונה) = hear. listen to = להקשיב." },
  },
  {
    id: "v-cl-watch",
    word: "watch",
    pos: "v",
    he: "לצפות ב-",
    def: "to look at something for a period of time, like a film or game",
    examples: ["We stayed home to watch the game on TV.", "I watched the kids play in the yard."],
    cloze: "Let's ___ a movie tonight.",
    collocations: ["watch TV", "watch a movie", "watch a game"],
    band: 3,
    tags: ["trap"],
    trap: "watch = לצפות (בסרט, במשחק, בטלוויזיה). see = לראות. look at = להסתכל על. watch TV, לא see TV; look at the picture.",
    colloc: { frame: "___ at this photo, isn't it beautiful?", answer: "Look", options: ["Look", "Watch", "See"], whyHe: "תסתכל על = look at. watch = לצפות. see = לראות." },
  },
  {
    id: "v-cl-funny",
    word: "funny",
    pos: "adj",
    he: "מצחיק",
    def: "making you laugh",
    examples: ["That movie was so funny that I couldn't stop laughing.", "He tells the funniest stories."],
    cloze: "The clown was really ___ and the kids loved him.",
    collocations: ["a funny story", "really funny", "funny joke"],
    band: 3,
    tags: ["trap"],
    trap: "funny = מצחיק. fun = כיף (שם עצם / תואר). 'היה כיף' = It was fun, לא It was funny.",
    colloc: { frame: "The trip was a lot of ___, we should go again.", answer: "fun", options: ["fun", "funny", "funs"], whyHe: "כיף = fun. funny = מצחיק." },
  },
  {
    id: "v-cl-lonely",
    word: "lonely",
    pos: "adj",
    he: "בודד (מרגיש לבד)",
    def: "sad because you have no friends or company",
    examples: ["She felt lonely after her friends moved away.", "The first months in the new city were lonely."],
    cloze: "He was ___ in the big city and missed his family.",
    collocations: ["feel lonely", "a lonely place", "lonely and sad"],
    band: 3,
    tags: ["trap"],
    trap: "lonely = בודד (רגש שלילי). alone = לבד (עובדה, לא רגש). אפשר להיות alone ולא lonely: I live alone, but I'm not lonely.",
    colloc: { frame: "I like traveling ___, it's more relaxing.", answer: "alone", options: ["alone", "lonely", "only"], whyHe: "לבד (עובדה) = alone. lonely = מרגיש בודד." },
  },
  {
    id: "v-cl-hardly",
    word: "hardly",
    pos: "adv",
    he: "בקושי, כמעט לא",
    def: "almost not",
    examples: ["I was so tired I could hardly keep my eyes open.", "We hardly ever go out on weekdays."],
    cloze: "He spoke so quietly that I could ___ hear him.",
    collocations: ["hardly ever", "can hardly", "hardly any"],
    band: 3,
    tags: ["trap"],
    trap: "hardly = בקושי, כמעט לא. hard = קשה / חזק, וגם כתואר-פועל: work hard. 'עבדתי קשה' = worked hard, לא hardly!",
    colloc: { frame: "She studied ___ and passed all her exams.", answer: "hard", options: ["hard", "hardly", "hardy"], whyHe: "למדה קשה = studied hard. hardly = בקושי." },
  },
  {
    id: "v-cl-lately",
    word: "lately",
    pos: "adv",
    he: "לאחרונה",
    def: "recently; in the last few days or weeks",
    examples: ["I haven't seen him much lately, he's been busy.", "Have you talked to Dana lately?"],
    cloze: "The weather has been strange ___, hot one day and cold the next.",
    collocations: ["lately", "haven't ... lately", "recently"],
    band: 3,
    tags: ["trap"],
    accept: ["recently"],
    trap: "lately = לאחרונה (בדרך כלל עם present perfect). late = מאוחר, גם כתואר-פועל: I arrived late. 'הגעתי מאוחר' = late, לא lately.",
    colloc: { frame: "Sorry I'm ___, the bus didn't come.", answer: "late", options: ["late", "lately", "later"], whyHe: "מאוחר = late. lately = לאחרונה." },
  },
];
