import type { VocabItem } from "@/lib/types";

export const DAILY_LIFE: VocabItem[] = [
  // ---------- Band 1 ----------
  {
    id: "v-dl-chores",
    word: "chores",
    pos: "n",
    he: "מטלות בית",
    def: "small jobs you have to do around the house",
    examples: ["I do my chores on Friday morning.", "Everyone in the family has chores."],
    cloze: "After dinner we split the ___ - I wash, he dries.",
    collocations: ["do the chores", "household chores", "split the chores"],
    band: 1,
    tags: ["home"],
    trap: "chores כמעט תמיד ברבים: a lot of chores. אומרים DO the chores, לא make the chores.",
    colloc: { frame: "I have to ___ the chores before my parents get home.", answer: "do", options: ["do", "make", "work"], whyHe: "עושים מטלות = do the chores; make = לייצר." },
  },
  {
    id: "v-dl-laundry",
    word: "laundry",
    pos: "n",
    he: "כביסה",
    def: "clothes that need washing, or clothes you have just washed",
    examples: ["There's a pile of laundry on the bed.", "I hang the laundry on the balcony."],
    cloze: "Can you take the ___ out of the machine?",
    collocations: ["do the laundry", "a load of laundry", "hang the laundry"],
    band: 1,
    tags: ["home"],
    trap: "laundry בלתי ספיר: a lot of laundry, לא many laundries. הכביסה עצמה = laundry, המכונה = washing machine.",
    colloc: { frame: "I still have to ___ the laundry before Shabbat.", answer: "do", options: ["do", "make", "put"], whyHe: "עושים כביסה = do the laundry - צירוף קבוע." },
  },
  {
    id: "v-dl-groceries",
    word: "groceries",
    pos: "n",
    he: "קניות למכולת, מצרכים",
    def: "the food and other things you buy at a supermarket",
    examples: ["I need to buy groceries on the way home.", "Can you help me carry the groceries?"],
    cloze: "The bags of ___ are still in the car.",
    collocations: ["buy groceries", "grocery store", "bag of groceries"],
    band: 1,
    tags: ["food"],
    trap: "groceries = המצרכים עצמם, תמיד ברבים. החנות = a grocery store (ביחיד, בלי s).",
    colloc: { frame: "On Sunday I ___ groceries for the whole week.", answer: "buy", options: ["buy", "make", "do"], whyHe: "buy / get groceries; אפשר גם do the shopping." },
  },
  {
    id: "v-dl-snack",
    word: "snack",
    pos: "n",
    he: "חטיף, נשנוש",
    def: "a small amount of food that you eat between meals",
    examples: ["I had a quick snack before the gym.", "She packs a snack for the kids every morning."],
    cloze: "I'm not hungry for dinner, I just want a ___.",
    collocations: ["have a snack", "grab a snack", "a healthy snack"],
    band: 1,
    tags: ["food"],
    trap: "snack ספיר: a snack, two snacks. 'לנשנש' = to snack on something: I snacked on nuts.",
    colloc: { frame: "Let's ___ a snack before the movie.", answer: "grab", options: ["grab", "take", "catch"], whyHe: "grab / have a snack = לחטוף משהו לאכול." },
  },
  {
    id: "v-dl-dessert",
    word: "dessert",
    pos: "n",
    he: "קינוח",
    def: "sweet food that you eat at the end of a meal",
    examples: ["What's for dessert?", "We had ice cream for dessert."],
    cloze: "I'm too full for ___.",
    collocations: ["for dessert", "have dessert", "skip dessert"],
    band: 1,
    tags: ["food"],
    trap: "dessert (קינוח) עם שני s, desert (מדבר) עם s אחד. 'לקינוח' = FOR dessert.",
  },
  {
    id: "v-dl-neighbor",
    word: "neighbor",
    pos: "n",
    he: "שכן",
    def: "someone who lives next to you or very near you",
    examples: ["Our neighbors are very quiet.", "I asked my neighbor to water the plants."],
    cloze: "The ___ upstairs plays music every night.",
    accept: ["neighbour"],
    collocations: ["next-door neighbor", "noisy neighbors", "the neighbors upstairs"],
    band: 1,
    tags: ["home"],
    trap: "אמריקאית neighbor, בריטית neighbour. 'השכן מלמעלה' = the neighbor upstairs, לא from above.",
  },
  {
    id: "v-dl-stairs",
    word: "stairs",
    pos: "n",
    he: "מדרגות",
    def: "steps that take you from one floor of a building to another",
    examples: ["I took the stairs instead of the elevator.", "Be careful, the stairs are slippery."],
    cloze: "The elevator was broken, so we walked up the ___.",
    collocations: ["take the stairs", "go up the stairs", "down the stairs"],
    band: 1,
    tags: ["home"],
    trap: "stairs תמיד ברבים: The stairs are steep. מדרגה בודדת = a step. 'עליתי במדרגות' = I went up the stairs.",
    colloc: { frame: "Let's ___ the stairs, it's only two floors.", answer: "take", options: ["take", "do", "make"], whyHe: "take the stairs - בדיוק כמו take the bus." },
  },
  {
    id: "v-dl-recipe",
    word: "recipe",
    pos: "n",
    he: "מתכון",
    def: "instructions that tell you how to cook a dish",
    examples: ["This soup recipe is from my grandmother.", "Send me the recipe for that cake."],
    cloze: "I followed the ___ exactly and it still burned.",
    collocations: ["follow a recipe", "a recipe for", "an easy recipe"],
    band: 1,
    tags: ["food"],
    trap: "recipe = מתכון לאוכל; prescription = מרשם מהרופא. וגם: a recipe FOR chicken soup, לא of.",
    colloc: { frame: "Just ___ the recipe and it will come out fine.", answer: "follow", options: ["follow", "do", "make"], whyHe: "עוקבים אחרי מתכון = follow a recipe." },
  },
  {
    id: "v-dl-routine",
    word: "routine",
    pos: "n",
    he: "שגרה, סדר יום",
    def: "the usual way you do things, in the same order, every day",
    examples: ["My morning routine takes about an hour.", "Small children need a routine."],
    cloze: "Since the baby was born, our whole ___ has changed.",
    collocations: ["a daily routine", "a morning routine", "stick to a routine"],
    band: 1,
    tags: ["daily"],
    trap: "routine ספיר: a daily routine (עם a). ההטעמה על ההברה השנייה: rou-TINE.",
  },
  {
    id: "v-dl-guest",
    word: "guest",
    pos: "n",
    he: "אורח",
    def: "someone you invite to your home, or someone staying at a hotel",
    examples: ["We have guests coming on Friday.", "The guest room is ready."],
    cloze: "Put out more chairs, we have six ___ tonight.",
    clozeAnswer: "guests",
    collocations: ["have guests", "a guest room", "invite guests"],
    band: 1,
    tags: ["family"],
    trap: "אורח בבית = guest; visitor הוא מבקר (במוזיאון, בבית חולים). 'קיבלנו אורחים' = We had guests over.",
  },
  {
    id: "v-dl-garbage",
    word: "garbage",
    pos: "n",
    he: "אשפה, זבל",
    def: "things you throw away because you do not want them",
    examples: ["The garbage smells, please take it out.", "He threw the box in the garbage."],
    cloze: "Don't leave the ___ next to the door all night.",
    accept: ["trash"],
    collocations: ["take out the garbage", "a garbage can", "throw it in the garbage"],
    band: 1,
    tags: ["home"],
    trap: "garbage בלתי ספיר: a lot of garbage, לא garbages. הפח עצמו = a garbage can (US) / bin (UK).",
  },
  {
    id: "v-dl-fresh",
    word: "fresh",
    pos: "adj",
    he: "טרי",
    def: "made, picked or bought a short time ago; not old",
    examples: ["I bought fresh bread this morning.", "The vegetables aren't fresh anymore."],
    cloze: "Open the window, I need some ___ air.",
    collocations: ["fresh bread", "fresh air", "fresh fruit"],
    band: 1,
    tags: ["food"],
    trap: "ההפך מ-fresh תלוי באוכל: לחם = stale, חלב = sour / off. 'אוויר צח' = fresh air.",
  },
  {
    id: "v-dl-tasty",
    word: "tasty",
    pos: "adj",
    he: "טעים",
    def: "with a good taste",
    examples: ["That was a really tasty soup.", "She made a tasty salad from the leftovers."],
    cloze: "Everything you cooked was so ___!",
    collocations: ["a tasty meal", "really tasty", "look tasty"],
    band: 1,
    tags: ["food"],
    trap: "'טעים' = tasty / delicious. לא אומרים it has taste ולא tasteful (זה 'בעל טעם אסתטי').",
  },
  {
    id: "v-dl-spicy",
    word: "spicy",
    pos: "adj",
    he: "חריף",
    def: "with a strong hot flavor from pepper or chili",
    examples: ["This curry is too spicy for me.", "I like spicy food."],
    cloze: "Careful, the sauce is very ___.",
    collocations: ["spicy food", "too spicy", "not very spicy"],
    band: 1,
    tags: ["food"],
    trap: "חריף = spicy / hot, לא sharp (sharp זה סכין). 'לא חריף' = mild.",
  },
  {
    id: "v-dl-messy",
    word: "messy",
    pos: "adj",
    he: "מבולגן",
    def: "not tidy; with things all over the place",
    examples: ["Sorry, the apartment is messy.", "His desk is always messy."],
    cloze: "The kids' room is so ___ that I can't see the floor.",
    collocations: ["a messy room", "get messy", "a messy desk"],
    band: 1,
    tags: ["home"],
    trap: "'בלאגן' = a mess (שם עצם ספיר!), messy = תואר. לא the room is mess אלא the room is a mess.",
    colloc: { frame: "My desk is such ___ mess right now.", answer: "a", options: ["a", "the", "some"], whyHe: "a mess - באנגלית 'בלאגן' הוא שם עצם ספיר." },
  },
  {
    id: "v-dl-noisy",
    word: "noisy",
    pos: "adj",
    he: "רועש",
    def: "making a lot of loud sound",
    examples: ["Our street is noisy at night.", "The neighbors upstairs are noisy."],
    cloze: "I can't sleep, the air conditioner is too ___.",
    collocations: ["noisy neighbors", "a noisy street", "noisy kids"],
    band: 1,
    tags: ["home"],
    trap: "noisy = רועש (תואר); noise = רעש (שם עצם בלתי ספיר). 'היה רעש' = There was a lot of noise.",
    colloc: { frame: "The neighbors made a lot of ___ last night.", answer: "noise", options: ["noise", "noises", "noisy"], whyHe: "noise בלתי ספיר: a lot of noise, לא noises." },
  },
  {
    id: "v-dl-broken",
    word: "broken",
    pos: "adj",
    he: "שבור, מקולקל",
    def: "damaged, so that it does not work",
    examples: ["The washing machine is broken again.", "Don't sit there, the chair is broken."],
    cloze: "We took the stairs because the elevator was ___.",
    collocations: ["a broken window", "broken elevator", "get it fixed"],
    band: 1,
    tags: ["home"],
    trap: "מכשיר שהתקלקל = broken / not working. 'המזגן התקלקל' = The AC broke down, לא was spoiled.",
  },
  {
    id: "v-dl-quiet",
    word: "quiet",
    pos: "adj",
    he: "שקט",
    def: "with little or no noise",
    examples: ["We moved to a quiet street.", "Please be quiet, the baby is sleeping."],
    cloze: "The house is so ___ when the kids are at school.",
    collocations: ["be quiet", "a quiet street", "a quiet neighborhood"],
    band: 1,
    tags: ["home"],
    trap: "quiet (שקט) לעומת quite (די, למדי) - אל תחליף ביניהם. 'תהיה בשקט' = Be quiet, לא be in quiet.",
  },
  {
    id: "v-dl-daily",
    word: "daily",
    pos: "adj",
    he: "יומי, יומיומי",
    def: "happening every day",
    examples: ["Walking is part of my daily routine.", "She takes the pills twice daily."],
    cloze: "Cooking dinner is a ___ job in our house.",
    collocations: ["a daily routine", "daily life", "on a daily basis"],
    band: 1,
    tags: ["daily"],
    trap: "daily הוא גם תואר וגם תואר הפועל: my daily routine / I check it daily. אין דבר כזה dayly.",
  },
  {
    id: "v-dl-boil",
    word: "boil",
    pos: "v",
    he: "להרתיח, לרתוח",
    def: "to heat water until it bubbles, or to cook food in bubbling water",
    examples: ["Boil the water before you add the pasta.", "I boiled two eggs for breakfast."],
    cloze: "Put the potatoes in the pot and let them ___ for twenty minutes.",
    collocations: ["boil water", "a boiled egg", "bring it to a boil"],
    band: 1,
    tags: ["food"],
    trap: "boil הוא גם 'להרתיח' וגם 'לרתוח': I boiled the water / The water is boiling. 'ביצה קשה' = a hard-boiled egg.",
  },
  {
    id: "v-dl-bake",
    word: "bake",
    pos: "v",
    he: "לאפות",
    def: "to cook bread, cakes or cookies in an oven",
    examples: ["She bakes challah every Friday.", "I am baking a cake for his birthday."],
    cloze: "My mom used to ___ cookies every Friday.",
    collocations: ["bake a cake", "bake bread", "freshly baked"],
    band: 1,
    tags: ["food"],
    trap: "bake = לאפות מאפים; בשר או ירקות בתנור = roast. 'אפיתי עוגה' = I baked a cake.",
    colloc: { frame: "She's going to ___ a cake for the party.", answer: "bake", options: ["bake", "cook", "prepare in the oven"], whyHe: "עוגה אופים = bake a cake." },
  },
  {
    id: "v-dl-fix",
    word: "fix",
    pos: "v",
    he: "לתקן",
    def: "to repair something that is broken",
    examples: ["Can you fix the door handle?", "He fixed my bike in ten minutes."],
    cloze: "The plumber came to ___ the pipe under the sink.",
    collocations: ["fix a problem", "get something fixed", "fix the sink"],
    band: 1,
    tags: ["home"],
    trap: "אם מישהו אחר תיקן בשבילך: I got it fixed, לא I fixed it. 'תיקנתי אצל טכנאי' = I had it fixed.",
    colloc: { frame: "I need to ___ the washing machine fixed this week.", answer: "get", options: ["get", "make", "do"], whyHe: "get something fixed = לדאוג שמישהו יתקן לך." },
  },
  {
    id: "v-dl-tidy-up",
    word: "tidy up",
    pos: "phr",
    he: "לסדר, לעשות סדר",
    def: "to make a place neat by putting things where they belong",
    examples: ["Let's tidy up before the guests arrive.", "I tidied up the living room in ten minutes."],
    cloze: "Give me five minutes to ___ the kitchen.",
    clozeAnswer: "tidy up",
    collocations: ["tidy up the room", "tidy up after someone", "tidy up a bit"],
    band: 1,
    tags: ["home"],
    trap: "'לעשות סדר' = tidy up / clean up, לא make order (תרגום מילולי שגוי מעברית).",
    colloc: { frame: "Can you ___ up your room before dinner?", answer: "tidy", options: ["tidy", "make", "arrange"], whyHe: "tidy up = לסדר; make order לא קיים באנגלית." },
  },
  {
    id: "v-dl-take-out-the-trash",
    word: "take out the trash",
    pos: "phr",
    he: "להוציא את הזבל",
    def: "to carry the garbage outside to the bin",
    examples: ["It's your turn to take out the trash.", "He takes out the trash every evening."],
    cloze: "Did you ___ before you left this morning?",
    clozeAnswer: "take out the trash",
    collocations: ["take out the trash", "take the trash out", "whose turn is it"],
    band: 1,
    tags: ["home"],
    trap: "'להוציא את הזבל' = take out the trash / take the trash out. לא throw the garbage (זה לזרוק משהו פנימה).",
  },
  {
    id: "v-dl-do-the-laundry",
    word: "do the laundry",
    pos: "phr",
    he: "לעשות כביסה",
    def: "to wash the clothes of the house",
    examples: ["I do the laundry on Sundays.", "Who did the laundry this week?"],
    cloze: "I can't go out tonight, I still have to ___.",
    clozeAnswer: "do the laundry",
    collocations: ["do the laundry", "a load of laundry", "sort the laundry"],
    band: 1,
    tags: ["home"],
    trap: "DO the laundry (עם do), לא make the laundry. 'לתלות כביסה' = hang the laundry.",
  },
  {
    id: "v-dl-get-dressed",
    word: "get dressed",
    pos: "phr",
    he: "להתלבש",
    def: "to put your clothes on",
    examples: ["Get dressed, we're leaving in five minutes.", "He got dressed in the dark."],
    cloze: "The kids ___ by themselves now.",
    clozeAnswer: "get dressed",
    collocations: ["get dressed quickly", "get the kids dressed", "get undressed"],
    band: 1,
    tags: ["daily"],
    trap: "get dressed = להתלבש. dress up = להתלבש יפה או להתחפש - לא אותו דבר.",
  },
  {
    id: "v-dl-make-the-bed",
    word: "make the bed",
    pos: "phr",
    he: "לסדר את המיטה",
    def: "to put the sheets and blanket in order after sleeping",
    examples: ["Make your bed before you leave.", "I never make the bed in the morning."],
    cloze: "She always ___ as soon as she wakes up.",
    clozeAnswer: "makes the bed",
    collocations: ["make the bed", "make your bed", "change the sheets"],
    band: 1,
    tags: ["home"],
    trap: "'לסדר את המיטה' = MAKE the bed, לא arrange או order the bed.",
    colloc: { frame: "Don't forget to ___ your bed.", answer: "make", options: ["make", "do", "arrange"], whyHe: "make the bed - צירוף קבוע עם make." },
  },
  {
    id: "v-dl-brush-your-teeth",
    word: "brush your teeth",
    pos: "phr",
    he: "לצחצח שיניים",
    def: "to clean your teeth with a toothbrush",
    examples: ["Brush your teeth before bed.", "He brushes his teeth twice a day."],
    cloze: "Did you ___ yet?",
    clozeAnswer: "brush your teeth",
    collocations: ["brush your teeth", "twice a day", "a toothbrush"],
    band: 1,
    tags: ["daily"],
    trap: "עם שייכות: brush YOUR teeth, brush HIS teeth - לא brush the teeth.",
  },
  {
    id: "v-dl-set-the-table",
    word: "set the table",
    pos: "phr",
    he: "לערוך שולחן",
    def: "to put plates, forks and glasses on the table before a meal",
    examples: ["Can you set the table, please?", "The kids set the table every Friday night."],
    cloze: "Dinner is almost ready - please ___.",
    clozeAnswer: "set the table",
    collocations: ["set the table", "clear the table", "set it for six"],
    band: 1,
    tags: ["home"],
    trap: "עורכים שולחן = set the table; מפנים אותו = clear the table. לא arrange the table.",
    colloc: { frame: "After we eat, we ___ the table together.", answer: "clear", options: ["clear", "empty", "tidy"], whyHe: "מפנים כלים מהשולחן = clear the table." },
  },
  {
    id: "v-dl-water-the-plants",
    word: "water the plants",
    pos: "phr",
    he: "להשקות את הצמחים",
    def: "to pour water on plants so they stay alive",
    examples: ["Can you water the plants while we're away?", "I forgot to water the plants for a week."],
    cloze: "Every Friday I ___ on the balcony.",
    clozeAnswer: "water the plants",
    collocations: ["water the plants", "water the garden", "the plants died"],
    band: 1,
    tags: ["home"],
    trap: "'להשקות' = to water - water הוא פועל שלם. לא give water to the plants.",
  },

  // ---------- Band 2 ----------
  {
    id: "v-dl-leftovers",
    word: "leftovers",
    pos: "n",
    he: "שאריות אוכל",
    def: "food from a meal that nobody ate, kept for later",
    examples: ["We had leftovers for lunch.", "Put the leftovers in the fridge."],
    cloze: "There's chicken from Friday in the fridge - eat the ___.",
    collocations: ["eat the leftovers", "leftovers from dinner", "heat up the leftovers"],
    band: 2,
    tags: ["food"],
    trap: "leftovers תמיד ברבים ותמיד על אוכל. כתואר בלי s: leftover rice, leftover soup.",
    colloc: { frame: "Don't throw it out - I'll eat the ___ tomorrow.", answer: "leftovers", options: ["leftovers", "leftover", "rests"], whyHe: "'השאריות' = the leftovers, ברבים; rests לא קיים במובן הזה." },
  },
  {
    id: "v-dl-landlord",
    word: "landlord",
    pos: "n",
    he: "בעל הדירה, המשכיר",
    def: "a person who owns a home and lets other people live in it for money",
    examples: ["Our landlord raised the rent again.", "I called the landlord about the leak."],
    cloze: "The ___ said he'll fix the boiler this week.",
    collocations: ["call the landlord", "a good landlord", "the landlord raised the rent"],
    band: 2,
    tags: ["home"],
    trap: "בעל הדירה = landlord (אישה: landlady); הדייר = the tenant. 'שכר דירה' = rent.",
    colloc: { frame: "We pay ___ to the landlord on the first of the month.", answer: "rent", options: ["rent", "a rent", "hire"], whyHe: "pay rent - בלי a. hire זה לשכור ציוד או שירות, לא דירה." },
  },
  {
    id: "v-dl-stain",
    word: "stain",
    pos: "n",
    he: "כתם",
    def: "a dirty mark that is hard to remove",
    examples: ["There's a coffee stain on my shirt.", "Wine stains are hard to get out."],
    cloze: "How do I get this ___ out of the carpet?",
    collocations: ["a coffee stain", "get a stain out", "remove a stain"],
    band: 2,
    tags: ["home"],
    trap: "כתם על בגד = stain. 'להוציא כתם' = get the stain out / remove the stain, לא take out.",
  },
  {
    id: "v-dl-ingredient",
    word: "ingredient",
    pos: "n",
    he: "מרכיב במתכון",
    def: "one of the foods you use to make a dish",
    examples: ["I'm missing one ingredient for the soup.", "Read the ingredients on the package."],
    cloze: "Mix all the dry ___ in a big bowl.",
    clozeAnswer: "ingredients",
    collocations: ["the main ingredient", "fresh ingredients", "a list of ingredients"],
    band: 2,
    tags: ["food"],
    trap: "ingredient ספיר: two ingredients. ההטעמה: in-GRE-dient.",
  },
  {
    id: "v-dl-shopping-list",
    word: "shopping list",
    pos: "n",
    he: "רשימת קניות",
    def: "a list of the things you need to buy",
    examples: ["Add milk to the shopping list.", "I always forget my shopping list at home."],
    cloze: "Write it on the ___ before you forget.",
    collocations: ["make a shopping list", "add it to the list", "on the list"],
    band: 2,
    tags: ["food"],
    trap: "עושים רשימה = MAKE a list; פריט נמצא ON the list, לא in the list.",
    colloc: { frame: "Put eggs ___ the shopping list.", answer: "on", options: ["on", "in", "to"], whyHe: "פריטים נמצאים ON the list." },
  },
  {
    id: "v-dl-closet",
    word: "closet",
    pos: "n",
    he: "ארון בגדים",
    def: "a tall cupboard or small room where you keep clothes",
    examples: ["Hang your coat in the closet.", "My closet is full of clothes I never wear."],
    cloze: "There's an extra blanket on the top shelf of the ___.",
    collocations: ["a walk-in closet", "hang it in the closet", "closet space"],
    band: 2,
    tags: ["home"],
    trap: "ארון בגדים = closet (US) / wardrobe (UK); ארון מטבח = cabinet או cupboard.",
  },
  {
    id: "v-dl-drawer",
    word: "drawer",
    pos: "n",
    he: "מגירה",
    def: "a box that slides in and out of a desk or a cupboard",
    examples: ["The forks are in the top drawer.", "She keeps her keys in a drawer by the door."],
    cloze: "Open the second ___ and take out a clean towel.",
    collocations: ["the top drawer", "open a drawer", "the sock drawer"],
    band: 2,
    tags: ["home"],
    trap: "IN the drawer (לא inside בדרך כלל). שים לב לאיות: drawer, מהפועל draw (למשוך).",
  },
  {
    id: "v-dl-sink",
    word: "sink",
    pos: "n",
    he: "כיור",
    def: "the bowl in a kitchen or bathroom where you wash things",
    examples: ["The dishes are in the sink.", "The bathroom sink is blocked."],
    cloze: "Don't leave dirty plates in the ___ overnight.",
    collocations: ["the kitchen sink", "in the sink", "a blocked sink"],
    band: 2,
    tags: ["home"],
    trap: "כיור = sink; אמבטיה = bathtub; אסלה = toilet. 'הכיור סתום' = The sink is clogged.",
  },
  {
    id: "v-dl-ceiling",
    word: "ceiling",
    pos: "n",
    he: "תקרה",
    def: "the surface above your head inside a room",
    examples: ["There's a stain on the ceiling from the leak.", "The ceilings here are very high."],
    cloze: "The light in the middle of the ___ stopped working.",
    collocations: ["a high ceiling", "a leak in the ceiling", "on the ceiling"],
    band: 2,
    tags: ["home"],
    trap: "תקרה = ceiling (מבפנים); גג = roof (מבחוץ). 'על התקרה' = on the ceiling.",
  },
  {
    id: "v-dl-blanket",
    word: "blanket",
    pos: "n",
    he: "שמיכה",
    def: "a thick cover that you put on a bed to keep warm",
    examples: ["Take another blanket, it's cold tonight.", "She fell asleep under a blanket on the couch."],
    cloze: "I woke up freezing because the ___ fell on the floor.",
    collocations: ["a warm blanket", "under the blanket", "a spare blanket"],
    band: 2,
    tags: ["home"],
    trap: "blanket = שמיכה רגילה; comforter / duvet = שמיכת פוך; sheet = סדין.",
  },
  {
    id: "v-dl-pillow",
    word: "pillow",
    pos: "n",
    he: "כרית שינה",
    def: "a soft bag that you put your head on when you sleep",
    examples: ["This pillow is too soft for me.", "Can I get another pillow?"],
    cloze: "He put a second ___ under his head.",
    collocations: ["a soft pillow", "a pillowcase", "two pillows"],
    band: 2,
    tags: ["home"],
    trap: "pillow = כרית שינה; cushion = כרית נוי בסלון. ציפית = pillowcase.",
  },
  {
    id: "v-dl-curtain",
    word: "curtain",
    pos: "n",
    he: "וילון",
    def: "a piece of cloth that hangs over a window",
    examples: ["Close the curtains, the sun is in my eyes.", "We bought new curtains for the living room."],
    cloze: "Open the ___ and let some light in.",
    clozeAnswer: "curtains",
    collocations: ["open the curtains", "close the curtains", "new curtains"],
    band: 2,
    tags: ["home"],
    trap: "וילונות בדרך כלל ברבים: the curtains. תריס = a blind או shutter.",
    colloc: { frame: "It's getting dark - can you ___ the curtains?", answer: "close", options: ["close", "shut down", "lower"], whyHe: "close / draw the curtains = לסגור וילונות." },
  },
  {
    id: "v-dl-elevator",
    word: "elevator",
    pos: "n",
    he: "מעלית",
    def: "a machine that takes people up and down inside a building",
    examples: ["The elevator is out of order again.", "We took the elevator to the fifth floor."],
    cloze: "I live on the eighth floor, so I use the ___ every day.",
    accept: ["lift"],
    collocations: ["take the elevator", "the elevator is broken", "the elevator button"],
    band: 2,
    tags: ["home"],
    trap: "elevator (US) = lift (UK). 'לקחת מעלית' = take the elevator, לא go with the elevator.",
    colloc: { frame: "Let's ___ the elevator, I'm carrying groceries.", answer: "take", options: ["take", "go with", "ride with"], whyHe: "take the elevator - כמו take the bus." },
  },
  {
    id: "v-dl-babysitter",
    word: "babysitter",
    pos: "n",
    he: "בייביסיטר, שמרטף",
    def: "someone you pay to take care of your children for a few hours",
    examples: ["We found a babysitter for Saturday night.", "The babysitter puts them to bed at eight."],
    cloze: "We can't go out unless we get a ___.",
    collocations: ["get a babysitter", "find a babysitter", "pay the babysitter"],
    band: 2,
    tags: ["family"],
    trap: "האדם = a babysitter; הפעולה = to babysit. 'עשיתי בייביסיטר' = I babysat, לא I did babysitter.",
  },
  {
    id: "v-dl-spare-time",
    word: "spare time",
    pos: "n",
    he: "זמן פנוי",
    def: "time when you are not working and can do what you like",
    examples: ["I read in my spare time.", "She doesn't have much spare time these days."],
    cloze: "What do you do in your ___?",
    collocations: ["in my spare time", "have spare time", "free time"],
    band: 2,
    tags: ["time"],
    trap: "'בזמן הפנוי שלי' = IN my spare time, לא at או on. spare = פנוי או רזרבי: a spare key.",
    colloc: { frame: "___ my spare time I go running.", answer: "In", options: ["In", "At", "On"], whyHe: "in my spare time - תמיד in." },
  },
  {
    id: "v-dl-errand",
    word: "errand",
    pos: "n",
    he: "סידור, מטלה קטנה בחוץ",
    def: "a short trip you make to do something, like going to the bank",
    examples: ["I have a few errands downtown.", "It's just a quick errand, I'll be back soon."],
    cloze: "I'll be home in an hour, I have one more ___.",
    collocations: ["run errands", "a quick errand", "errands to do"],
    band: 2,
    tags: ["daily"],
    trap: "'סידורים' = errands. הפועל הנכון הוא RUN errands, לא make errands.",
  },
  {
    id: "v-dl-dinner-party",
    word: "dinner party",
    pos: "n",
    he: "ארוחת ערב עם אורחים",
    def: "an evening meal at home for invited guests",
    examples: ["We're having a dinner party on Friday.", "She's great at hosting dinner parties."],
    cloze: "They invited eight people to their ___.",
    collocations: ["have a dinner party", "host a dinner party", "throw a dinner party"],
    band: 2,
    tags: ["food"],
    trap: "'לעשות ארוחה עם אורחים' = have / host / throw a dinner party, לא make a dinner party.",
    colloc: { frame: "They're ___ a dinner party for his birthday.", answer: "having", options: ["having", "making", "doing"], whyHe: "have a dinner party או host a dinner party." },
  },
  {
    id: "v-dl-plumber",
    word: "plumber",
    pos: "n",
    he: "אינסטלטור",
    def: "a worker who fixes water pipes, taps and toilets",
    examples: ["We had to call a plumber at midnight.", "The plumber said the pipe is old."],
    cloze: "There's water under the sink - call a ___.",
    collocations: ["call a plumber", "a good plumber", "the plumber came"],
    band: 2,
    tags: ["home"],
    trap: "אינסטלטור = plumber, וה-b שותקת: /PLUM-er/. אין מילה installer במובן הזה.",
  },
  {
    id: "v-dl-cozy",
    word: "cozy",
    pos: "adj",
    he: "נעים וחמים",
    def: "warm, comfortable and pleasant, usually about a room or a home",
    examples: ["Their living room is small but cozy.", "It's cozy under the blanket."],
    cloze: "The apartment is tiny, but it feels really ___ in the winter.",
    accept: ["cosy"],
    collocations: ["a cozy apartment", "feel cozy", "cozy and warm"],
    band: 2,
    tags: ["home"],
    trap: "cozy (US) / cosy (UK). מתאר מקום, לא אדם. על אדם נעים אומרים nice או warm.",
  },
  {
    id: "v-dl-sour",
    word: "sour",
    pos: "adj",
    he: "חמוץ",
    def: "with a sharp taste, like a lemon",
    examples: ["The milk has gone sour.", "This yogurt is a bit sour."],
    cloze: "Don't drink that - it smells ___.",
    collocations: ["go sour", "sour cream", "a sour taste"],
    band: 2,
    tags: ["food"],
    trap: "sour = חמוץ; bitter = מר. 'החלב התקלקל' = The milk went sour / went off.",
    colloc: { frame: "I put ___ cream on the soup.", answer: "sour", options: ["sour", "acid", "bitter"], whyHe: "שמנת חמוצה = sour cream." },
  },
  {
    id: "v-dl-stale",
    word: "stale",
    pos: "adj",
    he: "לא טרי, מיובש",
    def: "no longer fresh, especially bread or cake",
    examples: ["The bread is stale, don't eat it.", "Stale cake is fine for making crumbs."],
    cloze: "This challah is three days old and completely ___.",
    collocations: ["stale bread", "go stale", "stale air"],
    band: 2,
    tags: ["food"],
    trap: "לחם ישן = stale; חלב מקולקל = sour או off, לא stale.",
  },
  {
    id: "v-dl-sleepy",
    word: "sleepy",
    pos: "adj",
    he: "ישנוני",
    def: "feeling that you want to sleep",
    examples: ["I get sleepy right after lunch.", "The kids are sleepy already."],
    cloze: "A big meal always makes me ___.",
    collocations: ["feel sleepy", "get sleepy", "a sleepy morning"],
    band: 2,
    tags: ["daily"],
    trap: "sleepy = ישנוני; tired = עייף; asleep = ישן. 'אני ישן' (עכשיו) = I'm asleep, לא I'm sleepy.",
  },
  {
    id: "v-dl-run-errands",
    word: "run errands",
    pos: "phr",
    he: "לעשות סידורים",
    def: "to go out and do several small jobs, like shopping or the bank",
    examples: ["I spent the morning running errands.", "She runs errands for her parents."],
    cloze: "Sunday morning is when we ___ - bank, post office, pharmacy.",
    clozeAnswer: "run errands",
    collocations: ["run errands", "run a few errands", "run errands for someone"],
    band: 2,
    tags: ["daily"],
    trap: "'לעשות סידורים' = run errands. make arrangements זה משהו אחר - לתאם ולארגן מראש.",
    colloc: { frame: "I have to ___ a few errands before we leave.", answer: "run", options: ["run", "make", "arrange"], whyHe: "run errands - צירוף קבוע." },
  },
  {
    id: "v-dl-chop",
    word: "chop",
    pos: "v",
    he: "לקצוץ",
    def: "to cut food into small pieces with a knife",
    examples: ["Chop the onions finely.", "He chopped the vegetables for the salad."],
    cloze: "First ___ the tomatoes into small cubes.",
    collocations: ["chop onions", "finely chopped", "chop it up"],
    band: 2,
    tags: ["food"],
    trap: "chop = לקצוץ לחתיכות; slice = לפרוס; grate = לרסק בפומפייה. 'קצוץ דק' = finely chopped.",
  },
  {
    id: "v-dl-peel",
    word: "peel",
    pos: "v",
    he: "לקלף",
    def: "to take the skin off a fruit or vegetable",
    examples: ["Peel the potatoes before you boil them.", "She peeled an apple for the baby."],
    cloze: "Can you ___ the carrots for me?",
    collocations: ["peel potatoes", "peel an orange", "a potato peeler"],
    band: 2,
    tags: ["food"],
    trap: "peel הוא הפועל וגם הקליפה: orange peel. הכלי = a peeler.",
  },
  {
    id: "v-dl-stir",
    word: "stir",
    pos: "v",
    he: "לערבב, לבחוש",
    def: "to move food or liquid around with a spoon",
    examples: ["Stir the soup so it doesn't burn.", "He stirred sugar into his coffee."],
    cloze: "Keep ___ the sauce for two more minutes.",
    clozeAnswer: "stirring",
    collocations: ["stir the soup", "stir well", "stir constantly"],
    band: 2,
    tags: ["food"],
    trap: "stir = לבחוש נוזל בכף; mix = לערבב חומרים יחד. 'תבחש' = Stir it.",
  },
  {
    id: "v-dl-roast",
    word: "roast",
    pos: "v",
    he: "לצלות בתנור",
    def: "to cook meat or vegetables in an oven with some oil",
    examples: ["I roasted a chicken for Friday night.", "Roast the vegetables for forty minutes."],
    cloze: "We usually ___ potatoes with olive oil and salt.",
    collocations: ["roast chicken", "roasted vegetables", "roast it in the oven"],
    band: 2,
    tags: ["food"],
    trap: "roast = בתנור; grill = על גריל; fry = לטגן במחבת. 'עוף בתנור' = roast chicken.",
  },
  {
    id: "v-dl-spill",
    word: "spill",
    pos: "v",
    he: "לשפוך בטעות, להישפך",
    def: "to make liquid fall out of a container by accident",
    examples: ["I spilled coffee on my laptop.", "The milk spilled all over the floor."],
    cloze: "Careful, you're going to ___ the juice.",
    collocations: ["spill coffee", "spill water on something", "a spilled drink"],
    band: 2,
    tags: ["home"],
    trap: "spill = בטעות; pour = למזוג בכוונה. 'שפכתי מים' בטעות = I spilled water.",
    colloc: { frame: "He ___ red wine on the white tablecloth.", answer: "spilled", options: ["spilled", "poured", "dropped"], whyHe: "בטעות = spilled; poured = מזג בכוונה." },
  },
  {
    id: "v-dl-vacuum",
    word: "vacuum",
    pos: "v",
    he: "לשאוב אבק",
    def: "to clean a floor or a carpet with a machine that sucks up dirt",
    examples: ["I vacuum the living room twice a week.", "Can you vacuum under the couch?"],
    cloze: "The floor is full of crumbs - I need to ___.",
    collocations: ["vacuum the carpet", "a vacuum cleaner", "vacuum the whole house"],
    band: 2,
    tags: ["home"],
    trap: "'לשאוב אבק' = to vacuum (פועל אחד). המכשיר = a vacuum cleaner. לא to do vacuum.",
  },
  {
    id: "v-dl-sweep",
    word: "sweep",
    pos: "v",
    he: "לטאטא",
    def: "to clean a floor with a broom",
    examples: ["Sweep the kitchen floor after dinner.", "He swept the balcony this morning."],
    cloze: "Take the broom and ___ the sand off the porch.",
    collocations: ["sweep the floor", "sweep up the mess", "a broom"],
    band: 2,
    tags: ["home"],
    trap: "sweep = לטאטא במטאטא; mop = לשטוף עם מגב וסמרטוט. עבר: swept.",
  },
  {
    id: "v-dl-dust",
    word: "dust",
    pos: "v",
    he: "לנגב אבק",
    def: "to clean dust off furniture with a cloth",
    examples: ["I dusted the shelves this morning.", "Someone has to dust the living room."],
    cloze: "Don't forget to ___ the top of the bookcase.",
    collocations: ["dust the shelves", "dust the furniture", "a dusty room"],
    band: 2,
    tags: ["home"],
    trap: "כפועל dust פירושו להוריד אבק, לא להוסיף. האבק עצמו בלתי ספיר: There's a lot of dust.",
  },
  {
    id: "v-dl-rush",
    word: "rush",
    pos: "v",
    he: "למהר, לרוץ בלחץ",
    def: "to do something or go somewhere very quickly",
    examples: ["I rushed out without my keys.", "Don't rush, we still have time."],
    cloze: "Every morning we ___ to get the kids to school on time.",
    collocations: ["rush out", "rush home", "don't rush me"],
    band: 2,
    tags: ["time"],
    trap: "rush = למהר. 'אל תלחץ עליי' = Don't rush me, לא don't press me.",
    colloc: { frame: "I had to ___ home to let the plumber in.", answer: "rush", options: ["rush", "hurry up", "run out"], whyHe: "rush home = למהר הביתה; hurry up זה 'תזדרז' בלי יעד." },
  },
  {
    id: "v-dl-replace",
    word: "replace",
    pos: "v",
    he: "להחליף בחדש",
    def: "to put a new thing in the place of an old one",
    examples: ["We had to replace the fridge.", "Can you replace the light bulb?"],
    cloze: "The washing machine is fifteen years old - it's time to ___ it.",
    collocations: ["replace a part", "replace it with", "needs replacing"],
    band: 2,
    tags: ["home"],
    trap: "replace = לשים חדש במקום ישן. 'להחליף מקום או תורנות' = switch / swap. תמיד replace X WITH Y.",
    colloc: { frame: "We replaced the old sofa ___ a new one.", answer: "with", options: ["with", "to", "by"], whyHe: "replace X with Y - עם with." },
  },
  {
    id: "v-dl-lock",
    word: "lock",
    pos: "v",
    he: "לנעול",
    def: "to close something with a key so nobody can open it",
    examples: ["Did you lock the door?", "She locked the car and walked away."],
    cloze: "I always ___ the door before I go to sleep.",
    collocations: ["lock the door", "lock up the house", "get locked out"],
    band: 2,
    tags: ["home"],
    trap: "lock = לנעול; close = לסגור. 'ננעלתי בחוץ' = I got locked out, לא I closed myself outside.",
    colloc: { frame: "I left my keys inside and got ___ out.", answer: "locked", options: ["locked", "closed", "shut"], whyHe: "get locked out = להינעל מחוץ לבית." },
  },
  {
    id: "v-dl-microwave",
    word: "microwave",
    pos: "v",
    he: "לחמם במיקרוגל",
    def: "to heat food quickly in a microwave oven",
    examples: ["Just microwave it for two minutes.", "She microwaved the soup and sat down."],
    cloze: "Just ___ the rice for ninety seconds and stir it.",
    collocations: ["microwave it", "microwave for two minutes", "in the microwave"],
    band: 2,
    tags: ["food"],
    trap: "microwave הוא גם המכשיר וגם הפועל. אפשר גם heat it up in the microwave.",
  },
  {
    id: "v-dl-serve",
    word: "serve",
    pos: "v",
    he: "להגיש אוכל",
    def: "to give food or drink to people at a meal",
    examples: ["Dinner is served at seven.", "She served the soup in big bowls."],
    cloze: "We usually ___ salad before the main course.",
    collocations: ["serve dinner", "serve it hot", "serves four people"],
    band: 2,
    tags: ["food"],
    trap: "serve = להגיש אוכל. 'המנה מספיקה לארבעה' = It serves four. שירות במסעדה = service.",
  },
  {
    id: "v-dl-taste",
    word: "taste",
    pos: "v",
    he: "לטעום, להיות בטעם",
    def: "to try a little food, or to have a certain flavor",
    examples: ["Taste the sauce and tell me if it needs salt.", "This soup tastes amazing."],
    cloze: "Can I ___ it before you add the pepper?",
    collocations: ["taste the food", "tastes good", "taste like chicken"],
    band: 2,
    tags: ["food"],
    trap: "taste + תואר: It tastes good, לא it tastes well. taste LIKE + שם עצם: It tastes like fish.",
    colloc: { frame: "This soup ___ great, what did you put in it?", answer: "tastes", options: ["tastes", "tastes like", "is tasting"], whyHe: "taste + תואר: tastes great. tastes like + שם עצם." },
  },
  {
    id: "v-dl-iron",
    word: "iron",
    pos: "v",
    he: "לגהץ",
    def: "to make clothes smooth with a hot iron",
    examples: ["I have to iron a shirt for tomorrow.", "He never irons anything."],
    cloze: "Can you ___ my blue shirt for the wedding?",
    collocations: ["iron a shirt", "an ironing board", "do the ironing"],
    band: 2,
    tags: ["home"],
    trap: "iron הוא הפועל וגם המכשיר. 'גיהוץ' = the ironing: I did the ironing. הגייה: /AI-ern/.",
  },
  {
    id: "v-dl-feed-the-dog",
    word: "feed the dog",
    pos: "phr",
    he: "להאכיל את הכלב",
    def: "to give food to a pet dog",
    examples: ["Did anyone feed the dog?", "I feed the dog before I leave for work."],
    cloze: "It's your turn to ___ tonight.",
    clozeAnswer: "feed the dog",
    collocations: ["feed the dog", "feed the cat", "feed the baby"],
    band: 2,
    tags: ["family"],
    trap: "feed = להאכיל מישהו אחר; eat = לאכול. עבר לא סדיר: fed. 'האכלתי את הכלב' = I fed the dog.",
  },
  {
    id: "v-dl-knock",
    word: "knock",
    pos: "v",
    he: "לדפוק בדלת",
    def: "to hit a door with your hand so people know you are there",
    examples: ["Someone is knocking at the door.", "Knock before you come in."],
    cloze: "He ___ on the door three times but nobody answered.",
    clozeAnswer: "knocked",
    collocations: ["knock on the door", "knock at the door", "a knock at the door"],
    band: 2,
    tags: ["home"],
    trap: "knock ON או AT the door. ה-k שותקת: /nok/. 'דפקו בדלת' = Someone knocked on the door.",
    colloc: { frame: "Please ___ on the door before you open it.", answer: "knock", options: ["knock", "hit", "beat"], whyHe: "דופקים בדלת = knock on the door; hit ו-beat זה להכות." },
  },

  // ---------- Band 3 ----------
  {
    id: "v-dl-utility-bill",
    word: "utility bill",
    pos: "n",
    he: "חשבון חשמל, מים או גז",
    def: "a bill you pay for electricity, water or gas",
    examples: ["Our utility bills are higher in the summer.", "He pays the utility bills online."],
    cloze: "The AC runs all day, so the ___ are huge.",
    clozeAnswer: "utility bills",
    collocations: ["pay the bills", "the electricity bill", "monthly bills"],
    band: 3,
    tags: ["home"],
    trap: "'חשבון חשמל' = the electricity bill; כולם יחד = utility bills. משלמים bill בלי for: pay the bill.",
    colloc: { frame: "I forgot to ___ the electricity bill this month.", answer: "pay", options: ["pay", "pay for", "make"], whyHe: "pay the bill - בלי for. pay FOR משמש למוצר: I paid for the sofa." },
  },
  {
    id: "v-dl-lease",
    word: "lease",
    pos: "n",
    he: "חוזה שכירות",
    def: "a written agreement to rent a home for a fixed time",
    examples: ["We signed a one-year lease.", "The lease ends in June."],
    cloze: "Read the whole contract before you sign the ___.",
    collocations: ["sign a lease", "renew the lease", "a one-year lease"],
    band: 3,
    tags: ["home"],
    trap: "lease = החוזה; rent = הכסף החודשי. 'חתמנו על חוזה' = We signed a lease, לא signed on a lease.",
    colloc: { frame: "We're going to ___ the lease for another year.", answer: "renew", options: ["renew", "continue with", "make again"], whyHe: "renew a lease = לחדש חוזה שכירות." },
  },
  {
    id: "v-dl-appliance",
    word: "appliance",
    pos: "n",
    he: "מכשיר חשמלי ביתי",
    def: "a machine you use at home, such as a fridge or a washing machine",
    examples: ["All the appliances in the kitchen are new.", "The store delivers large appliances for free."],
    cloze: "The oven and the dishwasher are the only ___ we replaced.",
    clozeAnswer: "appliances",
    collocations: ["kitchen appliances", "home appliances", "an old appliance"],
    band: 3,
    tags: ["home"],
    trap: "appliance = מכשיר ביתי גדול (מקרר, תנור); device = מכשיר קטן או דיגיטלי. הטעמה: ap-PLI-ance.",
  },
  {
    id: "v-dl-laundry-basket",
    word: "laundry basket",
    pos: "n",
    he: "סל כביסה",
    def: "a basket where you put dirty clothes until you wash them",
    examples: ["Put your socks in the laundry basket.", "The laundry basket is full again."],
    cloze: "Your towel doesn't go on the floor - it goes in the ___.",
    collocations: ["in the laundry basket", "a full laundry basket", "empty the basket"],
    band: 3,
    tags: ["home"],
    trap: "סל כביסה = laundry basket או hamper (US). שמים IN the basket, לא throw to the basket.",
  },
  {
    id: "v-dl-daycare",
    word: "daycare",
    pos: "n",
    he: "מעון, גן לפעוטות",
    def: "a place that takes care of small children while the parents work",
    examples: ["We pay a lot for daycare.", "She picks him up from daycare at four."],
    cloze: "He's been at ___ since he was one year old.",
    collocations: ["at daycare", "a daycare center", "pick up from daycare"],
    band: 3,
    tags: ["family"],
    trap: "מעון = daycare (US) / nursery (UK). אומרים at daycare בלי the, כמו at school.",
    colloc: { frame: "I drop the baby off ___ daycare at 7:30.", answer: "at", options: ["at", "in", "to"], whyHe: "drop someone off AT a place." },
  },
  {
    id: "v-dl-stroller",
    word: "stroller",
    pos: "n",
    he: "עגלת תינוק",
    def: "a small seat on wheels for pushing a baby",
    examples: ["The baby fell asleep in the stroller.", "We keep the stroller under the stairs."],
    cloze: "There's no elevator, so I carry the ___ up three floors.",
    collocations: ["push a stroller", "fold the stroller", "in the stroller"],
    band: 3,
    tags: ["family"],
    trap: "stroller (US) / pushchair, pram (UK). עגלת קניות היא cart או trolley - לא אותה מילה.",
  },
  {
    id: "v-dl-fed-up",
    word: "fed up",
    pos: "adj",
    he: "נמאס לי, מאס",
    def: "annoyed and tired of a situation that has gone on too long",
    examples: ["I'm fed up with the noise upstairs.", "She got fed up and moved out."],
    cloze: "I'm ___ with washing dishes every single night.",
    clozeAnswer: "fed up",
    collocations: ["fed up with", "get fed up", "completely fed up"],
    band: 3,
    tags: ["daily"],
    trap: "fed up WITH something. 'נמאס לי מזה' = I'm fed up with it, לא fed up FROM it.",
    colloc: { frame: "He's fed ___ with the landlord's excuses.", answer: "up", options: ["up", "from", "of"], whyHe: "fed up with - הצירוף הקבוע; from הוא תרגום ישיר שגוי מעברית." },
  },
  {
    id: "v-dl-handy",
    word: "handy",
    pos: "adj",
    he: "שימושי, שווה להחזיק",
    def: "useful and easy to use; also good at fixing things",
    examples: ["A second key is always handy.", "My brother is handy - he fixed the shelf in ten minutes."],
    cloze: "Keep a flashlight in the drawer, it's really ___.",
    collocations: ["come in handy", "very handy", "handy around the house"],
    band: 3,
    tags: ["home"],
    trap: "come in handy = יתגלה כשימושי. על אדם: he's handy = 'יש לו ידיים טובות'.",
    colloc: { frame: "Take the extra charger - it might ___ in handy.", answer: "come", options: ["come", "be", "get"], whyHe: "come in handy - צירוף קבוע." },
  },
  {
    id: "v-dl-spotless",
    word: "spotless",
    pos: "adj",
    he: "נקי לגמרי",
    def: "perfectly clean, with no dirt at all",
    examples: ["Her kitchen is always spotless.", "The apartment was spotless when we moved in."],
    cloze: "After three hours of cleaning, the bathroom was ___.",
    collocations: ["a spotless kitchen", "keep it spotless", "absolutely spotless"],
    band: 3,
    tags: ["home"],
    trap: "spotless חזק יותר מ-clean: נקי בלי רבב. הפוך ממנו: filthy (מלוכלך מאוד).",
  },
  {
    id: "v-dl-brand-new",
    word: "brand-new",
    pos: "adj",
    he: "חדש לגמרי",
    def: "completely new and never used",
    examples: ["They bought a brand-new dishwasher.", "The building is brand-new."],
    cloze: "It's not second-hand - the couch is ___.",
    collocations: ["a brand-new car", "a brand-new apartment", "look brand-new"],
    band: 3,
    tags: ["home"],
    trap: "brand-new = חדש לגמרי. לא להתבלבל עם a new brand (=מותג חדש). לפני שם עצם עם מקף.",
  },
  {
    id: "v-dl-barely",
    word: "barely",
    pos: "adv",
    he: "בקושי",
    def: "almost not at all",
    examples: ["I barely slept last night.", "We barely have time to eat breakfast."],
    cloze: "The fridge is so full I can ___ close the door.",
    collocations: ["barely enough", "barely slept", "barely have time"],
    band: 3,
    tags: ["time"],
    trap: "barely כבר שולל: I barely slept, לא I didn't barely sleep. דומה מאוד ל-hardly.",
  },
  {
    id: "v-dl-stuffy",
    word: "stuffy",
    pos: "adj",
    he: "מחניק",
    def: "with no fresh air; unpleasantly warm and closed",
    examples: ["The room is stuffy, open a window.", "It gets stuffy in here at night."],
    cloze: "Turn on the fan - it's really ___ in the kitchen.",
    collocations: ["a stuffy room", "get stuffy", "a stuffy nose"],
    band: 3,
    tags: ["home"],
    trap: "חדר מחניק = stuffy, לא heavy air. אף סתום = a stuffy nose.",
  },
  {
    id: "v-dl-in-a-hurry",
    word: "in a hurry",
    pos: "phr",
    he: "ממהר, בחיפזון",
    def: "needing to do something quickly because you have little time",
    examples: ["Sorry, I'm in a hurry.", "He left in a hurry and forgot his phone."],
    cloze: "I ate standing up because I was ___.",
    clozeAnswer: "in a hurry",
    collocations: ["be in a hurry", "leave in a hurry", "in a big hurry"],
    band: 3,
    tags: ["time"],
    trap: "'אני ממהר' = I'm in a hurry, לא I hurry. ההפך: I'm in no hurry (אין לי לחץ).",
    colloc: { frame: "I can't talk now, I'm ___ a hurry.", answer: "in", options: ["in", "on", "at"], whyHe: "in a hurry - תמיד with in." },
  },
  {
    id: "v-dl-plenty-of",
    word: "plenty of",
    pos: "other",
    he: "הרבה, בשפע",
    def: "more than enough of something",
    examples: ["There's plenty of food for everyone.", "We have plenty of time before the bus."],
    cloze: "Don't buy milk, we still have ___ it.",
    clozeAnswer: "plenty of",
    collocations: ["plenty of time", "plenty of food", "plenty of room"],
    band: 3,
    tags: ["food"],
    trap: "plenty of מתאים למשפט חיובי ומשמעו 'יותר ממספיק'. בשאלה ובשלילה עדיף enough / much / many.",
    colloc: { frame: "Take your time, we have ___ of time.", answer: "plenty", options: ["plenty", "much", "many"], whyHe: "plenty of time; much ו-many לא באים בצורה הזו עם of." },
  },
  {
    id: "v-dl-be-running-late",
    word: "be running late",
    pos: "phr",
    he: "לאחר, להיות באיחור",
    def: "to be later than planned",
    examples: ["I'm running late, start without me.", "The bus is running late again."],
    cloze: "She called to say she's ___ because of traffic.",
    clozeAnswer: "running late",
    collocations: ["running late", "running a bit late", "sorry I'm late"],
    band: 3,
    tags: ["time"],
    trap: "'אני מאחר' = I'm running late / I'll be late, לא I'm delaying. delayed שייך לטיסות ורכבות.",
    colloc: { frame: "Sorry, I'm ___ late - traffic was terrible.", answer: "running", options: ["running", "becoming", "doing"], whyHe: "be running late = לאחר." },
  },
  {
    id: "v-dl-grab-a-bite",
    word: "grab a bite",
    pos: "phr",
    he: "לחטוף משהו לאכול",
    def: "to eat something quickly, usually outside the house",
    examples: ["Let's grab a bite before the movie.", "I grabbed a bite at the station."],
    cloze: "We only have twenty minutes - want to ___?",
    clozeAnswer: "grab a bite",
    collocations: ["grab a bite to eat", "grab a coffee", "grab something to eat"],
    band: 3,
    tags: ["food"],
    trap: "grab a bite = ארוחה מהירה. 'לאכול במסעדה' באופן כללי = eat out.",
  },
  {
    id: "v-dl-stay-up-late",
    word: "stay up late",
    pos: "phr",
    he: "להישאר ער עד מאוחר",
    def: "to go to bed much later than usual",
    examples: ["I stayed up late finishing the laundry.", "The kids stay up late on Fridays."],
    cloze: "Don't ___ - you have to get up at six.",
    clozeAnswer: "stay up late",
    collocations: ["stay up late", "stay up watching TV", "stay up until two"],
    band: 3,
    tags: ["time"],
    trap: "stay up late = להישאר ער; sleep late / sleep in = לישון עד מאוחר בבוקר. אל תחליף ביניהם.",
    colloc: { frame: "I ___ up late last night watching a series.", answer: "stayed", options: ["stayed", "remained", "was"], whyHe: "stay up = להישאר ער; remained up לא נאמר." },
  },
  {
    id: "v-dl-alarm-goes-off",
    word: "alarm goes off",
    pos: "phr",
    he: "השעון המעורר מצלצל",
    def: "when a clock or a phone makes a sound to wake you up",
    examples: ["My alarm goes off at 6:15.", "I didn't hear the alarm go off."],
    cloze: "The ___ every morning at six, but I keep hitting snooze.",
    clozeAnswer: "alarm goes off",
    collocations: ["set an alarm", "the alarm goes off", "hit snooze"],
    band: 3,
    tags: ["time"],
    trap: "go off על שעון = לצלצל, לא להיכבות. 'לכוון שעון' = set an alarm.",
    colloc: { frame: "I ___ my alarm for 5:45 so I won't be late.", answer: "set", options: ["set", "put", "turn"], whyHe: "set an alarm = לכוון שעון מעורר." },
  },
  {
    id: "v-dl-defrost",
    word: "defrost",
    pos: "v",
    he: "להפשיר",
    def: "to let frozen food get soft again before you cook it",
    examples: ["Defrost the chicken in the fridge overnight.", "I forgot to defrost the soup."],
    cloze: "Take the meat out of the freezer so it can ___.",
    collocations: ["defrost the chicken", "defrost overnight", "defrost in the microwave"],
    band: 3,
    tags: ["food"],
    trap: "defrost = להפשיר; freeze = להקפיא; frozen = קפוא. אפשר גם thaw, אבל defrost נפוץ יותר בבית.",
  },
  {
    id: "v-dl-heat-up",
    word: "heat up",
    pos: "phr",
    he: "לחמם אוכל",
    def: "to make cold food warm again",
    examples: ["Heat up the rice in the microwave.", "I heated up yesterday's soup."],
    cloze: "Just ___ the leftovers, don't cook anything new.",
    clozeAnswer: "heat up",
    collocations: ["heat up the leftovers", "heat it up", "warm it up"],
    band: 3,
    tags: ["food"],
    trap: "heat up = לחמם אוכל; warm up = גם לחמם וגם להתחמם לפני ספורט. לא make it hot.",
  },
  {
    id: "v-dl-repair",
    word: "repair",
    pos: "v",
    he: "לתקן (רשמי)",
    def: "to fix something damaged, often as professional work",
    examples: ["They repaired the roof after the storm.", "The AC needs to be repaired."],
    cloze: "It will cost four hundred shekels to ___ the oven.",
    collocations: ["repair the damage", "need repairs", "under repair"],
    band: 3,
    tags: ["home"],
    trap: "repair רשמי יותר מ-fix ומתאים לדברים גדולים. 'תיקונים בבית' = repairs (ברבים).",
  },
  {
    id: "v-dl-leak",
    word: "leak",
    pos: "v",
    he: "לדלוף, לטפטף",
    def: "to let liquid or gas out through a hole by mistake",
    examples: ["The pipe under the sink is leaking.", "Our roof leaks every winter."],
    cloze: "Water is dripping - I think the boiler is ___.",
    clozeAnswer: "leaking",
    collocations: ["a leaking pipe", "a water leak", "leak into the apartment"],
    band: 3,
    tags: ["home"],
    trap: "leak הוא פועל וגם שם עצם: There's a leak. 'יש נזילה מהשכנים' = There's a leak from the neighbors.",
    colloc: { frame: "There's a ___ in the ceiling from the apartment above.", answer: "leak", options: ["leak", "leaking", "drop"], whyHe: "יש נזילה = there's a leak (שם עצם)." },
  },
  {
    id: "v-dl-host",
    word: "host",
    pos: "v",
    he: "לארח",
    def: "to have guests in your home for a meal or an event",
    examples: ["We're hosting the family this Friday.", "She hosted twenty people in a tiny apartment."],
    cloze: "My parents always ___ the holiday dinner.",
    collocations: ["host a dinner", "host guests", "have people over"],
    band: 3,
    tags: ["family"],
    trap: "host someone (בלי to). המארח = the host, המתארח = the guest. 'לארח' בסלנג = have people over.",
    colloc: { frame: "We're having the whole family ___ for dinner.", answer: "over", options: ["over", "up", "in"], whyHe: "have someone over = לארח מישהו בבית." },
  },
  {
    id: "v-dl-do-the-shopping",
    word: "do the shopping",
    pos: "phr",
    he: "לעשות קניות לבית",
    def: "to buy the food and things that the house needs",
    examples: ["I do the shopping on Thursday nights.", "Who's doing the shopping this week?"],
    cloze: "He cooks and I ___ - that's our deal.",
    clozeAnswer: "do the shopping",
    collocations: ["do the shopping", "do the food shopping", "go shopping"],
    band: 3,
    tags: ["food"],
    trap: "do the shopping = קניות שוטפות לבית; go shopping = לצאת לקניות בגדים להנאה.",
    colloc: { frame: "I need to ___ the shopping before Shabbat.", answer: "do", options: ["do", "make", "buy"], whyHe: "do the shopping - צירוף קבוע עם do." },
  },
  {
    id: "v-dl-put-the-kids-to-bed",
    word: "put the kids to bed",
    pos: "phr",
    he: "להשכיב את הילדים לישון",
    def: "to get children ready and into bed for the night",
    examples: ["I put the kids to bed at 7:30.", "He reads them a story when he puts them to bed."],
    cloze: "Can you ___ while I finish the dishes?",
    clozeAnswer: "put the kids to bed",
    collocations: ["put the kids to bed", "a bedtime routine", "tuck them in"],
    band: 3,
    tags: ["family"],
    trap: "put someone to bed = להשכיב מישהו; go to bed = ללכת לישון בעצמך.",
  },

  // ---------- Band 4 ----------
  {
    id: "v-dl-move-in",
    word: "move in",
    pos: "phr",
    he: "להיכנס לגור",
    def: "to start living in a new home",
    examples: ["We moved in three months ago.", "They're moving in together next month."],
    cloze: "The apartment was painted before we ___.",
    clozeAnswer: "moved in",
    collocations: ["move in together", "move into an apartment", "move out"],
    band: 4,
    tags: ["home"],
    trap: "move in = להיכנס לדירה; move out = לעזוב. עם הדירה: move INTO a new place.",
    colloc: { frame: "They're moving ___ a bigger apartment next month.", answer: "into", options: ["into", "in", "to"], whyHe: "move into + הדירה; move in לבד בלי מושא." },
  },
  {
    id: "v-dl-doze-off",
    word: "doze off",
    pos: "phr",
    he: "להירדם בלי כוונה",
    def: "to fall asleep for a short time without meaning to",
    examples: ["I dozed off on the couch again.", "He dozes off in front of the TV every night."],
    cloze: "I ___ during the movie and missed the end.",
    clozeAnswer: "dozed off",
    collocations: ["doze off on the couch", "doze off for a minute", "nod off"],
    band: 4,
    tags: ["daily"],
    trap: "doze off = להירדם בטעות; go to sleep = ללכת לישון בכוונה; oversleep = לישון יותר מדי.",
  },
  {
    id: "v-dl-babysit",
    word: "babysit",
    pos: "v",
    he: "לשמור על ילדים",
    def: "to take care of children while their parents are out",
    examples: ["My sister babysits on weekends.", "Can you babysit for us on Thursday?"],
    cloze: "She earns extra money by ___ for the neighbors.",
    clozeAnswer: "babysitting",
    collocations: ["babysit for someone", "babysit the kids", "babysitting job"],
    band: 4,
    tags: ["family"],
    trap: "babysit FOR the parents, או babysit the kids. 'עשיתי בייביסיטר' = I babysat.",
  },
  {
    id: "v-dl-order-takeout",
    word: "order takeout",
    pos: "phr",
    he: "להזמין אוכל מבחוץ",
    def: "to ask a restaurant to prepare food that you pick up or get delivered",
    examples: ["Let's order takeout tonight, I'm exhausted.", "We ordered takeout twice this week."],
    cloze: "Nobody wants to cook, so we'll just ___.",
    clozeAnswer: "order takeout",
    accept: ["order takeaway"],
    collocations: ["order takeout", "order in", "get it delivered"],
    band: 4,
    tags: ["food"],
    trap: "takeout (US) / takeaway (UK). 'להזמין אוכל הביתה' = order in או order delivery.",
  },
  {
    id: "v-dl-sip",
    word: "sip",
    pos: "v",
    he: "ללגום לאט",
    def: "to drink a small amount at a time",
    examples: ["She sipped her tea slowly.", "He sat by the window, sipping coffee."],
    cloze: "He ___ his coffee and read the paper.",
    clozeAnswer: "sipped",
    collocations: ["sip coffee", "take a sip", "sip slowly"],
    band: 4,
    tags: ["food"],
    trap: "sip = ללגום לאט; gulp = לגמוע בבת אחת. 'לגימה' כשם עצם = a sip: Take a sip.",
  },
];
