import type { VocabItem } from "@/lib/types";

export const HEALTH_SPORT: VocabItem[] = [
  // ---------- Illness, body, symptoms ----------
  {
    id: "v-hl-injury",
    word: "injury",
    pos: "n",
    he: "פציעה",
    def: "damage to a part of your body, usually from an accident or sport",
    examples: ["He has a knee injury and can't play this week.", "Luckily, nobody had any serious injuries."],
    cloze: "She has a serious knee ___ and needs to rest for a month.",
    collocations: ["serious injury", "sports injury", "suffer an injury"],
    band: 2,
    tags: ["health", "body", "sport"],
    trap: "injury = פציעה גופנית. wound = פצע חמור (סכין, ירי). damage = נזק לדברים, לא לאנשים.",
    colloc: { frame: "He had to leave the game with a serious ___.", answer: "injury", options: ["injury", "damage", "harm"], whyHe: "פציעה של אדם = injury. damage = נזק לרכוש." },
  },
  {
    id: "v-hl-injure",
    word: "injure",
    pos: "v",
    he: "לפצוע",
    def: "to hurt a part of your body or someone else's body",
    examples: ["He injured his back lifting a heavy box.", "Two people were injured in the accident."],
    cloze: "He ___ his knee in the last game of the season.",
    clozeAnswer: "injured",
    collocations: ["get injured", "injure your back", "badly injured"],
    band: 2,
    tags: ["health", "body", "sport"],
    trap: "לא אומרים 'I injured' לבד. אומרים I got injured (נפצעתי) או I injured my knee (פצעתי את הברך).",
  },
  {
    id: "v-hl-hurt",
    word: "hurt",
    pos: "v",
    he: "לכאוב, לפגוע",
    def: "to feel pain, or to cause pain to someone",
    examples: ["My back hurts when I sit for too long.", "Careful, you'll hurt yourself with that knife."],
    cloze: "My back ___ when I sit for too long.",
    clozeAnswer: "hurts",
    collocations: ["it hurts", "hurt yourself", "hurt badly"],
    band: 1,
    tags: ["health", "body"],
    trap: "בעברית 'כואבת לי הרגל', באנגלית הרגל היא הנושא: my leg hurts. לא 'it hurts me the leg'. hurt לא משתנה: hurt/hurt/hurt.",
    colloc: { frame: "Ouch! That really ___.", answer: "hurts", options: ["hurts", "pains", "aches me"], whyHe: "it hurts = זה כואב. pain הוא שם עצם, לא פועל בשימוש הזה." },
  },
  {
    id: "v-hl-ache",
    word: "ache",
    pos: "n",
    he: "כאב עמום",
    def: "a continuous, dull pain in a part of your body",
    examples: ["I have a dull ache in my shoulder.", "She woke up with a terrible stomachache."],
    cloze: "I have a dull ___ in my lower back from sitting all day.",
    collocations: ["dull ache", "aches and pains", "headache"],
    band: 2,
    tags: ["health", "body"],
    trap: "ache = כאב עמום ומתמשך, לרוב במילה אחת: headache, stomachache, backache. pain = כאב חד או חזק יותר. לא 'I have ache' — אלא I have a headache.",
    colloc: { frame: "I've had a ___ all morning, I think I need coffee.", answer: "headache", options: ["headache", "headpain", "head hurt"], whyHe: "כאב ראש = headache, מילה אחת." },
  },
  {
    id: "v-hl-sore",
    word: "sore",
    pos: "adj",
    he: "כואב, רגיש",
    def: "painful when you touch or use it, often after exercise or illness",
    examples: ["I have a sore throat and I can hardly talk.", "My legs are sore after yesterday's run."],
    cloze: "My legs are ___ after yesterday's run.",
    collocations: ["sore throat", "sore muscles", "sore feet"],
    band: 2,
    tags: ["health", "body", "sport"],
    trap: "כאב גרון = a sore throat. לא 'my throat hurts me' — אלא my throat is sore / my throat hurts.",
    colloc: { frame: "I can't sing tonight, I have a ___ throat.", answer: "sore", options: ["sore", "hurt", "painful"], whyHe: "הצירוף הקבוע הוא sore throat." },
  },
  {
    id: "v-hl-pain",
    word: "pain",
    pos: "n",
    he: "כאב",
    def: "the feeling you have when part of your body hurts",
    examples: ["She's in a lot of pain after the operation.", "I felt a sharp pain in my chest."],
    cloze: "I felt a sharp ___ in my chest and called the doctor.",
    collocations: ["in pain", "sharp pain", "chest pain", "painful"],
    band: 1,
    tags: ["health", "body"],
    trap: "pain בדרך כלל לא ספיר: I'm in pain, a lot of pain. ספיר רק לכאב ספציפי: a sharp pain in my chest. 'I have pains' ❌ ברוב המקרים.",
    colloc: { frame: "After the accident he was ___ terrible pain.", answer: "in", options: ["in", "with", "under"], whyHe: "אומרים to be in pain." },
  },
  {
    id: "v-hl-cold",
    word: "cold",
    pos: "n",
    he: "הצטננות",
    def: "a common, mild illness that makes you sneeze and cough",
    examples: ["I've got a cold, so I'm staying home today.", "She caught a cold from her kids."],
    cloze: "I've got a ___, so I'm staying home today.",
    collocations: ["catch a cold", "have a cold", "a bad cold"],
    band: 1,
    tags: ["health"],
    trap: "I have a cold = אני מצונן. I am cold = קר לי. שני משפטים שונים לגמרי!",
    colloc: { frame: "Don't come too close, I don't want to ___ your cold.", answer: "catch", options: ["catch", "take", "get sick"], whyHe: "להידבק בהצטננות = catch a cold." },
  },
  {
    id: "v-hl-flu",
    word: "flu",
    pos: "n",
    he: "שפעת",
    def: "an illness like a bad cold, with a fever and aching body",
    examples: ["Half the office is out with the flu.", "I got a flu shot in October."],
    cloze: "Half the office is out with the ___ this week.",
    collocations: ["the flu", "flu shot", "come down with the flu"],
    band: 1,
    tags: ["health"],
    accept: ["the flu"],
    trap: "באמריקאית עם the: I have the flu. חיסון שפעת = flu shot. 'I'm sick in flu' ❌.",
  },
  {
    id: "v-hl-fever",
    word: "fever",
    pos: "n",
    he: "חום",
    def: "a body temperature that is higher than normal because you are sick",
    examples: ["The baby has a high fever, so we called the doctor.", "Take this if the fever doesn't go down."],
    cloze: "The baby has a high ___, so we called the doctor.",
    collocations: ["have a fever", "high fever", "run a fever"],
    band: 1,
    tags: ["health", "body"],
    trap: "בעברית 'יש לי חום', באנגלית I have a fever, לא 'I have heat'. חום גבוה = a high fever, לא 'strong fever'.",
    colloc: { frame: "You feel hot. I think you're ___ a fever.", answer: "running", options: ["running", "making", "doing"], whyHe: "run a fever / have a fever = להיות עם חום." },
  },
  {
    id: "v-hl-cough",
    word: "cough",
    pos: "v",
    he: "להשתעל",
    def: "to push air out of your throat with a sudden sound, often when you are sick",
    examples: ["I've been coughing all night.", "He coughed so loudly that everyone turned around."],
    cloze: "I've been ___ all night and I can't sleep.",
    clozeAnswer: "coughing",
    collocations: ["cough all night", "a bad cough", "cough syrup"],
    band: 2,
    tags: ["health", "body"],
    trap: "cough הוגים 'קוף' (עם פ). גם פועל וגם שם עצם: I have a cough / I keep coughing.",
  },
  {
    id: "v-hl-sneeze",
    word: "sneeze",
    pos: "v",
    he: "להתעטש",
    def: "to suddenly blow air out of your nose and mouth, for example because of dust",
    examples: ["Every spring I sneeze all day because of the pollen.", "Cover your mouth when you sneeze."],
    cloze: "Every spring I ___ all day because of the pollen.",
    collocations: ["sneeze loudly", "keep sneezing", "bless you"],
    band: 2,
    tags: ["health", "body"],
    trap: "אחרי שמישהו מתעטש אומרים Bless you! (לא 'to health'). sneeze הוא גם שם עצם: a loud sneeze.",
  },
  {
    id: "v-hl-dizzy",
    word: "dizzy",
    pos: "adj",
    he: "סחרחורת, מסוחרר",
    def: "feeling that everything is turning around you and you might fall",
    examples: ["I stood up too fast and felt dizzy.", "If you feel dizzy, sit down and drink some water."],
    cloze: "I stood up too fast and felt ___.",
    collocations: ["feel dizzy", "get dizzy", "a dizzy spell"],
    band: 2,
    tags: ["health", "body"],
    trap: "יש לי סחרחורת = I feel dizzy. לא 'my head is turning' ולא 'I have dizziness' (נכון אבל לא מדובר).",
    colloc: { frame: "I skipped breakfast and now I ___ dizzy.", answer: "feel", options: ["feel", "have", "am with"], whyHe: "feel dizzy = מרגיש סחרחורת." },
  },
  {
    id: "v-hl-faint",
    word: "faint",
    pos: "v",
    he: "להתעלף",
    def: "to suddenly become unconscious for a short time",
    examples: ["She fainted in the heat and we called an ambulance.", "I almost fainted when I saw the blood."],
    cloze: "She ___ in the heat and we called an ambulance.",
    clozeAnswer: "fainted",
    collocations: ["faint from the heat", "almost faint", "pass out"],
    band: 3,
    tags: ["health", "body"],
    accept: ["pass out"],
    trap: "להתעלף = faint (רשמי יותר) או pass out (מדובר). 'I fell from consciousness' ❌.",
  },
  {
    id: "v-hl-allergy",
    word: "allergy",
    pos: "n",
    he: "אלרגיה",
    def: "a medical condition in which your body reacts badly to a food, animal, or plant",
    examples: ["I have an allergy to cats.", "Does anyone at the table have any food allergies?"],
    cloze: "I have an ___ to cats, so I can't visit her house.",
    collocations: ["food allergy", "have an allergy to", "allergy season"],
    band: 2,
    tags: ["health", "body", "food"],
    trap: "allergy (שם עצם) / allergic (תואר). have an allergy to X או be allergic to X. לא 'have allergy from'.",
  },
  {
    id: "v-hl-allergic-to",
    word: "allergic to",
    pos: "phr",
    he: "אלרגי ל",
    def: "having a bad physical reaction to a certain food, animal, or substance",
    examples: ["I'm allergic to peanuts.", "Is anyone here allergic to penicillin?"],
    cloze: "I can't eat that cake, I'm ___ nuts.",
    collocations: ["allergic to nuts", "allergic reaction", "severely allergic"],
    band: 2,
    tags: ["health", "body", "food"],
    trap: "אלרגי ל = allergic to, לא 'allergic from' ולא 'allergic for'.",
    colloc: { frame: "She can't have milk, she's allergic ___ it.", answer: "to", options: ["to", "from", "for"], whyHe: "allergic to — תמיד to." },
  },
  {
    id: "v-hl-prescription",
    word: "prescription",
    pos: "n",
    he: "מרשם רופא",
    def: "a paper from a doctor that says which medicine you need",
    examples: ["The doctor gave me a prescription for antibiotics.", "You can't buy these pills without a prescription."],
    cloze: "The doctor gave me a ___ for antibiotics.",
    collocations: ["a prescription for", "write a prescription", "prescription drugs"],
    band: 2,
    tags: ["health"],
    trap: "prescription = מרשם של רופא. recipe = מתכון לבישול. בעברית 'מרשם' יכול להיות שניהם — באנגלית לא לבלבל!",
    colloc: { frame: "The doctor ___ me a prescription for the cough.", answer: "wrote", options: ["wrote", "made", "said"], whyHe: "write a prescription = לרשום מרשם." },
  },
  {
    id: "v-hl-painkiller",
    word: "painkiller",
    pos: "n",
    he: "משכך כאבים",
    def: "a medicine that reduces pain",
    examples: ["Take a painkiller if the headache gets worse.", "I don't like taking painkillers every day."],
    cloze: "Take a ___ if the headache gets worse.",
    collocations: ["take a painkiller", "strong painkillers", "over-the-counter painkillers"],
    band: 2,
    tags: ["health"],
    trap: "משכך כאבים = painkiller, מילה אחת. 'pills against pain' ❌. אקמול/אדוויל הם painkillers.",
  },
  {
    id: "v-hl-pill",
    word: "pill",
    pos: "n",
    he: "כדור, גלולה",
    def: "a small round piece of medicine that you swallow",
    examples: ["Take one pill after breakfast with water.", "I forgot to take my pills this morning."],
    cloze: "Take one ___ after breakfast with water.",
    collocations: ["take a pill", "sleeping pill", "swallow a pill"],
    band: 1,
    tags: ["health"],
    accept: ["tablet"],
    trap: "לוקחים כדור = take a pill, לא eat a pill ולא drink a pill.",
    colloc: { frame: "Did you ___ your pills this morning?", answer: "take", options: ["take", "eat", "drink"], whyHe: "take medicine / take a pill." },
  },
  {
    id: "v-hl-dose",
    word: "dose",
    pos: "n",
    he: "מנה (תרופה)",
    def: "the amount of a medicine you should take at one time",
    examples: ["Don't take more than one dose every six hours.", "The doctor lowered my dose."],
    cloze: "Don't take more than one ___ every six hours.",
    collocations: ["a dose of", "high dose", "the right dose", "miss a dose"],
    band: 3,
    tags: ["health"],
    trap: "dose = מנת תרופה (הוגים 'דוס'). dozen = תריסר. dosage = המינון הכולל.",
  },
  {
    id: "v-hl-appointment",
    word: "appointment",
    pos: "n",
    he: "תור, פגישה",
    def: "an arranged time to see a doctor, dentist, or other professional",
    examples: ["I have a dentist appointment at three o'clock.", "Can I make an appointment for tomorrow morning?"],
    cloze: "I have a dentist ___ at three o'clock.",
    collocations: ["make an appointment", "have an appointment", "cancel an appointment"],
    band: 1,
    tags: ["health"],
    trap: "לקבוע תור = make an appointment, לא 'close a turn' ולא 'take a queue'. עם רופא = with the doctor.",
    colloc: { frame: "I need to ___ an appointment with the eye doctor.", answer: "make", options: ["make", "close", "take"], whyHe: "make an appointment = לקבוע תור." },
  },
  {
    id: "v-hl-symptom",
    word: "symptom",
    pos: "n",
    he: "תסמין, סימפטום",
    def: "a sign that shows you have an illness, like a fever or a cough",
    examples: ["A sore throat is a common symptom of a cold.", "What symptoms do you have?"],
    cloze: "A sore throat is a common ___ of a cold.",
    collocations: ["symptom of", "common symptoms", "show symptoms"],
    band: 2,
    tags: ["health"],
    trap: "symptom of + מחלה: a symptom of the flu. לא 'symptom to'. ברבים: symptoms.",
  },
  {
    id: "v-hl-recover",
    word: "recover",
    pos: "v",
    he: "להחלים",
    def: "to become healthy again after being sick or hurt",
    examples: ["It took him two weeks to recover from the surgery.", "She's recovering well after the accident."],
    cloze: "It took him two weeks to ___ from the surgery.",
    collocations: ["recover from", "fully recover", "recover quickly"],
    band: 2,
    tags: ["health"],
    trap: "recover from + מחלה/ניתוח: recover from the flu. לא 'recover of'. בדיבור אפשר גם get better.",
    colloc: { frame: "My grandfather is still recovering ___ his operation.", answer: "from", options: ["from", "of", "after"], whyHe: "recover from — תמיד from." },
  },
  
  {
    id: "v-hl-heal",
    word: "heal",
    pos: "v",
    he: "להגליד, להחלים",
    def: "to become healthy again, especially when a wound or a broken bone gets better",
    examples: ["The cut on my hand took ten days to heal.", "Broken bones heal faster in children."],
    cloze: "The cut on my hand took ten days to ___.",
    collocations: ["heal quickly", "heal completely", "the wound healed"],
    band: 2,
    tags: ["health", "body"],
    trap: "heal = פצע/עצם מחלימים לבד. cure = לרפא מחלה (תרופה או רופא). 'my cut cured' ❌ → my cut healed.",
  },
  {
    id: "v-hl-treatment",
    word: "treatment",
    pos: "n",
    he: "טיפול רפואי",
    def: "medical care given to a sick or injured person",
    examples: ["She's getting treatment for her back problem.", "The new treatment works well for most patients."],
    cloze: "She's getting ___ for her back problem.",
    collocations: ["get treatment", "treatment for", "medical treatment"],
    band: 2,
    tags: ["health"],
    trap: "לקבל טיפול = get / receive treatment. 'do a treatment' ❌. treatment for + הבעיה.",
    colloc: { frame: "He's ___ treatment for a skin problem.", answer: "getting", options: ["getting", "doing", "making"], whyHe: "get treatment = לקבל טיפול." },
  },
  {
    id: "v-hl-treat",
    word: "treat",
    pos: "v",
    he: "לטפל ב",
    def: "to give medical care to a sick or injured person",
    examples: ["The doctors treated him for a broken arm.", "This cream is used to treat skin infections."],
    cloze: "The doctors ___ him for a broken arm.",
    clozeAnswer: "treated",
    collocations: ["treat a patient", "treat for", "treat with antibiotics"],
    band: 3,
    tags: ["health"],
    trap: "הרופא מטפל = the doctor treats. 'the doctor healed me' פחות טבעי. treat גם = לפנק (treat yourself).",
  },
  {
    id: "v-hl-check-up",
    word: "check-up",
    pos: "n",
    he: "בדיקה שגרתית",
    def: "a general medical examination to make sure you are healthy",
    examples: ["I go to the dentist for a check-up twice a year.", "The doctor said everything looked fine at my check-up."],
    cloze: "I go to the dentist for a ___ twice a year.",
    collocations: ["have a check-up", "regular check-up", "annual check-up"],
    band: 3,
    tags: ["health"],
    accept: ["checkup"],
    trap: "עוברים בדיקה = have / get a check-up. 'do a check-up' זה מה שהרופא עושה, לא המטופל.",
  },
  {
    id: "v-hl-insurance",
    word: "insurance",
    pos: "n",
    he: "ביטוח",
    def: "an arrangement in which you pay a company and it pays your costs if something bad happens",
    examples: ["Does your health insurance cover dental care?", "I need to renew my car insurance."],
    cloze: "Does your health ___ cover dental care?",
    collocations: ["health insurance", "insurance company", "insurance covers"],
    band: 2,
    tags: ["health"],
    trap: "insurance לא ספיר: 'health insurances' ❌. insure = לבטח (פועל). ensure = להבטיח — מילה אחרת.",
  },
  {
    id: "v-hl-emergency",
    word: "emergency",
    pos: "n",
    he: "מקרה חירום",
    def: "a serious and dangerous situation that needs action right away",
    examples: ["Call an ambulance only in a real emergency.", "In an emergency, use the stairs, not the elevator."],
    cloze: "Call an ambulance only in a real ___.",
    collocations: ["in an emergency", "emergency room", "medical emergency"],
    band: 1,
    tags: ["health"],
    trap: "חדר מיון = the emergency room (ER). במקרה חירום = in an emergency / in case of emergency. 'emergency case' ❌.",
    colloc: { frame: "They took him to the ___ room after the fall.", answer: "emergency", options: ["emergency", "urgent", "danger"], whyHe: "חדר מיון = emergency room." },
  },
  {
    id: "v-hl-first-aid",
    word: "first aid",
    pos: "n",
    he: "עזרה ראשונה",
    def: "simple medical help you give to someone before a doctor arrives",
    examples: ["Every car should have a first aid kit.", "I took a first aid course last year."],
    cloze: "Every car should have a ___ kit.",
    collocations: ["first aid kit", "first aid course", "give first aid"],
    band: 3,
    tags: ["health"],
    trap: "first aid לא ספיר: 'a first aid' ❌. ערכת עזרה ראשונה = a first aid kit.",
  },
  {
    id: "v-hl-bruise",
    word: "bruise",
    pos: "n",
    he: "חבורה, סימן כחול",
    def: "a dark mark on your skin where you were hit",
    examples: ["I have a big purple bruise on my leg from the door.", "The bruise will disappear in a few days."],
    cloze: "I have a big purple ___ on my leg from the door.",
    collocations: ["a nasty bruise", "covered in bruises", "bruise easily"],
    band: 3,
    tags: ["health", "body"],
    trap: "bruise הוגים 'ברוז'. סימן כחול = a bruise, לא 'blue mark'.",
  },
  {
    id: "v-hl-cut",
    word: "cut",
    pos: "n",
    he: "חתך",
    def: "an injury made by something sharp, like a knife",
    examples: ["I got a small cut on my finger while cooking.", "It's just a cut, it doesn't need stitches."],
    cloze: "I got a small ___ on my finger while cooking.",
    collocations: ["a deep cut", "cuts and bruises", "clean the cut"],
    band: 1,
    tags: ["health", "body"],
    trap: "cut = חתך קטן; wound = פצע חמור. הפועל cut לא משתנה: cut/cut/cut. 'I cutted myself' ❌.",
  },
  {
    id: "v-hl-bleed",
    word: "bleed",
    pos: "v",
    he: "לדמם",
    def: "to lose blood from your body",
    examples: ["My nose started bleeding for no reason.", "The cut bled for a few minutes and then stopped."],
    cloze: "Press on the wound, it's still ___.",
    clozeAnswer: "bleeding",
    collocations: ["bleed heavily", "stop the bleeding", "nosebleed"],
    band: 2,
    tags: ["health", "body"],
    trap: "bleed = פועל (bleed/bled/bled). blood = דם (שם עצם). 'my finger is blooding' ❌ → my finger is bleeding.",
  },
  {
    id: "v-hl-swollen",
    word: "swollen",
    pos: "adj",
    he: "נפוח",
    def: "bigger than normal because of an injury or illness",
    examples: ["My ankle is swollen and I can't put my shoe on.", "His eyes were swollen from crying."],
    cloze: "My ankle is ___ and I can't put my shoe on.",
    collocations: ["swollen ankle", "badly swollen", "swollen glands"],
    band: 3,
    tags: ["health", "body"],
    trap: "נפוח = swollen (תואר). 'my ankle is swelling' פחות טבעי → my ankle is swollen. 'blown up' ❌.",
  },
  {
    id: "v-hl-sick",
    word: "sick",
    pos: "adj",
    he: "חולה",
    def: "not healthy; having an illness",
    examples: ["I was sick all week, so I missed the meeting.", "I feel sick, I think it was the fish."],
    cloze: "I was ___ all week, so I missed the meeting.",
    collocations: ["feel sick", "get sick", "sick day", "call in sick"],
    band: 1,
    tags: ["health"],
    trap: "sick = המילה השגורה באמריקאית. ill = יותר רשמי/חמור. שים לב: I feel sick = גם 'יש לי בחילה'. 'I feel bad' = רגשית (מרגיש רע עם עצמי), לא גופנית!",
    colloc: { frame: "I can't come in today, I'm going to ___ in sick.", answer: "call", options: ["call", "say", "report"], whyHe: "call in sick = להודיע שאתה חולה ולא בא לעבודה." },
  },
  {
    id: "v-hl-ill",
    word: "ill",
    pos: "adj",
    he: "חולה (רשמי)",
    def: "sick; not in good health, often seriously",
    examples: ["His grandmother is seriously ill in the hospital.", "He became ill after eating the seafood."],
    cloze: "His grandmother is seriously ___ in the hospital.",
    collocations: ["seriously ill", "fall ill", "mentally ill"],
    band: 2,
    tags: ["health"],
    trap: "באמריקאית ill לא בא לפני שם עצם: 'an ill man' ❌ → a sick man. ill = חולה, לא 'רע'. seriously ill = חולה קשה.",
  },
  {
    id: "v-hl-throw-up",
    word: "throw up",
    pos: "phr",
    he: "להקיא",
    def: "to bring food up from your stomach through your mouth; to vomit",
    examples: ["I felt so bad that I thought I was going to throw up.", "The kids threw up on the boat."],
    cloze: "I felt so bad that I thought I was going to ___.",
    collocations: ["throw up", "feel like throwing up", "vomit"],
    band: 2,
    tags: ["health", "body"],
    accept: ["vomit"],
    trap: "להקיא = throw up (מדובר) או vomit (רפואי). בחילה = nausea / I feel sick. 'I did vomit' ❌.",
  },
  {
    id: "v-hl-surgery",
    word: "surgery",
    pos: "n",
    he: "ניתוח",
    def: "a medical operation in which a doctor cuts into your body to fix something",
    examples: ["He needs surgery on his knee next month.", "She had heart surgery last year and is fine now."],
    cloze: "He needs ___ on his knee next month.",
    collocations: ["have surgery", "undergo surgery", "heart surgery"],
    band: 3,
    tags: ["health"],
    accept: ["operation", "an operation"],
    trap: "עוברים ניתוח = have surgery / have an operation. 'pass an operation' ❌. המנתח = surgeon. surgery לא ספיר: 'a surgery' ❌.",
    colloc: { frame: "My father ___ surgery on his back last week.", answer: "had", options: ["had", "did", "passed"], whyHe: "have surgery = לעבור ניתוח. do surgery = מה שהמנתח עושה." },
  },
  {
    id: "v-hl-pharmacy",
    word: "pharmacy",
    pos: "n",
    he: "בית מרקחת",
    def: "a store where you buy medicine",
    examples: ["Is there a pharmacy near here? I need to buy some medicine.", "The pharmacy closes at nine."],
    cloze: "Is there a ___ near here? I need to buy some medicine.",
    collocations: ["go to the pharmacy", "24-hour pharmacy", "pharmacist"],
    band: 1,
    tags: ["health"],
    accept: ["drugstore"],
    trap: "בית מרקחת = pharmacy או drugstore (אמריקאי). הרוקח = pharmacist. 'medicine shop' ❌.",
  },
  {
    id: "v-hl-blood-pressure",
    word: "blood pressure",
    pos: "n",
    he: "לחץ דם",
    def: "the force of the blood moving through your body, measured by a doctor",
    examples: ["The nurse checked my blood pressure before the exam.", "My dad takes pills for high blood pressure."],
    cloze: "The nurse checked my ___ before the exam.",
    collocations: ["high blood pressure", "low blood pressure", "check your blood pressure"],
    band: 3,
    tags: ["health", "body"],
    trap: "לחץ דם גבוה = high blood pressure. 'high pressure' לבד = לחץ בעבודה, לא רפואי.",
  },
  {
    id: "v-hl-examine",
    word: "examine",
    pos: "v",
    he: "לבדוק (רופא)",
    def: "to look at someone's body carefully to find out what is wrong",
    examples: ["The doctor examined my throat and said it was just a cold.", "She was examined by two specialists."],
    cloze: "The doctor ___ my throat and said it was just a cold.",
    clozeAnswer: "examined",
    collocations: ["examine a patient", "examine carefully", "physical examination"],
    band: 3,
    tags: ["health"],
    trap: "examine = לבדוק גוף / חומר בקפידה. exam = מבחן. 'the doctor checked me' טוב בדיבור, examined רשמי יותר.",
  },
  {
    id: "v-hl-diagnose",
    word: "diagnose",
    pos: "v",
    he: "לאבחן",
    def: "to find out what illness someone has",
    examples: ["She was diagnosed with diabetes last year.", "It took months to diagnose the problem."],
    cloze: "She was ___ with diabetes last year.",
    clozeAnswer: "diagnosed",
    collocations: ["be diagnosed with", "diagnose a disease", "early diagnosis"],
    band: 4,
    tags: ["health"],
    trap: "אובחן עם = was diagnosed with X, לא 'diagnosed in'. diagnosis = אבחנה (שם עצם).",
    colloc: { frame: "He was diagnosed ___ asthma when he was six.", answer: "with", options: ["with", "in", "by"], whyHe: "be diagnosed with + מחלה." },
  },
  {
    id: "v-hl-sprain",
    word: "sprain",
    pos: "v",
    he: "לנקוע",
    def: "to injure a joint, like your ankle or wrist, by twisting it",
    examples: ["I sprained my ankle playing basketball.", "It's not broken, just sprained."],
    cloze: "I ___ my ankle playing basketball.",
    clozeAnswer: "sprained",
    collocations: ["sprain your ankle", "sprain your wrist", "twist your ankle"],
    band: 4,
    tags: ["health", "body", "sport"],
    accept: ["twist"],
    trap: "נקעתי את הקרסול = I sprained / twisted my ankle. 'my ankle got pulled' ❌ (זה pulled a muscle, לשריר).",
  },
  {
    id: "v-hl-infection",
    word: "infection",
    pos: "n",
    he: "זיהום, דלקת",
    def: "an illness caused by bacteria or a virus in a part of your body",
    examples: ["The doctor said I have an ear infection.", "Wash the cut well to prevent infection."],
    cloze: "The doctor said I have an ear ___.",
    collocations: ["ear infection", "get an infection", "fight an infection"],
    band: 3,
    tags: ["health", "body"],
    trap: "דלקת גרון/אוזניים = throat / ear infection, לא 'inflammation' (זו המילה הרפואית לדלקת, פחות שימושית).",
  },
  {
    id: "v-hl-breathe",
    word: "breathe",
    pos: "v",
    he: "לנשום",
    def: "to take air into your body and let it out again",
    examples: ["It was hard to breathe in the smoky room.", "Breathe slowly and try to calm down."],
    cloze: "It was hard to ___ in the smoky room.",
    collocations: ["breathe deeply", "breathe in / out", "take a deep breath"],
    band: 1,
    tags: ["health", "body"],
    trap: "breathe (פועל, עם e בסוף) ≠ breath (שם עצם). take a deep breath / I can't breathe. 'I can't breath' ❌.",
    colloc: { frame: "Take a deep ___ and relax.", answer: "breath", options: ["breath", "breathe", "breathing"], whyHe: "שם העצם הוא breath (בלי e), הפועל breathe." },
  },
  {
    id: "v-hl-contagious",
    word: "contagious",
    pos: "adj",
    he: "מדבק",
    def: "able to pass from one person to another, like a cold or the flu",
    examples: ["Stay home, the flu is very contagious.", "Don't worry, it's not contagious."],
    cloze: "Stay home, the flu is very ___.",
    collocations: ["highly contagious", "contagious disease", "still contagious"],
    band: 4,
    tags: ["health"],
    trap: "מדבק = contagious (או infectious). 'passing' ❌. גם צחוק יכול להיות contagious.",
  },

  // ---------- Stress, sleep, habits ----------
  {
    id: "v-hl-exhausted",
    word: "exhausted",
    pos: "adj",
    he: "מותש",
    def: "extremely tired",
    examples: ["After the marathon, I was completely exhausted.", "The kids were exhausted after the trip."],
    cloze: "After the marathon, I was completely ___.",
    collocations: ["completely exhausted", "physically exhausted", "exhausting"],
    band: 2,
    tags: ["health", "body", "sport"],
    trap: "exhausted כבר = מאוד עייף, אז לא 'very exhausted' אלא absolutely / completely exhausted. exhausting = מתיש.",
    colloc: { frame: "I'm ___ exhausted, I can't take another step.", answer: "absolutely", options: ["absolutely", "very", "much"], whyHe: "עם תארים 'קיצוניים' כמו exhausted משתמשים ב-absolutely / completely, לא very." },
  },
  {
    id: "v-hl-energetic",
    word: "energetic",
    pos: "adj",
    he: "אנרגטי, מלא מרץ",
    def: "having a lot of energy and activity",
    examples: ["My dog is really energetic in the morning.", "She's an energetic teacher who never sits down."],
    cloze: "My dog is really ___ in the morning.",
    collocations: ["energetic person", "feel energetic", "full of energy"],
    band: 3,
    tags: ["health", "body"],
    trap: "מלא מרץ = energetic או full of energy. 'with energies' ❌ (energy לא ספיר כאן).",
  },
  {
    id: "v-hl-stressed",
    word: "stressed",
    pos: "adj",
    he: "לחוץ",
    def: "worried and unable to relax because of pressure",
    examples: ["I'm so stressed about the exam next week.", "He gets stressed when the kids are late."],
    cloze: "I'm so ___ about the exam next week.",
    collocations: ["stressed about", "stressed out", "get stressed"],
    band: 1,
    tags: ["health"],
    trap: "stressed = לחוץ (אדם). stressful = מלחיץ (מצב). 'I'm stressful' ❌. 'I'm in stress' ❌ → I'm stressed / under stress.",
    colloc: { frame: "It was a very ___ week at work.", answer: "stressful", options: ["stressful", "stressed", "stressing"], whyHe: "השבוע מלחיץ = stressful. האדם לחוץ = stressed." },
  },
  {
    id: "v-hl-relax",
    word: "relax",
    pos: "v",
    he: "להירגע, לנוח",
    def: "to rest and stop worrying",
    examples: ["Sit down and relax for a minute.", "I like to relax with a book on the weekend."],
    cloze: "Sit down and ___ for a minute.",
    collocations: ["relax at home", "relaxed", "relaxing"],
    band: 1,
    tags: ["health"],
    trap: "relax הוא פועל: I need to relax. 'make relax' ❌. relaxed = רגוע (אדם), relaxing = מרגיע (פעילות).",
    colloc: { frame: "A hot bath is very ___ after a long day.", answer: "relaxing", options: ["relaxing", "relaxed", "relax"], whyHe: "האמבטיה מרגיעה = relaxing. האדם רגוע = relaxed." },
  },
  {
    id: "v-hl-chill",
    word: "chill",
    pos: "v",
    he: "לנוח, להירגע (סלנג)",
    def: "to relax and do nothing special (informal)",
    examples: ["Let's just chill at home tonight and watch a movie.", "Chill, it's not a big deal."],
    cloze: "Let's just ___ at home tonight and watch a movie.",
    collocations: ["chill out", "chill at home", "just chill"],
    band: 3,
    tags: ["health"],
    accept: ["chill out"],
    trap: "chill / chill out = להירגע, דיבורי מאוד. chill גם תואר: he's so chill (רגוע). Chill! = תירגע.",
  },
  {
    id: "v-hl-meditate",
    word: "meditate",
    pos: "v",
    he: "לעשות מדיטציה",
    def: "to sit quietly and calm your mind, often by focusing on your breathing",
    examples: ["I meditate for ten minutes every morning.", "She started meditating to deal with stress."],
    cloze: "I ___ for ten minutes every morning.",
    collocations: ["meditate daily", "meditation app", "practice meditation"],
    band: 3,
    tags: ["health"],
    trap: "meditate = פועל. meditation = שם עצם. 'do meditation' תקין גם, 'make meditation' ❌.",
  },
  {
    id: "v-hl-well-being",
    word: "well-being",
    pos: "n",
    he: "רווחה נפשית וגופנית",
    def: "the state of feeling healthy, happy, and comfortable",
    examples: ["Sleep and exercise are important for your well-being.", "The company cares about employee well-being."],
    cloze: "Sleep and exercise are important for your ___.",
    collocations: ["mental well-being", "physical well-being", "sense of well-being"],
    band: 4,
    tags: ["health"],
    accept: ["wellbeing", "wellness"],
    trap: "well-being = רווחה של אדם (גוף ונפש). welfare = רווחה במובן של קצבאות ומדינה. לא לבלבל.",
  },
  {
    id: "v-hl-burn-out",
    word: "burn out",
    pos: "phr",
    he: "להישחק, להישרף",
    def: "to become extremely tired and unable to work because of too much stress",
    examples: ["If you keep working weekends, you're going to burn out.", "A lot of nurses burn out after a few years."],
    cloze: "If you keep working weekends, you're going to ___.",
    collocations: ["burn out", "burned out", "burnout"],
    band: 4,
    tags: ["health"],
    trap: "burn out (שתי מילים) = פועל; burnout (מילה אחת) = שחיקה, שם עצם. אני שחוק = I'm burned out.",
  },
  {
    id: "v-hl-sleep-in",
    word: "sleep in",
    pos: "phr",
    he: "לישון עד מאוחר",
    def: "to sleep later than usual in the morning, on purpose",
    examples: ["It's Saturday, so I'm going to sleep in.", "I never get to sleep in with two small kids."],
    cloze: "It's Saturday, so I'm going to ___.",
    collocations: ["sleep in on weekends", "sleep in late", "sleep late"],
    band: 2,
    tags: ["health"],
    accept: ["sleep late"],
    trap: "sleep in = לישון עד מאוחר בכוונה (שבת). oversleep = לישון יותר מדי בטעות ולאחר.",
  },
  {
    id: "v-hl-oversleep",
    word: "oversleep",
    pos: "v",
    he: "לאחר לקום",
    def: "to sleep longer than you planned, so you are late",
    examples: ["I overslept and missed the bus this morning.", "Set two alarms so you don't oversleep."],
    cloze: "I ___ and missed the bus this morning.",
    clozeAnswer: "overslept",
    collocations: ["oversleep", "overslept again", "set an alarm"],
    band: 3,
    tags: ["health"],
    trap: "אמרתי 'ישנתי יותר מדי ואיחרתי' = I overslept, לא 'I slept too much' (זה אומר שישנתי הרבה, לא שאיחרתי).",
  },
  {
    id: "v-hl-nap",
    word: "nap",
    pos: "n",
    he: "תנומה",
    def: "a short sleep, usually during the day",
    examples: ["I took a short nap after lunch.", "The baby needs a nap in the afternoon."],
    cloze: "I took a short ___ after lunch and felt much better.",
    collocations: ["take a nap", "afternoon nap", "power nap"],
    band: 2,
    tags: ["health"],
    trap: "לחטוף תנומה = take a nap. 'sleep a nap' ❌, 'make a nap' ❌.",
    colloc: { frame: "I'm going to ___ a quick nap before dinner.", answer: "take", options: ["take", "sleep", "make"], whyHe: "take a nap = לנמנם." },
  },
  {
    id: "v-hl-habit",
    word: "habit",
    pos: "n",
    he: "הרגל",
    def: "something you do often, usually without thinking about it",
    examples: ["Biting your nails is a bad habit.", "I got into the habit of walking to work."],
    cloze: "Biting your nails is a bad ___.",
    collocations: ["bad habit", "get into the habit of", "break a habit"],
    band: 1,
    tags: ["health"],
    trap: "יש לי הרגל ל = I have a habit of + -ing, לא 'a habit to'. להיגמל מהרגל = break a habit. לא 'used to' (זה 'רגיל ל').",
    colloc: { frame: "It's hard to ___ a habit you've had for years.", answer: "break", options: ["break", "stop", "cut"], whyHe: "break a habit = להיגמל מהרגל." },
  },

  
  {
    id: "v-hl-addicted-to",
    word: "addicted to",
    pos: "phr",
    he: "מכור ל",
    def: "unable to stop doing or using something",
    examples: ["My brother is addicted to video games.", "I'm addicted to coffee, I can't start the day without it."],
    cloze: "My brother is ___ video games and plays all night.",
    collocations: ["addicted to coffee", "addicted to your phone", "addiction"],
    band: 2,
    tags: ["health"],
    trap: "addicted to + שם עצם או -ing: addicted to sugar, addicted to scrolling. 'addicted for' ❌. התמכרות = addiction.",
    colloc: { frame: "Half the class is addicted ___ their phones.", answer: "to", options: ["to", "for", "on"], whyHe: "addicted to — תמיד to." },
  },

  // ---------- Food & diet ----------
  {
    id: "v-hl-diet",
    word: "diet",
    pos: "n",
    he: "תזונה, דיאטה",
    def: "the food you usually eat; or a plan to eat less to lose weight",
    examples: ["A healthy diet includes lots of vegetables.", "I'm on a diet, so no dessert for me."],
    cloze: "A healthy ___ includes lots of vegetables and fruit.",
    collocations: ["healthy diet", "be on a diet", "go on a diet"],
    band: 1,
    tags: ["health", "food"],
    trap: "diet = גם מה שאתה אוכל בכלל (a balanced diet), לא רק דיאטה. לעשות דיאטה = go on a diet / be on a diet. 'make a diet' ❌.",
    colloc: { frame: "I've decided to ___ on a diet after the holidays.", answer: "go", options: ["go", "make", "do"], whyHe: "go on a diet = להתחיל דיאטה." },
  },
  {
    id: "v-hl-lose-weight",
    word: "lose weight",
    pos: "phr",
    he: "לרדת במשקל",
    def: "to become thinner and weigh less",
    examples: ["I need to lose weight before the wedding.", "She lost ten kilos in six months."],
    cloze: "I need to ___ before the wedding in June.",
    collocations: ["lose weight fast", "lose a few kilos", "weight loss"],
    band: 1,
    tags: ["health", "food", "body"],
    trap: "לרדת במשקל = lose weight. 'go down in weight' ❌. lose עם o אחד! loose = רופף.",
  },
  {
    id: "v-hl-put-on-weight",
    word: "put on weight",
    pos: "phr",
    he: "לעלות במשקל",
    def: "to become heavier",
    examples: ["I've put on weight since I stopped running.", "It's easy to put on weight during the holidays."],
    cloze: "I've ___ since I stopped running.",
    clozeAnswer: "put on weight",
    collocations: ["put on a few kilos", "gain weight", "weight gain"],
    band: 3,
    tags: ["health", "food", "body"],
    accept: ["gain weight"],
    trap: "לעלות במשקל = put on weight / gain weight. 'go up in weight' ❌. 'get fat' — לא מנומס.",
    colloc: { frame: "He ___ a lot of weight when he stopped playing football.", answer: "put on", options: ["put on", "took on", "got on"], whyHe: "put on weight = לעלות במשקל." },
  },
  {
    id: "v-hl-calorie",
    word: "calorie",
    pos: "n",
    he: "קלוריה",
    def: "a unit for measuring how much energy food gives you",
    examples: ["A can of soda has about 150 calories.", "I'm trying not to count calories anymore."],
    cloze: "A can of soda has about 150 ___.",
    clozeAnswer: "calories",
    collocations: ["count calories", "burn calories", "low in calories"],
    band: 2,
    tags: ["health", "food"],
    trap: "calories ספיר: how many calories? לשרוף קלוריות = burn calories. 'calory' ❌ (כתיב).",
  },
  {
    id: "v-hl-nutritious",
    word: "nutritious",
    pos: "adj",
    he: "מזין",
    def: "full of the things your body needs to be healthy",
    examples: ["Eggs are cheap and very nutritious.", "School lunches should be more nutritious."],
    cloze: "Eggs are cheap and very ___.",
    collocations: ["nutritious meal", "nutritious food", "nutrition"],
    band: 3,
    tags: ["health", "food"],
    trap: "nutritious = מזין (תואר). nutrition = תזונה (שם עצם). בדיבור יומיומי healthy נפוץ יותר.",
  },
  {
    id: "v-hl-vegetarian",
    word: "vegetarian",
    pos: "adj",
    he: "צמחוני",
    def: "not eating meat or fish",
    examples: ["My sister is vegetarian, so she doesn't eat meat.", "Do you have any vegetarian options on the menu?"],
    cloze: "My sister is ___, so she doesn't eat meat.",
    collocations: ["vegetarian food", "vegetarian option", "vegan"],
    band: 1,
    tags: ["food"],
    trap: "vegetarian = צמחוני (לא בשר ודגים). vegan = טבעוני (גם לא ביצים וחלב). כשם עצם: I'm a vegetarian.",
  },
  {
    id: "v-hl-overweight",
    word: "overweight",
    pos: "adj",
    he: "בעודף משקל",
    def: "weighing more than is healthy",
    examples: ["The doctor said I'm a little overweight and should exercise more.", "Many kids are overweight because they don't move enough."],
    cloze: "The doctor said I'm a little ___ and should exercise more.",
    collocations: ["slightly overweight", "overweight people", "obese"],
    band: 2,
    tags: ["health", "body", "food"],
    trap: "overweight = המילה המנומסת. fat = פוגע. 'he is with overweight' ❌ → he is overweight.",
  },

  // ---------- Fitness & sport ----------
  {
    id: "v-hl-fit",
    word: "fit",
    pos: "adj",
    he: "בכושר",
    def: "healthy and strong, usually because you exercise",
    examples: ["She runs every day to stay fit.", "I'm not fit enough to run a marathon yet."],
    cloze: "She runs every day to stay ___.",
    collocations: ["keep fit", "stay fit", "fit and healthy"],
    band: 1,
    tags: ["sport", "body", "health"],
    trap: "בכושר = fit / in shape. 'in fitness' ❌. fit גם = מתאים (this shirt fits me), אז שים לב להקשר.",
  },
  {
    id: "v-hl-in-shape",
    word: "in shape",
    pos: "phr",
    he: "בכושר",
    def: "physically fit and healthy",
    examples: ["I want to get in shape before summer.", "He's fifty but he's in great shape."],
    cloze: "I want to get ___ before summer.",
    collocations: ["get in shape", "stay in shape", "in great shape"],
    band: 2,
    tags: ["sport", "body"],
    trap: "להיכנס לכושר = get in shape / get fit. 'in form' ❌ — זה תרגום מעברית.",
    colloc: { frame: "I joined a gym to ___ in shape.", answer: "get", options: ["get", "enter", "go"], whyHe: "get in shape = להיכנס לכושר." },
  },
  {
    id: "v-hl-out-of-shape",
    word: "out of shape",
    pos: "phr",
    he: "לא בכושר",
    def: "not physically fit",
    examples: ["I'm so out of shape that I can't climb the stairs.", "After the winter, the whole team was out of shape."],
    cloze: "I'm so ___ that I can't climb two floors.",
    collocations: ["totally out of shape", "get out of shape", "unfit"],
    band: 3,
    tags: ["sport", "body"],
    accept: ["unfit"],
    trap: "לא בכושר = out of shape (או unfit). 'not in form' ❌. 'weak' = חלש, לא אותו דבר.",
  },
  
  {
    id: "v-hl-exercise",
    word: "exercise",
    pos: "n",
    he: "פעילות גופנית",
    def: "physical activity you do to stay healthy and strong",
    examples: ["Doctors say we need thirty minutes of exercise a day.", "Walking is good exercise for older people."],
    cloze: "Doctors say we need thirty minutes of ___ a day.",
    collocations: ["do exercise", "get some exercise", "regular exercise"],
    band: 1,
    tags: ["sport", "health", "body"],
    trap: "בעברית 'לעשות ספורט', באנגלית do exercise / exercise / work out. 'make sport' ❌. sport לבד = ענף ספורט (a sport like tennis).",
    colloc: { frame: "You should ___ more exercise, at least a walk every day.", answer: "get", options: ["get", "make", "play"], whyHe: "get / do exercise. לא make." },
  },
  
  {
    id: "v-hl-stretch",
    word: "stretch",
    pos: "v",
    he: "למתוח (שרירים)",
    def: "to make your arms, legs, or body as long as possible to loosen your muscles",
    examples: ["Remember to stretch after your workout.", "I stretched my arms and got out of bed."],
    cloze: "Remember to ___ after your workout, or your legs will be sore.",
    collocations: ["stretch your legs", "stretch before running", "do some stretching"],
    band: 2,
    tags: ["sport", "body"],
    trap: "מתיחות = stretching / stretches. 'make stretching' ❌ → do some stretching / stretch.",
  },
  {
    id: "v-hl-lift-weights",
    word: "lift weights",
    pos: "phr",
    he: "להרים משקולות",
    def: "to exercise by lifting heavy metal weights to build muscle",
    examples: ["He lifts weights every morning before work.", "I started lifting weights to get stronger."],
    cloze: "He ___ every morning before work.",
    clozeAnswer: "lifts weights",
    collocations: ["lift weights", "weight training", "build muscle"],
    band: 2,
    tags: ["sport", "body"],
    trap: "להרים משקולות = lift weights. 'make weights' ❌, 'do weights' — דיבורי, אפשרי.",
  },
  {
    id: "v-hl-gym",
    word: "gym",
    pos: "n",
    he: "חדר כושר",
    def: "a place with machines and equipment where people go to exercise",
    examples: ["I joined a gym near my office.", "She goes to the gym every day after work."],
    cloze: "I joined a ___ near my office.",
    collocations: ["go to the gym", "join a gym", "gym membership"],
    band: 1,
    tags: ["sport"],
    trap: "תמיד עם the: go to the gym, at the gym. 'go to gym' ❌ (לא כמו go to school / work).",
    colloc: { frame: "I go to ___ gym twice a week.", answer: "the", options: ["the", "a", "-"], whyHe: "go to the gym — תמיד עם the." },
  },
  {
    id: "v-hl-coach",
    word: "coach",
    pos: "n",
    he: "מאמן",
    def: "a person who trains a sports team or player",
    examples: ["The coach made us run ten laps.", "She's the new coach of the women's team."],
    cloze: "The ___ made us run ten laps after we lost.",
    collocations: ["head coach", "football coach", "coach a team"],
    band: 1,
    tags: ["sport"],
    trap: "coach = מאמן של קבוצה או ספורטאי. trainer = מאמן כושר אישי (personal trainer). 'the trainer of the team' ❌.",
  },
  {
    id: "v-hl-score",
    word: "score",
    pos: "v",
    he: "להבקיע, לקלוע",
    def: "to get a point or goal in a game",
    examples: ["Who scored the winning goal?", "She scored twenty points in the second half."],
    cloze: "Who ___ the winning goal last night?",
    clozeAnswer: "scored",
    collocations: ["score a goal", "score points", "What's the score?"],
    band: 1,
    tags: ["sport"],
    trap: "מבקיעים גול = score a goal, לא 'make a goal' ולא 'put a goal'. What's the score? = מה התוצאה?",
    colloc: { frame: "He ___ two goals in the last ten minutes.", answer: "scored", options: ["scored", "made", "put"], whyHe: "score a goal = להבקיע." },
  },
  {
    id: "v-hl-beat",
    word: "beat",
    pos: "v",
    he: "לנצח (יריב)",
    def: "to win against a person or team",
    examples: ["We beat them 3-1 in the final.", "Nobody has beaten her at chess this year."],
    cloze: "We ___ them 3-1 in the final.",
    collocations: ["beat a team", "beat easily", "beat/beat/beaten"],
    band: 2,
    tags: ["sport"],
    trap: "beat + יריב (אדם או קבוצה): We beat Maccabi. win + משחק/תחרות/פרס: We won the game. 'We won Maccabi' ❌.",
    colloc: { frame: "Brazil ___ Argentina 2-0 last night.", answer: "beat", options: ["beat", "won", "defeated over"], whyHe: "beat + יריב. won + game/match." },
  },
  {
    id: "v-hl-win",
    word: "win",
    pos: "v",
    he: "לנצח, לזכות",
    def: "to be the best or first in a game, race, or competition",
    examples: ["I hope our team will win the cup this year.", "She won first prize in the competition."],
    cloze: "I hope our team will ___ the cup this year.",
    collocations: ["win a game", "win a prize", "win/won/won"],
    band: 1,
    tags: ["sport"],
    trap: "win + משחק/פרס/תחרות: win the match, win a medal. לא win + יריב — בשביל זה beat. 'to win against Barcelona' תקין, 'to win Barcelona' ❌.",
    colloc: { frame: "Who ___ the game last night?", answer: "won", options: ["won", "beat", "earned"], whyHe: "win the game (משחק), beat the team (יריב)." },
  },
  {
    id: "v-hl-lose",
    word: "lose",
    pos: "v",
    he: "להפסיד",
    def: "to not win a game or competition",
    examples: ["If we lose tonight, we're out of the tournament.", "They lost to Barcelona 4-0."],
    cloze: "If we ___ tonight, we're out of the tournament.",
    collocations: ["lose a game", "lose to", "lose/lost/lost"],
    band: 1,
    tags: ["sport"],
    trap: "הפסדנו ל = we lost to (או lost against). lose עם o אחד! loose (שני o) = רופף. 'we lost from them' ❌.",
    colloc: { frame: "We lost ___ the best team in the league.", answer: "to", options: ["to", "from", "by"], whyHe: "lose to + היריב." },
  },
  {
    id: "v-hl-draw",
    word: "draw",
    pos: "n",
    he: "תיקו",
    def: "a result in which both teams have the same score",
    examples: ["The game ended in a 2-2 draw.", "A draw is enough for us to go to the final."],
    cloze: "The game ended in a 2-2 ___.",
    collocations: ["end in a draw", "a goalless draw", "a tie"],
    band: 3,
    tags: ["sport"],
    accept: ["tie"],
    trap: "תיקו = a draw (גם tie באמריקאית). המשחק הסתיים בתיקו = the game ended in a draw. 'ended in equal' ❌. draw גם = לצייר.",
  },
  {
    id: "v-hl-match",
    word: "match",
    pos: "n",
    he: "משחק (ספורט)",
    def: "a sports game between two teams or players",
    examples: ["Are you watching the match tonight?", "It was the best tennis match I've ever seen."],
    cloze: "Are you watching the ___ tonight?",
    collocations: ["football match", "win a match", "a big game"],
    band: 1,
    tags: ["sport"],
    accept: ["game"],
    trap: "match = בריטי ולטניס/כדורגל; game = אמריקאי ולרוב ענפי הספורט. שניהם תקינים. 'a football play' ❌ (play = הצגה).",
  },
  {
    id: "v-hl-referee",
    word: "referee",
    pos: "n",
    he: "שופט (ספורט)",
    def: "the person who makes sure the players follow the rules in a game",
    examples: ["The referee gave him a red card.", "The fans were angry with the referee."],
    cloze: "The ___ gave him a red card in the first half.",
    collocations: ["the referee blew the whistle", "the ref", "argue with the referee"],
    band: 3,
    tags: ["sport"],
    accept: ["ref"],
    trap: "שופט במשחק = referee (בקיצור ref). judge = שופט בבית משפט או בתחרות כמו ריקוד/בישול. 'the judge of the game' ❌.",
  },
  {
    id: "v-hl-cheer",
    word: "cheer",
    pos: "v",
    he: "לעודד, להריע",
    def: "to shout to show support for a team or player",
    examples: ["We went to the stadium to cheer for our team.", "The crowd cheered when she crossed the line."],
    cloze: "We went to the stadium to ___ for our team.",
    collocations: ["cheer for a team", "cheer loudly", "cheer someone up"],
    band: 3,
    tags: ["sport"],
    trap: "מעודדים קבוצה = cheer for a team (או root for). 'cheer to' ❌. cheer someone up = לעודד מישהו עצוב — משמעות אחרת.",
    colloc: { frame: "Which team do you cheer ___?", answer: "for", options: ["for", "to", "on"], whyHe: "cheer for / root for = לעודד." },
  },
  {
    id: "v-hl-training",
    word: "training",
    pos: "n",
    he: "אימונים",
    def: "the process of preparing for a sport or a job by practicing",
    examples: ["The players have training every morning at seven.", "She's in training for the marathon."],
    cloze: "The players have ___ every morning at seven.",
    collocations: ["in training for", "training session", "hard training"],
    band: 1,
    tags: ["sport"],
    trap: "training לא ספיר: 'a training' ❌ → a training session. אימון של קבוצה באמריקאית = practice: I have soccer practice today.",
    colloc: { frame: "I can't come, I have a training ___ tonight.", answer: "session", options: ["session", "meeting", "time"], whyHe: "אימון אחד = a training session או practice." },
  },
  {
    id: "v-hl-practice",
    word: "practice",
    pos: "v",
    he: "לתרגל, להתאמן",
    def: "to do something regularly so you get better at it",
    examples: ["You need to practice every day if you want to improve.", "She practices the piano for an hour a day."],
    cloze: "You need to ___ every day if you want to improve.",
    collocations: ["practice every day", "practice speaking", "practice makes perfect"],
    band: 1,
    tags: ["sport"],
    trap: "practice = לתרגל, ובאמריקאית גם 'אימון' (I have practice at five). תמיד עם c באמריקאית. 'make practice' ❌ → practice / have practice.",
    colloc: { frame: "I practice ___ English with my neighbor every Sunday.", answer: "speaking", options: ["speaking", "to speak", "speak"], whyHe: "practice + -ing, לא practice to." },
  },
  {
    id: "v-hl-jog",
    word: "jog",
    pos: "v",
    he: "לרוץ ריצה קלה",
    def: "to run slowly for exercise",
    examples: ["I jog in the park before work.", "We jogged along the beach for half an hour."],
    cloze: "I ___ in the park every morning before work.",
    collocations: ["go jogging", "go for a jog", "jog slowly"],
    band: 1,
    tags: ["sport", "body"],
    trap: "יוצאים לריצה = go jogging / go for a jog / go for a run. 'make jogging' ❌.",
    colloc: { frame: "Do you want to ___ jogging with me tomorrow?", answer: "go", options: ["go", "make", "do"], whyHe: "go + -ing לפעילויות: go jogging, go swimming." },
  },
];
