import type { VocabItem } from "@/lib/types";

export const MONEY_TECH_SOCIETY: VocabItem[] = [
  // ---------- money & banking ----------
  {
    id: "v-mn-afford",
    word: "afford",
    pos: "v",
    he: "להרשות לעצמך (כלכלית)",
    def: "to have enough money to buy or do something",
    examples: ["We can't afford a new car right now.", "I can afford to eat out once a week."],
    cloze: "They can't ___ to fly business class.",
    collocations: ["can't afford to do", "afford a house"],
    band: 2,
    tags: ["money"],
    trap: "afford בא כמעט תמיד עם can / can't: I can't afford it. אחרי afford בא to + פועל: afford to buy, לא afford buying.",
    colloc: { frame: "We can't ___ to lose this customer.", answer: "afford", options: ["afford", "allow", "effort"], whyHe: "can't afford to = לא יכולים להרשות לעצמנו. allow = להרשות למישהו אחר." },
  },
  {
    id: "v-mn-cost",
    word: "cost",
    pos: "v",
    he: "לעלות (מחיר)",
    def: "to have a particular price",
    examples: ["How much does this jacket cost?", "The repair cost me 400 shekels."],
    cloze: "The tickets ___ 80 shekels each.",
    collocations: ["cost a fortune", "cost me 50 shekels"],
    band: 1,
    tags: ["money"],
    trap: "שאלה: How much does it cost? (לא 'How much it costs?'). בעבר cost נשאר cost: It cost me 50 shekels.",
  },
  {
    id: "v-mn-worth",
    word: "worth",
    pos: "adj",
    he: "שווה",
    def: "having a certain value; good enough to justify the price or effort",
    examples: ["The phone is worth about 2,000 shekels.", "Is the course worth the money?"],
    cloze: "The view from the top was ___ the long climb.",
    collocations: ["worth it", "worth the money", "worth trying"],
    band: 2,
    tags: ["money"],
    trap: "worth הוא לא פועל: It's worth it / It's worth trying, לא 'it worths'. אחרי worth בא שם עצם או -ing.",
    colloc: { frame: "Don't buy it, it's not ___ the money.", answer: "worth", options: ["worth", "valued", "cost"], whyHe: "be worth + שם עצם = שווה את. הפועל הוא be, לא worth." },
  },
  {
    id: "v-mn-bill",
    word: "bill",
    pos: "n",
    he: "חשבון (לתשלום)",
    def: "a piece of paper that shows how much you must pay",
    examples: ["The electricity bill was higher than usual this month.", "Can we get the bill, please?"],
    cloze: "I forgot to pay the phone ___ last month.",
    collocations: ["pay a bill", "electricity bill", "split the bill"],
    band: 1,
    tags: ["money"],
    trap: "במסעדה בארה\"ב מבקשים the check, בבריטניה the bill. חשבון בנק זה account, לא bill.",
    colloc: { frame: "Let's ___ the bill, it's easier.", answer: "split", options: ["split", "cut", "divide"], whyHe: "split the bill = לחלק את החשבון. divide נשמע פורמלי ולא טבעי כאן." },
  },
  {
    id: "v-mn-invoice",
    word: "invoice",
    pos: "n",
    he: "חשבונית",
    def: "a document from a business that lists what you bought and what you must pay",
    examples: ["Please send me an invoice for the work.", "The invoice is due in 30 days."],
    cloze: "The plumber emailed me an ___ after he finished.",
    collocations: ["send an invoice", "pay an invoice"],
    band: 3,
    tags: ["money"],
  },
  {
    id: "v-mn-fee",
    word: "fee",
    pos: "n",
    he: "עמלה, דמי-",
    def: "money you pay for a service or to join something",
    examples: ["The bank charges a monthly fee on this account.", "There's a small fee for late returns."],
    cloze: "The gym has a registration ___ of 200 shekels.",
    collocations: ["pay a fee", "charge a fee", "late fee"],
    band: 2,
    tags: ["money"],
    colloc: { frame: "Most banks ___ a fee for international transfers.", answer: "charge", options: ["charge", "take", "ask"], whyHe: "charge a fee = לגבות עמלה. 'take a fee' לא טבעי." },
  },
  {
    id: "v-mn-charge-n",
    word: "charge",
    pos: "n",
    he: "חיוב, תשלום",
    def: "an amount of money you have to pay for something",
    examples: ["Delivery is free of charge.", "There's an extra charge for checked bags."],
    cloze: "Cancellation is free of ___ up to 24 hours before.",
    collocations: ["free of charge", "extra charge", "service charge"],
    band: 3,
    tags: ["money"],
    colloc: { frame: "Kids under five can enter free of ___.", answer: "charge", options: ["charge", "cost", "payment"], whyHe: "free of charge = ביטוי קבוע: ללא תשלום." },
  },
  {
    id: "v-mn-tip",
    word: "tip",
    pos: "n",
    he: "טיפ, תשר",
    def: "extra money you give to a waiter, driver, etc. for good service",
    examples: ["We left a 15% tip for the waiter.", "In the US, a 20% tip is normal at restaurants."],
    cloze: "The service was great, so we left a big ___.",
    collocations: ["leave a tip", "a generous tip"],
    band: 2,
    tags: ["money"],
    colloc: { frame: "The service was terrible, so we didn't ___ a tip.", answer: "leave", options: ["leave", "put", "pay"], whyHe: "leave a tip = להשאיר טיפ. 'pay a tip' לא טבעי." },
  },
  {
    id: "v-mn-loan",
    word: "loan",
    pos: "n",
    he: "הלוואה",
    def: "money you borrow and must pay back, usually with interest",
    examples: ["They took out a loan to buy the apartment.", "I'm still paying off my student loan."],
    cloze: "The bank approved our ___ in two days.",
    collocations: ["take out a loan", "pay off a loan", "student loan"],
    band: 2,
    tags: ["money"],
    trap: "לוקחים הלוואה = take out a loan. loan הוא שם עצם; הפועל 'להלוות' הוא lend.",
    colloc: { frame: "We had to ___ out a loan to cover the costs.", answer: "take", options: ["take", "get", "make"], whyHe: "take out a loan = לקחת הלוואה. ביטוי קבוע עם out." },
  },

  {
    id: "v-mn-owe",
    word: "owe",
    pos: "v",
    he: "להיות חייב (כסף)",
    def: "to need to pay money back to someone",
    examples: ["I owe you 50 shekels for the pizza.", "How much do we still owe on the car?"],
    cloze: "You paid for lunch, so I ___ you a coffee.",
    collocations: ["owe someone money", "owe an apology"],
    band: 3,
    tags: ["money"],
    trap: "owe somebody something: I owe you 50 (לא 'I owe to you'). בעברית 'אני חייב לך' – באנגלית בלי to.",
  },
  {
    id: "v-mn-debt",
    word: "debt",
    pos: "n",
    he: "חוב",
    def: "money that you owe to someone",
    examples: ["He's still in debt after buying the house.", "It took them years to pay off their debts."],
    cloze: "Many students finish college with a lot of ___.",
    collocations: ["in debt", "pay off a debt", "get into debt"],
    band: 2,
    tags: ["money"],
    colloc: { frame: "They are deeply ___ debt after the wedding.", answer: "in", options: ["in", "on", "with"], whyHe: "be in debt = להיות בחובות. הפרפוזיציה היא in." },
  },
  {
    id: "v-mn-save-up",
    word: "save up",
    pos: "phr",
    he: "לחסוך (למטרה)",
    def: "to keep money over time so you can buy something",
    examples: ["I'm saving up for a trip to Japan.", "It took him a year to save up for the bike."],
    cloze: "We're ___ for a new kitchen.",
    clozeAnswer: "saving up",
    collocations: ["save up for something"],
    band: 2,
    tags: ["money"],
    colloc: { frame: "She's saving up ___ a car.", answer: "for", options: ["for", "to", "on"], whyHe: "save up for + שם עצם. לפני פועל: save up to buy." },
  },
  {
    id: "v-mn-savings",
    word: "savings",
    pos: "n",
    he: "חסכונות",
    def: "money you have saved, usually in a bank",
    examples: ["We used our savings to pay for the wedding.", "I have a small savings account for emergencies."],
    cloze: "The trip cost me all my ___.",
    collocations: ["savings account", "life savings", "dip into savings"],
    band: 2,
    tags: ["money"],
    trap: "savings תמיד ברבים כשמדברים על כסף שחסכת: my savings, לא 'my saving'.",
  },
  {
    id: "v-mn-spend",
    word: "spend",
    pos: "v",
    he: "להוציא (כסף), לבלות (זמן)",
    def: "to use money to buy things, or to use time doing something",
    examples: ["I spent too much on clothes this month.", "We spent the whole weekend at the beach."],
    cloze: "How much did you ___ on the gift?",
    collocations: ["spend money on", "spend time doing", "spend a fortune"],
    band: 1,
    tags: ["money"],
    trap: "spend money ON something (לא for). spend time DOING (לא to do): I spent an hour waiting.",
    colloc: { frame: "He spends a lot of money ___ video games.", answer: "on", options: ["on", "for", "in"], whyHe: "spend money on = להוציא כסף על. for כאן שגוי." },
  },
  {
    id: "v-mn-waste",
    word: "waste",
    pos: "v",
    he: "לבזבז",
    def: "to use money, time, or things badly, without a good result",
    examples: ["Don't waste your money on that app.", "We wasted an hour looking for parking."],
    cloze: "I ___ 200 shekels on shoes I never wear.",
    clozeAnswer: "wasted",
    collocations: ["waste money on", "waste time", "a waste of time"],
    band: 2,
    tags: ["money"],
    trap: "בעברית 'לבזבז' זה גם spend וגם waste. spend = להוציא (ניטרלי), waste = לבזבז לחינם (שלילי).",
    colloc: { frame: "That meeting was a complete ___ of time.", answer: "waste", options: ["waste", "loss", "spend"], whyHe: "a waste of time = בזבוז זמן. loss = הפסד, לא מתאים כאן." },
  },
  
  {
    id: "v-mn-income",
    word: "income",
    pos: "n",
    he: "הכנסה",
    def: "the money a person or family receives, usually from work",
    examples: ["Their income dropped when she stopped working.", "Rent takes a third of my monthly income."],
    cloze: "Families with a low ___ can get help with rent.",
    collocations: ["low income", "monthly income", "source of income"],
    band: 3,
    tags: ["money"],
  },
  {
    id: "v-mn-tax",
    word: "tax",
    pos: "n",
    he: "מס",
    def: "money you must pay to the government from what you earn or buy",
    examples: ["Is that price with or without tax?", "We pay a lot of tax on fuel."],
    cloze: "You have to pay ___ on any money you earn.",
    collocations: ["pay tax", "income tax", "tax return"],
    band: 2,
    tags: ["money"],
    colloc: { frame: "Everyone with a salary has to ___ income tax.", answer: "pay", options: ["pay", "give", "spend"], whyHe: "pay tax = לשלם מס. לא give ולא spend." },
  },
  {
    id: "v-mn-invest",
    word: "invest",
    pos: "v",
    he: "להשקיע",
    def: "to put money into something to make more money later",
    examples: ["She invested her savings in an index fund.", "The company is investing in new technology."],
    cloze: "Many people ___ in real estate here.",
    collocations: ["invest in something", "invest money", "invest time"],
    band: 3,
    tags: ["money"],
    trap: "invest IN: invest in a company / in stocks (לא invest on).",
    colloc: { frame: "He decided to invest ___ his friend's startup.", answer: "in", options: ["in", "on", "at"], whyHe: "invest in = להשקיע ב-. on ו-at שגויים." },
  },
  
  {
    id: "v-mn-withdraw",
    word: "withdraw",
    pos: "v",
    he: "למשוך (כסף)",
    def: "to take money out of a bank account",
    examples: ["I withdrew 300 shekels from the ATM.", "You can't withdraw more than 2,000 a day."],
    cloze: "I need to ___ some cash before the market.",
    collocations: ["withdraw money from", "withdraw cash"],
    band: 4,
    tags: ["money"],
    trap: "מושכים כסף = withdraw money, לא 'pull money'. ההפך: deposit (להפקיד). עבר: withdrew.",
  },
  {
    id: "v-mn-cash",
    word: "cash",
    pos: "n",
    he: "מזומן",
    def: "money in coins and notes, not cards",
    examples: ["The market stalls only take cash.", "I paid in cash and got a small discount."],
    cloze: "Do you have any ___ on you? The machine is broken.",
    collocations: ["pay in cash", "cash only", "take out cash"],
    band: 1,
    tags: ["money"],
    trap: "cash לא ספיר: some cash, לא 'a cash' או 'cashes'. משלמים in cash / pay cash.",
    colloc: { frame: "They don't take cards, so we paid ___ cash.", answer: "in", options: ["in", "with", "by"], whyHe: "pay in cash אבל pay by card. שני הביטויים הקבועים חשובים." },
  },
  {
    id: "v-mn-change",
    word: "change",
    pos: "n",
    he: "עודף; כסף קטן",
    def: "the money you get back when you pay more than the price; coins",
    examples: ["Here's your change, 12 shekels.", "Do you have change for a 200?"],
    cloze: "Keep the ___, thanks.",
    collocations: ["keep the change", "small change", "change for a 100"],
    band: 1,
    tags: ["money"],
    trap: "עודף = change, לא 'rest'. 'Keep the change' = תשאיר את העודף. אין 'changes' במשמעות זו.",
  },
  
  {
    id: "v-mn-economical",
    word: "economical",
    pos: "adj",
    he: "חסכוני",
    def: "not costing much money or fuel; not wasteful",
    examples: ["This car is very economical, it uses very little fuel.", "Buying in bulk is more economical."],
    cloze: "A smaller apartment would be more ___ for us.",
    collocations: ["economical car", "economical way"],
    band: 4,
    tags: ["money"],
    trap: "economical = חסכוני (מכונית, פתרון). economic = כלכלי (economic crisis, economic growth). לא להחליף ביניהם.",
  },
  {
    id: "v-mn-broke",
    word: "broke",
    pos: "adj",
    he: "מרושש, בלי כסף",
    def: "having no money (informal)",
    examples: ["I can't go out tonight, I'm totally broke.", "We were broke after the trip."],
    cloze: "He's always ___ by the end of the month.",
    collocations: ["be broke", "go broke", "flat broke"],
    band: 3,
    tags: ["money"],
    trap: "I'm broke = אין לי כסף. I'm broken = אני שבור (רגשית). broke כאן הוא שם תואר, לא עבר של break.",
  },

  // ---------- shopping & consumer life ----------
  {
    id: "v-mn-expensive",
    word: "expensive",
    pos: "adj",
    he: "יקר",
    def: "costing a lot of money",
    examples: ["That restaurant is too expensive for us.", "Rent in Tel Aviv is really expensive."],
    cloze: "The hotel was nice but very ___.",
    collocations: ["too expensive", "expensive taste"],
    band: 1,
    tags: ["shopping"],
    trap: "דבר הוא expensive, מחיר הוא high: 'The price is high', לא 'the price is expensive'. באותו אופן: המחיר low, לא cheap.",
  },
  {
    id: "v-mn-pricey",
    word: "pricey",
    pos: "adj",
    he: "יקר (בדיבור)",
    def: "a bit expensive (informal)",
    examples: ["The coffee there is good but a bit pricey.", "Those sneakers are pricey for what they are."],
    cloze: "The menu looks great, but it's kind of ___.",
    collocations: ["a bit pricey", "kind of pricey"],
    band: 3,
    tags: ["shopping"],
  },
  {
    id: "v-mn-cheap",
    word: "cheap",
    pos: "adj",
    he: "זול",
    def: "costing little money",
    examples: ["Flights are cheaper in November.", "I bought a cheap phone that works fine."],
    cloze: "The market is the ___ place to buy vegetables.",
    clozeAnswer: "cheapest",
    collocations: ["cheap flights", "dirt cheap"],
    band: 1,
    tags: ["shopping"],
    trap: "cheap יכול להישמע גם 'זול ובאיכות נמוכה'. כמחמאה עדיף affordable / good value. וגם: a cheap person = קמצן.",
  },
  {
    id: "v-mn-bargain",
    word: "bargain",
    pos: "n",
    he: "מציאה",
    def: "something you buy for much less than its normal price",
    examples: ["This jacket was a real bargain, only 90 shekels.", "You can find great bargains at the end of the season."],
    cloze: "At that price, the laptop is a ___.",
    collocations: ["a real bargain", "bargain price", "hunt for bargains"],
    band: 2,
    tags: ["shopping"],
    colloc: { frame: "Half price? That's a ___ bargain.", answer: "real", options: ["real", "true", "big"], whyHe: "a real bargain = מציאה אמיתית. big/true bargain פחות טבעי." },
  },
  {
    id: "v-mn-discount",
    word: "discount",
    pos: "n",
    he: "הנחה",
    def: "a reduction in the usual price",
    examples: ["Students get a 10% discount on tickets.", "Is there any discount if I pay cash?"],
    cloze: "They gave us a 20% ___ because of the scratch.",
    collocations: ["get a discount", "give a discount", "discount on"],
    band: 1,
    tags: ["shopping"],
    trap: "discount ON something: a discount on shoes. מקבלים הנחה = get a discount; נותנים = give a discount (לא 'make a discount').",
    colloc: { frame: "Students ___ a 10% discount with a card.", answer: "get", options: ["get", "take", "make"], whyHe: "get a discount = לקבל הנחה. take/make שגויים." },
  },
  {
    id: "v-mn-on-sale",
    word: "on sale",
    pos: "phr",
    he: "במבצע",
    def: "being sold at a lower price than usual",
    examples: ["These boots are on sale this week.", "I only buy clothes when they're on sale."],
    cloze: "The TV was ___, so we bought two.",
    collocations: ["go on sale", "on sale for half price"],
    band: 2,
    tags: ["shopping"],
    trap: "on sale = במבצע (מחיר מוזל). for sale = למכירה (שלט על בית או רכב). לא לבלבל.",
  },
  
  {
    id: "v-mn-refund",
    word: "refund",
    pos: "n",
    he: "החזר כספי",
    def: "money that is given back to you when you return something",
    examples: ["I asked for a refund because the phone didn't work.", "You'll get a full refund within 14 days."],
    cloze: "The store gave me a full ___ without any questions.",
    collocations: ["get a refund", "full refund", "ask for a refund"],
    band: 2,
    tags: ["shopping"],
    colloc: { frame: "If the show is canceled, you'll get a full ___.", answer: "refund", options: ["refund", "return", "payback"], whyHe: "refund = החזר כספי. return = החזרת המוצר, לא הכסף." },
  },
  {
    id: "v-mn-exchange",
    word: "exchange",
    pos: "v",
    he: "להחליף (מוצר)",
    def: "to return something to a store and get a different one",
    examples: ["Can I exchange this for a bigger size?", "They only exchange items within 30 days."],
    cloze: "I want to ___ these shoes, they're too small.",
    collocations: ["exchange something for", "exchange rate"],
    band: 3,
    tags: ["shopping"],
    trap: "exchange X FOR Y (לא with). return = להחזיר ולקבל כסף, exchange = להחליף במוצר אחר.",
  },
  {
    id: "v-mn-warranty",
    word: "warranty",
    pos: "n",
    he: "אחריות (על מוצר)",
    def: "a written promise to repair or replace a product if it breaks",
    examples: ["The laptop comes with a two-year warranty.", "Is the screen still under warranty?"],
    cloze: "The repair was free because the phone was under ___.",
    collocations: ["under warranty", "two-year warranty", "extended warranty"],
    band: 3,
    tags: ["shopping"],
    trap: "אחריות על מוצר = warranty. responsibility = אחריות במובן של מחויבות. 'The phone has responsibility' שגוי.",
    colloc: { frame: "Don't worry, the fridge is still ___ warranty.", answer: "under", options: ["under", "in", "with"], whyHe: "under warranty = באחריות. הפרפוזיציה היא under." },
  },
  
  {
    id: "v-mn-deliver",
    word: "deliver",
    pos: "v",
    he: "לשלוח, למסור (משלוח)",
    def: "to bring goods or letters to a person or place",
    examples: ["They deliver for free within the city.", "The package was delivered while I was at work."],
    cloze: "Do you ___ to this address?",
    collocations: ["deliver a package", "free delivery", "deliver on time"],
    band: 2,
    tags: ["shopping"],
  },
  {
    id: "v-mn-in-stock",
    word: "in stock",
    pos: "phr",
    he: "במלאי",
    def: "available in the store now",
    examples: ["Is this model in stock?", "Sorry, that color isn't in stock right now."],
    cloze: "Let me check if that size is ___.",
    collocations: ["in stock", "out of stock", "back in stock"],
    band: 3,
    tags: ["shopping"],
    trap: "במלאי = in stock; אזל מהמלאי = out of stock. 'in the stock' שגוי – בלי the.",
  },
  {
    id: "v-mn-sold-out",
    word: "sold out",
    pos: "adj",
    he: "אזל, נמכר כולו",
    def: "with nothing left to buy because everything was sold",
    examples: ["The concert was sold out in an hour.", "Sorry, that size is sold out."],
    cloze: "Tickets are completely ___, we were too late.",
    collocations: ["completely sold out", "sell out fast"],
    band: 2,
    tags: ["shopping"],
  },
  {
    id: "v-mn-overpriced",
    word: "overpriced",
    pos: "adj",
    he: "יקר מדי (לא שווה)",
    def: "costing more than it should",
    examples: ["The food at the airport is totally overpriced.", "Nice apartment, but it's overpriced for the area."],
    cloze: "Those headphones are ___, you can get the same for half.",
    collocations: ["overpriced restaurant", "hugely overpriced"],
    band: 4,
    tags: ["shopping"],
  },
  {
    id: "v-mn-rip-off",
    word: "rip-off",
    pos: "n",
    he: "עושק, 'שוד'",
    def: "something that costs much more than it is worth (informal)",
    examples: ["Forty shekels for a coffee? What a rip-off!", "The tour was a total rip-off."],
    cloze: "Two hundred for parking? That's a ___!",
    collocations: ["a total rip-off", "what a rip-off"],
    band: 4,
    tags: ["shopping"],
    trap: "rip-off (שם עצם) = עושק. הפועל: rip someone off = לעשוק מישהו: They ripped us off.",
  },

  // ---------- technology & internet ----------

  {
    id: "v-mn-password",
    word: "password",
    pos: "n",
    he: "סיסמה",
    def: "a secret word or set of characters you use to enter an account",
    examples: ["I forgot my password again.", "Use a strong password with numbers and symbols."],
    cloze: "Never share your ___ with anyone.",
    collocations: ["strong password", "reset a password", "enter your password"],
    band: 1,
    tags: ["tech"],
    colloc: { frame: "Click here to ___ your password.", answer: "reset", options: ["reset", "renew", "repair"], whyHe: "reset a password = לאפס סיסמה. renew = לחדש (מנוי), repair = לתקן." },
  },
  {
    id: "v-mn-update",
    word: "update",
    pos: "v",
    he: "לעדכן",
    def: "to change something so it has the newest information or version",
    examples: ["You should update the app to fix the bug.", "I'll update you when I hear from them."],
    cloze: "My phone asks me to ___ the software every week.",
    collocations: ["update an app", "software update", "keep someone updated"],
    band: 2,
    tags: ["tech"],
    trap: "update somebody = לעדכן מישהו (בלי with): I'll update you. שם העצם: an update (עדכון).",
  },
  {
    id: "v-mn-download",
    word: "download",
    pos: "v",
    he: "להוריד (קובץ)",
    def: "to copy a file from the internet to your device",
    examples: ["I downloaded the movie to watch on the plane.", "It takes a minute to download the app."],
    cloze: "You can ___ the form from their website.",
    collocations: ["download a file", "download an app"],
    band: 1,
    tags: ["tech"],
    trap: "download = להוריד מהאינטרנט אליך. upload = להעלות ממך לאינטרנט. 'download to the cloud' שגוי.",
  },
  {
    id: "v-mn-upload",
    word: "upload",
    pos: "v",
    he: "להעלות (קובץ)",
    def: "to copy a file from your device to the internet",
    examples: ["She uploaded the photos to the shared album.", "Please upload your CV as a PDF."],
    cloze: "It took ages to ___ the video because of the slow Wi-Fi.",
    collocations: ["upload a photo", "upload to"],
    band: 2,
    tags: ["tech"],
  },
  {
    id: "v-mn-install",
    word: "install",
    pos: "v",
    he: "להתקין",
    def: "to put a program on a device, or equipment in a place",
    examples: ["I installed a new app for tracking expenses.", "They're installing solar panels on the roof."],
    cloze: "Do I need to ___ anything to join the call?",
    collocations: ["install an app", "install software", "uninstall"],
    band: 3,
    tags: ["tech"],
  },
  {
    id: "v-mn-device",
    word: "device",
    pos: "n",
    he: "מכשיר",
    def: "a machine or tool, especially an electronic one like a phone or tablet",
    examples: ["The app works on any device.", "Turn off all electronic devices before takeoff."],
    cloze: "You can log in from up to five ___ at once.",
    clozeAnswer: "devices",
    collocations: ["mobile device", "electronic device"],
    band: 3,
    tags: ["tech"],
  },
  {
    id: "v-mn-screen",
    word: "screen",
    pos: "n",
    he: "מסך",
    def: "the flat part of a phone, computer, or TV where you see pictures",
    examples: ["I dropped my phone and cracked the screen.", "Kids spend too much time in front of screens."],
    cloze: "Can you make the text on the ___ bigger?",
    collocations: ["touch screen", "screen time", "cracked screen"],
    band: 1,
    tags: ["tech"],
  },
  {
    id: "v-mn-charge-v",
    word: "charge",
    pos: "v",
    he: "להטעין",
    def: "to put electricity into a battery",
    examples: ["I need to charge my phone before we go.", "The car takes eight hours to charge."],
    cloze: "Can I ___ my laptop here? The battery is at 5%.",
    collocations: ["charge a phone", "fully charged", "charger"],
    band: 2,
    tags: ["tech"],
    trap: "להטעין = charge. הפועל load = לטעון סחורה / לטעון דף. 'I loaded my phone' שגוי. שם עצם: charger (מטען).",
  },
  {
    id: "v-mn-battery-dies",
    word: "battery dies",
    pos: "phr",
    he: "הסוללה נגמרת",
    def: "the battery runs out of power",
    examples: ["My battery died in the middle of the call.", "Turn down the brightness so the battery doesn't die so fast."],
    cloze: "Sorry I didn't answer, my ___ on the way home.",
    clozeAnswer: "battery died",
    collocations: ["my phone died", "dead battery", "low battery"],
    band: 2,
    tags: ["tech"],
    trap: "הסוללה נגמרה = my battery died / my phone died / my battery is dead. לא 'the battery finished'.",
  },
  {
    id: "v-mn-wifi",
    word: "wi-fi",
    pos: "n",
    he: "וויי-פיי, אינטרנט אלחוטי",
    def: "a way to connect to the internet without cables",
    examples: ["What's the Wi-Fi password here?", "The Wi-Fi keeps dropping in my room."],
    cloze: "Is there free ___ at the café?",
    collocations: ["connect to the Wi-Fi", "Wi-Fi password", "the Wi-Fi is down"],
    band: 1,
    tags: ["tech"],
    colloc: { frame: "I can't send it, the Wi-Fi is ___ again.", answer: "down", options: ["down", "off", "closed"], whyHe: "the Wi-Fi is down = הרשת נפלה / לא עובדת. off = כבוי בכוונה." },
  },
  
  {
    id: "v-mn-crash",
    word: "crash",
    pos: "v",
    he: "לקרוס (מחשב, אפליקציה)",
    def: "(of a computer or program) to suddenly stop working",
    examples: ["The app crashes every time I open the camera.", "My computer crashed and I lost the whole document."],
    cloze: "The website ___ because too many people logged in at once.",
    clozeAnswer: "crashed",
    collocations: ["the app crashed", "crash a car"],
    band: 2,
    tags: ["tech"],
  },
  {
    id: "v-mn-freeze",
    word: "freeze",
    pos: "v",
    he: "להיתקע (מסך)",
    def: "(of a screen or program) to stop moving or responding",
    examples: ["My screen froze during the game.", "The video keeps freezing, is it your Wi-Fi?"],
    cloze: "Zoom ___ for a minute, so I missed your question.",
    clozeAnswer: "froze",
    collocations: ["the screen froze", "freeze up"],
    band: 2,
    tags: ["tech"],
    trap: "המסך נתקע = the screen froze / it's frozen. 'the screen is stuck' מובן, אבל froze הוא הטבעי. עבר: froze, לא freezed.",
  },
  
  {
    id: "v-mn-app",
    word: "app",
    pos: "n",
    he: "אפליקציה",
    def: "a program you use on a phone or tablet",
    examples: ["Which app do you use for the bus times?", "The bank's app lets you pay bills in seconds."],
    cloze: "I deleted the ___ because it kept sending me ads.",
    collocations: ["download an app", "open an app", "banking app"],
    band: 1,
    tags: ["tech"],
  },
  {
    id: "v-mn-notification",
    word: "notification",
    pos: "n",
    he: "התראה",
    def: "a message from an app that tells you something happened",
    examples: ["I turned off notifications from that group.", "I got a notification that my package was delivered."],
    cloze: "My phone buzzed with a ___ from the bank.",
    collocations: ["get a notification", "turn off notifications", "push notification"],
    band: 3,
    tags: ["tech"],
    colloc: { frame: "I ___ off notifications at night so I can sleep.", answer: "turn", options: ["turn", "close", "shut"], whyHe: "turn off notifications = לכבות התראות. close = לסגור (חלון, אפליקציה)." },
  },
  {
    id: "v-mn-search-for",
    word: "search for",
    pos: "phr",
    he: "לחפש",
    def: "to look for something, especially online",
    examples: ["I searched for cheap flights to Rome.", "Search for the name and it'll come up."],
    cloze: "Just ___ 'pizza near me' on your phone.",
    collocations: ["search for something online", "search the web"],
    band: 2,
    tags: ["tech"],
    trap: "search FOR something (או look for). 'search after' הוא תרגום מ'לחפש אחרי' ושגוי. בלי for: search the internet = לחפש בתוך.",
    colloc: { frame: "I searched ___ the article but couldn't find it.", answer: "for", options: ["for", "after", "about"], whyHe: "search for = לחפש. after ו-about שגויים." },
  },
  {
    id: "v-mn-post",
    word: "post",
    pos: "v",
    he: "לפרסם (ברשת)",
    def: "to put a message, photo, or video on social media or a website",
    examples: ["She posted a photo of the sunset.", "Don't post anything you wouldn't want your boss to see."],
    cloze: "He ___ a video from the concert on Instagram.",
    clozeAnswer: "posted",
    collocations: ["post a photo", "post on Instagram", "a post"],
    band: 2,
    tags: ["tech"],
  },
  {
    id: "v-mn-share",
    word: "share",
    pos: "v",
    he: "לשתף",
    def: "to send something you saw online to other people",
    examples: ["Can you share the link with me?", "The video was shared thousands of times."],
    cloze: "I'll ___ the photos in the family group tonight.",
    collocations: ["share a link", "share with someone", "share a post"],
    band: 1,
    tags: ["tech"],
    trap: "share something WITH someone: share the file with me (לא 'share me the file' ולא 'share to me').",
  },
  {
    id: "v-mn-follow",
    word: "follow",
    pos: "v",
    he: "לעקוב (ברשת)",
    def: "to choose to see someone's posts on social media",
    examples: ["I follow a few chefs on Instagram.", "She has 50,000 people following her."],
    cloze: "You should ___ her page, she posts great recipes.",
    collocations: ["follow someone on Instagram", "followers", "unfollow"],
    band: 1,
    tags: ["tech"],
    trap: "follow somebody (בלי after): I follow her on TikTok. 'follow after her' = ללכת אחריה פיזית. שם עצם: follower.",
  },
  {
    id: "v-mn-influencer",
    word: "influencer",
    pos: "n",
    he: "משפיען, משפיענית",
    def: "a person with many followers who promotes products online",
    examples: ["Some influencers earn a lot from one post.", "The brand paid an influencer to review the phone."],
    cloze: "My cousin is an ___ with a million followers.",
    collocations: ["social media influencer", "become an influencer"],
    band: 3,
    tags: ["tech"],
  },

  // ---------- media & news ----------
  {
    id: "v-mn-headline",
    word: "headline",
    pos: "n",
    he: "כותרת (בחדשות)",
    def: "the title of a news story, printed in large letters",
    examples: ["I only read the headlines this morning.", "The story made headlines all over the world."],
    cloze: "The ___ said 'Prices to rise again', so I kept reading.",
    collocations: ["make headlines", "read the headlines", "front-page headline"],
    band: 2,
    tags: ["news"],
    colloc: { frame: "The scandal ___ headlines for weeks.", answer: "made", options: ["made", "did", "took"], whyHe: "make headlines = לזכות לכותרות. did/took שגויים." },
  },
  {
    id: "v-mn-breaking-news",
    word: "breaking news",
    pos: "n",
    he: "מבזק חדשות",
    def: "news about something important that is happening right now",
    examples: ["We interrupt this program with breaking news.", "I got a breaking news alert on my phone."],
    cloze: "The channel showed ___ about the earthquake.",
    collocations: ["breaking news alert"],
    band: 2,
    tags: ["news"],
  },
  {
    id: "v-mn-report",
    word: "report",
    pos: "v",
    he: "לדווח",
    def: "to tell people about something that happened, especially in the news",
    examples: ["The news reported heavy traffic on the highway.", "You should report the theft to the police."],
    cloze: "Local media ___ that the road will close tomorrow.",
    clozeAnswer: "reported",
    collocations: ["report on", "report something to the police", "a report"],
    band: 2,
    tags: ["news"],
    trap: "report something TO someone: report it to the police (לא 'report to the police about'). report ON a topic = לסקר. a report = דו\"ח / כתבה.",
  },
  {
    id: "v-mn-journalist",
    word: "journalist",
    pos: "n",
    he: "עיתונאי, עיתונאית",
    def: "a person who writes or reports the news",
    examples: ["A journalist called to ask about the accident.", "She worked as a journalist for ten years."],
    cloze: "The ___ interviewed the mayor about the new plan.",
    collocations: ["freelance journalist", "investigative journalist"],
    band: 3,
    tags: ["news"],
    trap: "עיתונאי = journalist או reporter. לא לבלבל עם journal (כתב עת / יומן).",
  },
  {
    id: "v-mn-fake-news",
    word: "fake news",
    pos: "n",
    he: "פייק ניוז, חדשות כזב",
    def: "false stories that are spread online as if they were real news",
    examples: ["That story about the celebrity was fake news.", "Schools now teach kids how to spot fake news."],
    cloze: "Check the source before you share, it might be ___.",
    collocations: ["spread fake news", "spot fake news"],
    band: 2,
    tags: ["news"],
  },
  
  {
    id: "v-mn-cover",
    word: "cover",
    pos: "v",
    he: "לסקר (בתקשורת)",
    def: "(of a journalist or news program) to report on an event",
    examples: ["Three channels covered the protest live.", "She covers sports for a local paper."],
    cloze: "Which reporter is going to ___ the election?",
    collocations: ["cover a story", "cover an event", "news coverage"],
    band: 4,
    tags: ["news"],
    trap: "cover = לסקר (עיתונות) וגם לכסות. שם עצם: coverage (סיקור). 'the media did coverage' שגוי, אומרים covered.",
  },
  {
    id: "v-mn-spread",
    word: "spread",
    pos: "v",
    he: "להתפשט, להפיץ",
    def: "to reach more people or places; to make something reach more people",
    examples: ["The rumor spread across the office in an hour.", "Please don't spread this, it's not confirmed."],
    cloze: "Fake stories ___ faster than real ones online.",
    collocations: ["spread quickly", "spread a rumor", "spread the word"],
    band: 3,
    tags: ["news"],
    colloc: { frame: "Help us spread the ___ about the event.", answer: "word", options: ["word", "voice", "talk"], whyHe: "spread the word = להפיץ את הבשורה. voice/talk שגויים." },
  },

  // ---------- society, government, law & education ----------
  {
    id: "v-mn-election",
    word: "election",
    pos: "n",
    he: "בחירות",
    def: "the time when people vote to choose a government or leader",
    examples: ["The election is in March.", "Who do you think will win the election?"],
    cloze: "Turnout in the last ___ was very low.",
    collocations: ["hold an election", "win an election", "general election"],
    band: 2,
    tags: ["society"],
    trap: "בחירות = election, בדרך כלל ביחיד: the election was… (בעברית זה רבים, באנגלית לא חייבים).",
    colloc: { frame: "The government will ___ an election next year.", answer: "hold", options: ["hold", "make", "do"], whyHe: "hold an election = לקיים בחירות. make/do שגויים." },
  },
  {
    id: "v-mn-vote",
    word: "vote",
    pos: "v",
    he: "להצביע",
    def: "to choose someone or something officially, for example in an election",
    examples: ["I voted for the first time at 18.", "Most people in the office voted against the plan."],
    cloze: "Who did you ___ for last time?",
    collocations: ["vote for", "vote against", "the right to vote"],
    band: 1,
    tags: ["society"],
    trap: "vote FOR somebody (לא 'vote to' / 'vote on somebody'). vote on = להצביע על נושא.",
  },
  {
    id: "v-mn-government",
    word: "government",
    pos: "n",
    he: "ממשלה",
    def: "the group of people who run a country",
    examples: ["The government promised to lower taxes.", "People want the government to do more about housing."],
    cloze: "The ___ announced new rules for drivers.",
    collocations: ["form a government", "government spending", "local government"],
    band: 1,
    tags: ["society"],
  },
  {
    id: "v-mn-law",
    word: "law",
    pos: "n",
    he: "חוק",
    def: "a rule made by the government that everyone must follow",
    examples: ["It's against the law to drive without a seatbelt.", "They passed a new law on smoking."],
    cloze: "Is there a ___ about how loud music can be at night?",
    collocations: ["against the law", "break the law", "pass a law"],
    band: 1,
    tags: ["society"],
    trap: "break the law = לעבור על החוק (לא 'cross the law'). by law = לפי חוק. law גם = משפטים (ללמוד law).",
    colloc: { frame: "Parking here is ___ the law.", answer: "against", options: ["against", "under", "over"], whyHe: "against the law = בניגוד לחוק. under the law = לפי החוק (משמעות אחרת)." },
  },
  {
    id: "v-mn-illegal",
    word: "illegal",
    pos: "adj",
    he: "לא חוקי",
    def: "not allowed by law",
    examples: ["It's illegal to park on the sidewalk.", "They were selling illegal copies of the game."],
    cloze: "Using your phone while driving is ___ here.",
    collocations: ["illegal to do", "illegal drugs", "strictly illegal"],
    band: 2,
    tags: ["society"],
  },
  {
    id: "v-mn-rights",
    word: "rights",
    pos: "n",
    he: "זכויות",
    def: "things that the law says you are allowed to have or do",
    examples: ["Workers have the right to a break every four hours.", "They marched for equal rights."],
    cloze: "Every citizen has basic ___ under the law.",
    collocations: ["human rights", "equal rights", "have the right to"],
    band: 2,
    tags: ["society"],
    trap: "have the right TO do something (לא 'have right to'). human rights = זכויות אדם. right גם = ימין / נכון.",
    colloc: { frame: "You have the right ___ remain silent.", answer: "to", options: ["to", "for", "of"], whyHe: "have the right to + פועל = יש לך זכות ל-. for ו-of שגויים." },
  },
  {
    id: "v-mn-protest",
    word: "protest",
    pos: "v",
    he: "למחות, להפגין",
    def: "to show publicly that you disagree with something",
    examples: ["Thousands protested against the new tax.", "Students are protesting outside the university."],
    cloze: "People ___ in the streets after the decision.",
    clozeAnswer: "protested",
    collocations: ["protest against", "hold a protest", "peaceful protest"],
    band: 2,
    tags: ["society"],
    trap: "protest against something (בארה\"ב גם protest something). שם עצם: a protest (הפגנה). demonstration גם תקין.",
  },
  {
    id: "v-mn-crime",
    word: "crime",
    pos: "n",
    he: "פשע",
    def: "an action that is against the law",
    examples: ["Crime has gone down in the city this year.", "Stealing a bike is still a crime."],
    cloze: "The police are fighting ___ in the area.",
    collocations: ["commit a crime", "crime rate", "serious crime"],
    band: 2,
    tags: ["society"],
    trap: "לבצע פשע = commit a crime, לא 'do a crime' או 'make a crime'.",
    colloc: { frame: "He ___ a serious crime and went to prison.", answer: "committed", options: ["committed", "did", "made"], whyHe: "commit a crime = לבצע פשע. do/make שגויים." },
  },
  {
    id: "v-mn-steal",
    word: "steal",
    pos: "v",
    he: "לגנוב",
    def: "to take something that belongs to someone else without permission",
    examples: ["Someone stole my bike from outside the store.", "He was caught stealing from the cash register."],
    cloze: "My wallet was ___ on the train.",
    clozeAnswer: "stolen",
    collocations: ["steal something from", "get stolen"],
    band: 1,
    tags: ["society"],
    trap: "steal + הדבר שנגנב: steal a bike. rob + המקום או האדם: rob a bank, rob someone. 'They stole the bank' שגוי. עבר: stole, stolen.",
  },
  {
    id: "v-mn-rob",
    word: "rob",
    pos: "v",
    he: "לשדוד",
    def: "to steal money or things from a person or place, often using force",
    examples: ["Two men robbed the bank on Tuesday.", "She was robbed on her way home."],
    cloze: "The store was ___ twice last month.",
    clozeAnswer: "robbed",
    collocations: ["rob a bank", "rob someone of", "robbery"],
    band: 2,
    tags: ["society"],
    trap: "rob = לשדוד (מקום או אדם): rob a bank / rob me. הדבר שנלקח בא עם of: robbed me of my phone. שם עצם: robbery.",
  },
  {
    id: "v-mn-theft",
    word: "theft",
    pos: "n",
    he: "גניבה",
    def: "the crime of stealing",
    examples: ["Bike theft is common in this neighborhood.", "He was arrested for theft."],
    cloze: "Report the ___ to the police as soon as you can.",
    collocations: ["car theft", "identity theft", "report a theft"],
    band: 4,
    tags: ["society"],
  },
  {
    id: "v-mn-burglar",
    word: "burglar",
    pos: "n",
    he: "פורץ",
    def: "a person who breaks into a building to steal things",
    examples: ["The burglar came in through the kitchen window.", "We got an alarm after burglars hit the street twice."],
    cloze: "A ___ broke into our neighbors' house last night.",
    collocations: ["burglar alarm", "break in"],
    band: 4,
    tags: ["society"],
    trap: "burglar = פורץ (לבית). thief = גנב (כללי). robber = שודד. הפועל: break in / break into a house.",
  },
  {
    id: "v-mn-witness",
    word: "witness",
    pos: "n",
    he: "עד, עדה",
    def: "a person who sees a crime or accident happen",
    examples: ["The police are looking for witnesses to the accident.", "A witness said the car ran the red light."],
    cloze: "There was only one ___, and she didn't see his face.",
    collocations: ["eyewitness", "witness to", "call a witness"],
    band: 3,
    tags: ["society"],
  },
  {
    id: "v-mn-evidence",
    word: "evidence",
    pos: "n",
    he: "ראיות",
    def: "facts or objects that show something is true, especially in court",
    examples: ["The police didn't have enough evidence to arrest him.", "There's no evidence that he was there."],
    cloze: "Without hard ___, the case will be closed.",
    collocations: ["evidence that", "strong evidence", "piece of evidence"],
    band: 3,
    tags: ["society"],
    trap: "evidence לא ספיר: some evidence / a piece of evidence, לא 'an evidence' או 'evidences'.",
  },
  {
    id: "v-mn-guilty",
    word: "guilty",
    pos: "adj",
    he: "אשם",
    def: "having done something wrong or against the law",
    examples: ["The jury found him guilty of theft.", "I feel guilty about not calling my mom."],
    cloze: "The court found her ___ and gave her two years.",
    collocations: ["find someone guilty", "guilty of", "feel guilty about"],
    band: 3,
    tags: ["society"],
    colloc: { frame: "He was found guilty ___ fraud.", answer: "of", options: ["of", "in", "for"], whyHe: "guilty of = אשם ב-. 'guilty in' תרגום מעברית." },
  },
  
  {
    id: "v-mn-punishment",
    word: "punishment",
    pos: "n",
    he: "עונש",
    def: "something bad that is done to someone because they did something wrong",
    examples: ["The punishment for drunk driving is very strict here.", "As a punishment, he lost his phone for a week."],
    cloze: "Do you think the ___ was too hard for a first offense?",
    collocations: ["harsh punishment", "as a punishment", "punish someone for"],
    band: 3,
    tags: ["society"],
    trap: "שם עצם punishment, פועל punish: punish someone FOR something. 'give punishment' פחות טבעי; אומרים punish.",
  },
  {
    id: "v-mn-arrest",
    word: "arrest",
    pos: "v",
    he: "לעצור (משטרה)",
    def: "(of the police) to take someone away because they may have broken the law",
    examples: ["The police arrested two men after the fight.", "He was arrested for driving without a license."],
    cloze: "They ___ the driver at the scene.",
    clozeAnswer: "arrested",
    collocations: ["arrest someone for", "under arrest", "get arrested"],
    band: 3,
    tags: ["society"],
    trap: "arrest someone FOR something. stop = לעצור רכב או מישהו ברחוב; arrest = מעצר. under arrest = עצור.",
  },
  {
    id: "v-mn-policy",
    word: "policy",
    pos: "n",
    he: "מדיניות",
    def: "a plan or set of rules made by a government or company",
    examples: ["The new housing policy will start next year.", "Our company has a strict no-smoking policy."],
    cloze: "The store has a 30-day return ___.",
    collocations: ["foreign policy", "return policy", "insurance policy"],
    band: 4,
    tags: ["society"],
    trap: "policy = מדיניות (ספיר: a policy). politics = פוליטיקה (לא ספיר). 'the politics of the company' שגוי.",
  },
  {
    id: "v-mn-sue",
    word: "sue",
    pos: "v",
    he: "לתבוע (בבית משפט)",
    def: "to take legal action against someone to get money",
    examples: ["She sued the hospital for medical mistakes.", "If they don't pay, we'll sue."],
    cloze: "He threatened to ___ the company for 100,000 shekels.",
    collocations: ["sue someone for", "get sued", "lawsuit"],
    band: 4,
    tags: ["society"],
    trap: "sue = לתבוע בבית משפט. demand = לדרוש. claim = לטעון / לתבוע מביטוח. 'I will demand him' שגוי.",
  },

  

];
