import type { VocabItem } from "@/lib/types";

export const OPINIONS_ABSTRACT: VocabItem[] = [
  // ---------- verbs & verb phrases ----------
  
  {
    id: "v-op-claim",
    word: "claim",
    pos: "v",
    he: "לטעון",
    def: "to say that something is true, often without proof",
    examples: ["He claims he never got the email.", "The company claims the product is completely safe."],
    cloze: "She ___ that she was at home all evening.",
    clozeAnswer: "claimed",
    collocations: ["claim that", "claim to be"],
    band: 4,
    tags: ["opinions", "reasoning"],
    trap: "claim = לטעון (בלי הוכחה). לא לבלבל עם complain (להתלונן).",
  },
  {
    id: "v-op-assume",
    word: "assume",
    pos: "v",
    he: "להניח",
    def: "to think something is true without checking it",
    examples: ["I assumed you were busy, so I didn't call.", "Let's assume the meeting starts at nine."],
    cloze: "Don't ___ she knows. Ask her.",
    collocations: ["assume that", "let's assume"],
    band: 3,
    tags: ["reasoning"],
    trap: "assume = להניח (לחשוב שמשהו נכון). 'להניח חפץ' = put, לא assume.",
  },
  {
    id: "v-op-suppose",
    word: "suppose",
    pos: "v",
    he: "לשער; להניח",
    def: "to think something is probably true",
    examples: ["I suppose we could leave a bit earlier.", "\"Is he coming?\" \"I suppose so.\""],
    cloze: "I ___ you're right, but I still don't like it.",
    collocations: ["I suppose so", "be supposed to do"],
    band: 2,
    tags: ["opinions", "reasoning"],
    trap: "'I suppose so' = כנראה שכן. שימו לב: be supposed to = אמור ל (You're supposed to be at work).",
  },
  {
    id: "v-op-doubt",
    word: "doubt",
    pos: "v",
    he: "לפקפק; לא להאמין",
    def: "to feel that something is probably not true or not likely",
    examples: ["I doubt he'll finish on time.", "I doubt that the store is still open."],
    cloze: "I ___ it. He never keeps his promises.",
    collocations: ["I doubt it", "doubt that", "no doubt"],
    band: 3,
    tags: ["opinions", "reasoning"],
    trap: "'I doubt it' = אני בספק. לא אומרים doubt in. אחרי doubt לא שמים not: I doubt he'll come (לא: I doubt he won't come).",
    colloc: { frame: "\"Will they win?\" \"I ___ it.\"", answer: "doubt", options: ["doubt", "suspect", "wonder"], whyHe: "I doubt it = אני בספק." },
  },
  {
    id: "v-op-convince",
    word: "convince",
    pos: "v",
    he: "לשכנע",
    def: "to make someone believe that something is true",
    examples: ["She convinced me that the plan would work.", "I'm not convinced this is a good idea."],
    cloze: "It took an hour to ___ him to come with us.",
    collocations: ["convince someone that", "convince someone to do", "I'm not convinced"],
    band: 3,
    tags: ["opinions", "reasoning"],
    trap: "convince someone (מישהו) that / to do. 'אני משוכנע' = I'm convinced, לא I'm convince.",
    colloc: { frame: "I'm not ___ that this is the best option.", answer: "convinced", options: ["convinced", "convincing", "convince"], whyHe: "האדם 'משוכנע' = convinced; הטיעון 'משכנע' = convincing." },
  },
  {
    id: "v-op-persuade",
    word: "persuade",
    pos: "v",
    he: "לשכנע (לעשות)",
    def: "to make someone agree to do something by giving good reasons",
    examples: ["My friends persuaded me to try skiing.", "Nobody could persuade her to change her mind."],
    cloze: "We finally ___ Dad to buy a new car.",
    clozeAnswer: "persuaded",
    collocations: ["persuade someone to do", "try to persuade"],
    band: 3,
    tags: ["opinions", "reasoning"],
    trap: "persuade someone to do — תמיד עם to + פועל. לא persuade someone doing.",
  },
  {
    id: "v-op-agree",
    word: "agree",
    pos: "v",
    he: "להסכים",
    def: "to have the same opinion as someone",
    examples: ["I agree with you about the price.", "We agreed to meet at seven."],
    cloze: "I don't ___ with everything he said.",
    collocations: ["agree with someone", "agree on/about something", "agree to do"],
    band: 1,
    tags: ["opinions"],
    trap: "'I agree', לא 'I am agree'. agree הוא פועל, לא שם תואר. מסכימים עם מישהו = agree with; על נושא = agree on/about.",
    colloc: { frame: "I totally ___ with you.", answer: "agree", options: ["agree", "am agree", "agreeing"], whyHe: "agree הוא פועל רגיל: I agree. לא I am agree." },
  },
  {
    id: "v-op-disagree",
    word: "disagree",
    pos: "v",
    he: "לא להסכים",
    def: "to have a different opinion from someone",
    examples: ["Sorry, but I disagree with you on this.", "They disagreed about where to go on vacation."],
    cloze: "I ___ with the idea that money makes people happy.",
    collocations: ["disagree with someone", "strongly disagree"],
    band: 1,
    tags: ["opinions"],
    trap: "'I disagree' — לא 'I'm not agree'. disagree with מישהו, disagree about/on נושא.",
    colloc: { frame: "I ___ disagree with that decision.", answer: "strongly", options: ["strongly", "hardly", "heavily"], whyHe: "strongly disagree = מתנגד בתוקף." },
  },
  {
    id: "v-op-admit",
    word: "admit",
    pos: "v",
    he: "להודות (ב)",
    def: "to say that something is true, even though you don't want to",
    examples: ["I have to admit, you were right.", "He admitted making a mistake."],
    cloze: "She finally ___ that she had forgotten the tickets.",
    clozeAnswer: "admitted",
    collocations: ["admit that", "admit doing", "I have to admit"],
    band: 3,
    tags: ["opinions"],
    trap: "admit + -ing או admit that. לא admit to do. 'להודות' במובן תודה = thank, לא admit.",
  },
  {
    id: "v-op-deny",
    word: "deny",
    pos: "v",
    he: "להכחיש",
    def: "to say that something is not true",
    examples: ["He denied taking the money.", "The company denies that there is a problem."],
    cloze: "She ___ any connection with the company.",
    clozeAnswer: "denied",
    collocations: ["deny doing", "deny that", "strongly deny"],
    band: 4,
    tags: ["opinions"],
    trap: "deny + -ing (He denied taking it), לא deny to take. deny ≠ refuse (לסרב): refuse to do.",
  },
  {
    id: "v-op-realize",
    word: "realize",
    pos: "v",
    he: "להבין; לקלוט",
    def: "to understand or notice something suddenly",
    examples: ["I didn't realize how late it was.", "She realized she had left her keys at home."],
    cloze: "Sorry, I didn't ___ you were on the phone.",
    collocations: ["realize that", "suddenly realize", "didn't realize"],
    band: 2,
    tags: ["reasoning"],
    accept: ["realise"],
    trap: "realize = להבין/לקלוט פתאום. לא 'לממש' (חלום = fulfill / make it happen).",
  },
  {
    id: "v-op-consider",
    word: "consider",
    pos: "v",
    he: "לשקול",
    def: "to think carefully about something before deciding",
    examples: ["Have you considered moving to a smaller apartment?", "We're considering a few options."],
    cloze: "You should ___ getting a second opinion.",
    collocations: ["consider doing", "consider the options", "consider it"],
    band: 2,
    tags: ["reasoning"],
    trap: "consider + -ing (consider moving), לא consider to move.",
    colloc: { frame: "Have you considered ___ for a new job?", answer: "looking", options: ["looking", "to look", "look"], whyHe: "אחרי consider בא פועל ב-ing." },
  },
  {
    id: "v-op-tend-to",
    word: "tend to",
    pos: "phr",
    he: "נוטה ל",
    def: "to usually do something or usually be a certain way",
    examples: ["I tend to eat too fast when I'm stressed.", "Prices tend to go up before the holidays."],
    cloze: "People ___ trust their friends more than the news.",
    clozeAnswer: "tend to",
    collocations: ["tend to do", "tend to be"],
    band: 3,
    tags: ["abstract"],
    trap: "tend to + פועל בסיסי. בעברית 'אני נוטה ל' — באנגלית I tend to, לא I'm tend to.",
  },
  {
    id: "v-op-depend-on",
    word: "depend on",
    pos: "phr",
    he: "להיות תלוי ב",
    def: "to change according to something else; to need something",
    examples: ["It depends on the weather.", "Everything depends on how much money we have."],
    cloze: "Can we go? Well, it ___ the traffic.",
    clozeAnswer: "depends on",
    collocations: ["depend on", "it depends", "depend on whether"],
    band: 1,
    tags: ["abstract", "reasoning"],
    trap: "depend ON, לא depend of / depend in. וכשעונים 'תלוי' לבד: It depends. (לא: It's depend.)",
    colloc: { frame: "The price depends ___ the season.", answer: "on", options: ["on", "of", "in"], whyHe: "תמיד depend on." },
  },
  {
    id: "v-op-affect",
    word: "affect",
    pos: "v",
    he: "להשפיע על",
    def: "to change or influence something",
    examples: ["Lack of sleep affects your mood.", "The strike affected thousands of travelers."],
    cloze: "The bad weather ___ our plans for the weekend.",
    clozeAnswer: "affected",
    collocations: ["affect someone/something", "badly affected"],
    band: 3,
    tags: ["abstract", "reasoning"],
    trap: "affect = פועל (להשפיע על), effect = שם עצם (השפעה). affect בא בלי on: affects your mood (לא affects on). 'have an effect on' = להשפיע.",
    colloc: { frame: "The noise really ___ my concentration.", answer: "affects", options: ["affects", "effects", "affects on"], whyHe: "affect הוא הפועל, ובא ישירות בלי on." },
  },
  {
    id: "v-op-influence",
    word: "influence",
    pos: "v",
    he: "להשפיע",
    def: "to change how someone thinks or acts",
    examples: ["My teacher influenced my decision to study art.", "Ads influence what we buy."],
    cloze: "Friends often ___ the way teenagers dress.",
    collocations: ["influence a decision", "be influenced by", "have an influence on"],
    band: 3,
    tags: ["abstract", "reasoning"],
    trap: "הפועל influence בא בלי on: influence people. שם העצם — have an influence on. אל תערבבו.",
  },
  {
    id: "v-op-cause",
    word: "cause",
    pos: "v",
    he: "לגרום ל",
    def: "to make something happen, usually something bad",
    examples: ["The storm caused a lot of damage.", "What caused the accident?"],
    cloze: "The delay was ___ by a technical problem.",
    clozeAnswer: "caused",
    collocations: ["cause problems", "cause damage", "cause someone to do"],
    band: 2,
    tags: ["abstract", "reasoning"],
    trap: "cause בא בלי to: cause problems (לא cause to problems). cause = גורם ל, בעיקר לדברים רעים.",
    colloc: { frame: "Smoking can ___ serious health problems.", answer: "cause", options: ["cause", "make", "do"], whyHe: "cause problems / cause damage — לא make/do." },
  },
  {
    id: "v-op-lead-to",
    word: "lead to",
    pos: "phr",
    he: "להוביל ל",
    def: "to cause something to happen as a result",
    examples: ["Stress can lead to health problems.", "One small mistake led to a big argument."],
    cloze: "Poor planning often ___ delays.",
    clozeAnswer: "leads to",
    collocations: ["lead to problems", "lead to a change"],
    band: 3,
    tags: ["abstract", "reasoning"],
    trap: "lead to + שם עצם או -ing: lead to problems / lead to losing. לא lead to lose.",
  },
  {
    id: "v-op-result-in",
    word: "result in",
    pos: "phr",
    he: "לגרום ל; להסתיים ב",
    def: "to have something as a result",
    examples: ["The accident resulted in two people being hurt.", "Working late every night resulted in burnout."],
    cloze: "The talks ___ a new agreement between the two sides.",
    clozeAnswer: "resulted in",
    collocations: ["result in", "result in something happening"],
    band: 4,
    tags: ["abstract", "reasoning"],
    trap: "result in = גורם ל (X results in Y). result from = נובע מ. לא result to.",
    colloc: { frame: "The changes resulted ___ fewer customers.", answer: "in", options: ["in", "to", "with"], whyHe: "result in = הביא ל." },
  },
  {
    id: "v-op-prevent",
    word: "prevent",
    pos: "v",
    he: "למנוע",
    def: "to stop something from happening",
    examples: ["Wash your hands to prevent illness.", "The rain prevented us from going out."],
    cloze: "A good lock can ___ most break-ins.",
    collocations: ["prevent something", "prevent someone from doing"],
    band: 2,
    tags: ["abstract"],
    trap: "prevent someone FROM doing — לא prevent someone to do.",
    colloc: { frame: "The noise prevented me ___ sleeping.", answer: "from", options: ["from", "to", "of"], whyHe: "prevent someone from doing." },
  },
  {
    id: "v-op-avoid",
    word: "avoid",
    pos: "v",
    he: "להימנע מ",
    def: "to stay away from something or not do it",
    examples: ["I avoid driving in the city center.", "Try to avoid sugar before bed."],
    cloze: "I ___ talking to him because he always complains.",
    collocations: ["avoid doing", "avoid a problem", "avoid the rush hour"],
    band: 2,
    tags: ["abstract"],
    trap: "avoid + -ing: avoid driving. לא avoid to drive.",
    colloc: { frame: "She always avoids ___ about politics.", answer: "talking", options: ["talking", "to talk", "talk"], whyHe: "אחרי avoid בא פועל ב-ing." },
  },
  {
    id: "v-op-manage-to",
    word: "manage to",
    pos: "phr",
    he: "להצליח ל",
    def: "to succeed in doing something difficult",
    examples: ["We managed to catch the last train.", "Did you manage to fix the printer?"],
    cloze: "I finally ___ find a parking space.",
    clozeAnswer: "managed to",
    collocations: ["manage to do", "somehow manage to"],
    band: 2,
    tags: ["abstract"],
    trap: "'הצלחתי ל' = I managed to. 'I succeeded to' שגוי (succeed in doing). לא לבלבל עם manage = לנהל.",
    colloc: { frame: "We ___ to finish before the deadline.", answer: "managed", options: ["managed", "succeeded", "could"], whyHe: "managed to = הצלחנו (בפועל). succeeded in -ing." },
  },
  {
    id: "v-op-fail-to",
    word: "fail to",
    pos: "phr",
    he: "לא להצליח ל",
    def: "to not do something you should do or tried to do",
    examples: ["He failed to show up for the meeting.", "The plan failed to solve the real problem."],
    cloze: "They ___ notice the mistake until it was too late.",
    clozeAnswer: "failed to",
    collocations: ["fail to do", "fail to understand", "fail an exam"],
    band: 3,
    tags: ["abstract"],
    trap: "fail to do = לא הצליח / לא עשה. אחרי fail בא to + פועל. 'להיכשל במבחן' = fail an exam (בלי in).",
  },
  {
    id: "v-op-struggle",
    word: "struggle",
    pos: "v",
    he: "להתקשות; להיאבק",
    def: "to try hard to do something that is difficult",
    examples: ["I'm struggling to understand this chapter.", "Many families struggle with high rent."],
    cloze: "He ___ with math all through high school.",
    clozeAnswer: "struggled",
    collocations: ["struggle to do", "struggle with something"],
    band: 3,
    tags: ["abstract"],
    trap: "struggle with משהו / struggle to do. 'I struggle in English' — עדיף struggle with English.",
  },
  {
    id: "v-op-cope-with",
    word: "cope with",
    pos: "phr",
    he: "להתמודד עם",
    def: "to deal successfully with a difficult situation",
    examples: ["How do you cope with stress at work?", "She's coping well with the new job."],
    cloze: "I can't ___ all this pressure anymore.",
    clozeAnswer: "cope with",
    collocations: ["cope with stress", "cope well", "can't cope"],
    band: 4,
    tags: ["abstract"],
    trap: "cope WITH — לא cope in. 'I can't cope' = אני לא עומד בזה.",
  },

  
  {
    id: "v-op-take-into-account",
    word: "take into account",
    pos: "phr",
    he: "להביא בחשבון",
    def: "to think about something when making a decision",
    examples: ["You should take the cost into account.", "The judge took his age into account."],
    cloze: "We didn't ___ the traffic, so we were late.",
    clozeAnswer: "take into account",
    collocations: ["take something into account", "take into account that"],
    band: 4,
    tags: ["reasoning"],
    trap: "take into account = להביא בחשבון. אפשר גם take account of. לא take in account.",
    colloc: { frame: "Did they take your experience ___ account?", answer: "into", options: ["into", "in", "to"], whyHe: "take into account." },
  },
  
  {
    id: "v-op-discuss",
    word: "discuss",
    pos: "v",
    he: "לדון ב; לדבר על",
    def: "to talk about something with someone, often to make a decision",
    examples: ["We discussed the problem for an hour.", "Let's discuss it over lunch."],
    cloze: "Can we ___ the budget at tomorrow's meeting?",
    collocations: ["discuss something", "discuss it with someone"],
    band: 1,
    tags: ["opinions"],
    trap: "discuss בא בלי about: discuss the plan (לא discuss about the plan). talk about — כן עם about.",
    colloc: { frame: "We need to ___ the schedule with the team.", answer: "discuss", options: ["discuss", "discuss about", "talk"], whyHe: "discuss + מושא ישיר. talk צריך about." },
  },
  {
    id: "v-op-explain",
    word: "explain",
    pos: "v",
    he: "להסביר",
    def: "to make something clear by describing it",
    examples: ["Can you explain the rules to me?", "She explained why she was late."],
    cloze: "Could you ___ this word to me?",
    collocations: ["explain something to someone", "explain why/how"],
    band: 1,
    tags: ["opinions", "reasoning"],
    trap: "explain something TO me — לא explain me. (בעברית 'תסביר לי', באנגלית explain it to me.)",
    colloc: { frame: "Let me explain the situation ___ you.", answer: "to", options: ["to", "for", "at"], whyHe: "explain something to someone." },
  },
  {
    id: "v-op-wonder",
    word: "wonder",
    pos: "v",
    he: "לתהות",
    def: "to ask yourself about something you are not sure about",
    examples: ["I wonder if she got my message.", "I was wondering whether you could help me."],
    cloze: "I ___ why he didn't call back.",
    collocations: ["wonder if/whether", "wonder why", "I was wondering"],
    band: 2,
    tags: ["reasoning"],
    trap: "wonder = לתהות, לא 'להתפלא'. 'I wonder if...' = מעניין אם / אני תוהה. בקשה מנומסת: I was wondering if you could...",
  },
  {
    id: "v-op-recommend",
    word: "recommend",
    pos: "v",
    he: "להמליץ",
    def: "to say that something is good and worth doing or trying",
    examples: ["I recommend the fish. It's excellent.", "The doctor recommended resting for a few days."],
    cloze: "Can you ___ a good dentist in this area?",
    collocations: ["recommend something", "recommend doing", "highly recommend"],
    band: 2,
    tags: ["opinions"],
    trap: "recommend + -ing או recommend that. לא recommend to do. 'להמליץ לך על' = recommend something to you.",
    colloc: { frame: "I ___ recommend this restaurant.", answer: "highly", options: ["highly", "very", "hardly"], whyHe: "highly recommend = ממליץ בחום. לא very recommend." },
  },
  {
    id: "v-op-expect",
    word: "expect",
    pos: "v",
    he: "לצפות; לחשוב שיקרה",
    def: "to think that something will probably happen",
    examples: ["I expect the train will be late again.", "We're expecting about twenty guests."],
    cloze: "I didn't ___ to see you here!",
    collocations: ["expect to do", "expect someone to do", "as expected"],
    band: 1,
    tags: ["reasoning"],
    trap: "expect = לצפות ש (לחשוב שיקרה), לא לקוות (hope). 'מחכה ל' פיזית = wait for, לא expect.",
  },
  
  {
    id: "v-op-mean",
    word: "mean",
    pos: "v",
    he: "להתכוון; פירושו",
    def: "to have a certain meaning; to intend to say or do something",
    examples: ["What does this word mean?", "I didn't mean to hurt you."],
    cloze: "Sorry, what do you ___ by 'later'?",
    collocations: ["What do you mean?", "I mean...", "mean to do"],
    band: 1,
    tags: ["opinions", "reasoning"],
    trap: "'למה אתה מתכוון?' = What do you mean? (לא what you mean). 'כלומר' בדיבור = I mean.",
    colloc: { frame: "I didn't ___ to wake you up.", answer: "mean", options: ["mean", "think", "want"], whyHe: "I didn't mean to = לא התכוונתי." },
  },
  {
    id: "v-op-matter",
    word: "matter",
    pos: "v",
    he: "להיות חשוב; משנה",
    def: "to be important",
    examples: ["It doesn't matter what time you come.", "Does it matter if I pay tomorrow?"],
    cloze: "Money doesn't ___ to me as much as free time.",
    collocations: ["it doesn't matter", "what matters is", "no matter what"],
    band: 2,
    tags: ["abstract", "opinions"],
    trap: "'לא משנה' = It doesn't matter (לא it doesn't change / it's not important). 'לא משנה מה' = no matter what.",
  },

  // ---------- nouns ----------
  {
    id: "v-op-point-of-view",
    word: "point of view",
    pos: "n",
    he: "נקודת מבט",
    def: "a way of thinking about something; someone's opinion",
    examples: ["From my point of view, the new schedule is better.", "Try to see it from her point of view."],
    cloze: "From a business ___, the deal makes sense.",
    clozeAnswer: "point of view",
    collocations: ["from my point of view", "see someone's point of view"],
    band: 3,
    tags: ["opinions"],
    trap: "from my point of view — לא 'from my side'. ולא 'according to me'.",
    colloc: { frame: "___ my point of view, this is a mistake.", answer: "From", options: ["From", "In", "By"], whyHe: "from someone's point of view." },
  },
  {
    id: "v-op-opinion",
    word: "opinion",
    pos: "n",
    he: "דעה",
    def: "what you think or believe about something",
    examples: ["In my opinion, the movie was too long.", "Everyone has a different opinion about the new law."],
    cloze: "What's your ___ of the new manager?",
    collocations: ["in my opinion", "have an opinion", "opinion of/about"],
    band: 1,
    tags: ["opinions"],
    trap: "in my opinion — לא 'by my opinion', 'according to me' או 'to my opinion'. אפשר גם: I think / If you ask me.",
    colloc: { frame: "___ my opinion, the second plan is better.", answer: "In", options: ["In", "By", "According to"], whyHe: "in my opinion. according to — רק לגבי מקור אחר, לא אני." },
  },
  {
    id: "v-op-advantage",
    word: "advantage",
    pos: "n",
    he: "יתרון",
    def: "something good that helps you or makes things better",
    examples: ["One advantage of living here is the quiet.", "Speaking two languages is a big advantage."],
    cloze: "The main ___ of the plan is its low cost.",
    collocations: ["advantage of", "big advantage", "take advantage of"],
    band: 2,
    tags: ["abstract", "opinions"],
    trap: "advantage OF something. take advantage of = לנצל (הזדמנות או אדם).",
    colloc: { frame: "You should ___ advantage of the free course.", answer: "take", options: ["take", "make", "get"], whyHe: "take advantage of = לנצל." },
  },
  {
    id: "v-op-disadvantage",
    word: "disadvantage",
    pos: "n",
    he: "חיסרון",
    def: "something bad about a situation or thing",
    examples: ["The only disadvantage is the price.", "Working from home has some disadvantages."],
    cloze: "A big ___ of the apartment is that it's far from the station.",
    collocations: ["disadvantage of", "advantages and disadvantages"],
    band: 2,
    tags: ["abstract", "opinions"],
    trap: "'יתרונות וחסרונות' = advantages and disadvantages או pros and cons. לא 'plus and minus'.",
  },
  {
    id: "v-op-benefit",
    word: "benefit",
    pos: "n",
    he: "תועלת; יתרון",
    def: "a good result or help that you get from something",
    examples: ["Exercise has many benefits for your health.", "What are the benefits of joining the club?"],
    cloze: "One ___ of cycling to work is that it's free.",
    collocations: ["benefit of", "health benefits", "benefit from"],
    band: 3,
    tags: ["abstract"],
    trap: "benefit OF (שם עצם); הפועל: benefit FROM (You'll benefit from the course).",
  },
  {
    id: "v-op-drawback",
    word: "drawback",
    pos: "n",
    he: "חיסרון",
    def: "a disadvantage or problem with something",
    examples: ["The main drawback of the car is its size.", "Every plan has its drawbacks."],
    cloze: "The only ___ is that the course is expensive.",
    collocations: ["drawback of", "major drawback", "have drawbacks"],
    band: 4,
    tags: ["abstract", "opinions"],
    trap: "drawback = חיסרון (כמו disadvantage), לא 'צעד אחורה' (setback).",
  },
  {
    id: "v-op-issue",
    word: "issue",
    pos: "n",
    he: "נושא; בעיה",
    def: "an important subject or a problem people talk about",
    examples: ["Money is a big issue for many students.", "We need to discuss a few issues before we start."],
    cloze: "Parking is a serious ___ in this neighborhood.",
    collocations: ["a serious issue", "raise an issue", "have issues with"],
    band: 2,
    tags: ["abstract"],
    trap: "issue = נושא/בעיה. 'I have an issue with' = יש לי בעיה עם. לא לבלבל עם 'הנפקה' של מגזין (זה גם issue).",
  },
  {
    id: "v-op-purpose",
    word: "purpose",
    pos: "n",
    he: "מטרה; תכלית",
    def: "the reason why something is done or exists",
    examples: ["The purpose of the meeting is to plan the trip.", "He did it on purpose."],
    cloze: "What's the ___ of this form?",
    collocations: ["the purpose of", "on purpose", "serve a purpose"],
    band: 3,
    tags: ["abstract"],
    trap: "on purpose = בכוונה. 'purpose of' ולא 'purpose for'.",
    colloc: { frame: "I'm sure he broke it ___ purpose.", answer: "on", options: ["on", "in", "by"], whyHe: "on purpose = בכוונה." },
  },
  {
    id: "v-op-aim",
    word: "aim",
    pos: "n",
    he: "מטרה; יעד",
    def: "what you are trying to achieve",
    examples: ["My main aim this year is to speak English more.", "The aim of the game is to collect points."],
    cloze: "The ___ of the campaign is to reduce waste.",
    collocations: ["the aim of", "main aim", "achieve an aim"],
    band: 3,
    tags: ["abstract"],
    trap: "aim דומה ל-goal. הפועל: aim to do / aim at -ing.",
  },
  {
    id: "v-op-goal",
    word: "goal",
    pos: "n",
    he: "מטרה; יעד",
    def: "something you want to achieve in the future",
    examples: ["My goal is to run 10 km by summer.", "Set small goals and you'll make progress."],
    cloze: "Her main ___ is to finish her degree this year.",
    collocations: ["set a goal", "reach/achieve a goal", "main goal"],
    band: 1,
    tags: ["abstract"],
    trap: "'להציב מטרה' = set a goal (לא put a goal). 'להשיג מטרה' = achieve/reach a goal.",
    colloc: { frame: "I ___ myself a goal: 20 new words a week.", answer: "set", options: ["set", "put", "made"], whyHe: "set a goal — לא put a goal." },
  },
  {
    id: "v-op-solution",
    word: "solution",
    pos: "n",
    he: "פתרון",
    def: "a way to solve a problem",
    examples: ["There's no easy solution to this problem.", "We found a solution that works for everyone."],
    cloze: "Let's think about a ___ instead of complaining.",
    collocations: ["solution to a problem", "find a solution", "simple solution"],
    band: 1,
    tags: ["abstract", "reasoning"],
    trap: "solution TO a problem — לא solution of. 'למצוא פתרון' = find a solution.",
    colloc: { frame: "Is there a solution ___ this problem?", answer: "to", options: ["to", "of", "for"], whyHe: "solution to a problem." },
  },
  {
    id: "v-op-approach",
    word: "approach",
    pos: "n",
    he: "גישה; דרך",
    def: "a way of doing or dealing with something",
    examples: ["We need a different approach to this problem.", "Her approach to teaching is very relaxed."],
    cloze: "Let's try a new ___. Talking isn't working.",
    collocations: ["approach to", "take a different approach", "practical approach"],
    band: 3,
    tags: ["abstract", "reasoning"],
    trap: "approach TO something (גישה ל). לא approach for.",
  },

  
  {
    id: "v-op-opportunity",
    word: "opportunity",
    pos: "n",
    he: "הזדמנות",
    def: "a chance to do something good or useful",
    examples: ["This job is a great opportunity for me.", "I never had the opportunity to travel."],
    cloze: "Don't miss this ___ to meet the team.",
    collocations: ["opportunity to do", "great opportunity", "miss an opportunity"],
    band: 2,
    tags: ["abstract"],
    trap: "opportunity TO do. 'יש לי אפשרות ל' = I have the opportunity/chance to — לא possibility to.",
    colloc: { frame: "It's a great opportunity ___ learn from experts.", answer: "to", options: ["to", "for", "of"], whyHe: "opportunity to do." },
  },
  {
    id: "v-op-chance",
    word: "chance",
    pos: "n",
    he: "סיכוי; הזדמנות",
    def: "a possibility that something will happen; an opportunity",
    examples: ["There's a good chance it will rain tomorrow.", "Give me a chance to explain."],
    cloze: "Is there any ___ you could work on Sunday?",
    collocations: ["a good chance", "chance of", "chance to do", "no chance"],
    band: 2,
    tags: ["abstract"],
    trap: "chance OF + -ing (סיכוי ש) / chance TO do (הזדמנות ל). 'אין סיכוי' = No chance / No way.",
    colloc: { frame: "There's a small chance ___ getting tickets.", answer: "of", options: ["of", "to", "for"], whyHe: "chance of -ing = סיכוי ש." },
  },
  {
    id: "v-op-risk",
    word: "risk",
    pos: "n",
    he: "סיכון",
    def: "the possibility that something bad will happen",
    examples: ["There's a risk of losing all the data.", "He took a big risk when he quit his job."],
    cloze: "Smoking increases the ___ of heart disease.",
    collocations: ["take a risk", "risk of", "at risk"],
    band: 2,
    tags: ["abstract"],
    trap: "'לקחת סיכון' = take a risk (כאן דווקא take). risk OF -ing.",
    colloc: { frame: "You're ___ a risk driving on those tires.", answer: "taking", options: ["taking", "making", "doing"], whyHe: "take a risk." },
  },
  {
    id: "v-op-decision",
    word: "decision",
    pos: "n",
    he: "החלטה",
    def: "a choice you make after thinking about something",
    examples: ["It was a hard decision to leave.", "We have to make a decision by Friday."],
    cloze: "That's the best ___ I've ever made.",
    collocations: ["make a decision", "final decision", "decision to do"],
    band: 1,
    tags: ["abstract", "reasoning"],
    trap: "'לקבל החלטה' = make a decision — לא take/get/receive a decision.",
    colloc: { frame: "We need to ___ a decision today.", answer: "make", options: ["make", "take", "get"], whyHe: "make a decision." },
  },
  {
    id: "v-op-choice",
    word: "choice",
    pos: "n",
    he: "בחירה; ברירה",
    def: "the act of choosing; the things you can choose from",
    examples: ["It was my choice to stay.", "We had no choice but to wait."],
    cloze: "You have a ___: the train or the bus.",
    collocations: ["have no choice", "make a choice", "a wide choice"],
    band: 2,
    tags: ["abstract"],
    trap: "'אין ברירה' = There's no choice / I have no choice. choose = הפועל, choice = שם העצם.",
  },
  {
    id: "v-op-option",
    word: "option",
    pos: "n",
    he: "אפשרות; אופציה",
    def: "one of the things you can choose to do",
    examples: ["We have two options: fix it or buy a new one.", "Renting is a good option for students."],
    cloze: "Keep your ___ open until you hear from them.",
    clozeAnswer: "options",
    collocations: ["have the option", "best option", "keep your options open"],
    band: 2,
    tags: ["abstract"],
    trap: "'אין לי אפשרות' (בחירה) = I have no option/choice. 'אין לי אפשרות' (יכולת) = I can't.",
  },
  {
    id: "v-op-alternative",
    word: "alternative",
    pos: "n",
    he: "חלופה; אלטרנטיבה",
    def: "something you can choose instead of something else",
    examples: ["Is there an alternative to driving?", "We have no alternative but to cancel."],
    cloze: "Tea is a good ___ to coffee in the evening.",
    collocations: ["alternative to", "no alternative", "an alternative option"],
    band: 4,
    tags: ["abstract"],
    trap: "alternative TO משהו (לא alternative for). 'אין ברירה' = there's no alternative.",
  },
  {
    id: "v-op-reason",
    word: "reason",
    pos: "n",
    he: "סיבה",
    def: "why something happens or why someone does something",
    examples: ["What's the reason for the delay?", "The main reason I moved was the job."],
    cloze: "There's no ___ to worry.",
    collocations: ["reason for", "the main reason", "for some reason"],
    band: 1,
    tags: ["reasoning"],
    trap: "reason FOR — לא reason of. 'הסיבה היא ש' = The reason is that... (לא: the reason is because).",
    colloc: { frame: "What was the reason ___ his decision?", answer: "for", options: ["for", "of", "to"], whyHe: "reason for." },
  },

  {
    id: "v-op-impact",
    word: "impact",
    pos: "n",
    he: "השפעה",
    def: "a strong effect that something has on something else",
    examples: ["The new law had a big impact on small businesses.", "Social media has an impact on how we talk."],
    cloze: "The price rise had a huge ___ on families.",
    collocations: ["have an impact on", "big impact", "negative impact"],
    band: 3,
    tags: ["abstract", "reasoning"],
    trap: "impact ON — לא impact for/to. 'להשפיע' = have an impact on.",
    colloc: { frame: "The change had a big impact ___ our team.", answer: "on", options: ["on", "for", "to"], whyHe: "impact on." },
  },
  {
    id: "v-op-consequence",
    word: "consequence",
    pos: "n",
    he: "תוצאה; השלכה",
    def: "a result of an action, often a bad one",
    examples: ["Skipping class has consequences.", "One consequence of the strike was empty shelves."],
    cloze: "He never thinks about the ___ of his actions.",
    clozeAnswer: "consequences",
    collocations: ["consequence of", "serious consequences", "as a consequence"],
    band: 4,
    tags: ["abstract", "reasoning"],
    trap: "consequence OF. בדרך כלל תוצאה שלילית. 'כתוצאה מכך' = as a consequence / as a result.",
  },
  {
    id: "v-op-possibility",
    word: "possibility",
    pos: "n",
    he: "אפשרות (שיקרה)",
    def: "the chance that something may happen or be true",
    examples: ["There's a possibility of snow tonight.", "We can't rule out the possibility that he forgot."],
    cloze: "Is there any ___ of changing the date?",
    collocations: ["possibility of -ing", "possibility that", "a strong possibility"],
    band: 3,
    tags: ["abstract", "reasoning"],
    trap: "possibility OF -ing או possibility that — לא possibility to do. 'הזדמנות/אפשרות ל' = opportunity/chance to.",
    colloc: { frame: "There's a possibility ___ delays on the road.", answer: "of", options: ["of", "to", "for"], whyHe: "possibility of." },
  },
  {
    id: "v-op-point",
    word: "point",
    pos: "n",
    he: "טעם; עיקר; נקודה",
    def: "the main idea or purpose of something",
    examples: ["What's the point of arguing?", "The point is, we can't afford it."],
    cloze: "I see your ___, but I still think you're wrong.",
    collocations: ["the point is", "what's the point", "make a point", "get to the point"],
    band: 2,
    tags: ["opinions", "reasoning"],
    trap: "'מה הטעם?' = What's the point? 'העיקר הוא ש' = The point is that... 'תגיע לעניין' = Get to the point.",
    colloc: { frame: "OK, ___ to the point. What do you want?", answer: "get", options: ["get", "go", "come"], whyHe: "get to the point = תגיע לעניין." },
  },
  {
    id: "v-op-priority",
    word: "priority",
    pos: "n",
    he: "עדיפות",
    def: "something that is more important than other things",
    examples: ["My top priority right now is my health.", "Safety is a priority for the company."],
    cloze: "Finding a job is my first ___ after the exams.",
    collocations: ["top priority", "give priority to", "a high priority"],
    band: 3,
    tags: ["abstract"],
    trap: "'יש לי סדרי עדיפויות' = I have priorities. 'לתת עדיפות ל' = give priority to.",
  },

  // ---------- adjectives & adverbs ----------
  {
    id: "v-op-likely",
    word: "likely",
    pos: "adj",
    he: "סביר; צפוי",
    def: "probably going to happen or be true",
    examples: ["It's likely to rain later.", "She's likely to get the job."],
    cloze: "The most ___ reason is that they forgot.",
    collocations: ["likely to do", "it's likely that", "very likely", "more/less likely"],
    band: 2,
    tags: ["reasoning"],
    trap: "likely הוא שם תואר: It's likely that / likely to happen. לא 'it likely rains'. במקום: it will probably rain.",
    colloc: { frame: "He's ___ to be late, as usual.", answer: "likely", options: ["likely", "probably", "possible"], whyHe: "be likely to do = צפוי ש. probably לא מתחבר ל-to; possible לא מתאר אדם." },
  },
  {
    id: "v-op-unlikely",
    word: "unlikely",
    pos: "adj",
    he: "לא סביר",
    def: "probably not going to happen",
    examples: ["It's unlikely that we'll finish today.", "He's unlikely to change his mind."],
    cloze: "It's ___ to snow in Tel Aviv.",
    collocations: ["unlikely to do", "highly unlikely", "it's unlikely that"],
    band: 2,
    tags: ["reasoning"],
    trap: "unlikely = לא סביר שיקרה. unexpected = לא צפוי מראש / מפתיע. אל תבלבלו.",
  },
  {
    id: "v-op-obvious",
    word: "obvious",
    pos: "adj",
    he: "ברור; מובן מאליו",
    def: "easy to see or understand",
    examples: ["It's obvious that he's tired.", "The answer was obvious to everyone."],
    cloze: "The reason is ___: they simply ran out of money.",
    collocations: ["it's obvious that", "obvious reason", "obviously"],
    band: 2,
    tags: ["reasoning"],
    trap: "obvious = ברור מאליו. obviously = כמובן / ברור ש. 'ברור!' כתשובה = Of course / Sure, לא obvious.",
  },
  {
    id: "v-op-reasonable",
    word: "reasonable",
    pos: "adj",
    he: "סביר; הגיוני",
    def: "fair and sensible; not too much",
    examples: ["That's a reasonable price for a used car.", "It's reasonable to ask for a break."],
    cloze: "The hotel was nice and the prices were ___.",
    collocations: ["reasonable price", "reasonable to do", "sounds reasonable"],
    band: 2,
    tags: ["opinions", "reasoning"],
    trap: "reasonable = סביר/הוגן. 'מחיר סביר' = reasonable price. reasonably good = לא רע.",
  },
  {
    id: "v-op-ridiculous",
    word: "ridiculous",
    pos: "adj",
    he: "מגוחך",
    def: "very silly or unreasonable",
    examples: ["Fifty dollars for a coffee? That's ridiculous!", "It's ridiculous to wait two hours for a bus."],
    cloze: "Don't be ___. Nobody is going to fire you.",
    collocations: ["that's ridiculous", "look ridiculous", "absolutely ridiculous"],
    band: 3,
    tags: ["opinions"],
    trap: "ridiculous = מגוחך, לא funny (מצחיק). 'לא הגיוני בכלל' = ridiculous / absurd.",
  },
  {
    id: "v-op-pointless",
    word: "pointless",
    pos: "adj",
    he: "חסר טעם",
    def: "with no purpose or useful result",
    examples: ["It's pointless to argue with him.", "Another meeting would be pointless."],
    cloze: "It's ___ to call now. The office is closed.",
    collocations: ["it's pointless to do", "pointless argument", "completely pointless"],
    band: 3,
    tags: ["opinions"],
    trap: "'אין טעם ל' = It's pointless to / There's no point in -ing. לא 'there's no taste'.",
    colloc: { frame: "There's no point ___ waiting any longer.", answer: "in", options: ["in", "to", "of"], whyHe: "no point in -ing." },
  },
  
  {
    id: "v-op-according-to",
    word: "according to",
    pos: "prep",
    he: "לפי; על פי",
    def: "as said or shown by someone or something",
    examples: ["According to the news, the road is closed.", "According to my mom, I talk too fast."],
    cloze: "___ the map, the station is on the left.",
    clozeAnswer: "According to",
    collocations: ["according to the report", "according to him"],
    band: 2,
    tags: ["opinions", "reasoning"],
    trap: "according to מציין מקור אחר, לא אותך: 'לפי דעתי' = in my opinion, לא according to me.",
    colloc: { frame: "___ the weather app, it'll rain tomorrow.", answer: "According to", options: ["According to", "By", "In"], whyHe: "according to + מקור מידע." },
  },
  {
    id: "v-op-apparently",
    word: "apparently",
    pos: "adv",
    he: "כנראה; מסתבר ש",
    def: "used to say that something seems true from what you have heard",
    examples: ["Apparently, the store is closing next month.", "He's apparently moving to Haifa."],
    cloze: "___, they got married last year. I had no idea.",
    clozeAnswer: "Apparently",
    collocations: ["apparently not", "apparently so"],
    band: 4,
    tags: ["reasoning"],
    trap: "apparently = שמעתי ש / מסתבר ש (מידע מכלי שני). לא 'לכאורה' בלבד, ולא 'ברור ש' (obviously).",
  },

  {
    id: "v-op-definitely",
    word: "definitely",
    pos: "adv",
    he: "בהחלט; בטוח",
    def: "without any doubt; certainly",
    examples: ["I'll definitely be there at eight.", "That's definitely the best pizza in town."],
    cloze: "Are you coming? — Yes, ___!",
    collocations: ["definitely not", "will definitely", "yes, definitely"],
    band: 2,
    tags: ["opinions"],
    trap: "איות: definitely (לא definately / definitly). 'בהחלט לא' = definitely not.",
    colloc: { frame: "\"Will you come to the party?\" \"___!\"", answer: "Definitely", options: ["Definitely", "Definitively", "Definately"], whyHe: "האיות הנכון: definitely. definitively = באופן סופי (משמעות אחרת)." },
  },
  {
    id: "v-op-probably",
    word: "probably",
    pos: "adv",
    he: "כנראה",
    def: "likely to be true or to happen",
    examples: ["He's probably still at work.", "We'll probably stay home this weekend."],
    cloze: "I'll ___ be late, so start without me.",
    collocations: ["probably not", "will probably", "most probably"],
    band: 1,
    tags: ["reasoning"],
    trap: "מיקום: probably אחרי be / לפני פועל רגיל: He's probably right. I probably won't come (לא: I won't probably).",
    colloc: { frame: "She's ___ not coming. She hates parties.", answer: "probably", options: ["probably", "probable", "probability"], whyHe: "probably = תואר הפועל; probable = שם תואר." },
  },
  {
    id: "v-op-mostly",
    word: "mostly",
    pos: "adv",
    he: "בעיקר; ברוב המקרים",
    def: "in most cases or most of the time",
    examples: ["I mostly work from home.", "The guests were mostly friends from college."],
    cloze: "We ___ speak Hebrew at home, but sometimes English.",
    collocations: ["mostly because", "mostly at home"],
    band: 3,
    tags: ["reasoning"],
    trap: "mostly = ברוב המקרים. 'הכי הרבה' = the most. 'רוב האנשים' = most people (לא the most people).",
  },
  {
    id: "v-op-rather",
    word: "rather",
    pos: "adv",
    he: "די; יותר נכון; מעדיף",
    def: "quite; used to show preference or to correct yourself",
    examples: ["I'd rather stay in tonight.", "It was rather cold for May."],
    cloze: "I'd ___ walk than take a taxi.",
    collocations: ["would rather", "rather than", "or rather"],
    band: 4,
    tags: ["opinions"],
    trap: "I'd rather + פועל בסיסי (I'd rather go), לא I'd rather to go. rather than = במקום / ולא.",
    colloc: { frame: "I'd rather ___ at home tonight.", answer: "stay", options: ["stay", "to stay", "staying"], whyHe: "would rather + פועל בסיסי." },
  },
  {
    id: "v-op-quite",
    word: "quite",
    pos: "adv",
    he: "די; למדי",
    def: "to some degree; fairly (in US English, sometimes very)",
    examples: ["The movie was quite good.", "I'm quite sure I locked the door."],
    cloze: "The hotel was ___ nice, but a bit noisy.",
    collocations: ["quite good", "quite a lot", "not quite"],
    band: 2,
    tags: ["opinions"],
    trap: "quite (די) ≠ quiet (שקט)! not quite = לא לגמרי. quite a lot = די הרבה.",
    colloc: { frame: "It's ___ a long way to the beach from here.", answer: "quite", options: ["quite", "quiet", "very"], whyHe: "quite a long way = די רחוק. very לא בא לפני a." },
  },
  {
    id: "v-op-fairly",
    word: "fairly",
    pos: "adv",
    he: "די; למדי",
    def: "to some degree, but not very",
    examples: ["The test was fairly easy.", "It's a fairly small town."],
    cloze: "The instructions are ___ simple. You'll manage.",
    collocations: ["fairly easy", "fairly common", "fairly well"],
    band: 3,
    tags: ["opinions"],
    trap: "fairly = די (לא 'בהגינות' בהקשר הזה). fairly good = לא רע. fair = הוגן.",
  },
  {
    id: "v-op-extremely",
    word: "extremely",
    pos: "adv",
    he: "מאוד; במידה קיצונית",
    def: "very; to a very high degree",
    examples: ["It was extremely hot yesterday.", "She's extremely good at her job."],
    cloze: "Be careful. The roads are ___ dangerous tonight.",
    collocations: ["extremely important", "extremely difficult"],
    band: 2,
    tags: ["opinions"],
    trap: "extremely מחזק תארים רגילים: extremely tired. לא עם תארים מוחלטים (extremely perfect — לא; absolutely perfect).",
  },
  {
    id: "v-op-slightly",
    word: "slightly",
    pos: "adv",
    he: "מעט; קצת",
    def: "a little",
    examples: ["The new version is slightly faster.", "I'm slightly worried about the exam."],
    cloze: "Prices are ___ higher this year, but not by much.",
    collocations: ["slightly different", "slightly more/less", "slightly better"],
    band: 4,
    tags: ["opinions"],
    trap: "slightly = מעט (קצת יותר עדין מ-a bit). slight = קל (a slight problem).",
  },
  {
    id: "v-op-in-general",
    word: "in general",
    pos: "phr",
    he: "באופן כללי",
    def: "usually; when thinking about the whole situation",
    examples: ["In general, I like working with people.", "People here are, in general, very friendly."],
    cloze: "___, the food in that area is cheap.",
    clozeAnswer: "In general",
    collocations: ["in general,", "generally speaking"],
    band: 2,
    tags: ["opinions", "reasoning"],
    trap: "in general — לא 'in generally'. גם: generally / generally speaking. 'בגדול' בדיבור = basically / overall.",
  },
  {
    id: "v-op-on-the-other-hand",
    word: "on the other hand",
    pos: "phr",
    he: "מצד שני",
    def: "used to give a different or opposite point",
    examples: ["The job pays well. On the other hand, the hours are long.", "It's far, but on the other hand, it's cheap."],
    cloze: "It's a nice car. ___, it uses a lot of gas.",
    clozeAnswer: "On the other hand",
    collocations: ["on the one hand... on the other hand"],
    band: 3,
    tags: ["opinions", "reasoning"],
    trap: "'מצד שני' = on the other hand, לא 'from the other side'. 'מצד אחד' = on the one hand.",
    colloc: { frame: "On the one hand it's cheap; on the ___ hand it's slow.", answer: "other", options: ["other", "second", "another"], whyHe: "on the other hand — לא on the second hand." },
  },

  
  {
    id: "v-op-convincing",
    word: "convincing",
    pos: "adj",
    he: "משכנע",
    def: "making you believe that something is true",
    examples: ["Her argument was very convincing.", "That's not a very convincing excuse."],
    cloze: "The evidence isn't ___ enough to prove it.",
    collocations: ["convincing argument", "convincing evidence", "not very convincing"],
    band: 3,
    tags: ["opinions", "reasoning"],
    trap: "convincing = משכנע (הטיעון). convinced = משוכנע (האדם). 'אני משוכנע' = I'm convinced.",
  },
  {
    id: "v-op-controversial",
    word: "controversial",
    pos: "adj",
    he: "שנוי במחלוקת",
    def: "causing a lot of disagreement between people",
    examples: ["The new law is very controversial.", "He's known for his controversial opinions."],
    cloze: "It's a ___ topic, so let's not discuss it at dinner.",
    collocations: ["controversial issue", "controversial decision", "highly controversial"],
    band: 4,
    tags: ["opinions"],
    trap: "controversial = שנוי במחלוקת. 'נושא רגיש' = sensitive topic; 'נושא שנוי במחלוקת' = controversial topic.",
  },
  {
    id: "v-op-relevant",
    word: "relevant",
    pos: "adj",
    he: "רלוונטי; שייך לעניין",
    def: "connected to what is being talked about",
    examples: ["Is this information relevant to our discussion?", "Only bring the relevant documents."],
    cloze: "Stick to the ___ facts. We don't need the whole story.",
    collocations: ["relevant to", "relevant information", "highly relevant"],
    band: 3,
    tags: ["reasoning"],
    trap: "relevant TO משהו (לא relevant for). ההפך: irrelevant.",
    colloc: { frame: "That question isn't relevant ___ this discussion.", answer: "to", options: ["to", "for", "with"], whyHe: "relevant to." },
  },
  {
    id: "v-op-aware",
    word: "aware",
    pos: "adj",
    he: "מודע",
    def: "knowing that something exists or is happening",
    examples: ["I wasn't aware of the change in plans.", "Are you aware that the deadline is tomorrow?"],
    cloze: "She's well ___ of the risks.",
    collocations: ["aware of", "aware that", "well aware", "become aware"],
    band: 3,
    tags: ["abstract", "reasoning"],
    trap: "be aware OF משהו / aware that. 'אני מודע לזה' = I'm aware of it (לא aware to it).",
    colloc: { frame: "I'm fully aware ___ the problem.", answer: "of", options: ["of", "to", "about"], whyHe: "aware of." },
  },
  {
    id: "v-op-typical",
    word: "typical",
    pos: "adj",
    he: "טיפוסי; אופייני",
    def: "usual; showing the normal qualities of a type",
    examples: ["It's a typical Israeli breakfast: salad, eggs, and cheese.", "That's typical of him. He's always late."],
    cloze: "A ___ working day for me starts at eight.",
    collocations: ["typical of", "typical day", "typically"],
    band: 2,
    tags: ["abstract"],
    trap: "typical OF someone (לא typical for). 'זה אופייני לו' = That's typical of him.",
  },
  {
    id: "v-op-effective",
    word: "effective",
    pos: "adj",
    he: "יעיל; אפקטיבי",
    def: "working well and producing the result you want",
    examples: ["The new medicine is very effective.", "Praise is more effective than punishment."],
    cloze: "Is there an ___ way to learn vocabulary fast?",
    collocations: ["effective way", "highly effective", "effective in/at -ing"],
    band: 3,
    tags: ["abstract", "opinions"],
    trap: "effective = עובד ומשיג תוצאה. efficient = יעיל בזמן/משאבים (בלי בזבוז). effect = השפעה (שם עצם).",
    colloc: { frame: "This method is very ___ for learning new words.", answer: "effective", options: ["effective", "effect", "affective"], whyHe: "effective = יעיל/אפקטיבי. effect הוא שם עצם." },
  },
];
