import type { VocabItem } from "@/lib/types";

// People, personality, relationships, feelings. Ids: v-pp-*
export const PEOPLE_FEELINGS: VocabItem[] = [
  // ---------------- verbs & phrases ----------------
  {
    id: "v-pp-get-along-with",
    word: "get along with",
    pos: "phr",
    he: "להסתדר עם",
    def: "to have a friendly, easy relationship with someone",
    examples: ["I get along with my roommate really well.", "Do you get along with your boss?"],
    cloze: "She doesn't ___ her sister, they fight all the time.",
    clozeAnswer: "get along with",
    collocations: ["get along well with", "get along with each other"],
    band: 1,
    tags: ["relationships", "people"],
    trap: "אומרים get along WITH someone. לא 'get along good' אלא get along WELL.",
    colloc: { frame: "My parents and I get along really ___ these days.", answer: "well", options: ["well", "good", "nice"], whyHe: "אחרי פועל בא תואר הפועל well, לא good." },
  },
  {
    id: "v-pp-fall-out-with",
    word: "fall out with",
    pos: "phr",
    he: "לריב ולהפסיק לדבר עם",
    def: "to have a serious argument with someone and stop being friends",
    examples: ["He fell out with his brother over money.", "They fell out years ago and never spoke again."],
    cloze: "I ___ my best friend last year, and we still don't talk.",
    clozeAnswer: "fell out with",
    collocations: ["fall out with someone over something"],
    band: 3,
    tags: ["relationships"],
    trap: "fall out with = לריב ולהתנתק. זה לא 'ליפול החוצה'. הריב עצמו: fall out OVER something.",
  },

  {
    id: "v-pp-get-engaged",
    word: "get engaged",
    pos: "phr",
    he: "להתארס",
    def: "to formally agree to marry someone",
    examples: ["We got engaged last summer in Greece.", "They got engaged after only two months."],
    cloze: "Guess what? Tom and Lily just ___!",
    clozeAnswer: "got engaged",
    collocations: ["get engaged to someone", "engagement ring"],
    band: 2,
    tags: ["relationships"],
    trap: "engaged TO someone, לא 'engaged with'. engaged with פירושו מעורב או עסוק במשהו.",
    colloc: { frame: "She's engaged ___ a guy she met at work.", answer: "to", options: ["to", "with", "for"], whyHe: "מאורסת ל- = engaged TO." },
  },
  {
    id: "v-pp-trust",
    word: "trust",
    pos: "v",
    he: "לסמוך על, לבטוח ב-",
    def: "to believe that someone is honest and will not hurt you",
    examples: ["I trust her completely.", "You can't trust everything you read online."],
    cloze: "Don't lend him money. I don't ___ him.",
    collocations: ["trust someone completely", "trust your instincts"],
    band: 1,
    tags: ["relationships", "people"],
    trap: "trust הוא פועל ישיר: I trust him. לא 'I trust ON him' ולא 'trust IN him' בדיבור יומיומי.",
  },

  {
    id: "v-pp-look-up-to",
    word: "look up to",
    pos: "phr",
    he: "להעריץ, לראות כמודל",
    def: "to admire and respect someone, often an older person",
    examples: ["I always looked up to my older brother.", "Kids look up to their teachers."],
    cloze: "As a boy, he ___ his grandfather more than anyone.",
    clozeAnswer: "looked up to",
    collocations: ["look up to someone as a role model"],
    band: 2,
    tags: ["relationships", "people"],
    trap: "look up to = להעריץ אדם. look up (בלי to) = לחפש מילה במילון. look DOWN on = לזלזל.",
  },
  {
    id: "v-pp-get-on-nerves",
    word: "get on someone's nerves",
    pos: "phr",
    he: "לעלות למישהו על העצבים",
    def: "to annoy someone, especially by doing something again and again",
    examples: ["His constant humming gets on my nerves.", "Stop tapping the table, you're getting on everyone's nerves."],
    cloze: "That alarm sound really ___. Turn it off!",
    clozeAnswer: "gets on my nerves",
    collocations: ["really get on someone's nerves"],
    band: 3,
    tags: ["feelings", "people"],
    trap: "אומרים get ON my nerves, לא 'go up on my nerves' ולא 'climb on my nerves'.",
    colloc: { frame: "The way he chews with his mouth open ___ on my nerves.", answer: "gets", options: ["gets", "goes", "climbs"], whyHe: "הביטוי: get on someone's nerves." },
    accept: ["gets on my nerves", "is getting on my nerves"],
  },
  {
    id: "v-pp-apologize",
    word: "apologize",
    pos: "v",
    he: "להתנצל",
    def: "to say you are sorry for something you did",
    examples: ["I apologized to her for being late.", "He never apologizes, even when he's wrong."],
    cloze: "You hurt her feelings. You should ___ to her.",
    collocations: ["apologize to someone", "apologize for something", "apologize sincerely"],
    band: 1,
    tags: ["relationships", "feelings"],
    trap: "apologize TO someone FOR something. לא 'apologize someone' ולא 'apologize about'. 'I'm sorry' הוא יותר נפוץ בדיבור.",
    colloc: { frame: "He apologized ___ shouting at me.", answer: "for", options: ["for", "about", "on"], whyHe: "מתנצלים FOR מעשה: apologize for + ing." },
    accept: ["apologise"],
  },
  {
    id: "v-pp-forgive",
    word: "forgive",
    pos: "v",
    he: "לסלוח",
    def: "to stop being angry at someone for something they did",
    examples: ["I forgave him, but I haven't forgotten.", "Please forgive me for missing your birthday."],
    cloze: "It was an accident. Can you ___ me?",
    collocations: ["forgive someone for something", "forgive and forget"],
    band: 1,
    tags: ["relationships", "feelings"],
    trap: "forgive SOMEONE (בלי to): forgive me, לא 'forgive to me'. forgive – forgave – forgiven.",
  },
  {
    id: "v-pp-blame",
    word: "blame",
    pos: "v",
    he: "להאשים",
    def: "to say that someone is responsible for something bad",
    examples: ["Don't blame me, it wasn't my idea.", "She blamed her brother for breaking the vase."],
    cloze: "Stop trying to ___ everyone else for your mistakes.",
    collocations: ["blame someone for something", "blame it on", "take the blame"],
    band: 2,
    tags: ["relationships", "people"],
    trap: "blame someone FOR something, או blame something ON someone. לא 'blame on me' בלי אובייקט.",
    colloc: { frame: "They blamed the delay ___ the weather.", answer: "on", options: ["on", "for", "to"], whyHe: "blame X ON Y = לתלות את האשמה ב-Y." },
  },
  {
    id: "v-pp-argue",
    word: "argue",
    pos: "v",
    he: "להתווכח, לריב",
    def: "to speak angrily to someone because you disagree",
    examples: ["My parents argue about money all the time.", "I don't want to argue with you."],
    cloze: "We always ___ about who should do the dishes.",
    collocations: ["argue with someone", "argue about something", "argue over"],
    band: 1,
    tags: ["relationships"],
    trap: "argue WITH someone ABOUT something. לא 'argue on'. גם: argue = לטעון (argue that...).",
    colloc: { frame: "They argued ___ where to go on vacation.", answer: "about", options: ["about", "on", "for"], whyHe: "מתווכחים ABOUT נושא." },
  },
  {
    id: "v-pp-complain",
    word: "complain",
    pos: "v",
    he: "להתלונן",
    def: "to say that you are not happy about something",
    examples: ["He complained about the noise all night.", "Stop complaining and do something about it."],
    cloze: "She always ___ that nobody helps her.",
    clozeAnswer: "complains",
    collocations: ["complain about something", "complain to someone", "nothing to complain about"],
    band: 1,
    tags: ["feelings", "people"],
    trap: "complain ABOUT something TO someone. לא 'complain on'. גם: complain (פועל) לעומת complaint (שם עצם).",
    colloc: { frame: "The neighbors complained ___ the manager about the party.", answer: "to", options: ["to", "at", "with"], whyHe: "מתלוננים TO האדם, ABOUT הבעיה." },
  },
  {
    id: "v-pp-praise",
    word: "praise",
    pos: "v",
    he: "לשבח",
    def: "to say good things about someone because of what they did",
    examples: ["The coach praised the team for their effort.", "She was praised for her honesty."],
    cloze: "The manager ___ him in front of everyone for closing the deal.",
    clozeAnswer: "praised",
    collocations: ["praise someone for something", "highly praised"],
    band: 3,
    tags: ["people"],
    trap: "praise someone FOR something. 'pray' (להתפלל) נשמע דומה אבל נכתב אחרת.",
  },
  {
    id: "v-pp-keep-in-touch",
    word: "keep in touch",
    pos: "phr",
    he: "לשמור על קשר",
    def: "to continue to communicate with someone you don't see often",
    examples: ["We keep in touch by texting every week.", "Let's keep in touch after the course ends."],
    cloze: "It was great meeting you. Let's ___!",
    clozeAnswer: "keep in touch",
    collocations: ["keep in touch with someone", "stay in touch", "lose touch"],
    band: 2,
    tags: ["relationships"],
    trap: "keep in touch WITH someone. ההפך: lose touch. לא 'keep contact' (אומרים stay in contact).",
    colloc: { frame: "We lost ___ after she moved to Canada.", answer: "touch", options: ["touch", "contact with", "connection"], whyHe: "lose touch = לאבד קשר, הביטוי הקבוע." },
    accept: ["stay in touch"],
  },

  {
    id: "v-pp-fall-in-love",
    word: "fall in love",
    pos: "phr",
    he: "להתאהב",
    def: "to start to love someone",
    examples: ["They fell in love on the first day of college.", "I think I'm falling in love with him."],
    cloze: "She ___ with a guy she met on a hiking trip.",
    clozeAnswer: "fell in love",
    collocations: ["fall in love with someone", "be in love with"],
    band: 1,
    tags: ["relationships", "feelings"],
    trap: "fall in love WITH someone. לא 'fall in love in'. אחרי ההתאהבות: be in love with.",
  },
  {
    id: "v-pp-ask-out",
    word: "ask someone out",
    pos: "phr",
    he: "להזמין לדייט",
    def: "to invite someone to go on a date with you",
    examples: ["He finally asked her out after months of talking.", "I'm too shy to ask anyone out."],
    cloze: "He finally ___ the girl from the coffee shop.",
    clozeAnswer: "asked out",
    collocations: ["ask someone out on a date", "ask someone out for coffee"],
    band: 2,
    tags: ["relationships"],
    trap: "ask someone OUT = להזמין לדייט. שם האדם באמצע: ask HER out.",
  },

  {
    id: "v-pp-hurt-feelings",
    word: "hurt someone's feelings",
    pos: "phr",
    he: "לפגוע במישהו",
    def: "to make someone feel upset by what you say or do",
    examples: ["I didn't mean to hurt your feelings.", "Her joke really hurt his feelings."],
    cloze: "Don't tell Dan you hate his cooking, you'll ___.",
    clozeAnswer: "hurt his feelings",
    collocations: ["hurt someone's feelings", "get your feelings hurt"],
    band: 2,
    tags: ["feelings", "relationships"],
    trap: "פגעת בי = You hurt my feelings. 'You hurt me' נשמע כמו פגיעה פיזית. אין hurt IN me.",
    colloc: { frame: "I'm sorry if I ___ your feelings yesterday.", answer: "hurt", options: ["hurt", "harmed", "injured"], whyHe: "עם feelings תמיד hurt, לא harm/injure." },
    accept: ["hurt his feelings", "hurt Dan's feelings"],
  },

  {
    id: "v-pp-take-after",
    word: "take after",
    pos: "phr",
    he: "להידמות ל- (הורה)",
    def: "to look or behave like an older family member",
    examples: ["She takes after her mother, they're both very stubborn.", "Who does the baby take after?"],
    cloze: "He's so funny. He definitely ___ his dad.",
    clozeAnswer: "takes after",
    collocations: ["take after your father/mother"],
    band: 4,
    tags: ["people", "relationships"],
    trap: "take after = לדמות להורה באופי או במראה. לא 'look like' (רק מראה) ולא 'similar to'. לא ניתן להפריד: take after HIM.",
  },
  
  {
    id: "v-pp-lose-temper",
    word: "lose your temper",
    pos: "phr",
    he: "לאבד את העשתונות",
    def: "to suddenly become very angry",
    examples: ["Dad lost his temper when he saw the broken window.", "I try not to lose my temper with the kids."],
    cloze: "The coach ___ and shouted at the referee.",
    clozeAnswer: "lost his temper",
    collocations: ["lose your temper with someone", "keep your temper"],
    band: 3,
    tags: ["feelings"],
    trap: "lose your temper = להתפרץ בכעס. lose temper WITH someone. ההפך: keep your temper.",
    colloc: { frame: "Try to ___ your temper, even when the kids are wild.", answer: "keep", options: ["keep", "hold", "save"], whyHe: "keep your temper = לשלוט בכעס. ההפך של lose your temper." },
    accept: ["lost his temper", "lost her temper"],
  },
  
  {
    id: "v-pp-offend",
    word: "offend",
    pos: "v",
    he: "להעליב, לפגוע",
    def: "to make someone upset or angry by saying something disrespectful",
    examples: ["I didn't mean to offend anyone.", "She was offended by his comment about her accent."],
    cloze: "His jokes about religion ___ a lot of people at the party.",
    clozeAnswer: "offended",
    collocations: ["offend someone", "be offended by", "easily offended"],
    band: 3,
    tags: ["feelings", "people"],
    trap: "נעלבתי = I was offended (BY his comment). לא 'I got insulted' בהקשר עדין. offensive = פוגעני.",
    colloc: { frame: "She's very easily ___, so be careful what you say.", answer: "offended", options: ["offended", "offensive", "offending"], whyHe: "נעלבת בקלות = easily offended. offensive = פוגעני (על דברים)." },
  },
  {
    id: "v-pp-stand-up-for",
    word: "stand up for",
    pos: "phr",
    he: "להגן על, לעמוד לצד",
    def: "to defend someone or something when they are attacked or criticized",
    examples: ["Thanks for standing up for me in the meeting.", "You need to stand up for yourself."],
    cloze: "Nobody ___ the new kid when they teased him.",
    clozeAnswer: "stood up for",
    collocations: ["stand up for yourself", "stand up for your rights"],
    band: 3,
    tags: ["relationships", "people"],
    trap: "stand up for someone = להגן על מישהו. stand up TO someone = להתעמת עם מישהו חזק. אל תתבלבלו.",
  },
  {
    id: "v-pp-make-fun-of",
    word: "make fun of",
    pos: "phr",
    he: "לצחוק על, ללעוג",
    def: "to laugh at someone in a way that is not kind",
    examples: ["The kids made fun of his accent.", "Stop making fun of me!"],
    cloze: "They ___ her glasses, so she stopped wearing them.",
    clozeAnswer: "made fun of",
    collocations: ["make fun of someone", "be made fun of"],
    band: 2,
    tags: ["people", "feelings"],
    trap: "צוחקים על מישהו = make fun of / laugh AT him. 'laugh on him' זו שגיאה.",
    colloc: { frame: "Everyone laughed ___ him when he fell.", answer: "at", options: ["at", "on", "of"], whyHe: "laugh AT someone = לצחוק על. 'laugh on' שגוי." },
  },
  {
    id: "v-pp-hold-a-grudge",
    word: "hold a grudge",
    pos: "phr",
    he: "לנטור טינה",
    def: "to keep feeling angry at someone for a long time about something they did",
    examples: ["She still holds a grudge against her old boss.", "Life is too short to hold grudges."],
    cloze: "He apologized years ago, but she still ___ against him.",
    clozeAnswer: "holds a grudge",
    collocations: ["hold a grudge against someone", "bear a grudge"],
    band: 4,
    tags: ["feelings", "relationships"],
    trap: "hold a grudge AGAINST someone, לא 'on'. גם bear a grudge. לא 'keep a grudge'.",
    colloc: { frame: "I don't hold a grudge ___ anyone. I forgive and move on.", answer: "against", options: ["against", "on", "to"], whyHe: "טינה נגד = grudge AGAINST." },
  },
  {
    id: "v-pp-tell-off",
    word: "tell someone off",
    pos: "phr",
    he: "לנזוף ב-, לגעור ב-",
    def: "to speak angrily to someone because they did something wrong",
    examples: ["My mom told me off for coming home late.", "The boss told him off in front of the whole team."],
    cloze: "The teacher ___ the whole class for talking during the test.",
    clozeAnswer: "told off",
    collocations: ["tell someone off for something", "get told off"],
    band: 4,
    tags: ["people", "relationships"],
    trap: "tell someone OFF = לנזוף. בלי off, tell = פשוט לומר. הכינוי באמצע: told ME off.",
  },

  // ---------------- nouns ----------------
  {
    id: "v-pp-relative",
    word: "relative",
    pos: "n",
    he: "קרוב משפחה",
    def: "a member of your family, such as an aunt or a cousin",
    examples: ["We have relatives in Argentina.", "A distant relative left her some money."],
    cloze: "All my ___ came to the wedding, even the ones from abroad.",
    clozeAnswer: "relatives",
    collocations: ["close relative", "distant relative", "friends and relatives"],
    band: 1,
    tags: ["relationships", "people"],
    trap: "קרוב משפחה = relative, לא 'family member close'. 'relative' כתואר = יחסי. אל תאמרו 'my relative' על חבר.",
  },
  {
    id: "v-pp-in-laws",
    word: "in-laws",
    pos: "n",
    he: "משפחת בן/בת הזוג",
    def: "the family of your husband or wife",
    examples: ["We're spending the holiday with my in-laws.", "She gets along well with her in-laws."],
    cloze: "Every Friday we have dinner with my ___.",
    collocations: ["mother-in-law", "father-in-law", "visit the in-laws"],
    band: 3,
    tags: ["relationships"],
    trap: "חמות = mother-in-law, חם = father-in-law, גיס = brother-in-law. ברבים: mothers-in-law (ה-s על המילה הראשונה).",
  },
  {
    id: "v-pp-sibling",
    word: "sibling",
    pos: "n",
    he: "אח או אחות",
    def: "a brother or sister",
    examples: ["Do you have any siblings?", "The two siblings look nothing alike."],
    cloze: "I'm the oldest of four ___.",
    clozeAnswer: "siblings",
    collocations: ["older sibling", "younger sibling", "sibling rivalry"],
    band: 2,
    tags: ["relationships", "people"],
    trap: "sibling = מילה ניטרלית לאח או אחות. בדיבור יומיומי עדיין נפוץ יותר לומר brothers and sisters.",
  },
  {
    id: "v-pp-acquaintance",
    word: "acquaintance",
    pos: "n",
    he: "מכר (לא חבר קרוב)",
    def: "a person you know a little but who is not a close friend",
    examples: ["He's not a friend, just an acquaintance from work.", "I bumped into an old acquaintance at the store."],
    cloze: "I wouldn't call him a friend. He's more of an ___.",
    collocations: ["a casual acquaintance", "an old acquaintance", "make someone's acquaintance"],
    band: 4,
    tags: ["relationships", "people"],
    trap: "מכר = acquaintance. אל תגידו 'friend' על כל מי שאתם מכירים, באנגלית friend זה מישהו קרוב.",
  },
  {
    id: "v-pp-stranger",
    word: "stranger",
    pos: "n",
    he: "אדם זר",
    def: "a person you do not know",
    examples: ["Don't talk to strangers.", "A complete stranger helped me carry my bags."],
    cloze: "I felt lost in the city, surrounded by ___.",
    clozeAnswer: "strangers",
    collocations: ["a complete stranger", "a total stranger", "talk to strangers"],
    band: 1,
    tags: ["people"],
    trap: "stranger = אדם זר, לא 'אדם מוזר' (strange person / weirdo). גם: foreigner = זר ממדינה אחרת.",
  },
  
  {
    id: "v-pp-mood",
    word: "mood",
    pos: "n",
    he: "מצב רוח",
    def: "the way you feel at a particular time",
    examples: ["He's in a bad mood this morning.", "Music always puts me in a good mood."],
    cloze: "Don't ask him now, he's in a terrible ___.",
    collocations: ["be in a good/bad mood", "put someone in a mood", "not in the mood"],
    band: 1,
    tags: ["feelings"],
    trap: "in A good mood, עם a. 'I'm not in the mood' = לא בא לי. לא 'I have a good mood'.",
    colloc: { frame: "I'm not ___ the mood for a party tonight.", answer: "in", options: ["in", "on", "at"], whyHe: "in the mood (for) = מתחשק לי." },
  },
  {
    id: "v-pp-personality",
    word: "personality",
    pos: "n",
    he: "אישיות",
    def: "the type of person you are, shown by the way you behave and feel",
    examples: ["She has a warm, friendly personality.", "Their personalities are completely different."],
    cloze: "He's not handsome, but he has a great ___.",
    collocations: ["a strong personality", "a great personality", "personality clash"],
    band: 2,
    tags: ["people"],
    trap: "personality = אישיות. character = אופי (בעיקר מוסרי). 'He has personality' בלי תואר = כריזמטי.",
  },
  {
    id: "v-pp-sense-of-humor",
    word: "sense of humor",
    pos: "n",
    he: "חוש הומור",
    def: "the ability to enjoy and make jokes",
    examples: ["I love his sense of humor.", "You need a sense of humor to work here."],
    cloze: "She has a great ___, she makes everyone laugh.",
    collocations: ["a good sense of humor", "a dry sense of humor", "have a sense of humor"],
    band: 2,
    tags: ["people"],
    trap: "sense OF humor, לא 'sense humor'. אמריקאי: humor, בריטי: humour.",
    accept: ["sense of humour"],
  },
  {
    id: "v-pp-temper",
    word: "temper",
    pos: "n",
    he: "מזג (נטייה לכעוס)",
    def: "a tendency to become angry quickly",
    examples: ["Be careful, he has a terrible temper.", "She needs to control her temper."],
    cloze: "My grandfather had a short ___ and shouted a lot.",
    collocations: ["a bad temper", "a short temper", "control your temper"],
    band: 3,
    tags: ["people", "feelings"],
    trap: "temper ≠ temperature. 'has a temper' = כעסן. 'in a temper' = בהתקף כעס.",
    colloc: { frame: "He has a really ___ temper, so don't provoke him.", answer: "short", options: ["short", "small", "fast"], whyHe: "short temper = כעסן, מתפוצץ מהר." },
  },
  {
    id: "v-pp-gossip",
    word: "gossip",
    pos: "n",
    he: "רכילות",
    def: "talk about other people's private lives, often not kind",
    examples: ["I don't listen to office gossip.", "Have you heard the latest gossip about Sara?"],
    cloze: "She loves ___, she knows everything about everyone.",
    collocations: ["spread gossip", "office gossip", "a piece of gossip"],
    band: 2,
    tags: ["people", "relationships"],
    trap: "gossip הוא לא ספיר: 'some gossip', לא 'a gossip' (a gossip = רכלן). לרכל = to gossip (פועל).",
  },
  {
    id: "v-pp-compliment",
    word: "compliment",
    pos: "n",
    he: "מחמאה",
    def: "something nice you say to someone about their appearance or work",
    examples: ["She paid me a nice compliment on my presentation.", "Take it as a compliment!"],
    cloze: "He gave me a lovely ___ about my new haircut.",
    collocations: ["pay someone a compliment", "take something as a compliment", "return the compliment"],
    band: 2,
    tags: ["people"],
    trap: "אומרים pay / give a compliment, לא 'make a compliment'. compliment (מחמאה) ≠ complement (משלים).",
    colloc: { frame: "He ___ her a compliment on her cooking.", answer: "paid", options: ["paid", "made", "said"], whyHe: "pay someone a compliment = לתת מחמאה." },
  },
  {
    id: "v-pp-apology",
    word: "apology",
    pos: "n",
    he: "התנצלות",
    def: "the words you say when you are sorry for something",
    examples: ["I owe you an apology.", "He accepted my apology and we moved on."],
    cloze: "She sent him a long message with a sincere ___.",
    collocations: ["owe someone an apology", "accept an apology", "a sincere apology"],
    band: 2,
    tags: ["relationships"],
    trap: "אני חייב לך התנצלות = I OWE you an apology. לא 'make an apology' בדיבור, אלא apologize.",
    colloc: { frame: "I ___ you an apology for what I said yesterday.", answer: "owe", options: ["owe", "give", "have"], whyHe: "owe someone an apology = חייב התנצלות." },
  },
  {
    id: "v-pp-relationship",
    word: "relationship",
    pos: "n",
    he: "מערכת יחסים, קשר",
    def: "the way two people or groups feel about and behave toward each other",
    examples: ["They've been in a relationship for two years.", "I have a good relationship with my parents."],
    cloze: "She's not ready for a serious ___ right now.",
    collocations: ["be in a relationship", "a close relationship with", "a long-distance relationship"],
    band: 1,
    tags: ["relationships"],
    trap: "relationship WITH someone. 'be in a relationship' = להיות בזוגיות. לא 'relation' (זה יחס בין דברים).",
  },
  {
    id: "v-pp-attitude",
    word: "attitude",
    pos: "n",
    he: "גישה, יחס",
    def: "the way you think and feel about something, shown in how you behave",
    examples: ["She has a positive attitude toward work.", "I don't like his attitude, he's so negative."],
    cloze: "With that ___, you'll never make friends here.",
    collocations: ["a positive/negative attitude", "attitude toward something", "have an attitude"],
    band: 3,
    tags: ["people"],
    trap: "attitude TOWARD something. 'have an attitude' (בלי תואר) = חצוף. יחס לאדם = the way he treats me, לא attitude.",
  },
  {
    id: "v-pp-behavior",
    word: "behavior",
    pos: "n",
    he: "התנהגות",
    def: "the way someone acts",
    examples: ["His behavior at dinner was embarrassing.", "The teacher praised the class for their good behavior."],
    cloze: "That kind of ___ is not acceptable in this house.",
    collocations: ["good/bad behavior", "childish behavior", "change your behavior"],
    band: 1,
    tags: ["people"],
    trap: "behavior לא ספיר: 'his behavior', לא 'behaviors'. אמריקאי: behavior, בריטי: behaviour.",
    accept: ["behaviour"],
  },
  {
    id: "v-pp-crush",
    word: "crush",
    pos: "n",
    he: "התאהבות, קראש",
    def: "a strong feeling of liking someone, often for a short time",
    examples: ["I had a huge crush on my English teacher.", "It's just a crush, it'll pass."],
    cloze: "Everyone knows you have a ___ on Ben. Just tell him!",
    collocations: ["have a crush on someone", "a secret crush", "my crush"],
    band: 3,
    tags: ["relationships", "feelings"],
    trap: "have a crush ON someone, לא 'in' או 'for'. crush גם = למעוך (פועל).",
    colloc: { frame: "She has a crush ___ the new guy in her class.", answer: "on", options: ["on", "in", "for"], whyHe: "crush ON someone, הביטוי הקבוע." },
  },
  {
    id: "v-pp-partner",
    word: "partner",
    pos: "n",
    he: "בן/בת זוג",
    def: "the person you live with or are in a romantic relationship with",
    examples: ["Bring your partner to the party.", "My partner and I are moving in together."],
    cloze: "Her ___ works nights, so they rarely eat dinner together.",
    collocations: ["my partner", "life partner", "business partner"],
    band: 1,
    tags: ["relationships"],
    trap: "partner = בן/בת זוג (גם לא נשואים), ניטרלי למגדר. לא 'my couple'. גם שותף עסקי.",
  },
  {
    id: "v-pp-spouse",
    word: "spouse",
    pos: "n",
    he: "בן/בת זוג (נשואים)",
    def: "your husband or wife",
    examples: ["Employees can bring their spouse to the event.", "Please write your spouse's name on the form."],
    cloze: "The invitation says guests may bring a ___.",
    collocations: ["spouse and children", "your spouse's name"],
    band: 3,
    tags: ["relationships"],
    trap: "spouse = מילה רשמית (טפסים, חוקים). בדיבור אומרים husband / wife / partner.",
  },
  {
    id: "v-pp-only-child",
    word: "only child",
    pos: "n",
    he: "בן יחיד / בת יחידה",
    def: "a child who has no brothers or sisters",
    examples: ["I'm an only child, so I never had to share.", "Only children are often very close to their parents."],
    cloze: "She's an ___, and her parents spoil her.",
    collocations: ["be an only child", "grow up as an only child"],
    band: 2,
    tags: ["relationships", "people"],
    trap: "בן יחיד = an ONLY child, לא 'single child' ולא 'one child'.",
  },
  {
    id: "v-pp-self-esteem",
    word: "self-esteem",
    pos: "n",
    he: "הערכה עצמית",
    def: "the feeling that you are a good and valuable person",
    examples: ["Sports helped build her self-esteem.", "He has very low self-esteem."],
    cloze: "Constant criticism can damage a child's ___.",
    collocations: ["low/high self-esteem", "build self-esteem", "boost self-esteem"],
    band: 4,
    tags: ["feelings", "people"],
    trap: "self-esteem עם מקף, לא ספיר. low self-esteem = הערכה עצמית נמוכה, לא 'small'.",
    colloc: { frame: "The bullying left him with very ___ self-esteem.", answer: "low", options: ["low", "small", "weak"], whyHe: "self-esteem מתאר בגובה: low/high." },
  },
  {
    id: "v-pp-peer-pressure",
    word: "peer pressure",
    pos: "n",
    he: "לחץ חברתי",
    def: "pressure to do what people your own age are doing",
    examples: ["Many teens start smoking because of peer pressure.", "He gave in to peer pressure and skipped class."],
    cloze: "It's hard to say no to drugs when there's so much ___.",
    collocations: ["give in to peer pressure", "resist peer pressure"],
    band: 4,
    tags: ["people"],
    trap: "לחץ חברתי מבני הגיל = peer pressure. 'social pressure' זה כללי יותר. peer = בן/בת אותו גיל או מעמד.",
    colloc: { frame: "She ___ in to peer pressure and dyed her hair.", answer: "gave", options: ["gave", "went", "fell"], whyHe: "give in to = להיכנע ל-." },
  },
  {
    id: "v-pp-confidence",
    word: "confidence",
    pos: "n",
    he: "ביטחון עצמי",
    def: "the feeling that you can do things well and that people like you",
    examples: ["She spoke with a lot of confidence.", "Failing the test hurt his confidence."],
    cloze: "Learning to drive gave me a lot more ___.",
    collocations: ["gain/lose confidence", "self-confidence", "have confidence in someone"],
    band: 2,
    tags: ["feelings", "people"],
    trap: "ביטחון עצמי = confidence / self-confidence. 'security' = ביטחון פיזי או כלכלי, לא עצמי.",
  },
  {
    id: "v-pp-guilt",
    word: "guilt",
    pos: "n",
    he: "אשמה, רגשות אשם",
    def: "the bad feeling you have when you know you did something wrong",
    examples: ["He was full of guilt after lying to her.", "I still feel guilt about missing the funeral."],
    cloze: "She couldn't sleep because of the ___ she felt.",
    collocations: ["feel guilt", "a sense of guilt", "guilt trip"],
    band: 3,
    tags: ["feelings"],
    trap: "guilt = שם עצם. guilty = תואר: I feel guilty (לא 'I feel guilt' בדיבור). guilty ABOUT something.",
  },
  {
    id: "v-pp-ex",
    word: "ex",
    pos: "n",
    he: "אקס, בן/בת זוג לשעבר",
    def: "a former husband, wife, boyfriend, or girlfriend",
    examples: ["I ran into my ex at the supermarket.", "She's still friends with her ex."],
    cloze: "It was awkward, my ___ was at the party with his new girlfriend.",
    collocations: ["my ex", "ex-boyfriend", "ex-wife"],
    band: 3,
    tags: ["relationships"],
    trap: "ex לבד = בן/בת זוג לשעבר. עם מקף לפני מילה: ex-husband, ex-boss. לא 'former' בדיבור.",
  },

  // ---------------- adjectives ----------------
  
  {
    id: "v-pp-honest",
    word: "honest",
    pos: "adj",
    he: "כן, ישר",
    def: "always telling the truth and not cheating",
    examples: ["Be honest with me, did you like the food?", "He's an honest guy, he'd never steal."],
    cloze: "To be ___, I didn't enjoy the movie at all.",
    collocations: ["be honest with someone", "to be honest", "an honest answer"],
    band: 1,
    tags: ["people"],
    trap: "honest with someone. ה-h שקטה: AN honest man. ההפך: dishonest.",
    colloc: { frame: "Just be honest ___ me. What happened?", answer: "with", options: ["with", "to", "at"], whyHe: "honest WITH someone = כן כלפי מישהו." },
  },
  {
    id: "v-pp-stubborn",
    word: "stubborn",
    pos: "adj",
    he: "עקשן",
    def: "refusing to change your mind, even when others give good reasons",
    examples: ["He's too stubborn to admit he was wrong.", "My daughter is as stubborn as a mule."],
    cloze: "Don't be so ___. Just try the doctor's advice.",
    collocations: ["stubborn as a mule", "too stubborn to", "a stubborn child"],
    band: 2,
    tags: ["people"],
  },
  {
    id: "v-pp-easygoing",
    word: "easygoing",
    pos: "adj",
    he: "נינוח, זורם",
    def: "relaxed and not easily worried or annoyed",
    examples: ["My roommate is really easygoing.", "He's easygoing about money, he never argues about the bill."],
    cloze: "She's so ___ that nothing seems to bother her.",
    collocations: ["easygoing personality", "pretty easygoing"],
    band: 2,
    tags: ["people"],
    trap: "easygoing = רגוע ונוח. לא 'easy' לבד (easy person יכול להישמע לא מכבד).",
    accept: ["easy-going"],
  },
  {
    id: "v-pp-outgoing",
    word: "outgoing",
    pos: "adj",
    he: "חברותי, פתוח",
    def: "friendly and enjoying meeting and talking to new people",
    examples: ["She's very outgoing, she talks to everyone.", "He wasn't outgoing as a kid, but he changed."],
    cloze: "You need to be ___ to work in sales.",
    collocations: ["an outgoing personality", "outgoing and friendly"],
    band: 2,
    tags: ["people"],
    trap: "outgoing = חברותי ואוהב אנשים (כמו sociable). ההפך: shy או reserved. לא 'social' (זה חברתי, לא חברותי).",
  },
  {
    id: "v-pp-shy",
    word: "shy",
    pos: "adj",
    he: "ביישן",
    def: "nervous and quiet around other people",
    examples: ["He's too shy to speak in class.", "Don't be shy, come and say hello."],
    cloze: "She was so ___ that she hid behind her mother.",
    collocations: ["painfully shy", "too shy to", "shy around strangers"],
    band: 1,
    tags: ["people", "feelings"],
    trap: "shy AROUND/WITH people. אני מתבייש = I'm shy (אופי) או I'm embarrassed (רגע מסוים).",
  },
  {
    id: "v-pp-generous",
    word: "generous",
    pos: "adj",
    he: "נדיב",
    def: "happy to give money, time, or help to others",
    examples: ["It was generous of you to pay for everyone.", "She's generous with her time."],
    cloze: "My uncle is very ___. He always brings gifts.",
    collocations: ["generous with", "generous of you", "a generous gift"],
    band: 2,
    tags: ["people"],
    trap: "generous OF you to do... (מעשה) / generous WITH money (משאב). לא 'generous from you'.",
  },
  {
    id: "v-pp-mean",
    word: "mean",
    pos: "adj",
    he: "רע, מרושע",
    def: "unkind and cruel to other people",
    examples: ["Why are you being so mean to your sister?", "That was a mean thing to say."],
    cloze: "Some kids at school were really ___ to him.",
    collocations: ["mean to someone", "a mean comment", "be mean"],
    band: 2,
    tags: ["people"],
    trap: "mean כתואר = רע/מרושע: mean TO someone. אל תתבלבלו עם הפועל mean (להתכוון): I mean it.",
    colloc: { frame: "Stop being so mean ___ your little brother.", answer: "to", options: ["to", "with", "on"], whyHe: "mean TO someone = מתנהג רע כלפי." },
  },
  {
    id: "v-pp-selfish",
    word: "selfish",
    pos: "adj",
    he: "אנוכי",
    def: "caring only about yourself and not about other people",
    examples: ["It's selfish to take the last piece without asking.", "He's too selfish to be a good partner."],
    cloze: "Don't be ___, share the cake with everyone.",
    collocations: ["selfish behavior", "a selfish person"],
    band: 2,
    tags: ["people"],
    trap: "selfish = אנוכי. ההפך: selfless או generous. 'egoist' קיים באנגלית אבל נדיר, אומרים selfish.",
  },
  
  {
    id: "v-pp-moody",
    word: "moody",
    pos: "adj",
    he: "הפכפך במצבי הרוח",
    def: "often changing from happy to angry or sad for no clear reason",
    examples: ["Teenagers can be very moody.", "He's been moody all week, I don't know why."],
    cloze: "My boss is so ___, you never know what to expect.",
    collocations: ["moody teenager", "get moody"],
    band: 3,
    tags: ["people", "feelings"],
    trap: "moody = בעל מצבי רוח משתנים, לרוב שלילי. לא 'in a good mood' — זה mood (שם עצם).",
  },
  {
    id: "v-pp-patient",
    word: "patient",
    pos: "adj",
    he: "סבלני",
    def: "able to wait or deal with problems calmly, without getting angry",
    examples: ["Be patient, the food will be ready soon.", "She's very patient with the kids."],
    cloze: "You have to be ___ when you teach beginners.",
    collocations: ["patient with someone", "be patient", "patiently wait"],
    band: 2,
    tags: ["people"],
    trap: "patient (תואר) = סבלני; patient (שם עצם) = מטופל. סבלני עם = patient WITH. שם עצם: patience.",
    colloc: { frame: "Try to be patient ___ your grandmother, she's slow.", answer: "with", options: ["with", "to", "for"], whyHe: "patient WITH someone." },
  },
  {
    id: "v-pp-confident",
    word: "confident",
    pos: "adj",
    he: "בטוח בעצמו",
    def: "sure of yourself and your abilities",
    examples: ["She walked in looking calm and confident.", "I'm confident that we'll win."],
    cloze: "After a few lessons he felt more ___ speaking English.",
    collocations: ["confident about", "confident in yourself", "feel confident"],
    band: 2,
    tags: ["people", "feelings"],
    trap: "confident (בטוח בעצמו) ≠ confidential (סודי). confident ABOUT something / IN someone. לא 'sure in myself'.",
  },
  {
    id: "v-pp-insecure",
    word: "insecure",
    pos: "adj",
    he: "חסר ביטחון",
    def: "not confident about yourself or about how others see you",
    examples: ["He's insecure about his accent.", "Social media makes a lot of teens feel insecure."],
    cloze: "She's so ___ that she needs constant compliments.",
    collocations: ["insecure about", "feel insecure", "deeply insecure"],
    band: 3,
    tags: ["people", "feelings"],
    trap: "insecure = חסר ביטחון עצמי. לא 'unconfident' (נדיר). insecure ABOUT something. גם: לא בטוח (an insecure network).",
  },
  {
    id: "v-pp-annoyed",
    word: "annoyed",
    pos: "adj",
    he: "מעוצבן, מרוגז",
    def: "a little angry about something",
    examples: ["I was annoyed with him for being late again.", "She gets annoyed when people interrupt her."],
    cloze: "He was ___ that nobody answered his messages.",
    collocations: ["annoyed with someone", "annoyed about/at something", "get annoyed"],
    band: 2,
    tags: ["feelings"],
    trap: "annoyed WITH a person, annoyed ABOUT/AT a thing. לא 'annoyed on'. annoying = מעצבן (על הדבר).",
    colloc: { frame: "I'm really annoyed ___ my brother for taking my car.", answer: "with", options: ["with", "on", "from"], whyHe: "annoyed WITH someone. 'on' היא שגיאה מעברית." },
  },
  {
    id: "v-pp-upset",
    word: "upset",
    pos: "adj",
    he: "מוטרד, פגוע, עצוב",
    def: "unhappy or worried because something bad has happened",
    examples: ["She was really upset about losing her job.", "Don't be upset, we can fix it."],
    cloze: "He was very ___ when his dog died.",
    collocations: ["upset about something", "upset with someone", "get upset"],
    band: 2,
    tags: ["feelings"],
    trap: "upset = עצוב/נפגע/מודאג יחד. upset ABOUT something, upset WITH someone. הדגש: upSET.",
  },
  {
    id: "v-pp-disappointed",
    word: "disappointed",
    pos: "adj",
    he: "מאוכזב",
    def: "sad because something was not as good as you hoped",
    examples: ["I was disappointed with the hotel.", "Her parents were disappointed in her grades."],
    cloze: "We were so ___ that the concert was canceled.",
    collocations: ["disappointed with/in", "disappointed that", "bitterly disappointed"],
    band: 2,
    tags: ["feelings"],
    trap: "disappointed WITH / IN, לא 'disappointed FROM'. disappointing = מאכזב (על הדבר).",
    colloc: { frame: "I'm really disappointed ___ you. You promised.", answer: "in", options: ["in", "from", "of"], whyHe: "מאוכזב מאדם = disappointed IN someone." },
  },
  {
    id: "v-pp-embarrassed",
    word: "embarrassed",
    pos: "adj",
    he: "נבוך, מובך",
    def: "feeling shy or ashamed because of something that happened",
    examples: ["I was so embarrassed when I forgot his name.", "She felt embarrassed about her old car."],
    cloze: "He was too ___ to ask for help in front of everyone.",
    collocations: ["embarrassed about", "feel embarrassed", "embarrassed to admit"],
    band: 2,
    tags: ["feelings"],
    trap: "embarrassed = נבוך (מצב); embarrassing = מביך (על הדבר). לא 'I was embarrassing'. כתיב: שתי r, שתי s.",
    colloc: { frame: "That was the most ___ moment of my life.", answer: "embarrassing", options: ["embarrassing", "embarrassed", "embarrass"], whyHe: "רגע מביך = embarrassing. אני נבוך = embarrassed." },
  },
  {
    id: "v-pp-ashamed",
    word: "ashamed",
    pos: "adj",
    he: "מתבייש (במעשה)",
    def: "feeling bad about something wrong you did",
    examples: ["I'm ashamed of how I treated her.", "He was ashamed to admit he had lied."],
    cloze: "You should be ___ of yourself for lying to your mother.",
    collocations: ["ashamed of", "ashamed to admit", "feel ashamed"],
    band: 3,
    tags: ["feelings"],
    trap: "ashamed OF = בושה על מעשה רע. embarrassed = מבוכה. לא 'ashamed from'. אי אפשר 'an ashamed man' (רק אחרי be/feel).",
  },
  {
    id: "v-pp-proud",
    word: "proud",
    pos: "adj",
    he: "גאה",
    def: "feeling pleased about something you or someone close to you did",
    examples: ["I'm so proud of you!", "She's proud of her daughter's success."],
    cloze: "His parents were ___ of him for finishing college.",
    collocations: ["proud of", "proud to be", "make someone proud"],
    band: 1,
    tags: ["feelings"],
    trap: "proud OF someone, לא 'proud ON'. גאה ב- = proud OF. שם עצם: pride.",
    colloc: { frame: "We're all very proud ___ what you did.", answer: "of", options: ["of", "on", "in"], whyHe: "proud OF. 'proud on' היא שגיאה מעברית." },
  },
  {
    id: "v-pp-relieved",
    word: "relieved",
    pos: "adj",
    he: "חש הקלה",
    def: "happy because something you were worried about did not happen",
    examples: ["I was relieved to hear that everyone was safe.", "She felt relieved when the exam was over."],
    cloze: "We were so ___ when the doctor said it wasn't serious.",
    collocations: ["relieved to hear", "feel relieved", "relieved that"],
    band: 3,
    tags: ["feelings"],
    trap: "הוקל לי = I was relieved. שם עצם: relief (What a relief!). לא 'I felt relief' בדיבור, אלא relieved.",
  },
  
  {
    id: "v-pp-anxious",
    word: "anxious",
    pos: "adj",
    he: "חרד, מודאג",
    def: "very worried about something, sometimes for a long time",
    examples: ["She feels anxious in crowded places.", "I'm anxious about the test results."],
    cloze: "He gets ___ whenever he has to speak in public.",
    collocations: ["anxious about", "feel anxious", "anxious to do"],
    band: 3,
    tags: ["feelings"],
    trap: "anxious = חרד. חזק יותר מ-worried. שם עצם: anxiety. 'anxious to do' = משתוקק (משמעות אחרת).",
  },
  {
    id: "v-pp-frustrated",
    word: "frustrated",
    pos: "adj",
    he: "מתוסכל",
    def: "annoyed because you cannot do or get what you want",
    examples: ["I get frustrated when my computer is slow.", "She was frustrated with the lack of progress."],
    cloze: "He felt ___ because nobody listened to his ideas.",
    collocations: ["frustrated with/by", "get frustrated", "feel frustrated"],
    band: 3,
    tags: ["feelings"],
    trap: "frustrated WITH someone / BY something. frustrating = מתסכל (על הדבר). לא 'I'm frustrating'.",
  },
  
  {
    id: "v-pp-bored",
    word: "bored",
    pos: "adj",
    he: "משועמם",
    def: "tired and unhappy because nothing interesting is happening",
    examples: ["I'm bored, let's go somewhere.", "The kids got bored after ten minutes."],
    cloze: "I was so ___ during the lecture that I fell asleep.",
    collocations: ["bored with", "get bored", "bored to death"],
    band: 1,
    tags: ["feelings"],
    trap: "bored = משועמם (אני); boring = משעמם (הדבר). 'I am boring' = אני אדם משעמם! bored WITH, לא 'bored from'.",
    colloc: { frame: "I'm getting bored ___ this game. Let's play something else.", answer: "with", options: ["with", "from", "at"], whyHe: "bored WITH something. 'from' היא שגיאה מעברית." },
  },
  {
    id: "v-pp-boring",
    word: "boring",
    pos: "adj",
    he: "משעמם",
    def: "not interesting",
    examples: ["The movie was so boring that we left early.", "He's a nice guy but a bit boring."],
    cloze: "The lecture was really ___. Half the class fell asleep.",
    collocations: ["a boring job", "really boring", "boring and repetitive"],
    band: 1,
    tags: ["people", "feelings"],
    trap: "boring = משעמם (הדבר או האדם). bored = משועמם (הרגשה). אותו כלל: interesting/interested, tiring/tired.",
    colloc: { frame: "This show is so ___. Let's change the channel.", answer: "boring", options: ["boring", "bored", "bore"], whyHe: "התוכנית משעממת = boring; אני משועמם = bored." },
  },
  {
    id: "v-pp-jealous",
    word: "jealous",
    pos: "adj",
    he: "מקנא",
    def: "unhappy because someone has something you want, or because of a partner's attention to others",
    examples: ["He gets jealous when she talks to other men.", "I'm so jealous of your vacation!"],
    cloze: "She was ___ of her sister's success.",
    collocations: ["jealous of", "get jealous", "a jealous boyfriend"],
    band: 2,
    tags: ["feelings", "relationships"],
    trap: "jealous OF someone, לא 'jealous in'. שם עצם: jealousy. envious = מקנא ברכוש, בלי הרגש הזוגי.",
    colloc: { frame: "Don't be jealous ___ your friends' success. Be happy for them.", answer: "of", options: ["of", "in", "on"], whyHe: "jealous OF. 'jealous in' היא שגיאה מעברית." },
  },
  {
    id: "v-pp-grateful",
    word: "grateful",
    pos: "adj",
    he: "אסיר תודה",
    def: "feeling that you want to thank someone",
    examples: ["I'm grateful to you for all your help.", "We're grateful for the support we received."],
    cloze: "She was very ___ for the ride to the airport.",
    collocations: ["grateful to someone", "grateful for something", "deeply grateful"],
    band: 2,
    tags: ["feelings"],
    trap: "grateful TO a person FOR a thing. לא 'thankful' תמיד, ולא 'grateful with'. שם עצם: gratitude.",
    colloc: { frame: "I'm so grateful ___ you for being there.", answer: "to", options: ["to", "with", "at"], whyHe: "grateful TO someone (FOR something)." },
  },
  {
    id: "v-pp-rude",
    word: "rude",
    pos: "adj",
    he: "גס רוח, חצוף",
    def: "not polite; behaving in a way that upsets people",
    examples: ["It's rude to talk with your mouth full.", "The waiter was really rude to us."],
    cloze: "Don't be ___ to your grandmother. Say thank you.",
    collocations: ["rude to someone", "rude comment", "plain rude"],
    band: 1,
    tags: ["people"],
    trap: "rude TO someone, לא 'rude with'. חצוף = rude (או cheeky לילד). 'impolite' תקין אבל פחות נפוץ.",
    colloc: { frame: "He was very rude ___ the cashier.", answer: "to", options: ["to", "with", "against"], whyHe: "rude TO someone." },
  },
  {
    id: "v-pp-polite",
    word: "polite",
    pos: "adj",
    he: "מנומס",
    def: "behaving in a way that shows respect for other people",
    examples: ["Be polite to the guests.", "She's always polite, even when she's angry."],
    cloze: "It's ___ to say please and thank you.",
    collocations: ["polite to someone", "a polite smile", "politely ask"],
    band: 2,
    tags: ["people"],
    trap: "polite TO someone. תואר הפועל: politely. ההפך: impolite או rude.",
  },

  {
    id: "v-pp-angry",
    word: "angry",
    pos: "adj",
    he: "כועס",
    def: "feeling strong displeasure toward someone or something",
    examples: ["She was angry with me for forgetting her birthday.", "Why are you so angry about it?"],
    cloze: "Dad was really ___ when I came home at 3 a.m.",
    collocations: ["angry with/at someone", "angry about something", "get angry"],
    band: 1,
    tags: ["feelings"],
    trap: "angry WITH/AT a person, ABOUT a thing. לא 'angry ON him' — שגיאה נפוצה מעברית 'כועס על'.",
    colloc: { frame: "Are you still angry ___ me?", answer: "with", options: ["with", "on", "for"], whyHe: "angry WITH (או at) someone. לא 'on'." },
  },
  {
    id: "v-pp-loyal",
    word: "loyal",
    pos: "adj",
    he: "נאמן",
    def: "always supporting your friends, family, or group",
    examples: ["A dog is a loyal friend.", "She stayed loyal to him even when things got hard."],
    cloze: "He's a very ___ friend. He'd never talk behind your back.",
    collocations: ["loyal to", "a loyal friend", "fiercely loyal"],
    band: 2,
    tags: ["people", "relationships"],
    trap: "loyal TO someone. שם עצם: loyalty. faithful = נאמן בזוגיות בעיקר.",
  },
  {
    id: "v-pp-arrogant",
    word: "arrogant",
    pos: "adj",
    he: "יהיר, מתנשא",
    def: "believing you are better or more important than other people",
    examples: ["He's so arrogant, he never listens to anyone.", "She came across as arrogant in the interview."],
    cloze: "Success made him ___. He treats everyone like they're stupid.",
    collocations: ["arrogant attitude", "come across as arrogant"],
    band: 3,
    tags: ["people"],
    trap: "arrogant = יהיר. proud יכול להיות חיובי (גאה), arrogant תמיד שלילי. שם עצם: arrogance.",
  },
  {
    id: "v-pp-laid-back",
    word: "laid-back",
    pos: "adj",
    he: "רגוע, לא לחוץ",
    def: "relaxed and not worried about things",
    examples: ["Our teacher is pretty laid-back about deadlines.", "He's so laid-back that nothing stresses him."],
    cloze: "I like working with him, he's really ___ and calm.",
    collocations: ["a laid-back attitude", "laid-back about", "pretty laid-back"],
    band: 4,
    tags: ["people"],
    trap: "laid-back עם מקף, קרוב ל-easygoing. מדוברת, לא רשמית. אל תבלבלו עם 'lay back' (לשכב אחורה).",
  },
  {
    id: "v-pp-self-conscious",
    word: "self-conscious",
    pos: "adj",
    he: "נבוך ממראהו, מודע לעצמו",
    def: "worried about what other people think of how you look or act",
    examples: ["I feel self-conscious about my accent.", "Teenagers are often self-conscious about their bodies."],
    cloze: "She's very ___ about the scar on her face.",
    collocations: ["self-conscious about", "feel self-conscious"],
    band: 4,
    tags: ["feelings", "people"],
    trap: "self-conscious = לא נוח ממראה או התנהגות שלך מול אחרים. לא 'conscious' לבד (בהכרה). self-conscious ABOUT.",
  },
  
  {
    id: "v-pp-furious",
    word: "furious",
    pos: "adj",
    he: "זועם",
    def: "extremely angry",
    examples: ["My mom was furious when she saw my grades.", "He was furious with the airline for losing his bag."],
    cloze: "She was ___ that they had lied to her.",
    collocations: ["furious with/at someone", "furious about", "absolutely furious"],
    band: 3,
    tags: ["feelings"],
    trap: "furious = כועס מאוד. לא 'very furious' (זה כבר קיצוני) אלא absolutely furious. furious WITH someone.",
  },
];
