import type { VocabItem } from "@/lib/types";

// The most frequent spoken-English phrasal verbs (B1 -> B2), each in its most common meaning.
// Cloze sentences blank ONLY the whole phrasal verb; clozeAnswer holds the inflected form.
export const PHRASAL_VERBS: VocabItem[] = [
  // ---------- get ----------
  {
    id: "v-pv-get-up",
    word: "get up",
    pos: "phr",
    he: "לקום (מהמיטה)",
    def: "to leave your bed after sleeping",
    examples: ["I get up at seven every day.", "She got up late and missed the bus."],
    cloze: "On weekends I ___ around nine.",
    clozeAnswer: "get up",
    collocations: ["get up early", "get up late"],
    band: 1,
    tags: ["phrasal"],
    trap: "get up = לקום מהמיטה; wake up = להתעורר. אפשר להתעורר בשש ולקום בשבע.",
  },
  {
    id: "v-pv-get-on",
    word: "get on",
    pos: "phr",
    he: "לעלות על (אוטובוס, רכבת)",
    def: "to go onto a bus, train, or plane (the opposite is get off)",
    examples: ["Get on the bus at the next stop.", "We got off the train at the central station."],
    cloze: "Hurry, ___ the bus before it leaves!",
    clozeAnswer: "get on",
    collocations: ["get on the bus", "get on a plane", "get off the train"],
    band: 1,
    tags: ["phrasal"],
    trap: "אוטובוס/רכבת/מטוס: get on / get off. מכונית או מונית: get in / get out.",
    colloc: { frame: "She got ___ the train at the last minute.", answer: "on", options: ["on", "in", "up"], whyHe: "לרכבת עולים get on; למכונית נכנסים get in." },
  },
  {
    id: "v-pv-get-along",
    word: "get along",
    pos: "phr",
    he: "להסתדר (עם מישהו)",
    def: "to have a friendly relationship with someone",
    examples: ["I get along really well with my sister.", "Do you get along with your boss?"],
    cloze: "My kids don't ___ with each other.",
    clozeAnswer: "get along",
    collocations: ["get along with someone", "get along well"],
    band: 2,
    tags: ["phrasal"],
    trap: "get along WITH someone. הגרסה הבריטית: get on with.",
    accept: ["get on"],
    colloc: { frame: "Do you get ___ with your coworkers?", answer: "along", options: ["along", "over", "through"], whyHe: "להסתדר עם מישהו = get along with." },
  },
  {
    id: "v-pv-get-over",
    word: "get over",
    pos: "phr",
    he: "להתגבר על",
    def: "to feel better after an illness, a breakup, or a bad experience",
    examples: ["It took her months to get over the breakup.", "I still haven't gotten over that cold."],
    cloze: "He can't ___ the fact that he lost.",
    clozeAnswer: "get over",
    collocations: ["get over a cold", "get over a breakup", "get over it"],
    band: 2,
    tags: ["phrasal"],
    trap: "get over something, בלי מילת יחס נוספת: get over it, לא get over of it.",
  },
  {
    id: "v-pv-get-back",
    word: "get back",
    pos: "phr",
    he: "לחזור",
    def: "to return to a place, usually home",
    examples: ["What time did you get back last night?", "I'll call you when I get back from the trip."],
    cloze: "We ___ home after midnight.",
    clozeAnswer: "got back",
    collocations: ["get back home", "get back from work", "get back to someone"],
    band: 2,
    tags: ["phrasal"],
    trap: "get back = לחזור; get something back = לקבל בחזרה (I got my money back); get back to you = לחזור אליך עם תשובה.",
  },
  {
    id: "v-pv-get-rid-of",
    word: "get rid of",
    pos: "phr",
    he: "להיפטר מ",
    def: "to throw away or remove something you do not want",
    examples: ["We should get rid of these old chairs.", "I can't get rid of this cough."],
    cloze: "It's time to ___ all this junk.",
    clozeAnswer: "get rid of",
    collocations: ["get rid of junk", "get rid of a problem"],
    band: 2,
    tags: ["phrasal"],
    trap: "תמיד עם of: get rid of it, לא get rid it או get rid from it.",
  },
  {
    id: "v-pv-get-through",
    word: "get through",
    pos: "phr",
    he: "לעבור, לשרוד (תקופה)",
    def: "to manage to finish or survive something difficult",
    examples: ["I don't know how I got through that week.", "We'll get through this together."],
    cloze: "Coffee is the only thing that helps me ___ the day.",
    clozeAnswer: "get through",
    collocations: ["get through the day", "get through a hard time"],
    band: 3,
    tags: ["phrasal"],
    trap: "get through = לעבור בשלום תקופה או משימה; get through to someone = להשיג בטלפון / לגרום לו להבין.",
  },
  // ---------- give ----------
  {
    id: "v-pv-give-up",
    word: "give up",
    pos: "phr",
    he: "לוותר, להפסיק",
    def: "to stop trying, or to stop doing something you used to do",
    examples: ["Don't give up, you're almost there.", "He gave up smoking last year."],
    cloze: "She ___ trying to fix the printer.",
    clozeAnswer: "gave up",
    collocations: ["give up smoking", "give up on someone", "never give up"],
    band: 1,
    tags: ["phrasal"],
    trap: "give up + -ing: gave up smoking, לא gave up to smoke.",
    colloc: { frame: "He gave ___ smoking two years ago.", answer: "up", options: ["up", "out", "off"], whyHe: "להפסיק הרגל = give up." },
  },
  {
    id: "v-pv-give-back",
    word: "give back",
    pos: "phr",
    he: "להחזיר (משהו שלקחת)",
    def: "to return something to the person you took it from",
    examples: ["Can you give me back my pen?", "She gave the book back to the library."],
    cloze: "I'll ___ the money next week.",
    clozeAnswer: "give back",
    collocations: ["give it back", "give back the money"],
    band: 1,
    tags: ["phrasal"],
    trap: "פועל נפרד: give it back, לא give back it.",
  },
  {
    id: "v-pv-give-in",
    word: "give in",
    pos: "phr",
    he: "להיכנע, לוותר ללחץ",
    def: "to stop fighting or arguing and agree to what someone wants",
    examples: ["The kids begged until Dad gave in.", "Don't give in to pressure from your friends."],
    cloze: "After an hour of arguing, he finally ___.",
    clozeAnswer: "gave in",
    collocations: ["give in to pressure", "finally give in"],
    band: 4,
    tags: ["phrasal"],
    trap: "give in = להיכנע לדרישה; give up = להפסיק לנסות. עם מושא: give in TO something.",
  },
  // ---------- go ----------
  {
    id: "v-pv-go-on",
    word: "go on",
    pos: "phr",
    he: "להמשיך; לקרות",
    def: "to continue; also, to happen",
    examples: ["Please go on, I'm listening.", "What's going on here?"],
    cloze: "Sorry I interrupted, please ___.",
    clozeAnswer: "go on",
    collocations: ["go on talking", "what's going on"],
    band: 1,
    tags: ["phrasal"],
    trap: "go on + -ing: went on talking. What's going on? = מה קורה פה?",
    accept: ["carry on"],
    colloc: { frame: "What's going ___ in there?", answer: "on", options: ["on", "up", "out"], whyHe: "מה קורה = what's going on." },
  },
  {
    id: "v-pv-go-out",
    word: "go out",
    pos: "phr",
    he: "לצאת (לבלות)",
    def: "to leave home to do something fun, like a restaurant or a party",
    examples: ["Let's go out for dinner tonight.", "They've been going out for two years."],
    cloze: "We don't ___ much since the baby was born.",
    clozeAnswer: "go out",
    collocations: ["go out for dinner", "go out with friends", "go out with someone"],
    band: 1,
    tags: ["phrasal"],
    trap: "go out with someone = לצאת עם מישהו (רומנטית). בילוי עם חברים בלי רומנטיקה: hang out.",
  },
  {
    id: "v-pv-go-through",
    word: "go through",
    pos: "phr",
    he: "לעבור (חוויה); לעבור על",
    def: "to experience something difficult; also, to check something carefully",
    examples: ["She's going through a hard time right now.", "Let's go through the plan one more time."],
    cloze: "He ___ a lot after the accident.",
    clozeAnswer: "went through",
    collocations: ["go through a hard time", "go through the details"],
    band: 2,
    tags: ["phrasal"],
    trap: "go through something — לא נפרד: go through the list, לא go the list through.",
  },
  {
    id: "v-pv-go-ahead",
    word: "go ahead",
    pos: "phr",
    he: "קדימה, בבקשה; להתקדם",
    def: "to start or continue doing something, often after asking permission",
    examples: ["Go ahead, ask your question.", "They decided to go ahead with the project."],
    cloze: "Can I use your phone? Sure, ___.",
    clozeAnswer: "go ahead",
    collocations: ["go ahead with a plan", "go ahead and do it"],
    band: 2,
    tags: ["phrasal"],
    trap: "כתשובה לבקשה: Go ahead = בבקשה, קדימה. להמשיך עם תוכנית: go ahead WITH it.",
  },
  // ---------- come ----------
  {
    id: "v-pv-come-up",
    word: "come up",
    pos: "phr",
    he: "לעלות (נושא); לצוץ",
    def: "to be mentioned; also, to happen unexpectedly",
    examples: ["Your name came up in the meeting.", "Something came up, so I can't make it tonight."],
    cloze: "Sorry I'm late, something ___ at work.",
    clozeAnswer: "came up",
    collocations: ["something came up", "the topic came up"],
    band: 2,
    tags: ["phrasal"],
    trap: "Something came up = צץ משהו (תירוץ מנומס). לא נפרד.",
    colloc: { frame: "The subject came ___ at dinner.", answer: "up", options: ["up", "out", "over"], whyHe: "נושא שעולה בשיחה = comes up." },
  },
  {
    id: "v-pv-come-up-with",
    word: "come up with",
    pos: "phr",
    he: "להמציא, להעלות (רעיון)",
    def: "to think of an idea, a plan, or an answer",
    examples: ["She came up with a great idea.", "We need to come up with a plan by Friday."],
    cloze: "Who ___ the name for the app?",
    clozeAnswer: "came up with",
    collocations: ["come up with an idea", "come up with a solution"],
    band: 2,
    tags: ["phrasal"],
    trap: "'להעלות רעיון' = come up with an idea, לא raise an idea / think an idea.",
  },
  {
    id: "v-pv-come-across",
    word: "come across",
    pos: "phr",
    he: "להיתקל ב (במקרה)",
    def: "to find something or meet someone by chance",
    examples: ["I came across an old photo of us.", "Have you ever come across this word?"],
    cloze: "I ___ this recipe online yesterday.",
    clozeAnswer: "came across",
    collocations: ["come across a word", "come across a photo"],
    band: 3,
    tags: ["phrasal"],
    trap: "come across = למצוא במקרה (חפץ, מילה); לפגוש אדם במקרה: run into.",
  },
  {
    id: "v-pv-come-back",
    word: "come back",
    pos: "phr",
    he: "לחזור",
    def: "to return to the place where the speaker is",
    examples: ["Come back soon!", "He came back from Japan last week."],
    cloze: "When do you ___ from vacation?",
    clozeAnswer: "come back",
    collocations: ["come back home", "come back later"],
    band: 1,
    tags: ["phrasal"],
    trap: "come back = לחזור לכאן (אל הדובר); go back = לחזור לשם.",
  },
  // ---------- look ----------
  {
    id: "v-pv-look-for",
    word: "look for",
    pos: "phr",
    he: "לחפש",
    def: "to try to find something or someone",
    examples: ["I'm looking for my keys.", "They're looking for a new apartment."],
    cloze: "What are you ___?",
    clozeAnswer: "looking for",
    collocations: ["look for a job", "look for the keys"],
    band: 1,
    tags: ["phrasal"],
    trap: "בעברית 'מחפש את', באנגלית look for (בלי at). לא לבלבל עם look after (לטפל).",
    accept: ["search for"],
    colloc: { frame: "I'm looking ___ a cheap flight to Rome.", answer: "for", options: ["for", "after", "up"], whyHe: "לחפש = look for." },
  },
  {
    id: "v-pv-look-after",
    word: "look after",
    pos: "phr",
    he: "לטפל ב, לשמור על",
    def: "to take care of a person, an animal, or a thing",
    examples: ["Can you look after the kids tonight?", "She looks after her elderly mother."],
    cloze: "Who will ___ the dog while you're away?",
    clozeAnswer: "look after",
    collocations: ["look after the kids", "look after yourself"],
    band: 1,
    tags: ["phrasal"],
    trap: "look after = לטפל; look for = לחפש. לא נפרד: look after him, לא look him after.",
    accept: ["take care of"],
    colloc: { frame: "Who's going to look ___ the baby?", answer: "after", options: ["after", "for", "at"], whyHe: "לטפל = look after." },
  },
  {
    id: "v-pv-look-forward-to",
    word: "look forward to",
    pos: "phr",
    he: "לצפות ל (בשמחה)",
    def: "to feel happy about something that is going to happen",
    examples: ["I'm looking forward to the weekend.", "We look forward to hearing from you."],
    cloze: "I'm really ___ seeing you again.",
    clozeAnswer: "looking forward to",
    collocations: ["look forward to the weekend", "look forward to seeing you"],
    band: 2,
    tags: ["phrasal"],
    trap: "look forward to + -ing: looking forward to seeing you, לא to see you. ה-to כאן היא מילת יחס.",
  },
  {
    id: "v-pv-look-up",
    word: "look up",
    pos: "phr",
    he: "לחפש (במילון, באינטרנט)",
    def: "to find information in a dictionary, a list, or online",
    examples: ["Look it up in the dictionary.", "I looked up the address online."],
    cloze: "I ___ the opening hours on their website.",
    clozeAnswer: "looked up",
    collocations: ["look up a word", "look it up"],
    band: 1,
    tags: ["phrasal"],
    trap: "פועל נפרד: look it up, לא look up it. look for = לחפש חפץ; look up = לחפש מידע.",
  },
  {
    id: "v-pv-look-into",
    word: "look into",
    pos: "phr",
    he: "לבדוק, לחקור",
    def: "to examine a problem or a situation to find out more",
    examples: ["The police are looking into the case.", "I'll look into it and get back to you."],
    cloze: "We're ___ several options for the new office.",
    clozeAnswer: "looking into",
    collocations: ["look into a problem", "look into it"],
    band: 3,
    tags: ["phrasal"],
    trap: "I'll look into it = אני אבדוק את זה (משפט מפתח בעבודה). לא נפרד.",
  },
  {
    id: "v-pv-look-out",
    word: "look out",
    pos: "phr",
    he: "להיזהר",
    def: "used to warn someone about danger",
    examples: ["Look out! There's a car coming.", "Look out for icy roads tonight."],
    cloze: "Hey, ___! That step is broken.",
    clozeAnswer: "look out",
    collocations: ["look out for something"],
    band: 2,
    tags: ["phrasal"],
    trap: "Look out! / Watch out! = זהירות! עם מושא: look out FOR cars.",
    accept: ["watch out"],
  },
  // ---------- put ----------
  {
    id: "v-pv-put-on",
    word: "put on",
    pos: "phr",
    he: "ללבוש, לשים (על הגוף)",
    def: "to cover part of your body with clothes, shoes, or makeup",
    examples: ["Put on your coat, it's cold.", "She put on some music and started cooking."],
    cloze: "Wait, let me ___ my shoes.",
    clozeAnswer: "put on",
    collocations: ["put on a coat", "put on makeup", "put on music"],
    band: 1,
    tags: ["phrasal"],
    trap: "put on = פעולת הלבישה; wear = ללבוש (המצב). פועל נפרד: put it on.",
  },
  {
    id: "v-pv-put-off",
    word: "put off",
    pos: "phr",
    he: "לדחות",
    def: "to delay something to a later time",
    examples: ["Don't put off your homework until Sunday.", "The meeting was put off until next week."],
    cloze: "Stop ___ the dentist appointment!",
    clozeAnswer: "putting off",
    collocations: ["put off a meeting", "put off doing something"],
    band: 2,
    tags: ["phrasal"],
    trap: "put off + -ing: put off calling him. מילה נרדפת פורמלית: postpone.",
    accept: ["postpone"],
  },
  {
    id: "v-pv-put-up-with",
    word: "put up with",
    pos: "phr",
    he: "לסבול (משהו לא נעים)",
    def: "to accept something unpleasant without complaining",
    examples: ["I can't put up with this noise anymore.", "How do you put up with him?"],
    cloze: "She won't ___ rude customers.",
    clozeAnswer: "put up with",
    collocations: ["put up with noise", "put up with someone"],
    band: 4,
    tags: ["phrasal"],
    trap: "'לסבול' במובן של להשלים עם = put up with, לא suffer. שלוש מילים, לא נפרד.",
    accept: ["tolerate"],
  },
  {
    id: "v-pv-put-away",
    word: "put away",
    pos: "phr",
    he: "לסדר במקום, להחזיר למקום",
    def: "to put something back in the place where it is kept",
    examples: ["Put away your toys before dinner.", "He put the dishes away."],
    cloze: "Please ___ your laptop, dinner's ready.",
    clozeAnswer: "put away",
    collocations: ["put away the dishes", "put away your phone"],
    band: 2,
    tags: ["phrasal"],
    trap: "put away = להחזיר למקום; put down = להניח. פועל נפרד: put it away.",
  },
  // ---------- take ----------
  {
    id: "v-pv-take-off",
    word: "take off",
    pos: "phr",
    he: "להמריא; להוריד (בגד)",
    def: "when a plane leaves the ground; also, to remove clothes",
    examples: ["The plane took off on time.", "Take off your shoes at the door."],
    cloze: "The flight ___ ten minutes late.",
    clozeAnswer: "took off",
    collocations: ["take off your shoes", "the plane takes off"],
    band: 1,
    tags: ["phrasal"],
    trap: "להוריד בגד = take off (נפרד: take it off), לא remove/take down.",
    colloc: { frame: "Please take ___ your hat inside.", answer: "off", options: ["off", "out", "down"], whyHe: "להוריד בגד = take off." },
  },
  {
    id: "v-pv-take-up",
    word: "take up",
    pos: "phr",
    he: "להתחיל (תחביב)",
    def: "to start a new hobby or activity",
    examples: ["I took up running last spring.", "She wants to take up the guitar."],
    cloze: "He ___ yoga after his back problems.",
    clozeAnswer: "took up",
    collocations: ["take up a hobby", "take up running"],
    band: 3,
    tags: ["phrasal"],
    trap: "take up גם = לתפוס מקום או זמן: It takes up too much space.",
  },
  {
    id: "v-pv-take-over",
    word: "take over",
    pos: "phr",
    he: "להשתלט על; לקחת אחריות",
    def: "to take control of something, or to do a job instead of someone else",
    examples: ["A big company took over the store.", "Can you take over while I'm on break?"],
    cloze: "She will ___ as manager in May.",
    clozeAnswer: "take over",
    collocations: ["take over a company", "take over from someone"],
    band: 3,
    tags: ["phrasal"],
    trap: "take over from someone = להחליף מישהו בתפקיד.",
  },
  {
    id: "v-pv-take-care-of",
    word: "take care of",
    pos: "phr",
    he: "לטפל ב, לדאוג ל",
    def: "to look after someone, or to deal with a task",
    examples: ["I'll take care of the tickets.", "Take care of yourself."],
    cloze: "Don't worry, I'll ___ everything.",
    clozeAnswer: "take care of",
    collocations: ["take care of the kids", "take care of a problem"],
    band: 2,
    tags: ["phrasal"],
    trap: "take care OF it, לא take care on it. I'll take care of it = אני אטפל בזה.",
    accept: ["look after"],
  },
  // ---------- turn ----------
  {
    id: "v-pv-turn-on",
    word: "turn on",
    pos: "phr",
    he: "להדליק",
    def: "to make a light or a machine start working (the opposite is turn off)",
    examples: ["Turn on the light, please.", "He turned off the TV and went to bed."],
    cloze: "It's dark in here, ___ the lamp.",
    clozeAnswer: "turn on",
    collocations: ["turn on the light", "turn on the TV", "turn off the phone"],
    band: 1,
    tags: ["phrasal"],
    trap: "בעברית 'לפתוח את האור', באנגלית turn on the light, לא open the light. ההפך: turn off. נפרד: turn it on.",
    accept: ["switch on"],
    colloc: { frame: "Can you turn ___ the air conditioning?", answer: "on", options: ["on", "in", "over"], whyHe: "להדליק = turn on." },
  },
  {
    id: "v-pv-turn-up",
    word: "turn up",
    pos: "phr",
    he: "להגביר (עוצמה, חום)",
    def: "to make something louder, hotter, or stronger",
    examples: ["Turn up the volume, I can't hear.", "Can you turn up the heat? It's cold."],
    cloze: "It's freezing, let's ___ the heating.",
    clozeAnswer: "turn up",
    collocations: ["turn up the volume", "turn up the music"],
    band: 2,
    tags: ["phrasal"],
    trap: "turn up גם = להופיע (He turned up late). ההפך של להגביר: turn down.",
  },
  {
    id: "v-pv-turn-down",
    word: "turn down",
    pos: "phr",
    he: "לדחות (הצעה); להנמיך",
    def: "to say no to an offer or a request; also, to make something quieter",
    examples: ["She turned down the job offer.", "Turn down the music, please."],
    cloze: "He ___ the offer because the salary was low.",
    clozeAnswer: "turned down",
    collocations: ["turn down an offer", "turn down the volume"],
    band: 2,
    tags: ["phrasal"],
    trap: "לדחות הצעה = turn down, לא reject בשיחה יומיומית. נפרד: turn it down.",
    colloc: { frame: "She turned ___ the offer.", answer: "down", options: ["down", "off", "out"], whyHe: "לדחות הצעה = turn down." },
  },
  {
    id: "v-pv-turn-out",
    word: "turn out",
    pos: "phr",
    he: "להתברר",
    def: "to happen or end in a particular way, often a surprising one",
    examples: ["It turned out that he was right.", "The party turned out great."],
    cloze: "The 'expert' ___ to be a fake.",
    clozeAnswer: "turned out",
    collocations: ["turn out to be", "it turned out that"],
    band: 2,
    tags: ["phrasal"],
    trap: "It turned out that... / He turned out to be... — לא turned out being.",
  },
  {
    id: "v-pv-turn-into",
    word: "turn into",
    pos: "phr",
    he: "להפוך ל",
    def: "to change and become something different",
    examples: ["The small shop turned into a big business.", "A nice chat turned into an argument."],
    cloze: "The rain ___ snow during the night.",
    clozeAnswer: "turned into",
    collocations: ["turn into a problem", "turn into an argument"],
    band: 2,
    tags: ["phrasal"],
    trap: "turn into + שם עצם: turned into a monster. אפשר גם become בלי into.",
  },
  // ---------- bring / pick / drop ----------
  {
    id: "v-pv-bring-up",
    word: "bring up",
    pos: "phr",
    he: "להעלות (נושא); לגדל",
    def: "to start talking about a subject; also, to raise a child",
    examples: ["Don't bring up politics at dinner.", "She was brought up by her grandmother."],
    cloze: "Why did you ___ my mistake in front of everyone?",
    clozeAnswer: "bring up",
    collocations: ["bring up a topic", "bring up children"],
    band: 2,
    tags: ["phrasal"],
    trap: "'להעלות נושא' = bring up a topic, לא raise up. נפרד: bring it up.",
    colloc: { frame: "He brought ___ the topic of money.", answer: "up", options: ["up", "in", "out"], whyHe: "להעלות נושא = bring up." },
  },
  {
    id: "v-pv-bring-back",
    word: "bring back",
    pos: "phr",
    he: "להחזיר; להביא בחזרה",
    def: "to return something, or to bring something with you when you return",
    examples: ["Bring back the car by six.", "This song brings back memories."],
    cloze: "Can you ___ some milk from the store?",
    clozeAnswer: "bring back",
    collocations: ["bring back memories", "bring it back"],
    band: 2,
    tags: ["phrasal"],
    trap: "bring back = להביא בחזרה לכאן; take back = להחזיר לחנות (לשם). נפרד: bring it back.",
  },
  {
    id: "v-pv-pick-up",
    word: "pick up",
    pos: "phr",
    he: "לאסוף; להרים",
    def: "to collect someone or something, or to lift something from a surface",
    examples: ["I'll pick you up at seven.", "She picked up the phone and said hello."],
    cloze: "Can you ___ the kids from school today?",
    clozeAnswer: "pick up",
    collocations: ["pick up the kids", "pick up the phone", "pick up a package"],
    band: 1,
    tags: ["phrasal"],
    trap: "פועל נפרד: pick it up / pick me up, לא pick up it.",
    colloc: { frame: "I'll pick you ___ at the station.", answer: "up", options: ["up", "out", "on"], whyHe: "לאסוף מישהו = pick up." },
  },
  {
    id: "v-pv-drop-off",
    word: "drop off",
    pos: "phr",
    he: "להוריד (מהרכב)",
    def: "to take someone or something to a place and leave them there",
    examples: ["I'll drop you off at the airport.", "She dropped off the package this morning."],
    cloze: "Can you ___ the kids on your way to work?",
    clozeAnswer: "drop off",
    collocations: ["drop off the kids", "drop me off"],
    band: 2,
    tags: ["phrasal"],
    trap: "drop off = להוריד; pick up = לאסוף. נפרד: drop me off, לא drop off me.",
  },
  {
    id: "v-pv-drop-out",
    word: "drop out",
    pos: "phr",
    he: "לנשור (מלימודים)",
    def: "to leave school or a course before you finish it",
    examples: ["He dropped out of college after a year.", "Half the runners dropped out before the finish."],
    cloze: "She ___ of school at sixteen.",
    clozeAnswer: "dropped out",
    collocations: ["drop out of school", "drop out of a race"],
    band: 3,
    tags: ["phrasal"],
    trap: "drop out OF school, לא drop out from. שם עצם: a dropout.",
  },
  {
    id: "v-pv-drop-by",
    word: "drop by",
    pos: "phr",
    he: "לקפוץ לביקור",
    def: "to visit someone for a short time, often without planning",
    examples: ["Drop by whenever you're in the area.", "I dropped by the office to say hi."],
    cloze: "Feel free to ___ this weekend.",
    clozeAnswer: "drop by",
    collocations: ["drop by the office", "drop by for coffee"],
    band: 3,
    tags: ["phrasal"],
    trap: "'לקפוץ לביקור' = drop by / stop by, לא jump to visit.",
    accept: ["stop by", "come by"],
  },
  // ---------- set / show / run ----------
  {
    id: "v-pv-set-up",
    word: "set up",
    pos: "phr",
    he: "להקים; להתקין",
    def: "to start a business or system, or to prepare equipment for use",
    examples: ["They set up a small company.", "Can you help me set up the printer?"],
    cloze: "It took an hour to ___ the new TV.",
    clozeAnswer: "set up",
    collocations: ["set up a company", "set up a meeting", "set up an account"],
    band: 2,
    tags: ["phrasal"],
    trap: "set up a meeting = לקבוע פגישה; set up an account = לפתוח חשבון. עבר: set up (ללא שינוי).",
    colloc: { frame: "We need to set ___ a meeting with the client.", answer: "up", options: ["up", "on", "off"], whyHe: "לקבוע פגישה = set up a meeting." },
  },
  {
    id: "v-pv-set-off",
    word: "set off",
    pos: "phr",
    he: "לצאת לדרך",
    def: "to start a journey",
    examples: ["We set off early to avoid traffic.", "They set off for the mountains at dawn."],
    cloze: "What time should we ___ tomorrow?",
    clozeAnswer: "set off",
    collocations: ["set off early", "set off for a place"],
    band: 3,
    tags: ["phrasal"],
    trap: "set off / set out = לצאת לדרך. set off גם = להפעיל אזעקה: set off the alarm.",
    accept: ["set out"],
  },
  {
    id: "v-pv-show-up",
    word: "show up",
    pos: "phr",
    he: "להופיע, להגיע",
    def: "to arrive at a place, often late or unexpectedly",
    examples: ["He showed up an hour late.", "Only ten people showed up to the party."],
    cloze: "She didn't ___ for the interview.",
    clozeAnswer: "show up",
    collocations: ["show up late", "show up for work"],
    band: 2,
    tags: ["phrasal"],
    trap: "show up = להגיע (בדיבור); לא show up = לא להופיע. לא נפרד.",
    accept: ["turn up"],
    colloc: { frame: "He never showed ___ to the meeting.", answer: "up", options: ["up", "on", "off"], whyHe: "להגיע/להופיע = show up." },
  },
  {
    id: "v-pv-show-off",
    word: "show off",
    pos: "phr",
    he: "להשוויץ",
    def: "to try to make people admire you or your things",
    examples: ["Stop showing off in front of the girls.", "He loves showing off his new car."],
    cloze: "She bought the car just to ___.",
    clozeAnswer: "show off",
    collocations: ["show off a new car", "stop showing off"],
    band: 3,
    tags: ["phrasal"],
    trap: "show off (בלי מושא) = להשוויץ; show something off = להציג בגאווה. שם עצם: a show-off.",
  },
  {
    id: "v-pv-run-out-of",
    word: "run out of",
    pos: "phr",
    he: "להישאר בלי, להיגמר",
    def: "to have no more of something",
    examples: ["We ran out of milk.", "I'm running out of time."],
    cloze: "We ___ gas in the middle of nowhere.",
    clozeAnswer: "ran out of",
    collocations: ["run out of time", "run out of money", "run out of milk"],
    band: 2,
    tags: ["phrasal"],
    trap: "בעברית 'נגמר לי החלב', באנגלית אני הנושא: I ran out of milk. גם: The milk ran out.",
    colloc: { frame: "We've run ___ of coffee again.", answer: "out", options: ["out", "off", "down"], whyHe: "נגמר = run out of." },
  },
  {
    id: "v-pv-run-into",
    word: "run into",
    pos: "phr",
    he: "להיתקל ב, לפגוש במקרה",
    def: "to meet someone by chance; also, to have a problem unexpectedly",
    examples: ["I ran into my old teacher at the mall.", "We ran into some problems with the software."],
    cloze: "Guess who I ___ at the gym today?",
    clozeAnswer: "ran into",
    collocations: ["run into a friend", "run into problems"],
    band: 2,
    tags: ["phrasal"],
    trap: "run into someone = לפגוש במקרה, לא לרוץ לתוכו. לא נפרד.",
    accept: ["bump into"],
  },
  {
    id: "v-pv-run-away",
    word: "run away",
    pos: "phr",
    he: "לברוח",
    def: "to leave a place quickly to escape from someone or something",
    examples: ["The dog ran away from home.", "You can't run away from your problems."],
    cloze: "The thief ___ before the police came.",
    clozeAnswer: "ran away",
    collocations: ["run away from home", "run away from a problem"],
    band: 2,
    tags: ["phrasal"],
    trap: "run away FROM something, לא run away of.",
  },
  // ---------- break / call / carry ----------
  {
    id: "v-pv-break-down",
    word: "break down",
    pos: "phr",
    he: "להתקלקל; להישבר (רגשית)",
    def: "when a car or machine stops working; also, to start crying",
    examples: ["My car broke down on the highway.", "She broke down when she heard the news."],
    cloze: "The elevator ___ again this morning.",
    clozeAnswer: "broke down",
    collocations: ["the car broke down", "break down in tears"],
    band: 2,
    tags: ["phrasal"],
    trap: "מכונית שהתקלקלה broke down; מכשיר שהתקלקל = stopped working / is broken.",
    colloc: { frame: "The bus broke ___ halfway there.", answer: "down", options: ["down", "up", "off"], whyHe: "להתקלקל = break down." },
  },
  {
    id: "v-pv-break-up",
    word: "break up",
    pos: "phr",
    he: "להיפרד (מבן/בת זוג)",
    def: "to end a romantic relationship",
    examples: ["They broke up after five years.", "She broke up with him last night."],
    cloze: "Did you hear that Dan and Maya ___?",
    clozeAnswer: "broke up",
    collocations: ["break up with someone", "a breakup"],
    band: 2,
    tags: ["phrasal"],
    trap: "break up WITH someone, לא break up from. שם עצם: a breakup.",
    accept: ["split up"],
    colloc: { frame: "She broke ___ with her boyfriend.", answer: "up", options: ["up", "down", "out"], whyHe: "להיפרד = break up with." },
  },
  {
    id: "v-pv-break-into",
    word: "break into",
    pos: "phr",
    he: "לפרוץ ל",
    def: "to enter a building or a car by force, usually to steal",
    examples: ["Someone broke into our house last night.", "Thieves broke into the car and took the bag."],
    cloze: "The burglars ___ the store through the back door.",
    clozeAnswer: "broke into",
    collocations: ["break into a house", "break into a car"],
    band: 2,
    tags: ["phrasal"],
    trap: "עם מושא: break into a house. בלי מושא: break in (Someone broke in). שם עצם: a break-in.",
  },
  {
    id: "v-pv-call-off",
    word: "call off",
    pos: "phr",
    he: "לבטל",
    def: "to cancel something that was planned",
    examples: ["They called off the wedding.", "The game was called off because of rain."],
    cloze: "We had to ___ the trip at the last minute.",
    clozeAnswer: "call off",
    collocations: ["call off a meeting", "call off the wedding"],
    band: 2,
    tags: ["phrasal"],
    trap: "call off = cancel. נפרד: call it off. לא לבלבל עם call back.",
    accept: ["cancel"],
    colloc: { frame: "The concert was called ___ due to the storm.", answer: "off", options: ["off", "out", "down"], whyHe: "לבטל = call off." },
  },
  {
    id: "v-pv-call-back",
    word: "call back",
    pos: "phr",
    he: "להתקשר בחזרה",
    def: "to phone someone again, or to phone someone who phoned you",
    examples: ["Can you call me back in ten minutes?", "She never called back."],
    cloze: "I'm busy now, I'll ___ later.",
    clozeAnswer: "call back",
    collocations: ["call me back", "call back later"],
    band: 2,
    tags: ["phrasal"],
    trap: "call me back, לא call back to me או return me a call.",
  },
  {
    id: "v-pv-carry-on",
    word: "carry on",
    pos: "phr",
    he: "להמשיך",
    def: "to continue doing something",
    examples: ["Carry on with your work, don't mind me.", "She carried on talking as if nothing happened."],
    cloze: "Don't stop, just ___ with the exercise.",
    clozeAnswer: "carry on",
    collocations: ["carry on with", "carry on talking"],
    band: 2,
    tags: ["phrasal"],
    trap: "carry on + -ing או carry on WITH + שם עצם. שם עצם: carry-on = תיק יד למטוס.",
    accept: ["go on", "keep on"],
  },
  {
    id: "v-pv-carry-out",
    word: "carry out",
    pos: "phr",
    he: "לבצע",
    def: "to do a task, a plan, or an order",
    examples: ["The team carried out the plan perfectly.", "Doctors carried out tests on the patient."],
    cloze: "The police ___ a search of the building.",
    clozeAnswer: "carried out",
    collocations: ["carry out a plan", "carry out research", "carry out an order"],
    band: 4,
    tags: ["phrasal"],
    trap: "carry out a plan / a test / an order — קצת יותר פורמלי מ-do. נפרד: carry it out.",
  },
  // ---------- catch / check / cheer / clean / cut ----------
  {
    id: "v-pv-catch-up",
    word: "catch up",
    pos: "phr",
    he: "להדביק את הפער; להתעדכן",
    def: "to reach the same level as others; also, to talk about news with a friend",
    examples: ["Let's meet for coffee and catch up.", "I missed a week, so I have to catch up."],
    cloze: "You go ahead, I'll ___ with you in a minute.",
    clozeAnswer: "catch up",
    collocations: ["catch up with a friend", "catch up on work", "catch up on sleep"],
    band: 2,
    tags: ["phrasal"],
    trap: "catch up WITH מישהו, catch up ON עבודה/שינה. keep up with = לעמוד בקצב.",
  },
  {
    id: "v-pv-check-in",
    word: "check in",
    pos: "phr",
    he: "לעשות צ'ק-אין; להתעדכן",
    def: "to register at a hotel or airport; also, to contact someone to see how they are",
    examples: ["We need to check in two hours before the flight.", "I'll check in with you tomorrow to see how it's going."],
    cloze: "You can ___ at the hotel from 3 p.m.",
    clozeAnswer: "check in",
    collocations: ["check in at the hotel", "check in with someone"],
    band: 2,
    tags: ["phrasal"],
    trap: "check in AT a hotel; check in WITH someone = לבדוק מה שלומו. ההפך: check out.",
  },
  {
    id: "v-pv-check-out",
    word: "check out",
    pos: "phr",
    he: "לבדוק (משהו מעניין); לעשות צ'ק-אאוט",
    def: "to look at something interesting; also, to leave a hotel and pay",
    examples: ["Check out this video!", "We have to check out by noon."],
    cloze: "You should ___ that new cafe on Dizengoff.",
    clozeAnswer: "check out",
    collocations: ["check it out", "check out a place"],
    band: 1,
    tags: ["phrasal"],
    trap: "Check it out! = תראה את זה! נפרד: check it out, לא check out it.",
  },
  {
    id: "v-pv-cheer-up",
    word: "cheer up",
    pos: "phr",
    he: "להתעודד; לעודד",
    def: "to become happier, or to make someone happier",
    examples: ["Cheer up, it's not the end of the world.", "A funny movie always cheers me up."],
    cloze: "Come on, ___! We'll try again tomorrow.",
    clozeAnswer: "cheer up",
    collocations: ["cheer someone up", "cheer up!"],
    band: 2,
    tags: ["phrasal"],
    trap: "פועל נפרד: cheer him up, לא cheer up him. Cheer up! = תתעודד!",
  },
  {
    id: "v-pv-clean-up",
    word: "clean up",
    pos: "phr",
    he: "לנקות, לסדר",
    def: "to make a place clean and tidy",
    examples: ["Clean up your room before your friends come.", "We cleaned up after the party."],
    cloze: "Who's going to ___ this mess?",
    clozeAnswer: "clean up",
    collocations: ["clean up the kitchen", "clean up a mess"],
    band: 1,
    tags: ["phrasal"],
    trap: "clean up = לנקות ולסדר; clean = לנקות. נפרד: clean it up.",
    accept: ["tidy up"],
    colloc: { frame: "Let's clean ___ the kitchen before Mom gets home.", answer: "up", options: ["up", "on", "in"], whyHe: "לנקות ולסדר = clean up." },
  },
  {
    id: "v-pv-cut-down-on",
    word: "cut down on",
    pos: "phr",
    he: "להפחית, לצמצם",
    def: "to do or use less of something",
    examples: ["I'm trying to cut down on sugar.", "He cut down on his hours at work."],
    cloze: "The doctor told me to ___ coffee.",
    clozeAnswer: "cut down on",
    collocations: ["cut down on sugar", "cut down on spending"],
    band: 3,
    tags: ["phrasal"],
    trap: "cut down ON something = להפחית; cut out = להפסיק לגמרי.",
  },
  {
    id: "v-pv-cut-off",
    word: "cut off",
    pos: "phr",
    he: "לנתק",
    def: "to stop the supply of something, or to interrupt a phone call",
    examples: ["They cut off the electricity because we didn't pay.", "The call got cut off in the tunnel."],
    cloze: "Sorry, we got ___, can you repeat that?",
    clozeAnswer: "cut off",
    collocations: ["cut off the power", "get cut off"],
    band: 3,
    tags: ["phrasal"],
    trap: "נפרד: cut it off. גם: cut someone off = לקטוע מישהו באמצע דיבור.",
  },
  // ---------- deal / end / fall / figure / fill / find ----------
  {
    id: "v-pv-deal-with",
    word: "deal with",
    pos: "phr",
    he: "להתמודד עם, לטפל ב",
    def: "to take action to solve a problem or handle a situation",
    examples: ["I'll deal with the customer complaints.", "She's dealing with a lot right now."],
    cloze: "How do you ___ stress?",
    clozeAnswer: "deal with",
    collocations: ["deal with a problem", "deal with stress", "deal with customers"],
    band: 1,
    tags: ["phrasal"],
    trap: "deal WITH a problem, לא deal a problem או treat with. עבר: dealt with.",
    accept: ["handle"],
    colloc: { frame: "I can't deal ___ this right now.", answer: "with", options: ["with", "on", "of"], whyHe: "להתמודד עם = deal with." },
  },
  {
    id: "v-pv-end-up",
    word: "end up",
    pos: "phr",
    he: "לגמור (במצב מסוים), למצוא את עצמך",
    def: "to finally be in a place or situation you did not plan",
    examples: ["We ended up staying home all weekend.", "He ended up in the hospital."],
    cloze: "We got lost and ___ in the wrong city.",
    clozeAnswer: "ended up",
    collocations: ["end up doing", "end up in a place"],
    band: 3,
    tags: ["phrasal"],
    trap: "end up + -ing: ended up paying, לא ended up to pay. end up + מקום: ended up in Haifa.",
  },
  {
    id: "v-pv-fall-apart",
    word: "fall apart",
    pos: "phr",
    he: "להתפרק",
    def: "to break into pieces; also, when a plan or a life stops working",
    examples: ["The old chair is falling apart.", "After the divorce, his life fell apart."],
    cloze: "These cheap shoes ___ after a month.",
    clozeAnswer: "fell apart",
    collocations: ["fall apart", "a plan falls apart"],
    band: 3,
    tags: ["phrasal"],
    trap: "fall apart = להתפרק (חפץ, תוכנית, אדם). עבר: fell apart.",
  },
  {
    id: "v-pv-fall-behind",
    word: "fall behind",
    pos: "phr",
    he: "לפגר (בלוח זמנים, בלימודים)",
    def: "to become slower than others or later than planned",
    examples: ["He fell behind in math after being sick.", "We're falling behind schedule."],
    cloze: "If you miss classes, you'll ___ quickly.",
    clozeAnswer: "fall behind",
    collocations: ["fall behind schedule", "fall behind with payments", "fall behind in school"],
    band: 3,
    tags: ["phrasal"],
    trap: "fall behind IN school / WITH payments / ON rent. ההפך: catch up.",
  },
  {
    id: "v-pv-figure-out",
    word: "figure out",
    pos: "phr",
    he: "להבין, לפתור",
    def: "to understand something or find the answer after thinking about it",
    examples: ["I can't figure out how this works.", "We'll figure it out together."],
    cloze: "Did you ___ why the app keeps crashing?",
    clozeAnswer: "figure out",
    collocations: ["figure out how", "figure it out", "figure out a way"],
    band: 2,
    tags: ["phrasal"],
    trap: "נפרד: figure it out, לא figure out it. figure out = להבין אחרי מאמץ; understand = להבין.",
    colloc: { frame: "I finally figured ___ the password.", answer: "out", options: ["out", "up", "on"], whyHe: "לפתור/להבין = figure out." },
  },
  {
    id: "v-pv-fill-out",
    word: "fill out",
    pos: "phr",
    he: "למלא (טופס)",
    def: "to write information in the spaces on a form",
    examples: ["Please fill out this form.", "I filled out the application online."],
    cloze: "You need to ___ a form at the front desk.",
    clozeAnswer: "fill out",
    collocations: ["fill out a form", "fill out an application"],
    band: 1,
    tags: ["phrasal"],
    trap: "בארה\"ב fill out a form; בבריטניה fill in. fill in גם = למלא פרט אחד: fill in your name. נפרד: fill it out.",
    accept: ["fill in"],
  },
  {
    id: "v-pv-find-out",
    word: "find out",
    pos: "phr",
    he: "לגלות, לברר",
    def: "to learn information that you did not know before",
    examples: ["I found out she's moving to Haifa.", "Let me find out what time the store opens."],
    cloze: "How did you ___ about the party?",
    clozeAnswer: "find out",
    collocations: ["find out about", "find out what", "find out the truth"],
    band: 1,
    tags: ["phrasal"],
    trap: "find out = לגלות מידע; find = למצוא חפץ. 'לברר' = find out, לא know out או check out.",
    colloc: { frame: "I need to find ___ when the train leaves.", answer: "out", options: ["out", "up", "on"], whyHe: "לברר = find out." },
  },
  // ---------- hand / hang / hold ----------
  {
    id: "v-pv-hand-in",
    word: "hand in",
    pos: "phr",
    he: "להגיש (עבודה)",
    def: "to give a piece of work to a teacher or a boss",
    examples: ["Hand in your essays by Monday.", "She handed in her resignation."],
    cloze: "Did you ___ the report yet?",
    clozeAnswer: "hand in",
    collocations: ["hand in homework", "hand in a report"],
    band: 2,
    tags: ["phrasal"],
    trap: "hand in / turn in = להגיש. נפרד: hand it in. submit = פורמלי.",
    accept: ["turn in", "submit"],
  },
  {
    id: "v-pv-hang-out",
    word: "hang out",
    pos: "phr",
    he: "לבלות (עם חברים)",
    def: "to spend relaxed time with friends",
    examples: ["We just hung out at the mall.", "Want to hang out this weekend?"],
    cloze: "I usually ___ with friends on Fridays.",
    clozeAnswer: "hang out",
    collocations: ["hang out with friends", "hang out at home"],
    band: 1,
    tags: ["phrasal"],
    trap: "hang out with friends = לבלות בלי תוכנית מיוחדת; go out = לצאת לבלות בחוץ. עבר: hung out.",
  },
  {
    id: "v-pv-hang-up",
    word: "hang up",
    pos: "phr",
    he: "לנתק (שיחה)",
    def: "to end a phone call",
    examples: ["Don't hang up, I'm almost done.", "He hung up on me!"],
    cloze: "She got angry and ___ on me.",
    clozeAnswer: "hung up",
    collocations: ["hang up the phone", "hang up on someone"],
    band: 2,
    tags: ["phrasal"],
    trap: "hang up ON someone = לטרוק לו את הטלפון. עבר: hung up (לא hanged).",
  },
  {
    id: "v-pv-hold-on",
    word: "hold on",
    pos: "phr",
    he: "לחכות רגע",
    def: "to wait for a short time, especially on the phone",
    examples: ["Hold on, I'll get a pen.", "Hold on a second, let me check."],
    cloze: "Can you ___ for a minute? I have another call.",
    clozeAnswer: "hold on",
    collocations: ["hold on a second", "hold on a minute"],
    band: 2,
    tags: ["phrasal"],
    trap: "Hold on / Hang on = רגע, חכה. hold on TO something = להחזיק חזק.",
    accept: ["hang on"],
  },
  // ---------- keep / let / make / mess / move ----------
  {
    id: "v-pv-keep-up-with",
    word: "keep up with",
    pos: "phr",
    he: "לעמוד בקצב של",
    def: "to move or learn as fast as someone or something else",
    examples: ["I can't keep up with all these emails.", "Slow down, I can't keep up with you."],
    cloze: "It's hard to ___ the news these days.",
    clozeAnswer: "keep up with",
    collocations: ["keep up with the news", "keep up with the class"],
    band: 4,
    tags: ["phrasal"],
    trap: "keep up with = לעמוד בקצב (עכשיו); catch up with = להדביק פער (אחרי שנשארת מאחור).",
  },
  {
    id: "v-pv-keep-on",
    word: "keep on",
    pos: "phr",
    he: "להמשיך (לעשות)",
    def: "to continue doing something, often something annoying",
    examples: ["He kept on talking during the movie.", "If you keep on practicing, you'll improve."],
    cloze: "She ___ asking the same question.",
    clozeAnswer: "kept on",
    collocations: ["keep on trying", "keep on going"],
    band: 2,
    tags: ["phrasal"],
    trap: "keep on + -ing: keep on trying, לא keep on to try. גם keep + -ing בלי on.",
  },
  {
    id: "v-pv-let-down",
    word: "let down",
    pos: "phr",
    he: "לאכזב",
    def: "to disappoint someone who trusted you",
    examples: ["Don't let me down.", "She let her parents down by lying."],
    cloze: "I promised to help, and I won't ___ my team.",
    clozeAnswer: "let down",
    collocations: ["let someone down", "feel let down"],
    band: 2,
    tags: ["phrasal"],
    trap: "נפרד: let me down, לא let down me. עבר: let down (ללא שינוי). disappoint = פורמלי יותר.",
    accept: ["disappoint"],
  },
  {
    id: "v-pv-make-up",
    word: "make up",
    pos: "phr",
    he: "להמציא (סיפור); להשלים (אחרי ריב)",
    def: "to invent a story or an excuse; also, to become friends again after a fight",
    examples: ["He made up an excuse for being late.", "They fought, but they made up the next day."],
    cloze: "Did he really see a ghost, or did he ___ the whole story?",
    clozeAnswer: "make up",
    collocations: ["make up an excuse", "make up a story", "make up with someone"],
    band: 2,
    tags: ["phrasal"],
    trap: "make up a story = להמציא; make up WITH someone = להשלים; makeup (שם עצם) = איפור.",
  },
  {
    id: "v-pv-make-up-for",
    word: "make up for",
    pos: "phr",
    he: "לפצות על",
    def: "to do something good to balance something bad you did",
    examples: ["I'll make up for it, I promise.", "Nothing can make up for lost time."],
    cloze: "He bought her dinner to ___ forgetting her birthday.",
    clozeAnswer: "make up for",
    collocations: ["make up for lost time", "make up for a mistake"],
    band: 4,
    tags: ["phrasal"],
    trap: "make up FOR + שם עצם או -ing: make up for being late. 'לפצות' = make up for, לא compensate בדיבור.",
  },
  {
    id: "v-pv-mess-up",
    word: "mess up",
    pos: "phr",
    he: "לפשל, להרוס",
    def: "to do something badly or make something go wrong",
    examples: ["I really messed up the interview.", "Don't mess up my plans."],
    cloze: "I ___ the recipe and the cake was terrible.",
    clozeAnswer: "messed up",
    collocations: ["mess up an interview", "mess it up", "mess up a plan"],
    band: 3,
    tags: ["phrasal"],
    trap: "'פישלתי' = I messed up. נפרד: mess it up. messed up (תואר) = דפוק, לא בסדר.",
    accept: ["screw up"],
  },
  {
    id: "v-pv-move-on",
    word: "move on",
    pos: "phr",
    he: "להמשיך הלאה",
    def: "to go to the next thing, or to stop thinking about something from the past",
    examples: ["It's time to move on to the next question.", "She's finally moved on after the breakup."],
    cloze: "Let's ___ to the next topic.",
    clozeAnswer: "move on",
    collocations: ["move on to", "move on from the past"],
    band: 2,
    tags: ["phrasal"],
    trap: "move on TO the next point; move on FROM the past. move (בלי on) = לעבור דירה.",
  },
  // ---------- pass / pay / point / pull ----------
  {
    id: "v-pv-pass-out",
    word: "pass out",
    pos: "phr",
    he: "להתעלף",
    def: "to suddenly become unconscious",
    examples: ["It was so hot that she passed out.", "He passed out after two drinks."],
    cloze: "I almost ___ when I saw the blood.",
    clozeAnswer: "passed out",
    collocations: ["pass out from the heat", "almost pass out"],
    band: 3,
    tags: ["phrasal"],
    trap: "pass out = להתעלף (בדיבור); faint = אותו דבר, קצת יותר פורמלי. pass away = למות.",
    accept: ["faint"],
  },
  {
    id: "v-pv-pay-back",
    word: "pay back",
    pos: "phr",
    he: "להחזיר (כסף)",
    def: "to give someone the money you borrowed from them",
    examples: ["I'll pay you back on Friday.", "He never paid back the loan."],
    cloze: "It took years to ___ the loan.",
    clozeAnswer: "pay back",
    collocations: ["pay someone back", "pay back a loan"],
    band: 2,
    tags: ["phrasal"],
    trap: "נפרד: pay me back, לא pay back me. 'להחזיר כסף' = pay back, לא return money.",
  },
  {
    id: "v-pv-point-out",
    word: "point out",
    pos: "phr",
    he: "לציין, להצביע על",
    def: "to tell someone about something important that they may not have noticed",
    examples: ["She pointed out a mistake in my email.", "I should point out that we're over budget."],
    cloze: "Thanks for ___ the error before we sent it.",
    clozeAnswer: "pointing out",
    collocations: ["point out a mistake", "point out that"],
    band: 2,
    tags: ["phrasal"],
    trap: "point out = להעיר על משהו; point at = להצביע באצבע. נפרד: point it out.",
    colloc: { frame: "He pointed ___ that the shop closes early.", answer: "out", options: ["out", "on", "at"], whyHe: "לציין = point out." },
  },
  {
    id: "v-pv-pull-over",
    word: "pull over",
    pos: "phr",
    he: "לעצור בצד הדרך",
    def: "to drive to the side of the road and stop",
    examples: ["The police pulled him over for speeding.", "Pull over, I feel sick."],
    cloze: "Can you ___? I need to check the map.",
    clozeAnswer: "pull over",
    collocations: ["pull over to the side", "get pulled over"],
    band: 3,
    tags: ["phrasal"],
    trap: "pull over = לעצור בצד; the police pulled me over = המשטרה עצרה אותי.",
  },
  // ---------- rely / sort / speak / stand / stick ----------
  {
    id: "v-pv-rely-on",
    word: "rely on",
    pos: "phr",
    he: "לסמוך על",
    def: "to trust someone or something to do what you need",
    examples: ["You can rely on me.", "The town relies on tourism."],
    cloze: "Don't ___ your phone for everything.",
    clozeAnswer: "rely on",
    collocations: ["rely on someone", "rely on technology"],
    band: 2,
    tags: ["phrasal"],
    trap: "rely ON, לא rely at. trust בלי מילת יחס: I trust him.",
    accept: ["count on", "depend on"],
    colloc: { frame: "I can always rely ___ my brother.", answer: "on", options: ["on", "in", "at"], whyHe: "לסמוך על = rely on." },
  },
  {
    id: "v-pv-sort-out",
    word: "sort out",
    pos: "phr",
    he: "לסדר, לפתור",
    def: "to solve a problem or organize something",
    examples: ["I need to sort out my visa before the trip.", "Let's sort out this mess."],
    cloze: "Did you ___ the problem with the bank?",
    clozeAnswer: "sort out",
    collocations: ["sort out a problem", "sort it out"],
    band: 3,
    tags: ["phrasal"],
    trap: "sort out = לפתור/להסדיר (נפוץ מאוד בדיבור). נפרד: sort it out.",
  },
  {
    id: "v-pv-speak-up",
    word: "speak up",
    pos: "phr",
    he: "לדבר בקול רם יותר; להביע דעה",
    def: "to talk louder; also, to say what you think openly",
    examples: ["Can you speak up? I can't hear you.", "If you disagree, speak up."],
    cloze: "Please ___, the people in the back can't hear.",
    clozeAnswer: "speak up",
    collocations: ["speak up for yourself", "speak up louder"],
    band: 2,
    tags: ["phrasal"],
    trap: "speak up גם = להעז לומר את דעתך: speak up for yourself.",
  },
  {
    id: "v-pv-stand-out",
    word: "stand out",
    pos: "phr",
    he: "לבלוט",
    def: "to be easy to notice because you are different or better",
    examples: ["Her red dress really stood out.", "You need to stand out from the other candidates."],
    cloze: "His resume ___ because of his experience.",
    clozeAnswer: "stood out",
    collocations: ["stand out from the crowd", "really stand out"],
    band: 3,
    tags: ["phrasal"],
    trap: "stand out FROM the crowd. עבר: stood out. outstanding = מצוין.",
  },
  {
    id: "v-pv-stick-to",
    word: "stick to",
    pos: "phr",
    he: "לדבוק ב, להיצמד ל",
    def: "to continue with a plan, a diet, or a rule without changing",
    examples: ["Stick to the plan.", "I'm trying to stick to my diet."],
    cloze: "Let's ___ the topic, please.",
    clozeAnswer: "stick to",
    collocations: ["stick to the plan", "stick to a diet", "stick to the rules"],
    band: 3,
    tags: ["phrasal"],
    trap: "stick TO the plan (גם stick with). עבר: stuck to.",
    accept: ["stick with"],
  },
  // ---------- throw / try / wake / warm / work / wear ----------
  {
    id: "v-pv-throw-away",
    word: "throw away",
    pos: "phr",
    he: "לזרוק (לפח)",
    def: "to put something in the trash because you do not want it",
    examples: ["Throw away those old newspapers.", "Don't throw the receipt away."],
    cloze: "Should I ___ these old shoes?",
    clozeAnswer: "throw away",
    collocations: ["throw away the trash", "throw it away"],
    band: 1,
    tags: ["phrasal"],
    trap: "נפרד: throw it away, לא throw away it. גם throw out.",
    accept: ["throw out"],
  },
  {
    id: "v-pv-try-on",
    word: "try on",
    pos: "phr",
    he: "למדוד (בגד)",
    def: "to put on clothes to see if they fit",
    examples: ["Can I try on this jacket?", "She tried on five pairs of shoes."],
    cloze: "Can I ___ these jeans?",
    clozeAnswer: "try on",
    collocations: ["try on a dress", "try it on"],
    band: 1,
    tags: ["phrasal"],
    trap: "בעברית 'למדוד', באנגלית try on, לא measure. נפרד: try it on.",
  },
  {
    id: "v-pv-wake-up",
    word: "wake up",
    pos: "phr",
    he: "להתעורר; להעיר",
    def: "to stop sleeping, or to make someone stop sleeping",
    examples: ["I wake up at six.", "Wake me up at seven, please."],
    cloze: "I ___ late and missed the bus.",
    clozeAnswer: "woke up",
    collocations: ["wake up early", "wake someone up"],
    band: 1,
    tags: ["phrasal"],
    trap: "wake up = להתעורר; get up = לקום מהמיטה. עבר: woke up. נפרד: wake me up.",
  },
  {
    id: "v-pv-warm-up",
    word: "warm up",
    pos: "phr",
    he: "להתחמם; לחמם",
    def: "to do light exercise before sport; also, to make food or a room warmer",
    examples: ["Warm up before you run.", "I'll warm up the soup."],
    cloze: "The players ___ for twenty minutes before the game.",
    clozeAnswer: "warmed up",
    collocations: ["warm up before a game", "warm up food"],
    band: 3,
    tags: ["phrasal"],
    trap: "warm up food = לחמם אוכל (גם heat up). נפרד: warm it up.",
    accept: ["heat up"],
  },
  {
    id: "v-pv-work-out",
    word: "work out",
    pos: "phr",
    he: "להתאמן; להסתדר (בסוף)",
    def: "to exercise; also, to end in a good way",
    examples: ["I work out three times a week.", "Don't worry, it'll all work out."],
    cloze: "He ___ at the gym every morning.",
    clozeAnswer: "works out",
    collocations: ["work out at the gym", "it worked out", "work out a solution"],
    band: 2,
    tags: ["phrasal"],
    trap: "work out גם = להצליח: It didn't work out. שם עצם: a workout = אימון.",
    accept: ["exercise"],
    colloc: { frame: "Things didn't work ___ between them.", answer: "out", options: ["out", "up", "on"], whyHe: "להסתדר / להצליח = work out." },
  },
  {
    id: "v-pv-wear-out",
    word: "wear out",
    pos: "phr",
    he: "להתבלות; להתיש",
    def: "to become old and useless from use; also, to make someone very tired",
    examples: ["These shoes wore out after one winter.", "The long trip wore me out."],
    cloze: "My old headphones ___, so I bought new ones.",
    clozeAnswer: "wore out",
    collocations: ["wear out shoes", "worn out"],
    band: 4,
    tags: ["phrasal"],
    trap: "worn out (תואר) = בלוי או מותש: I'm worn out. עבר: wore out.",
  },
  // ---------- back / blow / calm / count / dress / eat ----------
  {
    id: "v-pv-back-up",
    word: "back up",
    pos: "phr",
    he: "לגבות (קבצים); לתמוך ב",
    def: "to make a copy of computer files; also, to support someone",
    examples: ["Back up your files every week.", "My brother always backs me up."],
    cloze: "Did you ___ the photos before resetting the phone?",
    clozeAnswer: "back up",
    collocations: ["back up files", "back someone up"],
    band: 3,
    tags: ["phrasal"],
    trap: "back up = לגבות (מחשב) וגם לגבות מישהו (לתמוך בו). שם עצם: a backup.",
  },
  {
    id: "v-pv-blow-up",
    word: "blow up",
    pos: "phr",
    he: "להתפוצץ; להתפרץ בכעס",
    def: "to explode; also, to suddenly become very angry",
    examples: ["The old factory blew up.", "My dad blew up when he saw the bill."],
    cloze: "The gas tank could ___ if it gets too hot.",
    clozeAnswer: "blow up",
    collocations: ["blow up a balloon", "blow up at someone"],
    band: 3,
    tags: ["phrasal"],
    trap: "blow up גם = לנפח (blow up a balloon). blow up AT someone = להתפרץ עליו. עבר: blew up.",
    accept: ["explode"],
  },
  {
    id: "v-pv-calm-down",
    word: "calm down",
    pos: "phr",
    he: "להירגע",
    def: "to stop feeling angry, upset, or excited",
    examples: ["Calm down, everything is fine.", "It took him a while to calm down."],
    cloze: "Take a deep breath and ___.",
    clozeAnswer: "calm down",
    collocations: ["calm down", "calm someone down"],
    band: 1,
    tags: ["phrasal"],
    trap: "calm down = להירגע (רגשית); relax = לנוח, להירגע. נפרד: calm him down.",
    accept: ["relax"],
    colloc: { frame: "Please calm ___, nobody is hurt.", answer: "down", options: ["down", "off", "up"], whyHe: "להירגע = calm down." },
  },
  {
    id: "v-pv-count-on",
    word: "count on",
    pos: "phr",
    he: "לסמוך על",
    def: "to be sure that someone will help you or do what you need",
    examples: ["You can count on me.", "We're counting on you to finish this."],
    cloze: "I know I can always ___ my sister.",
    clozeAnswer: "count on",
    collocations: ["count on someone", "count on it"],
    band: 2,
    tags: ["phrasal"],
    trap: "count ON someone. Count me in = תספרו אותי (משהו אחר).",
    accept: ["rely on", "depend on"],
    colloc: { frame: "You can count ___ me.", answer: "on", options: ["on", "in", "with"], whyHe: "לסמוך על = count on." },
  },
  {
    id: "v-pv-dress-up",
    word: "dress up",
    pos: "phr",
    he: "להתלבש יפה; להתחפש",
    def: "to wear nice clothes for a special occasion; also, to wear a costume",
    examples: ["You don't need to dress up, it's casual.", "The kids dressed up as superheroes."],
    cloze: "Do we have to ___ for the wedding?",
    clozeAnswer: "dress up",
    collocations: ["dress up for a party", "dress up as a pirate"],
    band: 3,
    tags: ["phrasal"],
    trap: "dress up = להתלבש חגיגי או להתחפש (dress up AS); get dressed = סתם להתלבש.",
  },
  {
    id: "v-pv-eat-out",
    word: "eat out",
    pos: "phr",
    he: "לאכול בחוץ (במסעדה)",
    def: "to eat at a restaurant instead of at home",
    examples: ["We eat out about once a week.", "Let's eat out tonight, I don't feel like cooking."],
    cloze: "It's expensive to ___ every day.",
    clozeAnswer: "eat out",
    collocations: ["eat out tonight", "eat out a lot"],
    band: 1,
    tags: ["phrasal"],
    trap: "eat out = לאכול במסעדה; order in / get takeout = להזמין הביתה.",
  },
  // ---------- go off / grow / hurry / leave / log / mix ----------
  {
    id: "v-pv-go-off",
    word: "go off",
    pos: "phr",
    he: "לצלצל (אזעקה); להתפוצץ",
    def: "when an alarm starts ringing, or when a bomb explodes",
    examples: ["My alarm went off at five.", "The bomb went off in an empty street."],
    cloze: "The fire alarm ___ during the meeting.",
    clozeAnswer: "went off",
    collocations: ["the alarm goes off", "a bomb goes off"],
    band: 2,
    tags: ["phrasal"],
    trap: "The alarm went off = השעון צלצל (לא נכבה!). לכבות = turn off.",
  },
  {
    id: "v-pv-grow-up",
    word: "grow up",
    pos: "phr",
    he: "לגדול, להתבגר",
    def: "to change from a child into an adult",
    examples: ["I grew up in a small town.", "Grow up and stop complaining!"],
    cloze: "Where did you ___?",
    clozeAnswer: "grow up",
    collocations: ["grow up in a city", "when I grow up"],
    band: 1,
    tags: ["phrasal"],
    trap: "אנשים grow up (מתבגרים); צמחים וילדים grow (גדלים): I grew up in Haifa, לא I grew in Haifa. שם עצם: a grown-up.",
    colloc: { frame: "She grew ___ in Jerusalem.", answer: "up", options: ["up", "on", "out"], whyHe: "לגדול (ילדות) = grow up." },
  },
  {
    id: "v-pv-hurry-up",
    word: "hurry up",
    pos: "phr",
    he: "למהר",
    def: "to do something more quickly",
    examples: ["Hurry up, we're late!", "Can you hurry up in there?"],
    cloze: "Come on, ___, the bus is here!",
    clozeAnswer: "hurry up",
    collocations: ["hurry up!", "hurry up and finish"],
    band: 1,
    tags: ["phrasal"],
    trap: "Hurry up! = תזדרז! hurry up AND do it = תמהר ותעשה. לא נפרד.",
  },
  {
    id: "v-pv-leave-out",
    word: "leave out",
    pos: "phr",
    he: "להשמיט",
    def: "to not include someone or something",
    examples: ["You left out an important detail.", "Don't leave anyone out."],
    cloze: "Did I ___ anything in the summary?",
    clozeAnswer: "leave out",
    collocations: ["leave out a detail", "feel left out"],
    band: 3,
    tags: ["phrasal"],
    trap: "נפרד: leave it out. עבר: left out. feel left out = להרגיש שלא כללו אותך.",
  },
  {
    id: "v-pv-log-in",
    word: "log in",
    pos: "phr",
    he: "להתחבר (למערכת)",
    def: "to enter your username and password to use a website or computer",
    examples: ["I can't log in to my email.", "Log in with your username and password."],
    cloze: "You need to ___ before you can post a comment.",
    clozeAnswer: "log in",
    collocations: ["log in to a website", "log in with a password"],
    band: 1,
    tags: ["phrasal"],
    trap: "כפועל שתי מילים: log in TO the site; login (מילה אחת) = שם עצם. ההפך: log out.",
    accept: ["sign in", "log on"],
  },
  {
    id: "v-pv-mix-up",
    word: "mix up",
    pos: "phr",
    he: "לבלבל, להתבלבל בין",
    def: "to confuse two people or things with each other",
    examples: ["I always mix up their names.", "Sorry, I mixed up the dates."],
    cloze: "People often ___ the twins.",
    clozeAnswer: "mix up",
    collocations: ["mix up the names", "get mixed up"],
    band: 3,
    tags: ["phrasal"],
    trap: "mix up A and B = לבלבל ביניהם; I got mixed up = התבלבלתי. שם עצם: a mix-up.",
    accept: ["confuse"],
  },
  // ---------- put together / settle / sign / slow / split / stay ----------
  {
    id: "v-pv-put-together",
    word: "put together",
    pos: "phr",
    he: "להרכיב; להכין (מצגת, רשימה)",
    def: "to build something from parts, or to prepare something like a list or a plan",
    examples: ["We put together a short presentation.", "It took two hours to put together the shelf."],
    cloze: "Can you ___ a list of the guests?",
    clozeAnswer: "put together",
    collocations: ["put together a plan", "put together furniture"],
    band: 3,
    tags: ["phrasal"],
    trap: "put together = להרכיב / להכין. נפרד: put it together. עבר: put together.",
  },
  {
    id: "v-pv-settle-down",
    word: "settle down",
    pos: "phr",
    he: "להירגע; להתמקם, להקים משפחה",
    def: "to become calm and quiet; also, to start a stable life in one place",
    examples: ["It took the kids a while to settle down.", "He wants to settle down and start a family."],
    cloze: "OK class, ___ and open your books.",
    clozeAnswer: "settle down",
    collocations: ["settle down and start a family", "settle down after a busy day"],
    band: 4,
    tags: ["phrasal"],
    trap: "settle down = להירגע (ילדים, כיתה) או להתייצב בחיים (בית, משפחה).",
  },
  {
    id: "v-pv-sign-up",
    word: "sign up",
    pos: "phr",
    he: "להירשם",
    def: "to put your name on a list to join a course, a service, or an event",
    examples: ["I signed up for a Spanish course.", "Sign up on the website to get updates."],
    cloze: "Did you ___ for the marathon?",
    clozeAnswer: "sign up",
    collocations: ["sign up for a course", "sign up for a newsletter"],
    band: 1,
    tags: ["phrasal"],
    trap: "sign up FOR something, לא sign up to (בארה\"ב). register = פורמלי.",
    accept: ["register"],
    colloc: { frame: "I signed ___ for a yoga class.", answer: "up", options: ["up", "in", "on"], whyHe: "להירשם = sign up for." },
  },
  {
    id: "v-pv-slow-down",
    word: "slow down",
    pos: "phr",
    he: "להאט",
    def: "to go or do something more slowly",
    examples: ["Slow down, you're driving too fast.", "The doctor told me to slow down and rest."],
    cloze: "Please ___, I can't follow what you're saying.",
    clozeAnswer: "slow down",
    collocations: ["slow down the car", "slow down a bit"],
    band: 1,
    tags: ["phrasal"],
    trap: "slow down = להאט; speed up = להאיץ. נפרד: slow it down.",
    colloc: { frame: "The car slowed ___ near the school.", answer: "down", options: ["down", "off", "up"], whyHe: "להאט = slow down." },
  },
  {
    id: "v-pv-split-up",
    word: "split up",
    pos: "phr",
    he: "להיפרד; להתפצל",
    def: "to end a relationship; also, to divide into smaller groups",
    examples: ["My parents split up when I was ten.", "Let's split up and meet back here at noon."],
    cloze: "The band ___ after their last tour.",
    clozeAnswer: "split up",
    collocations: ["split up with someone", "split up into groups"],
    band: 3,
    tags: ["phrasal"],
    trap: "split up = break up (זוג) או להתפצל (קבוצה). עבר: split up (ללא שינוי).",
    accept: ["break up"],
  },
  {
    id: "v-pv-stay-up",
    word: "stay up",
    pos: "phr",
    he: "להישאר ער",
    def: "to not go to bed until late",
    examples: ["I stayed up until 2 a.m. studying.", "Don't stay up too late."],
    cloze: "The kids want to ___ to watch the game.",
    clozeAnswer: "stay up",
    collocations: ["stay up late", "stay up all night"],
    band: 1,
    tags: ["phrasal"],
    trap: "stay up late = להישאר ער עד מאוחר; stay awake = להישאר ער (לא להירדם).",
  },
  // ---------- take back / turn around / use up / watch out / work on ----------
  {
    id: "v-pv-take-back",
    word: "take back",
    pos: "phr",
    he: "להחזיר (לחנות); לחזור בך",
    def: "to return something to a store; also, to say that something you said was wrong",
    examples: ["I took the shirt back because it was too small.", "I take back what I said, sorry."],
    cloze: "You can ___ the jacket if it doesn't fit.",
    clozeAnswer: "take back",
    collocations: ["take back a purchase", "take back what you said"],
    band: 2,
    tags: ["phrasal"],
    trap: "נפרד: take it back. I take it back = אני חוזר בי. bring back = להביא בחזרה לכאן.",
    accept: ["return"],
  },
  {
    id: "v-pv-turn-around",
    word: "turn around",
    pos: "phr",
    he: "להסתובב; להפוך (מצב) לטובה",
    def: "to turn so you face the other way; also, to make a bad situation good",
    examples: ["Turn around and look at me.", "The new manager turned the company around."],
    cloze: "I heard my name, so I ___.",
    clozeAnswer: "turned around",
    collocations: ["turn around and go back", "turn a company around"],
    band: 3,
    tags: ["phrasal"],
    trap: "turn around = להסתובב במקום; turn = לפנות (turn left). נפרד במשמעות העסקית: turn it around.",
  },
  {
    id: "v-pv-use-up",
    word: "use up",
    pos: "phr",
    he: "לגמור (לנצל עד הסוף)",
    def: "to use all of something so there is none left",
    examples: ["We used up all the milk.", "Don't use up the hot water."],
    cloze: "Someone ___ all the printer paper.",
    clozeAnswer: "used up",
    collocations: ["use up the milk", "use up energy"],
    band: 3,
    tags: ["phrasal"],
    trap: "use up = לגמור לגמרי (פעולה); run out of = להישאר בלי (התוצאה). נפרד: use it up.",
  },
  {
    id: "v-pv-watch-out",
    word: "watch out",
    pos: "phr",
    he: "להיזהר",
    def: "used to tell someone to be careful",
    examples: ["Watch out! There's a step.", "Watch out for pickpockets in the market."],
    cloze: "You should ___ for scams online.",
    clozeAnswer: "watch out",
    collocations: ["watch out for", "watch out!"],
    band: 1,
    tags: ["phrasal"],
    trap: "Watch out! = זהירות! עם מושא: watch out FOR cars. be careful = תיזהר (פחות דחוף).",
    accept: ["look out"],
  },
  {
    id: "v-pv-work-on",
    word: "work on",
    pos: "phr",
    he: "לעבוד על",
    def: "to spend time trying to improve or finish something",
    examples: ["I'm working on a new project.", "You need to work on your pronunciation."],
    cloze: "What are you ___ these days?",
    clozeAnswer: "working on",
    collocations: ["work on a project", "work on your English"],
    band: 1,
    tags: ["phrasal"],
    trap: "work ON something = לעבוד על; work AT a place = לעבוד ב-; work FOR a company = לעבוד אצל.",
    colloc: { frame: "I'm working ___ my English every day.", answer: "on", options: ["on", "at", "in"], whyHe: "לעבוד על = work on." },
  },
];
