import type { VocabItem } from "@/lib/types";

export const TRAVEL_CITY: VocabItem[] = [
  // ---------- verbs & phrases ----------
  {
    id: "v-tr-book",
    word: "book",
    pos: "v",
    he: "להזמין (מקום, כרטיס)",
    def: "to arrange to have a room, seat, or ticket kept for you",
    examples: ["I booked a hotel near the beach.", "We should book the flights before prices go up."],
    cloze: "Did you ___ a table for tonight?",
    collocations: ["book a flight", "book a room", "book a table"],
    band: 1,
    tags: ["travel"],
    trap: "בעברית 'להזמין' משמש לכל דבר. באנגלית: book a room/flight/table (לשריין מקום), order food (להזמין אוכל), invite people (להזמין אנשים).",
    colloc: { frame: "I'd like to ___ a room for two nights.", answer: "book", options: ["book", "order", "invite"], whyHe: "מזמינים חדר = book. order = מזמינים אוכל או מוצר, invite = מזמינים אנשים." },
  },

  
  {
    id: "v-tr-pack",
    word: "pack",
    pos: "v",
    he: "לארוז",
    def: "to put your clothes and things into a bag or suitcase for a trip",
    examples: ["I still haven't packed for the trip.", "Don't forget to pack a charger."],
    cloze: "We leave at six tomorrow, so I need to ___ tonight.",
    collocations: ["pack a suitcase", "pack light", "pack your bags"],
    band: 1,
    tags: ["travel"],
    trap: "pack = לארוז. לא 'to make the suitcase'. שימו לב: package = חבילה, packet = חפיסה.",
    colloc: { frame: "Try to ___ light, we're taking a small plane.", answer: "pack", options: ["pack", "carry", "fill"], whyHe: "pack light = לארוז מעט. carry = לסחוב, fill = למלא." },
  },
  
  {
    id: "v-tr-turn-left",
    word: "turn left",
    pos: "phr",
    he: "לפנות שמאלה",
    def: "to change direction to the left",
    examples: ["Turn left at the traffic lights.", "You turned left too early, we missed the street."],
    cloze: "___ at the bank, and the museum is right there.",
    collocations: ["turn left at", "take the first left"],
    band: 1,
    tags: ["city"],
    trap: "turn left / turn right בלי to: לא 'turn to left'. וגם: take the first left = לפנות בשמאלה הראשונה.",
  },
  {
    id: "v-tr-go-straight",
    word: "go straight",
    pos: "phr",
    he: "להמשיך ישר",
    def: "to continue in the same direction without turning",
    examples: ["Go straight for two blocks and you'll see the station.", "Just go straight until the road ends."],
    cloze: "Don't turn here, ___ and then take the second right.",
    collocations: ["go straight ahead", "go straight on"],
    band: 1,
    tags: ["city"],
    trap: "ישר (בכיוון) = straight, לא direct. אומרים go straight ahead / straight on. שימו לב: straight home = ישר הביתה (מיד).",
  },
  
  {
    id: "v-tr-get-off",
    word: "get off",
    pos: "phr",
    he: "לרדת (מאוטובוס, מרכבת)",
    def: "to leave a bus, train, or plane",
    examples: ["Get off at the third stop.", "I got off the train and looked for a taxi."],
    cloze: "Which stop do I ___ at for the museum?",
    collocations: ["get off at", "get off the train"],
    band: 1,
    tags: ["transport"],
    trap: "יורדים מאוטובוס = get off, יוצאים ממכונית = get out of. לא 'go down from the bus'.",
  },
  
  {
    id: "v-tr-land",
    word: "land",
    pos: "v",
    he: "לנחות",
    def: "(of a plane) to come down to the ground at the end of a flight",
    examples: ["We landed in Rome just after midnight.", "The plane couldn't land because of the fog."],
    cloze: "What time does your flight ___ in Tel Aviv?",
    collocations: ["land safely", "land at the airport", "land in Paris"],
    band: 2,
    tags: ["transport"],
    trap: "נוחתים in a city / at an airport: We landed in London, at Heathrow. לא 'landed to'.",
  },

  {
    id: "v-tr-rent",
    word: "rent",
    pos: "v",
    he: "לשכור (רכב, דירה)",
    def: "to pay money to use a car, room, or apartment for a short time",
    examples: ["We rented a car for the whole week.", "It's cheaper to rent an apartment than to stay in a hotel."],
    cloze: "Let's ___ bikes and ride along the beach.",
    collocations: ["rent a car", "rent an apartment", "rental car"],
    band: 1,
    tags: ["travel"],
    trap: "rent = לשכור בתשלום (מכונית, דירה, אופניים). בבריטניה גם hire a car. rent הוא גם שם העצם: שכר דירה (pay the rent).",
    colloc: { frame: "We decided to ___ a car instead of taking trains.", answer: "rent", options: ["rent", "borrow", "lend"], whyHe: "שוכרים בתשלום = rent. borrow = לשאול בחינם, lend = להשאיל." },
  },
  
  {
    id: "v-tr-miss",
    word: "miss",
    pos: "v",
    he: "לפספס",
    def: "to arrive too late for a bus, train, or plane",
    examples: ["We missed the last bus and had to walk.", "If you don't leave now, you'll miss your flight."],
    cloze: "I ___ the train by two minutes, so I took a taxi.",
    clozeAnswer: "missed",
    collocations: ["miss a flight", "miss the bus", "miss a connection"],
    band: 1,
    tags: ["transport"],
    trap: "miss = לפספס (miss the bus) וגם להתגעגע (I miss you). 'to lose the bus' זו טעות נפוצה, אומרים miss the bus.",
    colloc: { frame: "Run, or we'll ___ the last train!", answer: "miss", options: ["miss", "lose", "pass"], whyHe: "מפספסים רכבת = miss the train. lose = לאבד." },
  },
  {
    id: "v-tr-catch",
    word: "catch",
    pos: "v",
    he: "לתפוס (אוטובוס, רכבת)",
    def: "to get on a bus, train, or plane in time to travel on it",
    examples: ["I have to catch the 8:15 train.", "We caught a taxi outside the hotel."],
    cloze: "If we hurry, we can still ___ the last bus.",
    collocations: ["catch a bus", "catch a flight", "catch a taxi"],
    band: 2,
    tags: ["transport"],
    colloc: { frame: "I need to ___ a flight at six tomorrow morning.", answer: "catch", options: ["catch", "reach", "hold"], whyHe: "תופסים טיסה או אוטובוס = catch (או take). reach = להגיע ל." },
  },
  {
    id: "v-tr-overtake",
    word: "overtake",
    pos: "v",
    he: "לעקוף (רכב)",
    def: "to pass another vehicle that is going more slowly",
    examples: ["Don't overtake on a bend, it's dangerous.", "A truck overtook us at over 120 kilometers an hour."],
    cloze: "It's illegal to ___ on this part of the road.",
    collocations: ["overtake a car", "overtake on the right"],
    band: 3,
    tags: ["transport"],
    trap: "עוקפים רכב = overtake (בארה״ב אומרים גם pass). לא bypass, זה כביש עוקף.",
  },

  {
    id: "v-tr-explore",
    word: "explore",
    pos: "v",
    he: "לסייר ולגלות, לחקור",
    def: "to walk around a new place to see what is there",
    examples: ["We spent the afternoon exploring the old town.", "I love exploring cities on foot."],
    cloze: "Let's ___ the neighborhood before dinner.",
    collocations: ["explore the city", "explore on foot", "explore the area"],
    band: 2,
    tags: ["travel"],
  },
  {
    id: "v-tr-arrive",
    word: "arrive",
    pos: "v",
    he: "להגיע",
    def: "to get to a place at the end of a journey",
    examples: ["We arrived at the hotel after midnight.", "What time does the train arrive in Haifa?"],
    cloze: "Call me when you ___ at the airport.",
    collocations: ["arrive at the station", "arrive in a city", "arrive on time"],
    band: 1,
    tags: ["travel"],
    trap: "אחרי arrive לא באה to: arrive at (מקום קטן: מלון, תחנה) / arrive in (עיר, מדינה). arrive home בלי מילת יחס.",
    colloc: { frame: "We ___ in Barcelona late at night.", answer: "arrived", options: ["arrived", "reached", "came"], whyHe: "עם in או at משתמשים ב-arrive. reach בא בלי מילת יחס: reached Barcelona." },
  },
  
  {
    id: "v-tr-change",
    word: "change",
    pos: "v",
    he: "להחליף (רכבת, אוטובוס)",
    def: "to get off one train or bus and get on another",
    examples: ["You have to change trains at the central station.", "Is it a direct bus or do I need to change?"],
    cloze: "It's a direct flight, so you don't have to ___ planes.",
    collocations: ["change trains", "change at", "change money"],
    band: 2,
    tags: ["transport"],
    trap: "מחליפים רכבת = change trains (ברבים!). change גם = להחליף כסף (change money), וגם עודף (keep the change).",
    colloc: { frame: "You don't need to ___ trains, this one goes all the way.", answer: "change", options: ["change", "replace", "exchange"], whyHe: "מחליפים רכבת = change trains. replace = להחליף משהו במשהו אחר, exchange = להחליף כסף או מוצר." },
  },
  {
    id: "v-tr-pour",
    word: "pour",
    pos: "v",
    he: "לרדת גשם חזק",
    def: "to rain very heavily",
    examples: ["It poured all night, so the roads are flooded.", "Take an umbrella, it's pouring outside."],
    cloze: "We couldn't leave the cafe because it was ___.",
    clozeAnswer: "pouring",
    collocations: ["it's pouring", "pouring rain", "pour with rain"],
    band: 2,
    tags: ["weather"],
    colloc: { frame: "It's ___ out there, wait ten minutes.", answer: "pouring", options: ["pouring", "falling", "dropping"], whyHe: "גשם חזק = it's pouring. 'rain is falling' נשמע ספרותי, dropping לא נאמר." },
  },
  {
    id: "v-tr-recycle",
    word: "recycle",
    pos: "v",
    he: "למחזר",
    def: "to use paper, plastic, or glass again instead of throwing it away",
    examples: ["Do you recycle plastic bottles at home?", "The hotel recycles everything, even the soap."],
    cloze: "There's a green bin outside where you can ___ paper.",
    collocations: ["recycle plastic", "recycling bin", "recycle waste"],
    band: 1,
    tags: ["nature"],
  },
  {
    id: "v-tr-hike",
    word: "hike",
    pos: "v",
    he: "לטייל ברגל (בטבע)",
    def: "to go for a long walk in the countryside or mountains",
    examples: ["We hiked to the top of the hill before sunrise.", "I love hiking in the north in winter."],
    cloze: "We're going to ___ around the lake this weekend.",
    collocations: ["go hiking", "hike a trail", "hiking boots"],
    band: 1,
    tags: ["nature"],
    trap: "'טיול' בעברית זה הכול; באנגלית: hike = הליכה בטבע, trip = נסיעה, walk = הליכה רגילה. אומרים go hiking, לא 'make a hike'.",
  },
  {
    id: "v-tr-cross",
    word: "cross",
    pos: "v",
    he: "לחצות",
    def: "to go from one side of a road, river, or bridge to the other",
    examples: ["Cross the street at the traffic lights.", "We crossed the bridge and turned right."],
    cloze: "Wait for the green light before you ___ the road.",
    collocations: ["cross the street", "cross the border", "cross the bridge"],
    band: 1,
    tags: ["city"],
    trap: "cross = לחצות (פועל). across = מילת יחס: across the street = מעבר לרחוב. across from the bank = מול הבנק.",
  },
  {
    id: "v-tr-stay",
    word: "stay",
    pos: "v",
    he: "להתארח, לשהות",
    def: "to live in a place for a short time as a visitor",
    examples: ["We stayed at a small hotel by the sea.", "How long are you staying in Berlin?"],
    cloze: "Where did you ___ when you were in Rome?",
    collocations: ["stay at a hotel", "stay with friends", "stay for a week"],
    band: 1,
    tags: ["travel"],
    trap: "'ישנתי במלון' = I stayed at a hotel, לא sleep in a hotel. stay with friends = לישון אצל חברים.",
    colloc: { frame: "We ___ at a cheap hostel near the station.", answer: "stayed", options: ["stayed", "slept", "lived"], whyHe: "מתארחים במלון = stay at. sleep מתאר רק את השינה, live = לגור." },
  },
  {
    id: "v-tr-give-directions",
    word: "give directions",
    pos: "phr",
    he: "להסביר את הדרך",
    def: "to tell someone how to get to a place",
    examples: ["A woman at the bus stop gave us directions to the museum.", "I'm bad at giving directions, let me draw a map."],
    cloze: "Excuse me, could you ___ to the train station?",
    clozeAnswer: "give me directions",
    collocations: ["give someone directions", "ask for directions", "follow the directions"],
    band: 2,
    tags: ["city"],
    trap: "directions (ברבים) = הסבר הדרך. ask for directions = לשאול איך מגיעים. direction (יחיד) = כיוון.",
    colloc: { frame: "We got lost, so we ___ for directions.", answer: "asked", options: ["asked", "requested", "questioned"], whyHe: "שואלים איך מגיעים = ask for directions." },
  },
  {
    id: "v-tr-go-sightseeing",
    word: "go sightseeing",
    pos: "phr",
    he: "לסייר באתרים",
    def: "to visit the interesting and famous places in a city",
    examples: ["On our first day we went sightseeing in the old town.", "I'm too tired to go sightseeing today."],
    cloze: "We'll ___ in the morning and relax at the pool later.",
    collocations: ["go sightseeing", "a sightseeing tour", "do some sightseeing"],
    band: 2,
    tags: ["travel"],
    trap: "אומרים go sightseeing / do some sightseeing, לא 'make sightseeing'. sightseeing הוא שם עצם לא ספיר.",
  },
  {
    id: "v-tr-get-around",
    word: "get around",
    pos: "phr",
    he: "להתנייד (בעיר)",
    def: "to travel from place to place in a city or area",
    examples: ["The easiest way to get around Amsterdam is by bike.", "Without a car, it's hard to get around here."],
    cloze: "How do people ___ in this city, bus or subway?",
    collocations: ["get around by bike", "get around the city", "easy to get around"],
    band: 2,
    tags: ["city"],
  },
  {
    id: "v-tr-show-around",
    word: "show around",
    pos: "phr",
    he: "לעשות סיור (למישהו)",
    def: "to take a visitor to the interesting places in a city or building",
    examples: ["My cousin showed us around Tel Aviv.", "Come visit and I'll show you around."],
    cloze: "If you come to Haifa, I'll ___ the city.",
    clozeAnswer: "show you around",
    collocations: ["show someone around", "show around the city"],
    band: 3,
    tags: ["travel"],
    trap: "'לעשות לו סיור' = show him around (המילה him באמצע). לא 'make him a tour'.",
  },
  {
    id: "v-tr-get-stuck",
    word: "get stuck",
    pos: "phr",
    he: "להיתקע",
    def: "to be unable to move or continue",
    examples: ["We got stuck in traffic for an hour.", "The car got stuck in the mud."],
    cloze: "Sorry I'm late, I ___ in a traffic jam.",
    clozeAnswer: "got stuck",
    collocations: ["get stuck in traffic", "get stuck in an elevator"],
    band: 2,
    tags: ["transport"],
    colloc: { frame: "I was ___ in traffic for two hours.", answer: "stuck", options: ["stuck", "caught", "held"], whyHe: "נתקעים בפקק = stuck in traffic. caught in the rain = נתפסים בגשם." },
  },
  
  {
    id: "v-tr-fill-up",
    word: "fill up",
    pos: "phr",
    he: "לתדלק (מיכל מלא)",
    def: "to put gas in a car until the tank is full",
    examples: ["Let's fill up before we leave the city.", "I filled up the tank this morning."],
    cloze: "We need to ___ at the next gas station.",
    collocations: ["fill up the tank", "fill up with gas"],
    band: 3,
    tags: ["transport"],
  },
  {
    id: "v-tr-board",
    word: "board",
    pos: "v",
    he: "לעלות (למטוס, לספינה)",
    def: "to get on a plane, ship, or train",
    examples: ["Passengers with small children may board first.", "We boarded the ship at six in the evening."],
    cloze: "Flight 302 is now ready to ___ at gate 12.",
    collocations: ["board the plane", "boarding time", "boarding pass"],
    band: 3,
    tags: ["transport"],
    trap: "board = לעלות למטוס (רשמי, בהודעות בשדה); בדיבור get on the plane. on board = במטוס, על הסיפון.",
  },

  // ---------- nouns ----------
  {
    id: "v-tr-reservation",
    word: "reservation",
    pos: "n",
    he: "הזמנה (שריון מקום)",
    def: "an arrangement to have a room, table, or seat kept for you",
    examples: ["I have a reservation under the name Cohen.", "You need a reservation for that restaurant."],
    cloze: "Hi, I'd like to make a ___ for two nights, please.",
    collocations: ["make a reservation", "have a reservation", "confirm a reservation"],
    band: 1,
    tags: ["travel"],
    trap: "עושים הזמנה = make a reservation (או booking). לא 'do a reservation'. order = הזמנת אוכל או מוצר.",
    colloc: { frame: "Did you ___ a reservation for dinner?", answer: "make", options: ["make", "do", "take"], whyHe: "make a reservation = לשריין מקום." },
  },
  {
    id: "v-tr-boarding-pass",
    word: "boarding pass",
    pos: "n",
    he: "כרטיס עלייה למטוס",
    def: "the card you show to get on a plane",
    examples: ["Please have your boarding pass and passport ready.", "I saved my boarding pass on my phone."],
    cloze: "You can print your ___ at home or use the app.",
    collocations: ["print a boarding pass", "show your boarding pass"],
    band: 2,
    tags: ["travel"],
  },
  {
    id: "v-tr-gate",
    word: "gate",
    pos: "n",
    he: "שער (בשדה תעופה)",
    def: "the place in an airport where you wait and get on your plane",
    examples: ["Our flight leaves from gate 22.", "Boarding starts at the gate thirty minutes before the flight."],
    cloze: "Let's find our ___ first and then get coffee.",
    collocations: ["go to the gate", "the gate closes", "gate number"],
    band: 2,
    tags: ["travel"],
    colloc: { frame: "The ___ closes ten minutes before departure.", answer: "gate", options: ["gate", "door", "entrance"], whyHe: "שער עלייה למטוס = gate." },
  },
  {
    id: "v-tr-delay",
    word: "delay",
    pos: "n",
    he: "עיכוב",
    def: "a situation when something happens later than planned",
    examples: ["There's a two-hour delay on our flight.", "Sorry for the delay, the traffic was terrible."],
    cloze: "Because of a ___, we missed our connection in Istanbul.",
    collocations: ["a long delay", "flight delay", "be delayed"],
    band: 1,
    tags: ["transport"],
    trap: "delay (שם עצם) / be delayed (סביל): The flight is delayed. לא 'the flight has delay'.",
    colloc: { frame: "Our train was ___ by forty minutes.", answer: "delayed", options: ["delayed", "late", "postponed"], whyHe: "עוכב ב-40 דקות = was delayed by. late לא מקבל by. postponed = נדחה למועד אחר." },
  },
  {
    id: "v-tr-connection",
    word: "connection",
    pos: "n",
    he: "טיסת המשך, קונקשן",
    def: "a second flight, train, or bus that you take to continue your journey",
    examples: ["We have a tight connection in Frankfurt, only fifty minutes.", "I missed my connection because the first flight was late."],
    cloze: "Our first flight was late, so we missed our ___ to Boston.",
    collocations: ["miss a connection", "a tight connection", "connecting flight"],
    band: 2,
    tags: ["travel"],
    trap: "טיסת המשך = connecting flight או connection. 'continuation flight' לא קיים באנגלית.",
  },
  {
    id: "v-tr-luggage",
    word: "luggage",
    pos: "n",
    he: "מטען, מזוודות",
    def: "the bags and suitcases you take with you when you travel",
    examples: ["How much luggage are you taking?", "My luggage didn't arrive with the flight."],
    cloze: "You can leave your ___ at the hotel until check-in time.",
    collocations: ["hand luggage", "a piece of luggage", "lost luggage"],
    band: 1,
    tags: ["travel"],
    trap: "luggage (וגם baggage) לא ספיר: אין luggages ואין a luggage. אומרים a piece of luggage או a suitcase.",
    colloc: { frame: "Sorry, sir, your hand ___ is too big for the cabin.", answer: "luggage", options: ["luggage", "luggages", "bags"], whyHe: "hand luggage = מטען יד, בלי ריבוי." },
  },
  {
    id: "v-tr-suitcase",
    word: "suitcase",
    pos: "n",
    he: "מזוודה",
    def: "a large bag with a handle that you carry clothes in when you travel",
    examples: ["I can't close my suitcase, it's too full.", "The wheels on my suitcase broke at the airport."],
    cloze: "This ___ is too heavy, you'll have to pay extra.",
    collocations: ["pack a suitcase", "a heavy suitcase", "carry a suitcase"],
    band: 1,
    tags: ["travel"],
  },
  {
    id: "v-tr-customs",
    word: "customs",
    pos: "n",
    he: "מכס",
    def: "the place at an airport or border where your bags can be checked",
    examples: ["We waited an hour to get through customs.", "Do I need to declare this at customs?"],
    cloze: "After you collect your bags, you go through ___.",
    collocations: ["go through customs", "customs officer", "declare at customs"],
    band: 3,
    tags: ["travel"],
    trap: "customs תמיד עם s כשהכוונה למכס (go through customs). custom ביחיד = מנהג.",
    colloc: { frame: "It took ages to get ___ customs.", answer: "through", options: ["through", "across", "over"], whyHe: "עוברים במכס = go / get through customs." },
  },
  {
    id: "v-tr-landmark",
    word: "landmark",
    pos: "n",
    he: "ציון דרך, אתר מפורסם",
    def: "a famous building or place that is easy to recognize",
    examples: ["The Eiffel Tower is the most famous landmark in Paris.", "We visited all the main landmarks in one day."],
    cloze: "That clock tower is a well-known ___ in the city.",
    collocations: ["a famous landmark", "historic landmark"],
    band: 3,
    tags: ["travel"],
  },
  {
    id: "v-tr-view",
    word: "view",
    pos: "n",
    he: "נוף (ממקום מסוים)",
    def: "what you can see from a place, especially beautiful countryside or a city",
    examples: ["Our room had an amazing view of the sea.", "You get the best view of the city from the roof."],
    cloze: "We paid extra for a room with a ___ of the mountains.",
    collocations: ["a room with a view", "a view of the sea", "a great view"],
    band: 2,
    tags: ["travel"],
    trap: "נוף שרואים ממקום מסוים = view (a view of the sea). נוף כמראה כללי של אזור = landscape / scenery. point of view = נקודת מבט.",
    colloc: { frame: "The hotel has a beautiful ___ of the old town.", answer: "view", options: ["view", "look", "sight"], whyHe: "נוף מהחלון = view of. look = מבט, sight = מראה או אתר." },
  },
  {
    id: "v-tr-guided-tour",
    word: "guided tour",
    pos: "n",
    he: "סיור מודרך",
    def: "a visit to a place with a person who explains what you see",
    examples: ["We took a guided tour of the old city.", "The guided tour starts at ten and lasts two hours."],
    cloze: "The museum offers a free ___ every morning at eleven.",
    collocations: ["take a guided tour", "go on a guided tour", "book a tour"],
    band: 2,
    tags: ["travel"],
    trap: "עושים סיור = take a tour / go on a tour, לא 'make a tour'. המדריך = guide (לא 'guider').",
    colloc: { frame: "We ___ a guided tour of the castle.", answer: "took", options: ["took", "made", "did"], whyHe: "take a tour / go on a tour = לעשות סיור." },
  },
  {
    id: "v-tr-trip",
    word: "trip",
    pos: "n",
    he: "נסיעה, טיול",
    def: "a journey to a place and back, usually for a short time",
    examples: ["We're going on a trip to Greece next month.", "How was your business trip?"],
    cloze: "It was a short ___, just three days in Paris.",
    collocations: ["go on a trip", "a business trip", "a day trip"],
    band: 1,
    tags: ["travel"],
    trap: "trip = נסיעה או טיול מסוים (שם עצם). travel = לנסוע (פועל) או נסיעות באופן כללי, לא אומרים 'a travel'. journey = הדרך עצמה.",
    colloc: { frame: "We're ___ on a trip to Italy in May.", answer: "going", options: ["going", "making", "doing"], whyHe: "go on a trip = לצאת לטיול. לא make a trip." },
  },
  {
    id: "v-tr-journey",
    word: "journey",
    pos: "n",
    he: "מסע, הנסיעה עצמה",
    def: "the act of traveling from one place to another, especially a long way",
    examples: ["The journey from the airport to the hotel took two hours.", "It was a long journey, but the views were beautiful."],
    cloze: "Have a safe ___! Text me when you arrive.",
    collocations: ["a long journey", "a safe journey", "on the journey"],
    band: 2,
    tags: ["travel"],
    trap: "journey = הנסיעה עצמה מנקודה לנקודה. trip = כל הטיול כולל השהות. travel = פועל, או שם עצם כללי בלי a.",
  },
  {
    id: "v-tr-block",
    word: "block",
    pos: "n",
    he: "בלוק (קטע רחוב בין צמתים)",
    def: "the part of a street between two corners",
    examples: ["The pharmacy is two blocks from here.", "Walk one block and turn right."],
    cloze: "The bank is just around the corner, one ___ away.",
    collocations: ["two blocks away", "walk a block", "around the block"],
    band: 3,
    tags: ["city"],
    trap: "block בארה״ב = קטע רחוב בין שני צמתים (walk two blocks). בניין = building, לא block.",
  },
  {
    id: "v-tr-traffic-jam",
    word: "traffic jam",
    pos: "n",
    he: "פקק תנועה",
    def: "a long line of cars that cannot move or move very slowly",
    examples: ["We were in a traffic jam for an hour.", "There's always a traffic jam on this road at five."],
    cloze: "Sorry I'm late, there was a huge ___ on the highway.",
    collocations: ["stuck in a traffic jam", "a huge traffic jam", "heavy traffic"],
    band: 1,
    tags: ["transport"],
    colloc: { frame: "There's ___ traffic downtown in the evening.", answer: "heavy", options: ["heavy", "strong", "big"], whyHe: "תנועה כבדה = heavy traffic." },
  },
  {
    id: "v-tr-rush-hour",
    word: "rush hour",
    pos: "n",
    he: "שעת העומס",
    def: "the time of day when roads and trains are very busy because people are going to or from work",
    examples: ["Avoid the subway during rush hour.", "It took me ninety minutes to get home in rush hour traffic."],
    cloze: "Let's leave before five so we miss the ___.",
    collocations: ["during rush hour", "rush hour traffic", "avoid rush hour"],
    band: 3,
    tags: ["transport"],
    colloc: { frame: "The trains are packed ___ rush hour.", answer: "during", options: ["during", "while", "along"], whyHe: "during rush hour = בשעת העומס. while בא לפני משפט, לא לפני שם עצם." },
  },
  {
    id: "v-tr-fare",
    word: "fare",
    pos: "n",
    he: "דמי נסיעה",
    def: "the money you pay to travel on a bus, train, taxi, or plane",
    examples: ["The bus fare is two euros.", "Taxi fares from the airport are very high."],
    cloze: "How much is the ___ to the city center?",
    collocations: ["bus fare", "pay the fare", "a cheap fare"],
    band: 3,
    tags: ["transport"],
    trap: "fare = מחיר נסיעה (bus fare, train fare), לא price כשמדובר בתחבורה. fair (הוגן, יריד) נשמע אותו דבר.",
  },
  {
    id: "v-tr-platform",
    word: "platform",
    pos: "n",
    he: "רציף",
    def: "the place in a train station where you wait for and get on the train",
    examples: ["The train to Haifa leaves from platform 3.", "We waited on the platform for twenty minutes."],
    cloze: "Which ___ does the train to Munich leave from?",
    collocations: ["on the platform", "platform number", "leave from platform 2"],
    band: 2,
    tags: ["transport"],
    trap: "אנחנו על הרציף = on the platform, לא in. בארה״ב אומרים גם track (Track 5).",
  },
  {
    id: "v-tr-round-trip-ticket",
    word: "round-trip ticket",
    pos: "n",
    he: "כרטיס הלוך ושוב",
    def: "a ticket to go to a place and come back",
    examples: ["A round-trip ticket is cheaper than two one-way tickets.", "I bought a round-trip ticket to Eilat."],
    cloze: "Do you want a one-way or a ___?",
    collocations: ["buy a round-trip ticket", "round trip", "return ticket (UK)"],
    band: 2,
    tags: ["transport"],
    trap: "הלוך ושוב = round-trip (ארה״ב) / return (בריטניה). לא 'there and back ticket'.",
  },
  {
    id: "v-tr-parking",
    word: "parking",
    pos: "n",
    he: "חניה",
    def: "leaving a car somewhere; the space where cars can be left",
    examples: ["Parking in the city center is expensive.", "Is there free parking at the hotel?"],
    cloze: "There's no ___ on this street after 8 a.m.",
    collocations: ["free parking", "parking lot", "parking space", "find parking"],
    band: 1,
    tags: ["transport"],
    trap: "parking לא ספיר: 'לא מצאתי חניה' = I couldn't find parking / a parking space. לא 'a parking'. חניון = parking lot.",
    colloc: { frame: "We drove around for ages looking for a parking ___.", answer: "space", options: ["space", "place", "room"], whyHe: "מקום חניה = parking space / parking spot." },
  },
  {
    id: "v-tr-fine",
    word: "fine",
    pos: "n",
    he: "קנס",
    def: "money you must pay because you broke a rule or law",
    examples: ["I got a fine for parking on the sidewalk.", "The fine for speeding here is 500 shekels."],
    cloze: "If you don't buy a ticket, you'll get a ___ of 100 euros.",
    collocations: ["get a fine", "pay a fine", "a parking fine"],
    band: 3,
    tags: ["transport"],
    trap: "fine = קנס (שם עצם), לא רק 'בסדר'. מקבלים קנס = get a fine, משלמים = pay a fine. 'a report' זו טעות (דו״ח בעברית).",
    colloc: { frame: "He had to ___ a fine of 300 shekels.", answer: "pay", options: ["pay", "give", "take"], whyHe: "משלמים קנס = pay a fine." },
  },
  {
    id: "v-tr-speed-limit",
    word: "speed limit",
    pos: "n",
    he: "מהירות מותרת",
    def: "the fastest speed that you are allowed to drive on a road",
    examples: ["The speed limit on this road is 90.", "He was driving well over the speed limit."],
    cloze: "Slow down, the ___ here is only 50.",
    collocations: ["over the speed limit", "break the speed limit", "stick to the speed limit"],
    band: 2,
    tags: ["transport"],
    colloc: { frame: "The police stopped him for driving ___ the speed limit.", answer: "over", options: ["over", "up to", "after"], whyHe: "מעל המהירות המותרת = over the speed limit." },
  },
  {
    id: "v-tr-flat-tire",
    word: "flat tire",
    pos: "n",
    he: "פנצ'ר",
    def: "a tire on a car or bike that has lost its air",
    examples: ["We got a flat tire on the way to the airport.", "Do you know how to change a flat tire?"],
    cloze: "We had a ___ on the highway and had to wait for help.",
    collocations: ["get a flat tire", "change a flat tire", "have a flat"],
    band: 2,
    tags: ["transport"],
    trap: "פנצ'ר = a flat tire (ארה״ב) / a puncture (בריטניה). 'puncher' לא קיים.",
    colloc: { frame: "It took him twenty minutes to ___ the flat tire.", answer: "change", options: ["change", "exchange", "repair up"], whyHe: "מחליפים גלגל = change a tire." },
  },
  {
    id: "v-tr-gas-station",
    word: "gas station",
    pos: "n",
    he: "תחנת דלק",
    def: "a place where you buy fuel for your car",
    examples: ["Is there a gas station near here?", "We stopped at a gas station for coffee."],
    cloze: "The tank is almost empty, let's stop at the next ___.",
    collocations: ["stop at a gas station", "fill up at a gas station"],
    band: 2,
    tags: ["transport"],
    trap: "דלק בארה״ב = gas, תחנת דלק = gas station. בבריטניה petrol / petrol station. 'benzine' לא בשימוש באנגלית.",
  },
  {
    id: "v-tr-forecast",
    word: "forecast",
    pos: "n",
    he: "תחזית",
    def: "a report that says what the weather will probably be like",
    examples: ["The forecast says it'll rain all weekend.", "Check the forecast before we plan the hike."],
    cloze: "According to the ___, tomorrow will be sunny and warm.",
    collocations: ["the weather forecast", "check the forecast", "the forecast says"],
    band: 2,
    tags: ["weather"],
    colloc: { frame: "Let me ___ the forecast before we book the boat trip.", answer: "check", options: ["check", "look", "control"], whyHe: "בודקים תחזית = check the forecast. look צריך at, control = לשלוט." },
  },
  {
    id: "v-tr-storm",
    word: "storm",
    pos: "n",
    he: "סערה",
    def: "very bad weather with strong wind and rain",
    examples: ["A big storm is coming tonight.", "The storm knocked down trees all over the city."],
    cloze: "All flights were canceled because of the ___.",
    collocations: ["a heavy storm", "a storm is coming", "thunderstorm"],
    band: 1,
    tags: ["weather"],
  },
  {
    id: "v-tr-breeze",
    word: "breeze",
    pos: "n",
    he: "רוח קלה, בריזה",
    def: "a light, pleasant wind",
    examples: ["There's a nice breeze coming from the sea.", "The breeze made the heat much easier to handle."],
    cloze: "It's hot, but there's a cool ___ on the balcony.",
    collocations: ["a light breeze", "a cool breeze", "a sea breeze"],
    band: 3,
    tags: ["weather"],
  },
  {
    id: "v-tr-shade",
    word: "shade",
    pos: "n",
    he: "צל",
    def: "a cool, darker area where the sun does not reach",
    examples: ["Let's sit in the shade, it's too hot.", "There's no shade on this beach at all."],
    cloze: "The kids played under the trees, in the ___.",
    collocations: ["in the shade", "find some shade", "sit in the shade"],
    band: 2,
    tags: ["weather"],
    trap: "צל שיושבים בו = shade (in the shade). צל של גוף מסוים = shadow (my shadow). לא 'sit in the shadow'.",
    colloc: { frame: "It's 35 degrees, let's find some ___.", answer: "shade", options: ["shade", "shadow", "cover"], whyHe: "מקום מוצל = shade. shadow = צללית של גוף." },
  },
  {
    id: "v-tr-coast",
    word: "coast",
    pos: "n",
    he: "חוף, קו החוף",
    def: "the land next to the sea",
    examples: ["We drove along the coast for three days.", "The town is on the west coast of the island."],
    cloze: "The road follows the ___ and the views are amazing.",
    collocations: ["on the coast", "along the coast", "the west coast"],
    band: 3,
    tags: ["nature"],
    trap: "coast = קו החוף, האזור ליד הים (on the coast). beach = החוף שהולכים אליו לשחות (go to the beach).",
  },
  {
    id: "v-tr-valley",
    word: "valley",
    pos: "n",
    he: "עמק",
    def: "a low area of land between hills or mountains",
    examples: ["The village sits in a green valley.", "We walked down into the valley to the river."],
    cloze: "From the top, you can see the whole ___ below.",
    collocations: ["a deep valley", "down in the valley", "a river valley"],
    band: 3,
    tags: ["nature"],
  },
  {
    id: "v-tr-hill",
    word: "hill",
    pos: "n",
    he: "גבעה",
    def: "a high area of land, smaller than a mountain",
    examples: ["The old town is built on a hill.", "We climbed the hill to watch the sunset."],
    cloze: "There's a small church at the top of the ___.",
    collocations: ["climb a hill", "on top of a hill", "a steep hill"],
    band: 1,
    tags: ["nature"],
  },
  {
    id: "v-tr-path",
    word: "path",
    pos: "n",
    he: "שביל",
    def: "a narrow way for walking, especially in the countryside",
    examples: ["Follow the path along the river.", "The path to the waterfall is easy, about an hour."],
    cloze: "Stay on the ___, the rocks are slippery.",
    collocations: ["follow the path", "a narrow path", "a walking path"],
    band: 2,
    tags: ["nature"],
    trap: "שביל להליכה = path (או trail). way = דרך במובן כללי, או הכיוון (Which way?). road = כביש.",
  },
  {
    id: "v-tr-countryside",
    word: "countryside",
    pos: "n",
    he: "אזור כפרי, טבע",
    def: "land outside towns and cities, with fields, farms, and villages",
    examples: ["We spent the weekend in the countryside.", "The countryside around the city is beautiful in spring."],
    cloze: "I grew up in the ___, far from any big city.",
    collocations: ["in the countryside", "the open countryside", "a trip to the countryside"],
    band: 2,
    tags: ["nature"],
    trap: "'לצאת לטבע' = go to the countryside / get out into nature. שימו לב: nature בלי the, 'the nature' זו טעות נפוצה.",
    colloc: { frame: "We love spending weekends ___ the countryside.", answer: "in", options: ["in", "on", "at"], whyHe: "in the countryside = בכפר, בטבע." },
  },
  {
    id: "v-tr-pollution",
    word: "pollution",
    pos: "n",
    he: "זיהום",
    def: "damage to air, water, or land caused by harmful substances",
    examples: ["Air pollution is a big problem in the city.", "The river is full of pollution from the factories."],
    cloze: "Fewer cars would mean less ___ in the city center.",
    collocations: ["air pollution", "reduce pollution", "cause pollution"],
    band: 2,
    tags: ["nature"],
    trap: "pollution לא ספיר: אין pollutions. זיהום אוויר = air pollution. הפועל: pollute.",
    colloc: { frame: "The new buses will help ___ pollution in the city.", answer: "reduce", options: ["reduce", "shrink", "fall"], whyHe: "מפחיתים זיהום = reduce pollution." },
  },
  {
    id: "v-tr-litter",
    word: "litter",
    pos: "n",
    he: "אשפה (שנזרקה ברחוב)",
    def: "paper, bottles, and other trash left lying on the ground in public places",
    examples: ["The beach was covered in litter after the holiday.", "Please don't leave any litter on the trail."],
    cloze: "Volunteers picked up ___ along the river all morning.",
    collocations: ["pick up litter", "drop litter", "litter bin"],
    band: 3,
    tags: ["nature"],
    trap: "litter = לכלוך שנזרק בשטח ציבורי (לא ספיר). garbage / trash = אשפה בפח. הפועל to litter = ללכלך.",
  },
  {
    id: "v-tr-wildlife",
    word: "wildlife",
    pos: "n",
    he: "חיות בר",
    def: "animals and birds that live in natural conditions",
    examples: ["The park is full of wildlife, including deer and eagles.", "Tourists come here to see the wildlife."],
    cloze: "Don't feed the ___, it's bad for the animals.",
    collocations: ["local wildlife", "protect wildlife", "wildlife park"],
    band: 3,
    tags: ["nature"],
    trap: "wildlife לא ספיר ובלי ריבוי: אין wildlifes. 'wild animals' תקין, אבל wildlife הוא המונח הכללי.",
  },
  {
    id: "v-tr-sidewalk",
    word: "sidewalk",
    pos: "n",
    he: "מדרכה",
    def: "the path at the side of a street where people walk",
    examples: ["Bikes aren't allowed on the sidewalk.", "The sidewalks were full of tables from the cafes."],
    cloze: "Walk on the ___, not in the road!",
    collocations: ["on the sidewalk", "along the sidewalk"],
    band: 2,
    tags: ["city"],
    trap: "מדרכה = sidewalk (ארה״ב) / pavement (בריטניה). בארה״ב pavement = האספלט של הכביש.",
  },
  {
    id: "v-tr-itinerary",
    word: "itinerary",
    pos: "n",
    he: "מסלול טיול, תוכנית נסיעה",
    def: "a detailed plan of a journey: where you go and when",
    examples: ["Our itinerary includes three days in Kyoto.", "The travel agent sent us the full itinerary by email."],
    cloze: "According to our ___, we're in Rome on Tuesday.",
    collocations: ["plan an itinerary", "a detailed itinerary", "travel itinerary"],
    band: 4,
    tags: ["travel"],
  },
  {
    id: "v-tr-layover",
    word: "layover",
    pos: "n",
    he: "עצירת ביניים (בטיסה)",
    def: "a short stop between flights before you continue your journey",
    examples: ["We have a six-hour layover in Istanbul.", "The layover was long enough to leave the airport."],
    cloze: "Is the flight direct, or is there a ___ somewhere?",
    collocations: ["a long layover", "a layover in", "an overnight layover"],
    band: 4,
    tags: ["travel"],
    trap: "עצירת ביניים = layover (ארה״ב) / stopover (בריטניה, או עצירה ארוכה). connection = טיסת ההמשך עצמה.",
  },
  {
    id: "v-tr-detour",
    word: "detour",
    pos: "n",
    he: "דרך עוקפת, מעקף",
    def: "a longer way that you take to avoid a problem on the usual road",
    examples: ["There were roadworks, so we had to take a detour.", "The detour added forty minutes to our trip."],
    cloze: "The bridge was closed, so we took a ___ through the villages.",
    collocations: ["take a detour", "a long detour", "make a detour"],
    band: 4,
    tags: ["transport"],
  },
  {
    id: "v-tr-accommodation",
    word: "accommodation",
    pos: "n",
    he: "מקום לינה",
    def: "a place to stay when you are traveling, like a hotel or apartment",
    examples: ["Accommodation in the city center is expensive.", "We haven't found accommodation for the first night yet."],
    cloze: "The price includes flights and ___, but not food.",
    collocations: ["find accommodation", "book accommodation", "cheap accommodation"],
    band: 3,
    tags: ["travel"],
    trap: "accommodation לא ספיר: לא 'an accommodation'. בדיבור אפשר גם a place to stay.",
  },
  {
    id: "v-tr-weather",
    word: "weather",
    pos: "n",
    he: "מזג אוויר",
    def: "the conditions outside: sun, rain, wind, and temperature",
    examples: ["What's the weather like in Berlin in March?", "The weather was terrible, so we stayed inside."],
    cloze: "The ___ is perfect today, let's go to the beach.",
    collocations: ["good weather", "bad weather", "What's the weather like?"],
    band: 1,
    tags: ["weather"],
    trap: "weather לא ספיר ובלי a: 'a nice weather' זו טעות, אומרים nice weather. וגם: 'חם לי' = I'm hot, 'חם בחוץ' = It's hot / the weather is hot.",
    colloc: { frame: "What's the ___ like in Rome in November?", answer: "weather", options: ["weather", "climate", "whether"], whyHe: "מזג אוויר של יום או תקופה = weather. climate = אקלים לאורך שנים." },
  },
  {
    id: "v-tr-vacation",
    word: "vacation",
    pos: "n",
    he: "חופשה",
    def: "a period of time when you do not work and often travel somewhere",
    examples: ["We're going on vacation in August.", "I need a vacation, I'm exhausted."],
    cloze: "He's on ___ in Thailand until the end of the month.",
    collocations: ["go on vacation", "be on vacation", "a summer vacation"],
    band: 1,
    tags: ["travel"],
    trap: "חופשה = vacation (ארה״ב) / holiday (בריטניה). 'בחופשה' = on vacation, לא in vacation.",
    colloc: { frame: "She's ___ vacation until next Monday.", answer: "on", options: ["on", "in", "at"], whyHe: "on vacation / on holiday = בחופשה." },
  },
  {
    id: "v-tr-drought",
    word: "drought",
    pos: "n",
    he: "בצורת",
    def: "a long period with no rain, when there is not enough water",
    examples: ["The drought lasted three years and the lake almost disappeared.", "Farmers lost most of their crops in the drought."],
    cloze: "After months without rain, the region is in a serious ___.",
    collocations: ["a severe drought", "suffer from drought", "years of drought"],
    band: 4,
    tags: ["nature"],
  },

  // ---------- adjectives & adverbs ----------
  {
    id: "v-tr-crowded",
    word: "crowded",
    pos: "adj",
    he: "צפוף, הומה אדם",
    def: "full of people",
    examples: ["The market was so crowded we couldn't move.", "The beach gets crowded on weekends."],
    cloze: "The train was really ___, I had to stand the whole way.",
    collocations: ["a crowded street", "get crowded", "crowded with tourists"],
    band: 1,
    tags: ["city"],
    trap: "מקום מלא אנשים = crowded, לא 'crowdy'. full מתאר גם דברים אחרים. שם העצם: crowd (קהל).",
    colloc: { frame: "The old town was ___ with tourists in August.", answer: "crowded", options: ["crowded", "full", "many"], whyHe: "crowded with tourists = הומה תיירים. full מקבל of, לא with." },
  },
  
  {
    id: "v-tr-humid",
    word: "humid",
    pos: "adj",
    he: "לח",
    def: "(of weather or air) warm and wet",
    examples: ["Tel Aviv is really humid in August.", "It's not the heat, it's the humid air that's hard."],
    cloze: "It's so ___ that my shirt is wet after five minutes outside.",
    collocations: ["hot and humid", "humid weather", "humidity"],
    band: 2,
    tags: ["weather"],
    trap: "מזג אוויר לח = humid. wet = רטוב או גשום. שם העצם: humidity (לחות).",
  },
  {
    id: "v-tr-mild",
    word: "mild",
    pos: "adj",
    he: "מתון, נעים (מזג אוויר)",
    def: "(of weather) not too hot and not too cold",
    examples: ["Winters here are mild, it rarely snows.", "It was a mild evening, perfect for a walk."],
    cloze: "The weather in October is usually ___, around twenty degrees.",
    collocations: ["a mild winter", "mild weather", "mild temperatures"],
    band: 2,
    tags: ["weather"],
    colloc: { frame: "Lisbon has ___ winters, so you don't need a heavy coat.", answer: "mild", options: ["mild", "soft", "light"], whyHe: "חורף מתון = mild winter. soft ו-light לא מתארים מזג אוויר." },
  },
  {
    id: "v-tr-freezing",
    word: "freezing",
    pos: "adj",
    he: "קפוא, קר מאוד",
    def: "extremely cold",
    examples: ["It's freezing outside, take a coat.", "The water in the lake was freezing."],
    cloze: "Close the window, it's ___ in here!",
    collocations: ["freezing cold", "it's freezing", "freezing temperatures"],
    band: 1,
    tags: ["weather"],
    trap: "freezing כבר אומר 'מאוד קר', לכן לא 'very freezing' אלא absolutely freezing. 'קר לי' = I'm cold / I'm freezing.",
  },
  {
    id: "v-tr-abroad",
    word: "abroad",
    pos: "adv",
    he: "בחו״ל, לחו״ל",
    def: "in or to a foreign country",
    examples: ["She's working abroad this year.", "We usually go abroad in the summer."],
    cloze: "Have you ever lived ___?",
    collocations: ["go abroad", "live abroad", "travel abroad"],
    band: 1,
    tags: ["travel"],
    trap: "abroad הוא תואר פועל, בלי to או in: go abroad, live abroad. 'go to abroad' ו-'in abroad' זו טעות.",
    colloc: { frame: "My sister moved ___ after university.", answer: "abroad", options: ["abroad", "to abroad", "in abroad"], whyHe: "move abroad, בלי מילת יחס." },
  },
  {
    id: "v-tr-direct",
    word: "direct",
    pos: "adj",
    he: "ישיר (טיסה, רכבת)",
    def: "going straight to a place without stopping or changing",
    examples: ["Is there a direct flight to Rome?", "There's no direct train, you change in Lyon."],
    cloze: "I prefer a ___ flight, even if it costs more.",
    collocations: ["a direct flight", "a direct train", "fly direct"],
    band: 2,
    tags: ["transport"],
    colloc: { frame: "Is this a ___ flight or do we stop in Athens?", answer: "direct", options: ["direct", "straight", "directly"], whyHe: "טיסה ישירה = direct flight (או nonstop flight). straight = ישר בכיוון." },
  },
  {
    id: "v-tr-on-time",
    word: "on time",
    pos: "phr",
    he: "בזמן (לפי הלוח)",
    def: "at the planned time, not late",
    examples: ["The train left exactly on time.", "Are we going to arrive on time?"],
    cloze: "For once, the flight was ___, not even a minute late.",
    collocations: ["arrive on time", "leave on time", "right on time"],
    band: 2,
    tags: ["transport"],
    trap: "on time = בזמן המתוכנן, לא באיחור. in time = מספיק מוקדם, לפני שיהיה מאוחר מדי (in time for dinner).",
    colloc: { frame: "We got to the gate just ___ time for boarding.", answer: "in", options: ["in", "on", "at"], whyHe: "just in time = בדיוק בזמן, רגע לפני שהיה מאוחר מדי. on time = לפי לוח הזמנים." },
  },
  {
    id: "v-tr-nearby",
    word: "nearby",
    pos: "adj",
    he: "קרוב, סמוך",
    def: "not far away",
    examples: ["Is there a pharmacy nearby?", "We had dinner at a nearby restaurant."],
    cloze: "Let's find a cafe ___ and wait for the rain to stop.",
    collocations: ["a nearby town", "somewhere nearby", "live nearby"],
    band: 2,
    tags: ["city"],
    trap: "nearby = קרוב, בלי משהו אחריו: Is there a bank nearby? עם שם עצם אחריו: near the hotel (לא nearby the hotel).",
  },
  {
    id: "v-tr-touristy",
    word: "touristy",
    pos: "adj",
    he: "תיירותי (מסחרי מדי)",
    def: "full of tourists and things made for tourists, often in a negative way",
    examples: ["The old port is nice but very touristy.", "We found a small restaurant that wasn't touristy at all."],
    cloze: "The main square is too ___ for me, let's find a quieter area.",
    collocations: ["too touristy", "a touristy area", "touristy restaurants"],
    band: 3,
    tags: ["travel"],
    trap: "touristy (דיבורי, קצת שלילי) = מלא תיירים וחנויות מזכרות. tourist הוא שם עצם: a tourist attraction. 'touristic' נדיר באנגלית.",
  },
  {
    id: "v-tr-lively",
    word: "lively",
    pos: "adj",
    he: "תוסס",
    def: "full of life, energy, and activity",
    examples: ["The neighborhood is lively at night, with bars and music.", "It's a lively little town with a great market."],
    cloze: "This street is really ___ in the evening, full of people and music.",
    collocations: ["a lively city", "lively nightlife", "a lively atmosphere"],
    band: 3,
    tags: ["city"],
  },
  {
    id: "v-tr-peaceful",
    word: "peaceful",
    pos: "adj",
    he: "שקט, שליו",
    def: "quiet and calm, without noise or trouble",
    examples: ["The village was so peaceful after the noise of the city.", "We found a peaceful spot by the lake."],
    cloze: "Early in the morning, the beach is completely ___.",
    collocations: ["a peaceful place", "peaceful and quiet", "a peaceful walk"],
    band: 2,
    tags: ["nature"],
  },
  {
    id: "v-tr-scenic",
    word: "scenic",
    pos: "adj",
    he: "ציורי, עם נוף יפה",
    def: "having beautiful views of nature",
    examples: ["We took the scenic route along the coast.", "The train ride through the mountains is very scenic."],
    cloze: "It's longer, but the coastal road is much more ___.",
    collocations: ["the scenic route", "a scenic drive", "scenic views"],
    band: 4,
    tags: ["nature"],
    colloc: { frame: "Let's take the ___ route, we're not in a hurry.", answer: "scenic", options: ["scenic", "scenery", "landscape"], whyHe: "הדרך הנופית = the scenic route. scenery ו-landscape הם שמות עצם." },
  },
  {
    id: "v-tr-windy",
    word: "windy",
    pos: "adj",
    he: "עם רוח חזקה",
    def: "with a lot of wind",
    examples: ["It's too windy to sit outside.", "The coast is always windy in winter."],
    cloze: "It was so ___ that my hat flew away.",
    collocations: ["a windy day", "cold and windy", "windy weather"],
    band: 1,
    tags: ["weather"],
  },
  {
    id: "v-tr-foggy",
    word: "foggy",
    pos: "adj",
    he: "מעורפל",
    def: "with thick fog, so you cannot see far",
    examples: ["It was so foggy we couldn't see the road.", "Mornings in the valley are often foggy."],
    cloze: "Drive slowly, it's very ___ on the mountain road.",
    collocations: ["a foggy morning", "thick fog", "foggy weather"],
    band: 2,
    tags: ["weather"],
  },
  {
    id: "v-tr-chilly",
    word: "chilly",
    pos: "adj",
    he: "קריר, צונן",
    def: "a little cold, in a way that is not comfortable",
    examples: ["It gets chilly at night, bring a sweater.", "The mornings are chilly but the afternoons are warm."],
    cloze: "It's a bit ___ out, do you want a jacket?",
    collocations: ["a chilly evening", "a bit chilly", "a chilly wind"],
    band: 3,
    tags: ["weather"],
    trap: "chilly = קריר במידה לא נעימה (פחות מ-cold). cool = קריר ונעים. chill לבד בדיבור = להירגע (chill out).",
  },
  {
    id: "v-tr-one-way",
    word: "one-way",
    pos: "adj",
    he: "לכיוון אחד, חד-סטרי",
    def: "going in one direction only; (of a ticket) for going but not coming back",
    examples: ["I bought a one-way ticket to London.", "This is a one-way street, you can't turn here."],
    cloze: "A ___ ticket is 40 dollars, round trip is 70.",
    collocations: ["a one-way ticket", "a one-way street", "one-way traffic"],
    band: 2,
    tags: ["transport"],
    trap: "כרטיס לכיוון אחד = one-way ticket (בבריטניה single). רחוב חד-סטרי = one-way street. לא 'one direction ticket'.",
  },
  {
    id: "v-tr-eco-friendly",
    word: "eco-friendly",
    pos: "adj",
    he: "ידידותי לסביבה",
    def: "not harmful to the environment",
    examples: ["The hotel is eco-friendly: solar power and no plastic.", "Trains are more eco-friendly than planes."],
    cloze: "We chose an ___ tour company that uses electric boats.",
    collocations: ["eco-friendly hotel", "eco-friendly products", "environmentally friendly"],
    band: 3,
    tags: ["nature"],
  },
];
