import type { VocabItem } from "@/lib/types";

export const WORK_STUDY: VocabItem[] = [
  // ---------- Band 1 ----------
  {
    id: "v-wk-hire",
    word: "hire",
    pos: "v",
    he: "לקבל לעבודה, לגייס",
    def: "to give someone a job",
    examples: ["They hired two new developers last month.", "We're hiring, so send me your resume."],
    cloze: "The company ___ me a week after the interview.",
    clozeAnswer: "hired",
    collocations: ["hire someone", "hire a new employee", "we're hiring"],
    band: 1,
    tags: ["work", "career"],
    trap: "hire = לקבל לעבודה. אל תבלבלו עם rent (לשכור דירה או רכב). באנגלית אמריקאית hire הוא כמעט תמיד על אנשים.",
    colloc: { frame: "We need to ___ someone for the front desk.", answer: "hire", options: ["hire", "rent", "take"], whyHe: "מגייסים אדם = hire; rent זה לשכור חפץ." },
  },
  {
    id: "v-wk-fire",
    word: "fire",
    pos: "v",
    he: "לפטר",
    def: "to make someone leave their job",
    examples: ["He was fired for being late every day.", "You can't fire someone without a reason."],
    cloze: "She got ___ after the argument with her boss.",
    clozeAnswer: "fired",
    collocations: ["get fired", "fire someone", "fired from a job"],
    band: 1,
    tags: ["work"],
    trap: "'פיטרו אותי' = I was fired / I got fired, לא they fired me out. פוטר בגלל קיצוצים (לא באשמתך) = get laid off.",
    colloc: { frame: "He ___ fired last week and is looking for a new job.", answer: "got", options: ["got", "made", "became"], whyHe: "get fired / be fired." },
  },
  {
    id: "v-wk-apply-for",
    word: "apply for",
    pos: "phr",
    he: "להגיש מועמדות ל-",
    def: "to officially ask for a job, a place at a university, etc.",
    examples: ["I applied for three jobs this week.", "You should apply for the marketing position."],
    cloze: "She ___ a scholarship and got it.",
    clozeAnswer: "applied for",
    collocations: ["apply for a job", "apply for a position", "apply to a company"],
    band: 1,
    tags: ["work", "career"],
    trap: "apply FOR a job / a position, apply TO a company / university. לא apply to a job. 'שלחתי קורות חיים' = I applied.",
    colloc: { frame: "Did you ___ for the job at the hospital?", answer: "apply", options: ["apply", "send", "register"], whyHe: "מגישים מועמדות = apply for." },
  },
  {
    id: "v-wk-cancel",
    word: "cancel",
    pos: "v",
    he: "לבטל",
    def: "to decide that a planned event will not happen",
    examples: ["The meeting was canceled at the last minute.", "I had to cancel my dentist appointment."],
    cloze: "They ___ the flight because of the storm.",
    clozeAnswer: "canceled",
    accept: ["cancelled"],
    collocations: ["cancel a meeting", "cancel an order", "canceled at the last minute"],
    band: 1,
    tags: ["work"],
    trap: "באנגלית אמריקאית: canceled (L אחת). ואל תבלבלו: cancel = לבטל; postpone = לדחות למועד אחר.",
  },
  {
    id: "v-wk-take-an-exam",
    word: "take an exam",
    pos: "phr",
    he: "להיבחן, לעשות מבחן",
    def: "to do an official test",
    examples: ["I'm taking an exam in English on Thursday.", "You can take the exam again in June."],
    cloze: "I can't come tonight, I ___ tomorrow morning.",
    clozeAnswer: "take an exam",
    accept: ["have an exam", "take a test"],
    collocations: ["take an exam", "take a test", "take the final"],
    band: 1,
    tags: ["study"],
    trap: "'לעשות מבחן' = take an exam, לא make an exam ולא do an exam. המורה נותן מבחן = give an exam.",
    colloc: { frame: "Students ___ the final exam in July.", answer: "take", options: ["take", "make", "do"], whyHe: "נבחנים = take an exam." },
  },
  {
    id: "v-wk-pass",
    word: "pass",
    pos: "v",
    he: "לעבור (מבחן)",
    def: "to succeed in a test or exam",
    examples: ["I passed my driving test on the second try.", "Only half the class passed the exam."],
    cloze: "Good news, I ___ the math test!",
    clozeAnswer: "passed",
    collocations: ["pass an exam", "pass a test", "pass with a high grade"],
    band: 1,
    tags: ["study"],
    trap: "'לעבור מבחן' = pass an exam, לא succeed the exam. 'עברתי בקושי' = I barely passed.",
  },
  {
    id: "v-wk-fail",
    word: "fail",
    pos: "v",
    he: "להיכשל",
    def: "to not pass a test, or to not succeed",
    examples: ["He failed the exam by two points.", "If you don't practice, you'll fail."],
    cloze: "She ___ her driving test three times before she passed.",
    clozeAnswer: "failed",
    collocations: ["fail an exam", "fail to do something", "fail the course"],
    band: 1,
    tags: ["study"],
    trap: "'נכשלתי במבחן' = I failed the exam (בלי in). fail to do = לא להצליח לעשות.",
    colloc: { frame: "He ___ the exam and has to take it again.", answer: "failed", options: ["failed", "fell", "lost"], whyHe: "נכשל במבחן = failed the exam; fell = נפל פיזית." },
  },
  {
    id: "v-wk-study-for",
    word: "study for",
    pos: "phr",
    he: "ללמוד למבחן",
    def: "to prepare for a test by reading and practicing",
    examples: ["I'm studying for my history exam tonight.", "Did you study for the test?"],
    cloze: "I can't go out, I have to ___ my exam.",
    clozeAnswer: "study for",
    collocations: ["study for an exam", "study hard", "study all night"],
    band: 1,
    tags: ["study"],
    trap: "'ללמוד למבחן' = study for a test, לא learn for a test. learn = לרכוש ידע חדש; study = לשבת וללמוד.",
    colloc: { frame: "She stayed up all night to ___ for the exam.", answer: "study", options: ["study", "learn", "read"], whyHe: "לומדים למבחן = study for." },
  },
  {
    id: "v-wk-responsible-for",
    word: "responsible for",
    pos: "phr",
    he: "אחראי על",
    def: "having the job or duty of doing or looking after something",
    examples: ["I'm responsible for the company's social media.", "Who is responsible for ordering supplies?"],
    cloze: "As a manager, you're ___ your team's results.",
    clozeAnswer: "responsible for",
    collocations: ["responsible for something", "responsible for doing", "be held responsible"],
    band: 1,
    tags: ["work"],
    trap: "אחראי על = responsible FOR, לא responsible on. אחרי for בא שם עצם או ing: responsible for training.",
    colloc: { frame: "She is responsible ___ training the new employees.", answer: "for", options: ["for", "on", "of"], whyHe: "responsible for, גם כשבעברית זה 'על'." },
  },
  {
    id: "v-wk-work-for",
    word: "work for",
    pos: "phr",
    he: "לעבוד ב- (חברה)",
    def: "to be employed by a company or person",
    examples: ["She works for a big tech company.", "I worked for my uncle for two summers."],
    cloze: "My brother ___ Intel in Haifa.",
    clozeAnswer: "works for",
    accept: ["works at"],
    collocations: ["work for a company", "work at Google", "work in marketing"],
    band: 1,
    tags: ["work"],
    trap: "'אני עובד בגוגל' = I work AT Google / FOR Google, לא work in Google. work in = תחום או עיר (work in marketing, work in Tel Aviv).",
    colloc: { frame: "I've worked ___ this company for six years.", answer: "for", options: ["for", "in", "by"], whyHe: "work for/at a company; work in a field or a city." },
  },
  
  {
    id: "v-wk-earn",
    word: "earn",
    pos: "v",
    he: "להרוויח (כסף)",
    def: "to get money for the work you do",
    examples: ["She earns about 15,000 shekels a month.", "How much do teachers earn here?"],
    cloze: "He ___ good money as an electrician.",
    clozeAnswer: "earns",
    accept: ["makes"],
    collocations: ["earn money", "earn a salary", "earn a living"],
    band: 1,
    tags: ["work"],
    trap: "להרוויח כסף בעבודה = earn (או make); win = לזכות במשחק או בהגרלה. 'הרווחתי 100 שקל היום' = I earned 100 shekels today.",
    colloc: { frame: "How much do you ___ in your new job?", answer: "earn", options: ["earn", "win", "gain"], whyHe: "מרוויחים משכורת = earn; win = לזכות." },
  },
  {
    id: "v-wk-boss",
    word: "boss",
    pos: "n",
    he: "בוס, מנהל ישיר",
    def: "the person who gives you orders at work",
    examples: ["My boss asked me to stay late tonight.", "She's a good boss, she listens to people."],
    cloze: "I need to ask my ___ for a day off.",
    collocations: ["my boss", "talk to your boss", "be your own boss"],
    band: 1,
    tags: ["work"],
    trap: "boss = המנהל הישיר שלך, מילה יומיומית. manager = תפקיד רשמי. במייל רשמי כתבו manager, בשיחה boss.",
  },
  {
    id: "v-wk-employee",
    word: "employee",
    pos: "n",
    he: "עובד, שכיר",
    def: "a person who is paid to work for a company or person",
    examples: ["The company has about 200 employees.", "Every employee gets a bonus in December."],
    cloze: "She's been an ___ here since 2019.",
    collocations: ["full-time employee", "new employee", "employee of the month"],
    band: 1,
    tags: ["work"],
    trap: "employee = עובד; employer = מעסיק. שימו לב להטעמה: employEE. worker נשמע יותר 'פועל'.",
    colloc: { frame: "The company hired twenty new ___ this year.", answer: "employees", options: ["employees", "employers", "employments"], whyHe: "העובדים = employees; employer = המעסיק." },
  },
  {
    id: "v-wk-schedule",
    word: "schedule",
    pos: "n",
    he: "לוח זמנים, לו״ז",
    def: "a plan that shows when things will happen",
    examples: ["My schedule is full until Thursday.", "Let's check the schedule and find a time."],
    cloze: "What does your ___ look like next week?",
    collocations: ["busy schedule", "tight schedule", "on schedule", "behind schedule"],
    band: 1,
    tags: ["work"],
    trap: "'הלו״ז שלי' = my schedule. 'לפי הלו״ז' = on schedule; 'בפיגור' = behind schedule. באמריקאית מבטאים SKED-jool.",
    colloc: { frame: "The project is ___ schedule, so we'll finish late.", answer: "behind", options: ["behind", "after", "under"], whyHe: "בפיגור בלו״ז = behind schedule." },
  },
  {
    id: "v-wk-interview",
    word: "interview",
    pos: "n",
    he: "ראיון (עבודה)",
    def: "a meeting where someone asks you questions to see if you are right for a job",
    examples: ["I have a job interview on Monday.", "The interview went really well."],
    cloze: "She has an ___ for a nursing job tomorrow.",
    collocations: ["job interview", "have an interview", "interview for a position"],
    band: 1,
    tags: ["work", "career"],
    trap: "'ראיון עבודה' = job interview (job לפני!). 'הייתי בראיון' = I had an interview / I went to an interview.",
    colloc: { frame: "I ___ an interview at the bank on Sunday.", answer: "have", options: ["have", "make", "pass"], whyHe: "have an interview; pass an interview אומרים רק אחרי שעברת." },
  },
  {
    id: "v-wk-task",
    word: "task",
    pos: "n",
    he: "משימה",
    def: "a piece of work that you have to do",
    examples: ["My first task today is answering emails.", "This task will take about an hour."],
    cloze: "Finish this ___ before you start the next one.",
    collocations: ["complete a task", "simple task", "daily tasks"],
    band: 1,
    tags: ["work"],
    trap: "task = משימה בעבודה. mission = משימה צבאית או גדולה. 'יש לי הרבה משימות' = I have a lot of tasks / a lot to do.",
  },
  {
    id: "v-wk-customer",
    word: "customer",
    pos: "n",
    he: "לקוח (בחנות)",
    def: "a person who buys something from a store or business",
    examples: ["The customer wanted a refund.", "We get about 100 customers a day."],
    cloze: "A ___ called to complain about the delivery.",
    collocations: ["customer service", "regular customer", "customer complaint"],
    band: 1,
    tags: ["work"],
    trap: "customer = לקוח שקונה מוצר או שירות (חנות, מסעדה). client = לקוח של איש מקצוע (עורך דין, סוכנות). 'שירות לקוחות' = customer service.",
    colloc: { frame: "She works in ___ service at the phone company.", answer: "customer", options: ["customer", "client", "buyer"], whyHe: "customer service הוא צירוף קבוע." },
  },
  {
    id: "v-wk-salary",
    word: "salary",
    pos: "n",
    he: "משכורת",
    def: "the money you get every month for your job",
    examples: ["The salary is good, but the hours are long.", "What salary are you looking for?"],
    cloze: "My ___ goes into my bank account on the 10th.",
    collocations: ["high salary", "monthly salary", "salary increase"],
    band: 1,
    tags: ["work"],
    trap: "salary = משכורת חודשית קבועה; wage = שכר לפי שעה. 'משכורת גבוהה' = high salary, לא big salary.",
    colloc: { frame: "They offered him a ___ salary than his old job.", answer: "higher", options: ["higher", "bigger", "more"], whyHe: "high / higher salary." },
  },
  {
    id: "v-wk-skill",
    word: "skill",
    pos: "n",
    he: "מיומנות, כישור",
    def: "the ability to do something well",
    examples: ["Communication skills are important in every job.", "I want to improve my English skills."],
    cloze: "This course teaches you basic computer ___.",
    clozeAnswer: "skills",
    collocations: ["communication skills", "improve your skills", "learn a new skill"],
    band: 1,
    tags: ["work", "career"],
    trap: "skill = כישור, יכולת. 'לשפר כישורים' = improve / develop skills. 'כישורים חברתיים' = people skills.",
  },
  {
    id: "v-wk-experience",
    word: "experience",
    pos: "n",
    he: "ניסיון",
    def: "knowledge or skill that you get from doing a job for a time",
    examples: ["Do you have any experience in sales?", "I have five years of experience as a teacher."],
    cloze: "The job requires three years of ___ in marketing.",
    collocations: ["work experience", "years of experience", "gain experience"],
    band: 1,
    tags: ["work", "career"],
    trap: "ניסיון בעבודה = experience, לא ספיר: I have a lot of experience (בלי a, בלי s). 'an experience' = חוויה.",
    colloc: { frame: "I have a lot of ___ working with children.", answer: "experience", options: ["experience", "experiences", "experiment"], whyHe: "ניסיון = experience (לא ספיר); experiment = ניסוי." },
  },
  {
    id: "v-wk-busy",
    word: "busy",
    pos: "adj",
    he: "עסוק",
    def: "having a lot of things to do",
    examples: ["I'm really busy this week.", "The office is busy in the mornings."],
    cloze: "Sorry, I'm too ___ to talk right now.",
    collocations: ["busy with something", "busy day", "keep busy"],
    band: 1,
    tags: ["work"],
    trap: "עסוק ב- = busy WITH (busy with a project) או busy + ing (busy writing). לא busy in.",
    colloc: { frame: "She's busy ___ the report right now.", answer: "with", options: ["with", "in", "on"], whyHe: "busy with something." },
  },
  {
    id: "v-wk-full-time",
    word: "full-time",
    pos: "adj",
    he: "במשרה מלאה",
    def: "working all the normal hours of the week",
    examples: ["I'm looking for a full-time job.", "She works full-time and studies at night."],
    cloze: "It's a ___ position, forty hours a week.",
    collocations: ["full-time job", "work full-time", "full-time student"],
    band: 1,
    tags: ["work"],
  },
  {
    id: "v-wk-part-time",
    word: "part-time",
    pos: "adj",
    he: "במשרה חלקית",
    def: "working only some of the normal hours",
    examples: ["He has a part-time job at a cafe.", "Many students work part-time."],
    cloze: "I work ___, only three days a week.",
    collocations: ["part-time job", "work part-time", "part-time student"],
    band: 1,
    tags: ["work"],
    trap: "'חצי משרה' = part-time (לא half job). 'משרה מלאה' = full-time.",
  },
  {
    id: "v-wk-on-time",
    word: "on time",
    pos: "adv",
    he: "בזמן",
    def: "at the correct time, not late",
    examples: ["Please be on time for the meeting.", "The report was finished on time."],
    cloze: "The bus is never ___ in the morning.",
    collocations: ["be on time", "arrive on time", "finish on time"],
    band: 1,
    tags: ["work"],
    trap: "on time = בדיוק בזמן, לא באיחור; in time = בזמן, לפני שמאוחר מדי (in time for dinner). 'הגעתי בזמן לפגישה' = I was on time.",
  },

  // ---------- Band 2 ----------
  {
    id: "v-wk-quit",
    word: "quit",
    pos: "v",
    he: "להתפטר, לעזוב",
    def: "to leave your job or stop doing something",
    examples: ["I quit my job last year and started my own business.", "Don't quit now, you're almost done."],
    cloze: "After ten years at the bank, he ___ and moved to Berlin.",
    collocations: ["quit a job", "quit smoking", "quit doing something"],
    band: 2,
    tags: ["work", "career"],
    trap: "quit לא משתנה בעבר: quit, quit, quit. וגם: quit + ing (quit smoking), לא quit to smoke.",
  },
  {
    id: "v-wk-retire",
    word: "retire",
    pos: "v",
    he: "לפרוש לפנסיה",
    def: "to stop working because you have reached a certain age",
    examples: ["My dad retired at 67.", "She wants to retire early and travel."],
    cloze: "He plans to ___ when he turns 65.",
    collocations: ["retire early", "retire at 65", "retire from work"],
    band: 2,
    tags: ["work", "career"],
    trap: "retire = לפרוש לגמלאות, לא סתם לעזוב עבודה (זה quit / resign). 'הוא יצא לפנסיה' = He retired.",
  },
  {
    id: "v-wk-attend",
    word: "attend",
    pos: "v",
    he: "להשתתף ב-, להיות נוכח",
    def: "to go to a meeting, class, or event",
    examples: ["I have to attend a meeting at ten.", "Only twenty people attended the lecture."],
    cloze: "All employees must ___ the safety training.",
    collocations: ["attend a meeting", "attend a course", "attend school"],
    band: 2,
    tags: ["work", "study"],
    trap: "attend a meeting (בלי to או in). לא attend to the meeting. 'להיות בפגישה' = attend the meeting.",
    colloc: { frame: "Can you ___ the meeting on Thursday?", answer: "attend", options: ["attend", "assist", "participate"], whyHe: "attend a meeting; assist = לעזור (מלכודת!); participate צריך in." },
  },
  {
    id: "v-wk-graduate",
    word: "graduate",
    pos: "v",
    he: "לסיים לימודים, לקבל תואר",
    def: "to finish your studies at a school or university",
    examples: ["She graduated from Tel Aviv University in 2020.", "I graduate next summer."],
    cloze: "He ___ from high school and joined the army.",
    clozeAnswer: "graduated",
    collocations: ["graduate from university", "graduate with a degree in", "recent graduate"],
    band: 2,
    tags: ["study", "career"],
    trap: "graduate FROM university (עם from). 'סיימתי תואר' = I graduated. graduate כשם עצם = בוגר.",
  },
  {
    id: "v-wk-cheat",
    word: "cheat",
    pos: "v",
    he: "לרמות, להעתיק",
    def: "to act dishonestly to win or pass",
    examples: ["Two students were caught cheating on the test.", "He cheats at cards every time."],
    cloze: "If you ___ on the exam, you'll fail the course.",
    collocations: ["cheat on a test", "cheat at a game", "get caught cheating"],
    band: 2,
    tags: ["study"],
    trap: "'להעתיק במבחן' = cheat ON a test, לא copy in the test. cheat on someone = לבגוד.",
    colloc: { frame: "She was caught cheating ___ the final exam.", answer: "on", options: ["on", "in", "at"], whyHe: "cheat on a test; cheat at a game." },
  },
  {
    id: "v-wk-in-charge-of",
    word: "in charge of",
    pos: "phr",
    he: "אחראי על, מנהל",
    def: "having control of or responsibility for something",
    examples: ["She's in charge of the whole project.", "Who's in charge here?"],
    cloze: "Dan is ___ the new office in Haifa.",
    clozeAnswer: "in charge of",
    accept: ["responsible for"],
    collocations: ["be in charge of", "put someone in charge", "the person in charge"],
    band: 2,
    tags: ["work"],
    trap: "in charge OF (לא in charge on). 'מי אחראי כאן?' = Who's in charge?",
    colloc: { frame: "He was put in ___ of the sales team.", answer: "charge", options: ["charge", "control", "responsible"], whyHe: "in charge of = אחראי על." },
  },
  {
    id: "v-wk-get-promoted",
    word: "get promoted",
    pos: "phr",
    he: "לקבל קידום",
    def: "to be given a higher position at work",
    examples: ["She got promoted to team leader last month.", "If you work hard, you'll get promoted."],
    cloze: "He ___ to manager after only one year.",
    clozeAnswer: "got promoted",
    accept: ["was promoted"],
    collocations: ["get promoted to", "be promoted", "promoted to manager"],
    band: 2,
    tags: ["work", "career"],
    trap: "'קיבלתי קידום' = I got promoted / I got a promotion, לא I got a promote. promoted TO a position.",
  },
  {
    id: "v-wk-train",
    word: "train",
    pos: "v",
    he: "להכשיר, להתאמן",
    def: "to teach someone the skills for a job, or to practice for a sport",
    examples: ["We train all new employees for two weeks.", "She's training to be a nurse."],
    cloze: "The company will ___ you on the new software.",
    collocations: ["train new staff", "train to be", "training course"],
    band: 2,
    tags: ["work", "study"],
    trap: "train = להכשיר עובד / להתאמן. 'הכשרה' = training. 'להכשיר מישהו' = train someone, לא make him a course.",
  },
  {
    id: "v-wk-submit",
    word: "submit",
    pos: "v",
    he: "להגיש",
    def: "to give a document or work to someone official",
    examples: ["Please submit your application by Friday.", "I submitted the report this morning."],
    cloze: "You must ___ the form online.",
    collocations: ["submit an application", "submit a report", "submit by a deadline"],
    band: 2,
    tags: ["work", "study"],
    trap: "submit = להגיש (רשמי, אונליין); hand in = להגיש (בכיתה, יומיומי). 'להגיש קורות חיים' = submit / send your resume.",
  },
  {
    id: "v-wk-sign-up-for",
    word: "sign up for",
    pos: "phr",
    he: "להירשם ל-",
    def: "to put your name on a list for a course or activity",
    examples: ["I signed up for a photography course.", "You can sign up for the newsletter online."],
    cloze: "She ___ Spanish classes at the community center.",
    clozeAnswer: "signed up for",
    accept: ["registered for", "enrolled in"],
    collocations: ["sign up for a course", "sign up online", "sign up for a class"],
    band: 2,
    tags: ["study"],
    trap: "'נרשמתי לקורס' = I signed up FOR a course / registered FOR, לא registered to.",
    colloc: { frame: "I want to sign ___ for the yoga class.", answer: "up", options: ["up", "in", "on"], whyHe: "sign up for = להירשם; sign in = להתחבר לאתר." },
  },
  {
    id: "v-wk-take-a-day-off",
    word: "take a day off",
    pos: "phr",
    he: "לקחת יום חופש",
    def: "to not go to work for a day",
    examples: ["I'm taking a day off on Thursday.", "Can I take a day off next week?"],
    cloze: "She ___ to go to her son's ceremony.",
    clozeAnswer: "took a day off",
    accept: ["took the day off"],
    collocations: ["take a day off", "take the afternoon off", "a day off"],
    band: 2,
    tags: ["work"],
    trap: "'יום חופש' = a day off. 'לקחת חופש' = take time off / take a day off. 'אני בחופש היום' = I'm off today.",
    colloc: { frame: "I'm taking Friday ___ to go to the wedding.", answer: "off", options: ["off", "free", "out"], whyHe: "take a day off / take Friday off." },
  },
  
  {
    id: "v-wk-manage",
    word: "manage",
    pos: "v",
    he: "לנהל, להצליח (לעשות)",
    def: "to be in charge of people or work; to succeed in doing something hard",
    examples: ["She manages a team of ten people.", "I managed to finish the report before lunch."],
    cloze: "Did you ___ to call the client?",
    collocations: ["manage a team", "manage to do", "manage your time"],
    band: 2,
    tags: ["work"],
    trap: "manage to do = להצליח לעשות (משהו קשה). לא manage doing. 'הצלחתי להגיע' = I managed to get there.",
    colloc: { frame: "We finally ___ to fix the printer.", answer: "managed", options: ["managed", "succeeded", "could"], whyHe: "managed to do; succeeded IN doing." },
  },
  
  {
    id: "v-wk-deadline",
    word: "deadline",
    pos: "n",
    he: "מועד אחרון, דדליין",
    def: "the time by which something must be finished",
    examples: ["The deadline for the project is next Friday.", "We're working late to meet the deadline."],
    cloze: "I have a tight ___ this week, so I can't help.",
    collocations: ["meet a deadline", "miss a deadline", "tight deadline"],
    band: 2,
    tags: ["work", "study"],
    trap: "'לעמוד בדדליין' = meet a deadline; 'לפספס' = miss a deadline. לא stand in the deadline.",
    colloc: { frame: "If we ___ the deadline, the client will cancel.", answer: "miss", options: ["miss", "lose", "pass"], whyHe: "miss a deadline = לפספס דדליין." },
  },
  {
    id: "v-wk-colleague",
    word: "colleague",
    pos: "n",
    he: "עמית לעבודה",
    def: "a person you work with, especially in a profession",
    examples: ["A colleague of mine recommended this restaurant.", "I get along well with my colleagues."],
    cloze: "I'm having lunch with a ___ from the finance team.",
    collocations: ["colleague of mine", "former colleague", "work with colleagues"],
    band: 2,
    tags: ["work"],
    trap: "'חבר לעבודה' = colleague / coworker, לא friend from work (אלא אם הוא באמת חבר). colleague זה מקצועי, לא בהכרח ידיד.",
    colloc: { frame: "A ___ of mine is leaving the company next month.", answer: "colleague", options: ["colleague", "college", "collect"], whyHe: "colleague = עמית; college = מכללה. שימו לב לאיות." },
  },
  {
    id: "v-wk-coworker",
    word: "coworker",
    pos: "n",
    he: "עובד לצידך",
    def: "a person who works with you at the same place",
    examples: ["My coworkers threw me a birthday party.", "She's a coworker, not really a friend."],
    cloze: "One of my ___ is always late.",
    clozeAnswer: "coworkers",
    accept: ["colleagues"],
    collocations: ["my coworkers", "friendly coworkers", "coworkers and managers"],
    band: 2,
    tags: ["work"],
    trap: "coworker (אמריקאי, יומיומי) = colleague (קצת יותר רשמי). שניהם 'חבר לעבודה', בלי friend.",
  },
  {
    id: "v-wk-employer",
    word: "employer",
    pos: "n",
    he: "מעסיק",
    def: "a person or company that pays people to work",
    examples: ["My employer pays for my health insurance.", "The city is the biggest employer in the area."],
    cloze: "Your ___ must give you a contract.",
    collocations: ["previous employer", "large employer", "employer and employee"],
    band: 2,
    tags: ["work"],
    trap: "employER = מעסיק (מי שמשלם); employEE = עובד. 'המעסיק הקודם שלי' = my previous employer.",
  },
  {
    id: "v-wk-promotion",
    word: "promotion",
    pos: "n",
    he: "קידום",
    def: "a move to a higher position at work",
    examples: ["She got a promotion and a bigger office.", "I'm hoping for a promotion this year."],
    cloze: "After the big project, he was given a ___.",
    collocations: ["get a promotion", "deserve a promotion", "promotion to manager"],
    band: 2,
    tags: ["work", "career"],
    trap: "get a promotion = לקבל קידום. בחנויות promotion = מבצע. 'להתקדם' באופן כללי = move up / progress.",
  },
  {
    id: "v-wk-raise",
    word: "raise",
    pos: "n",
    he: "העלאה במשכורת",
    def: "an increase in the money you are paid",
    examples: ["I asked my boss for a raise.", "Everyone got a 5% raise this year."],
    cloze: "She got a ___ after her first year.",
    collocations: ["get a raise", "ask for a raise", "pay raise"],
    band: 2,
    tags: ["work"],
    trap: "העלאה במשכורת = a raise (אמריקאי) / a pay rise (בריטי). 'ביקשתי העלאה' = I asked for a raise.",
    colloc: { frame: "I finally got a ___ after two years without one.", answer: "raise", options: ["raise", "rise up", "lift"], whyHe: "a raise = העלאה במשכורת." },
  },
  {
    id: "v-wk-shift",
    word: "shift",
    pos: "n",
    he: "משמרת",
    def: "a period of work time in a job with different hours",
    examples: ["I'm working the night shift this week.", "My shift starts at 7 a.m."],
    cloze: "She works the morning ___ at the hospital.",
    collocations: ["night shift", "work a shift", "shift work"],
    band: 2,
    tags: ["work"],
    trap: "'משמרת לילה' = night shift. 'לעבוד במשמרות' = work shifts / work in shifts.",
    colloc: { frame: "He ___ the night shift at the factory.", answer: "works", options: ["works", "does", "makes"], whyHe: "work a shift." },
  },
  {
    id: "v-wk-overtime",
    word: "overtime",
    pos: "n",
    he: "שעות נוספות",
    def: "extra hours that you work after your normal hours",
    examples: ["I did ten hours of overtime last week.", "Do they pay overtime here?"],
    cloze: "We had to work ___ to finish the order.",
    collocations: ["work overtime", "paid overtime", "overtime hours"],
    band: 2,
    tags: ["work"],
    trap: "'שעות נוספות' = overtime (לא ספיר, בלי s). 'עבדתי שעות נוספות' = I worked overtime.",
    colloc: { frame: "They ___ overtime every Thursday.", answer: "work", options: ["work", "make", "stay"], whyHe: "work overtime." },
  },
  {
    id: "v-wk-application",
    word: "application",
    pos: "n",
    he: "בקשה, טופס מועמדות",
    def: "a formal written request for a job, course, etc.",
    examples: ["I sent my application yesterday.", "They received over 300 applications for the job."],
    cloze: "Fill in the ___ form and attach your resume.",
    collocations: ["job application", "submit an application", "application form"],
    band: 2,
    tags: ["work", "career"],
    trap: "application = טופס מועמדות או בקשה. אפליקציה בטלפון = app. 'שלחתי מועמדות' = I sent an application / I applied.",
  },
  {
    id: "v-wk-resume",
    word: "resume",
    pos: "n",
    he: "קורות חיים",
    def: "a document that lists your education and work history",
    examples: ["Send me your resume and I'll pass it on.", "Keep your resume to one page."],
    cloze: "Update your ___ before you apply.",
    accept: ["CV"],
    collocations: ["send a resume", "update your resume", "resume and cover letter"],
    band: 2,
    tags: ["work", "career"],
    trap: "באמריקאית: resume (מבטאים REZ-oo-may); בבריטית: CV. 'קורות חיים' לא life story. 'שלחתי קו״ח' = I sent my resume.",
  },
  {
    id: "v-wk-position",
    word: "position",
    pos: "n",
    he: "משרה, תפקיד",
    def: "a job in a company (a more formal word)",
    examples: ["I'm applying for the position of sales manager.", "The position is still open."],
    cloze: "We have an open ___ in the design team.",
    collocations: ["apply for a position", "open position", "senior position"],
    band: 2,
    tags: ["work", "career"],
    trap: "position = משרה (רשמי, במודעות דרושים). job = יומיומי. 'התפקיד' = position / role.",
  },
  {
    id: "v-wk-assignment",
    word: "assignment",
    pos: "n",
    he: "עבודה (להגשה), מטלה",
    def: "a piece of work that a student or worker is given to do",
    examples: ["I have to hand in an assignment on Sunday.", "The teacher gave us a group assignment."],
    cloze: "I stayed up late finishing my history ___.",
    collocations: ["hand in an assignment", "written assignment", "assignment due Friday"],
    band: 2,
    tags: ["study"],
    trap: "'יש לי עבודה להגיש' = I have an assignment (לא a work!). work לא ספיר ולא 'עבודה' במובן של מטלה.",
    colloc: { frame: "The ___ is due on Friday, so start early.", answer: "assignment", options: ["assignment", "work", "job"], whyHe: "מטלה להגשה = assignment." },
  },
  {
    id: "v-wk-client",
    word: "client",
    pos: "n",
    he: "לקוח (של שירות)",
    def: "a person who pays a professional or company for a service",
    examples: ["The lawyer meets clients every afternoon.", "We lost an important client last year."],
    cloze: "I have a meeting with a new ___ at three.",
    collocations: ["important client", "meet a client", "client meeting"],
    band: 2,
    tags: ["work"],
    trap: "client = לקוח של שירות מקצועי (עו״ד, רואה חשבון, סוכנות פרסום). בחנות או במסעדה = customer.",
  },
  {
    id: "v-wk-degree",
    word: "degree",
    pos: "n",
    he: "תואר",
    def: "a qualification you get when you finish university",
    examples: ["She has a degree in economics.", "You need a degree for this job."],
    cloze: "He's doing a master's ___ in computer science.",
    collocations: ["bachelor's degree", "master's degree", "degree in something"],
    band: 2,
    tags: ["study", "career"],
    trap: "'תואר ראשון' = bachelor's degree (לא first degree); 'תואר שני' = master's degree. degree IN a subject.",
    colloc: { frame: "She's studying for a ___ degree in law.", answer: "bachelor's", options: ["bachelor's", "first", "primary"], whyHe: "תואר ראשון = bachelor's degree." },
  },
  {
    id: "v-wk-semester",
    word: "semester",
    pos: "n",
    he: "סמסטר",
    def: "one of the two halves of the school or university year",
    examples: ["The first semester starts in October.", "I'm taking five courses this semester."],
    cloze: "Exams are at the end of every ___.",
    collocations: ["fall semester", "this semester", "end of the semester"],
    band: 2,
    tags: ["study"],
    trap: "'סמסטר א' = the first / fall semester; 'סמסטר ב' = the second / spring semester. 'הסמסטר' = this semester.",
  },
  
  {
    id: "v-wk-career",
    word: "career",
    pos: "n",
    he: "קריירה",
    def: "the series of jobs you do in your working life",
    examples: ["She had a long career in journalism.", "I want a career, not just a job."],
    cloze: "He's thinking about a ___ change at 40.",
    collocations: ["career change", "start a career", "career in medicine"],
    band: 2,
    tags: ["career"],
    trap: "career מבטאים kuh-REER. אל תבלבלו עם carrier. 'ללמוד קריירה' לא קיים: study a subject, have a career.",
  },
  {
    id: "v-wk-effort",
    word: "effort",
    pos: "n",
    he: "מאמץ",
    def: "the energy or hard work you use to do something",
    examples: ["She puts a lot of effort into her work.", "It takes effort to learn a language."],
    cloze: "Thanks for all your ___ on this project.",
    collocations: ["make an effort", "put effort into", "a lot of effort"],
    band: 2,
    tags: ["work", "study"],
    trap: "'לעשות מאמץ' = make an effort, לא do an effort. 'להשקיע מאמץ ב-' = put effort into.",
    colloc: { frame: "You should ___ an effort to come to the meeting.", answer: "make", options: ["make", "do", "take"], whyHe: "make an effort." },
  },
  {
    id: "v-wk-unemployed",
    word: "unemployed",
    pos: "adj",
    he: "מובטל",
    def: "without a job",
    examples: ["He's been unemployed for six months.", "The number of unemployed people went down."],
    cloze: "She was ___ for a year before she found this job.",
    collocations: ["unemployed for months", "unemployed people", "become unemployed"],
    band: 2,
    tags: ["work", "career"],
    trap: "'מובטל' = unemployed; 'אבטלה' = unemployment. לא without work. 'בין עבודות' (עדין) = between jobs.",
  },
  {
    id: "v-wk-experienced",
    word: "experienced",
    pos: "adj",
    he: "מנוסה",
    def: "having a lot of knowledge or skill from doing something",
    examples: ["We need an experienced driver.", "She's very experienced in customer service."],
    cloze: "He's an ___ teacher with twenty years in schools.",
    collocations: ["experienced in something", "highly experienced", "experienced worker"],
    band: 2,
    tags: ["work", "career"],
    trap: "experienced IN something. ההפך: inexperienced. 'בעל ניסיון' = experienced.",
  },
  {
    id: "v-wk-reliable",
    word: "reliable",
    pos: "adj",
    he: "אמין",
    def: "someone or something you can trust to do what is expected",
    examples: ["She's a reliable employee who never misses a deadline.", "Is the bus reliable in the morning?"],
    cloze: "I need someone ___ to take care of the shop.",
    collocations: ["reliable worker", "reliable source", "reliable car"],
    band: 2,
    tags: ["work"],
    trap: "reliable = אמין, אפשר לסמוך עליו. 'אפשר לסמוך עליו' = you can rely on him / he's reliable.",
  },
  {
    id: "v-wk-productive",
    word: "productive",
    pos: "adj",
    he: "פרודוקטיבי, יעיל",
    def: "doing or making a lot of useful work",
    examples: ["I'm most productive in the morning.", "It was a very productive meeting."],
    cloze: "I had a really ___ day and finished everything.",
    collocations: ["productive day", "productive meeting", "stay productive"],
    band: 2,
    tags: ["work"],
  },
  {
    id: "v-wk-stressful",
    word: "stressful",
    pos: "adj",
    he: "מלחיץ",
    def: "causing worry and pressure",
    examples: ["My job is really stressful before the holidays.", "Moving house is stressful."],
    cloze: "It was a ___ week with three deadlines.",
    collocations: ["stressful job", "stressful time", "extremely stressful"],
    band: 2,
    tags: ["work"],
    trap: "stressful = מלחיץ (העבודה); stressed = לחוץ (אני). 'אני לחוץ' = I'm stressed, לא I'm stressful!",
    colloc: { frame: "I'm so ___ about the presentation tomorrow.", answer: "stressed", options: ["stressed", "stressful", "stress"], whyHe: "אדם הוא stressed; מצב הוא stressful." },
  },
  {
    id: "v-wk-flexible",
    word: "flexible",
    pos: "adj",
    he: "גמיש",
    def: "able to change easily when the situation changes",
    examples: ["My hours are flexible, so I can start late.", "We need to be flexible about the deadline."],
    cloze: "The company offers ___ working hours.",
    collocations: ["flexible hours", "flexible schedule", "be flexible about"],
    band: 2,
    tags: ["work"],
  },
  {
    id: "v-wk-remote",
    word: "remote",
    pos: "adj",
    he: "מרחוק",
    def: "done from home or away from the office",
    examples: ["I have a remote job with a US company.", "Remote work became normal after 2020."],
    cloze: "She works ___ from a village in the north.",
    clozeAnswer: "remotely",
    accept: ["from home"],
    collocations: ["remote work", "work remotely", "remote team"],
    band: 2,
    tags: ["work"],
    trap: "'עבודה מהבית / מרחוק' = remote work / working from home. 'אני עובד מרחוק' = I work remotely (תואר הפועל).",
  },
  {
    id: "v-wk-urgent",
    word: "urgent",
    pos: "adj",
    he: "דחוף",
    def: "needing to be done immediately",
    examples: ["I got an urgent email from the client.", "It's not urgent, it can wait till tomorrow."],
    cloze: "Sorry, I have to take this call, it's ___.",
    collocations: ["urgent matter", "urgent email", "not urgent"],
    band: 2,
    tags: ["work"],
    trap: "urgent = דחוף. 'זה דחוף' = It's urgent. 'בדחיפות' = urgently. לא emergency (זה מצב חירום).",
  },

  // ---------- Band 3 ----------
  {
    id: "v-wk-resign",
    word: "resign",
    pos: "v",
    he: "להתפטר (רשמי)",
    def: "to officially tell your employer that you are leaving your job",
    examples: ["The manager resigned after the report came out.", "I've decided to resign at the end of the month."],
    cloze: "She ___ from her position as head of sales.",
    clozeAnswer: "resigned",
    collocations: ["resign from a job", "resign as manager", "hand in your resignation"],
    band: 3,
    tags: ["work", "career"],
    trap: "resign = להתפטר; retire = לפרוש לפנסיה. 'הוא התפטר' לא retired! וגם: resign FROM, לא resign of.",
    colloc: { frame: "He ___ from the board after the scandal.", answer: "resigned", options: ["resigned", "retired", "fired"], whyHe: "התפטר (רשמית) = resign; retire זה פרישה לפנסיה." },
  },
  {
    id: "v-wk-reschedule",
    word: "reschedule",
    pos: "v",
    he: "לקבוע מועד חדש",
    def: "to change the time of a planned event",
    examples: ["Can we reschedule our meeting for Thursday?", "The interview was rescheduled twice."],
    cloze: "I'm sick today, can we ___ for next week?",
    accept: ["postpone"],
    collocations: ["reschedule a meeting", "reschedule for Monday", "reschedule an appointment"],
    band: 3,
    tags: ["work"],
    trap: "reschedule FOR a new time (reschedule for Friday). 'להזיז את הפגישה' = move / reschedule the meeting.",
  },
  {
    id: "v-wk-negotiate",
    word: "negotiate",
    pos: "v",
    he: "לנהל משא ומתן",
    def: "to discuss something to reach an agreement",
    examples: ["I negotiated a higher salary before I signed.", "We're still negotiating with the supplier."],
    cloze: "Don't accept the first offer, try to ___.",
    collocations: ["negotiate a salary", "negotiate with someone", "negotiate a deal"],
    band: 3,
    tags: ["work", "career"],
    trap: "negotiate a salary (בלי on או about): 'להתמקח על השכר' = negotiate the salary. negotiate WITH a person.",
    colloc: { frame: "She ___ a better deal with the supplier.", answer: "negotiated", options: ["negotiated", "discussed", "argued"], whyHe: "negotiate a deal = לסגור תנאים טובים במו״מ." },
  },
  {
    id: "v-wk-report-to",
    word: "report to",
    pos: "phr",
    he: "להיות כפוף ל-",
    def: "to have someone as your direct manager",
    examples: ["I report to the head of marketing.", "Who do you report to?"],
    cloze: "In this job you'll ___ the regional manager.",
    clozeAnswer: "report to",
    collocations: ["report to a manager", "report directly to", "who do you report to?"],
    band: 3,
    tags: ["work"],
    trap: "'אני כפוף ל-' = I report to. לא I'm under him. 'המנהל הישיר שלי' = the person I report to / my direct manager.",
  },
  
  {
    id: "v-wk-enroll",
    word: "enroll",
    pos: "v",
    he: "להירשם (ללימודים)",
    def: "to officially join a course, school, or university",
    examples: ["I enrolled in an evening course in accounting.", "Over 500 students enrolled this year."],
    cloze: "She ___ in a nursing program last fall.",
    clozeAnswer: "enrolled",
    accept: ["registered"],
    collocations: ["enroll in a course", "enroll at a university", "enrollment"],
    band: 3,
    tags: ["study"],
    trap: "enroll IN a course / program (אמריקאי: עם שני L). לא enroll to. יותר רשמי מ-sign up for.",
    colloc: { frame: "He enrolled ___ a coding bootcamp.", answer: "in", options: ["in", "to", "for"], whyHe: "enroll in a course." },
  },
  
  {
    id: "v-wk-major-in",
    word: "major in",
    pos: "phr",
    he: "ללמוד (חוג ראשי)",
    def: "to study something as your main subject at university",
    examples: ["She majored in psychology at Hebrew University.", "What did you major in?"],
    cloze: "I ___ economics and minored in French.",
    clozeAnswer: "majored in",
    collocations: ["major in economics", "double major", "my major"],
    band: 3,
    tags: ["study"],
    trap: "'למדתי פסיכולוגיה' (כתואר) = I majored in psychology. major = החוג. 'מה למדת?' = What did you major in? / What did you study?",
  },
  {
    id: "v-wk-commute",
    word: "commute",
    pos: "v",
    he: "לנסוע לעבודה",
    def: "to travel regularly between home and work",
    examples: ["I commute by train, it takes an hour.", "She commutes from Modiin to Tel Aviv every day."],
    cloze: "He ___ two hours a day and hates it.",
    clozeAnswer: "commutes",
    collocations: ["commute to work", "commute by train", "long commute"],
    band: 3,
    tags: ["work"],
    trap: "'הנסיעה לעבודה' = the commute (שם עצם). 'אני נוסע לעבודה ברכבת' = I commute by train, לא I travel to my work.",
  },
  {
    id: "v-wk-postpone",
    word: "postpone",
    pos: "v",
    he: "לדחות (לזמן אחר)",
    def: "to move an event to a later time",
    examples: ["The meeting was postponed until next week.", "Let's postpone the decision for now."],
    cloze: "They ___ the exam because of the strike.",
    clozeAnswer: "postponed",
    accept: ["put off"],
    collocations: ["postpone a meeting", "postpone until", "postpone doing"],
    band: 3,
    tags: ["work", "study"],
    trap: "'לדחות' = postpone (לזמן אחר) או reject (לסרב). 'דחו את הבקשה שלי' = They rejected my request, לא postponed! וגם: postpone + ing.",
    colloc: { frame: "The wedding was ___ because of the war.", answer: "postponed", options: ["postponed", "rejected", "refused"], whyHe: "נדחה למועד אחר = postponed; rejected = סורב." },
  },
  {
    id: "v-wk-approve",
    word: "approve",
    pos: "v",
    he: "לאשר",
    def: "to officially agree to a plan or request",
    examples: ["My boss approved my vacation request.", "The budget hasn't been approved yet."],
    cloze: "Has the manager ___ the new schedule?",
    clozeAnswer: "approved",
    collocations: ["approve a request", "approve a budget", "approve of someone"],
    band: 3,
    tags: ["work"],
    trap: "approve a request = לאשר (בלי of). approve OF = לראות בעין יפה (I don't approve of his behavior). אישור הגעה = confirm.",
    colloc: { frame: "HR still needs to ___ your day off.", answer: "approve", options: ["approve", "confirm", "agree"], whyHe: "approve a request = לאשר רשמית." },
  },
  {
    id: "v-wk-catch-up-on",
    word: "catch up on",
    pos: "phr",
    he: "להשלים (פיגור)",
    def: "to do work that you should have done earlier",
    examples: ["I need to catch up on emails after my vacation.", "She's catching up on the lessons she missed."],
    cloze: "I stayed late to ___ some paperwork.",
    clozeAnswer: "catch up on",
    collocations: ["catch up on work", "catch up on emails", "catch up with a friend"],
    band: 3,
    tags: ["work", "study"],
    trap: "catch up ON work = להשלים פיגור; catch up WITH a friend = להתעדכן. 'להשלים חומר' = catch up on the material.",
    colloc: { frame: "Let's ___ up over coffee, it's been ages.", answer: "catch", options: ["catch", "meet", "get"], whyHe: "catch up (with someone) = להתעדכן אחרי זמן." },
  },
  {
    id: "v-wk-get-back-to",
    word: "get back to",
    pos: "phr",
    he: "לחזור ל- (עם תשובה)",
    def: "to contact someone later with an answer",
    examples: ["I'll get back to you by the end of the day.", "She never got back to me about the price."],
    cloze: "Let me check and ___ you tomorrow.",
    clozeAnswer: "get back to",
    collocations: ["get back to someone", "get back to you soon", "get back to work"],
    band: 3,
    tags: ["work"],
    trap: "'אחזור אליך' = I'll get back to you, לא I'll return to you. get back to work = לחזור לעבודה.",
    colloc: { frame: "I'll get ___ to you with an answer on Monday.", answer: "back", options: ["back", "again", "return"], whyHe: "get back to someone = לחזור עם תשובה." },
  },
  {
    id: "v-wk-workload",
    word: "workload",
    pos: "n",
    he: "עומס עבודה",
    def: "the amount of work a person has to do",
    examples: ["My workload has doubled since Tom left.", "We need to share the workload better."],
    cloze: "The ___ is heavy this month because of the launch.",
    collocations: ["heavy workload", "manage your workload", "reduce the workload"],
    band: 3,
    tags: ["work"],
    trap: "'עומס' = a heavy workload (לא a big workload). 'יש לי עומס' = I have a heavy workload / I'm swamped.",
    colloc: { frame: "She has a very ___ workload this quarter.", answer: "heavy", options: ["heavy", "big", "strong"], whyHe: "heavy workload." },
  },
  {
    id: "v-wk-internship",
    word: "internship",
    pos: "n",
    he: "התמחות",
    def: "a period of work, often unpaid, to get experience",
    examples: ["I did a summer internship at a law firm.", "The internship turned into a full-time job."],
    cloze: "She got an ___ at a startup in Tel Aviv.",
    collocations: ["do an internship", "summer internship", "paid internship"],
    band: 3,
    tags: ["career", "study"],
    trap: "'לעשות התמחות' = do an internship; 'מתמחה' = intern. לא practice (זה תרגול או לעסוק במקצוע).",
  },
  {
    id: "v-wk-staff",
    word: "staff",
    pos: "n",
    he: "צוות, סגל",
    def: "all the people who work in an organization",
    examples: ["The staff at the hotel were really friendly.", "We have a staff of twelve."],
    cloze: "All ___ must wear a name tag.",
    collocations: ["staff meeting", "member of staff", "hire more staff"],
    band: 3,
    tags: ["work"],
    trap: "staff = כל העובדים יחד. לא a staff על אדם אחד: אומרים a staff member. 'ישיבת צוות' = staff meeting.",
    colloc: { frame: "We have a ___ meeting every Monday morning.", answer: "staff", options: ["staff", "stuff", "staffs"], whyHe: "staff meeting; stuff = דברים (שגיאת איות נפוצה!)." },
  },
  {
    id: "v-wk-candidate",
    word: "candidate",
    pos: "n",
    he: "מועמד",
    def: "a person who is trying to get a job or win an election",
    examples: ["We interviewed five candidates for the position.", "She's the strongest candidate we've seen."],
    cloze: "The best ___ will get an offer by Friday.",
    collocations: ["strong candidate", "job candidate", "candidate for a position"],
    band: 3,
    tags: ["work", "career"],
    trap: "candidate FOR a position. מועמד לעבודה גם applicant. אל תבלבלו עם competitor (מתחרה).",
  },
  {
    id: "v-wk-feedback",
    word: "feedback",
    pos: "n",
    he: "משוב, פידבק",
    def: "comments about how well someone is doing",
    examples: ["My manager gave me some useful feedback.", "We got great feedback from the customers."],
    cloze: "Can you give me some ___ on my presentation?",
    collocations: ["give feedback", "get feedback", "positive feedback"],
    band: 3,
    tags: ["work", "study"],
    trap: "feedback לא ספיר: some feedback, לא a feedback ולא feedbacks. 'לתת פידבק על' = give feedback ON.",
    colloc: { frame: "I'd love to get some feedback ___ my report.", answer: "on", options: ["on", "for", "to"], whyHe: "feedback on something." },
  },
  {
    id: "v-wk-budget",
    word: "budget",
    pos: "n",
    he: "תקציב",
    def: "the amount of money available for something",
    examples: ["We don't have the budget for a new office.", "The marketing budget was cut by half."],
    cloze: "The project went over ___ by 20%.",
    collocations: ["over budget", "tight budget", "cut the budget"],
    band: 3,
    tags: ["work"],
    trap: "'חריגה מהתקציב' = over budget; 'תקציב מצומצם' = tight budget. הגייה: BUH-jit.",
    colloc: { frame: "We're on a ___ budget, so no fancy dinners.", answer: "tight", options: ["tight", "narrow", "thin"], whyHe: "tight budget = תקציב מצומצם." },
  },
  {
    id: "v-wk-self-employed",
    word: "self-employed",
    pos: "adj",
    he: "עצמאי",
    def: "working for yourself instead of for an employer",
    examples: ["He's self-employed, so he pays his own taxes.", "Being self-employed means no paid vacation."],
    cloze: "She's been ___ since she left the bank.",
    accept: ["freelance"],
    collocations: ["be self-employed", "self-employed workers", "go self-employed"],
    band: 3,
    tags: ["work", "career"],
    trap: "'עצמאי' (עוסק) = self-employed / freelancer, לא independent (זה 'עצמאי' באופי). 'מעצב עצמאי' = a freelance designer.",
  },
  {
    id: "v-wk-qualified",
    word: "qualified",
    pos: "adj",
    he: "מוסמך, בעל הכשרה",
    def: "having the right training or exams for a job",
    examples: ["She's a qualified accountant.", "Are you qualified to teach English?"],
    cloze: "We're looking for a ___ electrician.",
    collocations: ["qualified for a job", "highly qualified", "qualified to do"],
    band: 3,
    tags: ["work", "career"],
    trap: "qualified FOR a job / qualified TO do. 'מוסמך' = qualified / certified. ההפך: not qualified.",
  },
  {
    id: "v-wk-efficient",
    word: "efficient",
    pos: "adj",
    he: "יעיל",
    def: "working well without wasting time or energy",
    examples: ["The new system is much more efficient.", "She's a very efficient worker."],
    cloze: "Email is more ___ than phone calls for this.",
    collocations: ["efficient worker", "more efficient", "energy-efficient"],
    band: 3,
    tags: ["work"],
    trap: "efficient = יעיל (מהר ובלי בזבוז); effective = אפקטיבי (משיג את המטרה). תרופה effective, עובד efficient.",
    colloc: { frame: "The medicine was very ___, my headache is gone.", answer: "effective", options: ["effective", "efficient", "efficiency"], whyHe: "effective = משיג תוצאה; efficient = יעיל בזמן ובמשאבים." },
  },
  {
    id: "v-wk-senior",
    word: "senior",
    pos: "adj",
    he: "בכיר",
    def: "having a high position or more experience",
    examples: ["She's a senior developer at Wix.", "A senior manager will join the meeting."],
    cloze: "He was promoted to ___ engineer last year.",
    collocations: ["senior manager", "senior position", "senior developer"],
    band: 3,
    tags: ["work", "career"],
    trap: "senior = בכיר (בעבודה), לא 'זקן'. ההפך: junior. senior citizen = אזרח ותיק.",
  },
  {
    id: "v-wk-hardworking",
    word: "hardworking",
    pos: "adj",
    he: "חרוץ",
    def: "working with a lot of effort",
    examples: ["She's honest and hardworking.", "The team is small but hardworking."],
    cloze: "He's the most ___ person in the office.",
    accept: ["hard-working"],
    collocations: ["hardworking employee", "honest and hardworking", "hardworking student"],
    band: 3,
    tags: ["work", "study"],
    trap: "'חרוץ' = hardworking (מילה אחת, תואר). diligent = יותר רשמי. 'הוא עובד קשה' = he works hard.",
  },
  {
    id: "v-wk-temporary",
    word: "temporary",
    pos: "adj",
    he: "זמני",
    def: "lasting only for a limited time",
    examples: ["It's a temporary job until the end of summer.", "This is only a temporary solution."],
    cloze: "She has a ___ contract for six months.",
    collocations: ["temporary job", "temporary contract", "temporary solution"],
    band: 3,
    tags: ["work"],
    trap: "temporary = זמני; permanent = קבוע. 'עובד זמני' = a temp / temporary worker. 'בינתיים' = for now.",
  },

  // ---------- Band 4 ----------
  {
    id: "v-wk-delegate",
    word: "delegate",
    pos: "v",
    he: "להאציל סמכויות",
    def: "to give part of your work to someone else to do",
    examples: ["A good manager knows how to delegate.", "I delegated the research to my assistant."],
    cloze: "You can't do everything yourself, learn to ___.",
    collocations: ["delegate tasks", "delegate to someone", "delegate responsibility"],
    band: 4,
    tags: ["work"],
    trap: "delegate a task TO someone. לא give down. delegate כשם עצם = נציג (מבטאים DEL-i-git).",
  },
  {
    id: "v-wk-overwhelmed",
    word: "overwhelmed",
    pos: "adj",
    he: "מוצף, לא עומד בעומס",
    def: "having too much to do or feel, so you cannot cope",
    examples: ["I feel overwhelmed by all the work.", "New parents often feel overwhelmed."],
    cloze: "She was ___ by the number of emails after her vacation.",
    collocations: ["feel overwhelmed", "overwhelmed by", "overwhelmed with work"],
    band: 4,
    tags: ["work", "study"],
    trap: "'אני מוצף / לא עומד בזה' = I'm overwhelmed (BY / WITH work). לא I'm flooded. overwhelming = מציף (an overwhelming workload).",
    colloc: { frame: "I'm completely overwhelmed ___ work this month.", answer: "with", options: ["with", "from", "of"], whyHe: "overwhelmed with / by work." },
  },
  {
    id: "v-wk-take-on",
    word: "take on",
    pos: "phr",
    he: "לקחת על עצמו",
    def: "to accept a new task or responsibility",
    examples: ["I can't take on any more projects right now.", "She took on extra hours to save money."],
    cloze: "He agreed to ___ the role of team leader.",
    clozeAnswer: "take on",
    accept: ["accept"],
    collocations: ["take on a task", "take on responsibility", "take on staff"],
    band: 4,
    tags: ["work"],
    trap: "'לקחת על עצמי' = take on (לא take on myself). take on staff = לגייס עובדים.",
    colloc: { frame: "I've taken ___ too much work this month.", answer: "on", options: ["on", "over", "up"], whyHe: "take on = לקחת על עצמך; take over = להחליף; take up = להתחיל תחביב." },
  },
  
  {
    id: "v-wk-make-a-living",
    word: "make a living",
    pos: "phr",
    he: "להתפרנס",
    def: "to earn enough money to live",
    examples: ["He makes a living as a photographer.", "It's hard to make a living from music."],
    cloze: "She ___ selling handmade jewelry online.",
    clozeAnswer: "makes a living",
    accept: ["earns a living"],
    collocations: ["make a living from", "make a living as", "earn a living"],
    band: 4,
    tags: ["work", "career"],
    trap: "'להתפרנס' = make a living / earn a living. 'ממה אתה מתפרנס?' = What do you do for a living?",
    colloc: { frame: "What do you do for a ___?", answer: "living", options: ["living", "life", "job"], whyHe: "What do you do for a living? = ממה אתה מתפרנס?" },
  },
  {
    id: "v-wk-agenda",
    word: "agenda",
    pos: "n",
    he: "סדר יום (לפגישה)",
    def: "a list of things to discuss in a meeting",
    examples: ["I'll send the agenda before the meeting.", "The first item on the agenda is the budget."],
    cloze: "What's on the ___ for today's meeting?",
    collocations: ["on the agenda", "set the agenda", "item on the agenda"],
    band: 4,
    tags: ["work"],
    trap: "agenda = סדר היום של פגישה. 'אג'נדה' בעברית (תפיסת עולם) = a hidden / political agenda. 'יומן' = planner / calendar.",
    colloc: { frame: "The next item ___ the agenda is hiring.", answer: "on", options: ["on", "in", "at"], whyHe: "on the agenda." },
  },
  {
    id: "v-wk-wage",
    word: "wage",
    pos: "n",
    he: "שכר (לשעה)",
    def: "money paid for work, usually by the hour or week",
    examples: ["The minimum wage went up this year.", "Waiters earn a low wage plus tips."],
    cloze: "The ___ here is 35 shekels an hour.",
    accept: ["pay"],
    collocations: ["minimum wage", "hourly wage", "low wages"],
    band: 4,
    tags: ["work"],
    trap: "wage = שכר לפי שעה או שבוע (מלצר, פועל); salary = משכורת חודשית קבועה. 'שכר מינימום' = minimum wage.",
    colloc: { frame: "Many students work for ___ wage.", answer: "minimum", options: ["minimum", "lowest", "basic"], whyHe: "minimum wage = שכר מינימום." },
  },
  {
    id: "v-wk-demanding",
    word: "demanding",
    pos: "adj",
    he: "תובעני",
    def: "needing a lot of time, effort, or attention",
    examples: ["Nursing is a demanding job.", "My boss is very demanding but fair."],
    cloze: "The course is ___, but you learn a lot.",
    collocations: ["demanding job", "demanding boss", "physically demanding"],
    band: 4,
    tags: ["work", "study"],
    trap: "demanding = תובעני (עבודה או אדם). 'בוס קשה' = a demanding boss, לא a hard boss.",
  },
  {
    id: "v-wk-follow-up",
    word: "follow up",
    pos: "phr",
    he: "לעשות מעקב",
    def: "to contact someone again about something you discussed",
    examples: ["I'll follow up with the client next week.", "Did you follow up on that email?"],
    cloze: "Please ___ with HR about your contract.",
    clozeAnswer: "follow up",
    collocations: ["follow up with someone", "follow up on something", "follow-up email"],
    band: 4,
    tags: ["work"],
    trap: "follow up WITH a person, follow up ON a topic. כתואר: a follow-up email (עם מקף).",
    colloc: { frame: "I'll follow up ___ Sarah about the invoice.", answer: "with", options: ["with", "on", "to"], whyHe: "follow up with a person; follow up on a topic." },
  },
  {
    id: "v-wk-supervise",
    word: "supervise",
    pos: "v",
    he: "לפקח על",
    def: "to watch and direct people while they work",
    examples: ["She supervises a team of six nurses.", "Students must be supervised during the exam."],
    cloze: "Who will ___ the new interns?",
    collocations: ["supervise a team", "supervise students", "supervisor"],
    band: 4,
    tags: ["work", "study"],
    trap: "supervise someone (בלי on!). 'הממונה' = supervisor. 'הוא מפקח על הצוות' = He supervises the team.",
  },
];
