import type { GrammarTopic } from "@/lib/types";

export const CLAUSES_WORD_ORDER: GrammarTopic[] = [
  // ------------------------------------------------------------------
  // 39. Relative clauses
  // ------------------------------------------------------------------
  {
    id: "g-relative-clauses",
    title: "Relative clauses: who / which / that / where / whose",
    titleHe: "משפטי זיקה",
    strand: "clauses",
    order: 39,
    prereqs: [],
    lesson: {
      explanationHe: [
        "משפט זיקה מוסיף מידע על שם עצם: 'האיש שגר למעלה', 'הספר שקניתי'. בעברית מילה אחת – 'ש' – עושה את כל העבודה. באנגלית בוחרים מילה לפי מה שמתארים: who לאנשים, which לדברים, where למקום, whose לשייכות, ו-that יכול להחליף את who או which.",
        "כשמילת הזיקה היא הנושא של המשפט הקטן (the man who lives upstairs) חייבים אותה. כשהיא המושא (the book that I bought), אפשר להשמיט אותה לגמרי: the book I bought. בדיבור זו הצורה הכי טבעית.",
        "where מתאר מקום שבו משהו קורה: the café where we met. אבל אם המקום הוא המושא של הפועל (קניתי את הבית), משתמשים ב-that או which: the house that I bought.",
        "whose = 'ש... שלו/שלה'. בעברית: 'הבחורה שאח שלה טייס'. באנגלית: the girl whose brother is a pilot – בלי her, בלי 'שלה'.",
        "משפט זיקה שמוסיף מידע צדדי על משהו שכבר מזוהה (אחותי, תל אביב) בא בין פסיקים, ואז אין that: My sister, who lives in Haifa, is coming.",
      ],
      form: [
        { label: "who – people", example: "the woman who lives next door" },
        { label: "which – things", example: "the phone which I bought" },
        { label: "that – people or things (no commas)", example: "the man that called / the car that broke down" },
        { label: "where – place", example: "the town where I grew up" },
        { label: "whose – possession", example: "the boy whose dad is a chef" },
        { label: "no pronoun (object)", example: "the movie (that) we saw" },
        { label: "extra info: , who / , which", example: "Dan, who is 30, lives in Haifa." },
      ],
      examples: [
        { en: "That's the guy who fixed my car.", he: "זה הבחור שתיקן לי את האוטו." },
        { en: "The soup that you made was delicious.", he: "המרק שהכנת היה מעולה." },
        { en: "I still remember the day we met.", he: "אני עדיין זוכר את היום שנפגשנו." },
        { en: "This is the street where I grew up.", he: "זה הרחוב שגדלתי בו." },
        { en: "I have a friend whose sister works at the airport.", he: "יש לי חברה שאחותה עובדת בנמל התעופה." },
        { en: "My boss, who is usually calm, shouted at everyone.", he: "הבוס שלי, שבדרך כלל רגוע, צעק על כולם." },
        { en: "Is that the restaurant you told me about?", he: "זו המסעדה שסיפרת לי עליה?" },
      ],
      contrastHe: [
        "בעברית 'ש' משמשת לאנשים, לדברים ולמקומות. באנגלית: who לאנשים, which/that לדברים, where למקומות. 'האישה שמדברת' = the woman who is talking, לא which.",
        "בעברית חוזרים על הכינוי: 'הספר שקניתי אותו', 'האיש שראיתי אותו'. באנגלית אסור: the book I bought, the man I saw – בלי it או him.",
        "בעברית 'ש... שלו': 'הילד שהאבא שלו רופא'. באנגלית whose מחליף את 'ש + שלו': the boy whose father is a doctor.",
        "'המקום שגרתי בו' – באנגלית where (the place where I lived) או that + in בסוף (the place I lived in). לא the place where I lived in.",
      ],
      commonErrors: [
        { wrong: "The man that I met him yesterday was nice.", right: "The man I met yesterday was nice.", whyHe: "him מיותר – מילת הזיקה כבר מייצגת את האיש. זה תרגום של 'שפגשתי אותו'." },
        { wrong: "I know a woman which speaks six languages.", right: "I know a woman who speaks six languages.", whyHe: "which רק לדברים ולבעלי חיים. לאנשים – who (או that)." },
        { wrong: "This is the apartment where I bought.", right: "This is the apartment that I bought.", whyHe: "where מתאר מקום שבו משהו קורה. כאן הדירה היא המושא של bought, אז that/which או כלום." },
        { wrong: "That's the girl who her brother is famous.", right: "That's the girl whose brother is famous.", whyHe: "'שאח שלה' = whose brother. לא who + her." },
        { wrong: "My mother, that is 60, still works.", right: "My mother, who is 60, still works.", whyHe: "אחרי פסיק (מידע נוסף על מישהו מזוהה) לא משתמשים ב-that, רק who או which." },
        { wrong: "I have a friend who live in London.", right: "I have a friend who lives in London.", whyHe: "הפועל אחרי who מתאים לשם העצם (a friend – יחיד): lives." },
      ],
    },
    items: [
      {
        id: "g-relative-clauses-01",
        type: "gap",
        prompt: "That's the woman ___ lives next door.",
        answer: "who",
        accept: ["that"],
        hint: "who / which / that / where / whose",
        explainHe: "אישה – אדם, ולכן who (או that). which לדברים בלבד.",
      },
      {
        id: "g-relative-clauses-02",
        type: "gap",
        prompt: "The phone ___ I bought yesterday is already broken.",
        answer: "that",
        accept: ["which"],
        hint: "who / which / that / where / whose",
        explainHe: "phone – דבר, לכן that או which. כאן אפשר גם להשמיט לגמרי, כי הטלפון הוא המושא של bought.",
      },
      {
        id: "g-relative-clauses-03",
        type: "gap",
        prompt: "This is the café ___ we first met.",
        answer: "where",
        hint: "who / which / that / where / whose",
        explainHe: "מקום שבו משהו קרה – where. שימו לב: לא 'where we met in'.",
      },
      {
        id: "g-relative-clauses-04",
        type: "gap",
        prompt: "I have a friend ___ father is a pilot.",
        answer: "whose",
        hint: "who / which / that / where / whose",
        explainHe: "'שאבא שלו טייס' = whose father. whose מחליף את 'ש + שלו'.",
      },
      {
        id: "g-relative-clauses-05",
        type: "gap",
        prompt: "The people ___ work here are really friendly.",
        answer: "who",
        accept: ["that"],
        hint: "who / which / that / where / whose",
        explainHe: "people – אנשים, לכן who או that. הפועל work ברבים כי people הם רבים.",
      },
      {
        id: "g-relative-clauses-06",
        type: "gap",
        prompt: "My sister, ___ lives in Haifa, is coming for dinner.",
        answer: "who",
        hint: "who / which / that",
        explainHe: "בין פסיקים (מידע נוסף על אחותי, שכבר מזוהה) – רק who. that אסור כאן.",
      },
      {
        id: "g-relative-clauses-07",
        type: "gap",
        prompt: "Is this the restaurant ___ you told me about?",
        answer: "that",
        accept: ["which"],
        hint: "who / which / that / where",
        explainHe: "המסעדה היא המושא של told ... about, לכן that או which (או כלום). where לא מתאים – כבר יש about בסוף.",
      },
      {
        id: "g-relative-clauses-08",
        type: "mcq",
        prompt: "She's the teacher ___ helped me pass the exam.",
        options: [
          { text: "which", errorType: "word-choice", whyHe: "which רק לדברים. מורה היא אדם." },
          { text: "who" },
          { text: "whose", errorType: "word-choice", whyHe: "whose = 'ש... שלו'. כאן המורה עצמה עזרה, לא משהו ששייך לה." },
          { text: "where", errorType: "word-choice", whyHe: "where רק למקום." },
        ],
        answerIndex: 1,
        explainHe: "המורה היא אדם והיא הנושא של helped – who (או that).",
      },
      {
        id: "g-relative-clauses-09",
        type: "mcq",
        prompt: "Choose the correct sentence.",
        options: [
          { text: "That's the man that I saw him yesterday.", errorType: "interference", whyHe: "him מיותר – 'שראיתי אותו' לא מתורגם מילה במילה. that כבר מייצג את האיש." },
          { text: "That's the man which I saw yesterday.", errorType: "word-choice", whyHe: "which לדברים, לא לאנשים." },
          { text: "That's the man I saw yesterday.", },
          { text: "That's the man where I saw yesterday.", errorType: "word-choice", whyHe: "where רק למקום." },
        ],
        answerIndex: 2,
        explainHe: "האיש הוא המושא של saw, אז אפשר בלי מילת זיקה בכלל – ובלי him.",
      },
      {
        id: "g-relative-clauses-10",
        type: "mcq",
        prompt: "Tel Aviv is the city ___ I grew up.",
        options: [
          { text: "which", errorType: "word-choice", whyHe: "which לבד לא מתאים – היה צריך in which. פשוט יותר: where." },
          { text: "who", errorType: "word-choice", whyHe: "who לאנשים." },
          { text: "that", errorType: "word-choice", whyHe: "that היה דורש in בסוף: the city that I grew up in." },
          { text: "where" },
        ],
        answerIndex: 3,
        explainHe: "העיר היא המקום שבו גדלתי – where.",
      },
      {
        id: "g-relative-clauses-11",
        type: "mcq",
        prompt: "The book ___ cover is red is mine.",
        options: [
          { text: "whose" },
          { text: "who's", errorType: "spelling", whyHe: "who's = who is. שייכות נכתבת whose." },
          { text: "that its", errorType: "interference", whyHe: "'שהכריכה שלו' – באנגלית whose מחליף גם את 'ש' וגם את 'שלו'." },
          { text: "which", errorType: "word-choice", whyHe: "which היה מתאים אם הספר עושה משהו, לא לשייכות." },
        ],
        answerIndex: 0,
        explainHe: "הכריכה שייכת לספר – whose. whose עובד גם לדברים, לא רק לאנשים.",
      },
      {
        id: "g-relative-clauses-12",
        type: "mcq",
        prompt: "My boss, ___ is from Canada, speaks French.",
        options: [
          { text: "that", errorType: "other", whyHe: "אחרי פסיק (מידע נוסף) אסור that." },
          { text: "which", errorType: "word-choice", whyHe: "which לדברים. הבוס אדם." },
          { text: "who" },
          { text: "whose", errorType: "word-choice", whyHe: "whose לשייכות. כאן הבוס עצמו מקנדה." },
        ],
        answerIndex: 2,
        explainHe: "מידע נוסף בין פסיקים על אדם – who בלבד.",
      },
      {
        id: "g-relative-clauses-13",
        type: "fix",
        prompt: "The movie which we saw it last night was boring.",
        answer: "The movie which we saw last night was boring.",
        accept: ["The movie that we saw last night was boring.", "The movie we saw last night was boring."],
        errorType: "interference",
        explainHe: "it מיותר – which כבר מייצג את הסרט. 'שראינו אותו' לא מתורגם מילה במילה.",
      },
      {
        id: "g-relative-clauses-14",
        type: "fix",
        prompt: "I met a woman which works at Google.",
        answer: "I met a woman who works at Google.",
        accept: ["I met a woman that works at Google."],
        errorType: "word-choice",
        explainHe: "אישה – אדם. who (או that), לא which.",
      },
      {
        id: "g-relative-clauses-15",
        type: "fix",
        prompt: "This is the house where I want to buy.",
        answer: "This is the house that I want to buy.",
        accept: ["This is the house which I want to buy.", "This is the house I want to buy."],
        errorType: "word-choice",
        explainHe: "הבית הוא המושא של buy (קונים את הבית), לא מקום שבו משהו קורה. לכן that/which או כלום, לא where.",
      },
      {
        id: "g-relative-clauses-16",
        type: "fix",
        prompt: "Do you know the guy who his car is parked outside?",
        answer: "Do you know the guy whose car is parked outside?",
        errorType: "interference",
        explainHe: "'שהאוטו שלו' = whose car. who + his הוא תרגום מעברית.",
      },
      {
        id: "g-relative-clauses-17",
        type: "fix",
        prompt: "I have a neighbor who have three dogs.",
        answer: "I have a neighbor who has three dogs.",
        errorType: "agreement",
        explainHe: "הפועל אחרי who מתאים ל-a neighbor (יחיד): has.",
      },
      {
        id: "g-relative-clauses-18",
        type: "transform",
        prompt: "I have a friend. She speaks five languages.",
        keyword: "who",
        answer: "I have a friend who speaks five languages.",
        explainHe: "מחברים את שני המשפטים: who מחליף את She.",
      },
      {
        id: "g-relative-clauses-19",
        type: "transform",
        prompt: "This is the park. We played here as kids.",
        keyword: "where",
        answer: "This is the park where we played as kids.",
        explainHe: "where מחליף את here – ולכן here נעלם מהמשפט החדש.",
      },
      {
        id: "g-relative-clauses-20",
        type: "transform",
        prompt: "That's the doctor. Her son is in my class.",
        keyword: "whose",
        answer: "That's the doctor whose son is in my class.",
        explainHe: "whose מחליף את Her – 'שהבן שלה'.",
      },
      {
        id: "g-relative-clauses-21",
        type: "order",
        words: ["the", "man", "who", "lives", "upstairs", "is", "a", "musician"],
        answer: "The man who lives upstairs is a musician.",
        explainHe: "משפט הזיקה (who lives upstairs) צמוד לשם העצם שהוא מתאר, והפועל הראשי (is) בא אחריו.",
      },
      {
        id: "g-relative-clauses-22",
        type: "order",
        words: ["is", "this", "the", "bag", "that", "you", "lost"],
        answer: "Is this the bag that you lost?",
        explainHe: "בשאלה: Is this + שם עצם + משפט הזיקה. that you lost מתאר את התיק.",
      },
      {
        id: "g-relative-clauses-23",
        type: "order",
        words: ["I", "know", "a", "girl", "whose", "brother", "is", "a", "famous", "chef"],
        answer: "I know a girl whose brother is a famous chef.",
        explainHe: "whose + שם העצם ששייך (brother) + הפועל של המשפט הקטן (is).",
      },
      {
        id: "g-relative-clauses-24",
        type: "translate",
        he: "זה החבר שסיפרתי לך עליו.",
        answer: "This is the friend I told you about.",
        accept: [
          "This is the friend that I told you about.",
          "This is the friend who I told you about.",
          "This is the friend whom I told you about.",
          "That's the friend I told you about.",
          "That's the friend that I told you about.",
          "That's the friend who I told you about.",
        ],
        explainHe: "'עליו' הופך ל-about בסוף המשפט, בלי him. מילת הזיקה אופציונלית כי החבר הוא המושא.",
      },
    ],
  },

  // ------------------------------------------------------------------
  // 40. Linking words
  // ------------------------------------------------------------------
  {
    id: "g-linking-words",
    title: "Linking: although / despite / however / so / because / in order to",
    titleHe: "מילות קישור",
    strand: "clauses",
    order: 40,
    prereqs: [],
    lesson: {
      explanationHe: [
        "מילות קישור מחברות רעיונות. השאלה הראשונה תמיד: מה בא אחרי המילה – משפט שלם (נושא + פועל) או רק שם עצם? although / even though / because / so מקבלות משפט שלם. despite / in spite of / because of מקבלות שם עצם או פועל ב-ing.",
        "ניגוד: although it rained = 'למרות שירד גשם'. even though זהה, רק חזק יותר ('אפילו ש'). despite the rain / despite raining = 'למרות הגשם'. שימו לב: despite בלי of, in spite of עם of.",
        "however פותח משפט חדש ובא עם פסיק אחריו: It was expensive. However, it was worth it. זה 'עם זאת' – לא מחברים אותו באמצע משפט כמו but.",
        "סיבה ותוצאה: because + סיבה (I stayed home because I was sick). so + תוצאה (I was sick, so I stayed home). because of + שם עצם: because of the rain.",
        "מטרה: to / in order to + פועל: I called in order to check. לא for to. for מקבל רק שם עצם: for information.",
      ],
      form: [
        { label: "although / even though / though + clause", example: "Although it was late, we kept working." },
        { label: "despite / in spite of + noun / -ing", example: "Despite the cold, we went out." },
        { label: "However, + new sentence", example: "I was tired. However, I finished it." },
        { label: "because + clause / because of + noun", example: "because it rained / because of the rain" },
        { label: "..., so + result", example: "It was late, so we left." },
        { label: "to / in order to + verb", example: "I called to ask about the price." },
      ],
      examples: [
        { en: "Although he's my boss, we're good friends.", he: "למרות שהוא הבוס שלי, אנחנו חברים טובים." },
        { en: "Even though it was raining, the kids played outside.", he: "אפילו שירד גשם, הילדים שיחקו בחוץ." },
        { en: "Despite the traffic, we got there on time.", he: "למרות הפקקים, הגענו בזמן." },
        { en: "In spite of being tired, she went to the gym.", he: "למרות שהייתה עייפה, היא הלכה לחדר כושר." },
        { en: "The hotel was nice. However, the food was terrible.", he: "המלון היה נחמד. עם זאת, האוכל היה נורא." },
        { en: "I missed the bus, so I took a taxi.", he: "פספסתי את האוטובוס, אז לקחתי מונית." },
        { en: "We left early in order to avoid the traffic.", he: "יצאנו מוקדם כדי להימנע מהפקקים." },
        { en: "The flight was canceled because of the storm.", he: "הטיסה בוטלה בגלל הסופה." },
      ],
      contrastHe: [
        "'למרות ש' + משפט = although / even though. 'למרות' + שם עצם = despite / in spite of. בעברית ההבדל הוא רק ה-'ש', באנגלית זו מילה אחרת לגמרי.",
        "'despite of' לא קיים – זה ערבוב של despite ו-in spite of. או despite the rain או in spite of the rain.",
        "even לבד פירושו 'אפילו' (Even Dan came). 'אפילו ש...' = even though + משפט. Even it was late – שגוי.",
        "'למרות זאת' / 'עם זאת' = However, / Still, / Even so, – לא 'in spite of that'. ו'בגלל ש' = because, 'בגלל' + שם עצם = because of.",
      ],
      commonErrors: [
        { wrong: "Despite of the rain, we went out.", right: "Despite the rain, we went out.", whyHe: "despite לא מקבל of. אפשר גם in spite of the rain." },
        { wrong: "Although the traffic, we arrived on time.", right: "Despite the traffic, we arrived on time.", whyHe: "אחרי although חייב משפט שלם. לפני שם עצם – despite / in spite of." },
        { wrong: "Even it was late, I called her.", right: "Even though it was late, I called her.", whyHe: "even לבד = 'אפילו'. כדי לומר 'אפילו ש / למרות ש' צריך even though." },
        { wrong: "I was sick, however I went to work.", right: "I was sick. However, I went to work.", whyHe: "however פותח משפט חדש (אחרי נקודה) ובא עם פסיק אחריו." },
        { wrong: "I went there for to see my grandmother.", right: "I went there to see my grandmother.", whyHe: "מטרה = to + פועל (או in order to). for to לא קיים." },
        { wrong: "Because of it was raining, we stayed in.", right: "Because it was raining, we stayed in.", whyHe: "because of + שם עצם (because of the rain). לפני משפט שלם – because בלבד." },
      ],
    },
    items: [
      {
        id: "g-linking-words-01",
        type: "gap",
        prompt: "___ it was raining, we went for a walk.",
        answer: "Although",
        accept: ["although", "Even though", "even though", "Though", "though"],
        hint: "although / despite",
        explainHe: "אחרי הרווח בא משפט שלם (it was raining) – לכן although / even though, לא despite.",
      },
      {
        id: "g-linking-words-02",
        type: "gap",
        prompt: "We went for a walk ___ the rain.",
        answer: "despite",
        accept: ["in spite of"],
        hint: "although / despite",
        explainHe: "אחרי הרווח שם עצם (the rain) – despite או in spite of. בלי of אחרי despite.",
      },
      {
        id: "g-linking-words-03",
        type: "gap",
        prompt: "I got up early ___ catch the first train.",
        answer: "to",
        accept: ["in order to"],
        hint: "purpose",
        explainHe: "מטרה = to + פועל (או in order to). לא for to.",
      },
      {
        id: "g-linking-words-04",
        type: "gap",
        prompt: "It was late, ___ we took a taxi.",
        answer: "so",
        hint: "so / because",
        explainHe: "לקחת מונית היא התוצאה של השעה המאוחרת – so. because היה הופך את הסדר.",
      },
      {
        id: "g-linking-words-05",
        type: "gap",
        prompt: "I stayed home ___ I was sick.",
        answer: "because",
        accept: ["as", "since"],
        hint: "so / because",
        explainHe: "המחלה היא הסיבה – because + משפט שלם.",
      },
      {
        id: "g-linking-words-06",
        type: "gap",
        prompt: "The hotel was expensive. ___, the service was great.",
        answer: "However",
        accept: ["however", "Nevertheless", "Still", "Even so"],
        hint: "one word, starts a new sentence",
        explainHe: "משפט חדש שמנוגד לקודם, עם פסיק אחריו – However. although לא פותח משפט חדש כך.",
      },
      {
        id: "g-linking-words-07",
        type: "gap",
        prompt: "___ being tired, she finished the report.",
        answer: "Despite",
        accept: ["despite", "In spite of", "in spite of"],
        hint: "although / despite",
        explainHe: "אחרי הרווח פועל ב-ing (being) – despite / in spite of. although היה דורש she was tired.",
      },
      {
        id: "g-linking-words-08",
        type: "mcq",
        prompt: "___ the traffic, we arrived on time.",
        options: [
          { text: "Despite of", errorType: "interference", whyHe: "despite לא מקבל of. או despite או in spite of." },
          { text: "Although", errorType: "other", whyHe: "אחרי although חייב משפט שלם עם פועל, כאן רק שם עצם." },
          { text: "Despite" },
          { text: "Even", errorType: "word-choice", whyHe: "even = 'אפילו', לא 'למרות'." },
        ],
        answerIndex: 2,
        explainHe: "שם עצם אחרי המילה – despite (בלי of).",
      },
      {
        id: "g-linking-words-09",
        type: "mcq",
        prompt: "___ he's 70, he still runs every morning.",
        options: [
          { text: "Even though" },
          { text: "Even", errorType: "interference", whyHe: "even לבד = 'אפילו'. 'אפילו ש' = even though." },
          { text: "Despite", errorType: "other", whyHe: "despite + שם עצם או ing. כאן משפט שלם." },
          { text: "In spite of", errorType: "other", whyHe: "in spite of + שם עצם. כאן משפט שלם." },
        ],
        answerIndex: 0,
        explainHe: "משפט שלם (he's 70) אחרי המילה – even though / although.",
      },
      {
        id: "g-linking-words-10",
        type: "mcq",
        prompt: "I was exhausted. ___, I finished the job.",
        options: [
          { text: "Although", errorType: "other", whyHe: "although מחבר שני חלקים בתוך אותו משפט, לא פותח משפט חדש עם פסיק." },
          { text: "However" },
          { text: "Despite", errorType: "other", whyHe: "despite צריך שם עצם אחריו." },
          { text: "Because", errorType: "word-choice", whyHe: "because מציין סיבה. כאן יש ניגוד." },
        ],
        answerIndex: 1,
        explainHe: "משפט חדש אחרי נקודה, עם פסיק – However.",
      },
      {
        id: "g-linking-words-11",
        type: "mcq",
        prompt: "She's learning Spanish ___ talk to her in-laws.",
        options: [
          { text: "for", errorType: "interference", whyHe: "'בשביל לדבר' – באנגלית אין for + פועל. צריך to / in order to." },
          { text: "for to", errorType: "interference", whyHe: "for to לא קיים באנגלית." },
          { text: "because", errorType: "other", whyHe: "אחרי because צריך נושא + פועל, וכאן מדובר במטרה." },
          { text: "in order to" },
        ],
        answerIndex: 3,
        explainHe: "מטרה + פועל – in order to (או פשוט to).",
      },
      {
        id: "g-linking-words-12",
        type: "mcq",
        prompt: "We missed the bus ___ we left late.",
        options: [
          { text: "so", errorType: "word-choice", whyHe: "so = תוצאה. היציאה המאוחרת היא הסיבה, לא התוצאה." },
          { text: "because" },
          { text: "because of", errorType: "other", whyHe: "because of + שם עצם. לפני משפט שלם – because." },
          { text: "despite", errorType: "word-choice", whyHe: "אין כאן ניגוד, יש סיבה." },
        ],
        answerIndex: 1,
        explainHe: "we left late הוא הסיבה לפספוס – because + משפט.",
      },
      {
        id: "g-linking-words-13",
        type: "fix",
        prompt: "Despite of the noise, I slept well.",
        answer: "Despite the noise, I slept well.",
        accept: ["In spite of the noise, I slept well."],
        errorType: "interference",
        explainHe: "despite בלי of. of שייך רק ל-in spite of.",
      },
      {
        id: "g-linking-words-14",
        type: "fix",
        prompt: "Even it was expensive, we bought the car.",
        answer: "Even though it was expensive, we bought the car.",
        accept: ["Although it was expensive, we bought the car.", "Though it was expensive, we bought the car."],
        errorType: "interference",
        explainHe: "even לבד = 'אפילו'. לפני משפט שלם במשמעות 'אפילו ש' – even though.",
      },
      {
        id: "g-linking-words-15",
        type: "fix",
        prompt: "I went to the bank for to open an account.",
        answer: "I went to the bank to open an account.",
        accept: ["I went to the bank in order to open an account."],
        errorType: "interference",
        explainHe: "מטרה = to + פועל. for to הוא תרגום של 'בשביל ל'.",
      },
      {
        id: "g-linking-words-16",
        type: "fix",
        prompt: "Although the bad weather, the game continued.",
        answer: "Despite the bad weather, the game continued.",
        accept: ["In spite of the bad weather, the game continued."],
        errorType: "word-choice",
        explainHe: "אחרי although צריך משפט שלם. לפני שם עצם (the bad weather) – despite / in spite of.",
      },
      {
        id: "g-linking-words-17",
        type: "fix",
        prompt: "He was tired, because he went to bed early.",
        answer: "He was tired, so he went to bed early.",
        errorType: "word-choice",
        explainHe: "העייפות היא הסיבה, וללכת לישון מוקדם היא התוצאה – so. because היה אומר שהוא עייף בגלל שהלך לישון מוקדם.",
      },
      {
        id: "g-linking-words-18",
        type: "transform",
        prompt: "Although she was ill, she went to work.",
        keyword: "despite",
        answer: "Despite being ill, she went to work.",
        accept: ["Despite her illness, she went to work.", "She went to work despite being ill."],
        explainHe: "despite לא מקבל משפט שלם, אז הופכים את she was ill ל-being ill (או her illness).",
      },
      {
        id: "g-linking-words-19",
        type: "transform",
        prompt: "It was cold. We still went swimming.",
        keyword: "even though",
        answer: "Even though it was cold, we went swimming.",
        accept: ["We went swimming even though it was cold."],
        explainHe: "even though + משפט שלם (it was cold). still נעלם – even though כבר מבטא את הניגוד.",
      },
      {
        id: "g-linking-words-20",
        type: "transform",
        prompt: "I take the bus because I want to save money.",
        keyword: "in order to",
        answer: "I take the bus in order to save money.",
        explainHe: "מטרה: in order to + פועל. I want to נעלם.",
      },
      {
        id: "g-linking-words-21",
        type: "order",
        words: ["although", "he", "was", "busy", "he", "helped", "me"],
        answer: "Although he was busy, he helped me.",
        accept: ["He helped me although he was busy."],
        explainHe: "Although + משפט שלם, פסיק, ואז המשפט הראשי.",
      },
      {
        id: "g-linking-words-22",
        type: "order",
        words: ["I", "stayed", "home", "because", "I", "didn't", "feel", "well"],
        answer: "I stayed home because I didn't feel well.",
        explainHe: "התוצאה קודם, ואז because + הסיבה.",
      },
      {
        id: "g-linking-words-23",
        type: "order",
        words: ["she", "went", "to", "bed", "early", "in", "order", "to", "wake", "up", "fresh"],
        answer: "She went to bed early in order to wake up fresh.",
        explainHe: "הפעולה קודם, ואז in order to + המטרה.",
      },
      {
        id: "g-linking-words-24",
        type: "translate",
        he: "למרות שהיה קר, יצאנו לרוץ.",
        answer: "Although it was cold, we went for a run.",
        accept: [
          "Even though it was cold, we went for a run.",
          "Though it was cold, we went for a run.",
          "Although it was cold, we went running.",
          "Even though it was cold, we went running.",
          "Despite the cold, we went for a run.",
        ],
        explainHe: "'למרות ש' + משפט = although / even though. אם רוצים despite צריך שם עצם: despite the cold.",
      },
    ],
  },

  // ------------------------------------------------------------------
  // 41. Comparatives & superlatives
  // ------------------------------------------------------------------
  {
    id: "g-comparatives-superlatives",
    title: "Comparatives & superlatives; as...as",
    titleHe: "השוואה: -er, more, the most, as...as",
    strand: "clauses",
    order: 41,
    prereqs: [],
    lesson: {
      explanationHe: [
        "כדי להשוות שני דברים, אנגלית משנה את התואר עצמו. תואר קצר (הברה אחת, או שתיים שמסתיימות ב-y) מקבל er-: taller, cheaper, happier. תואר ארוך מקבל more לפניו: more expensive, more interesting. אחרי ההשוואה באה than: taller than me.",
        "'הכי' = the + est- לתואר קצר (the tallest, the biggest), the most לתואר ארוך (the most expensive). אחרי סופרלטיב אפשר in (the best in the class) או of (the best of all).",
        "יוצאי דופן שחייבים לדעת: good – better – the best, bad – worse – the worst, far – farther – the farthest. אין more good ואין the most bad.",
        "as ... as = 'כמו' בהשוואה של שוויון: She's as tall as me. בשלילה: not as tall as = 'פחות גבוהה מ'. זו הדרך הטבעית לומר 'פחות' בדיבור.",
        "כתיב: תואר קצר שמסתיים בעיצור אחד אחרי תנועה מכפיל את העיצור: big – bigger, hot – hotter. y הופכת ל-i: easy – easier, happy – the happiest.",
        "לחיזוק: much / a lot / far + השוואה (much better), a bit / a little (a bit cheaper). לא very better.",
      ],
      form: [
        { label: "short adjective: -er / the -est", example: "cheap – cheaper – the cheapest" },
        { label: "-y adjective: -ier / the -iest", example: "easy – easier – the easiest" },
        { label: "long adjective: more / the most", example: "expensive – more expensive – the most expensive" },
        { label: "irregular", example: "good – better – the best; bad – worse – the worst" },
        { label: "comparison word: than", example: "older than me" },
        { label: "equality: as ... as / not as ... as", example: "as cheap as / not as cheap as" },
        { label: "intensifier: much / a bit + comparative", example: "much faster, a bit slower" },
      ],
      examples: [
        { en: "My new phone is faster than the old one.", he: "הטלפון החדש שלי מהיר יותר מהישן." },
        { en: "This café is more expensive than the one on the corner.", he: "בית הקפה הזה יקר יותר מזה שבפינה." },
        { en: "It's the best pizza in the city.", he: "זו הפיצה הכי טובה בעיר." },
        { en: "Yesterday was the hottest day of the year.", he: "אתמול היה היום הכי חם בשנה." },
        { en: "Her Hebrew is as good as mine.", he: "העברית שלה טובה כמו שלי." },
        { en: "The movie wasn't as good as the book.", he: "הסרט לא היה טוב כמו הספר." },
        { en: "Traffic today is much worse than usual.", he: "הפקקים היום הרבה יותר גרועים מהרגיל." },
        { en: "Which is easier, Spanish or French?", he: "מה יותר קל, ספרדית או צרפתית?" },
      ],
      contrastHe: [
        "בעברית מוסיפים 'יותר' לכל תואר: יותר גדול, יותר יקר. באנגלית ההחלטה תלויה באורך התואר: bigger אבל more expensive. לעולם לא more bigger.",
        "'יותר גבוה ממני' – ה'מ' מתורגמת ל-than, לא ל-from: taller than me.",
        "'הכי' = the + est / the most. 'הכי טוב' = the best, לא the most good.",
        "'גבוה כמו' בהשוואה = as tall as, לא as tall like ולא tall like.",
      ],
      commonErrors: [
        { wrong: "This car is more faster than mine.", right: "This car is faster than mine.", whyHe: "תואר קצר מקבל er- בלבד. more נועד לתארים ארוכים, לא מוסיפים גם וגם." },
        { wrong: "She's taller from her brother.", right: "She's taller than her brother.", whyHe: "אחרי השוואה תמיד than. ה'מ' העברית מפתה ל-from." },
        { wrong: "He's the most good player here.", right: "He's the best player here.", whyHe: "good יוצא דופן: better, the best." },
        { wrong: "It's the most big city in Israel.", right: "It's the biggest city in Israel.", whyHe: "big קצר: the biggest. the most רק לתארים ארוכים." },
        { wrong: "My English is as good like yours.", right: "My English is as good as yours.", whyHe: "המבנה הוא as ... as. like לא נכנס לכאן." },
        { wrong: "Today is more hot than yesterday.", right: "Today is hotter than yesterday.", whyHe: "hot קצר – מכפילים t ומוסיפים er." },
      ],
    },
    items: [
      {
        id: "g-comparatives-superlatives-01",
        type: "gap",
        prompt: "My brother is ___ (tall) than me.",
        answer: "taller",
        explainHe: "tall קצר – taller. לא more tall.",
      },
      {
        id: "g-comparatives-superlatives-02",
        type: "gap",
        prompt: "This restaurant is ___ (expensive) than the one near my office.",
        answer: "more expensive",
        explainHe: "expensive ארוך (שלוש הברות) – more expensive.",
      },
      {
        id: "g-comparatives-superlatives-03",
        type: "gap",
        prompt: "It was the ___ (bad) movie I've ever seen.",
        answer: "worst",
        explainHe: "bad יוצא דופן: worse, the worst.",
      },
      {
        id: "g-comparatives-superlatives-04",
        type: "gap",
        prompt: "Today is ___ (hot) than yesterday.",
        answer: "hotter",
        explainHe: "hot מסתיים בעיצור אחד אחרי תנועה – מכפילים: hotter.",
      },
      {
        id: "g-comparatives-superlatives-05",
        type: "gap",
        prompt: "She's the ___ (friendly) person in the office.",
        answer: "friendliest",
        accept: ["most friendly"],
        explainHe: "friendly מסתיים ב-y – the friendliest. גם the most friendly מקובל.",
      },
      {
        id: "g-comparatives-superlatives-06",
        type: "gap",
        prompt: "The test was ___ (easy) than I expected.",
        answer: "easier",
        explainHe: "easy – y הופכת ל-i: easier.",
      },
      {
        id: "g-comparatives-superlatives-07",
        type: "gap",
        prompt: "Who is the ___ (good) player on the team?",
        answer: "best",
        explainHe: "good יוצא דופן: better, the best. לא the most good.",
      },
      {
        id: "g-comparatives-superlatives-08",
        type: "mcq",
        prompt: "Tel Aviv is ___ than Jerusalem.",
        options: [
          { text: "more bigger", errorType: "interference", whyHe: "'יותר גדול' – אבל באנגלית לא מוסיפים גם more וגם er." },
          { text: "bigger" },
          { text: "more big", errorType: "word-choice", whyHe: "big קצר – מקבל er, לא more." },
          { text: "biger", errorType: "spelling", whyHe: "מכפילים את ה-g: bigger." },
        ],
        answerIndex: 1,
        explainHe: "big קצר: bigger (עם g כפולה).",
      },
      {
        id: "g-comparatives-superlatives-09",
        type: "mcq",
        prompt: "My car is older ___ yours.",
        options: [
          { text: "from", errorType: "interference", whyHe: "'ישן יותר משלך' – ה'מ' היא than, לא from." },
          { text: "of", errorType: "preposition", whyHe: "אחרי השוואה תמיד than." },
          { text: "than" },
          { text: "that", errorType: "spelling", whyHe: "than (השוואה), לא that." },
        ],
        answerIndex: 2,
        explainHe: "אחרי צורת השוואה – than.",
      },
      {
        id: "g-comparatives-superlatives-10",
        type: "mcq",
        prompt: "She's ___ singer in the family.",
        options: [
          { text: "the best" },
          { text: "the most good", errorType: "interference", whyHe: "'הכי טובה' – אבל good יוצא דופן: the best." },
          { text: "the better", errorType: "word-choice", whyHe: "better משווה בין שניים. 'הכי' במשפחה – the best." },
          { text: "the goodest", errorType: "word-form" as never, whyHe: "אין goodest. good – better – best." },
        ],
        answerIndex: 0,
        explainHe: "סופרלטיב של good – the best.",
      },
      {
        id: "g-comparatives-superlatives-11",
        type: "mcq",
        prompt: "Her English is ___ mine.",
        options: [
          { text: "as good like", errorType: "interference", whyHe: "'טובה כמו' מפתה ל-like, אבל המבנה הוא as ... as." },
          { text: "so good as", errorType: "word-choice", whyHe: "so ... as נדיר ורק בשלילה. בחיוב: as ... as." },
          { text: "good as", errorType: "other", whyHe: "חסר ה-as הראשון: as good as." },
          { text: "as good as" },
        ],
        answerIndex: 3,
        explainHe: "שוויון = as + תואר + as.",
      },
      {
        id: "g-comparatives-superlatives-12",
        type: "mcq",
        prompt: "This book is ___ interesting than the movie.",
        options: [
          { text: "much more" },
          { text: "very more", errorType: "word-choice", whyHe: "very לא מחזק השוואה. much / a lot / far + more." },
          { text: "more much", errorType: "word-order", whyHe: "המחזק בא לפני more: much more." },
          { text: "much", errorType: "other", whyHe: "חסר more – interesting ארוך וצריך more לפניו." },
        ],
        answerIndex: 0,
        explainHe: "מחזקים השוואה עם much: much more interesting.",
      },
      {
        id: "g-comparatives-superlatives-13",
        type: "fix",
        prompt: "My new apartment is more smaller than the old one.",
        answer: "My new apartment is smaller than the old one.",
        errorType: "interference",
        explainHe: "small קצר – smaller בלבד. more + er יחד זו שגיאה של 'יותר קטן'.",
      },
      {
        id: "g-comparatives-superlatives-14",
        type: "fix",
        prompt: "He is stronger from his brother.",
        answer: "He is stronger than his brother.",
        errorType: "interference",
        explainHe: "השוואה = than. from הוא תרגום של 'מ'.",
      },
      {
        id: "g-comparatives-superlatives-15",
        type: "fix",
        prompt: "It's the most cheap phone in the store.",
        answer: "It's the cheapest phone in the store.",
        errorType: "word-choice",
        explainHe: "cheap קצר – the cheapest. the most רק לתארים ארוכים.",
      },
      {
        id: "g-comparatives-superlatives-16",
        type: "fix",
        prompt: "Your bag is heavy as mine.",
        answer: "Your bag is as heavy as mine.",
        errorType: "other",
        explainHe: "המבנה דורש שני as: as heavy as.",
      },
      {
        id: "g-comparatives-superlatives-17",
        type: "fix",
        prompt: "This is the more beautiful beach in Israel.",
        answer: "This is the most beautiful beach in Israel.",
        errorType: "word-choice",
        explainHe: "'הכי יפה' מבין כולם – the most beautiful. more משווה רק בין שניים.",
      },
      {
        id: "g-comparatives-superlatives-18",
        type: "transform",
        prompt: "Dan is taller than Omer.",
        keyword: "as",
        answer: "Omer isn't as tall as Dan.",
        accept: ["Omer isn't as tall as Dan is.", "Omer is not as tall as Dan."],
        explainHe: "'פחות גבוה' בדיבור = not as tall as. הופכים את הסדר: עומר לא גבוה כמו דן.",
      },
      {
        id: "g-comparatives-superlatives-19",
        type: "transform",
        prompt: "I have never seen a bigger dog.",
        keyword: "biggest",
        answer: "This is the biggest dog I have ever seen.",
        accept: ["It's the biggest dog I have ever seen.", "That's the biggest dog I have ever seen.", "This is the biggest dog I've ever seen."],
        explainHe: "'אף פעם לא ראיתי יותר גדול' = 'זה הכי גדול שראיתי': the biggest ... I have ever seen.",
      },
      {
        id: "g-comparatives-superlatives-20",
        type: "transform",
        prompt: "The blue shirt is cheaper than the red one.",
        keyword: "expensive",
        answer: "The red shirt is more expensive than the blue one.",
        accept: ["The red one is more expensive than the blue one.", "The red shirt is more expensive than the blue shirt."],
        explainHe: "הופכים את הכיוון: האדומה יקרה יותר. expensive ארוך – more expensive.",
      },
      {
        id: "g-comparatives-superlatives-21",
        type: "order",
        words: ["this", "winter", "is", "colder", "than", "last", "year"],
        answer: "This winter is colder than last year.",
        explainHe: "נושא + is + השוואה (colder) + than + מושא ההשוואה.",
      },
      {
        id: "g-comparatives-superlatives-22",
        type: "order",
        words: ["she", "is", "the", "most", "talented", "student", "in", "the", "class"],
        answer: "She is the most talented student in the class.",
        explainHe: "the most + תואר ארוך + שם עצם, ואז in + הקבוצה.",
      },
      {
        id: "g-comparatives-superlatives-23",
        type: "order",
        words: ["my", "job", "isn't", "as", "stressful", "as", "yours"],
        answer: "My job isn't as stressful as yours.",
        explainHe: "not as + תואר + as: 'פחות מלחיץ משלך'.",
      },
      {
        id: "g-comparatives-superlatives-24",
        type: "translate",
        he: "האח שלי יותר גבוה ממני.",
        answer: "My brother is taller than me.",
        accept: ["My brother is taller than I am.", "My brother is taller than I."],
        explainHe: "'יותר גבוה' = taller (בלי more), 'ממני' = than me.",
      },
    ],
  },

  // ------------------------------------------------------------------
  // 42. so / such / too / enough
  // ------------------------------------------------------------------
  {
    id: "g-so-such-too-enough",
    title: "so / such / too / enough",
    titleHe: "so, such, too, enough",
    strand: "clauses",
    order: 42,
    prereqs: ["g-comparatives-superlatives"],
    lesson: {
      explanationHe: [
        "so ו-such שניהם 'כל כך', אבל הם עומדים במקומות שונים. so לפני תואר או תואר פועל לבד: so hot, so fast. such לפני שם עצם (עם או בלי תואר): such a hot day, such nice people. הכלל הפשוט: אם יש שם עצם – such.",
        "עם שם עצם ספיר ביחיד, such מקבל a/an: such a good idea. ברבים ובלא-ספיר – בלי: such good ideas, such bad weather. עם כמויות: so many + רבים, so much + לא ספיר.",
        "so ... that / such ... that מתארים תוצאה: I was so tired that I fell asleep. It was such a long day that I went straight to bed.",
        "too = 'מדי', כלומר יותר ממה שאפשר, וזה תמיד שלילי: too hot to drink. too לא אומר 'מאוד'! אם המסיבה הייתה מעולה – so good / really good, לא too good.",
        "enough = 'מספיק'. אחרי תואר או תואר פועל: good enough, fast enough. לפני שם עצם: enough money, enough time. אחריו אפשר to + פועל: old enough to drive.",
      ],
      form: [
        { label: "so + adjective / adverb", example: "so cold, so quickly" },
        { label: "such + a/an + (adj) + singular noun", example: "such a good idea" },
        { label: "such + (adj) + plural / uncountable", example: "such nice people, such bad luck" },
        { label: "so many + plural / so much + uncountable", example: "so many people, so much noise" },
        { label: "so / such ... that", example: "so late that we missed it" },
        { label: "too + adjective (+ to)", example: "too expensive to buy" },
        { label: "adjective + enough (+ to) / enough + noun", example: "warm enough to swim, enough chairs" },
      ],
      examples: [
        { en: "The soup is so hot that I can't eat it.", he: "המרק כל כך חם שאני לא יכול לאכול אותו." },
        { en: "It was such a boring meeting.", he: "זו הייתה פגישה כל כך משעממת." },
        { en: "They're such nice neighbors.", he: "הם שכנים כל כך נחמדים." },
        { en: "There were so many people that we couldn't find a seat.", he: "היו כל כך הרבה אנשים שלא מצאנו מקום." },
        { en: "This coffee is too strong for me.", he: "הקפה הזה חזק מדי בשבילי." },
        { en: "He's not old enough to drive.", he: "הוא לא מספיק מבוגר כדי לנהוג." },
        { en: "We don't have enough time to finish.", he: "אין לנו מספיק זמן לסיים." },
        { en: "The concert was so good!", he: "ההופעה הייתה כל כך טובה!" },
      ],
      contrastHe: [
        "'כל כך' אחד בעברית, שניים באנגלית: so לפני תואר (so nice), such לפני שם עצם (such a nice guy). 'יום כל כך יפה' = such a beautiful day.",
        "בעברית 'מדי' בא אחרי התואר (חם מדי). באנגלית too לפני: too hot. ו-too לא 'מאוד' – I love it too much הוא שגיאה, אומרים so much.",
        "בעברית 'מספיק' לפני התואר (מספיק טוב). באנגלית אחרי: good enough. אבל לפני שם עצם: enough money.",
        "'כל כך הרבה' = so many (ספיר) / so much (לא ספיר). so much people – שגוי.",
      ],
      commonErrors: [
        { wrong: "It was so nice day.", right: "It was such a nice day.", whyHe: "יש שם עצם (day) – לכן such, ועם a כי day ספיר ביחיד." },
        { wrong: "The food was too delicious!", right: "The food was so delicious!", whyHe: "too = יותר מדי, שלילי. למחמאה: so / really / very." },
        { wrong: "He's enough tall to reach the shelf.", right: "He's tall enough to reach the shelf.", whyHe: "enough בא אחרי תואר: tall enough." },
        { wrong: "It's too much expensive.", right: "It's too expensive.", whyHe: "לפני תואר – too לבד. too much רק לפני שם עצם לא ספיר (too much sugar)." },
        { wrong: "She has so much friends.", right: "She has so many friends.", whyHe: "friends ספיר ברבים – so many. so much לשמות עצם לא ספירים." },
        { wrong: "I was such tired that I went to bed.", right: "I was so tired that I went to bed.", whyHe: "tired הוא תואר בלי שם עצם אחריו – so." },
      ],
    },
    items: [
      {
        id: "g-so-such-too-enough-01",
        type: "gap",
        prompt: "It was ___ a great party!",
        answer: "such",
        hint: "so / such",
        explainHe: "יש שם עצם (party) עם a – such a great party.",
      },
      {
        id: "g-so-such-too-enough-02",
        type: "gap",
        prompt: "The coffee is ___ hot to drink.",
        answer: "too",
        hint: "so / too / enough",
        explainHe: "'חם מדי לשתייה' – too + תואר + to. too לפני התואר.",
      },
      {
        id: "g-so-such-too-enough-03",
        type: "gap",
        prompt: "He isn't old ___ to drive.",
        answer: "enough",
        hint: "too / enough",
        explainHe: "'מספיק מבוגר' – old enough. enough אחרי התואר.",
      },
      {
        id: "g-so-such-too-enough-04",
        type: "gap",
        prompt: "I was ___ tired that I fell asleep on the bus.",
        answer: "so",
        hint: "so / such",
        explainHe: "tired הוא תואר בלי שם עצם – so tired that.",
      },
      {
        id: "g-so-such-too-enough-05",
        type: "gap",
        prompt: "She has ___ many books that she needs another shelf.",
        answer: "so",
        hint: "so / such / too",
        explainHe: "so many + רבים. such לא מתחבר עם many.",
      },
      {
        id: "g-so-such-too-enough-06",
        type: "gap",
        prompt: "There isn't ___ time to finish everything.",
        answer: "enough",
        hint: "too / enough",
        explainHe: "לפני שם עצם – enough time. (אחרי תואר: good enough).",
      },
      {
        id: "g-so-such-too-enough-07",
        type: "gap",
        prompt: "They're ___ nice people.",
        answer: "such",
        hint: "so / such",
        explainHe: "יש שם עצם ברבים (people) – such, בלי a.",
      },
      {
        id: "g-so-such-too-enough-08",
        type: "mcq",
        prompt: "It was ___ cold that the lake froze.",
        options: [
          { text: "such", errorType: "word-choice", whyHe: "cold כאן תואר בלי שם עצם – so, לא such." },
          { text: "so" },
          { text: "too", errorType: "word-choice", whyHe: "too מתחבר עם to (too cold to swim), לא עם that." },
          { text: "very", errorType: "other", whyHe: "very לא מתחבר עם that. לתוצאה: so ... that." },
        ],
        answerIndex: 1,
        explainHe: "תוצאה: so + תואר + that.",
      },
      {
        id: "g-so-such-too-enough-09",
        type: "mcq",
        prompt: "She's ___ good cook.",
        options: [
          { text: "so", errorType: "word-choice", whyHe: "יש שם עצם (cook) – צריך such a." },
          { text: "so a", errorType: "word-order", whyHe: "so לא בא לפני a + שם עצם. such a." },
          { text: "such", errorType: "article", whyHe: "cook ספיר ביחיד – such a good cook." },
          { text: "such a" },
        ],
        answerIndex: 3,
        explainHe: "such + a + תואר + שם עצם ביחיד.",
      },
      {
        id: "g-so-such-too-enough-10",
        type: "mcq",
        prompt: "This bag is ___ to carry.",
        options: [
          { text: "too heavy" },
          { text: "very heavy", errorType: "word-choice", whyHe: "very לא מתחבר עם to. 'כבד מדי בשביל' = too heavy to." },
          { text: "too much heavy", errorType: "interference", whyHe: "לפני תואר – too לבד. too much רק לפני שם עצם." },
          { text: "enough heavy", errorType: "word-order", whyHe: "enough בא אחרי תואר, וגם המשמעות לא מתאימה כאן." },
        ],
        answerIndex: 0,
        explainHe: "'כבד מדי' = too heavy, ואחריו to + פועל.",
      },
      {
        id: "g-so-such-too-enough-11",
        type: "mcq",
        prompt: "Is the water ___ to swim?",
        options: [
          { text: "enough warm", errorType: "interference", whyHe: "'מספיק חם' בעברית לפני, באנגלית אחרי: warm enough." },
          { text: "warm enough" },
          { text: "too warm", errorType: "word-choice", whyHe: "too warm to swim = חם מדי בשביל לשחות, לא השאלה כאן." },
          { text: "warm too much", errorType: "word-order", whyHe: "too לפני תואר, ולא too much." },
        ],
        answerIndex: 1,
        explainHe: "enough אחרי התואר: warm enough to swim.",
      },
      {
        id: "g-so-such-too-enough-12",
        type: "mcq",
        prompt: "I loved the concert. It was ___!",
        options: [
          { text: "too good", errorType: "interference", whyHe: "too = יותר מדי, שלילי. למחמאה – so good." },
          { text: "such good", errorType: "word-choice", whyHe: "good בלי שם עצם – so, לא such." },
          { text: "so good" },
          { text: "so a good", errorType: "word-order", whyHe: "so לא מקבל a. או so good או such a good concert." },
        ],
        answerIndex: 2,
        explainHe: "מחמאה עם תואר לבד – so good. too היה אומר 'טוב מדי'.",
      },
      {
        id: "g-so-such-too-enough-13",
        type: "fix",
        prompt: "It was so beautiful day that we stayed outside.",
        answer: "It was such a beautiful day that we stayed outside.",
        errorType: "word-choice",
        explainHe: "יש שם עצם (day) – such a beautiful day.",
      },
      {
        id: "g-so-such-too-enough-14",
        type: "fix",
        prompt: "He's not enough strong to lift it.",
        answer: "He's not strong enough to lift it.",
        errorType: "word-order",
        explainHe: "enough אחרי התואר: strong enough.",
      },
      {
        id: "g-so-such-too-enough-15",
        type: "fix",
        prompt: "The exam was too much difficult.",
        answer: "The exam was too difficult.",
        errorType: "interference",
        explainHe: "לפני תואר – too לבד. too much רק לפני שם עצם לא ספיר.",
      },
      {
        id: "g-so-such-too-enough-16",
        type: "fix",
        prompt: "I like this song too much!",
        answer: "I like this song so much!",
        accept: ["I really like this song!", "I like this song very much!"],
        errorType: "word-choice",
        explainHe: "too much = יותר מדי (שלילי). 'אני כל כך אוהב' = so much.",
      },
      {
        id: "g-so-such-too-enough-17",
        type: "fix",
        prompt: "There were so much people at the beach.",
        answer: "There were so many people at the beach.",
        errorType: "countability",
        explainHe: "people ספיר ברבים – so many.",
      },
      {
        id: "g-so-such-too-enough-18",
        type: "transform",
        prompt: "The box is very heavy. I can't lift it.",
        keyword: "too",
        answer: "The box is too heavy to lift.",
        accept: ["The box is too heavy for me to lift."],
        explainHe: "'כבד מדי בשביל להרים' = too heavy to lift. בלי it בסוף.",
      },
      {
        id: "g-so-such-too-enough-19",
        type: "transform",
        prompt: "The movie was so boring that we left.",
        keyword: "such",
        answer: "It was such a boring movie that we left.",
        explainHe: "מוסיפים שם עצם (movie) ולכן so הופך ל-such a.",
      },
      {
        id: "g-so-such-too-enough-20",
        type: "transform",
        prompt: "He is too young to vote.",
        keyword: "enough",
        answer: "He isn't old enough to vote.",
        explainHe: "'צעיר מדי' = 'לא מספיק מבוגר': not old enough.",
      },
      {
        id: "g-so-such-too-enough-21",
        type: "order",
        words: ["she", "was", "so", "tired", "that", "she", "went", "to", "bed", "early"],
        answer: "She was so tired that she went to bed early.",
        explainHe: "so + תואר + that + תוצאה.",
      },
      {
        id: "g-so-such-too-enough-22",
        type: "order",
        words: ["it", "was", "such", "a", "long", "day"],
        answer: "It was such a long day.",
        explainHe: "such + a + תואר + שם עצם.",
      },
      {
        id: "g-so-such-too-enough-23",
        type: "order",
        words: ["is", "the", "room", "big", "enough", "for", "everyone"],
        answer: "Is the room big enough for everyone?",
        explainHe: "תואר + enough + for.",
      },
      {
        id: "g-so-such-too-enough-24",
        type: "translate",
        he: "הקפה חם מדי לשתייה.",
        answer: "The coffee is too hot to drink.",
        explainHe: "'חם מדי' = too hot (too לפני), 'לשתייה' = to drink.",
      },
    ],
  },

  // ------------------------------------------------------------------
  // 43. Adverb position
  // ------------------------------------------------------------------
  {
    id: "g-adverb-position",
    title: "Adverb position & frequency adverbs",
    titleHe: "מיקום תוארי פועל",
    strand: "word-order",
    order: 43,
    prereqs: [],
    lesson: {
      explanationHe: [
        "תוארי פועל של תדירות (always, usually, often, sometimes, rarely, never) עומדים באנגלית לפני הפועל הראשי: I always drink coffee. בעברית הם באים אחרי הפועל ('אני שותה תמיד') – ומכאן השגיאה הנפוצה I drink always coffee.",
        "יש שני יוצאי דופן. אחרי הפועל be הם באים אחריו: She is always late. ואם יש פועל עזר (have, can, will, don't), הם באים בין פועל העזר לפועל הראשי: I have never been there, I can always help, I don't usually eat meat.",
        "sometimes ו-usually גמישים ויכולים גם לפתוח משפט (Sometimes I walk to work). always ו-never כמעט תמיד באמצע. also, still, already, just מתנהגים כמו תוארי תדירות: I still don't understand, I've already eaten.",
        "תוארי אופן (well, carefully, quickly) באים בדרך כלל בסוף המשפט, ולעולם לא בין הפועל למושא: She speaks English well – לא She speaks well English. אם יש גם מקום וגם זמן, הסדר הוא אופן, מקום, זמן: I worked hard at home yesterday.",
        "בשאלות תואר התדירות נשאר לפני הפועל הראשי: Do you usually work on Fridays? Have you ever been to Rome?",
      ],
      form: [
        { label: "adverb + main verb", example: "I usually get up at six." },
        { label: "be + adverb", example: "He is never on time." },
        { label: "auxiliary + adverb + verb", example: "We have never met. / I can always try." },
        { label: "don't + adverb + verb", example: "I don't often cook." },
        { label: "question: Do you + adverb + verb", example: "Do you always take the bus?" },
        { label: "manner adverb at the end", example: "She sings beautifully." },
        { label: "verb + object + adverb", example: "He speaks Hebrew fluently." },
      ],
      examples: [
        { en: "I always check my email before breakfast.", he: "אני תמיד בודק מיילים לפני ארוחת הבוקר." },
        { en: "She is usually home by seven.", he: "היא בדרך כלל בבית עד שבע." },
        { en: "We have never been to Greece.", he: "אף פעם לא היינו ביוון." },
        { en: "He doesn't often go out during the week.", he: "הוא לא יוצא הרבה באמצע השבוע." },
        { en: "Do you usually cook on weekends?", he: "אתה בדרך כלל מבשל בסופי שבוע?" },
        { en: "My brother plays the guitar really well.", he: "אחי מנגן בגיטרה ממש טוב." },
        { en: "I've already finished the report.", he: "כבר סיימתי את הדוח." },
        { en: "Sometimes I work from home.", he: "לפעמים אני עובד מהבית." },
      ],
      contrastHe: [
        "בעברית: 'אני הולך תמיד לחדר כושר' – תמיד אחרי הפועל. באנגלית: I always go to the gym – always לפני הפועל.",
        "בעברית: 'היא מדברת טוב אנגלית'. באנגלית המושא צמוד לפועל: She speaks English well. תואר האופן בסוף.",
        "'אני אף פעם לא' – שתי מילות שלילה בעברית. באנגלית never לבד, בלי don't: I never drink coffee, לא I don't never drink.",
        "עם הפועל be הכיוון מתהפך: 'הוא תמיד מאחר' = He is always late (אחרי is), אבל עם פועל רגיל: He always arrives late.",
      ],
      commonErrors: [
        { wrong: "I go always to work by train.", right: "I always go to work by train.", whyHe: "תואר תדירות לפני הפועל הראשי. זה תרגום של 'אני הולך תמיד'." },
        { wrong: "She always is tired in the morning.", right: "She is always tired in the morning.", whyHe: "עם be התואר בא אחרי הפועל: is always." },
        { wrong: "I have seen never this movie.", right: "I have never seen this movie.", whyHe: "עם פועל עזר, התואר עומד בין have לפועל: have never seen." },
        { wrong: "He speaks very well English.", right: "He speaks English very well.", whyHe: "לא מפרידים בין הפועל למושא. תואר האופן בסוף." },
        { wrong: "I don't never eat meat.", right: "I never eat meat.", whyHe: "never כבר שלילי. שלילה כפולה (don't + never) שגויה." },
        { wrong: "They eat usually dinner at eight.", right: "They usually eat dinner at eight.", whyHe: "usually לפני הפועל eat." },
      ],
    },
    items: [
      {
        id: "g-adverb-position-01",
        type: "gap",
        prompt: "I ___ coffee in the morning. (usually / drink)",
        answer: "usually drink",
        hint: "put the two words in the right order",
        explainHe: "תואר תדירות לפני הפועל הראשי: usually drink.",
      },
      {
        id: "g-adverb-position-02",
        type: "gap",
        prompt: "She ___ late for work. (is / never)",
        answer: "is never",
        hint: "put the two words in the right order",
        explainHe: "עם be התואר בא אחרי: is never.",
      },
      {
        id: "g-adverb-position-03",
        type: "gap",
        prompt: "We ___ been to Eilat. (never / have)",
        answer: "have never",
        hint: "put the two words in the right order",
        explainHe: "פועל עזר + תואר + פועל: have never been.",
      },
      {
        id: "g-adverb-position-04",
        type: "gap",
        prompt: "They ___ tennis on Sundays. (often / play)",
        answer: "often play",
        hint: "put the two words in the right order",
        explainHe: "often לפני הפועל הראשי play.",
      },
      {
        id: "g-adverb-position-05",
        type: "gap",
        prompt: "He ___ me with my homework. (always / can / help)",
        answer: "can always help",
        hint: "put the three words in the right order",
        explainHe: "מודאל (can) + תואר + פועל: can always help.",
      },
      {
        id: "g-adverb-position-06",
        type: "mcq",
        prompt: "Choose the correct sentence.",
        options: [
          { text: "I work always from home on Fridays.", errorType: "interference", whyHe: "'אני עובד תמיד' – בעברית אחרי הפועל, באנגלית לפני." },
          { text: "I always work from home on Fridays." },
          { text: "I work from home always on Fridays.", errorType: "word-order", whyHe: "always לא בא בסוף או אחרי המושא." },
          { text: "Always I work from home on Fridays.", errorType: "word-order", whyHe: "always לא פותח משפט (בניגוד ל-sometimes / usually)." },
        ],
        answerIndex: 1,
        explainHe: "always לפני הפועל הראשי work.",
      },
      {
        id: "g-adverb-position-07",
        type: "mcq",
        prompt: "She speaks ___.",
        options: [
          { text: "very well English", errorType: "interference", whyHe: "'מדברת טוב אנגלית' – באנגלית המושא צמוד לפועל: English very well." },
          { text: "English very good", errorType: "word-choice", whyHe: "good הוא תואר לשם עצם. את הפועל speaks מתאר תואר הפועל well." },
          { text: "English very well" },
          { text: "well very English", errorType: "word-order", whyHe: "very לפני well, והמושא לפני שניהם." },
        ],
        answerIndex: 2,
        explainHe: "פועל + מושא + תואר אופן: speaks English very well.",
      },
      {
        id: "g-adverb-position-08",
        type: "mcq",
        prompt: "He ___ late.",
        options: [
          { text: "never is", errorType: "word-order", whyHe: "עם be התואר בא אחריו: is never." },
          { text: "is not never", errorType: "other", whyHe: "never כבר שלילי – אין not + never." },
          { text: "is never" },
          { text: "never", errorType: "verb-form", whyHe: "חסר הפועל is." },
        ],
        answerIndex: 2,
        explainHe: "be + תואר תדירות: is never late.",
      },
      {
        id: "g-adverb-position-09",
        type: "mcq",
        prompt: "I ___ understand this rule.",
        options: [
          { text: "still don't" },
          { text: "don't still", errorType: "word-order", whyHe: "still בא לפני don't: still don't." },
          { text: "still not", errorType: "verb-form", whyHe: "חסר פועל עזר: still don't understand." },
          { text: "not still", errorType: "word-order", whyHe: "גם הסדר שגוי וגם חסר do." },
        ],
        answerIndex: 0,
        explainHe: "still עומד לפני הפועל השלילי: I still don't understand.",
      },
      {
        id: "g-adverb-position-10",
        type: "fix",
        prompt: "I go always to the gym after work.",
        answer: "I always go to the gym after work.",
        errorType: "word-order",
        explainHe: "always לפני הפועל הראשי go.",
      },
      {
        id: "g-adverb-position-11",
        type: "fix",
        prompt: "She speaks very well English.",
        answer: "She speaks English very well.",
        errorType: "word-order",
        explainHe: "לא מפרידים בין הפועל למושא. תואר האופן בסוף.",
      },
      {
        id: "g-adverb-position-12",
        type: "fix",
        prompt: "We have seen never such a big dog.",
        answer: "We have never seen such a big dog.",
        errorType: "word-order",
        explainHe: "never בין פועל העזר have לפועל seen.",
      },
      {
        id: "g-adverb-position-13",
        type: "fix",
        prompt: "He drives carefully always.",
        answer: "He always drives carefully.",
        errorType: "word-order",
        explainHe: "always לפני הפועל, carefully (אופן) בסוף.",
      },
      {
        id: "g-adverb-position-14",
        type: "transform",
        prompt: "I am late for work. This never happens.",
        keyword: "never",
        answer: "I am never late for work.",
        explainHe: "עם be: am never late.",
      },
      {
        id: "g-adverb-position-15",
        type: "transform",
        prompt: "I go to bed at 11 on most nights.",
        keyword: "usually",
        answer: "I usually go to bed at 11.",
        accept: ["Usually I go to bed at 11.", "I usually go to bed at eleven.", "I usually go to bed at 11 at night."],
        explainHe: "'ברוב הלילות' = usually, לפני הפועל go.",
      },
      {
        id: "g-adverb-position-16",
        type: "order",
        words: ["I", "always", "have", "breakfast", "at", "seven"],
        answer: "I always have breakfast at seven.",
        explainHe: "always לפני הפועל הראשי have (כאן have = אוכל, לא פועל עזר).",
      },
      {
        id: "g-adverb-position-17",
        type: "order",
        words: ["she", "is", "usually", "very", "busy", "on", "Mondays"],
        answer: "She is usually very busy on Mondays.",
        accept: ["Usually she is very busy on Mondays."],
        explainHe: "עם be: is usually. הזמן (on Mondays) בסוף.",
      },
      {
        id: "g-adverb-position-18",
        type: "order",
        words: ["we", "have", "never", "eaten", "sushi"],
        answer: "We have never eaten sushi.",
        explainHe: "תוארי תדירות כמו never באים בין פועל העזר לפועל העיקרי: have never eaten.",
      },
      {
        id: "g-adverb-position-19",
        type: "order",
        words: ["he", "plays", "the", "guitar", "really", "well"],
        answer: "He plays the guitar really well.",
        explainHe: "פועל + מושא (the guitar) + תואר אופן (really well) בסוף.",
      },
      {
        id: "g-adverb-position-20",
        type: "order",
        words: ["they", "often", "go", "to", "the", "beach", "in", "summer"],
        answer: "They often go to the beach in summer.",
        accept: ["In summer they often go to the beach."],
        explainHe: "often לפני go. מקום (to the beach) לפני זמן (in summer).",
      },
      {
        id: "g-adverb-position-21",
        type: "order",
        words: ["I", "can", "never", "remember", "her", "name"],
        answer: "I can never remember her name.",
        explainHe: "מודאל + never + פועל: can never remember.",
      },
      {
        id: "g-adverb-position-22",
        type: "order",
        words: ["do", "you", "usually", "work", "on", "Fridays"],
        answer: "Do you usually work on Fridays?",
        explainHe: "בשאלה: Do you + usually + פועל.",
      },
      {
        id: "g-adverb-position-23",
        type: "order",
        words: ["I", "have", "already", "finished", "my", "homework"],
        answer: "I have already finished my homework.",
        accept: ["I have finished my homework already."],
        explainHe: "already בין have לפועל: have already finished.",
      },
      {
        id: "g-adverb-position-24",
        type: "translate",
        he: "אני אף פעם לא שותה קפה בערב.",
        answer: "I never drink coffee in the evening.",
        accept: ["I never drink coffee at night.", "I never drink coffee in the evenings."],
        explainHe: "'אף פעם לא' = never לבד (בלי don't), לפני הפועל drink.",
      },
    ],
  },

  // ------------------------------------------------------------------
  // 44. Adjective order & -ed / -ing adjectives
  // ------------------------------------------------------------------
  {
    id: "g-adjective-order",
    title: "Adjective order & -ed / -ing adjectives",
    titleHe: "סדר תארים ו-ed/-ing",
    strand: "word-order",
    order: 44,
    prereqs: [],
    lesson: {
      explanationHe: [
        "באנגלית התואר בא לפני שם העצם – הפוך מעברית: 'בית גדול' = a big house, 'חולצה כחולה' = a blue shirt. ותואר אף פעם לא מקבל צורת רבים: big houses, לא bigs houses.",
        "כשיש כמה תארים יש סדר קבוע: דעה – גודל – גיל – צורה – צבע – מוצא – חומר. בפועל מספיק לזכור: קודם דעה (beautiful, nice), אחר כך גודל (big), גיל (old), צבע (red), מוצא (Italian), חומר (wooden): a beautiful old Italian car, a small wooden table.",
        "בדיבור נדיר להשתמש ביותר משניים-שלושה תארים. מה שחשוב: הדעה תמיד ראשונה, החומר או המוצא תמיד צמודים לשם העצם.",
        "תארים ב-ed וב-ing: ing- מתאר את מה שגורם לרגש (a boring movie – הסרט משעמם), ed- מתאר את מי שמרגיש (I'm bored – אני משועמם). I'm boring פירושו 'אני אדם משעמם' – לא מה שהתכוונתם.",
        "זוגות שימושיים: interested / interesting, excited / exciting, tired / tiring, surprised / surprising, confused / confusing, embarrassed / embarrassing, disappointed / disappointing. בעברית ההבדל הוא בין בניינים (משועמם / משעמם), באנגלית בין ed ל-ing.",
        "מילות יחס אחרי תארי ed: interested in, excited about, bored with, tired of, surprised by, disappointed with.",
      ],
      form: [
        { label: "adjective + noun", example: "a red car (not: a car red)" },
        { label: "opinion + size + age", example: "a nice big old house" },
        { label: "age + color + origin / material", example: "an old blue Japanese car / a small wooden box" },
        { label: "no plural on adjectives", example: "three old friends" },
        { label: "-ing = the cause", example: "The lesson was boring." },
        { label: "-ed = the feeling", example: "The students were bored." },
        { label: "-ed + preposition", example: "interested in, excited about, tired of" },
      ],
      examples: [
        { en: "She lives in a small white house near the beach.", he: "היא גרה בבית לבן קטן ליד הים." },
        { en: "He drives a big old German car.", he: "הוא נוהג באוטו גרמני גדול וישן." },
        { en: "I bought a beautiful wooden table.", he: "קניתי שולחן עץ יפהפה." },
        { en: "The meeting was long and boring.", he: "הפגישה הייתה ארוכה ומשעממת." },
        { en: "I was bored, so I left early.", he: "השתעממתי, אז הלכתי מוקדם." },
        { en: "It's an exciting project, and I'm excited to start.", he: "זה פרויקט מרגש, ואני נרגש להתחיל." },
        { en: "The instructions were confusing.", he: "ההוראות היו מבלבלות." },
        { en: "I'm interested in learning Italian.", he: "מעניין אותי ללמוד איטלקית." },
      ],
      contrastHe: [
        "בעברית התואר אחרי שם העצם: 'שולחן קטן'. באנגלית לפני: a small table. וללא ריבוי: 'ילדים קטנים' = small children, לא smalls children.",
        "בעברית 'משעמם' (הסרט) מול 'משועמם' (אני). באנגלית: boring מול bored. I'm boring = 'אני משעמם' – שגיאה מביכה.",
        "'מעניין אותי' – באנגלית I'm interested in, לא I'm interesting ולא It interests me.",
        "בעברית סדר התארים חופשי יחסית ('אוטו ישן גדול' או 'גדול ישן'). באנגלית קבוע: a big old car.",
      ],
      commonErrors: [
        { wrong: "She has a car new.", right: "She has a new car.", whyHe: "תואר לפני שם העצם. הסדר העברי הפוך." },
        { wrong: "I'm very boring in this lecture.", right: "I'm very bored in this lecture.", whyHe: "מי שמרגיש – ed. boring = משעמם (הרצאה או אדם משעמם)." },
        { wrong: "The movie was so bored.", right: "The movie was so boring.", whyHe: "הסרט גורם לשעמום – ing." },
        { wrong: "They bought a wooden big table.", right: "They bought a big wooden table.", whyHe: "גודל לפני חומר: big wooden." },
        { wrong: "We saw many olds buildings.", right: "We saw many old buildings.", whyHe: "תארים באנגלית לא מקבלים s ברבים." },
        { wrong: "I'm interesting in history.", right: "I'm interested in history.", whyHe: "אני מתעניין = interested in. interesting = מעניין." },
      ],
    },
    items: [
      {
        id: "g-adjective-order-01",
        type: "gap",
        prompt: "The lecture was so ___ (bore) that half the room fell asleep.",
        answer: "boring",
        explainHe: "ההרצאה גורמת לשעמום – boring.",
      },
      {
        id: "g-adjective-order-02",
        type: "gap",
        prompt: "I was really ___ (surprise) by the news.",
        answer: "surprised",
        explainHe: "אני מרגיש – surprised. החדשות היו surprising.",
      },
      {
        id: "g-adjective-order-03",
        type: "gap",
        prompt: "We had a ___ (tire) day at the beach.",
        answer: "tiring",
        explainHe: "היום גרם לעייפות – tiring. אנחנו היינו tired.",
      },
      {
        id: "g-adjective-order-04",
        type: "gap",
        prompt: "She's ___ (interest) in photography.",
        answer: "interested",
        explainHe: "היא מתעניינת – interested in. הצילום הוא interesting.",
      },
      {
        id: "g-adjective-order-05",
        type: "gap",
        prompt: "What an ___ (excite) game!",
        answer: "exciting",
        explainHe: "המשחק מרגש – exciting. הצופים היו excited.",
      },
      {
        id: "g-adjective-order-06",
        type: "mcq",
        prompt: "She bought a ___ dress.",
        options: [
          { text: "red beautiful silk", errorType: "word-order", whyHe: "דעה (beautiful) תמיד ראשונה." },
          { text: "beautiful red silk" },
          { text: "silk red beautiful", errorType: "word-order", whyHe: "סדר הפוך. החומר (silk) צמוד לשם העצם." },
          { text: "beautiful silk red", errorType: "word-order", whyHe: "צבע לפני חומר: red silk." },
        ],
        answerIndex: 1,
        explainHe: "דעה – צבע – חומר: beautiful red silk dress.",
      },
      {
        id: "g-adjective-order-07",
        type: "mcq",
        prompt: "I'm ___ with this job. I want to quit.",
        options: [
          { text: "boring", errorType: "interference", whyHe: "I'm boring = 'אני משעמם'. מי שמרגיש – bored." },
          { text: "bore", errorType: "verb-form", whyHe: "bore הוא פועל. צריך תואר: bored." },
          { text: "bored" },
          { text: "bores", errorType: "verb-form", whyHe: "bores הוא פועל בגוף שלישי. צריך תואר: bored." },
        ],
        answerIndex: 2,
        explainHe: "אני משועמם = bored (with).",
      },
      {
        id: "g-adjective-order-08",
        type: "mcq",
        prompt: "He lives in ___.",
        options: [
          { text: "an old big house", errorType: "word-order", whyHe: "גודל לפני גיל: big old." },
          { text: "a house big old", errorType: "interference", whyHe: "סדר עברי – התארים באנגלית לפני שם העצם." },
          { text: "a big old house" },
        ],
        answerIndex: 2,
        explainHe: "תארים לפני שם העצם, גודל לפני גיל: a big old house.",
      },
      {
        id: "g-adjective-order-09",
        type: "mcq",
        prompt: "I've never been so ___ in my life.",
        options: [
          { text: "embarrassing", errorType: "interference", whyHe: "embarrassing = מביך (הסיטואציה). אני נבוך = embarrassed." },
          { text: "embarrassed" },
          { text: "embarrass", errorType: "verb-form", whyHe: "embarrass הוא פועל. צריך תואר ב-ed." },
          { text: "embarrassment", errorType: "word-choice", whyHe: "embarrassment הוא שם עצם (מבוכה). אחרי so צריך תואר." },
        ],
        answerIndex: 1,
        explainHe: "אני מרגיש נבוך – embarrassed.",
      },
      {
        id: "g-adjective-order-10",
        type: "fix",
        prompt: "I'm very boring in this class.",
        answer: "I'm very bored in this class.",
        errorType: "interference",
        explainHe: "מי שמרגיש שעמום – bored. boring היה אומר שאני אדם משעמם.",
      },
      {
        id: "g-adjective-order-11",
        type: "fix",
        prompt: "She has a car red.",
        answer: "She has a red car.",
        errorType: "interference",
        explainHe: "תואר לפני שם העצם: a red car.",
      },
      {
        id: "g-adjective-order-12",
        type: "fix",
        prompt: "They live in a wooden small house.",
        answer: "They live in a small wooden house.",
        errorType: "word-order",
        explainHe: "גודל לפני חומר: small wooden.",
      },
      {
        id: "g-adjective-order-13",
        type: "fix",
        prompt: "The movie was so bored that we left.",
        answer: "The movie was so boring that we left.",
        errorType: "interference",
        explainHe: "הסרט גורם לשעמום – boring. bored זה מה שאנחנו הרגשנו.",
      },
      {
        id: "g-adjective-order-14",
        type: "fix",
        prompt: "We visited some olds churches in Rome.",
        answer: "We visited some old churches in Rome.",
        errorType: "agreement",
        explainHe: "תארים לא מקבלים s ברבים.",
      },
      {
        id: "g-adjective-order-15",
        type: "transform",
        prompt: "The film bored me.",
        keyword: "boring",
        answer: "The film was boring.",
        accept: ["I found the film boring.", "The film was boring to me."],
        explainHe: "הסרט גרם לשעמום – The film was boring.",
      },
      {
        id: "g-adjective-order-16",
        type: "transform",
        prompt: "This puzzle confuses me.",
        keyword: "confused",
        answer: "I'm confused by this puzzle.",
        accept: ["I am confused by this puzzle.", "This puzzle makes me confused.", "I'm confused about this puzzle."],
        explainHe: "אני מרגיש מבולבל – confused (by). הפאזל הוא confusing.",
      },
      {
        id: "g-adjective-order-17",
        type: "order",
        words: ["she", "wore", "a", "long", "black", "dress"],
        answer: "She wore a long black dress.",
        explainHe: "צורה/גודל (long) לפני צבע (black), ואז שם העצם.",
      },
      {
        id: "g-adjective-order-18",
        type: "order",
        words: ["I", "bought", "a", "small", "wooden", "table"],
        answer: "I bought a small wooden table.",
        explainHe: "גודל לפני חומר: small wooden table.",
      },
      {
        id: "g-adjective-order-19",
        type: "order",
        words: ["it", "was", "a", "boring", "movie"],
        answer: "It was a boring movie.",
        explainHe: "a + תואר (boring – הסרט גורם לשעמום) + שם עצם.",
      },
      {
        id: "g-adjective-order-20",
        type: "order",
        words: ["he", "has", "a", "lovely", "little", "garden"],
        answer: "He has a lovely little garden.",
        explainHe: "דעה (lovely) לפני גודל (little).",
      },
      {
        id: "g-adjective-order-21",
        type: "order",
        words: ["we", "were", "surprised", "by", "the", "results"],
        answer: "We were surprised by the results.",
        explainHe: "אנחנו הרגשנו – surprised, ואחריו by.",
      },
      {
        id: "g-adjective-order-22",
        type: "order",
        words: ["they", "bought", "an", "old", "Italian", "car"],
        answer: "They bought an old Italian car.",
        explainHe: "גיל (old) לפני מוצא (Italian). an לפני old.",
      },
      {
        id: "g-adjective-order-23",
        type: "order",
        words: ["what", "an", "interesting", "story"],
        answer: "What an interesting story!",
        explainHe: "קריאה: What + an + תואר + שם עצם. הסיפור מעניין – interesting.",
      },
      {
        id: "g-adjective-order-24",
        type: "translate",
        he: "קניתי חולצה כחולה חדשה.",
        answer: "I bought a new blue shirt.",
        accept: ["I've bought a new blue shirt.", "I bought a new blue t-shirt."],
        explainHe: "התארים לפני שם העצם, גיל (new) לפני צבע (blue): a new blue shirt.",
      },
    ],
  },
];
