import type { GrammarTopic } from "@/lib/types";

export const CONDITIONALS: GrammarTopic[] = [
  // ---------------------------------------------------------------------------
  // 18. Zero & first conditional
  // ---------------------------------------------------------------------------
  {
    id: "g-conditional-0-1",
    title: "Zero & first conditional",
    titleHe: "תנאי אפס ותנאי ראשון",
    strand: "conditionals",
    order: 18,
    prereqs: ["g-future-time-clauses"],
    lesson: {
      explanationHe: [
        "תנאי אפס מתאר משהו שתמיד נכון: חוק טבע, הרגל או כלל. If you heat water, it boils. כאן if שווה בערך ל-when, כי זה קורה בכל פעם מחדש.",
        "תנאי ראשון מתאר מצב אמיתי ואפשרי בעתיד ואת התוצאה שלו: If it rains tomorrow, we'll stay home. זה לא דמיוני - זה באמת יכול לקרות, ולכן הוא המבנה שמשתמשים בו בתכנונים, באזהרות ובהבטחות.",
        "הנקודה הקשה לדוברי עברית: אחרי if בא פועל בהווה, גם כשהכוונה לעתיד. בעברית אומרים \"אם אראה אותו\" (עתיד), באנגלית If I see him. ה-will יושב רק בפסוקית התוצאה.",
        "צורה: If + present simple, will + פועל בסיס. אם פסוקית ה-if ראשונה - שמים פסיק; אם היא שנייה - בלי פסיק. במקום will אפשר ציווי (If you see him, call me) או מודאל (can, may, might, should). unless פירושו \"אלא אם כן\" ומחליף if not, ולכן הפועל אחריו חיובי.",
      ],
      form: [
        { label: "Zero: If + present simple, present simple", example: "If you heat ice, it melts." },
        { label: "First: If + present simple, will + base verb", example: "If it rains, we'll stay home." },
        { label: "Reversed order (no comma)", example: "We'll stay home if it rains." },
        { label: "Negative in the if-clause: don't / doesn't", example: "If you don't hurry, you'll miss the bus." },
        { label: "unless = if not (positive verb after it)", example: "I won't go unless you come too." },
        { label: "Result as an imperative", example: "If you see Dan, tell him to call me." },
        { label: "Result with can / may / might / should", example: "If you're tired, you can go home." },
        { label: "Future time clauses: when / as soon as / before / after + present", example: "I'll text you when I get there." },
      ],
      examples: [
        { en: "If you press this button, the machine stops.", he: "אם לוחצים על הכפתור הזה, המכונה נעצרת." },
        { en: "If it rains tomorrow, we'll cancel the picnic.", he: "אם ירד מחר גשם, נבטל את הפיקניק." },
        { en: "You'll feel better if you sleep a bit.", he: "תרגיש יותר טוב אם תישן קצת." },
        { en: "If you don't leave now, you'll be late.", he: "אם לא תצא עכשיו, תאחר." },
        { en: "I'll call you as soon as I finish work.", he: "אני אתקשר אליך ברגע שאסיים לעבוד." },
        { en: "We won't get tickets unless we book today.", he: "לא נשיג כרטיסים אלא אם כן נזמין היום." },
        { en: "If you see Maya, tell her I'm waiting outside.", he: "אם תראה את מאיה, תגיד לה שאני מחכה בחוץ." },
        { en: "If you're not sure, you can ask me anytime.", he: "אם אתה לא בטוח, אתה יכול לשאול אותי מתי שתרצה." },
      ],
      contrastHe: [
        "בעברית אומרים \"אם אראה אותו\" בזמן עתיד, ולכן מתפתים לכתוב If I will see him. באנגלית אחרי if בא הווה: If I see him, I'll tell him.",
        "אותו כלל חל על when, as soon as, before, after, until: I'll call you when I arrive, ולא when I will arrive.",
        "\"אלא אם כן\" = unless, וכבר יש בו שלילה. אומרים unless you hurry, ולא unless you don't hurry.",
        "בעברית \"כש\" מכסה גם מצב ודאי וגם מצב מסופק. באנגלית when = בטוח שיקרה (When I get home), if = ייתכן שיקרה (If I get home early).",
      ],
      commonErrors: [
        { wrong: "If I will see him, I'll tell him.", right: "If I see him, I'll tell him.", whyHe: "אחרי if בא הווה, גם כשהכוונה לעתיד." },
        { wrong: "When I will arrive, I'll send a message.", right: "When I arrive, I'll send a message.", whyHe: "גם אחרי when של עתיד בא פועל בהווה." },
        { wrong: "If it will rain, we stay home.", right: "If it rains, we'll stay home.", whyHe: "ה-will עובר לפסוקית התוצאה, לא לפסוקית ה-if." },
        { wrong: "Unless you don't hurry, you'll be late.", right: "Unless you hurry, you'll be late.", whyHe: "unless כבר שלילי; אין להוסיף שלילה נוספת." },
        { wrong: "If you will need help, call me.", right: "If you need help, call me.", whyHe: "התוצאה יכולה להיות ציווי, אבל אחרי if תמיד הווה." },
      ],
    },
    items: [
      { id: "g-conditional-0-1-01", type: "gap", prompt: "If you ___ (heat) ice, it melts.", answer: "heat", hint: "כלל שתמיד נכון", explainHe: "תנאי אפס: אחרי if בא present simple." },
      { id: "g-conditional-0-1-02", type: "gap", prompt: "If it ___ (rain) tomorrow, we'll cancel the trip.", answer: "rains", hint: "אחרי if - הווה", explainHe: "גם כשמדובר במחר, אחרי if בא הווה, ובגוף שלישי עם s." },
      { id: "g-conditional-0-1-03", type: "gap", prompt: "I'll call you as soon as I ___ (get) home.", answer: "get", explainHe: "אחרי as soon as לא בא will; משתמשים בהווה." },
      { id: "g-conditional-0-1-04", type: "gap", prompt: "If you ___ (not / leave) now, you'll be late for work.", answer: "don't leave", explainHe: "שלילה בפסוקית ה-if: don't + פועל בסיס." },
      { id: "g-conditional-0-1-05", type: "gap", prompt: "She ___ (not / pass) the exam if she doesn't study.", answer: "won't pass", explainHe: "פסוקית התוצאה בעתיד: won't + פועל בסיס." },
      { id: "g-conditional-0-1-06", type: "gap", prompt: "If you see Dan, ___ (tell) him to call me.", answer: "tell", hint: "ציווי", explainHe: "התוצאה בתנאי ראשון יכולה להיות ציווי: פועל בסיס." },
      { id: "g-conditional-0-1-07", type: "gap", prompt: "What ___ (you / do) if you don't get the job?", answer: "will you do", explainHe: "שאלה על התוצאה: will + נושא + פועל בסיס; אחרי if נשאר הווה." },
      { id: "g-conditional-0-1-08", type: "gap", prompt: "We won't get seats unless we ___ (book) today.", answer: "book", hint: "unless = if not", explainHe: "אחרי unless בא פועל חיובי בהווה." },
      {
        id: "g-conditional-0-1-09", type: "mcq", prompt: "If I ___ him tomorrow, I'll give him your message.",
        options: [
          { text: "will see", errorType: "tense", whyHe: "אחרי if לא בא will, גם כשמדובר במחר." },
          { text: "see" },
          { text: "would see", errorType: "conditional", whyHe: "would שייך לתנאי דמיוני, לא למצב אמיתי בעתיד." },
          { text: "am seeing", errorType: "aspect", whyHe: "בפסוקית if משתמשים ב-present simple." },
        ],
        answerIndex: 1, explainHe: "תנאי ראשון: If + present simple, will + פועל בסיס.",
      },
      {
        id: "g-conditional-0-1-10", type: "mcq", prompt: "We'll go to the beach if the weather ___ nice.",
        options: [
          { text: "will be", errorType: "tense", whyHe: "אחרי if בא הווה: is." },
          { text: "is" },
          { text: "would be", errorType: "conditional", whyHe: "המצב אמיתי ואפשרי, ולכן לא would." },
          { text: "be", errorType: "verb-form", whyHe: "חסר הפועל המוטה: is." },
        ],
        answerIndex: 1, explainHe: "if + present simple גם כשהכוונה למחר.",
      },
      {
        id: "g-conditional-0-1-11", type: "mcq", prompt: "Don't call me tonight ___ it's really urgent.",
        options: [
          { text: "unless" },
          { text: "if", errorType: "word-choice", whyHe: "if הופך את המשמעות; \"אלא אם כן\" = unless." },
          { text: "unless it isn't", errorType: "conditional", whyHe: "unless כבר שלילי; אסור להוסיף שלילה." },
          { text: "except", errorType: "word-choice", whyHe: "except לא פותח פסוקית תנאי כזאת." },
        ],
        answerIndex: 0, explainHe: "unless = if not, ואחריו פועל חיובי.",
      },
      {
        id: "g-conditional-0-1-12", type: "mcq", prompt: "I'll text you when I ___ at the station.",
        options: [
          { text: "will arrive", errorType: "tense", whyHe: "אחרי when של עתיד בא הווה." },
          { text: "arrive" },
          { text: "arrived", errorType: "tense", whyHe: "המשפט מדבר על העתיד, לא על העבר." },
          { text: "would arrive", errorType: "conditional", whyHe: "would לא מתאים לתוכנית אמיתית." },
        ],
        answerIndex: 1, explainHe: "פסוקית זמן של עתיד: when + present simple.",
      },
      {
        id: "g-conditional-0-1-13", type: "mcq", prompt: "If I have time tomorrow, I ___ you.",
        options: [
          { text: "call", errorType: "tense", whyHe: "בפסוקית התוצאה של תנאי ראשון בא will." },
          { text: "will call" },
          { text: "would call", errorType: "conditional", whyHe: "would שייך לתנאי שני (דמיוני)." },
          { text: "am calling", errorType: "aspect", whyHe: "לתוצאה מותנית בעתיד משתמשים ב-will." },
        ],
        answerIndex: 1, explainHe: "ה-will יושב בפסוקית התוצאה, לא אחרי if.",
      },
      { id: "g-conditional-0-1-14", type: "fix", prompt: "If I will see him tomorrow, I'll tell him about it.", answer: "If I see him tomorrow, I'll tell him about it.", errorType: "tense", explainHe: "אחרי if בא הווה, גם במשמעות עתיד." },
      { id: "g-conditional-0-1-15", type: "fix", prompt: "When I will arrive, I'll send you a message.", answer: "When I arrive, I'll send you a message.", errorType: "tense", explainHe: "אחרי when של עתיד בא present simple." },
      { id: "g-conditional-0-1-16", type: "fix", prompt: "Unless you don't hurry, you will miss the train.", answer: "Unless you hurry, you will miss the train.", errorType: "conditional", explainHe: "unless כבר כולל שלילה, ולכן הפועל אחריו חיובי." },
      { id: "g-conditional-0-1-17", type: "fix", prompt: "If it rains tomorrow, we stay at home.", answer: "If it rains tomorrow, we'll stay at home.", errorType: "tense", explainHe: "תוצאה עתידית: will + פועל בסיס." },
      { id: "g-conditional-0-1-18", type: "transform", prompt: "Hurry up, or you'll miss the bus.", keyword: "if", answer: "If you don't hurry up, you'll miss the bus.", accept: ["You'll miss the bus if you don't hurry up."], explainHe: "אזהרה: If + present simple שלילי, ואז will." },
      { id: "g-conditional-0-1-19", type: "transform", prompt: "You can't come in if you don't have a ticket.", keyword: "unless", answer: "You can't come in unless you have a ticket.", accept: ["Unless you have a ticket, you can't come in."], explainHe: "if not = unless, ואז הפועל חיובי." },
      { id: "g-conditional-0-1-20", type: "transform", prompt: "First I'll finish work, then I'll call you.", keyword: "when", answer: "I'll call you when I finish work.", accept: ["When I finish work, I'll call you."], explainHe: "פסוקית זמן של עתיד: when + present simple." },
      { id: "g-conditional-0-1-21", type: "order", words: ["call", "If", "need", "just", "help", "me", "you"], answer: "If you need help, just call me.", explainHe: "If + present simple, ואז ציווי בפסוקית התוצאה." },
      { id: "g-conditional-0-1-22", type: "order", words: ["as", "We'll", "leave", "soon", "you're", "as", "ready"], answer: "We'll leave as soon as you're ready.", explainHe: "as soon as + הווה, גם כשהכוונה לעתיד." },
      { id: "g-conditional-0-1-23", type: "translate", he: "אם תראה את דנה, תגיד לה שהתקשרתי.", answer: "If you see Dana, tell her that I called.", accept: ["If you see Dana, tell her I called."], explainHe: "\"אם תראה\" בעברית עתיד, באנגלית If you see (הווה)." },
      { id: "g-conditional-0-1-24", type: "translate", he: "לא נצא לטיול אם מזג האוויר לא ישתפר.", answer: "We won't go on the trip if the weather doesn't get better.", accept: ["We won't go on the trip unless the weather gets better.", "We won't go on the trip if the weather doesn't improve."], explainHe: "אחרי if בא הווה שלילי, והתוצאה עם won't." },
    ],
  },

  // ---------------------------------------------------------------------------
  // 19. Second conditional
  // ---------------------------------------------------------------------------
  {
    id: "g-conditional-2",
    title: "Second conditional",
    titleHe: "תנאי שני (דמיוני)",
    strand: "conditionals",
    order: 19,
    prereqs: ["g-conditional-0-1"],
    lesson: {
      explanationHe: [
        "תנאי שני מדבר על מצב שאינו נכון עכשיו או שאינו סביר: חלומות, דמיון ועצות. If I had a car, I'd drive you home - אין לי אוטו, אז זה רק דמיון.",
        "ההבדל מתנאי ראשון הוא במידת הריאליות, לא בזמן. If I get a bonus, I'll buy a laptop = יש סיכוי אמיתי. If I got a bonus, I'd buy a laptop = לא באמת מצפה לזה.",
        "השימוש הכי נפוץ בדיבור הוא עצה: If I were you, I'd talk to your boss. זה ביטוי קבוע, ותמיד were - גם עם I ועם he/she.",
        "צורה: If + past simple, would + פועל בסיס. ה-past simple אחרי if הוא לא זמן עבר אלא סימן לדמיון. במקום would אפשר could (יכולת) או might (אולי), ואחרי would בא תמיד פועל בסיס בלי to. אף פעם לא שמים would בתוך פסוקית ה-if.",
      ],
      form: [
        { label: "If + past simple, would + base verb", example: "If I had a car, I'd drive you." },
        { label: "were for every person (fixed phrase)", example: "If I were you, I'd say no." },
        { label: "Negative if-clause: didn't + base verb", example: "If I didn't work weekends, I'd travel more." },
        { label: "Negative result: wouldn't + base verb", example: "I wouldn't live here if I had a choice." },
        { label: "could / might instead of would", example: "If we left now, we could still make it." },
        { label: "Question: What would + subject + base verb?", example: "What would you do if you lost your job?" },
        { label: "Reversed order (no comma)", example: "I'd move abroad if I got the chance." },
        { label: "Never would after if", example: "If I had time (not: If I would have time)" },
      ],
      examples: [
        { en: "If I had more time, I'd learn to play the guitar.", he: "אם היה לי יותר זמן, הייתי לומד לנגן בגיטרה." },
        { en: "If I were you, I wouldn't sign that contract.", he: "אם הייתי במקומך, לא הייתי חותם על החוזה הזה." },
        { en: "She'd travel much more if she had a better job.", he: "היא הייתה מטיילת הרבה יותר אם הייתה לה עבודה טובה יותר." },
        { en: "If we left now, we could still catch the movie.", he: "אם היינו יוצאים עכשיו, עוד היינו מספיקים לסרט." },
        { en: "What would you do if you won a lot of money?", he: "מה היית עושה אם היית זוכה בהרבה כסף?" },
        { en: "I wouldn't say that if I didn't believe it.", he: "לא הייתי אומר את זה אם לא הייתי מאמין בזה." },
        { en: "If he were here, he would know what to do.", he: "אם הוא היה כאן, הוא היה יודע מה לעשות." },
        { en: "Life would be easier if we lived closer to work.", he: "החיים היו קלים יותר אם היינו גרים קרוב יותר לעבודה." },
      ],
      contrastHe: [
        "בעברית \"הייתי\" מכסה שני דברים שונים באנגלית: \"אם היה לי\" = If I had (עבר פשוט אחרי if), ו\"הייתי קונה\" = I would buy (would בתוצאה).",
        "מכאן השגיאה הכי נפוצה: If I would have time. אחרי if לעולם לא שמים would - רק past simple: If I had time.",
        "\"לו הייתי במקומך\" = If I were you. באנגלית זה תמיד were, ולא If I am you.",
        "ה-past simple אחרי if לא מציין עבר: If I lived in London מדבר על עכשיו, על מצב שאינו קיים.",
      ],
      commonErrors: [
        { wrong: "If I would be rich, I would travel.", right: "If I were rich, I would travel.", whyHe: "אחרי if בא past simple (were), ולא would." },
        { wrong: "If I would have time, I would come.", right: "If I had time, I would come.", whyHe: "\"אם היה לי זמן\" = If I had time." },
        { wrong: "If I am you, I wouldn't wait.", right: "If I were you, I wouldn't wait.", whyHe: "ביטוי קבוע לעצה: If I were you." },
        { wrong: "If she studied more, she will pass.", right: "If she studied more, she would pass.", whyHe: "בתנאי דמיוני התוצאה עם would, לא will." },
        { wrong: "I would to buy a house near the sea.", right: "I would buy a house near the sea.", whyHe: "אחרי would בא פועל בסיס בלי to." },
        { wrong: "If I had a car, I will drive you.", right: "If I had a car, I would drive you.", whyHe: "אם אחרי if יש past simple, בתוצאה חייב would." },
      ],
    },
    items: [
      { id: "g-conditional-2-01", type: "gap", prompt: "If I ___ (know) her number, I'd call her right now.", answer: "knew", hint: "מצב דמיוני", explainHe: "תנאי שני: אחרי if בא past simple." },
      { id: "g-conditional-2-02", type: "gap", prompt: "If I were you, I ___ (not / sign) that contract.", answer: "wouldn't sign", explainHe: "תוצאה שלילית בתנאי שני: wouldn't + פועל בסיס." },
      { id: "g-conditional-2-03", type: "gap", prompt: "She ___ (travel) a lot more if she had a better job.", answer: "would travel", hint: "פסוקית התוצאה", explainHe: "התוצאה בתנאי שני: would + פועל בסיס." },
      { id: "g-conditional-2-04", type: "gap", prompt: "If we ___ (leave) now, we could still catch the movie.", answer: "left", explainHe: "אחרי if בא past simple, גם כשמדובר על עכשיו." },
      { id: "g-conditional-2-05", type: "gap", prompt: "What ___ (you / do) if you won a lot of money?", answer: "would you do", explainHe: "שאלה בתנאי שני: would + נושא + פועל בסיס." },
      { id: "g-conditional-2-06", type: "gap", prompt: "If he ___ (be) here, he would know what to do.", answer: "were", accept: ["was"], hint: "צורה קבועה", explainHe: "בתנאי שני משתמשים ב-were לכל הגופים (was מקובל בדיבור)." },
      { id: "g-conditional-2-07", type: "gap", prompt: "I ___ (not / live) in this neighborhood if I had a choice.", answer: "wouldn't live", explainHe: "תוצאה דמיונית שלילית: wouldn't + פועל בסיס." },
      { id: "g-conditional-2-08", type: "gap", prompt: "If they ___ (not / argue) so much, they'd be much happier.", answer: "didn't argue", explainHe: "שלילה בפסוקית if של תנאי שני: didn't + פועל בסיס." },
      {
        id: "g-conditional-2-09", type: "mcq", prompt: "If I ___ rich, I'd buy a small house by the sea.",
        options: [
          { text: "would be", errorType: "conditional", whyHe: "אחרי if אף פעם לא בא would." },
          { text: "were" },
          { text: "am", errorType: "tense", whyHe: "המצב דמיוני, ולכן past simple / were." },
          { text: "will be", errorType: "tense", whyHe: "will שייך לתנאי ראשון אמיתי." },
        ],
        answerIndex: 1, explainHe: "תנאי שני: If I were rich, I would buy...",
      },
      {
        id: "g-conditional-2-10", type: "mcq", prompt: "If she had more patience, she ___ a great teacher.",
        options: [
          { text: "will be", errorType: "conditional", whyHe: "בתנאי דמיוני התוצאה עם would." },
          { text: "would be" },
          { text: "would to be", errorType: "verb-form", whyHe: "אחרי would בא פועל בסיס בלי to." },
          { text: "is", errorType: "tense", whyHe: "התוצאה דמיונית, ולכן would be." },
        ],
        answerIndex: 1, explainHe: "If + past simple, would + פועל בסיס.",
      },
      {
        id: "g-conditional-2-11", type: "mcq", prompt: "What would you do if you ___ your phone on the train?",
        options: [
          { text: "will lose", errorType: "tense", whyHe: "אחרי if לא בא will." },
          { text: "lost" },
          { text: "would lose", errorType: "conditional", whyHe: "would לא נכנס לפסוקית ה-if." },
          { text: "have lost", errorType: "tense", whyHe: "בתנאי שני אחרי if בא past simple." },
        ],
        answerIndex: 1, explainHe: "שאלה דמיונית: would + נושא + פועל, ואחרי if past simple.",
      },
      {
        id: "g-conditional-2-12", type: "mcq", prompt: "If we lived closer, we ___ each other every week.",
        options: [
          { text: "could see" },
          { text: "can see", errorType: "modal", whyHe: "בתנאי דמיוני משתמשים ב-could, לא ב-can." },
          { text: "will see", errorType: "conditional", whyHe: "will שייך למצב אמיתי בעתיד." },
          { text: "saw", errorType: "verb-form", whyHe: "בפסוקית התוצאה צריך would/could + פועל בסיס." },
        ],
        answerIndex: 0, explainHe: "אפשר להחליף would ב-could כשמדובר ביכולת.",
      },
      {
        id: "g-conditional-2-13", type: "mcq", prompt: "If I ___ enough money, I'd help you out.",
        options: [
          { text: "would have", errorType: "conditional", whyHe: "\"אם היה לי\" בעברית מטעה; באנגלית אחרי if בא had." },
          { text: "had" },
          { text: "have", errorType: "tense", whyHe: "המצב אינו נכון עכשיו, ולכן past simple." },
          { text: "will have", errorType: "tense", whyHe: "אחרי if לא בא will." },
        ],
        answerIndex: 1, explainHe: "\"אם היה לי כסף\" = If I had money.",
      },
      { id: "g-conditional-2-14", type: "fix", prompt: "If I would be rich, I would buy a boat.", answer: "If I were rich, I would buy a boat.", accept: ["If I was rich, I would buy a boat."], errorType: "conditional", explainHe: "אחרי if בא were, ולא would be." },
      { id: "g-conditional-2-15", type: "fix", prompt: "If I would have time, I would join you tonight.", answer: "If I had time, I would join you tonight.", errorType: "conditional", explainHe: "\"אם היה לי זמן\" = If I had time." },
      { id: "g-conditional-2-16", type: "fix", prompt: "If she asked me nicely, I will help her.", answer: "If she asked me nicely, I would help her.", errorType: "tense", explainHe: "past simple אחרי if מחייב would בתוצאה." },
      { id: "g-conditional-2-17", type: "fix", prompt: "I would to move to Tel Aviv if I found a job there.", answer: "I would move to Tel Aviv if I found a job there.", errorType: "verb-form", explainHe: "אחרי would בא פועל בסיס בלי to." },
      { id: "g-conditional-2-18", type: "transform", prompt: "I don't have a car, so I take the bus every day.", keyword: "if", answer: "If I had a car, I wouldn't take the bus every day.", accept: ["I wouldn't take the bus every day if I had a car."], explainHe: "מצב שאינו נכון עכשיו: If + past simple, wouldn't + פועל." },
      { id: "g-conditional-2-19", type: "transform", prompt: "My advice is to talk to your boss about it.", keyword: "were", answer: "If I were you, I would talk to your boss about it.", accept: ["If I were you, I'd speak to your boss about it."], explainHe: "עצה: If I were you, I'd + פועל בסיס." },
      { id: "g-conditional-2-20", type: "transform", prompt: "She doesn't speak French, so she can't apply for the job.", keyword: "could", answer: "If she spoke French, she could apply for the job.", accept: ["She could apply for the job if she spoke French."], explainHe: "יכולת דמיונית: could + פועל בסיס בתוצאה." },
      { id: "g-conditional-2-21", type: "order", words: ["I'd", "If", "were", "apologize", "you", "I"], answer: "If I were you, I'd apologize.", explainHe: "ביטוי העצה הקבוע: If I were you, I'd + פועל." },
      { id: "g-conditional-2-22", type: "order", words: ["you", "What", "would", "do", "lost", "if", "your", "you", "job"], answer: "What would you do if you lost your job?", explainHe: "שאלה דמיונית: would בשאלה, past simple אחרי if." },
      { id: "g-conditional-2-23", type: "translate", he: "אם הייתי גר בחוץ לארץ, הייתי מתגעגע למשפחה שלי.", answer: "If I lived abroad, I would miss my family.", accept: ["I would miss my family if I lived abroad."], explainHe: "\"אם הייתי גר\" = If I lived; \"הייתי מתגעגע\" = I would miss." },
      { id: "g-conditional-2-24", type: "translate", he: "אם היה לנו יותר מקום, היינו מזמינים את כולם.", answer: "If we had more space, we would invite everyone.", accept: ["If we had more room, we would invite everybody.", "We would invite everyone if we had more space."], explainHe: "\"אם היה לנו\" = If we had, והתוצאה עם would." },
    ],
  },

  // ---------------------------------------------------------------------------
  // 20. Third & mixed conditionals
  // ---------------------------------------------------------------------------
  {
    id: "g-conditional-3-mixed",
    title: "Third & mixed conditionals",
    titleHe: "תנאי שלישי ומעורב",
    strand: "conditionals",
    order: 20,
    prereqs: ["g-conditional-2", "g-past-perfect"],
    lesson: {
      explanationHe: [
        "תנאי שלישי מדבר על העבר שכבר נסגר: מה היה קורה אילו משהו היה שונה. If I had known you were sick, I would have visited you - לא ידעתי, ולכן לא ביקרתי. זו הצורה של חרטה, של \"מזל ש\" ושל ביקורת בדיעבד.",
        "צורה: If + past perfect (had + V3), would have + V3. ה-had נמצא רק בפסוקית ה-if, וה-would have רק בתוצאה. אפשר גם could have (הייתה אפשרות) ו-might have (אולי).",
        "תנאי מעורב מחבר בין הזמנים. סוג א: תנאי בעבר, תוצאה בהווה - If I had studied medicine, I'd be a doctor now. סוג ב: תנאי קבוע בהווה, תוצאה בעבר - If I weren't so shy, I would have said something.",
        "בדיבור מקצרים הכול ל-'d, וזה מבלבל: If I'd known = had known (בפסוקית ה-if), ו-I'd have called = would have (בתוצאה). הכלל הפשוט: אחרי if אף פעם לא כותבים would have.",
      ],
      form: [
        { label: "Third: If + had + V3, would have + V3", example: "If I had known, I would have called." },
        { label: "Negative if-clause: hadn't + V3", example: "If you hadn't helped me, I wouldn't have finished." },
        { label: "could have / might have in the result", example: "We might have won if we'd tried harder." },
        { label: "Mixed A (past cause, present result): If + had + V3, would + base", example: "If I had studied medicine, I'd be a doctor now." },
        { label: "Mixed B (present cause, past result): If + past simple, would have + V3", example: "If I weren't so shy, I would have said something." },
        { label: "'d = had after if, would in the result", example: "If I'd known, I'd have come." },
        { label: "Question: What would + subject + have + V3?", example: "What would you have done?" },
      ],
      examples: [
        { en: "If I had known you were sick, I would have visited you.", he: "אם הייתי יודע שאתה חולה, הייתי בא לבקר אותך." },
        { en: "She would have passed the exam if she had studied harder.", he: "היא הייתה עוברת את המבחן אם הייתה לומדת יותר." },
        { en: "If we hadn't taken a taxi, we would have been late.", he: "אם לא היינו לוקחים מונית, היינו מאחרים." },
        { en: "We could have won if the goalkeeper had been fit.", he: "יכולנו לנצח אם השוער היה כשיר." },
        { en: "If I had taken that job, I'd be living in Berlin now.", he: "אם הייתי לוקח את העבודה ההיא, הייתי גר עכשיו בברלין." },
        { en: "If he weren't so stubborn, he would have apologized long ago.", he: "אם הוא לא היה כזה עקשן, הוא היה מתנצל מזמן." },
        { en: "What would you have done in my place?", he: "מה היית עושה במקומי?" },
        { en: "If you'd told me earlier, I'd have changed my plans.", he: "אם היית אומר לי קודם, הייתי משנה את התוכניות שלי." },
      ],
      contrastHe: [
        "בעברית \"הייתי אומר לך\" יכול להיות דמיון על עכשיו או חרטה על העבר. באנגלית חייבים להחליט: I would tell you (עכשיו) לעומת I would have told you (אז).",
        "\"אם היית מספר לי\" מתורגם If you had told me - צריך had + V3, לא If you would have told me.",
        "\"היינו מפספסים\" מול \"היינו מפספסים אז\": התוצאה על העבר תמיד would have + V3, גם כשהעברית זהה לתנאי שני.",
        "בתנאי מעורב העברית משתמשת באותה מילה \"הייתי\" בשני חלקי המשפט, ובאנגלית החלק על ההווה בלי have: If I had saved money, I'd have a car now.",
      ],
      commonErrors: [
        { wrong: "If I would have known, I would have told you.", right: "If I had known, I would have told you.", whyHe: "אחרי if בא had + V3, לעולם לא would have." },
        { wrong: "If she had studied, she would passed.", right: "If she had studied, she would have passed.", whyHe: "בתוצאה חסר have: would have + V3." },
        { wrong: "If they hadn't have left, we would have met.", right: "If they hadn't left, we would have met.", whyHe: "אין have נוסף אחרי hadn't." },
        { wrong: "If I had saved money, I would bought a car last year.", right: "If I had saved money, I would have bought a car last year.", whyHe: "תוצאה בעבר: would have + V3." },
        { wrong: "If I would be there, I would have helped.", right: "If I had been there, I would have helped.", whyHe: "תנאי בעבר: had been." },
        { wrong: "If he had listened, he will not have failed.", right: "If he had listened, he wouldn't have failed.", whyHe: "בתנאי שלישי אין will; משתמשים ב-would have." },
      ],
    },
    items: [
      { id: "g-conditional-3-mixed-01", type: "gap", prompt: "If I ___ (know) you were in town, I would have called you.", answer: "had known", hint: "had + V3", explainHe: "תנאי שלישי: אחרי if בא past perfect." },
      { id: "g-conditional-3-mixed-02", type: "gap", prompt: "She would have passed the exam if she ___ (study) harder.", answer: "had studied", explainHe: "פסוקית if של תנאי שלישי: had + V3." },
      { id: "g-conditional-3-mixed-03", type: "gap", prompt: "If you had told me, I ___ (help) you with the move.", answer: "would have helped", hint: "would have + V3", explainHe: "תוצאה בעבר: would have + V3." },
      { id: "g-conditional-3-mixed-04", type: "gap", prompt: "We ___ (not / miss) the flight if we had left earlier.", answer: "wouldn't have missed", explainHe: "תוצאה שלילית בעבר: wouldn't have + V3." },
      { id: "g-conditional-3-mixed-05", type: "gap", prompt: "If they ___ (not / take) a taxi, they would have been late.", answer: "hadn't taken", explainHe: "שלילה בפסוקית ה-if: hadn't + V3." },
      { id: "g-conditional-3-mixed-06", type: "gap", prompt: "If I had studied medicine, I ___ (be) a doctor now.", answer: "would be", hint: "תוצאה בהווה", explainHe: "תנאי מעורב: הסיבה בעבר, התוצאה בהווה - would + פועל בסיס, בלי have." },
      { id: "g-conditional-3-mixed-07", type: "gap", prompt: "If he ___ (not / be) so stubborn, he would have apologized long ago.", answer: "weren't", accept: ["wasn't"], hint: "תכונה קבועה", explainHe: "תנאי מעורב הפוך: תכונה קבועה בהווה, תוצאה בעבר." },
      { id: "g-conditional-3-mixed-08", type: "gap", prompt: "What ___ (you / do) if you had missed the last bus?", answer: "would you have done", explainHe: "שאלה בתנאי שלישי: would + נושא + have + V3." },
      {
        id: "g-conditional-3-mixed-09", type: "mcq", prompt: "If I ___ about the party, I would have come.",
        options: [
          { text: "would have known", errorType: "conditional", whyHe: "אחרי if לא בא would have." },
          { text: "had known" },
          { text: "have known", errorType: "verb-form", whyHe: "חסר had: had known." },
          { text: "would know", errorType: "tense", whyHe: "התנאי מדבר על העבר, ולכן had known." },
        ],
        answerIndex: 1, explainHe: "תנאי שלישי: If + had + V3.",
      },
      {
        id: "g-conditional-3-mixed-10", type: "mcq", prompt: "If she had asked me, I ___ her without any problem.",
        options: [
          { text: "would helped", errorType: "verb-form", whyHe: "חסר have: would have helped." },
          { text: "would have helped" },
          { text: "will help", errorType: "tense", whyHe: "המשפט מדבר על העבר, ולא על העתיד." },
          { text: "had helped", errorType: "conditional", whyHe: "ה-had שייך לפסוקית ה-if, לא לתוצאה." },
        ],
        answerIndex: 1, explainHe: "תוצאה של תנאי שלישי: would have + V3.",
      },
      {
        id: "g-conditional-3-mixed-11", type: "mcq", prompt: "If we hadn't missed the train, we ___ here two hours ago.",
        options: [
          { text: "would have been" },
          { text: "would be", errorType: "tense", whyHe: "two hours ago מציין עבר, ולכן would have been." },
          { text: "had been", errorType: "conditional", whyHe: "בתוצאה בא would have, לא had." },
          { text: "will be", errorType: "tense", whyHe: "אין will בתנאי דמיוני." },
        ],
        answerIndex: 0, explainHe: "כשהתוצאה בעבר (two hours ago): would have + V3.",
      },
      {
        id: "g-conditional-3-mixed-12", type: "mcq", prompt: "If I had listened to my parents, I ___ in this situation now.",
        options: [
          { text: "wouldn't be" },
          { text: "wouldn't have been", errorType: "tense", whyHe: "now מציין הווה, ולכן wouldn't be." },
          { text: "won't be", errorType: "conditional", whyHe: "אין will/won't בתנאי דמיוני." },
          { text: "hadn't been", errorType: "conditional", whyHe: "ה-had שייך רק לפסוקית ה-if." },
        ],
        answerIndex: 0, explainHe: "תנאי מעורב: סיבה בעבר, תוצאה בהווה - would + פועל בסיס.",
      },
      {
        id: "g-conditional-3-mixed-13", type: "mcq", prompt: "If you'd told me earlier, I ___ something about it.",
        options: [
          { text: "would have said" },
          { text: "would said", errorType: "verb-form", whyHe: "חסר have: would have said." },
          { text: "had said", errorType: "conditional", whyHe: "בתוצאה בא would have." },
          { text: "would say", errorType: "tense", whyHe: "המשפט על העבר: would have + V3." },
        ],
        answerIndex: 0, explainHe: "you'd told = you had told, ולכן התוצאה would have + V3.",
      },
      { id: "g-conditional-3-mixed-14", type: "fix", prompt: "If I would have known, I would have said something.", answer: "If I had known, I would have said something.", errorType: "conditional", explainHe: "אחרי if בא had + V3, ולא would have." },
      { id: "g-conditional-3-mixed-15", type: "fix", prompt: "If she had come earlier, she would met him.", answer: "If she had come earlier, she would have met him.", errorType: "verb-form", explainHe: "בתוצאה חסר have: would have met." },
      { id: "g-conditional-3-mixed-16", type: "fix", prompt: "If I had saved money last year, I would buy a car last month.", answer: "If I had saved money last year, I would have bought a car last month.", errorType: "tense", explainHe: "התוצאה מדברת על העבר, ולכן would have + V3." },
      { id: "g-conditional-3-mixed-17", type: "fix", prompt: "If she hadn't have missed the bus, she would have been on time.", answer: "If she hadn't missed the bus, she would have been on time.", errorType: "verb-form", explainHe: "אחרי hadn't בא V3 ישירות, בלי have נוסף." },
      { id: "g-conditional-3-mixed-18", type: "transform", prompt: "I didn't know you were in town, so I didn't call.", keyword: "if", answer: "If I had known you were in town, I would have called.", accept: ["I would have called if I had known you were in town."], explainHe: "חרטה על העבר: If + had + V3, would have + V3." },
      { id: "g-conditional-3-mixed-19", type: "transform", prompt: "She didn't study medicine, so she isn't a doctor today.", keyword: "would", answer: "If she had studied medicine, she would be a doctor today.", accept: ["She would be a doctor today if she had studied medicine."], explainHe: "תנאי מעורב: סיבה בעבר, תוצאה בהווה." },
      { id: "g-conditional-3-mixed-20", type: "transform", prompt: "We left late, so we missed the beginning of the film.", keyword: "hadn't", answer: "If we hadn't left late, we wouldn't have missed the beginning of the film.", accept: ["We wouldn't have missed the beginning of the film if we hadn't left late."], explainHe: "היפוך המציאות בעבר: hadn't + V3, wouldn't have + V3." },
      { id: "g-conditional-3-mixed-21", type: "order", words: ["known", "If", "I", "had", "would", "I", "have", "called"], answer: "If I had known, I would have called.", explainHe: "If + had + V3, ואז would have + V3." },
      { id: "g-conditional-3-mixed-22", type: "order", words: ["have", "She", "passed", "would", "she", "if", "studied", "had"], answer: "She would have passed if she had studied.", explainHe: "אפשר להתחיל מהתוצאה; אז אין פסיק לפני if." },
      { id: "g-conditional-3-mixed-23", type: "translate", he: "אם היינו יוצאים מוקדם יותר, לא היינו נתקעים בפקק.", answer: "If we had left earlier, we wouldn't have been stuck in traffic.", accept: ["If we had left earlier, we wouldn't have gotten stuck in traffic."], explainHe: "העבר כבר נסגר: had left + wouldn't have been." },
      { id: "g-conditional-3-mixed-24", type: "translate", he: "אם לא היית עוזר לי אז, לא הייתי כאן היום.", answer: "If you hadn't helped me then, I wouldn't be here today.", accept: ["If you hadn't helped me back then, I wouldn't be here today."], explainHe: "תנאי מעורב: hadn't helped (עבר) + wouldn't be (היום)." },
    ],
  },

  // ---------------------------------------------------------------------------
  // 21. wish / if only / I'd rather
  // ---------------------------------------------------------------------------
  {
    id: "g-wish-if-only",
    title: "wish / if only / I'd rather",
    titleHe: "wish ו-if only",
    strand: "conditionals",
    order: 21,
    prereqs: ["g-conditional-2"],
    lesson: {
      explanationHe: [
        "wish מביע חוסר שביעות רצון מהמצב: משהו לא כמו שהיינו רוצים. I wish I had more time = אין לי מספיק זמן ואני מצטער על כך. if only הוא בדיוק אותו דבר, רק חזק ורגשי יותר.",
        "על ההווה: wish + past simple. I wish I lived closer. עם be משתמשים ב-were לכל הגופים: I wish I were taller. ליכולת: I wish I could come.",
        "על העבר (חרטה): wish + had + V3. I wish I hadn't said that = אמרתי, ואני מתחרט. שימו לב להבדל: I wish I knew = עכשיו לא יודע; I wish I had known = אז לא ידעתי.",
        "wish + would שמור לתלונה על התנהגות של מישהו אחר שמעצבנת אותנו: I wish you would stop interrupting. לא משתמשים בו על עצמנו. ובנוסף: I'd rather you + past simple מביע העדפה ממה שמישהו אחר יעשה - I'd rather you didn't smoke here.",
      ],
      form: [
        { label: "About now: wish + past simple", example: "I wish I had more time." },
        { label: "be → were for every person", example: "I wish I were taller." },
        { label: "Ability: wish + could + base verb", example: "I wish I could come tonight." },
        { label: "Regret about the past: wish + had + V3", example: "I wish I hadn't said that." },
        { label: "Someone else's annoying habit: wish + would + base verb", example: "I wish you would listen to me." },
        { label: "if only = a stronger wish", example: "If only I knew the answer!" },
        { label: "Preference about someone else: I'd rather + subject + past simple", example: "I'd rather you didn't smoke here." },
      ],
      examples: [
        { en: "I wish I had more free time during the week.", he: "הלוואי שהיה לי יותר זמן פנוי במהלך השבוע." },
        { en: "I wish I were better at math.", he: "הלוואי שהייתי טוב יותר במתמטיקה." },
        { en: "I wish I could help you, but I'm stuck at work.", he: "הלוואי שיכולתי לעזור לך, אבל אני תקוע בעבודה." },
        { en: "She wishes she hadn't sold her old apartment.", he: "היא מצטערת שמכרה את הדירה הישנה שלה." },
        { en: "I wish my neighbors wouldn't make so much noise at night.", he: "הלוואי שהשכנים שלי לא היו עושים כל כך הרבה רעש בלילה." },
        { en: "If only I had listened to you!", he: "הלוואי שהייתי מקשיב לך!" },
        { en: "I'd rather you didn't tell anyone about this.", he: "אני מעדיף שלא תספר על זה לאף אחד." },
        { en: "I wish this week were over already.", he: "הלוואי שהשבוע הזה כבר היה נגמר." },
      ],
      contrastHe: [
        "בעברית אומרים \"הלוואי שיש לי זמן\" בהווה, ולכן מתפתים לומר I wish I have time. באנגלית חייבים עבר: I wish I had time.",
        "\"הלוואי שהייתי יודע\" דו-משמעי בעברית. אם הכוונה לעכשיו: I wish I knew. אם הכוונה לאז: I wish I had known.",
        "\"חבל ש\" מתורגם בדרך כלל ל-I wish: \"חבל שאתה לא בא\" = I wish you were coming.",
        "I wish you would... הוא תלונה על מישהו אחר. על עצמי לא אומרים I wish I would - אלא I wish I could או I wish I had.",
      ],
      commonErrors: [
        { wrong: "I wish I have more time.", right: "I wish I had more time.", whyHe: "אחרי wish בא past simple, גם כשמדובר בהווה." },
        { wrong: "I wish I am taller.", right: "I wish I were taller.", whyHe: "עם be משתמשים ב-were לכל הגופים." },
        { wrong: "I wish I would have more money.", right: "I wish I had more money.", whyHe: "על עצמי לא אומרים wish I would; פשוט past simple." },
        { wrong: "I wish I would come yesterday.", right: "I wish I had come yesterday.", whyHe: "חרטה על העבר: wish + had + V3." },
        { wrong: "If only I would know what to do!", right: "If only I knew what to do!", whyHe: "if only מתנהג כמו wish: past simple על ההווה." },
        { wrong: "I'd rather you come tomorrow.", right: "I'd rather you came tomorrow.", whyHe: "אחרי I'd rather + נושא בא past simple." },
      ],
    },
    items: [
      { id: "g-wish-if-only-01", type: "gap", prompt: "I wish I ___ (have) more free time during the week.", answer: "had", hint: "אחרי wish - עבר", explainHe: "wish על ההווה: past simple, גם כשהמשמעות היא עכשיו." },
      { id: "g-wish-if-only-02", type: "gap", prompt: "I wish I ___ (can) help you, but I'm busy all day.", answer: "could", explainHe: "יכולת אחרי wish: could + פועל בסיס." },
      { id: "g-wish-if-only-03", type: "gap", prompt: "She wishes she ___ (not / say) that at the meeting.", answer: "hadn't said", hint: "חרטה על העבר", explainHe: "חרטה על העבר: wish + hadn't + V3." },
      { id: "g-wish-if-only-04", type: "gap", prompt: "I wish it ___ (not / be) so hot today.", answer: "weren't", accept: ["wasn't"], explainHe: "אחרי wish משתמשים ב-were/weren't (was מקובל בדיבור)." },
      { id: "g-wish-if-only-05", type: "gap", prompt: "If only I ___ (know) the answer to this question!", answer: "knew", explainHe: "if only מתנהג כמו wish: past simple על ההווה." },
      { id: "g-wish-if-only-06", type: "gap", prompt: "I wish you ___ (stop) interrupting me all the time.", answer: "would stop", hint: "תלונה על מישהו אחר", explainHe: "תלונה על התנהגות של מישהו אחר: wish + would + פועל בסיס." },
      { id: "g-wish-if-only-07", type: "gap", prompt: "He wishes he ___ (study) harder when he was at school.", answer: "had studied", explainHe: "חרטה על העבר: wish + had + V3." },
      { id: "g-wish-if-only-08", type: "gap", prompt: "I'd rather you ___ (not / tell) anyone about this.", answer: "didn't tell", explainHe: "אחרי I'd rather + נושא בא past simple." },
      {
        id: "g-wish-if-only-09", type: "mcq", prompt: "I wish I ___ a bigger apartment.",
        options: [
          { text: "have", errorType: "tense", whyHe: "אחרי wish בא עבר, גם כשמדובר בהווה." },
          { text: "had" },
          { text: "would have", errorType: "conditional", whyHe: "wish + would שמור לתלונה על מישהו אחר." },
          { text: "will have", errorType: "tense", whyHe: "אין will אחרי wish." },
        ],
        answerIndex: 1, explainHe: "\"הלוואי שהייתה לי\" = I wish I had.",
      },
      {
        id: "g-wish-if-only-10", type: "mcq", prompt: "I wish I ___ a little taller.",
        options: [
          { text: "am", errorType: "tense", whyHe: "אחרי wish לא בא הווה." },
          { text: "were" },
          { text: "would be", errorType: "conditional", whyHe: "על עצמי לא אומרים wish I would be." },
          { text: "will be", errorType: "tense", whyHe: "אין will אחרי wish." },
        ],
        answerIndex: 1, explainHe: "wish + were לכל הגופים.",
      },
      {
        id: "g-wish-if-only-11", type: "mcq", prompt: "I wish I ___ that email yesterday.",
        options: [
          { text: "didn't send", errorType: "tense", whyHe: "חרטה על העבר דורשת had + V3." },
          { text: "hadn't sent" },
          { text: "wouldn't send", errorType: "conditional", whyHe: "would לא מתאר חרטה על העבר." },
          { text: "haven't sent", errorType: "tense", whyHe: "yesterday סגור; צריך past perfect." },
        ],
        answerIndex: 1, explainHe: "wish על העבר: hadn't + V3.",
      },
      {
        id: "g-wish-if-only-12", type: "mcq", prompt: "I wish my neighbors ___ so much noise at night.",
        options: [
          { text: "wouldn't make" },
          { text: "didn't made", errorType: "verb-form", whyHe: "אחרי didn't בא פועל בסיס." },
          { text: "won't make", errorType: "tense", whyHe: "אין will/won't אחרי wish." },
          { text: "don't make", errorType: "tense", whyHe: "אחרי wish לא בא הווה." },
        ],
        answerIndex: 0, explainHe: "תלונה על התנהגות של אחרים: wish + wouldn't + פועל בסיס.",
      },
      {
        id: "g-wish-if-only-13", type: "mcq", prompt: "I'd rather you ___ me the truth from the start.",
        options: [
          { text: "tell", errorType: "tense", whyHe: "אחרי I'd rather + נושא בא past simple." },
          { text: "told" },
          { text: "would tell", errorType: "modal", whyHe: "אחרי I'd rather + נושא לא בא would." },
          { text: "will tell", errorType: "tense", whyHe: "אין will במבנה הזה." },
        ],
        answerIndex: 1, explainHe: "I'd rather you + past simple, גם כשמדובר בעכשיו.",
      },
      { id: "g-wish-if-only-14", type: "fix", prompt: "I wish I have more time to read books.", answer: "I wish I had more time to read books.", errorType: "tense", explainHe: "\"הלוואי שיש לי\" = I wish I had." },
      { id: "g-wish-if-only-15", type: "fix", prompt: "I wish I would have known about it earlier.", answer: "I wish I had known about it earlier.", errorType: "conditional", explainHe: "חרטה על העבר: wish + had + V3, בלי would." },
      { id: "g-wish-if-only-16", type: "fix", prompt: "If only I would know what to do!", answer: "If only I knew what to do!", errorType: "modal", explainHe: "if only + past simple כשמדובר על ההווה." },
      { id: "g-wish-if-only-17", type: "fix", prompt: "I'd rather you come back tomorrow morning.", answer: "I'd rather you came back tomorrow morning.", errorType: "tense", explainHe: "אחרי I'd rather + נושא בא past simple." },
      { id: "g-wish-if-only-18", type: "transform", prompt: "I'm sorry that I don't speak Arabic.", keyword: "wish", answer: "I wish I spoke Arabic.", explainHe: "חוסר שביעות רצון מההווה: wish + past simple." },
      { id: "g-wish-if-only-19", type: "transform", prompt: "I regret telling him my secret.", keyword: "hadn't", answer: "I wish I hadn't told him my secret.", accept: ["If only I hadn't told him my secret."], explainHe: "חרטה על מעשה בעבר: wish + hadn't + V3." },
      { id: "g-wish-if-only-20", type: "transform", prompt: "Please don't call me at work.", keyword: "rather", answer: "I'd rather you didn't call me at work.", explainHe: "בקשה מנומסת: I'd rather you + past simple." },
      { id: "g-wish-if-only-21", type: "order", words: ["listened", "only", "If", "I", "to", "had", "you"], answer: "If only I had listened to you!", explainHe: "if only על העבר: had + V3." },
      { id: "g-wish-if-only-22", type: "order", words: ["stop", "wish", "would", "I", "shouting", "you"], answer: "I wish you would stop shouting.", explainHe: "תלונה על מישהו אחר: wish + would + פועל בסיס." },
      { id: "g-wish-if-only-23", type: "translate", he: "הלוואי שהייתה לי יותר סבלנות.", answer: "I wish I had more patience.", accept: ["If only I had more patience."], explainHe: "העברית בהווה, האנגלית בעבר: I wish I had." },
      { id: "g-wish-if-only-24", type: "translate", he: "הלוואי שלא הייתי אומר לו כלום.", answer: "I wish I hadn't said anything to him.", accept: ["I wish I hadn't told him anything.", "If only I hadn't said anything to him."], explainHe: "חרטה על מה שנאמר בעבר: wish + hadn't + V3." },
    ],
  },
];
