import type { GrammarTopic } from "@/lib/types";

export const MODALS_CONDITIONALS: GrammarTopic[] = [
  // ---------------------------------------------------------------------------
  // 13. Ability
  // ---------------------------------------------------------------------------
  {
    id: "g-modals-ability",
    title: "Ability: can / could / be able to",
    titleHe: "יכולת: can, could, be able to",
    strand: "modals",
    order: 13,
    prereqs: [],
    lesson: {
      explanationHe: [
        "can מבטא יכולת בהווה או יכולת כללית (I can swim), וגם רשות ובקשה (Can I open the window?). זו המילה לכל מה שבעברית אומרים עליו \"יודע\" או \"יכול\": I can drive = אני יודע לנהוג.",
        "could הוא can בעבר, אבל רק ליכולת כללית: When I was a kid, I could climb trees. לתאר הצלחה חד-פעמית בעבר (הצלחתי לעשות X באירוע מסוים) משתמשים ב-was/were able to או managed to, לא ב-could. בשלילה couldn't מתאים לשני המקרים.",
        "be able to משלים את can בכל מקום שבו can לא יכול להופיע: בעתיד (will be able to), ב-present perfect (have been able to), אחרי מודאל אחר (might be able to) ואחרי to (I'd love to be able to).",
        "צורה: מודאל + פועל בסיס, בלי to ובלי s. שאלה בהיפוך (Can you...?) ושלילה עם not (can't, couldn't). אין do/does.",
      ],
      form: [
        { label: "Present ability: can + base verb", example: "She can drive." },
        { label: "Negative: can't / cannot", example: "I can't hear you." },
        { label: "Question: Can + subject + verb?", example: "Can you help me?" },
        { label: "Past (general ability): could / couldn't", example: "I could read at four." },
        { label: "Past (one specific success): was/were able to, managed to", example: "We were able to get tickets." },
        { label: "Future: will be able to", example: "You'll be able to see it tomorrow." },
        { label: "Present perfect: have/has been able to", example: "I haven't been able to sleep." },
        { label: "After another modal / after to: might be able to, to be able to", example: "I'd like to be able to cook." },
      ],
      examples: [
        { en: "I can speak three languages.", he: "אני יודע לדבר שלוש שפות." },
        { en: "Can you come a bit earlier tomorrow?", he: "אתה יכול לבוא קצת יותר מוקדם מחר?" },
        { en: "My grandmother could swim really well.", he: "סבתא שלי ידעה לשחות ממש טוב." },
        { en: "The traffic was terrible, but we were able to get there on time.", he: "התנועה הייתה נוראית, אבל הצלחנו להגיע בזמן." },
        { en: "I couldn't find my keys this morning.", he: "לא הצלחתי למצוא את המפתחות שלי הבוקר." },
        { en: "After the course, you'll be able to write emails in English.", he: "אחרי הקורס תוכל לכתוב מיילים באנגלית." },
        { en: "I haven't been able to reach him all day.", he: "לא הצלחתי להשיג אותו כל היום." },
        { en: "I'd love to be able to work from anywhere.", he: "הייתי שמח לוכל לעבוד מכל מקום." },
      ],
      contrastHe: [
        "בעברית \"יודע\" משמש גם ליכולת (\"אני יודע לשחות\"). באנגלית זה can, לא know: I can swim, ולא I know to swim.",
        "\"יכולתי\" בעברית מכסה גם יכולת כללית בעבר וגם הצלחה חד-פעמית. באנגלית could = יכולת כללית; להצלחה חד-פעמית אומרים was able to או managed to.",
        "בעברית אחרי \"יכול\" בא שם פועל עם ל' (\"יכול ללכת\"), ולכן מתפתים לכתוב can to go. באנגלית can + פועל בסיס בלי to.",
        "can לא משתנה לפי זמן או גוף: אין cans ואין will can. לעתיד ול-perfect עוברים ל-be able to.",
      ],
      commonErrors: [
        { wrong: "I can to swim.", right: "I can swim.", whyHe: "אחרי can בא פועל בסיס בלי to." },
        { wrong: "She cans speak French.", right: "She can speak French.", whyHe: "מודאל לא מקבל s בגוף שלישי." },
        { wrong: "I will can come tomorrow.", right: "I will be able to come tomorrow.", whyHe: "אי אפשר שני מודאלים ברצף. בעתיד: will be able to." },
        { wrong: "Yesterday I could fix the printer.", right: "Yesterday I was able to fix the printer.", whyHe: "הצלחה חד-פעמית בעבר: was able to / managed to, לא could." },
        { wrong: "I know to drive.", right: "I can drive.", whyHe: "\"יודע\" במובן של יכולת = can." },
        { wrong: "Do you can help me?", right: "Can you help me?", whyHe: "שאלה עם מודאל: הופכים את המודאל והנושא, בלי do." },
      ],
    },
    items: [
      { id: "g-modals-ability-01", type: "gap", prompt: "My little brother ___ (swim) already; he learned last summer.", answer: "can swim", hint: "יכולת בהווה", explainHe: "יכולת בהווה: can + פועל בסיס." },
      { id: "g-modals-ability-02", type: "gap", prompt: "When I was ten, I ___ (run) really fast.", answer: "could run", hint: "יכולת כללית בעבר", explainHe: "יכולת כללית בעבר: could + פועל בסיס." },
      { id: "g-modals-ability-03", type: "gap", prompt: "Sorry, I ___ (not / hear) you. The line is bad.", answer: "can't hear", accept: ["cannot hear"], explainHe: "שלילה בהווה: can't + פועל בסיס. בלי do." },
      { id: "g-modals-ability-04", type: "gap", prompt: "Next year, you ___ (drive) on your own.", answer: "will be able to drive", accept: ["'ll be able to drive"], hint: "עתיד", explainHe: "אין will can. בעתיד: will be able to + פועל." },
      { id: "g-modals-ability-05", type: "gap", prompt: "The fire was bad, but everyone ___ (get) out safely.", answer: "was able to get", accept: ["managed to get"], hint: "הצלחה חד-פעמית", explainHe: "הצלחה חד-פעמית בעבר: was able to / managed to, לא could." },
      { id: "g-modals-ability-06", type: "gap", prompt: "I ___ (not / sleep) well since we moved.", answer: "haven't been able to sleep", hint: "present perfect + be able to", explainHe: "since מחייב present perfect, ו-can אין לו צורה כזאת: haven't been able to." },
      { id: "g-modals-ability-07", type: "gap", prompt: "___ (you / carry) this for me, please?", answer: "Can you carry", accept: ["Could you carry"], explainHe: "בקשה: Can/Could you + פועל בסיס. בלי Do you can." },
      { id: "g-modals-ability-08", type: "gap", prompt: "I'd love ___ (speak) Spanish one day.", answer: "to be able to speak", hint: "אחרי to", explainHe: "אחרי to אי אפשר לשים can. משתמשים ב-to be able to." },
      {
        id: "g-modals-ability-09", type: "mcq", prompt: "I ___ come to the meeting tomorrow, sorry.",
        options: [
          { text: "won't be able to" },
          { text: "won't can", errorType: "modal", whyHe: "אין שני מודאלים ברצף (will + can)." },
          { text: "will not able to", errorType: "verb-form", whyHe: "חסר be: will not be able to." },
          { text: "don't can", errorType: "modal", whyHe: "מודאל לא מקבל do/don't." },
        ],
        answerIndex: 0, explainHe: "חוסר יכולת בעתיד: won't be able to.",
      },
      {
        id: "g-modals-ability-10", type: "mcq", prompt: "Yesterday the app crashed, but I ___ save my work.",
        options: [
          { text: "could", errorType: "modal", whyHe: "could לא מתאר הצלחה חד-פעמית חיובית בעבר." },
          { text: "was able to" },
          { text: "can", errorType: "tense", whyHe: "המשפט בעבר (yesterday)." },
          { text: "could to", errorType: "verb-form", whyHe: "אין to אחרי could." },
        ],
        answerIndex: 1, explainHe: "הצלחה במקרה ספציפי בעבר: was able to (או managed to).",
      },
      {
        id: "g-modals-ability-11", type: "mcq", prompt: "___ speak English when you were a child?",
        options: [
          { text: "Did you can", errorType: "modal", whyHe: "מודאל לא מקבל did." },
          { text: "Could you" },
          { text: "Do you could", errorType: "question-form", whyHe: "אין do לפני מודאל." },
          { text: "You could", errorType: "question-form", whyHe: "בשאלה המודאל בא לפני הנושא." },
        ],
        answerIndex: 1, explainHe: "שאלה על יכולת בעבר: Could you + פועל.",
      },
      {
        id: "g-modals-ability-12", type: "mcq", prompt: "She ___ three languages.",
        options: [
          { text: "can speaks", errorType: "agreement", whyHe: "אחרי מודאל פועל בסיס, בלי s." },
          { text: "can to speak", errorType: "verb-form", whyHe: "אין to אחרי can." },
          { text: "can speak" },
          { text: "knows to speak", errorType: "interference", whyHe: "\"יודעת לדבר\" = can speak, לא knows to." },
        ],
        answerIndex: 2, explainHe: "can + פועל בסיס, גם בגוף שלישי.",
      },
      {
        id: "g-modals-ability-13", type: "mcq", prompt: "I ___ reach her since Monday.",
        options: [
          { text: "can't", errorType: "tense", whyHe: "since מחייב present perfect." },
          { text: "haven't been able to" },
          { text: "couldn't", errorType: "tense", whyHe: "since + עד עכשיו = present perfect, לא past." },
          { text: "haven't can", errorType: "modal", whyHe: "ל-can אין צורת V3; משתמשים ב-been able to." },
        ],
        answerIndex: 1, explainHe: "\"מאז יום שני\" גורר הווה מושלם, ולכן haven't been able to ולא couldn't.",
      },
      { id: "g-modals-ability-14", type: "fix", prompt: "I can to help you with the move.", answer: "I can help you with the move.", errorType: "verb-form", explainHe: "אחרי can בא פועל בסיס בלי to." },
      { id: "g-modals-ability-15", type: "fix", prompt: "He cans play the guitar very well.", answer: "He can play the guitar very well.", errorType: "agreement", explainHe: "מודאלים לא מקבלים s." },
      { id: "g-modals-ability-16", type: "fix", prompt: "Do you can come on Friday?", answer: "Can you come on Friday?", errorType: "question-form", explainHe: "שאלה עם מודאל: הופכים את המודאל, בלי do." },
      { id: "g-modals-ability-17", type: "fix", prompt: "I will can call you after the meeting.", answer: "I will be able to call you after the meeting.", accept: ["I'll be able to call you after the meeting."], errorType: "modal", explainHe: "אין will can. בעתיד: will be able to." },
      { id: "g-modals-ability-18", type: "transform", prompt: "It is possible for me to work from home on Fridays.", keyword: "can", answer: "I can work from home on Fridays.", explainHe: "יכולת/אפשרות בהווה: can + פועל בסיס." },
      { id: "g-modals-ability-19", type: "transform", prompt: "We managed to find a parking spot near the beach.", keyword: "able", answer: "We were able to find a parking spot near the beach.", explainHe: "managed to = were able to (הצלחה חד-פעמית בעבר)." },
      { id: "g-modals-ability-20", type: "transform", prompt: "She knew how to read when she was four.", keyword: "could", answer: "She could read when she was four.", accept: ["When she was four, she could read."], explainHe: "יכולת כללית בעבר: could." },
      { id: "g-modals-ability-21", type: "order", words: ["been", "able", "haven't", "I", "to", "concentrate", "today"], answer: "I haven't been able to concentrate today.", explainHe: "present perfect של יכולת: haven't been able to + פועל." },
      { id: "g-modals-ability-22", type: "order", words: ["Could", "you", "open", "the", "window,", "please?"], answer: "Could you open the window, please?", accept: ["Could you please open the window?"], explainHe: "בקשה מנומסת: Could you + פועל בסיס." },
      { id: "g-modals-ability-23", type: "translate", he: "לא הצלחתי למצוא את הטלפון שלי אתמול.", answer: "I couldn't find my phone yesterday.", accept: ["I wasn't able to find my phone yesterday.", "I didn't manage to find my phone yesterday."], explainHe: "בשלילה couldn't מתאים גם למקרה חד-פעמי." },
      { id: "g-modals-ability-24", type: "translate", he: "אחרי הקורס תוכל לדבר אנגלית בביטחון.", answer: "After the course, you will be able to speak English with confidence.", accept: ["After the course you'll be able to speak English confidently.", "After the course, you will be able to speak English confidently.", "After the course you will be able to speak English with confidence."], explainHe: "יכולת בעתיד: will be able to." },
    ],
  },

  // ---------------------------------------------------------------------------
  // 14. Obligation
  // ---------------------------------------------------------------------------
  {
    id: "g-modals-obligation",
    title: "Obligation: must / have to / should / don't have to",
    titleHe: "חובה: must, have to, should",
    strand: "modals",
    order: 14,
    prereqs: [],
    lesson: {
      explanationHe: [
        "must = חובה שהדובר עצמו מרגיש או קובע (I must call my mom), וגם כללים רשמיים בכתב (Passengers must show ID). have to = חובה שבאה מבחוץ: כללים, בוס, מצב (I have to be at work by eight). בדיבור יומיומי have to הרבה יותר נפוץ מ-must.",
        "should = מומלץ, נכון לעשות, אבל לא חובה (You should drink more water). על עצות נרחיב בנושא הבא.",
        "הפח הגדול הוא השלילה: mustn't = אסור! don't have to = לא צריך, לא חייב, אפשר לבחור. You mustn't pay = אסור לך לשלם; You don't have to pay = אתה לא חייב לשלם.",
        "have to מתנהג כמו פועל רגיל: has to, had to, will have to, don't/doesn't have to, ובשאלה Do you have to...? ל-must אין עבר ולא עתיד: בעבר had to, בעתיד will have to.",
      ],
      form: [
        { label: "Obligation (speaker's): must + base verb", example: "I must call my mom tonight." },
        { label: "Obligation (external): have to / has to", example: "She has to wear a uniform." },
        { label: "Past: had to", example: "We had to wait an hour." },
        { label: "Future: will have to", example: "You'll have to book early." },
        { label: "Prohibition: mustn't / can't", example: "You mustn't touch that." },
        { label: "No obligation: don't / doesn't have to", example: "You don't have to pay." },
        { label: "Question: Do I have to...?", example: "Do I have to come?" },
        { label: "Recommendation: should / shouldn't", example: "You should rest." },
      ],
      examples: [
        { en: "I have to be at work by eight.", he: "אני צריך להיות בעבודה עד שמונה." },
        { en: "You must see this movie, it's amazing.", he: "אתה חייב לראות את הסרט הזה, הוא מדהים." },
        { en: "We had to cancel the trip because of the storm.", he: "היינו צריכים לבטל את הטיול בגלל הסופה." },
        { en: "You don't have to bring anything, just come.", he: "אתה לא צריך להביא כלום, פשוט תבוא." },
        { en: "You mustn't tell anyone, it's a secret.", he: "אסור לך לספר לאף אחד, זה סוד." },
        { en: "Does she have to work on Saturdays?", he: "היא צריכה לעבוד בשבתות?" },
        { en: "You'll have to renew your passport before the trip.", he: "תצטרך לחדש את הדרכון לפני הטיול." },
        { en: "You should drink more water.", he: "כדאי שתשתה יותר מים." },
      ],
      contrastHe: [
        "\"צריך\" בעברית מכסה גם must, גם have to וגם should. באנגלית שואלים: זו חובה אמיתית (have to / must) או רק המלצה (should)?",
        "\"לא צריך\" = don't have to. \"אסור\" = mustn't / can't. בעברית ההבדל ברור, באנגלית הטעות הנפוצה היא לחשוב ש-mustn't פירושו \"לא חייב\".",
        "בעברית \"צריך ל-\" ולכן מתפתים ל-must to. אחרי must בא פועל בסיס בלי to; ב-have to ה-to כבר חלק מהביטוי.",
        "ל-must אין עבר או עתיד: \"הייתי צריך\" = had to, \"אצטרך\" = will have to.",
      ],
      commonErrors: [
        { wrong: "I must to go now.", right: "I must go now.", whyHe: "אחרי must אין to." },
        { wrong: "You mustn't pay, it's free.", right: "You don't have to pay, it's free.", whyHe: "mustn't = אסור. \"לא צריך\" = don't have to." },
        { wrong: "Yesterday I must work late.", right: "Yesterday I had to work late.", whyHe: "ל-must אין צורת עבר; משתמשים ב-had to." },
        { wrong: "She have to leave early.", right: "She has to leave early.", whyHe: "have to מתנהג כפועל רגיל: has to בגוף שלישי." },
        { wrong: "Must you to wear a suit?", right: "Do you have to wear a suit?", whyHe: "שאלות על חובה בדרך כלל עם Do you have to, ואין to אחרי must." },
        { wrong: "I will must finish it.", right: "I will have to finish it.", whyHe: "אין שני מודאלים ברצף; בעתיד will have to." },
      ],
    },
    items: [
      { id: "g-modals-obligation-01", type: "gap", prompt: "I ___ (get up) at six tomorrow; my train is at seven.", answer: "have to get up", accept: ["must get up", "need to get up"], hint: "חובה מהמצב", explainHe: "חובה שנובעת מהמצב: have to + פועל בסיס." },
      { id: "g-modals-obligation-02", type: "gap", prompt: "You ___ (not / pay) for the parking here; it's free.", answer: "don't have to pay", accept: ["needn't pay", "need not pay"], hint: "לא חייב", explainHe: "\"לא צריך\" = don't have to. mustn't היה אומר שאסור." },
      { id: "g-modals-obligation-03", type: "gap", prompt: "You ___ (not / use) your phone during the exam. It's forbidden.", answer: "mustn't use", accept: ["must not use", "can't use", "cannot use", "aren't allowed to use"], hint: "אסור", explainHe: "איסור: mustn't / can't + פועל בסיס." },
      { id: "g-modals-obligation-04", type: "gap", prompt: "Last week we ___ (work) on Saturday because of the deadline.", answer: "had to work", explainHe: "חובה בעבר: had to. ל-must אין עבר." },
      { id: "g-modals-obligation-05", type: "gap", prompt: "She ___ (wear) glasses for reading now.", answer: "has to wear", hint: "have to", explainHe: "have to בגוף שלישי: has to." },
      { id: "g-modals-obligation-06", type: "gap", prompt: "If the bus doesn't come, we ___ (take) a taxi.", answer: "will have to take", accept: ["'ll have to take"], hint: "עתיד", explainHe: "חובה בעתיד: will have to. לא will must." },
      { id: "g-modals-obligation-07", type: "gap", prompt: "___ (she / have to / come) to the meeting, or is it optional?", answer: "Does she have to come", explainHe: "שאלה עם have to: Does she have to...? כמו פועל רגיל." },
      { id: "g-modals-obligation-08", type: "gap", prompt: "Passengers ___ (show) their ID at the gate. (official rule)", answer: "must show", accept: ["have to show"], explainHe: "כלל רשמי: must + פועל בסיס." },
      {
        id: "g-modals-obligation-09", type: "mcq", prompt: "It's a secret, so you ___ tell anyone.",
        options: [
          { text: "don't have to", errorType: "word-choice", whyHe: "don't have to = לא חייב. כאן צריך \"אסור\"." },
          { text: "mustn't" },
          { text: "shouldn't to", errorType: "verb-form", whyHe: "אין to אחרי מודאל." },
          { text: "haven't to", errorType: "modal", whyHe: "השלילה של have to היא don't have to." },
        ],
        answerIndex: 1, explainHe: "איסור: mustn't.",
      },
      {
        id: "g-modals-obligation-10", type: "mcq", prompt: "Yesterday I ___ stay late at the office.",
        options: [
          { text: "must", errorType: "tense", whyHe: "ל-must אין עבר." },
          { text: "had to" },
          { text: "must to", errorType: "verb-form", whyHe: "אין to אחרי must, וגם אין עבר." },
          { text: "have to", errorType: "tense", whyHe: "המשפט בעבר (yesterday)." },
        ],
        answerIndex: 1, explainHe: "חובה בעבר: had to.",
      },
      {
        id: "g-modals-obligation-11", type: "mcq", prompt: "We ___ hurry, we have plenty of time.",
        options: [
          { text: "mustn't", errorType: "word-choice", whyHe: "mustn't = אסור. כאן הכוונה \"לא חייבים\"." },
          { text: "don't have to" },
          { text: "haven't to", errorType: "modal", whyHe: "השלילה: don't have to." },
          { text: "don't must", errorType: "modal", whyHe: "מודאל לא מקבל don't." },
        ],
        answerIndex: 1, explainHe: "אין חובה: don't have to.",
      },
      {
        id: "g-modals-obligation-12", type: "mcq", prompt: "___ wear a tie at your office?",
        options: [
          { text: "Must you to", errorType: "verb-form", whyHe: "אין to אחרי must." },
          { text: "Do you have to" },
          { text: "Have you to", errorType: "question-form", whyHe: "have to מתנהג כפועל רגיל: Do you have to." },
          { text: "Do you must", errorType: "modal", whyHe: "מודאל לא מקבל do." },
        ],
        answerIndex: 1, explainHe: "שאלה על חובה: Do you have to + פועל.",
      },
      {
        id: "g-modals-obligation-13", type: "mcq", prompt: "My doctor says I ___ eat less sugar.",
        options: [
          { text: "must to", errorType: "verb-form", whyHe: "אין to אחרי must." },
          { text: "have", errorType: "verb-form", whyHe: "חסר to: have to eat." },
          { text: "should" },
          { text: "should to", errorType: "verb-form", whyHe: "אין to אחרי should." },
        ],
        answerIndex: 2, explainHe: "המלצה: should + פועל בסיס.",
      },
      { id: "g-modals-obligation-14", type: "fix", prompt: "I must to finish this today.", answer: "I must finish this today.", errorType: "verb-form", explainHe: "אחרי must אין to." },
      { id: "g-modals-obligation-15", type: "fix", prompt: "You mustn't come if you're busy, it's not a problem.", answer: "You don't have to come if you're busy, it's not a problem.", errorType: "modal", explainHe: "\"לא חייב\" = don't have to. mustn't = אסור." },
      { id: "g-modals-obligation-16", type: "fix", prompt: "He have to renew his license next month.", answer: "He has to renew his license next month.", errorType: "agreement", explainHe: "have to בגוף שלישי: has to." },
      { id: "g-modals-obligation-17", type: "fix", prompt: "Did you must wait long at the clinic?", answer: "Did you have to wait long at the clinic?", errorType: "modal", explainHe: "ל-must אין עבר ואין did. שאלה בעבר: Did you have to." },
      { id: "g-modals-obligation-18", type: "transform", prompt: "It is necessary for me to finish the report today.", keyword: "have", answer: "I have to finish the report today.", accept: ["I have to finish this report today."], explainHe: "חובה: have to + פועל בסיס." },
      { id: "g-modals-obligation-19", type: "transform", prompt: "Smoking is not allowed in this building.", keyword: "mustn't", answer: "You mustn't smoke in this building.", accept: ["You must not smoke in this building."], explainHe: "איסור: mustn't + פועל בסיס." },
      { id: "g-modals-obligation-20", type: "transform", prompt: "It isn't necessary to book a table.", keyword: "don't", answer: "You don't have to book a table.", accept: ["We don't have to book a table."], explainHe: "אין חובה: don't have to." },
      { id: "g-modals-obligation-21", type: "order", words: ["had", "to", "We", "the", "cancel", "meeting"], answer: "We had to cancel the meeting.", explainHe: "חובה בעבר: had to + פועל." },
      { id: "g-modals-obligation-22", type: "order", words: ["have", "to", "don't", "You", "early", "get", "up", "tomorrow"], answer: "You don't have to get up early tomorrow.", explainHe: "אין חובה: don't have to + פועל." },
      { id: "g-modals-obligation-23", type: "translate", he: "אתה לא חייב לבוא, אבל כדאי.", answer: "You don't have to come, but you should.", accept: ["You don't have to come but you should."], explainHe: "\"לא חייב\" = don't have to; \"כדאי\" = should." },
      { id: "g-modals-obligation-24", type: "translate", he: "הייתי צריך לעבוד עד מאוחר אתמול.", answer: "I had to work late yesterday.", accept: ["Yesterday I had to work late."], explainHe: "חובה בעבר (ועשיתי): had to." },
    ],
  },

  // ---------------------------------------------------------------------------
  // 15. Advice & suggestions
  // ---------------------------------------------------------------------------
  {
    id: "g-modals-advice",
    title: "Advice & suggestions: should / had better / why don't / let's",
    titleHe: "עצות והצעות",
    strand: "modals",
    order: 15,
    prereqs: ["g-modals-obligation"],
    lesson: {
      explanationHe: [
        "should (ובאופן רשמי יותר ought to) נותן עצה: מה נכון או כדאי לעשות. You should see a doctor. השלילה shouldn't. לבקש עצה: Should I...? / What should I do?",
        "had better (בדיבור: 'd better) הוא עצה חזקה עם אזהרה: אם לא תעשה את זה, יקרה משהו רע. You'd better hurry, or you'll miss the bus. תמיד had (לא have), אחריו פועל בסיס, והשלילה had better not.",
        "להצעות משתמשים בכמה תבניות קבועות: Why don't you / we + פועל בסיס? How about / What about + -ing? Let's + פועל בסיס (ובשלילה Let's not). Shall we + פועל בסיס?",
        "שימו לב לצורה שאחרי כל ביטוי: should, had better, Why don't, Let's ו-Shall we לוקחים פועל בסיס בלי to; How about / What about לוקחים -ing או שם עצם.",
      ],
      form: [
        { label: "Advice: should / shouldn't + base verb", example: "You should call her." },
        { label: "Advice (formal): ought to + base verb", example: "You ought to apologize." },
        { label: "Strong advice / warning: had better (not) + base verb", example: "You'd better not be late." },
        { label: "Suggestion (question): Why don't we / you + base verb?", example: "Why don't we order pizza?" },
        { label: "Suggestion: How about / What about + -ing?", example: "How about going out?" },
        { label: "Suggestion (together): Let's + base verb / Let's not", example: "Let's take a break." },
        { label: "Suggestion (question): Shall we + base verb?", example: "Shall we start?" },
        { label: "Asking for advice: Should I...? / What should I do?", example: "Should I tell him?" },
      ],
      examples: [
        { en: "You should get more sleep.", he: "כדאי לך לישון יותר." },
        { en: "You shouldn't drive when you're this tired.", he: "לא כדאי שתנהג כשאתה כזה עייף." },
        { en: "We'd better leave now, or we'll miss the train.", he: "כדאי מאוד שנצא עכשיו, אחרת נפספס את הרכבת." },
        { en: "You'd better not forget her birthday again.", he: "כדאי לך מאוד לא לשכוח שוב את יום ההולדת שלה." },
        { en: "Why don't you talk to your manager about it?", he: "למה שלא תדבר עם המנהל שלך על זה?" },
        { en: "How about meeting for coffee on Sunday?", he: "מה דעתך שניפגש לקפה ביום ראשון?" },
        { en: "Let's not argue about it now.", he: "בואו לא נתווכח על זה עכשיו." },
        { en: "Should I bring anything to the party?", he: "להביא משהו למסיבה?" },
      ],
      contrastHe: [
        "\"כדאי\" בעברית = should. \"כדאי מאוד, אחרת...\" = had better. had better חזק יותר מ-should ולא משמש לעצות כלליות (לא אומרים You'd better learn English).",
        "\"למה שלא...\" = Why don't you...? בעברית משתמשים בעתיד (\"למה שלא תלך\"), באנגלית don't + פועל בסיס.",
        "\"בוא / בואו נ-\" = Let's + פועל בסיס. בעברית זה עתיד, באנגלית לא. שלילה: Let's not.",
        "אחרי How about / What about בא פועל ב-ing או שם עצם, לא פועל בסיס ולא to.",
      ],
      commonErrors: [
        { wrong: "You should to see a doctor.", right: "You should see a doctor.", whyHe: "should + פועל בסיס, בלי to." },
        { wrong: "You have better hurry.", right: "You'd better hurry.", whyHe: "הביטוי הוא had better (='d better), לא have better." },
        { wrong: "You'd better to go now.", right: "You'd better go now.", whyHe: "אחרי had better אין to." },
        { wrong: "Let's go not out tonight.", right: "Let's not go out tonight.", whyHe: "השלילה: Let's not + פועל." },
        { wrong: "How about to go to the beach?", right: "How about going to the beach?", whyHe: "How about + -ing." },
        { wrong: "Why you don't ask him?", right: "Why don't you ask him?", whyHe: "סדר שאלה: Why don't + נושא + פועל." },
      ],
    },
    items: [
      { id: "g-modals-advice-01", type: "gap", prompt: "You look exhausted. You ___ (take) a day off.", answer: "should take", hint: "should", explainHe: "עצה: should + פועל בסיס." },
      { id: "g-modals-advice-02", type: "gap", prompt: "You ___ (not / eat) so much junk food.", answer: "shouldn't eat", hint: "should", explainHe: "עצה שלילית: shouldn't + פועל בסיס." },
      { id: "g-modals-advice-03", type: "gap", prompt: "It's getting dark. We ___ (leave) now.", answer: "had better leave", accept: ["'d better leave"], hint: "had better", explainHe: "עצה חזקה עם אזהרה: had better + פועל בסיס." },
      { id: "g-modals-advice-04", type: "gap", prompt: "You ___ (not / forget) your passport this time.", answer: "had better not forget", accept: ["'d better not forget"], hint: "had better", explainHe: "השלילה: had better not + פועל." },
      { id: "g-modals-advice-05", type: "gap", prompt: "Why ___ (we / order) pizza tonight?", answer: "don't we order", explainHe: "הצעה: Why don't we + פועל בסיס?" },
      { id: "g-modals-advice-06", type: "gap", prompt: "How about ___ (go) for a walk after dinner?", answer: "going", explainHe: "אחרי How about בא פועל בצורת -ing: How about going?" },
      { id: "g-modals-advice-07", type: "gap", prompt: "___ (not / tell) him yet. Wait until you're sure.", answer: "Let's not tell", hint: "Let's", explainHe: "הצעה שלילית: Let's not + פועל בסיס." },
      { id: "g-modals-advice-08", type: "gap", prompt: "I'm not sure what to do. ___ (I / call) her or wait?", answer: "Should I call", hint: "should", explainHe: "לבקש עצה: Should I + פועל בסיס?" },
      {
        id: "g-modals-advice-09", type: "mcq", prompt: "You ___ see a doctor about that cough.",
        options: [
          { text: "should to", errorType: "verb-form", whyHe: "אין to אחרי should." },
          { text: "should" },
          { text: "ought", errorType: "verb-form", whyHe: "הביטוי הוא ought to." },
          { text: "had better to", errorType: "verb-form", whyHe: "אין to אחרי had better." },
        ],
        answerIndex: 1, explainHe: "עצה: should + פועל בסיס.",
      },
      {
        id: "g-modals-advice-10", type: "mcq", prompt: "The exam starts in ten minutes. We ___ or we'll be late.",
        options: [
          { text: "had better run" },
          { text: "have better run", errorType: "word-choice", whyHe: "הביטוי הוא had better, לא have better." },
          { text: "had better to run", errorType: "verb-form", whyHe: "אין to אחרי had better." },
          { text: "should better run", errorType: "modal", whyHe: "אין ביטוי כזה; או should או had better." },
        ],
        answerIndex: 0, explainHe: "אזהרה: had better + פועל בסיס.",
      },
      {
        id: "g-modals-advice-11", type: "mcq", prompt: "___ eat out tonight?",
        options: [
          { text: "Let's", errorType: "question-form", whyHe: "Let's לא פותח שאלה." },
          { text: "Why don't we" },
          { text: "Why we don't", errorType: "word-order", whyHe: "בשאלה: Why don't we." },
          { text: "How about", errorType: "verb-form", whyHe: "אחרי How about צריך -ing: How about eating out?" },
        ],
        answerIndex: 1, explainHe: "הצעה בשאלה: Why don't we + פועל בסיס?",
      },
      {
        id: "g-modals-advice-12", type: "mcq", prompt: "How about ___ a movie?",
        options: [
          { text: "to watch", errorType: "verb-form", whyHe: "How about + -ing, לא to." },
          { text: "watch", errorType: "verb-form", whyHe: "How about + -ing." },
          { text: "watching" },
          { text: "we will watch", errorType: "tense", whyHe: "אחרי How about לא בא משפט בעתיד." },
        ],
        answerIndex: 2, explainHe: "אחרי How about בא פועל בצורת -ing: How about going?",
      },
      {
        id: "g-modals-advice-13", type: "mcq", prompt: "It's late. ___ go home.",
        options: [
          { text: "Let's" },
          { text: "Let's to", errorType: "verb-form", whyHe: "אין to אחרי Let's." },
          { text: "Let we", errorType: "interference", whyHe: "\"בואו נ-\" = Let's (let us), לא let we." },
          { text: "Let's will", errorType: "tense", whyHe: "אחרי Let's פועל בסיס, בלי will." },
        ],
        answerIndex: 0, explainHe: "הצעה משותפת: Let's + פועל בסיס.",
      },
      { id: "g-modals-advice-14", type: "fix", prompt: "You should to apologize to her.", answer: "You should apologize to her.", errorType: "verb-form", explainHe: "should + פועל בסיס, בלי to." },
      { id: "g-modals-advice-15", type: "fix", prompt: "You have better take an umbrella, it's going to rain.", answer: "You'd better take an umbrella, it's going to rain.", accept: ["You had better take an umbrella, it's going to rain."], errorType: "word-choice", explainHe: "הביטוי הוא had better ('d better)." },
      { id: "g-modals-advice-16", type: "fix", prompt: "Why you don't join us for dinner?", answer: "Why don't you join us for dinner?", errorType: "word-order", explainHe: "סדר השאלה: Why don't you + פועל." },
      { id: "g-modals-advice-17", type: "fix", prompt: "What about to invite the neighbors?", answer: "What about inviting the neighbors?", errorType: "verb-form", explainHe: "אחרי What about בא פועל בצורת -ing: What about taking a break?" },
      { id: "g-modals-advice-18", type: "transform", prompt: "I think it's a good idea for you to rest.", keyword: "should", answer: "You should rest.", accept: ["I think you should rest."], explainHe: "עצה: should + פועל בסיס." },
      { id: "g-modals-advice-19", type: "transform", prompt: "Hurry up, or you'll miss the flight.", keyword: "better", answer: "You'd better hurry up, or you'll miss the flight.", accept: ["You had better hurry up, or you'll miss the flight.", "You'd better hurry, or you'll miss the flight."], explainHe: "אזהרה: had better + פועל בסיס." },
      { id: "g-modals-advice-20", type: "transform", prompt: "Shall we go to the beach on Saturday?", keyword: "about", answer: "How about going to the beach on Saturday?", accept: ["What about going to the beach on Saturday?"], explainHe: "אחרי How about בא פועל בצורת -ing: How about going?" },
      { id: "g-modals-advice-21", type: "order", words: ["don't", "Why", "you", "a", "take", "break"], answer: "Why don't you take a break?", explainHe: "הצעה: Why don't you + פועל בסיס?" },
      { id: "g-modals-advice-22", type: "order", words: ["better", "not", "We'd", "late", "be"], answer: "We'd better not be late.", explainHe: "had better not + פועל בסיס." },
      { id: "g-modals-advice-23", type: "translate", he: "כדאי שתדבר איתו לפני שתחליט.", answer: "You should talk to him before you decide.", accept: ["You should talk to him before deciding.", "You should speak to him before you decide."], explainHe: "\"כדאי ש\" = should. אחרי before הווה, לא עתיד." },
      { id: "g-modals-advice-24", type: "translate", he: "בואו לא נחכה להם, הם תמיד מאחרים.", answer: "Let's not wait for them, they're always late.", accept: ["Let's not wait for them, they are always late."], explainHe: "\"בואו לא\" = Let's not + פועל בסיס." },
    ],
  },

  // ---------------------------------------------------------------------------
  // 16. Deduction
  // ---------------------------------------------------------------------------
  {
    id: "g-modals-deduction",
    title: "Deduction: must / might / can't be",
    titleHe: "הסקה: must be, might be, can't be",
    strand: "modals",
    order: 16,
    prereqs: ["g-modals-obligation"],
    lesson: {
      explanationHe: [
        "מודאלים משמשים לא רק לחובה, אלא גם כדי להגיד עד כמה אנחנו בטוחים במשהו. must be = בטוח (כמעט 100%) על סמך ראיות: The lights are off. They must be asleep.",
        "might / may / could be = אולי, יכול להיות (בערך 50%): She might be at the gym. השלילה: might not / may not be.",
        "can't be = בטוח שלא: He can't be at home, his car isn't here. שימו לב: ההפך של must be הוא can't be, לא mustn't be.",
        "עם פעולה שקורית עכשיו: מודאל + be + -ing (She must be sleeping). עם פועל רגיל: מודאל + פועל בסיס (He must know the answer). כשאין פועל אחר, חייבים be: He must be tired, לא He must tired.",
      ],
      form: [
        { label: "Sure (positive): must + be / base verb", example: "He must be tired." },
        { label: "Possible: might / may / could + be", example: "It might be true." },
        { label: "Sure (negative): can't + be", example: "That can't be right." },
        { label: "Possible negative: might not / may not + be", example: "She might not be home." },
        { label: "Happening now: must / might / can't + be + -ing", example: "They must be joking." },
        { label: "With other verbs: must / might / can't + base verb", example: "He must know the answer." },
        { label: "Question: Could it be...? / Do you think he might...?", example: "Could it be a mistake?" },
      ],
      examples: [
        { en: "You've been working all day. You must be exhausted.", he: "עבדת כל היום, אתה בטח מותש." },
        { en: "The phone is ringing. It might be Dana.", he: "הטלפון מצלצל, אולי זו דנה." },
        { en: "That can't be Tom; he's in London this week.", he: "זה לא יכול להיות טום, הוא בלונדון השבוע." },
        { en: "The lights are on, so someone must be home.", he: "האורות דולקים, אז בטח מישהו בבית." },
        { en: "He isn't answering. He might be driving.", he: "הוא לא עונה, אולי הוא נוהג." },
        { en: "She may not know about the change.", he: "יכול להיות שהיא לא יודעת על השינוי." },
        { en: "It could be a mistake in the system.", he: "זו יכולה להיות טעות במערכת." },
        { en: "They must know each other; look how they talk.", he: "הם בטח מכירים, תראה איך הם מדברים." },
      ],
      contrastHe: [
        "\"בטח\" בעברית = must be (הסקה), לא sure ולא will: \"הוא בטח עייף\" = He must be tired.",
        "\"אולי\" = might / may / could. בעברית אפשר בלי פועל (\"אולי הוא בבית\"), באנגלית חייבים פועל: He might be at home, לא Maybe he at home.",
        "\"לא יכול להיות ש...\" = can't be. mustn't be לא קיים במשמעות הזאת.",
        "אחרי מודאל של הסקה צריך be כשאין פועל אחר: He must be sick, לא He must sick.",
      ],
      commonErrors: [
        { wrong: "He must sick.", right: "He must be sick.", whyHe: "אחרי must צריך be כשאין פועל אחר." },
        { wrong: "She mustn't be at work, her car isn't here.", right: "She can't be at work, her car isn't here.", whyHe: "ההסקה השלילית היא can't be." },
        { wrong: "It can be Dan at the door.", right: "It might be Dan at the door.", whyHe: "can לא משמש לניחוש על מקרה ספציפי; משתמשים ב-might / may / could." },
        { wrong: "They must to be twins.", right: "They must be twins.", whyHe: "אין to אחרי must." },
        { wrong: "He must is joking.", right: "He must be joking.", whyHe: "אחרי מודאל תמיד צורת בסיס: be." },
        { wrong: "She might not to come.", right: "She might not come.", whyHe: "אין to אחרי might." },
      ],
    },
    items: [
      { id: "g-modals-deduction-01", type: "gap", prompt: "You haven't eaten all day. You ___ (be) starving.", answer: "must be", hint: "בטוח", explainHe: "הסקה בטוחה: must be." },
      { id: "g-modals-deduction-02", type: "gap", prompt: "I don't know where Yossi is. He ___ (be) at lunch.", answer: "might be", accept: ["may be", "could be"], hint: "אולי", explainHe: "אפשרות: might / may / could be." },
      { id: "g-modals-deduction-03", type: "gap", prompt: "That ___ (be) Sara's car; hers is red, not blue.", answer: "can't be", accept: ["cannot be", "couldn't be"], hint: "בטוח שלא", explainHe: "הסקה שלילית בטוחה: can't be." },
      { id: "g-modals-deduction-04", type: "gap", prompt: "The baby is quiet. She ___ (sleep).", answer: "must be sleeping", hint: "בטוח, פעולה עכשיו", explainHe: "פעולה שקורית עכשיו: must be + -ing." },
      { id: "g-modals-deduction-05", type: "gap", prompt: "Don't call now; he ___ (drive) home.", answer: "might be driving", accept: ["may be driving", "could be driving"], hint: "אולי, פעולה עכשיו", explainHe: "אפשרות + פעולה מתמשכת: might be + -ing." },
      { id: "g-modals-deduction-06", type: "gap", prompt: "She speaks with an accent. She ___ (come) from another country.", answer: "must come", hint: "בטוח", explainHe: "עם פועל רגיל: must + פועל בסיס (בלי be)." },
      { id: "g-modals-deduction-07", type: "gap", prompt: "They ___ (not / know) about the party yet. Nobody told them.", answer: "might not know", accept: ["may not know"], hint: "אולי לא", explainHe: "אפשרות שלילית: might not / may not + פועל בסיס." },
      { id: "g-modals-deduction-08", type: "gap", prompt: "It's 3 a.m. there. He ___ (be) awake.", answer: "can't be", accept: ["cannot be"], hint: "בטוח שלא", explainHe: "בטוח שלא: can't be. לא mustn't be." },
      {
        id: "g-modals-deduction-09", type: "mcq", prompt: "He's wearing a heavy coat in August. He ___ crazy.",
        options: [
          { text: "must be" },
          { text: "must", errorType: "verb-form", whyHe: "חסר be לפני שם תואר." },
          { text: "must is", errorType: "verb-form", whyHe: "אחרי מודאל צורת בסיס: be." },
          { text: "can be", errorType: "modal", whyHe: "can לא משמש להסקה על מקרה ספציפי." },
        ],
        answerIndex: 0, explainHe: "הסקה בטוחה + שם תואר: must be.",
      },
      {
        id: "g-modals-deduction-10", type: "mcq", prompt: "The door is locked and the lights are off. They ___ home.",
        options: [
          { text: "must be", errorType: "word-choice", whyHe: "הראיות מובילות למסקנה שלילית." },
          { text: "can't be" },
          { text: "mustn't be", errorType: "modal", whyHe: "ההסקה השלילית היא can't be." },
          { text: "aren't able to be", errorType: "modal", whyHe: "זו יכולת, לא הסקה." },
        ],
        answerIndex: 1, explainHe: "בטוח שלא: can't be.",
      },
      {
        id: "g-modals-deduction-11", type: "mcq", prompt: "Someone is knocking. It ___ the delivery guy.",
        options: [
          { text: "can be", errorType: "modal", whyHe: "לניחוש על מקרה ספציפי: might / may / could." },
          { text: "might be" },
          { text: "might", errorType: "verb-form", whyHe: "חסר be." },
          { text: "must", errorType: "verb-form", whyHe: "חסר be, וגם לא בטוחים." },
        ],
        answerIndex: 1, explainHe: "אפשרות: might be.",
      },
      {
        id: "g-modals-deduction-12", type: "mcq", prompt: "She's been running for two hours. She ___ tired.",
        options: [
          { text: "must to be", errorType: "verb-form", whyHe: "אין to אחרי must." },
          { text: "must be" },
          { text: "must", errorType: "verb-form", whyHe: "חסר be לפני שם תואר." },
          { text: "can be", errorType: "modal", whyHe: "can לא מבטא הסקה על מצב ספציפי." },
        ],
        answerIndex: 1, explainHe: "הסקה בטוחה: must be + שם תואר.",
      },
      {
        id: "g-modals-deduction-13", type: "mcq", prompt: "I'm not sure. The meeting ___ tomorrow, not today.",
        options: [
          { text: "must be", errorType: "word-choice", whyHe: "הדובר לא בטוח (I'm not sure)." },
          { text: "might be" },
          { text: "can't be", errorType: "word-choice", whyHe: "זו לא שלילה בטוחה." },
          { text: "can be", errorType: "modal", whyHe: "can לא משמש לניחוש ספציפי." },
        ],
        answerIndex: 1, explainHe: "חוסר ודאות: might be.",
      },
      { id: "g-modals-deduction-14", type: "fix", prompt: "He must tired after such a long flight.", answer: "He must be tired after such a long flight.", errorType: "verb-form", explainHe: "אחרי must צריך be לפני שם תואר." },
      { id: "g-modals-deduction-15", type: "fix", prompt: "That mustn't be true, I saw him yesterday.", answer: "That can't be true, I saw him yesterday.", errorType: "modal", explainHe: "הסקה שלילית: can't be, לא mustn't be." },
      { id: "g-modals-deduction-16", type: "fix", prompt: "She can be at the gym, she goes there on Tuesdays.", answer: "She might be at the gym, she goes there on Tuesdays.", accept: ["She may be at the gym, she goes there on Tuesdays.", "She could be at the gym, she goes there on Tuesdays."], errorType: "modal", explainHe: "ניחוש על מקרה ספציפי: might / may / could, לא can." },
      { id: "g-modals-deduction-17", type: "fix", prompt: "They must to be very rich; look at their house.", answer: "They must be very rich; look at their house.", errorType: "verb-form", explainHe: "אין to אחרי must." },
      { id: "g-modals-deduction-18", type: "transform", prompt: "I'm sure he is at work now.", keyword: "must", answer: "He must be at work now.", explainHe: "כשאתה בטוח שמשהו נכון, ההסקה היא must be: הוא בטח בבית = He must be home." },
      { id: "g-modals-deduction-19", type: "transform", prompt: "Maybe she is in a meeting.", keyword: "might", answer: "She might be in a meeting.", explainHe: "\"אולי\" בהסקה = might be או could be, לא maybe בתוך הפועל." },
      { id: "g-modals-deduction-20", type: "transform", prompt: "I'm sure that isn't his real name.", keyword: "can't", answer: "That can't be his real name.", explainHe: "כשאתה בטוח שמשהו לא נכון, השלילה בהסקה היא can't be, לא mustn't be." },
      { id: "g-modals-deduction-21", type: "order", words: ["be", "must", "You", "joking"], answer: "You must be joking.", explainHe: "must be + -ing: הסקה על מה שקורה עכשיו." },
      { id: "g-modals-deduction-22", type: "order", words: ["can't", "It", "be", "that", "expensive"], answer: "It can't be that expensive.", explainHe: "בטוח שלא: can't be." },
      { id: "g-modals-deduction-23", type: "translate", he: "הוא בטח בדרך, הוא יצא לפני שעה.", answer: "He must be on his way, he left an hour ago.", accept: ["He must be on the way, he left an hour ago."], explainHe: "\"בטח\" = must be." },
      { id: "g-modals-deduction-24", type: "translate", he: "זה לא יכול להיות דני, הוא בחו״ל.", answer: "It can't be Danny, he's abroad.", accept: ["That can't be Danny, he's abroad.", "It can't be Danny, he is abroad."], explainHe: "\"לא יכול להיות\" = can't be." },
    ],
  },

  // ---------------------------------------------------------------------------
  // 17. Past modals
  // ---------------------------------------------------------------------------
  {
    id: "g-modals-past",
    title: "Past modals: should have / could have / must have",
    titleHe: "מודאלים בעבר",
    strand: "modals",
    order: 17,
    prereqs: ["g-modals-deduction", "g-past-simple"],
    lesson: {
      explanationHe: [
        "מודאל + have + V3 מדבר על העבר. יש שתי משפחות. הראשונה: הסקה על העבר. must have = בטח קרה (He must have forgotten), might / may / could have = אולי קרה, can't / couldn't have = בטוח שלא קרה.",
        "המשפחה השנייה: חרטה וביקורת. should have = היה צריך, ולא עשה (I should have called). shouldn't have = לא היה צריך, אבל עשה (You shouldn't have said that). could have = היה יכול, אבל לא (We could have won).",
        "צורה: מודאל + have + past participle. ה-have לא משתנה אף פעם (לא has, לא had). בדיבור: should've, must've, could've. שלילה: shouldn't have, might not have, can't have.",
        "אזהרה: should of נשמע כמו should've, אבל זו שגיאת כתיב. תמיד have.",
      ],
      form: [
        { label: "Regret (didn't do it): should have + V3", example: "I should have called." },
        { label: "Criticism (did it): shouldn't have + V3", example: "You shouldn't have said that." },
        { label: "Missed possibility: could have + V3", example: "We could have won." },
        { label: "Sure about the past: must have + V3", example: "He must have forgotten." },
        { label: "Possible in the past: might / may have + V3", example: "She might have missed the bus." },
        { label: "Sure it didn't happen: can't / couldn't have + V3", example: "You can't have seen him." },
        { label: "Spoken forms: should've / must've / could've", example: "I should've known." },
      ],
      examples: [
        { en: "I should have listened to you.", he: "הייתי צריך להקשיב לך." },
        { en: "You shouldn't have spent so much on shoes.", he: "לא היית צריך להוציא כל כך הרבה על נעליים." },
        { en: "We could have taken the train; it was faster.", he: "יכולנו לקחת את הרכבת, זה היה מהיר יותר." },
        { en: "The floor is wet. Someone must have spilled water.", he: "הרצפה רטובה, מישהו בטח שפך מים." },
        { en: "She's not here yet. She might have missed the bus.", he: "היא עוד לא פה, אולי היא פספסה את האוטובוס." },
        { en: "You can't have seen Ron; he was abroad.", he: "לא יכול להיות שראית את רון, הוא היה בחו״ל." },
        { en: "He may not have received my message.", he: "ייתכן שהוא לא קיבל את ההודעה שלי." },
        { en: "I could have helped if you had asked.", he: "יכולתי לעזור אם היית מבקש." },
      ],
      contrastHe: [
        "\"הייתי צריך\" בעברית משמש גם ל-had to (וגם עשיתי) וגם ל-should have (ולא עשיתי). באנגלית: I had to go = הלכתי; I should have gone = לא הלכתי.",
        "\"יכולתי\" = could have (הייתה אפשרות ולא ניצלתי אותה), לעומת was able to (הצלחתי). \"יכולתי לבוא אבל לא רציתי\" = I could have come.",
        "\"בטח שכח\" = must have forgotten. בעברית \"בטח\" + עבר; באנגלית must + have + V3, לא must forgot.",
        "\"לא היה צריך\" = shouldn't have (ביקורת על מה שנעשה), לא didn't have to (לא היה חייב).",
      ],
      commonErrors: [
        { wrong: "I should call her yesterday.", right: "I should have called her yesterday.", whyHe: "חרטה על העבר: should have + V3." },
        { wrong: "He must forgot the meeting.", right: "He must have forgotten the meeting.", whyHe: "הסקה על העבר: must have + V3." },
        { wrong: "You should of told me.", right: "You should have told me.", whyHe: "of זו שגיאת שמיעה; תמיד have." },
        { wrong: "She should has come earlier.", right: "She should have come earlier.", whyHe: "ה-have לא משתנה אחרי מודאל." },
        { wrong: "They mustn't have seen us.", right: "They can't have seen us.", whyHe: "הסקה שלילית על העבר: can't / couldn't have." },
        { wrong: "I could to have helped.", right: "I could have helped.", whyHe: "אין to אחרי מודאל." },
      ],
    },
    items: [
      { id: "g-modals-past-01", type: "gap", prompt: "I failed the test. I ___ (study) more.", answer: "should have studied", accept: ["should've studied"], hint: "should", explainHe: "חרטה: should have + V3." },
      { id: "g-modals-past-02", type: "gap", prompt: "You ___ (not / tell) her; now she's upset.", answer: "shouldn't have told", hint: "should", explainHe: "ביקורת על מה שנעשה: shouldn't have + V3." },
      { id: "g-modals-past-03", type: "gap", prompt: "The ground is wet. It ___ (rain) last night.", answer: "must have rained", accept: ["must've rained"], hint: "בטוח", explainHe: "הסקה על העבר: must have + V3." },
      { id: "g-modals-past-04", type: "gap", prompt: "He didn't answer. He ___ (be) asleep.", answer: "might have been", accept: ["may have been", "could have been"], hint: "אולי", explainHe: "אפשרות בעבר: might have + V3 (been)." },
      { id: "g-modals-past-05", type: "gap", prompt: "You ___ (not / see) Maya at the party; she was in Eilat.", answer: "can't have seen", accept: ["couldn't have seen", "cannot have seen"], hint: "בטוח שלא", explainHe: "בטוח שלא קרה: can't / couldn't have + V3." },
      { id: "g-modals-past-06", type: "gap", prompt: "We ___ (take) a taxi, but we decided to walk.", answer: "could have taken", accept: ["could've taken"], hint: "אפשרות שלא נוצלה", explainHe: "אפשרות שלא נוצלה: could have + V3." },
      { id: "g-modals-past-07", type: "gap", prompt: "She's late. She ___ (miss) the train.", answer: "might have missed", accept: ["may have missed", "could have missed"], hint: "אולי", explainHe: "ניחוש על העבר: might have + V3." },
      { id: "g-modals-past-08", type: "gap", prompt: "Ron ___ (forget) about our meeting; he never showed up.", answer: "must have forgotten", accept: ["must've forgotten"], hint: "בטוח", explainHe: "הסקה על העבר: must have + V3 (forgotten)." },
      {
        id: "g-modals-past-09", type: "mcq", prompt: "I ___ you, but my phone died.",
        options: [
          { text: "should call", errorType: "tense", whyHe: "מדובר על העבר: should have + V3." },
          { text: "should have called" },
          { text: "should of called", errorType: "spelling", whyHe: "of זו שגיאת שמיעה; צריך have." },
          { text: "should has called", errorType: "verb-form", whyHe: "have לא משתנה אחרי מודאל." },
        ],
        answerIndex: 1, explainHe: "חרטה על העבר: should have + V3.",
      },
      {
        id: "g-modals-past-10", type: "mcq", prompt: "The lights were off. They ___ out.",
        options: [
          { text: "must go", errorType: "tense", whyHe: "הסקה על העבר: must have + V3." },
          { text: "must have gone" },
          { text: "must went", errorType: "verb-form", whyHe: "אחרי מודאל לא בא past simple." },
          { text: "must have go", errorType: "verb-form", whyHe: "אחרי have צריך V3: gone." },
        ],
        answerIndex: 1, explainHe: "הסקה על העבר: must have gone.",
      },
      {
        id: "g-modals-past-11", type: "mcq", prompt: "She knew everything about it. Someone ___ her.",
        options: [
          { text: "must have told" },
          { text: "must told", errorType: "verb-form", whyHe: "חסר have: must have told." },
          { text: "mustn't have told", errorType: "modal", whyHe: "ההיגיון הפוך, וגם mustn't לא משמש להסקה." },
          { text: "should tell", errorType: "tense", whyHe: "זו הסקה על העבר, לא עצה." },
        ],
        answerIndex: 0, explainHe: "הסקה בטוחה על העבר: must have + V3.",
      },
      {
        id: "g-modals-past-12", type: "mcq", prompt: "You ___ Ilan yesterday; he was in the hospital.",
        options: [
          { text: "can't have met" },
          { text: "mustn't have met", errorType: "modal", whyHe: "הסקה שלילית: can't have." },
          { text: "can't met", errorType: "verb-form", whyHe: "חסר have." },
          { text: "shouldn't have met", errorType: "word-choice", whyHe: "זו ביקורת, לא הסקה." },
        ],
        answerIndex: 0, explainHe: "בטוח שלא קרה: can't have + V3.",
      },
      {
        id: "g-modals-past-13", type: "mcq", prompt: "We ___ the early flight, but we overslept.",
        options: [
          { text: "could take", errorType: "tense", whyHe: "אפשרות שלא נוצלה בעבר: could have + V3." },
          { text: "could have taken" },
          { text: "could taken", errorType: "verb-form", whyHe: "חסר have." },
          { text: "can have taken", errorType: "modal", whyHe: "can לא מתחבר ל-have + V3 בחיוב." },
        ],
        answerIndex: 1, explainHe: "אפשרות שלא נוצלה: could have taken.",
      },
      { id: "g-modals-past-14", type: "fix", prompt: "You should of asked me first.", answer: "You should have asked me first.", errorType: "spelling", explainHe: "should've = should have, לא should of." },
      { id: "g-modals-past-15", type: "fix", prompt: "He must forgot to lock the door.", answer: "He must have forgotten to lock the door.", errorType: "verb-form", explainHe: "הסקה על העבר: must have + V3." },
      { id: "g-modals-past-16", type: "fix", prompt: "I should call you yesterday, sorry.", answer: "I should have called you yesterday, sorry.", errorType: "tense", explainHe: "חרטה על העבר: should have + V3." },
      { id: "g-modals-past-17", type: "fix", prompt: "She could has won the race if she'd tried.", answer: "She could have won the race if she'd tried.", errorType: "verb-form", explainHe: "have לא משתנה אחרי מודאל." },
      { id: "g-modals-past-18", type: "transform", prompt: "It was a mistake for me to sell the car.", keyword: "shouldn't", answer: "I shouldn't have sold the car.", explainHe: "ביקורת על מה שנעשה: shouldn't have + V3." },
      { id: "g-modals-past-19", type: "transform", prompt: "I'm sure he missed the bus.", keyword: "must", answer: "He must have missed the bus.", explainHe: "I'm sure + עבר = must have + V3." },
      { id: "g-modals-past-20", type: "transform", prompt: "It's possible that she forgot about it.", keyword: "might", answer: "She might have forgotten about it.", explainHe: "אפשרות בעבר: might have + V3." },
      { id: "g-modals-past-21", type: "order", words: ["have", "should", "I", "earlier", "left"], answer: "I should have left earlier.", explainHe: "חרטה: should have + V3." },
      { id: "g-modals-past-22", type: "order", words: ["must", "He", "been", "have", "tired", "very"], answer: "He must have been very tired.", explainHe: "הסקה על העבר: must have been." },
      { id: "g-modals-past-23", type: "translate", he: "הייתי צריך להתקשר אליה, אבל שכחתי.", answer: "I should have called her, but I forgot.", accept: ["I should've called her, but I forgot."], explainHe: "\"הייתי צריך\" ולא עשיתי = should have + V3." },
      { id: "g-modals-past-24", type: "translate", he: "הם בטח פספסו את הטיסה.", answer: "They must have missed the flight.", accept: ["They must've missed the flight."], explainHe: "\"בטח\" + עבר = must have + V3." },
    ],
  },
];
