import type { GrammarTopic } from "@/lib/types";

export const NOUNS_PREPOSITIONS_PATTERNS: GrammarTopic[] = [
  // ------------------------------------------------------------------
  // 30. Articles: a / an / the
  // ------------------------------------------------------------------
  {
    id: "g-articles-a-an-the",
    title: "Articles: a / an / the",
    titleHe: "תוויות: a, an, the",
    strand: "articles-nouns",
    order: 30,
    prereqs: [],
    lesson: {
      explanationHe: [
        "בעברית יש רק 'ה' הידיעה, ואין מילה שאומרת 'איזשהו אחד'. לכן דוברי עברית משמיטים a/an: 'יש לי כלב' יוצא I have dog. באנגלית שם עצם ספיר ביחיד כמעט אף פעם לא עומד לבד: צריך לפניו a/an, the, או מילה כמו my, this, one.",
        "a/an = אחד מתוך רבים, משהו שהשומע עדיין לא מכיר: I saw a dog. משתמשים בו גם למקצועות (She's a teacher), לתדירות (twice a week), ואחרי what בקריאה (What a day!).",
        "the = ספציפי, שני הצדדים יודעים על מה מדובר: כבר הוזכר (I saw a dog. The dog was huge), יחיד בהקשר (the sun, the kitchen, the boss), או מוגדר על ידי ההמשך (the book you gave me), וגם עם superlative (the best).",
        "a או an? לפי הצליל, לא לפי האות: an hour, an honest man (h שקטה), אבל a university, a European, a one-way street (צליל y/w). an MBA, an X-ray (שם האות מתחיל בתנועה).",
        "הכלל הפשוט לסיפור: פעם ראשונה a, מהפעם השנייה the. אם אתם לא בטוחים ואין 'ה' בעברית, כנראה צריך a/an, לא כלום.",
      ],
      form: [
        { label: "a + צליל עיצור", example: "a car, a house, a university, a European" },
        { label: "an + צליל תנועה", example: "an apple, an hour, an honest man, an MBA" },
        { label: "the + ספציפי/ידוע", example: "the car I bought, the sun, the kitchen, the best" },
        { label: "a/an + מקצוע", example: "She's an engineer. He's a nurse." },
        { label: "a + תדירות", example: "once a week, twice a day, 80 km an hour" },
        { label: "what a / such a", example: "What a great idea! It was such a long day." },
      ],
      examples: [
        { en: "I have a dog and two cats.", he: "יש לי כלב ושני חתולים." },
        { en: "She's an engineer at a startup.", he: "היא מהנדסת בסטארט-אפ." },
        { en: "We waited for an hour.", he: "חיכינו שעה." },
        { en: "I bought a phone, but the phone doesn't work.", he: "קניתי טלפון, אבל הטלפון לא עובד." },
        { en: "Can you close the door? It's cold.", he: "אתה יכול לסגור את הדלת? קר." },
        { en: "He goes to the gym twice a week.", he: "הוא הולך לחדר כושר פעמיים בשבוע." },
        { en: "This is the best pizza in town.", he: "זו הפיצה הכי טובה בעיר." },
        { en: "What a beautiful day!", he: "איזה יום יפה!" },
      ],
      contrastHe: [
        "בעברית אומרים 'יש לי אח' בלי שום מילה לפני 'אח'. באנגלית חייבים: I have a brother.",
        "בעברית 'היא רופאה' — באנגלית She's a doctor. מקצוע ביחיד תמיד עם a/an.",
        "בעברית 'פעם בשבוע' (עם ב'). באנגלית once a week — בלי in.",
        "בעברית 'איזה יום יפה!' — באנגלית What a beautiful day! (עם a).",
      ],
      commonErrors: [
        { wrong: "I have dog.", right: "I have a dog.", whyHe: "שם עצם ספיר ביחיד לא עומד לבד. אין 'ה' בעברית? כנראה צריך a." },
        { wrong: "She is teacher.", right: "She is a teacher.", whyHe: "מקצועות ביחיד תמיד עם a/an." },
        { wrong: "It took a hour.", right: "It took an hour.", whyHe: "ה-h ב-hour שקטה, הצליל מתחיל בתנועה, לכן an." },
        { wrong: "He studies at an university.", right: "He studies at a university.", whyHe: "university מתחיל בצליל y (יו), עיצור, לכן a." },
        { wrong: "We go out once in a week.", right: "We go out once a week.", whyHe: "תדירות: once/twice a week, בלי in. תרגום ישיר של 'פעם בשבוע' שגוי." },
        { wrong: "It's a same problem.", right: "It's the same problem.", whyHe: "same תמיד עם the: the same." },
      ],
    },
    items: [
      {
        id: "g-articles-a-an-the-01",
        type: "gap",
        prompt: "I saw ___ dog in the park, and it followed me home. (a / an / the / - = no article)",
        answer: "a",
        hint: "הזכרה ראשונה של הכלב",
        explainHe: "הזכרה ראשונה של משהו שהשומע לא מכיר: a dog.",
      },
      {
        id: "g-articles-a-an-the-02",
        type: "gap",
        prompt: "She's ___ engineer at a startup in Herzliya. (a / an / the / -)",
        answer: "an",
        explainHe: "מקצוע ביחיד צריך a/an. engineer מתחיל בצליל תנועה, לכן an.",
      },
      {
        id: "g-articles-a-an-the-03",
        type: "gap",
        prompt: "We waited for ___ hour, and then we left. (a / an / the / -)",
        answer: "an",
        hint: "ה-h שקטה",
        explainHe: "hour נשמע 'אאוור', מתחיל בתנועה, לכן an hour.",
      },
      {
        id: "g-articles-a-an-the-04",
        type: "gap",
        prompt: "Can you close ___ door? It's really cold in here. (a / an / the / -)",
        answer: "the",
        explainHe: "שנינו יודעים על איזו דלת מדובר (הדלת של החדר), לכן the.",
      },
      {
        id: "g-articles-a-an-the-05",
        type: "gap",
        prompt: "He goes to the gym twice ___ week. (a / an / the / -)",
        answer: "a",
        explainHe: "תדירות: twice a week. בעברית 'פעמיים בשבוע', באנגלית בלי in.",
      },
      {
        id: "g-articles-a-an-the-06",
        type: "gap",
        prompt: "I bought a phone yesterday, but ___ phone doesn't work. (a / an / the / -)",
        answer: "the",
        explainHe: "הטלפון כבר הוזכר, מהפעם השנייה the.",
      },
      {
        id: "g-articles-a-an-the-07",
        type: "gap",
        prompt: "My sister is studying at ___ university in Haifa. (a / an / the / -)",
        answer: "a",
        hint: "לפי הצליל, לא לפי האות",
        explainHe: "university מתחיל בצליל 'יו' (עיצור), לכן a university, לא an.",
      },
      {
        id: "g-articles-a-an-the-08",
        type: "gap",
        prompt: "___ sun was shining when we left the house. (a / an / the / -)",
        answer: "the",
        accept: ["The"],
        explainHe: "יש רק שמש אחת, לכן the sun.",
      },
      {
        id: "g-articles-a-an-the-09",
        type: "mcq",
        prompt: "My brother is ___ .",
        options: [
          { text: "a doctor" },
          { text: "doctor", errorType: "article", whyHe: "בעברית 'אחי רופא', אבל באנגלית מקצוע ביחיד חייב a." },
          { text: "the doctor", errorType: "article", whyHe: "the אומר 'הרופא הספציפי שאנחנו מכירים'. כאן זה סתם מקצוע." },
        ],
        answerIndex: 0,
        explainHe: "מקצוע = a/an: My brother is a doctor.",
      },
      {
        id: "g-articles-a-an-the-10",
        type: "mcq",
        prompt: "It took me ___ to get there.",
        options: [
          { text: "a hour", errorType: "article", whyHe: "ה-h שקטה, הצליל מתחיל בתנועה, לכן an." },
          { text: "an hour" },
          { text: "hour", errorType: "article", whyHe: "שם עצם ספיר ביחיד לא עומד לבד." },
        ],
        answerIndex: 1,
        explainHe: "an hour: לפי הצליל (אאוור), לא לפי האות.",
      },
      {
        id: "g-articles-a-an-the-11",
        type: "mcq",
        prompt: "This is ___ pizza in town.",
        options: [
          { text: "the best" },
          { text: "a best", errorType: "article", whyHe: "superlative (best, biggest) תמיד עם the." },
          { text: "best", errorType: "article", whyHe: "בעברית 'הכי טובה' — באנגלית the best, לא best לבד." },
        ],
        answerIndex: 0,
        explainHe: "superlative תמיד עם the: the best, the most expensive.",
      },
      {
        id: "g-articles-a-an-the-12",
        type: "mcq",
        prompt: "I read ___ book you gave me. It was great.",
        options: [
          { text: "a", errorType: "article", whyHe: "'you gave me' מגדיר בדיוק איזה ספר, לכן the." },
          { text: "the" },
          { text: "an", errorType: "article", whyHe: "book מתחיל בעיצור, וגם: הספר ספציפי, צריך the." },
        ],
        answerIndex: 1,
        explainHe: "שם עצם שמוגדר על ידי ההמשך (the book you gave me) מקבל the.",
      },
      {
        id: "g-articles-a-an-the-13",
        type: "mcq",
        prompt: "What ___ beautiful day!",
        options: [
          { text: "the", errorType: "article", whyHe: "בקריאה עם what משתמשים ב-a: What a day!" },
          { text: "a" },
          { text: "-", errorType: "article", whyHe: "בעברית 'איזה יום יפה' בלי כלום, אבל באנגלית What a beautiful day." },
        ],
        answerIndex: 1,
        explainHe: "What a + שם עצם ספיר ביחיד: What a beautiful day!",
      },
      {
        id: "g-articles-a-an-the-14",
        type: "fix",
        prompt: "I have dog and two cats.",
        answer: "I have a dog and two cats.",
        errorType: "article",
        explainHe: "dog ביחיד לא עומד לבד: a dog. cats ברבים עם מספר, אין בעיה.",
      },
      {
        id: "g-articles-a-an-the-15",
        type: "fix",
        prompt: "She is teacher in Tel Aviv.",
        answer: "She is a teacher in Tel Aviv.",
        errorType: "article",
        explainHe: "מקצוע ביחיד: a teacher. בעברית 'היא מורה' בלי כלום, באנגלית חייבים a.",
      },
      {
        id: "g-articles-a-an-the-16",
        type: "fix",
        prompt: "He bought an new car last month.",
        answer: "He bought a new car last month.",
        errorType: "article",
        explainHe: "מסתכלים על המילה שמיד אחרי התווית: new מתחיל בעיצור, לכן a new car.",
      },
      {
        id: "g-articles-a-an-the-17",
        type: "fix",
        prompt: "We go to the movies once in a week.",
        answer: "We go to the movies once a week.",
        errorType: "interference",
        explainHe: "תדירות: once a week, בלי in. 'פעם בשבוע' לא מתורגם מילה במילה.",
      },
      {
        id: "g-articles-a-an-the-18",
        type: "fix",
        prompt: "This is a same problem we had yesterday.",
        answer: "This is the same problem we had yesterday.",
        errorType: "article",
        explainHe: "same תמיד עם the: the same problem.",
      },
      {
        id: "g-articles-a-an-the-19",
        type: "transform",
        prompt: "She teaches math.",
        keyword: "teacher",
        answer: "She is a math teacher.",
        accept: ["She's a math teacher."],
        explainHe: "מקצוע ביחיד עם a: a math teacher.",
      },
      {
        id: "g-articles-a-an-the-20",
        type: "transform",
        prompt: "I eat at a restaurant on Mondays and on Thursdays.",
        keyword: "twice",
        answer: "I eat at a restaurant twice a week.",
        accept: ["I eat out twice a week.", "I eat at a restaurant twice a week"],
        explainHe: "תדירות: twice a week (לא twice in a week).",
      },
      {
        id: "g-articles-a-an-the-21",
        type: "order",
        words: ["I", "saw", "an", "old", "man", "at", "the", "bus", "stop"],
        answer: "I saw an old man at the bus stop.",
        explainHe: "an old man: old מתחיל בתנועה. the bus stop: תחנה ספציפית שידועה לשנינו.",
      },
      {
        id: "g-articles-a-an-the-22",
        type: "order",
        words: ["the", "movie", "we", "watched", "was", "a", "bit", "boring"],
        answer: "The movie we watched was a bit boring.",
        explainHe: "the movie we watched — מוגדר על ידי ההמשך. a bit = קצת.",
      },
      {
        id: "g-articles-a-an-the-23",
        type: "translate",
        he: "יש לי אח ואחות.",
        answer: "I have a brother and a sister.",
        accept: ["I have a brother and sister.", "I've got a brother and a sister.", "I've got a brother and sister."],
        explainHe: "בעברית בלי כלום לפני 'אח'. באנגלית: a brother, a sister.",
      },
      {
        id: "g-articles-a-an-the-24",
        type: "translate",
        he: "היא רופאה בבית חולים גדול.",
        answer: "She is a doctor in a big hospital.",
        accept: ["She is a doctor at a big hospital.", "She's a doctor in a big hospital.", "She's a doctor at a big hospital.", "She is a doctor in a large hospital.", "She is a doctor at a large hospital."],
        explainHe: "a doctor (מקצוע), a big hospital (הזכרה ראשונה, אחד מרבים).",
      },
    ],
  },

  // ------------------------------------------------------------------
  // 31. Zero article & general statements
  // ------------------------------------------------------------------
  {
    id: "g-articles-zero-general",
    title: "Zero article & general statements",
    titleHe: "בלי תווית: הכללות, שמות, ארוחות",
    strand: "articles-nouns",
    order: 31,
    prereqs: ["g-articles-a-an-the"],
    lesson: {
      explanationHe: [
        "כאן הבעיה הפוכה: דוברי עברית מוסיפים the שלא צריך. בעברית הכללה מקבלת 'ה': 'החיים קשים', 'אני אוהב את המוזיקה', 'האנשים פה נחמדים'. באנגלית הכללה היא בלי תווית: Life is hard. I love music. People here are nice.",
        "הכלל: רבים או לא ספיר במשמעות כללית = בלי תווית (Dogs are loyal, Coffee is expensive). ברגע שמדברים על קבוצה ספציפית, חוזר the: The dogs next door bark all night. The coffee at this place is great.",
        "בלי תווית גם עם: ארוחות (have breakfast/lunch/dinner), שפות ומקצועות לימוד (speak English, study math), ספורט (play soccer), ורוב שמות: אנשים, ערים, רחובות, רוב המדינות (Israel, Paris). מוסדות בתפקידם: go to school/work/bed, at home, in prison (באנגלית אמריקאית: in the hospital).",
        "עוד בלי תווית: זמן עם next/last/this/every (next week, last year, every day), ו-watch TV, by bus/car. אבל: listen to the radio, in the morning, on the weekend.",
        "the כן מופיע עם: מדינות ברבים או עם מילה כללית (the United States, the UK, the Netherlands), נהרות וימים (the Jordan, the Mediterranean), ומשפחות ברבים (the Cohens).",
      ],
      form: [
        { label: "הכללה: רבים / לא ספיר", example: "Dogs are loyal. Music helps me relax. Life is short." },
        { label: "קבוצה ספציפית = the", example: "The dogs next door bark. The music at the party was loud." },
        { label: "ארוחות", example: "have breakfast / lunch / dinner (בלי the)" },
        { label: "שפות, מקצועות, ספורט", example: "speak Hebrew, study history, play basketball" },
        { label: "מוסדות בתפקידם", example: "go to school / work / bed, be at home, at work" },
        { label: "זמן עם next / last / every", example: "next week, last month, every Friday" },
        { label: "שמות עם the", example: "the US, the UK, the Netherlands, the Mediterranean" },
      ],
      examples: [
        { en: "Life is short, so enjoy it.", he: "החיים קצרים, אז תיהנה מהם." },
        { en: "I love music, especially jazz.", he: "אני אוהב מוזיקה, במיוחד ג'אז." },
        { en: "People are usually friendly here.", he: "האנשים פה בדרך כלל ידידותיים." },
        { en: "We had dinner at a nice restaurant.", he: "אכלנו ארוחת ערב במסעדה נחמדה." },
        { en: "My son goes to school by bus.", he: "הבן שלי נוסע לבית הספר באוטובוס." },
        { en: "She speaks Spanish and a little French.", he: "היא מדברת ספרדית וקצת צרפתית." },
        { en: "The coffee at this place is excellent.", he: "הקפה במקום הזה מצוין." },
        { en: "He's from the United States.", he: "הוא מארצות הברית." },
      ],
      contrastHe: [
        "בעברית 'החיים יפים' עם 'ה'. באנגלית הכללה בלי תווית: Life is beautiful.",
        "בעברית 'אני אוהב את הקפה' יכול להיות כללי. באנגלית I love coffee = כללי, I love the coffee = הקפה הזה, הספציפי.",
        "בעברית 'ארוחת הערב' עם 'ה'. באנגלית: dinner, בלי the: We had dinner at eight.",
        "בעברית 'בשבוע הבא' עם 'ה'. באנגלית next week, בלי the ובלי in.",
      ],
      commonErrors: [
        { wrong: "The life in Tel Aviv is expensive.", right: "Life in Tel Aviv is expensive.", whyHe: "life במשמעות כללית = בלי the." },
        { wrong: "I love the music.", right: "I love music.", whyHe: "הכללה על מוזיקה בכלל = בלי the. the music = המוזיקה הספציפית הזאת." },
        { wrong: "The people are always late.", right: "People are always late.", whyHe: "people בהכללה = בלי the." },
        { wrong: "We had the dinner at seven.", right: "We had dinner at seven.", whyHe: "ארוחות בלי תווית: breakfast, lunch, dinner." },
        { wrong: "I'll see you in the next week.", right: "I'll see you next week.", whyHe: "next/last week בלי in ובלי the." },
        { wrong: "My kids go to the school by bus.", right: "My kids go to school by bus.", whyHe: "school בתפקידו (ללמוד) = בלי the. the school = הבניין הספציפי." },
      ],
    },
    items: [
      {
        id: "g-articles-zero-general-01",
        type: "gap",
        prompt: "___ life is short, so enjoy it. (a / an / the / - = no article)",
        answer: "-",
        hint: "הכללה",
        explainHe: "life בהכללה = בלי תווית. בעברית 'החיים', באנגלית Life.",
      },
      {
        id: "g-articles-zero-general-02",
        type: "gap",
        prompt: "I usually have ___ breakfast at seven. (a / an / the / -)",
        answer: "-",
        explainHe: "ארוחות בלי תווית: have breakfast.",
      },
      {
        id: "g-articles-zero-general-03",
        type: "gap",
        prompt: "My kids are still at ___ school. They finish at two. (a / an / the / -)",
        answer: "-",
        explainHe: "school בתפקידו (ללמוד) = בלי the: at school, go to school.",
      },
      {
        id: "g-articles-zero-general-04",
        type: "gap",
        prompt: "___ dogs we saw yesterday were huge. (a / an / the / -)",
        answer: "the",
        accept: ["The"],
        hint: "כלבים ספציפיים",
        explainHe: "לא הכללה על כלבים, אלא הכלבים הספציפיים שראינו אתמול, לכן the.",
      },
      {
        id: "g-articles-zero-general-05",
        type: "gap",
        prompt: "She speaks ___ Spanish and a little French. (a / an / the / -)",
        answer: "-",
        explainHe: "שפות בלי תווית: speak Spanish.",
      },
      {
        id: "g-articles-zero-general-06",
        type: "gap",
        prompt: "We went to ___ Italy last summer. (a / an / the / -)",
        answer: "-",
        explainHe: "רוב שמות המדינות בלי the: Italy, Israel, France. (יוצאי דופן: the US, the UK.)",
      },
      {
        id: "g-articles-zero-general-07",
        type: "gap",
        prompt: "He's from ___ United States. (a / an / the / -)",
        answer: "the",
        explainHe: "מדינות עם מילה כללית (States, Kingdom) או ברבים מקבלות the: the United States, the UK.",
      },
      {
        id: "g-articles-zero-general-08",
        type: "gap",
        prompt: "I don't watch ___ TV very often. (a / an / the / -)",
        answer: "-",
        explainHe: "watch TV בלי the. (אבל listen to the radio.)",
      },
      {
        id: "g-articles-zero-general-09",
        type: "mcq",
        prompt: "___ doesn't buy happiness.",
        options: [
          { text: "Money" },
          { text: "The money", errorType: "article", whyHe: "הכללה על כסף בכלל = בלי the. בעברית 'הכסף', באנגלית Money." },
          { text: "A money", errorType: "countability", whyHe: "money לא ספיר, אין a money." },
        ],
        answerIndex: 0,
        explainHe: "שם עצם לא ספיר בהכללה = בלי תווית: Money doesn't buy happiness.",
      },
      {
        id: "g-articles-zero-general-10",
        type: "mcq",
        prompt: "I go to ___ every day by bus.",
        options: [
          { text: "work" },
          { text: "the work", errorType: "article", whyHe: "בעברית 'לעבודה' עם ה', אבל באנגלית go to work בלי the." },
          { text: "a work", errorType: "countability", whyHe: "work לא ספיר. משרה ספציפית = a job." },
        ],
        answerIndex: 0,
        explainHe: "go to work / school / bed: מוסד בתפקידו, בלי תווית.",
      },
      {
        id: "g-articles-zero-general-11",
        type: "mcq",
        prompt: "Most ___ in my office speak Hebrew.",
        options: [
          { text: "the people", errorType: "article", whyHe: "אחרי most ישירות, בלי the: most people. (most of the people = עם of)." },
          { text: "people" },
          { text: "of people", errorType: "interference", whyHe: "'רוב האנשים' מתורגם most people. most of חייב the אחריו: most of the people." },
        ],
        answerIndex: 1,
        explainHe: "most people (הכללה) או most of the people (קבוצה ספציפית). לא most of people, לא most the people.",
      },
      {
        id: "g-articles-zero-general-12",
        type: "mcq",
        prompt: "OK, see you ___ !",
        options: [
          { text: "next week" },
          { text: "the next week", errorType: "article", whyHe: "next week בלי the. בעברית 'בשבוע הבא', באנגלית next week." },
          { text: "in the next week", errorType: "interference", whyHe: "בלי in ובלי the: next week." },
        ],
        answerIndex: 0,
        explainHe: "next/last/this + week/month/year: בלי מילת יחס ובלי the.",
      },
      {
        id: "g-articles-zero-general-13",
        type: "mcq",
        prompt: "Shh, the kids are in ___ already.",
        options: [
          { text: "the bed", errorType: "article", whyHe: "in bed = ישנים (המיטה בתפקידה). in the bed = פיזית על המיטה הספציפית." },
          { text: "bed" },
          { text: "a bed", errorType: "article", whyHe: "in bed = לישון, בלי תווית." },
        ],
        answerIndex: 1,
        explainHe: "in bed, go to bed: בלי תווית, כמו at home ו-at work.",
      },
      {
        id: "g-articles-zero-general-14",
        type: "fix",
        prompt: "The life in Tel Aviv is expensive.",
        answer: "Life in Tel Aviv is expensive.",
        errorType: "article",
        explainHe: "life בהכללה = בלי the. בעברית 'החיים', באנגלית Life.",
      },
      {
        id: "g-articles-zero-general-15",
        type: "fix",
        prompt: "I love the music, especially the jazz.",
        answer: "I love music, especially jazz.",
        errorType: "article",
        explainHe: "מוזיקה בכלל, ג'אז בכלל = בלי the.",
      },
      {
        id: "g-articles-zero-general-16",
        type: "fix",
        prompt: "We had the dinner at a nice restaurant.",
        answer: "We had dinner at a nice restaurant.",
        errorType: "article",
        explainHe: "ארוחות בלי the: have dinner.",
      },
      {
        id: "g-articles-zero-general-17",
        type: "fix",
        prompt: "My son goes to the school by bus.",
        answer: "My son goes to school by bus.",
        errorType: "article",
        explainHe: "go to school (ללמוד) בלי the.",
      },
      {
        id: "g-articles-zero-general-18",
        type: "fix",
        prompt: "The people are always late in this country.",
        answer: "People are always late in this country.",
        errorType: "article",
        explainHe: "people בהכללה = בלי the. 'האנשים' בעברית, People באנגלית.",
      },
      {
        id: "g-articles-zero-general-19",
        type: "transform",
        prompt: "Every dog needs exercise.",
        keyword: "dogs",
        answer: "Dogs need exercise.",
        accept: ["All dogs need exercise."],
        explainHe: "הכללה ברבים בלי the: Dogs need exercise.",
      },
      {
        id: "g-articles-zero-general-20",
        type: "transform",
        prompt: "She is a teacher of English.",
        keyword: "teaches",
        answer: "She teaches English.",
        explainHe: "שפה בלי תווית: teaches English.",
      },
      {
        id: "g-articles-zero-general-21",
        type: "order",
        words: ["children", "learn", "languages", "faster", "than", "adults"],
        answer: "Children learn languages faster than adults.",
        explainHe: "שלוש הכללות, שלושתן בלי the: children, languages, adults.",
      },
      {
        id: "g-articles-zero-general-22",
        type: "order",
        words: ["we", "usually", "have", "lunch", "at", "work", "on", "Mondays"],
        answer: "We usually have lunch at work on Mondays.",
        explainHe: "have lunch, at work: בלי תווית.",
      },
      {
        id: "g-articles-zero-general-23",
        type: "translate",
        he: "אני אוהב מוזיקה, אבל שונא לרקוד.",
        answer: "I love music, but I hate dancing.",
        accept: ["I love music but I hate dancing.", "I like music, but I hate dancing.", "I like music but I hate dancing.", "I love music, but hate dancing.", "I love music but hate dancing."],
        explainHe: "music בהכללה בלי the. hate + ing: hate dancing.",
      },
      {
        id: "g-articles-zero-general-24",
        type: "translate",
        he: "החיים קצרים.",
        answer: "Life is short.",
        explainHe: "'החיים' עם ה' בעברית, אבל Life is short בלי the (ויחיד!).",
      },
    ],
  },

  // ------------------------------------------------------------------
  // 32. Countable & uncountable nouns
  // ------------------------------------------------------------------
  {
    id: "g-countable-uncountable",
    title: "Countable & uncountable nouns",
    titleHe: "שמות עצם ספירים ובלתי ספירים",
    strand: "articles-nouns",
    order: 32,
    prereqs: [],
    lesson: {
      explanationHe: [
        "באנגלית יש קבוצה של שמות עצם שלא סופרים: אין להם צורת רבים, אין לפניהם a/an, והפועל אחריהם ביחיד. הבעיה: הרבה מהם ספירים בעברית. 'עצה/עצות' = advice, 'ידיעה/חדשות' = news, 'רהיט/רהיטים' = furniture, 'מידע' = information.",
        "הרשימה שחייבים לדעת: advice, information, news, furniture, money, homework, work, luggage, bread, hair, traffic, weather, progress, research, equipment, knowledge, evidence, music, food. עם כולם: some/a lot of/much, ולא a או -s.",
        "כשרוצים 'אחד', מוסיפים יחידת מידה: a piece of advice, a piece of information, a piece of furniture, a loaf of bread, a cup of coffee. שימו לב: news מסתיים ב-s אבל הוא יחיד: The news is good.",
        "people הוא ההפך: הוא רבים תמיד (person ביחיד): People are waiting. Two people were late. אין peoples במשמעות אנשים, ואין people is.",
        "כמה מילים הן גם וגם, עם משמעות שונה: a coffee (כוס), coffee (החומר); a hair (שערה אחת), hair (השיער); work (עבודה כללית), a job (משרה); an experience (חוויה), experience (ניסיון).",
      ],
      form: [
        { label: "לא ספיר: בלי a, בלי -s, פועל ביחיד", example: "The information is correct. Some advice." },
        { label: "יחידה: a piece of / a cup of", example: "a piece of advice, a piece of furniture, a loaf of bread" },
        { label: "news = יחיד", example: "The news is bad. (לא: are)" },
        { label: "people = רבים", example: "People are angry. Three people came." },
        { label: "work (לא ספיר) / job (ספיר)", example: "I have a lot of work. I found a new job." },
        { label: "hair / a hair", example: "She has long hair. There's a hair in my soup!" },
      ],
      examples: [
        { en: "Can you give me some advice?", he: "אתה יכול לתת לי עצה?" },
        { en: "The news is really good today.", he: "החדשות ממש טובות היום." },
        { en: "We need to buy some new furniture.", he: "אנחנו צריכים לקנות רהיטים חדשים." },
        { en: "I have a lot of homework tonight.", he: "יש לי הרבה שיעורי בית הערב." },
        { en: "People are waiting outside.", he: "אנשים מחכים בחוץ." },
        { en: "Do you have any information about the flight?", he: "יש לך מידע על הטיסה?" },
        { en: "There was too much traffic this morning.", he: "היו יותר מדי פקקים הבוקר." },
        { en: "Let me give you a piece of advice.", he: "תן לי לתת לך עצה אחת." },
      ],
      contrastHe: [
        "בעברית 'עצה' ספירה (שתי עצות). באנגלית advice לא ספיר: some advice, two pieces of advice.",
        "בעברית 'חדשות' ברבים. באנגלית news יחיד: The news is good.",
        "בעברית 'אנשים' רבים ובאנגלית גם, אבל דוברי עברית אומרים people is. תמיד people are.",
        "בעברית 'רהיטים' ברבים. באנגלית furniture בלי s: The furniture is old.",
      ],
      commonErrors: [
        { wrong: "She gave me a good advice.", right: "She gave me some good advice.", whyHe: "advice לא ספיר: בלי a. אפשר a piece of advice." },
        { wrong: "The furnitures are old.", right: "The furniture is old.", whyHe: "furniture בלי -s, ופועל ביחיד." },
        { wrong: "The news are bad.", right: "The news is bad.", whyHe: "news מסתיים ב-s אבל הוא יחיד." },
        { wrong: "People is angry.", right: "People are angry.", whyHe: "people = רבים תמיד." },
        { wrong: "I have three homeworks.", right: "I have a lot of homework.", whyHe: "homework לא ספיר: בלי s, בלי מספר." },
        { wrong: "I'm looking for a work.", right: "I'm looking for a job.", whyHe: "work לא ספיר. משרה = a job." },
      ],
    },
    items: [
      {
        id: "g-countable-uncountable-01",
        type: "gap",
        prompt: "Can you give me some ___ (advice)? I don't know what to do.",
        answer: "advice",
        explainHe: "advice לא ספיר: some advice, בלי s.",
      },
      {
        id: "g-countable-uncountable-02",
        type: "gap",
        prompt: "The news ___ (be) bad today.",
        answer: "is",
        hint: "news = יחיד",
        explainHe: "news מסתיים ב-s, אבל הוא לא ספיר ויחיד: The news is bad.",
      },
      {
        id: "g-countable-uncountable-03",
        type: "gap",
        prompt: "I have a lot of ___ (homework) tonight.",
        answer: "homework",
        explainHe: "homework לא ספיר: בלי s.",
      },
      {
        id: "g-countable-uncountable-04",
        type: "gap",
        prompt: "We need to buy some new ___ (furniture) for the living room.",
        answer: "furniture",
        explainHe: "furniture לא ספיר: בלי s. 'רהיטים' ברבים בעברית, אבל לא באנגלית.",
      },
      {
        id: "g-countable-uncountable-05",
        type: "gap",
        prompt: "How many ___ (person) came to the meeting?",
        answer: "people",
        hint: "צורת הרבים אינה סדירה",
        explainHe: "person ברבים = people. לא persons (משפטי), לא peoples.",
      },
      {
        id: "g-countable-uncountable-06",
        type: "gap",
        prompt: "There ___ (be) too much traffic this morning.",
        answer: "was",
        accept: ["is"],
        explainHe: "traffic לא ספיר, לכן פועל ביחיד: there was / there is. much מסמן שלא ספיר.",
      },
      {
        id: "g-countable-uncountable-07",
        type: "gap",
        prompt: "Do you have any ___ (information) about the flight?",
        answer: "information",
        explainHe: "information לא ספיר: בלי s. 'פרט מידע' = a piece of information.",
      },
      {
        id: "g-countable-uncountable-08",
        type: "gap",
        prompt: "She has long black ___ (hair).",
        answer: "hair",
        explainHe: "שיער כמכלול = hair, לא ספיר. hairs = שערות בודדות (למשל על החולצה).",
      },
      {
        id: "g-countable-uncountable-09",
        type: "mcq",
        prompt: "The news ___ really good.",
        options: [
          { text: "are", errorType: "agreement", whyHe: "'חדשות' ברבים בעברית, אבל news באנגלית יחיד." },
          { text: "is" },
          { text: "were", errorType: "agreement", whyHe: "news יחיד: was / is, לא were." },
        ],
        answerIndex: 1,
        explainHe: "news = יחיד תמיד: The news is good.",
      },
      {
        id: "g-countable-uncountable-10",
        type: "mcq",
        prompt: "He gave me ___ .",
        options: [
          { text: "a good advice", errorType: "countability", whyHe: "advice לא ספיר, בלי a." },
          { text: "some good advices", errorType: "countability", whyHe: "advice בלי s גם ברבים." },
          { text: "some good advice" },
        ],
        answerIndex: 2,
        explainHe: "advice: some advice / a piece of advice. בלי a ובלי s.",
      },
      {
        id: "g-countable-uncountable-11",
        type: "mcq",
        prompt: "We didn't have much ___ , just two small bags.",
        options: [
          { text: "luggage" },
          { text: "luggages", errorType: "countability", whyHe: "luggage לא ספיר, בלי s. 'מזוודות' = bags / suitcases." },
          { text: "a luggage", errorType: "countability", whyHe: "luggage בלי a. פריט אחד = a bag / a suitcase." },
        ],
        answerIndex: 0,
        explainHe: "luggage/baggage לא ספירים. much luggage, a piece of luggage.",
      },
      {
        id: "g-countable-uncountable-12",
        type: "mcq",
        prompt: "___ waiting outside for you.",
        options: [
          { text: "Some people are" },
          { text: "Some people is", errorType: "agreement", whyHe: "people = רבים: people are." },
          { text: "Some peoples are", errorType: "countability", whyHe: "people כבר רבים. peoples = עמים." },
        ],
        answerIndex: 0,
        explainHe: "people רבים תמיד: people are, people were.",
      },
      {
        id: "g-countable-uncountable-13",
        type: "mcq",
        prompt: "Can you get ___ on your way home?",
        options: [
          { text: "a bread", errorType: "countability", whyHe: "bread לא ספיר. כיכר = a loaf of bread." },
          { text: "some bread" },
          { text: "some breads", errorType: "countability", whyHe: "bread בלי s." },
        ],
        answerIndex: 1,
        explainHe: "bread לא ספיר: some bread, a loaf of bread, a slice of bread.",
      },
      {
        id: "g-countable-uncountable-14",
        type: "fix",
        prompt: "She gave me a lot of good advices.",
        answer: "She gave me a lot of good advice.",
        errorType: "countability",
        explainHe: "advice לא ספיר, בלי s. 'עצות' = advice.",
      },
      {
        id: "g-countable-uncountable-15",
        type: "fix",
        prompt: "The furnitures in this room are old.",
        answer: "The furniture in this room is old.",
        errorType: "countability",
        explainHe: "furniture בלי s, ופועל ביחיד: is.",
      },
      {
        id: "g-countable-uncountable-16",
        type: "fix",
        prompt: "I have a lot of homeworks tonight.",
        answer: "I have a lot of homework tonight.",
        errorType: "countability",
        explainHe: "homework לא ספיר. 'שיעורי בית' ברבים בעברית, homework בלי s.",
      },
      {
        id: "g-countable-uncountable-17",
        type: "fix",
        prompt: "The people is angry about the prices.",
        answer: "The people are angry about the prices.",
        accept: ["People are angry about the prices."],
        errorType: "agreement",
        explainHe: "people = רבים: are, לא is.",
      },
      {
        id: "g-countable-uncountable-18",
        type: "fix",
        prompt: "Can I have an information about the trip?",
        answer: "Can I have some information about the trip?",
        accept: ["Can I have information about the trip?", "Can I have a piece of information about the trip?"],
        errorType: "countability",
        explainHe: "information לא ספיר: בלי an. some information או a piece of information.",
      },
      {
        id: "g-countable-uncountable-19",
        type: "transform",
        prompt: "Let me give you some advice.",
        keyword: "piece",
        answer: "Let me give you a piece of advice.",
        explainHe: "עצה אחת = a piece of advice.",
      },
      {
        id: "g-countable-uncountable-20",
        type: "transform",
        prompt: "There were too many cars on the road this morning.",
        keyword: "traffic",
        answer: "There was too much traffic this morning.",
        accept: ["There was too much traffic on the road this morning.", "There was a lot of traffic this morning.", "There was a lot of traffic on the road this morning."],
        explainHe: "traffic לא ספיר: there was, much traffic.",
      },
      {
        id: "g-countable-uncountable-21",
        type: "order",
        words: ["the", "information", "on", "the", "website", "is", "wrong"],
        answer: "The information on the website is wrong.",
        explainHe: "information לא ספיר, לכן is.",
      },
      {
        id: "g-countable-uncountable-22",
        type: "order",
        words: ["how", "much", "money", "do", "we", "need"],
        answer: "How much money do we need?",
        explainHe: "money לא ספיר, לכן how much (לא how many).",
      },
      {
        id: "g-countable-uncountable-23",
        type: "translate",
        he: "החדשות היו טובות.",
        answer: "The news was good.",
        explainHe: "news יחיד: was, לא were.",
      },
      {
        id: "g-countable-uncountable-24",
        type: "translate",
        he: "אנשים אוהבים לדבר על מזג האוויר.",
        answer: "People like to talk about the weather.",
        accept: ["People love to talk about the weather.", "People like talking about the weather.", "People love talking about the weather."],
        explainHe: "People בלי the, ופועל ברבים: like. the weather: תמיד עם the.",
      },
    ],
  },

  // ------------------------------------------------------------------
  // 33. Quantifiers
  // ------------------------------------------------------------------
  {
    id: "g-quantifiers",
    title: "Quantifiers: much / many / a lot of / few / little / some / any",
    titleHe: "כמתים: much, many, few, little",
    strand: "articles-nouns",
    order: 33,
    prereqs: ["g-countable-uncountable"],
    lesson: {
      explanationHe: [
        "בעברית 'הרבה' ו'כמה' עובדות עם הכל. באנגלית צריך לבחור לפי ספירות: many/few/a few עם ספיר ברבים (many people, a few days), much/little/a little עם לא ספיר (much time, a little money).",
        "a lot of / lots of עובד עם שניהם ונשמע טבעי במשפט חיובי: I have a lot of work. much ו-many מרגישים טבעיים בעיקר בשאלות ובשלילה: How much time? I don't have many friends here. 'I have much work' נשמע מוזר בדיבור.",
        "a few / a little = 'כמה, קצת' (חיובי, יש): I have a few friends here. We have a little time. בלי a — few / little = 'כמעט ואין' (שלילי): Few people know this. There's little hope. בדיבור אומרים בדרך כלל very few / very little או not many / not much.",
        "some במשפט חיובי ובהצעות/בקשות (Would you like some tea? Can I have some water?). any בשאלות ובשלילה: Do you have any questions? I don't have any money. הבעיה בעברית: 'אין לי קצת כסף' לא קיים, אבל I don't have some money נשמע לדוברי עברית סביר. תמיד any אחרי שלילה.",
        "שאלות: How many + ספיר (How many people?), How much + לא ספיר (How much money? How much time?).",
      ],
      form: [
        { label: "ספיר ברבים", example: "many / a few / few / (not) many + people, cars, days" },
        { label: "לא ספיר", example: "much / a little / little / (not) much + time, money, work" },
        { label: "שניהם", example: "a lot of / lots of / some / any / no + הכל" },
        { label: "a few / a little = יש קצת", example: "I have a few ideas. We have a little time." },
        { label: "few / little = כמעט אין", example: "Few people came. There's very little time." },
        { label: "some (חיובי, הצעה) / any (שאלה, שלילה)", example: "I need some help. Do you need any help? I don't need any help." },
        { label: "How many / How much", example: "How many people? How much money?" },
      ],
      examples: [
        { en: "How much sugar do you take?", he: "כמה סוכר אתה שם?" },
        { en: "There aren't many good restaurants here.", he: "אין פה הרבה מסעדות טובות." },
        { en: "I have a lot of work this week.", he: "יש לי הרבה עבודה השבוע." },
        { en: "We have a little time, so let's grab a coffee.", he: "יש לנו קצת זמן, אז בוא ניקח קפה." },
        { en: "Hurry up, we have very little time!", he: "מהר, יש לנו מעט מאוד זמן!" },
        { en: "Only a few people came to the meeting.", he: "רק כמה אנשים הגיעו לפגישה." },
        { en: "Do you have any questions?", he: "יש לכם שאלות?" },
        { en: "Sorry, we don't have any tables tonight.", he: "מצטער, אין לנו שולחנות הערב." },
      ],
      contrastHe: [
        "בעברית 'הרבה אנשים' ו'הרבה כסף' אותה מילה. באנגלית many people אבל much money, או a lot of לשניהם.",
        "בעברית 'כמה' לשניהם. באנגלית How many people? אבל How much time?",
        "בעברית 'קצת' לשניהם. באנגלית a few friends (ספיר) אבל a little money (לא ספיר).",
        "בעברית 'אין לי חברים' בלי כמת. באנגלית I don't have any friends, ולא some.",
      ],
      commonErrors: [
        { wrong: "There were much people.", right: "There were a lot of people.", whyHe: "people ספיר ברבים: many / a lot of, לא much." },
        { wrong: "How many time do you need?", right: "How much time do you need?", whyHe: "time לא ספיר: how much." },
        { wrong: "I have few money.", right: "I have a little money.", whyHe: "money לא ספיר: little / a little, לא few." },
        { wrong: "We have a little minutes.", right: "We have a few minutes.", whyHe: "minutes ספיר: a few." },
        { wrong: "I don't have some money.", right: "I don't have any money.", whyHe: "אחרי שלילה: any, לא some." },
        { wrong: "I have much work today.", right: "I have a lot of work today.", whyHe: "much במשפט חיובי נשמע רשמי ומוזר בדיבור. a lot of." },
      ],
    },
    items: [
      {
        id: "g-quantifiers-01",
        type: "gap",
        prompt: "How ___ sugar do you take in your coffee? (much / many)",
        answer: "much",
        explainHe: "sugar לא ספיר: how much.",
      },
      {
        id: "g-quantifiers-02",
        type: "gap",
        prompt: "There aren't ___ good restaurants in this area. (much / many)",
        answer: "many",
        explainHe: "restaurants ספיר ברבים: many.",
      },
      {
        id: "g-quantifiers-03",
        type: "gap",
        prompt: "I have very ___ money left, so I can't come. (few / little)",
        answer: "little",
        explainHe: "money לא ספיר: little. very little = כמעט אין.",
      },
      {
        id: "g-quantifiers-04",
        type: "gap",
        prompt: "Would you like ___ tea? (some / any)",
        answer: "some",
        hint: "הצעה",
        explainHe: "בהצעות ובקשות משתמשים ב-some גם בשאלה: Would you like some tea?",
      },
      {
        id: "g-quantifiers-05",
        type: "gap",
        prompt: "Do you have ___ questions before we start? (some / any)",
        answer: "any",
        explainHe: "שאלה רגילה (לא הצעה): any.",
      },
      {
        id: "g-quantifiers-06",
        type: "gap",
        prompt: "There were only ___ people at the party, maybe ten. (a few / few / a little)",
        answer: "a few",
        explainHe: "people ספיר: a few. only a few = רק כמה.",
      },
      {
        id: "g-quantifiers-07",
        type: "gap",
        prompt: "We have ___ time, let's hurry! (few / little)",
        answer: "little",
        explainHe: "time לא ספיר: little. little time = כמעט אין זמן.",
      },
      {
        id: "g-quantifiers-08",
        type: "gap",
        prompt: "She has ___ of friends in Haifa. (much / a lot / many)",
        answer: "a lot",
        explainHe: "a lot of עובד עם הכל במשפט חיובי. much of / many of לא מתאים כאן.",
      },
      {
        id: "g-quantifiers-09",
        type: "mcq",
        prompt: "There were ___ people at the concert.",
        options: [
          { text: "much", errorType: "countability", whyHe: "people ספיר ברבים: many / a lot of, לא much." },
          { text: "a lot of" },
          { text: "much of", errorType: "countability", whyHe: "much לא הולך עם ספיר, ו-much of צריך the אחריו." },
        ],
        answerIndex: 1,
        explainHe: "משפט חיובי + ספיר ברבים: a lot of people (או many people).",
      },
      {
        id: "g-quantifiers-10",
        type: "mcq",
        prompt: "I don't have ___ money on me right now.",
        options: [
          { text: "much" },
          { text: "many", errorType: "countability", whyHe: "money לא ספיר: much." },
          { text: "some", errorType: "word-choice", whyHe: "אחרי שלילה: any או much, לא some." },
        ],
        answerIndex: 0,
        explainHe: "שלילה + לא ספיר: not much money / not any money.",
      },
      {
        id: "g-quantifiers-11",
        type: "mcq",
        prompt: "Hurry up! We have ___ time.",
        options: [
          { text: "very few", errorType: "countability", whyHe: "time לא ספיר: little, לא few." },
          { text: "a little", errorType: "word-choice", whyHe: "a little = יש קצת (חיובי). 'מהר!' מתאים ל-very little = כמעט אין." },
          { text: "very little" },
        ],
        answerIndex: 2,
        explainHe: "little (בלי a) = כמעט אין. time לא ספיר, לכן little ולא few.",
      },
      {
        id: "g-quantifiers-12",
        type: "mcq",
        prompt: "Can I ask you ___ questions?",
        options: [
          { text: "a few" },
          { text: "a little", errorType: "countability", whyHe: "questions ספיר: a few." },
          { text: "few", errorType: "word-choice", whyHe: "few בלי a = כמעט אין. בבקשה צריך a few = כמה." },
        ],
        answerIndex: 0,
        explainHe: "a few + ספיר ברבים = כמה: a few questions.",
      },
      {
        id: "g-quantifiers-13",
        type: "mcq",
        prompt: "Sorry, we don't have ___ tables tonight.",
        options: [
          { text: "some", errorType: "word-choice", whyHe: "אחרי שלילה: any." },
          { text: "any" },
          { text: "no", errorType: "other", whyHe: "שלילה כפולה. או don't have any, או have no." },
        ],
        answerIndex: 1,
        explainHe: "don't have any = have no. לא don't have some, לא don't have no.",
      },
      {
        id: "g-quantifiers-14",
        type: "fix",
        prompt: "There were much people at the beach.",
        answer: "There were a lot of people at the beach.",
        accept: ["There were many people at the beach.", "There were lots of people at the beach."],
        errorType: "countability",
        explainHe: "people ספיר: a lot of / many, לא much.",
      },
      {
        id: "g-quantifiers-15",
        type: "fix",
        prompt: "I have few money left, maybe ten shekels.",
        answer: "I have a little money left, maybe ten shekels.",
        accept: ["I have little money left, maybe ten shekels.", "I have very little money left, maybe ten shekels."],
        errorType: "countability",
        explainHe: "money לא ספיר: little / a little, לא few.",
      },
      {
        id: "g-quantifiers-16",
        type: "fix",
        prompt: "She doesn't have some friends here.",
        answer: "She doesn't have any friends here.",
        errorType: "word-choice",
        explainHe: "אחרי שלילה: any. doesn't have any = has no.",
      },
      {
        id: "g-quantifiers-17",
        type: "fix",
        prompt: "How many time do you need?",
        answer: "How much time do you need?",
        errorType: "countability",
        explainHe: "time לא ספיר: how much time. (how many times = כמה פעמים.)",
      },
      {
        id: "g-quantifiers-18",
        type: "fix",
        prompt: "We only had a little minutes to decide.",
        answer: "We only had a few minutes to decide.",
        errorType: "countability",
        explainHe: "minutes ספיר: a few minutes.",
      },
      {
        id: "g-quantifiers-19",
        type: "transform",
        prompt: "There isn't much traffic today.",
        keyword: "little",
        answer: "There is little traffic today.",
        accept: ["There is very little traffic today.", "There's very little traffic today."],
        explainHe: "not much = little / very little (לא ספיר).",
      },
      {
        id: "g-quantifiers-20",
        type: "transform",
        prompt: "Not many people came to the party.",
        keyword: "few",
        answer: "Few people came to the party.",
        accept: ["Very few people came to the party.", "Only a few people came to the party."],
        explainHe: "not many = few / very few (ספיר).",
      },
      {
        id: "g-quantifiers-21",
        type: "order",
        words: ["how", "many", "people", "are", "coming", "to", "the", "party"],
        answer: "How many people are coming to the party?",
        explainHe: "people ספיר: how many.",
      },
      {
        id: "g-quantifiers-22",
        type: "order",
        words: ["there", "isn't", "much", "time", "left"],
        answer: "There isn't much time left.",
        explainHe: "שלילה + לא ספיר: isn't much time.",
      },
      {
        id: "g-quantifiers-23",
        type: "translate",
        he: "יש לי מעט מאוד זמן היום.",
        answer: "I have very little time today.",
        accept: ["I've got very little time today."],
        explainHe: "time לא ספיר: very little, לא very few.",
      },
      {
        id: "g-quantifiers-24",
        type: "translate",
        he: "כמה אנשים היו שם?",
        answer: "How many people were there?",
        explainHe: "people ספיר: how many. 'כמה' בעברית לא אומר לנו, הספירות כן.",
      },
    ],
  },

  // ------------------------------------------------------------------
  // 34. there is / it is / have got
  // ------------------------------------------------------------------
  {
    id: "g-there-is-it-is",
    title: "there is / it is / have got",
    titleHe: "there is מול it is",
    strand: "articles-nouns",
    order: 34,
    prereqs: [],
    lesson: {
      explanationHe: [
        "'יש' בעברית עושה שתי עבודות, ובאנגלית יש להן שתי מבנים שונים. 'יש בעיה' (משהו קיים) = There is a problem. 'יש לי בעיה' (שייכות) = I have a problem / I've got a problem. דוברי עברית מתרגמים 'יש' ל-it has או משמיטים את הנושא (Is a problem, Have a lot of traffic). שניהם שגויים.",
        "there is/are = קיום: מציגים משהו חדש. There is a cat on the roof. There are two new students. הפועל מתאים לשם העצם שאחריו: there is + יחיד או לא ספיר, there are + רבים. בעבר: there was / there were. בעתיד: there will be.",
        "it is = תיאור או זיהוי של משהו שכבר ידוע, וגם זמן, מזג אוויר, מרחק ודעות: It's cold. It's nine o'clock. It's far from here. It's a good idea. אם אפשר להחליף it ב'זה' — זה it is. אם המשמעות היא 'יש/קיים' — there is.",
        "שאלות ושלילה: Is there a bank near here? Are there any tickets? There isn't any milk = There's no milk. There aren't any tickets. שימו לב: לא Has a bank? ולא Is a bank?",
        "have got = have, נפוץ בבריטית ובדיבור: I've got two tickets. Have you got a minute? באנגלית אמריקאית אומרים בעיקר I have / Do you have. שניהם נכונים. אבל אין there has ואין it has במשמעות 'יש'.",
      ],
      form: [
        { label: "קיום, יחיד / לא ספיר", example: "There is (There's) a problem. There is some milk." },
        { label: "קיום, רבים", example: "There are two problems. There are many people." },
        { label: "עבר / עתיד", example: "There was a party. There were many guests. There will be a test." },
        { label: "שאלה", example: "Is there a bank near here? Are there any tickets?" },
        { label: "שלילה", example: "There isn't any milk. = There's no milk." },
        { label: "it is: זמן, מזג אוויר, מרחק, דעה", example: "It's 9:00. It's cold. It's far. It's a good idea." },
        { label: "שייכות", example: "I have a car. = I've got a car. Do you have a pen?" },
      ],
      examples: [
        { en: "There's a problem with my computer.", he: "יש בעיה עם המחשב שלי." },
        { en: "There are a lot of people in the street.", he: "יש הרבה אנשים ברחוב." },
        { en: "Is there a meeting today?", he: "יש פגישה היום?" },
        { en: "There was a lot of traffic, so I was late.", he: "היו פקקים, אז איחרתי." },
        { en: "It's cold today, take a jacket.", he: "קר היום, קח ז'קט." },
        { en: "It's a good idea to call first.", he: "זה רעיון טוב להתקשר קודם." },
        { en: "There's nothing we can do.", he: "אין שום דבר שאנחנו יכולים לעשות." },
        { en: "I've got two tickets for the show.", he: "יש לי שני כרטיסים להופעה." },
      ],
      contrastHe: [
        "בעברית 'יש בעיה' בלי נושא. באנגלית חייבים נושא: There is a problem, לא Is a problem.",
        "בעברית 'יש הרבה אנשים ברחוב'. דוברי עברית אומרים It has many people — שגוי. יש = there are.",
        "בעברית 'יש לי' = 'יש' + 'לי'. באנגלית זה פועל אחר: I have / I've got, לא There is to me.",
        "בעברית 'קר' בלי נושא. באנגלית It's cold, ולא Is cold.",
      ],
      commonErrors: [
        { wrong: "Is a problem with the car.", right: "There's a problem with the car.", whyHe: "אין משפט בלי נושא. 'יש' = there is." },
        { wrong: "It has many restaurants in this street.", right: "There are many restaurants on this street.", whyHe: "it has = יש לו. קיום = there are." },
        { wrong: "There is three reasons.", right: "There are three reasons.", whyHe: "reasons רבים: there are." },
        { wrong: "There has a mistake here.", right: "There is a mistake here.", whyHe: "there הולך עם be, לא עם have." },
        { wrong: "Has a bank near here?", right: "Is there a bank near here?", whyHe: "שאלת קיום: Is there...?" },
        { wrong: "There is nine o'clock.", right: "It's nine o'clock.", whyHe: "זמן, מזג אוויר, מרחק: it is." },
      ],
    },
    items: [
      {
        id: "g-there-is-it-is-01",
        type: "gap",
        prompt: "___ a problem with my computer. (There is / It is)",
        answer: "There is",
        accept: ["There's"],
        explainHe: "'יש בעיה' = קיום: There is a problem.",
      },
      {
        id: "g-there-is-it-is-02",
        type: "gap",
        prompt: "___ cold today, take a jacket. (There is / It is)",
        answer: "It is",
        accept: ["It's"],
        explainHe: "מזג אוויר: It's cold. לא There is cold.",
      },
      {
        id: "g-there-is-it-is-03",
        type: "gap",
        prompt: "___ any milk in the fridge? (Is there / Is it)",
        answer: "Is there",
        explainHe: "שאלת קיום: Is there any milk?",
      },
      {
        id: "g-there-is-it-is-04",
        type: "gap",
        prompt: "___ two new students in my class. (There is / There are)",
        answer: "There are",
        explainHe: "students רבים: there are.",
      },
      {
        id: "g-there-is-it-is-05",
        type: "gap",
        prompt: "___ far from here to the station? (Is it / Is there)",
        answer: "Is it",
        explainHe: "מרחק: it. Is it far? לא Is there far.",
      },
      {
        id: "g-there-is-it-is-06",
        type: "gap",
        prompt: "___ a lot of traffic this morning, so I was late. (There was / It was)",
        answer: "There was",
        explainHe: "'היו פקקים' = קיום בעבר: There was a lot of traffic. traffic לא ספיר, לכן was.",
      },
      {
        id: "g-there-is-it-is-07",
        type: "gap",
        prompt: "___ a good idea to call before you come. (There is / It is)",
        answer: "It is",
        accept: ["It's"],
        explainHe: "דעה: It's a good idea to... (זה רעיון טוב).",
      },
      {
        id: "g-there-is-it-is-08",
        type: "gap",
        prompt: "___ nothing we can do about it. (There is / It is)",
        answer: "There is",
        accept: ["There's"],
        explainHe: "'אין שום דבר' = קיום: There is nothing.",
      },
      {
        id: "g-there-is-it-is-09",
        type: "mcq",
        prompt: "___ a lot of people in the street today.",
        options: [
          { text: "It has", errorType: "interference", whyHe: "'יש' לא מתורגם ל-it has. קיום = there is/are." },
          { text: "There is", errorType: "agreement", whyHe: "people רבים: there are." },
          { text: "There are" },
        ],
        answerIndex: 2,
        explainHe: "קיום + רבים: There are a lot of people.",
      },
      {
        id: "g-there-is-it-is-10",
        type: "mcq",
        prompt: "___ nine o'clock, let's go.",
        options: [
          { text: "There is", errorType: "word-choice", whyHe: "זמן = it: It's nine o'clock." },
          { text: "It's" },
          { text: "Is", errorType: "interference", whyHe: "משפט בלי נושא. באנגלית תמיד יש נושא: It's." },
        ],
        answerIndex: 1,
        explainHe: "שעה, מזג אוויר, מרחק: It's.",
      },
      {
        id: "g-there-is-it-is-11",
        type: "mcq",
        prompt: "___ a meeting today?",
        options: [
          { text: "Is there" },
          { text: "Has", errorType: "interference", whyHe: "'יש פגישה?' = שאלת קיום: Is there a meeting?" },
          { text: "Is it", errorType: "word-choice", whyHe: "it is מתאר משהו ידוע. שאלה אם משהו קיים = Is there." },
          { text: "There is", errorType: "question-form", whyHe: "בשאלה הופכים: Is there...?" },
        ],
        answerIndex: 0,
        explainHe: "שאלת קיום: Is there + שם עצם?",
      },
      {
        id: "g-there-is-it-is-12",
        type: "mcq",
        prompt: "Don't worry, ___ no reason to panic.",
        options: [
          { text: "there's" },
          { text: "it's", errorType: "word-choice", whyHe: "'אין סיבה' = קיום (שלילי): there's no reason." },
          { text: "has", errorType: "interference", whyHe: "'אין' לא מתורגם ל-has no. קיום = there is." },
        ],
        answerIndex: 0,
        explainHe: "there's no + שם עצם = אין. There's no reason to panic.",
      },
      {
        id: "g-there-is-it-is-13",
        type: "mcq",
        prompt: "Sorry, ___ any tickets left.",
        options: [
          { text: "there isn't", errorType: "agreement", whyHe: "tickets רבים: there aren't." },
          { text: "it isn't", errorType: "word-choice", whyHe: "'אין כרטיסים' = קיום: there aren't." },
          { text: "there aren't" },
        ],
        answerIndex: 2,
        explainHe: "שלילה + רבים: there aren't any tickets = there are no tickets.",
      },
      {
        id: "g-there-is-it-is-14",
        type: "fix",
        prompt: "Is a problem with the printer.",
        answer: "There is a problem with the printer.",
        accept: ["There's a problem with the printer."],
        errorType: "interference",
        explainHe: "משפט בלי נושא. 'יש בעיה' = There is a problem.",
      },
      {
        id: "g-there-is-it-is-15",
        type: "fix",
        prompt: "It has many restaurants in this street.",
        answer: "There are many restaurants in this street.",
        accept: ["There are many restaurants on this street.", "There are a lot of restaurants in this street.", "There are a lot of restaurants on this street."],
        errorType: "interference",
        explainHe: "it has = יש לו (שייכות). 'יש הרבה מסעדות' = קיום: There are.",
      },
      {
        id: "g-there-is-it-is-16",
        type: "fix",
        prompt: "There is three reasons for this.",
        answer: "There are three reasons for this.",
        errorType: "agreement",
        explainHe: "reasons רבים: there are.",
      },
      {
        id: "g-there-is-it-is-17",
        type: "fix",
        prompt: "There has a mistake in the report.",
        answer: "There is a mistake in the report.",
        accept: ["There's a mistake in the report."],
        errorType: "interference",
        explainHe: "there הולך רק עם be: there is / there are. לא there has.",
      },
      {
        id: "g-there-is-it-is-18",
        type: "fix",
        prompt: "Has a bank near here?",
        answer: "Is there a bank near here?",
        errorType: "question-form",
        explainHe: "שאלת קיום: Is there a bank...? 'יש בנק?' לא Has a bank.",
      },
      {
        id: "g-there-is-it-is-19",
        type: "transform",
        prompt: "We have a big garden behind the house.",
        keyword: "there",
        answer: "There is a big garden behind the house.",
        accept: ["There's a big garden behind the house.", "There is a big garden behind our house.", "There's a big garden behind our house."],
        explainHe: "משייכות (we have) לקיום (there is).",
      },
      {
        id: "g-there-is-it-is-20",
        type: "transform",
        prompt: "My street has two supermarkets.",
        keyword: "there",
        answer: "There are two supermarkets on my street.",
        accept: ["There are two supermarkets in my street."],
        explainHe: "supermarkets רבים: there are. אנגלית אמריקאית: on my street.",
      },
      {
        id: "g-there-is-it-is-21",
        type: "order",
        words: ["there", "are", "too", "many", "cars", "in", "the", "city"],
        answer: "There are too many cars in the city.",
        explainHe: "קיום + רבים: There are too many cars.",
      },
      {
        id: "g-there-is-it-is-22",
        type: "order",
        words: ["is", "there", "anything", "I", "can", "do", "to", "help"],
        answer: "Is there anything I can do to help?",
        explainHe: "שאלת קיום: Is there anything...?",
      },
      {
        id: "g-there-is-it-is-23",
        type: "translate",
        he: "יש בעיה עם ההזמנה שלי.",
        answer: "There is a problem with my order.",
        accept: ["There's a problem with my order."],
        explainHe: "'יש' = there is. לא It has, לא Is a problem.",
      },
      {
        id: "g-there-is-it-is-24",
        type: "translate",
        he: "אין הרבה זמן.",
        answer: "There isn't much time.",
        accept: ["There is not much time.", "There's not much time.", "There isn't a lot of time.", "There is not a lot of time."],
        explainHe: "'אין' = there isn't / there's no. time לא ספיר: much.",
      },
    ],
  },
];
