import type { GrammarTopic } from "@/lib/types";

// Strands: passive-reported (orders 22-25) and questions (orders 26-29).
export const PASSIVE_REPORTED_QUESTIONS: GrammarTopic[] = [
  // ------------------------------------------------------------------
  // 22. Passive: present & past simple
  // ------------------------------------------------------------------
  {
    id: "g-passive-present-past",
    title: "Passive: present & past simple",
    titleHe: "סביל: הווה ועבר",
    strand: "passive-reported",
    order: 22,
    prereqs: ["g-present-perfect"],
    lesson: {
      explanationHe: [
        "משתמשים בסביל (passive) כשמי שעשה את הפעולה לא חשוב, לא ידוע או ברור מאליו, וכשרוצים להתחיל את המשפט מהדבר שקרה לו משהו: My car was stolen (האוטו שלי נגנב) – לא חשוב מי גנב.",
        "הסביל נפוץ מאוד באנגלית מדוברת, הרבה יותר מבעברית: I was born in Haifa, it's made in China, the meeting was canceled. בעברית לרוב נגיד 'ביטלו את הפגישה' – באנגלית טבעי יותר לומר 'הפגישה בוטלה'.",
        "הצורה: be + פועל בצורה השלישית (V3). בהווה: am / is / are + V3. בעבר: was / were + V3. הפועל be הוא שמשתנה לפי הזמן ולפי הנושא; ה-V3 לא משתנה לעולם.",
        "שלילה ושאלה נעשות דרך be, בלי do: The room isn't cleaned every day. Was the letter sent? Where were you born?",
        "אם בכל זאת רוצים לומר מי עשה את הפעולה, מוסיפים by בסוף: The photo was taken by my sister. אבל ברוב המשפטים הסבילים אין by בכלל.",
      ],
      form: [
        { label: "הווה פשוט: am/is/are + V3", example: "English is spoken here." },
        { label: "עבר פשוט: was/were + V3", example: "The house was built in 1990." },
        { label: "שלילה: be + not + V3", example: "The windows weren't cleaned." },
        { label: "שאלה: Be + נושא + V3?", example: "Was the letter sent?" },
        { label: "שאלת Wh-", example: "Where were you born?" },
        { label: "מי עשה: by + מבצע הפעולה", example: "The photo was taken by Dana." },
      ],
      examples: [
        { en: "My phone was stolen on the bus.", he: "הטלפון שלי נגנב באוטובוס." },
        { en: "I was born in Haifa in 1995.", he: "נולדתי בחיפה ב-1995." },
        { en: "These shoes are made in Italy.", he: "הנעליים האלה מיוצרות באיטליה." },
        { en: "The meeting was canceled at the last minute.", he: "הפגישה בוטלה ברגע האחרון." },
        { en: "The office is cleaned every evening.", he: "המשרד מנוקה כל ערב." },
        { en: "Two men were arrested last night.", he: "שני גברים נעצרו אתמול בלילה." },
        { en: "Is breakfast included in the price?", he: "ארוחת הבוקר כלולה במחיר?" },
        { en: "The windows weren't cleaned last week.", he: "החלונות לא נוקו בשבוע שעבר." },
      ],
      contrastHe: [
        "בעברית מדוברת מעדיפים משפט סתמי: 'גנבו לי את האוטו', 'בנו את הבניין ב-1990'. באנגלית הצורה הטבעית היא סביל: My car was stolen, the building was built in 1990.",
        "'נולדתי' הוא בעברית פועל רגיל, אבל באנגלית זה תמיד סביל: I was born, לא I born ולא I was birth.",
        "בעברית אין פועל עזר בסביל ('המכתב נשלח'), ולכן דוברי עברית נוטים להשמיט את be: The letter sent. באנגלית חייבים be + V3: The letter was sent.",
        "שימו לב לפעלים לא רגילים: הצורה השלישית (V3) היא לא צורת העבר: stole → stolen, wrote → written, took → taken, built → built.",
      ],
      commonErrors: [
        { wrong: "The house builded in 1990.", right: "The house was built in 1990.", whyHe: "סביל = be + V3. חסר was, ו-build הוא פועל לא רגיל: built." },
        { wrong: "I born in Tel Aviv.", right: "I was born in Tel Aviv.", whyHe: "born תמיד מגיע עם be: I was born, she was born." },
        { wrong: "The letters are send every Monday.", right: "The letters are sent every Monday.", whyHe: "אחרי be בסביל בא V3 (sent), לא הצורה הבסיסית." },
        { wrong: "Hebrew speaks in Israel.", right: "Hebrew is spoken in Israel.", whyHe: "עברית לא 'מדברת' – היא 'מדוברת'. הנושא לא עושה את הפעולה, ולכן צריך סביל." },
        { wrong: "The rooms was cleaned this morning.", right: "The rooms were cleaned this morning.", whyHe: "be מתאים לנושא: rooms ברבים → were." },
        { wrong: "The cake was made from my grandmother.", right: "The cake was made by my grandmother.", whyHe: "מי שעשה את הפעולה מסומן ב-by, לא ב-from." },
      ],
    },
    items: [
      { id: "g-passive-present-past-01", type: "gap", prompt: "This bread ___ (make) fresh every morning.", answer: "is made", hint: "הווה פשוט, סביל", explainHe: "הלחם לא עושה את הפעולה – מישהו מכין אותו. סביל בהווה: is + made." },
      { id: "g-passive-present-past-02", type: "gap", prompt: "The Eiffel Tower ___ (build) in 1889.", answer: "was built", hint: "עבר, סביל", explainHe: "סביל בעבר: was + V3. build → built (לא builded)." },
      { id: "g-passive-present-past-03", type: "gap", prompt: "My phone ___ (steal) on the bus yesterday.", answer: "was stolen", explainHe: "'גנבו לי את הטלפון' = My phone was stolen. steal → stole → stolen." },
      { id: "g-passive-present-past-04", type: "gap", prompt: "These cars ___ (produce) in Japan.", answer: "are produced", explainHe: "נושא ברבים בהווה: are + produced." },
      { id: "g-passive-present-past-05", type: "gap", prompt: "The windows ___ (not clean) last week.", answer: "weren't cleaned", explainHe: "שלילה בסביל נעשית דרך be: were + not + cleaned. לא didn't cleaned." },
      { id: "g-passive-present-past-06", type: "gap", prompt: "I ___ (bear) in Haifa in 1995.", answer: "was born", hint: "bear → born", explainHe: "'נולדתי' באנגלית הוא תמיד סביל: I was born." },
      { id: "g-passive-present-past-07", type: "gap", prompt: "Is English ___ (speak) in your office?", answer: "spoken", explainHe: "בשאלה be עובר לפני הנושא, וה-V3 נשאר: Is English spoken...?" },
      {
        id: "g-passive-present-past-08",
        type: "mcq",
        prompt: "Where ___ you born?",
        options: [
          { text: "were" },
          { text: "did", errorType: "passive", whyHe: "born הוא סביל וצריך be, לא do/did." },
          { text: "are", errorType: "tense", whyHe: "הלידה קרתה בעבר: were, לא are." },
          { text: "was", errorType: "agreement", whyHe: "עם you תמיד were, לא was." },
        ],
        answerIndex: 0,
        explainHe: "Where were you born? – סביל בעבר עם you → were.",
      },
      {
        id: "g-passive-present-past-09",
        type: "mcq",
        prompt: "The report ___ yesterday.",
        options: [
          { text: "was sent" },
          { text: "sent", errorType: "passive", whyHe: "הדוח לא שולח – הוא נשלח. חסר was." },
          { text: "was send", errorType: "verb-form", whyHe: "אחרי be צריך V3: sent." },
          { text: "is sent", errorType: "tense", whyHe: "yesterday → עבר: was sent." },
        ],
        answerIndex: 0,
        explainHe: "סביל בעבר: was + sent. המילה yesterday מחייבת עבר.",
      },
      {
        id: "g-passive-present-past-10",
        type: "mcq",
        prompt: "Our office ___ every evening.",
        options: [
          { text: "is cleaned" },
          { text: "cleans", errorType: "passive", whyHe: "המשרד לא מנקה – הוא מנוקה. צריך סביל." },
          { text: "is cleaning", errorType: "passive", whyHe: "is + V-ing = הווה ממושך פעיל, לא סביל." },
          { text: "cleaned", errorType: "passive", whyHe: "בלי be זה עבר פעיל, וגם לא מתאים ל-every evening." },
        ],
        answerIndex: 0,
        explainHe: "פעולה שחוזרת (every evening) בסביל: is + cleaned.",
      },
      {
        id: "g-passive-present-past-11",
        type: "mcq",
        prompt: "These photos ___ by my sister.",
        options: [
          { text: "were taken" },
          { text: "were took", errorType: "verb-form", whyHe: "took היא צורת העבר, לא V3. take → taken." },
          { text: "was taken", errorType: "agreement", whyHe: "photos ברבים → were." },
          { text: "took", errorType: "passive", whyHe: "התמונות לא צילמו – הן צולמו. by my sister מסמן סביל." },
        ],
        answerIndex: 0,
        explainHe: "were + taken. by my sister אומר לנו מי צילם.",
      },
      {
        id: "g-passive-present-past-12",
        type: "mcq",
        prompt: "The meeting ___ because the boss was sick.",
        options: [
          { text: "was canceled" },
          { text: "canceled", errorType: "passive", whyHe: "הפגישה לא ביטלה כלום – היא בוטלה." },
          { text: "was cancel", errorType: "verb-form", whyHe: "אחרי was צריך V3: canceled." },
          { text: "is canceled", errorType: "tense", whyHe: "המשפט בעבר (the boss was sick) → was canceled." },
        ],
        answerIndex: 0,
        explainHe: "'ביטלו את הפגישה' = The meeting was canceled.",
      },
      { id: "g-passive-present-past-13", type: "fix", prompt: "The house builded in 1990.", answer: "The house was built in 1990.", errorType: "passive", explainHe: "חסר be, ו-build הוא לא רגיל: was built." },
      { id: "g-passive-present-past-14", type: "fix", prompt: "I born in Tel Aviv in 1998.", answer: "I was born in Tel Aviv in 1998.", errorType: "passive", explainHe: "born תמיד עם be: I was born." },
      { id: "g-passive-present-past-15", type: "fix", prompt: "The letters are send every Monday.", answer: "The letters are sent every Monday.", errorType: "verb-form", explainHe: "אחרי are בסביל בא V3: sent." },
      { id: "g-passive-present-past-16", type: "fix", prompt: "Hebrew speaks in Israel.", answer: "Hebrew is spoken in Israel.", errorType: "passive", explainHe: "עברית היא מה שמדברים, לא מי שמדבר: is spoken." },
      { id: "g-passive-present-past-17", type: "fix", prompt: "The rooms was cleaned this morning.", answer: "The rooms were cleaned this morning.", errorType: "agreement", explainHe: "rooms ברבים → were cleaned." },
      { id: "g-passive-present-past-18", type: "transform", prompt: "Someone stole my wallet.", keyword: "was", answer: "My wallet was stolen.", accept: ["My wallet was stolen by someone."], explainHe: "כשלא יודעים מי עשה את זה, מתחילים מהארנק: My wallet was stolen. אין צורך ב-by someone." },
      { id: "g-passive-present-past-19", type: "transform", prompt: "They make these shoes in Italy.", keyword: "are", answer: "These shoes are made in Italy.", explainHe: "הווה פשוט סביל: are + made. 'They' הכללי נעלם." },
      { id: "g-passive-present-past-20", type: "transform", prompt: "The police arrested two men last night.", keyword: "were", answer: "Two men were arrested last night.", accept: ["Two men were arrested by the police last night."], explainHe: "עבר סביל: were + arrested. אפשר להוסיף by the police, אבל זה ברור מאליו." },
      { id: "g-passive-present-past-21", type: "order", words: ["was", "the", "window", "broken", "by", "the", "kids"], answer: "The window was broken by the kids.", explainHe: "נושא + was + V3 + by + מי שעשה." },
      { id: "g-passive-present-past-22", type: "order", words: ["are", "these", "cookies", "made", "with", "butter"], answer: "These cookies are made with butter.", accept: ["Are these cookies made with butter?"], explainHe: "are + made. with = החומר שממנו זה עשוי, לא מי שהכין." },
      { id: "g-passive-present-past-23", type: "translate", he: "האוטו שלי נגנב אתמול.", answer: "My car was stolen yesterday.", explainHe: "steal → stolen. סביל בעבר: was stolen." },
      { id: "g-passive-present-past-24", type: "translate", he: "נולדתי בירושלים.", answer: "I was born in Jerusalem.", explainHe: "'נולדתי' = I was born – תמיד עם was/were." },
    ],
  },
  // ------------------------------------------------------------------
  // 23. Passive: other tenses, modals, "by"
  // ------------------------------------------------------------------
  {
    id: "g-passive-other",
    title: "Passive: other tenses, modals, \"by\"",
    titleHe: "סביל: זמנים נוספים ומודאלים",
    strand: "passive-reported",
    order: 23,
    prereqs: ["g-passive-present-past"],
    lesson: {
      explanationHe: [
        "הסביל עובד בכל הזמנים, לא רק בהווה ובעבר פשוט. הכלל תמיד אותו כלל: משנים רק את be, וה-V3 נשאר. בהווה מושלם: has/have been + V3 (The flight has been canceled). בעתיד: will be + V3 (The results will be announced tomorrow).",
        "בזמנים ממושכים משתמשים ב-being: is/are being + V3 להווה (The road is being repaired – מתקנים את הכביש עכשיו), was/were being + V3 לעבר (The house was being painted when I arrived).",
        "אחרי מודאלים (can, must, should, might, have to) הסביל הוא תמיד be + V3: This medicine must be kept in the fridge. The problem can be solved. אין to אחרי must ו-can, ואין שינוי ב-be.",
        "by מציין מי עשה את הפעולה, ומוסיפים אותו רק כשזה מידע חשוב: The painting was stolen by two men in masks. עם כלי או חומר משתמשים ב-with: The door was opened with a key. The cookies are made with butter.",
        "בדיבור יומיומי שומעים גם get במקום be: I got fired, my bike got stolen. זה אותו סביל, בסגנון פחות רשמי.",
      ],
      form: [
        { label: "הווה מושלם: has/have been + V3", example: "The flight has been canceled." },
        { label: "עתיד: will be + V3", example: "The winners will be announced on Friday." },
        { label: "הווה ממושך: is/are being + V3", example: "The road is being repaired." },
        { label: "עבר ממושך: was/were being + V3", example: "The house was being painted." },
        { label: "מודאלים: must/can/should be + V3", example: "This medicine must be kept cold." },
        { label: "by (מי) / with (במה)", example: "It was opened by Dan with a key." },
      ],
      examples: [
        { en: "Your order has already been sent.", he: "ההזמנה שלך כבר נשלחה." },
        { en: "The new bridge will be finished next year.", he: "הגשר החדש יושלם בשנה הבאה." },
        { en: "Sorry, the room is being cleaned right now.", he: "סליחה, מנקים את החדר ממש עכשיו." },
        { en: "The car was being repaired when I called.", he: "תיקנו את האוטו כשהתקשרתי." },
        { en: "Children must be accompanied by an adult.", he: "ילדים חייבים להיות מלווים על ידי מבוגר." },
        { en: "This problem can be solved in five minutes.", he: "את הבעיה הזאת אפשר לפתור בחמש דקות." },
        { en: "My application hasn't been approved yet.", he: "הבקשה שלי עדיין לא אושרה." },
        { en: "He got fired last month.", he: "הוא פוטר בחודש שעבר." },
      ],
      contrastHe: [
        "בעברית 'מתקנים את הכביש' הוא משפט סתמי בהווה. באנגלית הצורה הטבעית היא The road is being repaired – ודוברי עברית נוטים לדלג על being ולומר The road is repaired (שמשמעותו: זה נעשה בקביעות, לא עכשיו).",
        "אחרי מודאל בעברית אין be ('חייב להישמר'), ולכן נפוצה השמטה: must kept, can solved. באנגלית: must be kept, can be solved.",
        "'על ידי' = by. אבל 'עם/באמצעות' (כלי, חומר) = with. דוברי עברית לפעמים אומרים from ('נעשה מ...') – באנגלית: made by (מי) לעומת made of/from (חומר).",
        "בהווה מושלם סביל יש שני חלקי be: has been. דוברי עברית נוטים להשמיט את been: has canceled (שזה פעיל!).",
      ],
      commonErrors: [
        { wrong: "The report has been wrote by Dana.", right: "The report has been written by Dana.", whyHe: "אחרי been צריך V3: written, לא wrote." },
        { wrong: "The new mall will built next year.", right: "The new mall will be built next year.", whyHe: "אחרי will חייב be: will be built." },
        { wrong: "The car is repairing now.", right: "The car is being repaired now.", whyHe: "האוטו לא מתקן – מתקנים אותו. הווה ממושך סביל: is being + V3." },
        { wrong: "Your bag must leave outside.", right: "Your bag must be left outside.", whyHe: "מודאל + be + V3. התיק לא עוזב, משאירים אותו." },
        { wrong: "The cake was made from my grandmother.", right: "The cake was made by my grandmother.", whyHe: "מי שעשה = by. from מתאר חומר (made from flour)." },
        { wrong: "The flight has canceled.", right: "The flight has been canceled.", whyHe: "הטיסה לא ביטלה כלום. הווה מושלם סביל: has been canceled." },
      ],
    },
    items: [
      { id: "g-passive-other-01", type: "gap", prompt: "The road ___ (repair) at the moment, so take the other way.", answer: "is being repaired", hint: "הווה ממושך סביל", explainHe: "פעולה שקורית עכשיו בסביל: is being + repaired." },
      { id: "g-passive-other-02", type: "gap", prompt: "The results ___ (will / announce) tomorrow.", answer: "will be announced", explainHe: "עתיד סביל: will be + V3." },
      { id: "g-passive-other-03", type: "gap", prompt: "Your order has already ___ (send). It should arrive tomorrow.", answer: "been sent", explainHe: "הווה מושלם סביל: has (already) been + sent." },
      { id: "g-passive-other-04", type: "gap", prompt: "This medicine must ___ (keep) in the fridge.", answer: "be kept", explainHe: "מודאל + be + V3: must be kept." },
      { id: "g-passive-other-05", type: "gap", prompt: "The house ___ (paint) when I came by yesterday.", answer: "was being painted", hint: "עבר ממושך סביל", explainHe: "פעולה שהייתה באמצע כשהגעתי: was being + painted." },
      { id: "g-passive-other-06", type: "gap", prompt: "The problem can ___ (solve) in a few minutes.", answer: "be solved", explainHe: "can + be + solved. אין to אחרי can." },
      { id: "g-passive-other-07", type: "gap", prompt: "The painting was stolen ___ two men in masks. (by / with / from)", answer: "by", explainHe: "מי שעשה את הפעולה מסומן ב-by." },
      {
        id: "g-passive-other-08",
        type: "mcq",
        prompt: "The new bridge ___ next year.",
        options: [
          { text: "will be finished" },
          { text: "will finish", errorType: "passive", whyHe: "הגשר לא מסיים כלום – מסיימים אותו. צריך סביל." },
          { text: "will finished", errorType: "verb-form", whyHe: "אחרי will חייב be לפני V3." },
          { text: "will be finish", errorType: "verb-form", whyHe: "אחרי be בסביל בא V3: finished." },
        ],
        answerIndex: 0,
        explainHe: "עתיד סביל: will be + finished.",
      },
      {
        id: "g-passive-other-09",
        type: "mcq",
        prompt: "Sorry, the room ___ right now. Can you wait?",
        options: [
          { text: "is being cleaned" },
          { text: "is cleaning", errorType: "passive", whyHe: "החדר לא מנקה – מנקים אותו." },
          { text: "is cleaned", errorType: "aspect", whyHe: "is cleaned = מנוקה בקביעות. right now דורש being." },
          { text: "cleaning", errorType: "verb-form", whyHe: "חסר פועל be, ואין סביל." },
        ],
        answerIndex: 0,
        explainHe: "'מנקים את החדר עכשיו' = The room is being cleaned right now.",
      },
      {
        id: "g-passive-other-10",
        type: "mcq",
        prompt: "The door was opened ___ a key.",
        options: [
          { text: "with" },
          { text: "by", errorType: "preposition", whyHe: "by מציין מי עשה; המפתח הוא כלי → with." },
          { text: "from", errorType: "preposition", whyHe: "from = מקור/חומר, לא כלי." },
          { text: "of", errorType: "preposition", whyHe: "of לא מתאר כלי." },
        ],
        answerIndex: 0,
        explainHe: "כלי או אמצעי = with a key. מי שפתח = by Dan.",
      },
      {
        id: "g-passive-other-11",
        type: "mcq",
        prompt: "My application ___ yet.",
        options: [
          { text: "hasn't been approved" },
          { text: "hasn't approved", errorType: "passive", whyHe: "הבקשה לא מאשרת – מאשרים אותה. חסר been." },
          { text: "didn't approve", errorType: "tense", whyHe: "yet דורש הווה מושלם, וגם חסר סביל." },
          { text: "wasn't been approved", errorType: "verb-form", whyHe: "been מגיע אחרי has/have, לא אחרי was." },
        ],
        answerIndex: 0,
        explainHe: "yet + הווה מושלם סביל: hasn't been approved.",
      },
      {
        id: "g-passive-other-12",
        type: "mcq",
        prompt: "Children ___ by an adult at all times.",
        options: [
          { text: "must be accompanied" },
          { text: "must accompanied", errorType: "verb-form", whyHe: "אחרי מודאל חייב be לפני V3." },
          { text: "must to be accompanied", errorType: "modal", whyHe: "אחרי must אין to." },
          { text: "must be accompany", errorType: "verb-form", whyHe: "אחרי be בסביל בא V3: accompanied." },
        ],
        answerIndex: 0,
        explainHe: "מודאל + be + V3: must be accompanied.",
      },
      { id: "g-passive-other-13", type: "fix", prompt: "The report has been wrote by Dana.", answer: "The report has been written by Dana.", errorType: "verb-form", explainHe: "write → wrote → written. אחרי been צריך V3." },
      { id: "g-passive-other-14", type: "fix", prompt: "The new mall will built next year.", answer: "The new mall will be built next year.", errorType: "passive", explainHe: "עתיד סביל: will be built. חסר be." },
      { id: "g-passive-other-15", type: "fix", prompt: "The car is being repair at the garage.", answer: "The car is being repaired at the garage.", errorType: "verb-form", explainHe: "אחרי being בא V3: repaired." },
      { id: "g-passive-other-16", type: "fix", prompt: "The cake was made from my grandmother.", answer: "The cake was made by my grandmother.", errorType: "preposition", explainHe: "מי שעשה = by. from היה אומר שסבתא היא החומר..." },
      { id: "g-passive-other-17", type: "fix", prompt: "Your bag must leave outside.", answer: "Your bag must be left outside.", errorType: "passive", explainHe: "התיק לא עוזב – משאירים אותו: must be left." },
      { id: "g-passive-other-18", type: "transform", prompt: "They have canceled the flight.", keyword: "been", answer: "The flight has been canceled.", explainHe: "הווה מושלם סביל: has been + canceled. flight ביחיד → has." },
      { id: "g-passive-other-19", type: "transform", prompt: "Someone is cleaning the office now.", keyword: "being", answer: "The office is being cleaned now.", explainHe: "הווה ממושך סביל: is being + cleaned." },
      { id: "g-passive-other-20", type: "transform", prompt: "You should send the form by Friday.", keyword: "sent", answer: "The form should be sent by Friday.", explainHe: "מודאל + be + V3: should be sent. כאן by Friday = עד יום שישי, לא 'על ידי'." },
      { id: "g-passive-other-21", type: "order", words: ["has", "the", "package", "been", "delivered", "already"], answer: "The package has already been delivered.", accept: ["The package has been delivered already."], explainHe: "has + already + been + V3. already בדרך כלל בין has ל-been." },
      { id: "g-passive-other-22", type: "order", words: ["the", "will", "winners", "be", "announced", "on", "Friday"], answer: "The winners will be announced on Friday.", explainHe: "עתיד סביל: will be + announced." },
      { id: "g-passive-other-23", type: "translate", he: "המכתב עדיין לא נשלח.", answer: "The letter hasn't been sent yet.", accept: ["The letter still hasn't been sent.", "The letter has still not been sent."], explainHe: "'עדיין לא' = hasn't ... yet. הווה מושלם סביל: hasn't been sent." },
      { id: "g-passive-other-24", type: "translate", he: "הבעיה הזאת חייבת להיפתר היום.", answer: "This problem must be solved today.", accept: ["This problem has to be solved today.", "This problem needs to be solved today."], explainHe: "'חייבת להיפתר' = must be solved. מודאל + be + V3." },
    ],
  },
  // ------------------------------------------------------------------
  // 24. Reported speech: statements
  // ------------------------------------------------------------------
  {
    id: "g-reported-statements",
    title: "Reported speech: statements",
    titleHe: "דיבור עקיף: משפטי חיווי",
    strand: "passive-reported",
    order: 24,
    prereqs: ["g-past-perfect"],
    lesson: {
      explanationHe: [
        "דיבור עקיף (reported speech) הוא כשמספרים מה מישהו אמר, בלי לצטט אותו מילה במילה: 'I'm tired' הופך ל-She said she was tired. זה נפוץ מאוד בשיחה: לספר מה הבוס אמר, מה חבר סיפר, מה שמעתם בחדשות.",
        "הכלל המרכזי: כשפועל הדיווח בעבר (said, told), הפועל במשפט המדווח 'נסוג' זמן אחד אחורה (backshift). הווה → עבר: 'I live here' → he said he lived there. עבר / הווה מושלם → past perfect: 'I saw it' → she said she had seen it.",
        "גם מודאלים נסוגים: will → would, can → could, may → might. must ו-should נשארים. 'I'll call you' → he said he would call me.",
        "משתנים גם כינויי גוף (I → he/she) וביטויי זמן ומקום: now → then, today → that day, tomorrow → the next day, yesterday → the day before, here → there.",
        "say לעומת tell: tell תמיד עם מישהו אחריו (told me, told us), say בלי (said that...). אם רוצים say עם אדם: said to me. המילה that אחרי say/tell היא אופציונלית בדיבור.",
        "אם מה שנאמר עדיין נכון עכשיו, אפשר בדיבור לא לסגת בזמן: She said she lives in Haifa (והיא עדיין גרה שם). אבל הנסיגה תמיד נכונה, אז כשלא בטוחים – נסוגים.",
      ],
      form: [
        { label: "הווה פשוט → עבר פשוט", example: "\"I work here.\" → He said he worked there." },
        { label: "הווה ממושך → עבר ממושך", example: "\"I'm leaving.\" → She said she was leaving." },
        { label: "עבר / הווה מושלם → past perfect", example: "\"I lost it.\" → He said he had lost it." },
        { label: "will → would, can → could", example: "\"I'll help.\" → She said she would help." },
        { label: "tell + מישהו / say (+ that)", example: "He told me (that) he was busy." },
        { label: "tomorrow → the next day, here → there", example: "He said he'd come the next day." },
      ],
      examples: [
        { en: "She said she was very tired.", he: "היא אמרה שהיא עייפה מאוד." },
        { en: "He told me he had lost his phone.", he: "הוא אמר לי שהוא איבד את הטלפון שלו." },
        { en: "They said they couldn't find the hotel.", he: "הם אמרו שהם לא מוצאים את המלון." },
        { en: "Mom said she would be home at eight.", he: "אמא אמרה שהיא תהיה בבית בשמונה." },
        { en: "Dan said he was going to the gym.", he: "דן אמר שהוא הולך לחדר כושר." },
        { en: "The doctor told her that she needed to rest.", he: "הרופא אמר לה שהיא צריכה לנוח." },
        { en: "He said he didn't have any money on him.", he: "הוא אמר שאין עליו כסף." },
        { en: "She told us she'd call the next day.", he: "היא אמרה לנו שהיא תתקשר למחרת." },
      ],
      contrastHe: [
        "בעברית אין נסיגת זמנים: 'הוא אמר שהוא עייף' (הווה גם בדיווח). באנגלית הזמן נסוג: He said he was tired. זה ההבדל המרכזי, ודוברי עברית נוטים לשמור על הווה: He said he is tired.",
        "'אמר לי' – בעברית say + לי. באנגלית זה tell: He told me. הצירוף He said me הוא שגיאה נפוצה מאוד של דוברי עברית. אם מתעקשים על say: He said to me.",
        "'הוא אמר שהוא יבוא' – בעברית העתיד נשאר עתיד. באנגלית will → would: He said he would come.",
        "'הוא אמר שהוא ראה' – עבר בעברית נשאר עבר. באנגלית נסוג ל-had seen: He said he had seen it.",
      ],
      commonErrors: [
        { wrong: "He said me that he was busy.", right: "He told me that he was busy.", whyHe: "say לא מקבל אדם ישירות. 'אמר לי' = told me." },
        { wrong: "She told that she would be late.", right: "She said that she would be late.", whyHe: "tell חייב מישהו אחריו (told me). בלי אדם: said." },
        { wrong: "She said she will call me yesterday.", right: "She said she would call me yesterday.", whyHe: "אחרי said, will → would." },
        { wrong: "He said he is tired, so he went to sleep.", right: "He said he was tired, so he went to sleep.", whyHe: "פועל דיווח בעבר → הזמן נסוג: is → was." },
        { wrong: "They told us they have never been to Eilat before.", right: "They told us they had never been to Eilat before.", whyHe: "הווה מושלם נסוג ל-past perfect: had never been." },
        { wrong: "He said he can't come tomorrow.", right: "He said he couldn't come the next day.", whyHe: "can → could, ו-tomorrow הופך ל-the next day אם מדווחים ביום אחר." },
      ],
    },
    items: [
      { id: "g-reported-statements-01", type: "gap", prompt: "\"I'm tired.\" → She said she ___ tired.", answer: "was", explainHe: "am → was. הזמן נסוג אחרי said." },
      { id: "g-reported-statements-02", type: "gap", prompt: "\"I will call you.\" → He said he ___ call me.", answer: "would", explainHe: "will → would בדיבור עקיף." },
      { id: "g-reported-statements-03", type: "gap", prompt: "\"We live in Haifa.\" → They said they ___ (live) in Haifa.", answer: "lived", explainHe: "הווה פשוט → עבר פשוט: live → lived." },
      { id: "g-reported-statements-04", type: "gap", prompt: "\"I can't come.\" → Dana said she ___ come.", answer: "couldn't", explainHe: "בדיבור עקיף can עובר ל-couldn't (נסיגת זמן)." },
      { id: "g-reported-statements-05", type: "gap", prompt: "\"I have finished.\" → He said he ___ finished.", answer: "had", explainHe: "הווה מושלם (have finished) → past perfect (had finished)." },
      { id: "g-reported-statements-06", type: "gap", prompt: "\"I saw the movie.\" → She said she ___ (see) the movie.", answer: "had seen", explainHe: "עבר פשוט → past perfect: saw → had seen." },
      { id: "g-reported-statements-07", type: "gap", prompt: "He ___ (say / tell) me that the meeting was canceled.", answer: "told", explainHe: "יש אדם אחרי הפועל (me) → told. said me היא שגיאה." },
      {
        id: "g-reported-statements-08",
        type: "mcq",
        prompt: "He ___ he was late.",
        options: [
          { text: "said" },
          { text: "said me", errorType: "word-choice", whyHe: "say לא מקבל me ישירות. 'אמר לי' = told me." },
          { text: "told", errorType: "word-choice", whyHe: "tell חייב אדם אחריו: told me." },
          { text: "told to me", errorType: "word-choice", whyHe: "tell בלי to: told me. to הולך עם say: said to me." },
        ],
        answerIndex: 0,
        explainHe: "בלי אדם: said. עם אדם: told me / said to me.",
      },
      {
        id: "g-reported-statements-09",
        type: "mcq",
        prompt: "(A week ago) \"I'm working tomorrow.\" → She said she was working ___.",
        options: [
          { text: "the next day" },
          { text: "tomorrow", errorType: "reported", whyHe: "זה נאמר לפני שבוע, אז 'מחר' של אז הוא לא המחר של היום." },
          { text: "the day before", errorType: "reported", whyHe: "the day before = yesterday, ההפך." },
          { text: "next day", errorType: "article", whyHe: "צריך the: the next day (או the following day)." },
        ],
        answerIndex: 0,
        explainHe: "tomorrow בדיבור עקיף מזמן אחר → the next day.",
      },
      {
        id: "g-reported-statements-10",
        type: "mcq",
        prompt: "She said she ___ any money on her.",
        options: [
          { text: "didn't have" },
          { text: "doesn't have", errorType: "tense", whyHe: "אחרי said הזמן נסוג: doesn't → didn't." },
          { text: "hasn't", errorType: "tense", whyHe: "hasn't any money נשמע לא טבעי, וגם לא נסוג בזמן." },
          { text: "didn't had", errorType: "verb-form", whyHe: "אחרי didn't בא פועל בסיסי: have." },
        ],
        answerIndex: 0,
        explainHe: "בדיבור עקיף הווה עובר לעבר: don't have הופך ל-didn't have.",
      },
      {
        id: "g-reported-statements-11",
        type: "mcq",
        prompt: "\"I've lost my keys,\" he said. → He said he ___ his keys.",
        options: [
          { text: "had lost" },
          { text: "has lost", errorType: "tense", whyHe: "הווה מושלם נסוג ל-past perfect אחרי said." },
          { text: "had lose", errorType: "verb-form", whyHe: "אחרי had בא V3: lost." },
          { text: "have lost", errorType: "agreement", whyHe: "he + have לא מתאים, וגם צריך נסיגה ל-had." },
        ],
        answerIndex: 0,
        explainHe: "בדיבור עקיף הווה מושלם (have lost) הופך לעבר מושלם (had lost).",
      },
      {
        id: "g-reported-statements-12",
        type: "mcq",
        prompt: "My mom said ___ dinner was ready.",
        options: [
          { text: "that" },
          { text: "me that", errorType: "word-choice", whyHe: "said me היא שגיאה. או said that או told me that." },
          { text: "to that", errorType: "word-choice", whyHe: "said to מקבל אדם: said to me that." },
          { text: "us to", errorType: "verb-form", whyHe: "said us לא קיים, ו-to + שם פועל לא מתאים כאן." },
        ],
        answerIndex: 0,
        explainHe: "said (that) + משפט. אפשר גם told me (that).",
      },
      { id: "g-reported-statements-13", type: "fix", prompt: "He said me that he was busy.", answer: "He told me that he was busy.", accept: ["He said to me that he was busy."], errorType: "word-choice", explainHe: "'אמר לי' = told me. say מקבל אדם רק עם to." },
      { id: "g-reported-statements-14", type: "fix", prompt: "She told that she would be late.", answer: "She said that she would be late.", accept: ["She told me that she would be late.", "She told us that she would be late."], errorType: "word-choice", explainHe: "tell חייב מישהו אחריו. בלי אדם משתמשים ב-say." },
      { id: "g-reported-statements-15", type: "fix", prompt: "She said she will call me yesterday, but she didn't.", answer: "She said she would call me yesterday, but she didn't.", errorType: "reported", explainHe: "אחרי said: will → would. השיחה הייתה בעבר." },
      { id: "g-reported-statements-16", type: "fix", prompt: "They told us they have never been to Eilat before.", answer: "They told us they had never been to Eilat before.", errorType: "tense", explainHe: "have never been → had never been. 'before' מראה שזה לפני רגע הדיווח." },
      { id: "g-reported-statements-17", type: "fix", prompt: "Dan said he can't come because he is sick yesterday.", answer: "Dan said he couldn't come because he was sick yesterday.", errorType: "reported", explainHe: "yesterday מראה שזה דיווח מהעבר: can't → couldn't, is → was." },
      { id: "g-reported-statements-18", type: "transform", prompt: "\"I'm going to the gym,\" Dan said. → Dan said ___", keyword: "was", answer: "Dan said he was going to the gym.", accept: ["Dan said that he was going to the gym."], explainHe: "בדיבור עקיף גם הזמן וגם הגוף משתנים: am going הופך ל-was going, ו-I הופך ל-he." },
      { id: "g-reported-statements-19", type: "transform", prompt: "\"We can't find the hotel,\" they said. → They said ___", keyword: "couldn't", answer: "They said they couldn't find the hotel.", accept: ["They said that they couldn't find the hotel."], explainHe: "בדיבור עקיף can't הופך ל-couldn't, ו-we הופך ל-they." },
      { id: "g-reported-statements-20", type: "transform", prompt: "\"I'll be home at eight,\" Mom said. → Mom said ___", keyword: "would", answer: "Mom said she would be home at eight.", accept: ["Mom said that she would be home at eight."], explainHe: "בדיבור עקיף will הופך ל-would, ו-I הופך ל-she." },
      { id: "g-reported-statements-21", type: "order", words: ["said", "she", "she", "was", "tired", "very"], answer: "She said she was very tired.", explainHe: "נושא + said + (that) + נושא + פועל בעבר." },
      { id: "g-reported-statements-22", type: "order", words: ["told", "he", "me", "he", "had", "lost", "his", "phone"], answer: "He told me he had lost his phone.", explainHe: "told + me, ואז המשפט המדווח ב-past perfect." },
      { id: "g-reported-statements-23", type: "translate", he: "הוא אמר שהוא עסוק.", answer: "He said he was busy.", accept: ["He said that he was busy."], explainHe: "בעברית הווה, באנגלית הזמן נסוג: was busy." },
      { id: "g-reported-statements-24", type: "translate", he: "היא אמרה לי שהיא תתקשר מחר.", answer: "She told me she would call tomorrow.", accept: ["She told me that she would call tomorrow.", "She told me she would call me tomorrow.", "She told me that she would call me tomorrow.", "She told me she would call the next day.", "She told me that she would call the next day."], explainHe: "'אמרה לי' = told me. 'תתקשר' → would call." },
    ],
  },
  // ------------------------------------------------------------------
  // 25. Reported questions, requests & commands
  // ------------------------------------------------------------------
  {
    id: "g-reported-questions-requests",
    title: "Reported questions, requests & commands",
    titleHe: "דיבור עקיף: שאלות ובקשות",
    strand: "passive-reported",
    order: 25,
    prereqs: ["g-reported-statements"],
    lesson: {
      explanationHe: [
        "כשמדווחים על שאלה, השאלה הופכת למשפט רגיל: סדר המילים הוא של משפט חיווי (נושא ואז פועל), בלי do/does/did, ובלי סימן שאלה. 'Where do you live?' → He asked me where I lived.",
        "בשאלות Wh (where, what, why, how...) שומרים את מילת השאלה: She asked what time it was. בשאלות כן/לא (Do you...? Are you...?) מוסיפים if או whether: He asked if I was tired.",
        "נסיגת הזמנים עובדת כמו במשפטי חיווי: 'Are you tired?' → she asked if I was tired. 'Did you see it?' → he asked if I had seen it. גם כאן, בדיבור, לא תמיד נסוגים אם זה עדיין נכון.",
        "בקשות ופקודות מדווחים עם to + פועל: 'Close the window' → He told me to close the window. 'Please help me' → She asked me to help her. שלילה: not to: Mom told us not to be late.",
        "הבחירה בין tell ל-ask: tell לפקודות והוראות (told me to wait), ask לבקשות מנומסות (asked me to wait). שניהם חייבים אדם אחריהם.",
      ],
      form: [
        { label: "שאלת Wh: asked + wh + נושא + פועל", example: "She asked where the station was." },
        { label: "שאלת כן/לא: asked + if/whether + נושא + פועל", example: "He asked if I liked the food." },
        { label: "בלי do/does/did", example: "\"Where do you work?\" → He asked where I worked." },
        { label: "פקודה: told + מישהו + to + פועל", example: "He told me to close the door." },
        { label: "בקשה: asked + מישהו + to + פועל", example: "She asked me to help her." },
        { label: "שלילה: not to + פועל", example: "Mom told us not to be late." },
      ],
      examples: [
        { en: "He asked me where I lived.", he: "הוא שאל אותי איפה אני גר." },
        { en: "She asked if I was tired.", he: "היא שאלה אם אני עייף." },
        { en: "Dad asked what time it was.", he: "אבא שאל מה השעה." },
        { en: "The teacher told us to turn off our phones.", he: "המורה אמרה לנו לכבות את הטלפונים." },
        { en: "She asked me to open the door.", he: "היא ביקשה ממני לפתוח את הדלת." },
        { en: "Mom told us not to be late.", he: "אמא אמרה לנו לא לאחר." },
        { en: "They asked me how old I was.", he: "הם שאלו אותי בן כמה אני." },
        { en: "The doctor told him to stop smoking.", he: "הרופא אמר לו להפסיק לעשן." },
      ],
      contrastHe: [
        "בעברית סדר המילים בשאלה ובדיווח עליה זהה: 'איפה התחנה?' / 'שאלה איפה התחנה'. באנגלית השאלה הישירה מתהפכת (Where is the station?) אבל הדיווח חוזר לסדר רגיל (where the station was). דוברי עברית 'מייבאים' את ההיפוך גם לדיווח: She asked where was the station – שגיאה.",
        "בעברית 'שאל אם' = asked if/whether. אין להשתמש ב-that בשאלות מדווחות.",
        "'אמר לי ללכת' מתורגם ישירות: told me to go. אבל 'אמר לי לא ללכת' = told me not to go (not לפני to).",
        "'ביקש ממני' = asked me (בלי from!). asked from me היא שגיאת תרגום נפוצה.",
      ],
      commonErrors: [
        { wrong: "She asked where was the station.", right: "She asked where the station was.", whyHe: "בשאלה מדווחת הסדר הוא של משפט רגיל: נושא ואז פועל." },
        { wrong: "He asked me did I like the movie.", right: "He asked me if I liked the movie.", whyHe: "אין did בשאלה מדווחת. שאלת כן/לא → if + נושא + פועל בעבר." },
        { wrong: "The boss said us to finish by Friday.", right: "The boss told us to finish by Friday.", whyHe: "said us לא קיים. פקודה/הוראה: told us to." },
        { wrong: "My mom told me don't forget my keys.", right: "My mom told me not to forget my keys.", whyHe: "שלילה בפקודה מדווחת: not to + פועל." },
        { wrong: "He asked from me to help him.", right: "He asked me to help him.", whyHe: "asked + אדם ישירות, בלי from." },
        { wrong: "I asked her that she was OK.", right: "I asked her if she was OK.", whyHe: "שאלת כן/לא מדווחת עם if/whether, לא that." },
      ],
    },
    items: [
      { id: "g-reported-questions-requests-01", type: "gap", prompt: "\"Where do you live?\" → He asked me where I ___ (live).", answer: "lived", explainHe: "בלי do, סדר רגיל, והזמן נסוג: lived." },
      { id: "g-reported-questions-requests-02", type: "gap", prompt: "\"Are you tired?\" → She asked ___ I was tired.", answer: "if", accept: ["whether"], explainHe: "שאלת כן/לא → if (או whether)." },
      { id: "g-reported-questions-requests-03", type: "gap", prompt: "\"Close the window.\" → He told me ___ (close) the window.", answer: "to close", explainHe: "פקודה מדווחת: told me to + פועל." },
      { id: "g-reported-questions-requests-04", type: "gap", prompt: "\"Don't be late.\" → Mom told us ___ (not / be) late.", answer: "not to be", explainHe: "שלילה: not to + פועל. not לפני to." },
      { id: "g-reported-questions-requests-05", type: "gap", prompt: "\"What time is it?\" → She asked what time it ___.", answer: "was", explainHe: "סדר של משפט רגיל (it was), והזמן נסוג: is → was." },
      { id: "g-reported-questions-requests-06", type: "gap", prompt: "\"Can you help me?\" → He asked me ___ (help) him.", answer: "to help", explainHe: "בקשה מדווחת: asked me to + פועל." },
      { id: "g-reported-questions-requests-07", type: "gap", prompt: "\"Did you see the game?\" → Dad asked if I ___ (see) the game.", answer: "had seen", accept: ["saw"], explainHe: "did you see → had seen (נסיגה מלאה). בדיבור שומעים גם saw." },
      {
        id: "g-reported-questions-requests-08",
        type: "mcq",
        prompt: "She asked me where ___.",
        options: [
          { text: "the station was" },
          { text: "was the station", errorType: "word-order", whyHe: "היפוך שייך לשאלה ישירה. בדיווח: נושא ואז פועל." },
          { text: "does the station", errorType: "question-form", whyHe: "אין do/does בשאלה מדווחת, וגם חסר פועל." },
          { text: "the station does", errorType: "question-form", whyHe: "אין does בשאלה מדווחת. צריך פועל אמיתי: was." },
        ],
        answerIndex: 0,
        explainHe: "asked where + the station was. סדר רגיל, בלי היפוך.",
      },
      {
        id: "g-reported-questions-requests-09",
        type: "mcq",
        prompt: "He asked me ___ I liked the food.",
        options: [
          { text: "if" },
          { text: "that", errorType: "reported", whyHe: "that לדיווח על משפט חיווי. לשאלת כן/לא: if/whether." },
          { text: "what", errorType: "word-choice", whyHe: "what לא מתאים – השאלה הייתה Do you like the food? (כן/לא)." },
          { text: "do", errorType: "question-form", whyHe: "אין do בשאלה מדווחת." },
        ],
        answerIndex: 0,
        explainHe: "בשאלת כן/לא עקיפה משתמשים ב-if או whether, והמשפט חוזר לסדר רגיל: asked if I liked the food.",
      },
      {
        id: "g-reported-questions-requests-10",
        type: "mcq",
        prompt: "The teacher told us ___ our phones.",
        options: [
          { text: "to turn off" },
          { text: "turn off", errorType: "verb-form", whyHe: "אחרי told us צריך to + פועל." },
          { text: "that turn off", errorType: "reported", whyHe: "פקודה מדווחת לא עם that, אלא עם to." },
          { text: "to turned off", errorType: "verb-form", whyHe: "אחרי to בא הפועל הבסיסי: turn." },
        ],
        answerIndex: 0,
        explainHe: "פקודה: told + us + to turn off.",
      },
      {
        id: "g-reported-questions-requests-11",
        type: "mcq",
        prompt: "She asked me ___ late.",
        options: [
          { text: "not to be" },
          { text: "don't be", errorType: "reported", whyHe: "זה ציטוט ישיר. בדיווח: not to be." },
          { text: "to don't be", errorType: "verb-form", whyHe: "אין don't אחרי to. שלילה: not to." },
          { text: "no to be", errorType: "word-choice", whyHe: "השלילה כאן היא not, לא no." },
        ],
        answerIndex: 0,
        explainHe: "בקשה עקיפה נבנית עם asked + מושא + not to: asked me not to be late.",
      },
      {
        id: "g-reported-questions-requests-12",
        type: "mcq",
        prompt: "I asked him ___ he wanted coffee.",
        options: [
          { text: "if" },
          { text: "do", errorType: "question-form", whyHe: "אין do בשאלה מדווחת." },
          { text: "does", errorType: "question-form", whyHe: "אין does בשאלה מדווחת." },
          { text: "that", errorType: "reported", whyHe: "שאלת כן/לא מדווחת עם if/whether, לא that." },
        ],
        answerIndex: 0,
        explainHe: "שאלת כן/לא עקיפה: asked him if he wanted coffee — בלי סימן שאלה ובלי היפוך.",
      },
      { id: "g-reported-questions-requests-13", type: "fix", prompt: "She asked where was the station.", answer: "She asked where the station was.", errorType: "word-order", explainHe: "בשאלה מדווחת אין היפוך: the station was." },
      { id: "g-reported-questions-requests-14", type: "fix", prompt: "He asked me did I like the movie.", answer: "He asked me if I liked the movie.", accept: ["He asked me whether I liked the movie."], errorType: "question-form", explainHe: "did נעלם, מוסיפים if, והפועל בעבר: liked." },
      { id: "g-reported-questions-requests-15", type: "fix", prompt: "The boss said us to finish by Friday.", answer: "The boss told us to finish by Friday.", errorType: "word-choice", explainHe: "said us לא קיים באנגלית. הוראה: told us to." },
      { id: "g-reported-questions-requests-16", type: "fix", prompt: "My mom told me don't forget my keys.", answer: "My mom told me not to forget my keys.", errorType: "verb-form", explainHe: "שלילה בפקודה מדווחת: not to forget." },
      { id: "g-reported-questions-requests-17", type: "fix", prompt: "They asked me how old was I.", answer: "They asked me how old I was.", errorType: "word-order", explainHe: "how old + נושא + פועל: how old I was." },
      { id: "g-reported-questions-requests-18", type: "transform", prompt: "\"Why are you late?\" she asked me. → She asked me ___", keyword: "why", answer: "She asked me why I was late.", explainHe: "why + I was (סדר רגיל, are → was)." },
      { id: "g-reported-questions-requests-19", type: "transform", prompt: "\"Please open the door,\" he said to me. → He asked ___", keyword: "asked", answer: "He asked me to open the door.", explainHe: "בקשה: asked me to open." },
      { id: "g-reported-questions-requests-20", type: "transform", prompt: "\"Do you speak English?\" she asked. → She asked ___", keyword: "if", answer: "She asked if I spoke English.", accept: ["She asked me if I spoke English.", "She asked whether I spoke English.", "She asked me whether I spoke English."], explainHe: "שאלת כן/לא: if + I spoke (בלי do, בעבר)." },
      { id: "g-reported-questions-requests-21", type: "order", words: ["asked", "she", "me", "what", "I", "wanted"], answer: "She asked me what I wanted.", explainHe: "asked me + what + נושא + פועל." },
      { id: "g-reported-questions-requests-22", type: "order", words: ["told", "the", "doctor", "him", "to", "stop", "smoking"], answer: "The doctor told him to stop smoking.", explainHe: "told + him + to + פועל." },
      { id: "g-reported-questions-requests-23", type: "translate", he: "הוא שאל אותי איפה אני גר.", answer: "He asked me where I lived.", accept: ["He asked me where I live."], explainHe: "where + I lived – בלי do, סדר רגיל. בעברית הווה, באנגלית נסוג." },
      { id: "g-reported-questions-requests-24", type: "translate", he: "היא אמרה לי לחכות בחוץ.", answer: "She told me to wait outside.", explainHe: "'אמרה לי לחכות' = told me to wait." },
    ],
  },
  // ------------------------------------------------------------------
  // 26. Question formation & word order
  // ------------------------------------------------------------------
  {
    id: "g-question-formation",
    title: "Question formation & word order",
    titleHe: "בניית שאלות וסדר מילים",
    strand: "questions",
    order: 26,
    prereqs: ["g-present-simple-continuous"],
    lesson: {
      explanationHe: [
        "שאלות הן הלב של שיחה: לשאול איפה, מתי, למה, כמה. באנגלית לשאלה יש מבנה קבוע שחייבים לשלוט בו אוטומטית, כי שאלה בלי המבנה הזה (Where you live?) נשמעת שבורה גם אם מבינים אותה.",
        "הכלל: בשאלה פועל עזר בא לפני הנושא. אם יש כבר פועל עזר או be במשפט (is, are, was, have, can, will) – פשוט מחליפים סדר: She is coming → Is she coming? You can swim → Can you swim?",
        "אם אין פועל עזר (הווה פשוט, עבר פשוט) – מוסיפים do/does/did לפני הנושא, והפועל חוזר לצורה הבסיסית: She lives here → Does she live here? You went home → Did you go home?",
        "שאלות Wh: מילת השאלה ראשונה, ואז אותו מבנה: Wh + פועל עזר + נושא + פועל. Where do you work? What did you do? How long have you lived here?",
        "מילות יחס נשארות בסוף השאלה בדיבור: Who are you talking to? What are you looking for? Where are you from?",
      ],
      form: [
        { label: "be: Be + נושא", example: "Are they coming? Where is she?" },
        { label: "הווה פשוט: Do/Does + נושא + פועל", example: "Does she like coffee?" },
        { label: "עבר פשוט: Did + נושא + פועל", example: "What did you do yesterday?" },
        { label: "הווה מושלם: Have/Has + נושא + V3", example: "How long have you been here?" },
        { label: "מודאלים: Can/Will + נושא + פועל", example: "Can she speak French?" },
        { label: "מילת יחס בסוף", example: "Who are you going with?" },
      ],
      examples: [
        { en: "Do you like spicy food?", he: "אתה אוהב אוכל חריף?" },
        { en: "Where does she work?", he: "איפה היא עובדת?" },
        { en: "What did you do last weekend?", he: "מה עשית בסוף השבוע?" },
        { en: "Are they coming to the party?", he: "הם באים למסיבה?" },
        { en: "How long have you lived here?", he: "כמה זמן אתה גר כאן?" },
        { en: "What does this word mean?", he: "מה המילה הזאת אומרת?" },
        { en: "How much does this bag cost?", he: "כמה עולה התיק הזה?" },
        { en: "Who are you going with?", he: "עם מי אתה הולך?" },
      ],
      contrastHe: [
        "בעברית שאלת כן/לא היא בדיוק המשפט הרגיל עם אינטונציה: 'אתה בא?'. באנגלית חייבים פועל עזר לפני הנושא: Are you coming? / Do you like it? זה הקושי המרכזי של דוברי עברית: You like pizza? נשמע ילדותי או חסר.",
        "בעברית 'איפה אתה עובד?' אין do. באנגלית: Where do you work? – ה-do הוא חובה, לא תוספת. Where you work? היא השגיאה הנפוצה ביותר.",
        "'מה זה אומר?' / 'מה המשמעות של המילה?' – באנגלית What does this word mean? דוברי עברית אומרים What means this word? – שגיאה: mean הוא פועל רגיל וצריך does.",
        "אחרי do/does/did הפועל חוזר לצורה הבסיסית: Does she like? (לא likes), Did you go? (לא went). ה-s וה-ed 'עברו' לפועל העזר.",
      ],
      commonErrors: [
        { wrong: "Where you live?", right: "Where do you live?", whyHe: "הווה פשוט בשאלה חייב do/does לפני הנושא." },
        { wrong: "What means this word?", right: "What does this word mean?", whyHe: "mean הוא פועל רגיל: What does + נושא + mean?" },
        { wrong: "Does she likes coffee?", right: "Does she like coffee?", whyHe: "אחרי does הפועל בסיסי, בלי s." },
        { wrong: "Did you went home?", right: "Did you go home?", whyHe: "אחרי did הפועל בסיסי: go. העבר כבר ב-did." },
        { wrong: "How much it costs?", right: "How much does it cost?", whyHe: "צריך does לפני הנושא, והפועל בלי s." },
        { wrong: "You are coming tonight?", right: "Are you coming tonight?", whyHe: "עם be פשוט מחליפים סדר: Are you coming?" },
      ],
    },
    items: [
      { id: "g-question-formation-01", type: "gap", prompt: "___ you like spicy food?", answer: "Do", explainHe: "הווה פשוט עם you: Do you like...?" },
      { id: "g-question-formation-02", type: "gap", prompt: "Where ___ she work?", answer: "does", explainHe: "she בהווה פשוט → does. הפועל נשאר work (בלי s)." },
      { id: "g-question-formation-03", type: "gap", prompt: "What ___ you do last weekend?", answer: "did", explainHe: "last weekend = עבר → did. הפועל do נשאר בסיסי." },
      { id: "g-question-formation-04", type: "gap", prompt: "___ they coming to the party?", answer: "Are", explainHe: "יש be (coming) → מחליפים סדר: Are they coming?" },
      { id: "g-question-formation-05", type: "gap", prompt: "How long ___ you lived here?", answer: "have", explainHe: "How long + הווה מושלם: have you lived." },
      {
        id: "g-question-formation-06",
        type: "mcq",
        prompt: "___ this word mean?",
        options: [
          { text: "What does" },
          { text: "What means", errorType: "question-form", whyHe: "mean הוא פועל רגיל – צריך does לפני הנושא. תרגום ישיר מ'מה אומרת'." },
          { text: "What is mean", errorType: "question-form", whyHe: "mean הוא לא שם תואר, אין be כאן." },
          { text: "What do", errorType: "agreement", whyHe: "this word = יחיד → does." },
        ],
        answerIndex: 0,
        explainHe: "What does this word mean? – does + נושא + mean.",
      },
      {
        id: "g-question-formation-07",
        type: "mcq",
        prompt: "___ to the party last night?",
        options: [
          { text: "Did you go" },
          { text: "Did you went", errorType: "verb-form", whyHe: "אחרי did הפועל בסיסי: go." },
          { text: "Do you went", errorType: "tense", whyHe: "last night = עבר → did, ו-went לא יכול לבוא אחרי do." },
          { text: "Went you", errorType: "question-form", whyHe: "פועל רגיל לא מתהפך עם הנושא. צריך did." },
        ],
        answerIndex: 0,
        explainHe: "עבר פשוט בשאלה: Did + you + go.",
      },
      {
        id: "g-question-formation-08",
        type: "mcq",
        prompt: "___ your brother live?",
        options: [
          { text: "Where does" },
          { text: "Where do", errorType: "agreement", whyHe: "your brother = he → does." },
          { text: "Where is", errorType: "question-form", whyHe: "live הוא פועל רגיל, לא צריך be." },
          { text: "Where lives", errorType: "question-form", whyHe: "אין היפוך של פועל רגיל. צריך does." },
        ],
        answerIndex: 0,
        explainHe: "Where does your brother live? – does לגוף שלישי יחיד.",
      },
      {
        id: "g-question-formation-09",
        type: "mcq",
        prompt: "___ she speak French?",
        options: [
          { text: "Can" },
          { text: "Does can", errorType: "modal", whyHe: "מודאל לא צריך do. הוא עצמו מתהפך עם הנושא." },
          { text: "Is", errorType: "question-form", whyHe: "speak הוא פועל רגיל, לא צריך be." },
          { text: "Do", errorType: "agreement", whyHe: "עם she זה does, ובכל מקרה 'האם היא יודעת' = Can she." },
        ],
        answerIndex: 0,
        explainHe: "Can + she + speak. מודאל מתהפך בעצמו.",
      },
      { id: "g-question-formation-10", type: "fix", prompt: "Where you live?", answer: "Where do you live?", errorType: "question-form", explainHe: "חסר do לפני הנושא." },
      { id: "g-question-formation-11", type: "fix", prompt: "What means this word?", answer: "What does this word mean?", errorType: "question-form", explainHe: "סדר השאלה: מילת שאלה + does + נושא + פועל בסיס — What does this word mean?" },
      { id: "g-question-formation-12", type: "fix", prompt: "Does she likes coffee?", answer: "Does she like coffee?", errorType: "verb-form", explainHe: "אחרי does הפועל בלי s." },
      { id: "g-question-formation-13", type: "fix", prompt: "How much it costs?", answer: "How much does it cost?", errorType: "question-form", explainHe: "סדר השאלה: How much + does + נושא + פועל בסיס — How much does it cost?" },
      { id: "g-question-formation-14", type: "transform", prompt: "She lives in Haifa. (Ask where)", keyword: "where", answer: "Where does she live?", explainHe: "סדר השאלה: Where + does + נושא + פועל בסיס — Where does she live?" },
      { id: "g-question-formation-15", type: "transform", prompt: "They arrived at nine. (Ask what time)", keyword: "what time", answer: "What time did they arrive?", accept: ["When did they arrive?"], explainHe: "עבר → did, והפועל בסיסי: arrive." },
      { id: "g-question-formation-16", type: "transform", prompt: "He is talking to someone. (Ask who)", keyword: "who", answer: "Who is he talking to?", accept: ["To whom is he talking?", "Who is he talking with?"], explainHe: "be מתהפך: is he talking, ומילת היחס to נשארת בסוף." },
      { id: "g-question-formation-17", type: "order", words: ["do", "where", "you", "work"], answer: "Where do you work?", explainHe: "Wh + do + נושא + פועל." },
      { id: "g-question-formation-18", type: "order", words: ["did", "what", "you", "yesterday", "do"], answer: "What did you do yesterday?", explainHe: "What + did + you + do. הפועל do כאן הוא פועל רגיל ('לעשות')." },
      { id: "g-question-formation-19", type: "order", words: ["is", "why", "she", "crying"], answer: "Why is she crying?", explainHe: "בזמן ממושך פועל העזר is בא לפני הנושא: Why is she crying?" },
      { id: "g-question-formation-20", type: "order", words: ["long", "how", "have", "you", "here", "been"], answer: "How long have you been here?", explainHe: "בהווה מושלם פועל העזר have בא לפני הנושא: How long have you been here?" },
      { id: "g-question-formation-21", type: "order", words: ["does", "much", "how", "cost", "this", "bag"], answer: "How much does this bag cost?", explainHe: "סדר השאלה: How much + does + נושא + פועל בסיס — How much does this bag cost?" },
      { id: "g-question-formation-22", type: "order", words: ["you", "are", "going", "who", "with"], answer: "Who are you going with?", explainHe: "Who + are + you + going + with. מילת היחס בסוף." },
      { id: "g-question-formation-23", type: "translate", he: "איפה אתה עובד?", answer: "Where do you work?", explainHe: "בעברית אין do, באנגלית חובה: Where do you work?" },
      { id: "g-question-formation-24", type: "translate", he: "מה עשית אתמול?", answer: "What did you do yesterday?", explainHe: "עבר → did + do. 'עשית' = did you do." },
    ],
  },
  // ------------------------------------------------------------------
  // 27. Indirect questions
  // ------------------------------------------------------------------
  {
    id: "g-indirect-questions",
    title: "Indirect questions: Could you tell me where...?",
    titleHe: "שאלות עקיפות מנומסות",
    strand: "questions",
    order: 27,
    prereqs: ["g-question-formation"],
    lesson: {
      explanationHe: [
        "שאלה עקיפה היא שאלה 'עטופה' בפתיח מנומס או במשפט: Could you tell me where the bank is? Do you know what time the store opens? I don't know what it is. משתמשים בה כדי להישמע מנומסים (עם זרים, בעבודה, בשירות) או כשמדברים על משהו שלא יודעים.",
        "פתיחים נפוצים: Could you tell me...? Do you know...? Do you have any idea...? I wonder... I'm not sure... I have no idea... I'd like to know...",
        "הכלל החשוב: אחרי הפתיח, החלק של השאלה הוא בסדר של משפט רגיל – נושא ואז פועל, ובלי do/does/did. Where is the bank? הופך ל-...where the bank is. What time does it open? הופך ל-...what time it opens. שימו לב: ה-s חוזרת לפועל (opens) כי אין יותר does.",
        "שאלת כן/לא בתוך שאלה עקיפה מקבלת if או whether: Is this seat free? → Do you know if this seat is free?",
        "בניגוד לדיבור עקיף, הזמן לא משתנה: Could you tell me where she lives? (הווה נשאר הווה). סימן שאלה בסוף רק אם הפתיח עצמו שאלה (Could you tell me...?), ולא אחרי I don't know / I wonder.",
      ],
      form: [
        { label: "פתיח + wh + נושא + פועל", example: "Could you tell me where the bank is?" },
        { label: "בלי do/does/did", example: "Do you know what time it opens?" },
        { label: "שאלת כן/לא: if / whether", example: "Do you know if the bank is open?" },
        { label: "בתוך משפט (בלי סימן שאלה)", example: "I don't know what it is." },
        { label: "I wonder / I have no idea", example: "I have no idea why he left." },
        { label: "הזמן לא משתנה", example: "Could you tell me where she lives?" },
      ],
      examples: [
        { en: "Could you tell me where the station is?", he: "תוכל להגיד לי איפה התחנה?" },
        { en: "Do you know what time the store opens?", he: "אתה יודע מתי החנות נפתחת?" },
        { en: "I don't know what it is.", he: "אני לא יודע מה זה." },
        { en: "Can you tell me if this bus goes downtown?", he: "אתה יכול להגיד לי אם האוטובוס הזה נוסע למרכז?" },
        { en: "I'm not sure how much it costs.", he: "אני לא בטוח כמה זה עולה." },
        { en: "I wonder why the bus is late.", he: "מעניין למה האוטובוס מאחר." },
        { en: "Do you know if anyone here speaks Spanish?", he: "אתה יודע אם מישהו כאן מדבר ספרדית?" },
        { en: "I have no idea where Dan went last night.", he: "אין לי מושג לאן דן הלך אתמול בלילה." },
      ],
      contrastHe: [
        "בעברית 'אתה יודע איפה התחנה?' – המבנה זהה לאנגלית (נושא ואז פועל). הבעיה היא שדוברי עברית כבר למדו להפוך שאלות ישירות באנגלית (Where is the station?) ומכניסים את ההיפוך גם לתוך השאלה העקיפה: Do you know where is the station? – זו השגיאה המרכזית.",
        "'אני לא יודע מה זה' → I don't know what it is (לא what is it). המילה it באה לפני is, כמו במשפט רגיל.",
        "'אתה יודע אם...' = Do you know if... – בעברית 'אם' ובאנגלית if/whether. לא that ולא do.",
        "'מעניין אם / למה' = I wonder if / why – ביטוי מאוד נפוץ בדיבור, בלי סימן שאלה.",
      ],
      commonErrors: [
        { wrong: "Do you know where is the toilet?", right: "Do you know where the toilet is?", whyHe: "אחרי הפתיח: נושא ואז פועל. ההיפוך שייך רק לשאלה הישירה." },
        { wrong: "I don't know what is it.", right: "I don't know what it is.", whyHe: "what + it + is. סדר של משפט רגיל." },
        { wrong: "Could you tell me what time does the movie start?", right: "Could you tell me what time the movie starts?", whyHe: "אין does בשאלה עקיפה, וה-s חוזרת לפועל: starts." },
        { wrong: "Can you tell me does this bus go downtown?", right: "Can you tell me if this bus goes downtown?", whyHe: "שאלת כן/לא בתוך שאלה עקיפה → if + נושא + פועל (goes)." },
        { wrong: "I wonder where did he go.", right: "I wonder where he went.", whyHe: "אין did. הפועל עצמו בעבר: went." },
        { wrong: "Do you know how much costs it?", right: "Do you know how much it costs?", whyHe: "נושא (it) לפני הפועל (costs)." },
      ],
    },
    items: [
      { id: "g-indirect-questions-01", type: "gap", prompt: "Could you tell me where the bank ___ (be)?", answer: "is", explainHe: "the bank is – נושא ואז פועל, הווה נשאר הווה." },
      { id: "g-indirect-questions-02", type: "gap", prompt: "Do you know what time the store ___ (open)?", answer: "opens", explainHe: "אין does, אז ה-s חוזרת לפועל: opens." },
      { id: "g-indirect-questions-03", type: "gap", prompt: "I don't know ___ she is coming. (if / that / what)", answer: "if", accept: ["whether"], explainHe: "שאלת כן/לא בתוך משפט → if (או whether)." },
      { id: "g-indirect-questions-04", type: "gap", prompt: "I'm not sure how much it ___ (cost).", answer: "costs", explainHe: "it costs – בלי does, עם s." },
      { id: "g-indirect-questions-05", type: "gap", prompt: "Do you know where ___ (Dan / go) last night?", answer: "Dan went", explainHe: "בלי did: הנושא ואז הפועל בעבר – Dan went." },
      {
        id: "g-indirect-questions-06",
        type: "mcq",
        prompt: "Could you tell me ___?",
        options: [
          { text: "where the station is" },
          { text: "where is the station", errorType: "word-order", whyHe: "היפוך שייך לשאלה ישירה. כאן: נושא ואז פועל." },
          { text: "where does the station", errorType: "question-form", whyHe: "אין does בשאלה עקיפה, וחסר פועל." },
          { text: "where the station does", errorType: "question-form", whyHe: "does לא מתאים כאן – צריך את הפועל is." },
        ],
        answerIndex: 0,
        explainHe: "בשאלה עקיפה מנומסת אין היפוך: Could you tell me where the station is?",
      },
      {
        id: "g-indirect-questions-07",
        type: "mcq",
        prompt: "I don't know ___.",
        options: [
          { text: "what it is" },
          { text: "what is it", errorType: "word-order", whyHe: "תרגום ישיר של 'מה זה?'. בתוך משפט: what it is." },
          { text: "what does it", errorType: "question-form", whyHe: "אין does בשאלה עקיפה, וחסר פועל." },
          { text: "what it be", errorType: "verb-form", whyHe: "צריך את be בצורה מוטה: is." },
        ],
        answerIndex: 0,
        explainHe: "I don't know what it is. – נושא (it) לפני הפועל (is).",
      },
      {
        id: "g-indirect-questions-08",
        type: "mcq",
        prompt: "Do you know ___ speaks Spanish here?",
        options: [
          { text: "if anyone" },
          { text: "anyone", errorType: "question-form", whyHe: "חסר if – השאלה המקורית היא כן/לא (Does anyone speak...?)." },
          { text: "does anyone", errorType: "question-form", whyHe: "אין does בשאלה עקיפה." },
          { text: "that anyone", errorType: "word-choice", whyHe: "that לא מתאים לשאלת כן/לא. צריך if/whether." },
        ],
        answerIndex: 0,
        explainHe: "שאלת כן/לא עקיפה נפתחת ב-if, והפועל חוזר לסדר רגיל: Do you know if anyone speaks Spanish?",
      },
      {
        id: "g-indirect-questions-09",
        type: "mcq",
        prompt: "I wonder ___ the bus is late.",
        options: [
          { text: "why" },
          { text: "why does", errorType: "question-form", whyHe: "אין does אחרי I wonder – יש כבר פועל (is)." },
          { text: "why is", errorType: "word-order", whyHe: "זה היפוך של שאלה ישירה. ה-is כבר נמצא אחרי the bus." },
          { text: "that why", errorType: "word-choice", whyHe: "אין that לפני מילת שאלה." },
        ],
        answerIndex: 0,
        explainHe: "I wonder why + the bus is late. בלי היפוך, בלי סימן שאלה.",
      },
      { id: "g-indirect-questions-10", type: "fix", prompt: "Do you know where is the toilet?", answer: "Do you know where the toilet is?", errorType: "question-form", explainHe: "אחרי where: the toilet is (נושא ואז פועל)." },
      { id: "g-indirect-questions-11", type: "fix", prompt: "Could you tell me what time does the movie start?", answer: "Could you tell me what time the movie starts?", errorType: "question-form", explainHe: "does נעלם, וה-s עוברת לפועל: starts." },
      { id: "g-indirect-questions-12", type: "fix", prompt: "I don't know what is it.", answer: "I don't know what it is.", errorType: "word-order", explainHe: "what it is – סדר של משפט רגיל." },
      { id: "g-indirect-questions-13", type: "fix", prompt: "Can you tell me does this bus go downtown?", answer: "Can you tell me if this bus goes downtown?", accept: ["Can you tell me whether this bus goes downtown?"], errorType: "question-form", explainHe: "שאלת כן/לא → if + this bus goes. ה-s חוזרת לפועל." },
      { id: "g-indirect-questions-14", type: "transform", prompt: "Where is the post office? → Could you tell me ___", keyword: "tell", answer: "Could you tell me where the post office is?", explainHe: "בשאלה עקיפה הנושא בא לפני הפועל: where the post office is." },
      { id: "g-indirect-questions-15", type: "transform", prompt: "Does this train stop in Haifa? → Do you know ___", keyword: "know", answer: "Do you know if this train stops in Haifa?", accept: ["Do you know whether this train stops in Haifa?"], explainHe: "שאלת כן/לא → if + this train stops (בלי does, עם s)." },
      { id: "g-indirect-questions-16", type: "transform", prompt: "How much did it cost? → I'd like to know ___", keyword: "like", answer: "I'd like to know how much it cost.", explainHe: "did נעלם, והפועל בעבר: cost (עבר של cost = cost)." },
      { id: "g-indirect-questions-17", type: "order", words: ["you", "could", "tell", "me", "where", "the", "is", "station"], answer: "Could you tell me where the station is?", explainHe: "פתיח מנומס + where + the station + is." },
      { id: "g-indirect-questions-18", type: "order", words: ["know", "do", "you", "what", "time", "it", "is"], answer: "Do you know what time it is?", explainHe: "Do you know + what time + it is. לא what time is it." },
      { id: "g-indirect-questions-19", type: "order", words: ["I'm", "not", "sure", "where", "lives", "she"], answer: "I'm not sure where she lives.", explainHe: "I'm not sure + where + she lives (עם s, בלי does)." },
      { id: "g-indirect-questions-20", type: "order", words: ["wonder", "I", "if", "open", "is", "the", "bank"], answer: "I wonder if the bank is open.", explainHe: "I wonder + if + the bank is open. בלי סימן שאלה." },
      { id: "g-indirect-questions-21", type: "order", words: ["me", "tell", "you", "can", "how", "much", "costs", "it"], answer: "Can you tell me how much it costs?", explainHe: "how much + it costs – נושא לפני הפועל." },
      { id: "g-indirect-questions-22", type: "order", words: ["idea", "no", "I", "have", "why", "left", "he"], answer: "I have no idea why he left.", explainHe: "I have no idea + why + he left. בלי did." },
      { id: "g-indirect-questions-23", type: "translate", he: "אתה יודע איפה התחנה?", answer: "Do you know where the station is?", explainHe: "where the station is – לא where is the station." },
      { id: "g-indirect-questions-24", type: "translate", he: "אני לא יודע מה זה.", answer: "I don't know what it is.", accept: ["I don't know what this is.", "I don't know what that is."], explainHe: "what it is – הנושא לפני הפועל." },
    ],
  },
];
