import type { GrammarTopic } from "@/lib/types";

// Strands: questions (orders 28-29) and prepositions (orders 35-36).
export const QUESTIONS_PREPOSITIONS: GrammarTopic[] = [
  // ------------------------------------------------------------------
  // 28. Question tags
  // ------------------------------------------------------------------
  {
    id: "g-question-tags",
    title: "Question tags",
    titleHe: "שאלות זנב (isn't it?)",
    strand: "questions",
    order: 28,
    prereqs: ["g-question-formation"],
    lesson: {
      explanationHe: [
        "שאלת זנב היא תוספת קצרה בסוף משפט שמבקשת אישור או מזמינה הסכמה: You're Israeli, aren't you? זה אחד הדברים שהכי מרגישים 'טבעיים' באנגלית מדוברת – מי שלא משתמש בזה נשמע יבש.",
        "בעברית יש זנב אחד לכל המקרים: 'נכון?' או 'לא?'. באנגלית הזנב משתנה לפי המשפט, ובזה כל הקושי. אין דרך לתרגם ישירות – צריך להרכיב את הזנב מהמשפט עצמו.",
        "כלל ראשון – הפוך את הסימן: משפט חיובי מקבל זנב שלילי, ומשפט שלילי מקבל זנב חיובי. You're coming, aren't you? מול You aren't coming, are you?",
        "כלל שני – חזור על פועל העזר שכבר נמצא במשפט (is, are, was, can, will, have). אם אין פועל עזר, כלומר הווה או עבר פשוט, משתמשים ב-do/does/did בדיוק כמו בשאלה רגילה: She works here, doesn't she?",
        "בזנב תמיד בא כינוי גוף ולא שם: Dan is late, isn't he? (לא isn't Dan). עם there משאירים there: There's a problem, isn't there?",
        "כדאי לזכור כמה מקרים מיוחדים: I'm late, aren't I? / ציווי: Close the window, will you? / Let's go, shall we? מילים כמו never, nothing, nobody נחשבות שליליות, ולכן הזנב חיובי: He never calls, does he?",
      ],
      form: [
        { label: "חיובי + זנב שלילי", example: "You're tired, aren't you?" },
        { label: "שלילי + זנב חיובי", example: "She isn't ready, is she?" },
        { label: "הווה פשוט: do / does", example: "He works here, doesn't he?" },
        { label: "עבר פשוט: did", example: "They left early, didn't they?" },
        { label: "מודאל / have חוזרים כמו שהם", example: "You can drive, can't you?" },
        { label: "מיוחדים: I'm / ציווי / Let's", example: "I'm next, aren't I? Let's go, shall we?" },
      ],
      examples: [
        { en: "You're coming tonight, aren't you?", he: "אתה בא הערב, נכון?" },
        { en: "She works in a bank, doesn't she?", he: "היא עובדת בבנק, נכון?" },
        { en: "They didn't call you, did they?", he: "הם לא התקשרו אליך, נכון?" },
        { en: "It's a great song, isn't it?", he: "זה שיר מעולה, לא?" },
        { en: "You haven't seen my keys, have you?", he: "לא ראית את המפתחות שלי, נכון?" },
        { en: "Dan can drive, can't he?", he: "דן יודע לנהוג, נכון?" },
        { en: "Let's take a taxi, shall we?", he: "בוא ניקח מונית, טוב?" },
        { en: "He never answers his phone, does he?", he: "הוא אף פעם לא עונה לטלפון, נכון?" },
      ],
      contrastHe: [
        "בעברית זנב אחד משרת הכל: 'אתה בא, נכון?', 'היא לא באה, נכון?'. באנגלית כל משפט מקבל זנב אחר, כי הזנב בנוי מפועל העזר של המשפט.",
        "התרגום הישיר של 'לא?' ל-no? הוא שגיאה נפוצה מאוד: You're coming, no? צריך: You're coming, aren't you?",
        "בזנב חייב לבוא כינוי גוף (he, she, it, they, we, you, I). דוברי עברית חוזרים על השם: Dan is late, isn't Dan? – באנגלית זה לא קיים.",
        "היפוך הסימן הוא הרעיון הכי זר לעברית: אחרי משפט שלילי הזנב חיובי. You didn't see it, did you? – ולא didn't you?",
      ],
      commonErrors: [
        { wrong: "You are coming tonight, no?", right: "You are coming tonight, aren't you?", whyHe: "'לא?' לא מתורגם ל-no. בונים זנב מפועל העזר: are → aren't you." },
        { wrong: "She works here, isn't she?", right: "She works here, doesn't she?", whyHe: "אין be במשפט. הווה פשוט עם she → does, ולכן doesn't she." },
        { wrong: "Dan is a doctor, isn't Dan?", right: "Dan is a doctor, isn't he?", whyHe: "בזנב בא כינוי גוף במקום השם: he." },
        { wrong: "You didn't call me, didn't you?", right: "You didn't call me, did you?", whyHe: "המשפט שלילי, ולכן הזנב חיובי: did you?" },
        { wrong: "I'm late, am not I?", right: "I'm late, aren't I?", whyHe: "אין am not בזנב. הצורה המקובלת היא aren't I." },
        { wrong: "He never calls, doesn't he?", right: "He never calls, does he?", whyHe: "never הופך את המשפט לשלילי, ולכן הזנב חיובי: does he?" },
      ],
    },
    items: [
      { id: "g-question-tags-01", type: "gap", prompt: "You're coming tonight, ___?", answer: "aren't you", hint: "חיובי → זנב שלילי", explainHe: "יש be במשפט (you're), ולכן הזנב הוא aren't you." },
      { id: "g-question-tags-02", type: "gap", prompt: "She works in a bank, ___?", answer: "doesn't she", explainHe: "הווה פשוט בלי פועל עזר → does. חיובי, ולכן doesn't she." },
      { id: "g-question-tags-03", type: "gap", prompt: "They didn't call you, ___?", answer: "did they", explainHe: "המשפט שלילי (didn't), ולכן הזנב חיובי: did they." },
      { id: "g-question-tags-04", type: "gap", prompt: "Dan can drive, ___?", answer: "can't he", explainHe: "חוזרים על המודאל can, בשלילה, עם כינוי גוף: can't he." },
      { id: "g-question-tags-05", type: "gap", prompt: "You haven't seen my keys, ___?", answer: "have you", explainHe: "haven't שלילי → זנב חיובי: have you." },
      { id: "g-question-tags-06", type: "gap", prompt: "It isn't too late, ___?", answer: "is it", explainHe: "isn't שלילי → is it. עם it משאירים it, לא this." },
      { id: "g-question-tags-07", type: "gap", prompt: "Your parents live in Haifa, ___?", answer: "don't they", explainHe: "הווה פשוט ברבים → do. הזנב: don't they (כינוי גוף במקום your parents)." },
      { id: "g-question-tags-08", type: "gap", prompt: "We'll be late, ___?", answer: "won't we", explainHe: "will חוזר בשלילה: won't we." },
      {
        id: "g-question-tags-09",
        type: "mcq",
        prompt: "I'm late again, ___?",
        options: [
          { text: "aren't I" },
          { text: "am not I", errorType: "question-form", whyHe: "am not לא משמש בזנב. הצורה המקובלת היא aren't I." },
          { text: "isn't it", errorType: "interference", whyHe: "isn't it הוא לא 'נכון?' אוניברסלי – הזנב חייב להתאים לנושא I." },
          { text: "no", errorType: "interference", whyHe: "תרגום ישיר של 'לא?'. באנגלית אין זנב no." },
        ],
        answerIndex: 0,
        explainHe: "I'm late, aren't I? – יוצא דופן שכדאי לשנן.",
      },
      {
        id: "g-question-tags-10",
        type: "mcq",
        prompt: "He never answers his phone, ___?",
        options: [
          { text: "does he" },
          { text: "doesn't he", errorType: "question-form", whyHe: "never הופך את המשפט לשלילי, ולכן צריך זנב חיובי." },
          { text: "did he", errorType: "tense", whyHe: "המשפט בהווה פשוט (answers), ולכן does ולא did." },
          { text: "is he", errorType: "question-form", whyHe: "אין be במשפט. answer הוא פועל רגיל → does." },
        ],
        answerIndex: 0,
        explainHe: "never = שלילה, ולכן הזנב חיובי: does he?",
      },
      {
        id: "g-question-tags-11",
        type: "mcq",
        prompt: "Let's take a taxi, ___?",
        options: [
          { text: "shall we" },
          { text: "do we", errorType: "question-form", whyHe: "אחרי Let's הזנב הקבוע הוא shall we." },
          { text: "will we", errorType: "question-form", whyHe: "will you מתאים לציווי, אבל אחרי Let's אומרים shall we." },
          { text: "don't we", errorType: "question-form", whyHe: "Let's אינו משפט רגיל בהווה פשוט – אין כאן do." },
        ],
        answerIndex: 0,
        explainHe: "Let's ..., shall we? – צירוף קבוע להצעה.",
      },
      {
        id: "g-question-tags-12",
        type: "mcq",
        prompt: "There's a problem with the file, ___?",
        options: [
          { text: "isn't there" },
          { text: "isn't it", errorType: "question-form", whyHe: "עם There's הזנב חוזר על there, לא על it." },
          { text: "is there", errorType: "question-form", whyHe: "המשפט חיובי, ולכן הזנב חייב להיות שלילי." },
          { text: "doesn't it", errorType: "question-form", whyHe: "יש be במשפט (There's = There is), ולכן חוזרים על is." },
        ],
        answerIndex: 0,
        explainHe: "There is ..., isn't there? – there נשאר גם בזנב.",
      },
      {
        id: "g-question-tags-13",
        type: "mcq",
        prompt: "Close the window, ___?",
        options: [
          { text: "will you" },
          { text: "do you", errorType: "question-form", whyHe: "אחרי ציווי הזנב הוא will you (או can you), לא do you." },
          { text: "don't you", errorType: "question-form", whyHe: "ציווי אינו משפט חיובי רגיל – אין כאן היפוך סימן." },
          { text: "shall we", errorType: "question-form", whyHe: "shall we שייך ל-Let's, לא לציווי לאדם אחר." },
        ],
        answerIndex: 0,
        explainHe: "בקשה מנומסת בציווי: Close the window, will you?",
      },
      { id: "g-question-tags-14", type: "fix", prompt: "You are coming tonight, no?", answer: "You are coming tonight, aren't you?", errorType: "interference", explainHe: "'לא?' אינו no. בונים זנב מ-are: aren't you." },
      { id: "g-question-tags-15", type: "fix", prompt: "She works here, isn't she?", answer: "She works here, doesn't she?", errorType: "question-form", explainHe: "אין be במשפט. הווה פשוט עם she → doesn't she." },
      { id: "g-question-tags-16", type: "fix", prompt: "Dan is a doctor, isn't Dan?", answer: "Dan is a doctor, isn't he?", errorType: "question-form", explainHe: "בזנב בא כינוי גוף: he." },
      { id: "g-question-tags-17", type: "fix", prompt: "You didn't call me, didn't you?", answer: "You didn't call me, did you?", errorType: "question-form", explainHe: "משפט שלילי מקבל זנב חיובי: did you?" },
      { id: "g-question-tags-18", type: "fix", prompt: "It's cold today, is it?", answer: "It's cold today, isn't it?", errorType: "question-form", explainHe: "משפט חיובי מקבל זנב שלילי: isn't it?" },
      { id: "g-question-tags-19", type: "transform", prompt: "You've been to London. (Add a question tag)", keyword: "haven't", answer: "You've been to London, haven't you?", explainHe: "הווה מושלם חיובי → זנב שלילי עם have: haven't you." },
      { id: "g-question-tags-20", type: "transform", prompt: "Tom doesn't eat meat. (Add a question tag)", keyword: "does", answer: "Tom doesn't eat meat, does he?", explainHe: "doesn't שלילי → זנב חיובי, ובכינוי גוף: does he." },
      { id: "g-question-tags-21", type: "order", words: ["you", "coming", "are", "aren't", "you"], answer: "You are coming, aren't you?", explainHe: "משפט חיובי + זנב שלילי מאותו פועל עזר: are → aren't you." },
      { id: "g-question-tags-22", type: "order", words: ["works", "she", "here", "she", "doesn't"], answer: "She works here, doesn't she?", explainHe: "הווה פשוט → הזנב נבנה מ-does: doesn't she." },
      { id: "g-question-tags-23", type: "translate", he: "אתה בא איתנו, נכון?", answer: "You're coming with us, aren't you?", explainHe: "'נכון?' הופך לזנב שמתאים למשפט: aren't you." },
      { id: "g-question-tags-24", type: "translate", he: "היא לא אכלה כלום, נכון?", answer: "She didn't eat anything, did she?", explainHe: "משפט שלילי בעבר → זנב חיובי: did she." },
    ],
  },
  // ------------------------------------------------------------------
  // 29. Subject vs object questions
  // ------------------------------------------------------------------
  {
    id: "g-subject-object-questions",
    title: "Subject vs object questions",
    titleHe: "שאלות נושא ומושא",
    strand: "questions",
    order: 29,
    prereqs: ["g-question-formation"],
    lesson: {
      explanationHe: [
        "יש שני סוגים של שאלות who/what: כאלה ששואלות מי עשה את הפעולה, וכאלה ששואלות למי או מה הפעולה קרתה. ההבדל בין Who called you? (מי התקשר אליך) לבין Who did you call? (למי התקשרת) הוא הבדל של משמעות, לא של סגנון.",
        "כששאלת ה-Wh היא הנושא – כלומר היא זו שעושה את הפעולה – לא מוסיפים do/does/did בכלל, וסדר המילים נשאר כמו במשפט רגיל: Who called you? What happened? Who wants coffee?",
        "כששאלת ה-Wh היא המושא, חוזרים לבנייה הרגילה של שאלה: Wh + do/does/did + נושא + פועל בסיסי. Who did you call? What did you buy? Who did she talk to?",
        "בשאלת נושא הפועל נושא את הזמן ואת ה-s: Who wants coffee? (לא Who want), What happened? (לא What did happen). זו הנקודה שהכי קל לפספס.",
        "אותו כלל חל על Which, How many, How much ו-Whose כשהם מתחילים את הנושא: How many people came? Which team won? Whose phone rang?",
        "בשאלות מושא מילת היחס נשארת בסוף: Who did you go with? What are you looking at? – בדיוק כמו בשאלות רגילות.",
      ],
      form: [
        { label: "שאלת נושא: Wh + פועל (בלי do)", example: "Who called you?" },
        { label: "שאלת מושא: Wh + do/does/did + נושא + פועל", example: "Who did you call?" },
        { label: "נושא בהווה מקבל s", example: "Who wants coffee?" },
        { label: "What happened? – תמיד בלי did", example: "What happened to your phone?" },
        { label: "Which / How many + שם כנושא", example: "How many people came?" },
        { label: "מילת יחס בסוף בשאלת מושא", example: "Who did you go with?" },
      ],
      examples: [
        { en: "Who called you last night?", he: "מי התקשר אליך אתמול בלילה?" },
        { en: "Who did you call last night?", he: "למי התקשרת אתמול בלילה?" },
        { en: "What happened at the meeting?", he: "מה קרה בפגישה?" },
        { en: "What did you say to her?", he: "מה אמרת לה?" },
        { en: "Who wants another coffee?", he: "מי רוצה עוד קפה?" },
        { en: "How many people came to your party?", he: "כמה אנשים הגיעו למסיבה שלך?" },
        { en: "Which team won the game?", he: "איזו קבוצה ניצחה במשחק?" },
        { en: "Who did she talk to at the party?", he: "עם מי היא דיברה במסיבה?" },
      ],
      contrastHe: [
        "בעברית ההבדל מסומן במילית: 'מי התקשר אליך?' מול 'למי התקשרת?'. באנגלית אותה מילה (who) משמשת לשניהם, וההבדל מסומן בנוכחות או בהיעדר did – ולכן קל לטעות.",
        "דוברי עברית מוסיפים did גם בשאלת נושא, כי הם רגילים ש'שאלה = did': Who did call you? באנגלית זה נשמע כמו הדגשה מיוחדת, לא כמו שאלה רגילה.",
        "'מה קרה?' הוא תמיד What happened? – אף פעם What did happen? זה משפט שכדאי לשנן כמו שהוא.",
        "בשאלת נושא בהווה הפועל מקבל s: Who wants tea? בעברית אין שום סימן כזה, ולכן נופלת ה-s: Who want tea?",
      ],
      commonErrors: [
        { wrong: "Who did call you yesterday?", right: "Who called you yesterday?", whyHe: "who הוא הנושא כאן, ולכן אין did והפועל נושא את הזמן: called." },
        { wrong: "What did happen to your phone?", right: "What happened to your phone?", whyHe: "what הוא הנושא. 'מה קרה' = What happened, בלי did." },
        { wrong: "Who did broke the glass?", right: "Who broke the glass?", whyHe: "בשאלת נושא אין did, והפועל בעבר: broke." },
        { wrong: "Who you saw at the station?", right: "Who did you see at the station?", whyHe: "כאן who הוא המושא (אתה ראית מישהו), ולכן צריך did + פועל בסיסי." },
        { wrong: "How many people did came?", right: "How many people came?", whyHe: "How many people הוא הנושא, ולכן אין did והפועל בעבר: came." },
        { wrong: "Who want to come with me?", right: "Who wants to come with me?", whyHe: "who כנושא מתנהג כמו he/she: wants." },
      ],
    },
    items: [
      { id: "g-subject-object-questions-01", type: "gap", prompt: "Who ___ (call) you last night?", answer: "called", hint: "מי התקשר – שאלת נושא", explainHe: "who הוא הנושא, ולכן אין did והפועל בעבר: called." },
      { id: "g-subject-object-questions-02", type: "gap", prompt: "Who ___ you call last night?", answer: "did", explainHe: "כאן אתה עשית את הפעולה, ולכן who הוא המושא: Who did you call?" },
      { id: "g-subject-object-questions-03", type: "gap", prompt: "What ___ (happen) at the meeting?", answer: "happened", explainHe: "what הוא הנושא: What happened? – אף פעם לא What did happen." },
      { id: "g-subject-object-questions-04", type: "gap", prompt: "How many people ___ (come) to your party?", answer: "came", explainHe: "How many people הוא הנושא, ולכן הפועל בעבר בלי did." },
      { id: "g-subject-object-questions-05", type: "gap", prompt: "Which team ___ (win) the game last night?", answer: "won", explainHe: "Which team הוא הנושא: Which team won? בלי did." },
      { id: "g-subject-object-questions-06", type: "gap", prompt: "Who ___ (want) another coffee?", answer: "wants", hint: "הווה, שאלת נושא", explainHe: "who כנושא מתנהג כמו he/she ומקבל s: wants." },
      { id: "g-subject-object-questions-07", type: "gap", prompt: "Who ___ she talk to at the party?", answer: "did", explainHe: "היא דיברה עם מישהו, ולכן who הוא המושא: Who did she talk to?" },
      { id: "g-subject-object-questions-08", type: "gap", prompt: "What ___ (make) that noise last night?", answer: "made", explainHe: "what הוא מה שעשה את הרעש – שאלת נושא בלי did: made." },
      {
        id: "g-subject-object-questions-09",
        type: "mcq",
        prompt: "Who ___ the window?",
        options: [
          { text: "broke" },
          { text: "did break", errorType: "question-form", whyHe: "who הוא הנושא, ולכן אין did. did break נשמע כמו הדגשה מיוחדת." },
          { text: "did broke", errorType: "verb-form", whyHe: "גם אם היה did, אחריו בא פועל בסיסי: break." },
          { text: "does break", errorType: "tense", whyHe: "השאלה על אירוע שקרה, ובכל מקרה בשאלת נושא אין do." },
        ],
        answerIndex: 0,
        explainHe: "Who broke the window? – who עושה את הפעולה, ולכן הפועל בעבר בלי did.",
      },
      {
        id: "g-subject-object-questions-10",
        type: "mcq",
        prompt: "Who ___ you meet yesterday?",
        options: [
          { text: "did" },
          { text: "do", errorType: "tense", whyHe: "yesterday מחייב עבר: did." },
          { text: "have", errorType: "aspect", whyHe: "עם yesterday לא משתמשים בהווה מושלם." },
          { text: "were", errorType: "question-form", whyHe: "meet הוא פועל רגיל וצריך did, לא be." },
        ],
        answerIndex: 0,
        explainHe: "אתה פגשת מישהו, ולכן who הוא המושא: Who did you meet yesterday?",
      },
      {
        id: "g-subject-object-questions-11",
        type: "mcq",
        prompt: "What ___ after the concert?",
        options: [
          { text: "happened" },
          { text: "did happen", errorType: "question-form", whyHe: "'מה קרה' הוא תמיד What happened, בלי did." },
          { text: "was happened", errorType: "passive", whyHe: "happen אינו פועל סביל – אין was happened." },
          { text: "is happen", errorType: "verb-form", whyHe: "אין צירוף כזה. הצורה הנכונה בעבר היא happened." },
        ],
        answerIndex: 0,
        explainHe: "what הוא הנושא: What happened after the concert?",
      },
      {
        id: "g-subject-object-questions-12",
        type: "mcq",
        prompt: "How many students ___ the exam?",
        options: [
          { text: "passed" },
          { text: "did pass", errorType: "question-form", whyHe: "How many students הוא הנושא, ולכן אין did." },
          { text: "did passed", errorType: "verb-form", whyHe: "אחרי did בא פועל בסיסי, וגם ככה אין כאן did." },
          { text: "have pass", errorType: "verb-form", whyHe: "אחרי have צריך V3 (passed), אבל כאן פשוט passed." },
        ],
        answerIndex: 0,
        explainHe: "שאלת נושא: How many students passed the exam?",
      },
      {
        id: "g-subject-object-questions-13",
        type: "mcq",
        prompt: "Who ___ you that story?",
        options: [
          { text: "told" },
          { text: "did tell", errorType: "question-form", whyHe: "who הוא מי שסיפר, כלומר הנושא – בלי did." },
          { text: "did told", errorType: "verb-form", whyHe: "אחרי did בא פועל בסיסי, וכאן בכלל לא צריך did." },
          { text: "tells", errorType: "tense", whyHe: "מדובר בסיפור שכבר סופר: told." },
        ],
        answerIndex: 0,
        explainHe: "Who told you that story? – who הוא הנושא, ולכן told לבד.",
      },
      { id: "g-subject-object-questions-14", type: "fix", prompt: "Who did call you yesterday?", answer: "Who called you yesterday?", errorType: "question-form", explainHe: "שאלת נושא: אין did, והפועל בעבר: called." },
      { id: "g-subject-object-questions-15", type: "fix", prompt: "What did happen to your phone?", answer: "What happened to your phone?", errorType: "question-form", explainHe: "'מה קרה' = What happened, תמיד בלי did." },
      { id: "g-subject-object-questions-16", type: "fix", prompt: "Who did broke the glass?", answer: "Who broke the glass?", errorType: "question-form", explainHe: "who הוא הנושא: Who broke ...? בלי did." },
      { id: "g-subject-object-questions-17", type: "fix", prompt: "Who you saw at the station?", answer: "Who did you see at the station?", errorType: "question-form", explainHe: "כאן who הוא המושא, ולכן צריך did + see." },
      { id: "g-subject-object-questions-18", type: "fix", prompt: "How many people did came to the meeting?", answer: "How many people came to the meeting?", errorType: "question-form", explainHe: "How many people הוא הנושא: came, בלי did." },
      { id: "g-subject-object-questions-19", type: "transform", prompt: "Someone called you this morning. (Ask about the person who called)", keyword: "who", answer: "Who called you this morning?", explainHe: "מחפשים את מי שעשה את הפעולה → שאלת נושא בלי did." },
      { id: "g-subject-object-questions-20", type: "transform", prompt: "You called someone this morning. (Ask about the person you called)", keyword: "who did", answer: "Who did you call this morning?", accept: ["Whom did you call this morning?"], explainHe: "כאן אתה הנושא ו-who הוא המושא, ולכן did + call." },
      { id: "g-subject-object-questions-21", type: "order", words: ["who", "you", "yesterday", "helped"], answer: "Who helped you yesterday?", explainHe: "שאלת נושא: Wh + פועל + מושא, בלי פועל עזר." },
      { id: "g-subject-object-questions-22", type: "order", words: ["who", "did", "help", "you", "yesterday"], answer: "Who did you help yesterday?", explainHe: "שאלת מושא: Who + did + נושא + פועל בסיסי." },
      { id: "g-subject-object-questions-23", type: "translate", he: "מי התקשר אליך?", answer: "Who called you?", explainHe: "מי עשה את הפעולה → בלי did: Who called you?" },
      { id: "g-subject-object-questions-24", type: "translate", he: "למי התקשרת?", answer: "Who did you call?", accept: ["Whom did you call?"], explainHe: "אתה עשית את הפעולה, ולכן who הוא המושא: Who did you call?" },
    ],
  },
  // ------------------------------------------------------------------
  // 35. Prepositions of time & place: in / on / at
  // ------------------------------------------------------------------
  {
    id: "g-prepositions-time-place",
    title: "Prepositions of time & place: in / on / at",
    titleHe: "מילות יחס של זמן ומקום",
    strand: "prepositions",
    order: 35,
    prereqs: [],
    lesson: {
      explanationHe: [
        "בעברית אות אחת, ב־, מכסה כמעט הכל: בשמונה, ביום שני, ביוני, בבית, באוטובוס. באנגלית צריך לבחור בין in, on ו-at, ולכן דוברי עברית מנחשים. הפתרון הוא לזכור סולם של גודל.",
        "זמן: at לנקודה מדויקת (at eight, at midnight, at night), on ליום או תאריך (on Monday, on July 4th, on my birthday), in לתקופה גדולה שאפשר 'להיכנס' אליה (in May, in 2020, in the summer, in the morning).",
        "מקום: at לנקודה או למקום כמוסד (at the bus stop, at work, at home, at the door), on למשטח ולקו (on the table, on the wall, on the second floor, on Herzl Street), in למקום סגור או שטח גדול (in the room, in Tel Aviv, in Israel, in my bag).",
        "צירופים קבועים שחייבים לשנן: at home, at work, at school – בלי the. on the bus / on the train / on a plane – אבל in the car ו-in a taxi. in the picture ו-in the photo, לא on.",
        "on time פירושו בזמן המדויק (The meeting started on time), ואילו in time פירושו מספיק מוקדם בשביל משהו (We arrived in time for dinner). in two weeks מדבר על העתיד: 'בעוד שבועיים'.",
        "שים לב לשילוב: כשמוסיפים יום לחלק של היום, on מנצח: in the morning אבל on Monday morning. וכן at night אבל in the evening.",
      ],
      form: [
        { label: "at + שעה / נקודה בזמן", example: "The movie starts at eight." },
        { label: "on + יום / תאריך", example: "See you on Monday." },
        { label: "in + חודש / שנה / עונה / חלק ביום", example: "I was born in 1995." },
        { label: "at + מקום כנקודה", example: "She's at work. Wait at the door." },
        { label: "on + משטח / קו / כלי תחבורה ציבורי", example: "Your keys are on the table." },
        { label: "in + מקום סגור / עיר / מדינה", example: "They live in Haifa." },
      ],
      examples: [
        { en: "The movie starts at eight o'clock.", he: "הסרט מתחיל בשמונה." },
        { en: "See you on Monday morning.", he: "נתראה ביום שני בבוקר." },
        { en: "I was born in Haifa in 1995.", he: "נולדתי בחיפה ב-1995." },
        { en: "Sorry, I can't talk — I'm at work.", he: "סליחה, אני לא יכול לדבר, אני בעבודה." },
        { en: "I met her on the bus this morning.", he: "פגשתי אותה באוטובוס הבוקר." },
        { en: "Who's the girl in this picture?", he: "מי הבחורה בתמונה הזאת?" },
        { en: "It gets really cold here at night.", he: "נהיה כאן ממש קר בלילה." },
        { en: "Please try to be on time tomorrow.", he: "תשתדל להגיע בזמן מחר." },
      ],
      contrastHe: [
        "'בבית' זה at home, לא in home ולא in the home. באותו אופן: at work, at school – בלי the.",
        "'באוטובוס' ו'ברכבת' הם on the bus / on the train, אבל 'באוטו' הוא in the car. זה נראה הפוך מההיגיון, וצריך פשוט לשנן.",
        "'בתמונה' זה in the picture. דוברי עברית אומרים on the picture בהשפעת 'על' – זה נשמע כאילו מישהו עומד מעל התמונה.",
        "'בזמן' זה on time. in time הוא משהו אחר: מספיק מוקדם בשביל משהו. We came in time for the movie.",
      ],
      commonErrors: [
        { wrong: "I'm in home right now.", right: "I'm at home right now.", whyHe: "'בבית' = at home. אין in home באנגלית." },
        { wrong: "We sat in the train for two hours.", right: "We sat on the train for two hours.", whyHe: "בתחבורה ציבורית משתמשים ב-on: on the train, on the bus." },
        { wrong: "The class starts in 9:00.", right: "The class starts at 9:00.", whyHe: "שעה מדויקת מקבלת at." },
        { wrong: "I live in Ben Gurion Street.", right: "I live on Ben Gurion Street.", whyHe: "רחוב הוא קו: on Ben Gurion Street (בעיר: in Tel Aviv)." },
        { wrong: "Who is on this picture?", right: "Who is in this picture?", whyHe: "בתוך תמונה או צילום: in the picture." },
        { wrong: "I have a meeting in Monday morning.", right: "I have a meeting on Monday morning.", whyHe: "כשמצוין יום מסוים, on מנצח – גם עם morning." },
      ],
    },
    items: [
      { id: "g-prepositions-time-place-01", type: "gap", prompt: "I was born ___ 1995. (in / on / at)", answer: "in", explainHe: "שנה מקבלת in: in 1995." },
      { id: "g-prepositions-time-place-02", type: "gap", prompt: "See you ___ Monday. (in / on / at)", answer: "on", explainHe: "יום בשבוע מקבל on: on Monday." },
      { id: "g-prepositions-time-place-03", type: "gap", prompt: "The movie starts ___ eight o'clock. (in / on / at)", answer: "at", explainHe: "שעה מדויקת מקבלת at: at eight." },
      { id: "g-prepositions-time-place-04", type: "gap", prompt: "I met her ___ the bus this morning. (in / on / at)", answer: "on", explainHe: "בתחבורה ציבורית: on the bus." },
      { id: "g-prepositions-time-place-05", type: "gap", prompt: "She isn't here. She's ___ work today. (in / on / at)", answer: "at", explainHe: "'בעבודה' = at work, בלי the." },
      { id: "g-prepositions-time-place-06", type: "gap", prompt: "It gets really cold here ___ night. (in / on / at)", answer: "at", explainHe: "at night הוא צירוף קבוע (אבל in the evening)." },
      { id: "g-prepositions-time-place-07", type: "gap", prompt: "Who's the girl ___ this picture? (in / on / at)", answer: "in", explainHe: "'בתמונה' = in the picture, לא on." },
      { id: "g-prepositions-time-place-08", type: "gap", prompt: "We're moving to a new office ___ August. (in / on / at)", answer: "in", explainHe: "חודש מקבל in: in August." },
      {
        id: "g-prepositions-time-place-09",
        type: "mcq",
        prompt: "I'll be ___ all evening, so just call me.",
        options: [
          { text: "at home" },
          { text: "in home", errorType: "preposition", whyHe: "תרגום ישיר של 'בבית'. הצירוף הנכון הוא at home." },
          { text: "at the home", errorType: "article", whyHe: "at home הוא צירוף קבוע בלי the (the home = מוסד לקשישים)." },
          { text: "in the home", errorType: "preposition", whyHe: "נשמע כמו מוסד, לא כמו הבית שלך." },
        ],
        answerIndex: 0,
        explainHe: "'אני בבית' = I'm at home – צירוף קבוע בלי the.",
      },
      {
        id: "g-prepositions-time-place-10",
        type: "mcq",
        prompt: "There were no free seats ___ this morning.",
        options: [
          { text: "on the bus" },
          { text: "in the bus", errorType: "preposition", whyHe: "'באוטובוס' הוא on the bus. in the bus נשמע כאילו אתה חלק מהמנוע." },
          { text: "at the bus", errorType: "preposition", whyHe: "at the bus stop זו תחנה, לא האוטובוס עצמו." },
          { text: "on bus", errorType: "article", whyHe: "חסר the: on the bus." },
        ],
        answerIndex: 0,
        explainHe: "תחבורה ציבורית: on the bus / on the train / on a plane.",
      },
      {
        id: "g-prepositions-time-place-11",
        type: "mcq",
        prompt: "The meeting starts at nine, so please be ___.",
        options: [
          { text: "on time" },
          { text: "in time", errorType: "word-choice", whyHe: "in time = מספיק מוקדם בשביל משהו. 'לא לאחר' זה on time." },
          { text: "at time", errorType: "preposition", whyHe: "אין צירוף כזה באנגלית." },
          { text: "in the time", errorType: "preposition", whyHe: "in the time פירושו משהו אחר לגמרי, ולא מתאים כאן." },
        ],
        answerIndex: 0,
        explainHe: "'להגיע בזמן' = to be on time.",
      },
      {
        id: "g-prepositions-time-place-12",
        type: "mcq",
        prompt: "I have a meeting ___ Monday morning.",
        options: [
          { text: "on" },
          { text: "in", errorType: "preposition", whyHe: "in the morning נכון, אבל כשמצוין היום עוברים ל-on Monday morning." },
          { text: "at", errorType: "preposition", whyHe: "at שמור לשעות ולנקודות זמן, לא לימים." },
          { text: "in the", errorType: "preposition", whyHe: "לא אומרים in the Monday morning." },
        ],
        answerIndex: 0,
        explainHe: "יום + חלק מהיום → on: on Monday morning.",
      },
      {
        id: "g-prepositions-time-place-13",
        type: "mcq",
        prompt: "Don't worry, I'll finish the report ___ two weeks.",
        options: [
          { text: "in" },
          { text: "on", errorType: "preposition", whyHe: "on מתאים לימים ותאריכים, לא למשך זמן." },
          { text: "at", errorType: "preposition", whyHe: "at מתאים לשעה מדויקת." },
          { text: "during", errorType: "word-choice", whyHe: "during two weeks אינו טבעי. 'בעוד שבועיים' = in two weeks." },
        ],
        answerIndex: 0,
        explainHe: "'בעוד שבועיים' (מתי זה יקרה) = in two weeks.",
      },
      { id: "g-prepositions-time-place-14", type: "fix", prompt: "I live in Tel Aviv, in Ben Gurion Street.", answer: "I live in Tel Aviv, on Ben Gurion Street.", errorType: "preposition", explainHe: "עיר מקבלת in, אבל רחוב מקבל on." },
      { id: "g-prepositions-time-place-15", type: "fix", prompt: "I'm in home right now.", answer: "I'm at home right now.", errorType: "preposition", explainHe: "'בבית' = at home." },
      { id: "g-prepositions-time-place-16", type: "fix", prompt: "We sat in the train for two hours.", answer: "We sat on the train for two hours.", errorType: "preposition", explainHe: "ברכבת ובאוטובוס משתמשים ב-on." },
      { id: "g-prepositions-time-place-17", type: "fix", prompt: "The class starts in 9:00.", answer: "The class starts at 9:00.", errorType: "preposition", explainHe: "שעה מדויקת: at 9:00." },
      { id: "g-prepositions-time-place-18", type: "fix", prompt: "Who is on this picture?", answer: "Who is in this picture?", errorType: "preposition", explainHe: "בתוך תמונה: in the picture." },
      { id: "g-prepositions-time-place-19", type: "transform", prompt: "I'll see you when the weekend comes.", keyword: "on", answer: "I'll see you on the weekend.", accept: ["I'll see you at the weekend."], explainHe: "באנגלית אמריקאית on the weekend (ובריטית at the weekend)." },
      { id: "g-prepositions-time-place-20", type: "transform", prompt: "I'm staying in my house today.", keyword: "at", answer: "I'm staying at home today.", explainHe: "'נשאר בבית' = stay at home, בלי the ובלי in." },
      { id: "g-prepositions-time-place-21", type: "order", words: ["at", "meet", "let's", "eight", "on", "Monday"], answer: "Let's meet at eight on Monday.", explainHe: "שעה עם at, יום עם on. סדר טבעי: שעה ואז יום." },
      { id: "g-prepositions-time-place-22", type: "order", words: ["on", "the", "the", "I", "left", "keys", "table"], answer: "I left the keys on the table.", explainHe: "משטח מקבל on: on the table." },
      { id: "g-prepositions-time-place-23", type: "translate", he: "אני בבית עכשיו.", answer: "I'm at home now.", accept: ["I'm at home right now."], explainHe: "'בבית' = at home, לא in home." },
      { id: "g-prepositions-time-place-24", type: "translate", he: "נתראה ביום שני בשמונה.", answer: "See you on Monday at eight.", accept: ["See you at eight on Monday.", "See you on Monday at 8."], explainHe: "יום עם on, שעה עם at." },
    ],
  },
  // ------------------------------------------------------------------
  // 36. Dependent prepositions
  // ------------------------------------------------------------------
  {
    id: "g-dependent-prepositions",
    title: "Dependent prepositions (depend on, good at, listen to...)",
    titleHe: "מילות יחס תלויות",
    strand: "prepositions",
    order: 36,
    prereqs: ["g-prepositions-time-place"],
    lesson: {
      explanationHe: [
        "הרבה פעלים ושמות תואר באנגלית 'נולדו' עם מילת יחס קבועה: depend on, listen to, good at, afraid of. מילת היחס היא חלק מהמילה, ולא משהו שבוחרים לפי היגיון.",
        "הבעיה לדוברי עברית היא שמילת היחס העברית כמעט אף פעם לא זהה: 'תלוי ב־' הופך ל-on, 'מפחד מ־' הופך ל-of, 'טוב ב־' הופך ל-at, 'נשוי ל־' הופך ל-to. תרגום ישיר כמעט תמיד ייתן שגיאה.",
        "פעלים שכדאי לשנן: depend on, listen to, wait for, look for (לחפש), look at (להסתכל), belong to, apologize for, pay for, ask for, think about / think of, arrive at (מקום קטן) / arrive in (עיר או מדינה), explain something to someone.",
        "שמות תואר שכדאי לשנן: good at / bad at, interested in, afraid of, angry with someone (אבל angry about something), worried about, married to, proud of, similar to, different from.",
        "יש גם מקרה הפוך: פעלים שבעברית דורשים מילת יחס ובאנגלית לא. discuss something (לדון ב־), answer the question (לענות על), call me (להתקשר ל־), enter the room (להיכנס ל־). הוספת מילת יחס שם היא שגיאה.",
        "טיפ מעשי: כשלומדים מילה חדשה, לומדים אותה יחד עם מילת היחס שלה ובמשפט שלם – depend on the weather, good at math – ולא כשתי מילים נפרדות.",
      ],
      form: [
        { label: "פועל + מילת יחס", example: "It depends on the weather." },
        { label: "שם תואר + מילת יחס", example: "She's good at math." },
        { label: "arrive at (מקום) / arrive in (עיר)", example: "We arrived at the airport." },
        { label: "explain / say + to somebody", example: "Can you explain it to me?" },
        { label: "בלי מילת יחס: discuss, answer, call", example: "We discussed the price." },
        { label: "think about (לשקול) / think of (רעיון)", example: "I'm thinking about a new job." },
      ],
      examples: [
        { en: "It depends on the weather.", he: "זה תלוי במזג האוויר." },
        { en: "I like listening to music while I work.", he: "אני אוהב להקשיב למוזיקה בזמן העבודה." },
        { en: "She's really good at math.", he: "היא ממש טובה במתמטיקה." },
        { en: "My sister is married to a teacher.", he: "אחותי נשואה למורה." },
        { en: "We arrived at the airport at six.", he: "הגענו לשדה התעופה בשש." },
        { en: "Don't be angry with me, it wasn't my fault.", he: "אל תכעס עליי, זו לא הייתה אשמתי." },
        { en: "Can you explain the rules to me?", he: "אתה יכול להסביר לי את הכללים?" },
        { en: "We discussed the price for an hour.", he: "דנו במחיר במשך שעה." },
      ],
      contrastHe: [
        "'תלוי ב־' הופך ל-depend on, אף פעם לא depend of או depend in. וזכור: It depends, בלי on, כשאין המשך.",
        "'לשמוע מוזיקה' באנגלית הוא listen to music. דוברי עברית משמיטים את to ואומרים listen music, או מבלבלים עם hear.",
        "'מפחד מ־' הופך ל-afraid of, לא afraid from. באותו אופן 'שונה מ־' הוא different from, ו'טוב ב־' הוא good at.",
        "'להגיע ל־' אף פעם לא arrive to. אומרים arrive at the station (מקום מסוים) או arrive in Tel Aviv (עיר), וגם get to.",
      ],
      commonErrors: [
        { wrong: "I arrived to Tel Aviv at nine.", right: "I arrived in Tel Aviv at nine.", whyHe: "arrive to לא קיים. לעיר: arrive in, למקום מסוים: arrive at." },
        { wrong: "He is married with a doctor.", right: "He is married to a doctor.", whyHe: "'נשוי ל־' = married to. with נשמע כאילו התחתנו יחד עם מישהו שלישי." },
        { wrong: "We discussed about the price.", right: "We discussed the price.", whyHe: "discuss לא לוקח מילת יחס. עם talk כן: talk about the price." },
        { wrong: "I'm looking my keys.", right: "I'm looking for my keys.", whyHe: "'לחפש' = look for. בלי for זה סתם 'מסתכל'." },
        { wrong: "Can you explain me this word?", right: "Can you explain this word to me?", whyHe: "explain תמיד מוסר את המידע ל-somebody: explain something to me." },
        { wrong: "She's very good in her job.", right: "She's very good at her job.", whyHe: "'טוב ב־' = good at, לא good in." },
      ],
    },
    items: [
      { id: "g-dependent-prepositions-01", type: "gap", prompt: "It depends ___ the weather.", answer: "on", hint: "תלוי ב־", explainHe: "depend on – מילת היחס הקבועה של הפועל, לא of." },
      { id: "g-dependent-prepositions-02", type: "gap", prompt: "She's really good ___ math.", answer: "at", explainHe: "'טוב ב־' = good at, לא good in." },
      { id: "g-dependent-prepositions-03", type: "gap", prompt: "I'm waiting ___ the bus.", answer: "for", explainHe: "'לחכות ל־' = wait for." },
      { id: "g-dependent-prepositions-04", type: "gap", prompt: "My sister is married ___ a teacher.", answer: "to", explainHe: "'נשוי ל־' = married to, לא with." },
      { id: "g-dependent-prepositions-05", type: "gap", prompt: "We arrived ___ the airport at six.", answer: "at", explainHe: "arrive at + מקום מסוים. לעולם לא arrive to." },
      { id: "g-dependent-prepositions-06", type: "gap", prompt: "I'm not really interested ___ politics.", answer: "in", explainHe: "'מתעניין ב־' = interested in." },
      { id: "g-dependent-prepositions-07", type: "gap", prompt: "Don't be angry ___ me, it wasn't my fault.", answer: "with", explainHe: "כועסים על אדם: angry with somebody (ועל דבר: angry about something)." },
      { id: "g-dependent-prepositions-08", type: "gap", prompt: "Who does this umbrella belong ___?", answer: "to", explainHe: "'שייך ל־' = belong to, וה-to נשאר בסוף השאלה." },
      {
        id: "g-dependent-prepositions-09",
        type: "mcq",
        prompt: "I love ___ music while I work.",
        options: [
          { text: "listening to" },
          { text: "listening", errorType: "preposition", whyHe: "'לשמוע מוזיקה' בעברית בלי מילת יחס, אבל listen תמיד דורש to." },
          { text: "listening at", errorType: "preposition", whyHe: "listen at אינו קיים. מילת היחס של listen היא to." },
          { text: "hearing to", errorType: "word-choice", whyHe: "hear הוא לשמוע במקרה ואינו לוקח to. כאן צריך listen to." },
        ],
        answerIndex: 0,
        explainHe: "listen to music – ה-to הוא חלק מהפועל.",
      },
      {
        id: "g-dependent-prepositions-10",
        type: "mcq",
        prompt: "Everything depends ___ you now.",
        options: [
          { text: "on" },
          { text: "of", errorType: "preposition", whyHe: "depend of אינו קיים באנגלית, למרות שזה נשמע הגיוני." },
          { text: "in", errorType: "preposition", whyHe: "תרגום ישיר של 'תלוי ב־'. הצורה הנכונה היא depend on." },
          { text: "from", errorType: "preposition", whyHe: "depend from אינו קיים. תמיד depend on." },
        ],
        answerIndex: 0,
        explainHe: "depend on somebody / something – צירוף קבוע.",
      },
      {
        id: "g-dependent-prepositions-11",
        type: "mcq",
        prompt: "Are you afraid ___ dogs?",
        options: [
          { text: "of" },
          { text: "from", errorType: "interference", whyHe: "תרגום ישיר של 'מפחד מ־'. באנגלית afraid of." },
          { text: "about", errorType: "preposition", whyHe: "worried about נכון, אבל afraid דורש of." },
          { text: "at", errorType: "preposition", whyHe: "afraid at אינו קיים." },
        ],
        answerIndex: 0,
        explainHe: "afraid of – אחת השגיאות הנפוצות ביותר של דוברי עברית.",
      },
      {
        id: "g-dependent-prepositions-12",
        type: "mcq",
        prompt: "Can you ___ how this machine works?",
        options: [
          { text: "explain to me" },
          { text: "explain me", errorType: "interference", whyHe: "'תסביר לי' מתורגם ישירות, אבל explain דורש to לפני האדם." },
          { text: "explain for me", errorType: "preposition", whyHe: "explain for me נשמע כאילו מישהו מסביר במקומך. צריך to." },
          { text: "explain at me", errorType: "preposition", whyHe: "explain at אינו קיים." },
        ],
        answerIndex: 0,
        explainHe: "explain something to somebody – ההסבר נמסר למישהו: Can you explain it to me?",
      },
      {
        id: "g-dependent-prepositions-13",
        type: "mcq",
        prompt: "We need to ___ the price with the boss.",
        options: [
          { text: "discuss" },
          { text: "discuss about", errorType: "preposition", whyHe: "'לדון ב־' מתורגם עם about, אבל discuss לא לוקח מילת יחס." },
          { text: "discuss on", errorType: "preposition", whyHe: "discuss on אינו קיים." },
          { text: "talk", errorType: "word-choice", whyHe: "talk דורש about: talk about the price." },
        ],
        answerIndex: 0,
        explainHe: "discuss something – ישר אל המושא, בלי מילת יחס.",
      },
      { id: "g-dependent-prepositions-14", type: "fix", prompt: "I arrived to Tel Aviv at nine.", answer: "I arrived in Tel Aviv at nine.", errorType: "preposition", explainHe: "לעיר: arrive in. arrive to אינו קיים." },
      { id: "g-dependent-prepositions-15", type: "fix", prompt: "He is married with a doctor.", answer: "He is married to a doctor.", errorType: "preposition", explainHe: "'נשוי ל־' = married to." },
      { id: "g-dependent-prepositions-16", type: "fix", prompt: "We discussed about the price for an hour.", answer: "We discussed the price for an hour.", errorType: "preposition", explainHe: "discuss לא לוקח about." },
      { id: "g-dependent-prepositions-17", type: "fix", prompt: "I'm looking my keys everywhere.", answer: "I'm looking for my keys everywhere.", errorType: "preposition", explainHe: "'לחפש' = look for." },
      { id: "g-dependent-prepositions-18", type: "fix", prompt: "She apologized about the mistake.", answer: "She apologized for the mistake.", errorType: "preposition", explainHe: "'להתנצל על' = apologize for." },
      { id: "g-dependent-prepositions-19", type: "transform", prompt: "The trip isn't certain — the weather will decide.", keyword: "depends", answer: "The trip depends on the weather.", explainHe: "depend on – מילת היחס היא חלק מהפועל." },
      { id: "g-dependent-prepositions-20", type: "transform", prompt: "He plays the guitar very well.", keyword: "good at", answer: "He's good at playing the guitar.", accept: ["He is very good at playing the guitar."], explainHe: "good at + פועל ב-ing: good at playing." },
      { id: "g-dependent-prepositions-21", type: "order", words: ["depends", "it", "on", "you"], answer: "It depends on you.", explainHe: "depend on somebody – צירוף קבוע." },
      { id: "g-dependent-prepositions-22", type: "order", words: ["for", "waiting", "I'm", "my", "sister"], answer: "I'm waiting for my sister.", explainHe: "wait for somebody – ה-for חובה." },
      { id: "g-dependent-prepositions-23", type: "translate", he: "זה תלוי במזג האוויר.", answer: "It depends on the weather.", explainHe: "'תלוי ב־' = depend on." },
      { id: "g-dependent-prepositions-24", type: "translate", he: "אני מחכה לחבר שלי.", answer: "I'm waiting for my friend.", explainHe: "'מחכה ל־' = wait for." },
    ],
  },
];
