import type { GrammarTopic } from "@/lib/types";

export const TENSES: GrammarTopic[] = [
  // ---------------------------------------------------------------------------
  // 1. Present simple vs present continuous
  // ---------------------------------------------------------------------------
  {
    id: "g-present-simple-continuous",
    title: "Present simple vs present continuous",
    titleHe: "הווה פשוט מול הווה ממושך",
    strand: "tenses",
    order: 1,
    prereqs: [],
    lesson: {
      explanationHe: [
        "בעברית יש הווה אחד: 'אני עובד'. באנגלית יש שניים, וההבדל ביניהם הוא במשמעות, לא בזמן. Present Simple מתאר דברים קבועים: הרגלים, שגרה, עובדות ומצבים כלליים. Present Continuous מתאר משהו שקורה ממש עכשיו, או מצב זמני שנמשך בתקופה הזאת.",
        "שאלו את עצמכם: זה 'בדרך כלל' או 'עכשיו'? 'I work in Haifa' = זה מקום העבודה שלי בכלל. 'I'm working from home this week' = מצב זמני, רק השבוע. Present Continuous מתאים גם לשינויים ומגמות: 'More people are working from home these days'.",
        "הצורה של Present Simple: הפועל הבסיסי, ובגוף שלישי יחיד (he/she/it) מוסיפים s. שלילה ושאלה בעזרת do/does: 'She doesn't like fish', 'Does he work here?'. שימו לב: אחרי does הפועל חוזר לצורה הבסיסית, בלי s.",
        "הצורה של Present Continuous: am/is/are + פועל עם ing. השלילה נכנסת אחרי be: 'I'm not working'. בשאלה be עובר לפני הנושא: 'Are you listening?'.",
        "מילות סימן עוזרות: always, usually, often, never, every day, on Fridays מכוונות ל-Present Simple. now, right now, at the moment, today, these days, Look! Listen! מכוונות ל-Present Continuous.",
      ],
      form: [
        { label: "Present simple (+)", example: "I / you / we / they work — he / she / it works" },
        { label: "Present simple (-)", example: "I don't work — she doesn't work" },
        { label: "Present simple (?)", example: "Do you work? — Does she work?" },
        { label: "Present continuous (+)", example: "I am working — he is working — they are working" },
        { label: "Present continuous (-)", example: "I'm not working — she isn't working" },
        { label: "Present continuous (?)", example: "Are you working? — Is he working?" },
      ],
      examples: [
        { en: "I usually take the bus to work.", he: "אני בדרך כלל נוסע לעבודה באוטובוס." },
        { en: "I'm taking a taxi today because it's raining.", he: "היום אני נוסע במונית כי יורד גשם." },
        { en: "My brother lives in Beersheba.", he: "אחי גר בבאר שבע." },
        { en: "He's living with friends until he finds an apartment.", he: "הוא גר אצל חברים עד שימצא דירה." },
        { en: "Does she work on Fridays?", he: "היא עובדת בימי שישי?" },
        { en: "Be quiet, the kids are sleeping.", he: "בשקט, הילדים ישנים." },
        { en: "The sun rises in the east.", he: "השמש זורחת במזרח." },
        { en: "Prices are going up these days.", he: "המחירים עולים בתקופה הזאת." },
      ],
      contrastHe: [
        "בעברית 'אני קורא ספר' יכול להיות גם הרגל וגם עכשיו. באנגלית חייבים לבחור: 'I read books' (בכלל) או 'I'm reading a book' (עכשיו).",
        "בעברית אין מילת עזר בשאלה: 'את עובדת פה?'. באנגלית חייבים do/does: 'Do you work here?'. הטעות 'You work here?' נשמעת כמו הפתעה, לא כמו שאלה רגילה.",
        "דוברי עברית נוטים לומר 'I am work' – תערובת של שתי הצורות. או be + ing, או פועל בלי be. אף פעם לא be + פועל בסיסי.",
      ],
      commonErrors: [
        { wrong: "I am work in a bank.", right: "I work in a bank.", whyHe: "עובדה קבועה = Present Simple, בלי am." },
        { wrong: "He don't like coffee.", right: "He doesn't like coffee.", whyHe: "גוף שלישי יחיד: doesn't." },
        { wrong: "She is going to the gym every day.", right: "She goes to the gym every day.", whyHe: "every day = הרגל = Present Simple." },
        { wrong: "Now I read a book.", right: "Now I'm reading a book.", whyHe: "עכשיו, בזמן הדיבור = Present Continuous." },
        { wrong: "You like pizza?", right: "Do you like pizza?", whyHe: "שאלה ב-Present Simple דורשת do/does." },
        { wrong: "Does she works here?", right: "Does she work here?", whyHe: "אחרי does הפועל בצורה הבסיסית, ה-s כבר נמצאת ב-does." },
      ],
    },
    items: [
      { id: "g-present-simple-continuous-01", type: "gap", prompt: "My sister ___ (work) at a hospital in Haifa.", answer: "works", explainHe: "עובדה קבועה על מקום העבודה שלה: Present Simple, ובגוף שלישי מוסיפים s." },
      { id: "g-present-simple-continuous-02", type: "gap", prompt: "Be quiet! The baby ___ (sleep).", answer: "is sleeping", explainHe: "זה קורה ממש עכשיו: is + sleeping." },
      { id: "g-present-simple-continuous-03", type: "gap", prompt: "We usually ___ (eat) dinner at seven.", answer: "eat", explainHe: "usually = הרגל = Present Simple. we לא מקבל s." },
      { id: "g-present-simple-continuous-04", type: "gap", prompt: "I ___ (not/watch) TV these days. I'm too busy.", answer: "am not watching", accept: ["'m not watching"], explainHe: "these days = מצב זמני בתקופה הזאת = Present Continuous בשלילה: am not watching." },
      { id: "g-present-simple-continuous-05", type: "gap", prompt: "___ (your brother/play) tennis every weekend?", answer: "Does your brother play", explainHe: "שאלה על הרגל (every weekend): Does + נושא + פועל בסיסי." },
      { id: "g-present-simple-continuous-06", type: "gap", prompt: "Look! It ___ (snow)!", answer: "is snowing", explainHe: "Look! מסמן משהו שקורה עכשיו מול העיניים: is snowing." },
      { id: "g-present-simple-continuous-07", type: "gap", prompt: "Dan ___ (stay) with his parents until his apartment is ready.", answer: "is staying", explainHe: "מצב זמני (עד שהדירה תהיה מוכנה) = Present Continuous." },
      { id: "g-present-simple-continuous-08", type: "gap", prompt: "Water ___ (boil) at 100 degrees.", answer: "boils", explainHe: "עובדה מדעית שתמיד נכונה: Present Simple עם s." },
      {
        id: "g-present-simple-continuous-09", type: "mcq", prompt: "Sorry, I can't talk now. I ___ dinner.",
        options: [
          { text: "am cooking" },
          { text: "cook", errorType: "aspect", whyHe: "'cook' אומר שאני מבשל בכלל, כהרגל. כאן זה קורה עכשיו." },
          { text: "cooking", errorType: "verb-form", whyHe: "חסר הפועל be: am cooking." },
          { text: "am cook", errorType: "verb-form", whyHe: "אחרי am חייב לבוא ing: am cooking." },
        ],
        answerIndex: 0, explainHe: "now + פעולה שמתרחשת ברגע הדיבור = am + ing.",
      },
      {
        id: "g-present-simple-continuous-10", type: "mcq", prompt: "How often ___ to the gym?",
        options: [
          { text: "do you go" },
          { text: "are you going", errorType: "aspect", whyHe: "How often שואל על תדירות/הרגל, לא על עכשיו." },
          { text: "you go", errorType: "question-form", whyHe: "בשאלה ב-Present Simple חייבים do." },
          { text: "you are going", errorType: "question-form", whyHe: "זה סדר של משפט חיווי, לא של שאלה, וגם הזמן לא מתאים." },
        ],
        answerIndex: 0, explainHe: "How often = תדירות = Present Simple, ושאלה דורשת do + נושא + פועל.",
      },
      {
        id: "g-present-simple-continuous-11", type: "mcq", prompt: "The store ___ at 9 every morning.",
        options: [
          { text: "opens" },
          { text: "is opening", errorType: "aspect", whyHe: "every morning = שגרה קבועה, לא משהו שקורה עכשיו." },
          { text: "open", errorType: "agreement", whyHe: "The store = it, צריך s: opens." },
          { text: "opening", errorType: "verb-form", whyHe: "צורת ing לבד אינה פועל במשפט." },
        ],
        answerIndex: 0, explainHe: "שגרה + גוף שלישי יחיד = opens.",
      },
      {
        id: "g-present-simple-continuous-12", type: "mcq", prompt: "More and more people ___ from home these days.",
        options: [
          { text: "are working" },
          { text: "work", errorType: "aspect", whyHe: "'more and more' + 'these days' מתארים שינוי בתקופה הזאת: Present Continuous." },
          { text: "works", errorType: "agreement", whyHe: "people = רבים, אין s. וגם הזמן לא מתאים." },
          { text: "working", errorType: "verb-form", whyHe: "חסר are לפני working." },
        ],
        answerIndex: 0, explainHe: "מגמה שמשתנה בתקופה הנוכחית = Present Continuous.",
      },
      {
        id: "g-present-simple-continuous-13", type: "mcq", prompt: "I ___ coffee, but this week I'm drinking tea.",
        options: [
          { text: "don't usually drink" },
          { text: "am not usually drinking", errorType: "aspect", whyHe: "usually = הרגל = Present Simple. ההמשך 'this week' הוא הזמני." },
          { text: "not drink usually", errorType: "verb-form", whyHe: "שלילה ב-Present Simple דורשת don't." },
          { text: "don't drinking", errorType: "verb-form", whyHe: "אחרי don't בא פועל בסיסי, לא ing." },
        ],
        answerIndex: 0, explainHe: "הניגוד: בדרך כלל (Simple) מול השבוע (Continuous).",
      },
      { id: "g-present-simple-continuous-14", type: "fix", prompt: "I am work in Tel Aviv.", answer: "I work in Tel Aviv.", errorType: "verb-form", explainHe: "עובדה קבועה: Present Simple בלי am. 'am work' היא תערובת של שתי הצורות." },
      { id: "g-present-simple-continuous-15", type: "fix", prompt: "He don't like fish.", answer: "He doesn't like fish.", errorType: "agreement", explainHe: "he/she/it בשלילה: doesn't." },
      { id: "g-present-simple-continuous-16", type: "fix", prompt: "She is going to the gym every day.", answer: "She goes to the gym every day.", errorType: "aspect", explainHe: "every day = הרגל = Present Simple." },
      { id: "g-present-simple-continuous-17", type: "fix", prompt: "Right now I read a good book.", answer: "Right now I am reading a good book.", errorType: "aspect", explainHe: "right now = בזמן הדיבור = Present Continuous." },
      { id: "g-present-simple-continuous-18", type: "transform", prompt: "She works at night.", keyword: "Does", answer: "Does she work at night?", explainHe: "שאלה ב-Present Simple: Does + she + פועל בסיסי (בלי s)." },
      { id: "g-present-simple-continuous-19", type: "transform", prompt: "They are watching a movie.", keyword: "What", answer: "What are they watching?", explainHe: "מילת שאלה + are + נושא + ing." },
      { id: "g-present-simple-continuous-20", type: "transform", prompt: "He lives in Haifa.", keyword: "not", answer: "He does not live in Haifa.", accept: ["He doesn't live in Haifa."], explainHe: "שלילה: does not + פועל בסיסי. ה-s עוברת מ-lives ל-does." },
      { id: "g-present-simple-continuous-21", type: "order", words: ["why", "is", "she", "crying?"], answer: "Why is she crying?", explainHe: "מילת שאלה, אחר כך is, אחר כך הנושא, ואז הפועל עם ing." },
      { id: "g-present-simple-continuous-22", type: "order", words: ["my", "dad", "never", "eats", "meat"], answer: "My dad never eats meat.", explainHe: "never נכנס לפני הפועל הראשי, והפועל מקבל s כי dad = he." },
      { id: "g-present-simple-continuous-23", type: "translate", he: "אני לומד אנגלית עכשיו.", answer: "I am learning English now.", accept: ["I am studying English now.", "Now I am learning English.", "Now I am studying English."], explainHe: "עכשיו = Present Continuous: am + ing. 'I learn English now' נשמע כמו הרגל." },
      { id: "g-present-simple-continuous-24", type: "translate", he: "היא לא אוכלת בשר.", answer: "She doesn't eat meat.", explainHe: "עובדה כללית עליה: Present Simple בשלילה עם doesn't." },
    ],
  },

  // ---------------------------------------------------------------------------
  // 2. Past simple
  // ---------------------------------------------------------------------------
  {
    id: "g-past-simple",
    title: "Past simple (regular & irregular)",
    titleHe: "עבר פשוט",
    strand: "tenses",
    order: 2,
    prereqs: [],
    lesson: {
      explanationHe: [
        "Past Simple הוא הזמן של סיפורים ושל עובדות מהעבר: משהו קרה, נגמר, ואנחנו יודעים (או מרגישים) מתי. 'I went to the beach yesterday', 'She bought a car last week'. זה הזמן הכי קרוב לעבר העברי, ובדרך כלל הוא התרגום הנכון של 'הלכתי', 'קניתי', 'ראיתי'.",
        "פעלים רגילים מקבלים ed: work → worked, stop → stopped, study → studied. פעלים לא רגילים צריך פשוט לזכור: go → went, buy → bought, see → saw, have → had. הצורה זהה לכל הגופים: I went, she went, they went.",
        "השלילה והשאלה נבנות עם did, וזה החלק שדוברי עברית הכי מפספסים: אחרי did הפועל חוזר לצורה הבסיסית. 'I didn't go' (לא 'didn't went'), 'Did you see?' (לא 'Did you saw?'). ה-did כבר נושא את העבר, הפועל לא צריך לשאת אותו שוב.",
        "הפועל be הוא יוצא דופן: was/were, ובלי did. 'I was tired', 'Were you there?', 'It wasn't cold'.",
        "מילות סימן: yesterday, last night, last year, two days ago, in 2015, when I was a child. אם יש במשפט זמן שנגמר – Past Simple.",
      ],
      form: [
        { label: "רגיל (+)", example: "I worked / she played / we stopped / he studied" },
        { label: "לא רגיל (+)", example: "I went / she bought / they saw / he had" },
        { label: "שלילה", example: "I didn't go — she didn't buy — we didn't have" },
        { label: "שאלה", example: "Did you go? — Did she buy it? — When did they arrive?" },
        { label: "be", example: "I was / you were / he was / they were — Was it good? — I wasn't there" },
      ],
      examples: [
        { en: "I went to the beach yesterday.", he: "הלכתי לים אתמול." },
        { en: "She bought a new phone two days ago.", he: "היא קנתה טלפון חדש לפני יומיים." },
        { en: "We didn't have time to finish.", he: "לא היה לנו זמן לסיים." },
        { en: "Did you see the game last night?", he: "ראית את המשחק אתמול בערב?" },
        { en: "Where did they go on vacation?", he: "לאן הם נסעו בחופשה?" },
        { en: "The meeting was long and boring.", he: "הפגישה הייתה ארוכה ומשעממת." },
        { en: "He studied medicine in Italy in the nineties.", he: "הוא למד רפואה באיטליה בשנות התשעים." },
      ],
      contrastHe: [
        "בעברית השלילה בעבר פשוטה: 'לא הלכתי'. באנגלית צריך את did: 'I didn't go'. הפועל אחרי did תמיד בצורה הבסיסית.",
        "בעברית שאלה בעבר היא רק אינטונציה: 'ראית?'. באנגלית: 'Did you see?'. בלי did זה נשמע כמו הפתעה או חוסר ידע בשפה.",
        "'לפני שנתיים' = 'two years ago', לא 'before two years'. ago תמיד בא אחרי משך הזמן.",
      ],
      commonErrors: [
        { wrong: "I didn't went to work.", right: "I didn't go to work.", whyHe: "אחרי didn't הפועל בצורה הבסיסית. did כבר מסמן עבר." },
        { wrong: "Did you saw the news?", right: "Did you see the news?", whyHe: "אותו כלל בשאלה: Did + פועל בסיסי." },
        { wrong: "She was call me last night.", right: "She called me last night.", whyHe: "עבר פשוט לא משתמש ב-was + פועל. was רק עם ing או עם שם תואר." },
        { wrong: "We eated pizza.", right: "We ate pizza.", whyHe: "eat הוא פועל לא רגיל: ate." },
        { wrong: "I came here before two years.", right: "I came here two years ago.", whyHe: "'לפני X זמן' = X ago." },
      ],
    },
    items: [
      { id: "g-past-simple-01", type: "gap", prompt: "Yesterday I ___ (go) to the beach.", answer: "went", explainHe: "yesterday = עבר פשוט. go הוא פועל לא רגיל: went." },
      { id: "g-past-simple-02", type: "gap", prompt: "We ___ (not/have) time to finish the project last week.", answer: "didn't have", explainHe: "שלילה בעבר: didn't + פועל בסיסי. לא 'didn't had'." },
      { id: "g-past-simple-03", type: "gap", prompt: "___ (you/see) the game last night?", answer: "Did you see", explainHe: "שאלה בעבר: Did + נושא + פועל בסיסי." },
      { id: "g-past-simple-04", type: "gap", prompt: "She ___ (buy) a new phone two days ago.", answer: "bought", explainHe: "ago = זמן שנגמר = Past Simple. buy → bought." },
      { id: "g-past-simple-05", type: "gap", prompt: "They ___ (stop) at a gas station on the way home yesterday.", answer: "stopped", explainHe: "פועל רגיל קצר: מכפילים את העיצור האחרון לפני ed: stopped." },
      { id: "g-past-simple-06", type: "gap", prompt: "He ___ (study) medicine in Italy in the nineties.", answer: "studied", explainHe: "y אחרי עיצור הופכת ל-ied: studied." },
      { id: "g-past-simple-07", type: "gap", prompt: "When ___ (they/arrive) last night?", answer: "did they arrive", explainHe: "מילת שאלה + did + נושא + פועל בסיסי." },
      { id: "g-past-simple-08", type: "gap", prompt: "I ___ (feel) terrible after the meeting yesterday.", answer: "felt", explainHe: "feel הוא פועל לא רגיל: felt." },
      {
        id: "g-past-simple-09", type: "mcq", prompt: "Where ___ last summer?",
        options: [
          { text: "did you go" },
          { text: "did you went", errorType: "verb-form", whyHe: "אחרי did הפועל בצורה הבסיסית." },
          { text: "you went", errorType: "question-form", whyHe: "שאלה בעבר דורשת did לפני הנושא." },
          { text: "were you go", errorType: "verb-form", whyHe: "were לא מתחבר לפועל בסיסי." },
        ],
        answerIndex: 0, explainHe: "שאלה בעבר: מילת שאלה + did + נושא + פועל בסיסי.",
      },
      {
        id: "g-past-simple-10", type: "mcq", prompt: "She ___ me an email an hour ago.",
        options: [
          { text: "sent" },
          { text: "has sent", errorType: "tense", whyHe: "ago מסמן זמן שנגמר: לא Present Perfect." },
          { text: "send", errorType: "tense", whyHe: "צריך צורת עבר: sent." },
          { text: "was sending", errorType: "aspect", whyHe: "פעולה שהסתיימה, לא תהליך ברקע." },
        ],
        answerIndex: 0, explainHe: "\"לפני שעה\" הוא סמן עבר, ולכן עבר פשוט: send הופך ל-sent.",
      },
      {
        id: "g-past-simple-11", type: "mcq", prompt: "I ___ the movie. It was boring.",
        options: [
          { text: "didn't like" },
          { text: "didn't liked", errorType: "verb-form", whyHe: "אחרי didn't אין ed." },
          { text: "not liked", errorType: "verb-form", whyHe: "שלילה בעבר דורשת didn't." },
          { text: "wasn't like", errorType: "verb-form", whyHe: "wasn't מתאים לשם תואר, לא לפועל." },
        ],
        answerIndex: 0, explainHe: "שלילה בעבר: didn't + פועל בסיסי.",
      },
      {
        id: "g-past-simple-12", type: "mcq", prompt: "We ___ in Eilat for a week last year.",
        options: [
          { text: "were" },
          { text: "was", errorType: "agreement", whyHe: "we = were." },
          { text: "are", errorType: "tense", whyHe: "last year = עבר." },
          { text: "have been", errorType: "tense", whyHe: "last year = זמן שנגמר, לא Present Perfect." },
        ],
        answerIndex: 0, explainHe: "be בעבר: I/he/she/it was, we/you/they were.",
      },
      {
        id: "g-past-simple-13", type: "mcq", prompt: "___ the meeting long?",
        options: [
          { text: "Was" },
          { text: "Did", errorType: "verb-form", whyHe: "אין פועל אחרי, רק שם תואר (long): צריך was." },
          { text: "Were", errorType: "agreement", whyHe: "the meeting = it = was." },
          { text: "Has", errorType: "tense", whyHe: "שאלה על אירוע שנגמר: was." },
        ],
        answerIndex: 0, explainHe: "עם be לא משתמשים ב-did: Was the meeting long?",
      },
      { id: "g-past-simple-14", type: "fix", prompt: "I didn't went to work yesterday.", answer: "I didn't go to work yesterday.", errorType: "verb-form", explainHe: "didn't כבר מסמן עבר; הפועל אחריו בצורה הבסיסית." },
      { id: "g-past-simple-15", type: "fix", prompt: "She was call me last night.", answer: "She called me last night.", errorType: "verb-form", explainHe: "עבר פשוט הוא פועל אחד עם ed. was + פועל בסיסי לא קיים." },
      { id: "g-past-simple-16", type: "fix", prompt: "Did you saw the news?", answer: "Did you see the news?", errorType: "question-form", explainHe: "אחרי Did הפועל בצורה הבסיסית: see." },
      { id: "g-past-simple-17", type: "fix", prompt: "We eated pizza on Friday.", answer: "We ate pizza on Friday.", errorType: "verb-form", explainHe: "eat הוא פועל לא רגיל: ate." },
      { id: "g-past-simple-18", type: "transform", prompt: "I go to work by bus.", keyword: "yesterday", answer: "I went to work by bus yesterday.", accept: ["Yesterday I went to work by bus."], explainHe: "yesterday מכריח עבר: go → went." },
      { id: "g-past-simple-19", type: "transform", prompt: "They watched the game.", keyword: "Did", answer: "Did they watch the game?", explainHe: "בשאלה ה-ed עובר ל-did: Did they watch?" },
      { id: "g-past-simple-20", type: "transform", prompt: "He bought a car.", keyword: "not", answer: "He did not buy a car.", accept: ["He didn't buy a car."], explainHe: "שלילה: did not + buy (הצורה הבסיסית, לא bought)." },
      { id: "g-past-simple-21", type: "order", words: ["what", "time", "did", "you", "get", "home?"], answer: "What time did you get home?", explainHe: "מילת שאלה + did + נושא + פועל בסיסי." },
      { id: "g-past-simple-22", type: "order", words: ["we", "didn't", "have", "any", "money", "last", "month"], answer: "We didn't have any money last month.", explainHe: "didn't + have (בסיסי); ביטוי הזמן בסוף." },
      { id: "g-past-simple-23", type: "translate", he: "קניתי לחם אתמול.", answer: "I bought bread yesterday.", accept: ["Yesterday I bought bread.", "I bought some bread yesterday."], explainHe: "buy → bought. הזמן yesterday בדרך כלל בסוף המשפט." },
      { id: "g-past-simple-24", type: "translate", he: "הם לא באו למסיבה.", answer: "They didn't come to the party.", explainHe: "שלילה בעבר: didn't + come. לא 'didn't came'." },
    ],
  },

  // ---------------------------------------------------------------------------
  // 3. Past continuous vs past simple
  // ---------------------------------------------------------------------------
  {
    id: "g-past-continuous",
    title: "Past continuous vs past simple",
    titleHe: "עבר ממושך",
    strand: "tenses",
    order: 3,
    prereqs: ["g-past-simple"],
    lesson: {
      explanationHe: [
        "Past Continuous מתאר פעולה שהייתה באמצע, בתהליך, בנקודת זמן מסוימת בעבר. 'At 8 last night I was watching TV' – ב-8 הייתי באמצע לצפות. זה לא אומר מתי התחלתי או מתי סיימתי, רק שברגע ההוא זה היה קורה.",
        "השימוש הכי חשוב הוא בשילוב עם Past Simple: הפעולה הארוכה ברקע (Continuous) ופעולה קצרה שקוטעת אותה (Simple). 'I was cooking when the phone rang' – הבישול היה ברקע, הצלצול קטע אותו. בדרך כלל when + Past Simple, while + Past Continuous.",
        "כששתי פעולות ארוכות קורות במקביל, שתיהן ב-Continuous: 'While I was cooking, he was watching TV'. וכשפעולות באות אחת אחרי השנייה (סיפור), כולן ב-Past Simple: 'I came in, sat down and opened the laptop'.",
        "הצורה: was/were + פועל עם ing. שלילה: wasn't/weren't. שאלה: Were you sleeping? What was he doing?",
        "שימו לב לפעלים קצרים ומיידיים: break, drop, arrive, stop – הם בדרך כלל ב-Past Simple, כי הם לא נמשכים. 'She broke her leg while she was skiing'.",
      ],
      form: [
        { label: "(+)", example: "I was working — you were working — she was working — they were working" },
        { label: "(-)", example: "I wasn't listening — they weren't listening" },
        { label: "(?)", example: "Were you sleeping? — What was she doing at ten?" },
        { label: "רקע + קטיעה", example: "I was walking home when it started to rain." },
        { label: "while + continuous", example: "While we were driving, the kids were sleeping." },
      ],
      examples: [
        { en: "At 8 o'clock last night I was watching TV.", he: "אתמול ב-8 בערב צפיתי בטלוויזיה." },
        { en: "I was cooking when the phone rang.", he: "בישלתי כשהטלפון צלצל." },
        { en: "While we were driving home, it started to rain.", he: "בזמן שנסענו הביתה, התחיל לרדת גשם." },
        { en: "She wasn't listening, so she missed the question.", he: "היא לא הקשיבה, אז היא פספסה את השאלה." },
        { en: "What were you doing at ten yesterday morning?", he: "מה עשית אתמול בעשר בבוקר?" },
        { en: "He broke his leg while he was skiing.", he: "הוא שבר את הרגל בזמן שעשה סקי." },
        { en: "They were talking about me when I walked in.", he: "הם דיברו עליי כשנכנסתי." },
      ],
      contrastHe: [
        "בעברית 'בישלתי כשהטלפון צלצל' – שני הפעלים באותה צורה. באנגלית מבדילים: was cooking (רקע) מול rang (קטיעה).",
        "'בזמן ש...' = while, ואחריו כמעט תמיד Past Continuous. 'כש...' = when, ואחריו בדרך כלל Past Simple.",
        "דוברי עברית לפעמים שמים was + פועל בלי ing: 'I was sleep'. אחרי was/were חייב ing.",
      ],
      commonErrors: [
        { wrong: "I was sleep when you called.", right: "I was sleeping when you called.", whyHe: "was/were + ing תמיד." },
        { wrong: "While I cooked dinner, the lights went out.", right: "While I was cooking dinner, the lights went out.", whyHe: "הפעולה הארוכה ברקע = Past Continuous." },
        { wrong: "She was breaking her arm while she was playing.", right: "She broke her arm while she was playing.", whyHe: "break היא פעולה רגעית שקוטעת: Past Simple." },
        { wrong: "They was waiting for the bus.", right: "They were waiting for the bus.", whyHe: "they = were." },
        { wrong: "When I was seeing him, he was crying.", right: "When I saw him, he was crying.", whyHe: "see היא הפעולה הקצרה, crying היא הרקע." },
      ],
    },
    items: [
      { id: "g-past-continuous-01", type: "gap", prompt: "At 8 o'clock last night I ___ (watch) TV.", answer: "was watching", explainHe: "נקודת זמן בעבר + פעולה באמצע = Past Continuous." },
      { id: "g-past-continuous-02", type: "gap", prompt: "I ___ (cook) when the phone rang.", answer: "was cooking", explainHe: "הבישול היה ברקע, הצלצול קטע אותו: was cooking." },
      { id: "g-past-continuous-03", type: "gap", prompt: "While we ___ (drive) home, it started to rain.", answer: "were driving", explainHe: "while + פעולה ארוכה = Past Continuous. we = were." },
      { id: "g-past-continuous-04", type: "gap", prompt: "She ___ (not/listen), so she missed the question.", answer: "wasn't listening", explainHe: "מצב שנמשך ברקע (לא הקשיבה) = wasn't + ing." },
      { id: "g-past-continuous-05", type: "gap", prompt: "What ___ (you/do) at ten yesterday morning?", answer: "were you doing", explainHe: "שאלה על מה היה באמצע לקרות בשעה מסוימת: were you doing." },
      { id: "g-past-continuous-06", type: "gap", prompt: "He ___ (break) his leg while he was skiing.", answer: "broke", explainHe: "break היא פעולה רגעית שקוטעת את הרקע: Past Simple. break → broke." },
      { id: "g-past-continuous-07", type: "gap", prompt: "They ___ (talk) about me when I walked in.", answer: "were talking", explainHe: "הדיבור היה בתהליך כשנכנסתי: were talking." },
      { id: "g-past-continuous-08", type: "gap", prompt: "The sun ___ (shine) when we left the house this morning.", answer: "was shining", explainHe: "מזג האוויר הוא הרקע, היציאה היא הפעולה הקצרה." },
      {
        id: "g-past-continuous-09", type: "mcq", prompt: "I ___ down the street when I saw an old friend.",
        options: [
          { text: "was walking" },
          { text: "walked", errorType: "aspect", whyHe: "ההליכה היא הרקע הארוך; הפגישה קטעה אותה. צריך Continuous." },
          { text: "were walking", errorType: "agreement", whyHe: "I = was." },
          { text: "am walking", errorType: "tense", whyHe: "הסיפור בעבר (saw)." },
        ],
        answerIndex: 0, explainHe: "רקע ארוך (was walking) + קטיעה קצרה (saw).",
      },
      {
        id: "g-past-continuous-10", type: "mcq", prompt: "The phone rang while I ___ a shower.",
        options: [
          { text: "was having" },
          { text: "had", errorType: "aspect", whyHe: "אחרי while באה הפעולה הארוכה שברקע: Past Continuous." },
          { text: "have", errorType: "tense", whyHe: "המשפט בעבר (rang)." },
          { text: "having", errorType: "verb-form", whyHe: "חסר was." },
        ],
        answerIndex: 0, explainHe: "while + Past Continuous; המקלחת הייתה ברקע.",
      },
      {
        id: "g-past-continuous-11", type: "mcq", prompt: "When the teacher came in, the students ___.",
        options: [
          { text: "stopped talking" },
          { text: "were stopping talking", errorType: "aspect", whyHe: "stop היא פעולה רגעית שבאה אחרי הכניסה, לא רקע." },
          { text: "were stop talking", errorType: "verb-form", whyHe: "were דורש ing." },
          { text: "stop talking", errorType: "tense", whyHe: "הסיפור בעבר: stopped." },
        ],
        answerIndex: 0, explainHe: "שתי פעולות קצרות בזו אחר זו: came in → stopped. שתיהן Past Simple.",
      },
      {
        id: "g-past-continuous-12", type: "mcq", prompt: "___ when the accident happened?",
        options: [
          { text: "Were you driving" },
          { text: "Did you drive", errorType: "aspect", whyHe: "השאלה היא מה היית באמצע לעשות ברגע התאונה: Continuous." },
          { text: "You were driving", errorType: "question-form", whyHe: "בשאלה were בא לפני הנושא." },
          { text: "Was you driving", errorType: "agreement", whyHe: "you = were." },
        ],
        answerIndex: 0, explainHe: "שאלה על פעולה ברקע: Were + נושא + ing.",
      },
      {
        id: "g-past-continuous-13", type: "mcq", prompt: "This time yesterday we ___ on the beach.",
        options: [
          { text: "were lying" },
          { text: "lay", errorType: "aspect", whyHe: "'this time yesterday' = נקודת זמן שבה היינו באמצע: Continuous." },
          { text: "lied", errorType: "word-choice", whyHe: "lied = שיקרנו. lie (לשכב) → lying." },
          { text: "were lie", errorType: "verb-form", whyHe: "were + ing: lying." },
        ],
        answerIndex: 0, explainHe: "נקודת זמן מדויקת בעבר + מה היה בתהליך = were lying.",
      },
      { id: "g-past-continuous-14", type: "fix", prompt: "I was sleep when you called.", answer: "I was sleeping when you called.", errorType: "verb-form", explainHe: "אחרי was חייב ing." },
      { id: "g-past-continuous-15", type: "fix", prompt: "While I cooked dinner, the lights went out.", answer: "While I was cooking dinner, the lights went out.", errorType: "aspect", explainHe: "while + הפעולה הארוכה ברקע = Past Continuous." },
      { id: "g-past-continuous-16", type: "fix", prompt: "She was breaking her arm while she was playing.", answer: "She broke her arm while she was playing.", errorType: "aspect", explainHe: "השבירה היא רגעית וקוטעת: Past Simple." },
      { id: "g-past-continuous-17", type: "fix", prompt: "They was waiting for the bus.", answer: "They were waiting for the bus.", errorType: "agreement", explainHe: "עם they צורת העבר של be היא were." },
      { id: "g-past-continuous-18", type: "transform", prompt: "I was reading. The doorbell rang.", keyword: "when", answer: "I was reading when the doorbell rang.", accept: ["When the doorbell rang, I was reading."], explainHe: "רקע + when + הקטיעה ב-Past Simple." },
      { id: "g-past-continuous-19", type: "transform", prompt: "He was driving. He was talking on the phone. (at the same time)", keyword: "while", answer: "He was talking on the phone while he was driving.", accept: ["He was driving while he was talking on the phone.", "While he was driving, he was talking on the phone.", "While he was talking on the phone, he was driving."], explainHe: "שתי פעולות ארוכות במקביל: שתיהן Past Continuous, מחוברות ב-while." },
      { id: "g-past-continuous-20", type: "transform", prompt: "We walked home. It started to rain.", keyword: "while", answer: "It started to rain while we were walking home.", accept: ["While we were walking home, it started to rain."], explainHe: "while + הרקע (were walking); הגשם התחיל = Past Simple." },
      { id: "g-past-continuous-21", type: "order", words: ["what", "were", "you", "doing", "at", "midnight?"], answer: "What were you doing at midnight?", explainHe: "מילת שאלה + were + נושא + ing + זמן." },
      { id: "g-past-continuous-22", type: "order", words: ["she", "wasn't", "looking", "when", "the", "car", "came"], answer: "She wasn't looking when the car came.", explainHe: "wasn't looking = הרקע; when the car came = הקטיעה." },
      { id: "g-past-continuous-23", type: "translate", he: "ישנתי כשהיא התקשרה.", answer: "I was sleeping when she called.", accept: ["When she called, I was sleeping.", "I was asleep when she called."], explainHe: "השינה ברקע (was sleeping), הטלפון קוטע (called)." },
      { id: "g-past-continuous-24", type: "translate", he: "מה עשית אתמול בשמונה בערב?", answer: "What were you doing at eight last night?", accept: ["What were you doing at 8 last night?", "What were you doing yesterday at eight in the evening?", "What were you doing at eight yesterday evening?", "What were you doing at 8 yesterday evening?", "What were you doing yesterday at 8 pm?", "What were you doing yesterday at 8 in the evening?"], explainHe: "שאלה על מה היה בתהליך בשעה מסוימת: were you doing." },
    ],
  },

  // ---------------------------------------------------------------------------
  // 4. Present perfect
  // ---------------------------------------------------------------------------
  {
    id: "g-present-perfect",
    title: "Present perfect: experience, results, unfinished time",
    titleHe: "הווה מושלם (Present Perfect)",
    strand: "tenses",
    order: 4,
    prereqs: ["g-past-simple"],
    lesson: {
      explanationHe: [
        "Present Perfect הוא הזמן שאין לו מקבילה בעברית, ולכן הוא הכי חשוב ללמוד. הרעיון: משהו קרה בעבר, אבל אנחנו מדברים עליו בגלל הקשר שלו לעכשיו. לא מעניין אותנו מתי זה קרה, אלא מה המצב היום.",
        "שלושה שימושים מרכזיים. (1) ניסיון חיים: 'I have been to Japan' – אי פעם בחיים, בלי לומר מתי. עם ever, never, before, twice. (2) תוצאה עכשיו: 'I have lost my keys' – ולכן עכשיו אין לי מפתחות. עם just, already, yet. (3) משהו שהתחיל בעבר ונמשך עד עכשיו: 'I have lived here for five years' – ועדיין גר. עם for, since, how long.",
        "המפתח: אם המשפט מתחבר להווה, זה Present Perfect. אם יש בו זמן שנגמר (yesterday, in 2015, ago) – זה Past Simple, ונלמד את ההבדל בשיעור הבא.",
        "הצורה: have/has + הצורה השלישית של הפועל (past participle). בפעלים רגילים זה ed: worked, lived. בלא רגילים צריך לזכור את הטור השלישי: go → gone, see → seen, eat → eaten, be → been, buy → bought.",
        "שלילה: haven't/hasn't. שאלה: Have you...? Has she...? המילים ever, never, just, already נכנסות בין have לפועל: 'I have never seen', 'She has just left'.",
      ],
      form: [
        { label: "(+)", example: "I have worked — she has worked — they have gone" },
        { label: "(-)", example: "I haven't seen — he hasn't finished" },
        { label: "(?)", example: "Have you ever eaten sushi? — Has she arrived?" },
        { label: "ניסיון", example: "I have been to Rome twice. I have never tried it." },
        { label: "תוצאה", example: "I have lost my keys. She has just left." },
        { label: "עד עכשיו", example: "We have lived here for ten years / since 2016." },
      ],
      examples: [
        { en: "I have never been to Japan.", he: "מעולם לא הייתי ביפן." },
        { en: "Have you ever eaten sushi?", he: "אי פעם אכלת סושי?" },
        { en: "She has lost her keys, so she can't get in.", he: "היא איבדה את המפתחות, אז היא לא יכולה להיכנס." },
        { en: "We have known each other since high school.", he: "אנחנו מכירים מהתיכון." },
        { en: "He hasn't finished his homework yet.", he: "הוא עוד לא סיים את שיעורי הבית." },
        { en: "They have lived here for ten years.", he: "הם גרים פה עשר שנים." },
        { en: "I've seen that movie three times.", he: "ראיתי את הסרט הזה שלוש פעמים." },
        { en: "My brother has just passed his driving test.", he: "אחי הרגע עבר את מבחן הנהיגה." },
      ],
      contrastHe: [
        "'אני גר פה חמש שנים' – בעברית הווה. באנגלית: 'I have lived here for five years'. משהו שהתחיל בעבר ונמשך עכשיו = Present Perfect, לא Present Simple.",
        "'אנחנו מכירים מ-2010' → 'We have known each other since 2010'. 'אנחנו נשואים עשר שנים' → 'We have been married for ten years'.",
        "'מעולם לא הייתי ב...' (עבר בעברית) → 'I have never been to...' (Present Perfect באנגלית), כי מדובר בניסיון חיים עד עכשיו.",
        "'איבדתי את הארנק' יכול להיות סיפור (lost) או מצב עכשיו (have lost). כשהתוצאה חשובה עכשיו – have lost.",
      ],
      commonErrors: [
        { wrong: "I live here for five years.", right: "I have lived here for five years.", whyHe: "התחיל בעבר ונמשך עכשיו = Present Perfect." },
        { wrong: "She has went to the bank.", right: "She has gone to the bank.", whyHe: "אחרי has באה הצורה השלישית: gone." },
        { wrong: "Have you ever saw a whale?", right: "Have you ever seen a whale?", whyHe: "Have + הצורה השלישית: seen." },
        { wrong: "We know each other since 2010.", right: "We have known each other since 2010.", whyHe: "since מסמן התחלה בעבר שנמשכת: Present Perfect." },
        { wrong: "I have been never to London.", right: "I have never been to London.", whyHe: "never נכנס בין have לפועל." },
      ],
    },
    items: [
      { id: "g-present-perfect-01", type: "gap", prompt: "I ___ (never/be) to Japan.", answer: "have never been", explainHe: "ניסיון חיים עד עכשיו: have + never + been." },
      { id: "g-present-perfect-02", type: "gap", prompt: "She ___ (lose) her keys, so she can't get in.", answer: "has lost", explainHe: "תוצאה בהווה (לא יכולה להיכנס) = has lost." },
      { id: "g-present-perfect-03", type: "gap", prompt: "___ (you/ever/eat) sushi?", answer: "Have you ever eaten", explainHe: "שאלה על ניסיון: Have you ever + הצורה השלישית (eaten)." },
      { id: "g-present-perfect-04", type: "gap", prompt: "We ___ (know) each other since high school.", answer: "have known", explainHe: "since + מצב שנמשך עד עכשיו = Present Perfect. know → known." },
      { id: "g-present-perfect-05", type: "gap", prompt: "He ___ (not/finish) his homework yet.", answer: "hasn't finished", explainHe: "yet = עד עכשיו עדיין לא: hasn't finished." },
      { id: "g-present-perfect-06", type: "gap", prompt: "They ___ (live) here for ten years.", answer: "have lived", accept: ["have been living"], explainHe: "for + משך זמן שנמשך עד עכשיו: have lived. (גם have been living נכון.)" },
      { id: "g-present-perfect-07", type: "gap", prompt: "I ___ (see) that movie three times.", answer: "have seen", explainHe: "ספירה של ניסיון עד עכשיו: have seen." },
      { id: "g-present-perfect-08", type: "gap", prompt: "My brother ___ (just/pass) his driving test.", answer: "has just passed", explainHe: "just = ממש עכשיו, תוצאה טרייה: has just passed." },
      {
        id: "g-present-perfect-09", type: "mcq", prompt: "I ___ my phone. Can I use yours?",
        options: [
          { text: "have lost" },
          { text: "lost", errorType: "tense", whyHe: "הדגש הוא על המצב עכשיו (אין לי טלפון), לא על סיפור מהעבר: Present Perfect." },
          { text: "am losing", errorType: "aspect", whyHe: "זה כבר קרה, לא בתהליך." },
          { text: "lose", errorType: "tense", whyHe: "הווה פשוט מתאר הרגל, לא מה שקרה." },
        ],
        answerIndex: 0, explainHe: "תוצאה בהווה = have + הצורה השלישית.",
      },
      {
        id: "g-present-perfect-10", type: "mcq", prompt: "___ ever been to London?",
        options: [
          { text: "Have you" },
          { text: "Did you", errorType: "tense", whyHe: "ever + been = ניסיון חיים = Present Perfect." },
          { text: "Were you", errorType: "verb-form", whyHe: "been דורש have, לא were." },
          { text: "Are you", errorType: "tense", whyHe: "זו שאלה על העבר עד היום, לא על עכשיו." },
        ],
        answerIndex: 0, explainHe: "שאלת ניסיון: Have you ever been...?",
      },
      {
        id: "g-present-perfect-11", type: "mcq", prompt: "She ___ in this company since 2019.",
        options: [
          { text: "has worked" },
          { text: "works", errorType: "tense", whyHe: "בעברית 'היא עובדת פה מ-2019', אבל since דורש Present Perfect." },
          { text: "is working", errorType: "tense", whyHe: "since + נקודת התחלה = Present Perfect, לא Continuous של הווה." },
          { text: "worked", errorType: "tense", whyHe: "worked אומר שהיא כבר לא עובדת שם." },
        ],
        answerIndex: 0, explainHe: "since 2019 ועדיין שם = has worked.",
      },
      {
        id: "g-present-perfect-12", type: "mcq", prompt: "We ___ three emails from him so far today.",
        options: [
          { text: "have received" },
          { text: "received", errorType: "tense", whyHe: "'so far today' = היום עוד לא נגמר, הספירה עוד פתוחה: Present Perfect." },
          { text: "receive", errorType: "tense", whyHe: "הווה פשוט = הרגל, לא מה שהצטבר היום." },
          { text: "are receiving", errorType: "aspect", whyHe: "המיילים כבר הגיעו, זה לא בתהליך." },
        ],
        answerIndex: 0, explainHe: "זמן שלא נגמר (today, this week) + ספירה = Present Perfect.",
      },
      {
        id: "g-present-perfect-13", type: "mcq", prompt: "Have you finished? — No, I ___ yet.",
        options: [
          { text: "haven't finished" },
          { text: "didn't finish", errorType: "tense", whyHe: "yet מתחבר ל-Present Perfect." },
          { text: "not finished", errorType: "verb-form", whyHe: "חסר haven't." },
          { text: "haven't finish", errorType: "verb-form", whyHe: "אחרי haven't באה הצורה השלישית: finished." },
        ],
        answerIndex: 0, explainHe: "yet בשלילה = haven't + הצורה השלישית.",
      },
      { id: "g-present-perfect-14", type: "fix", prompt: "I live here for five years.", answer: "I have lived here for five years.", accept: ["I have been living here for five years."], errorType: "tense", explainHe: "התחיל לפני חמש שנים ונמשך עכשיו = Present Perfect. בעברית זה הווה, באנגלית לא." },
      { id: "g-present-perfect-15", type: "fix", prompt: "She has went to the bank.", answer: "She has gone to the bank.", errorType: "verb-form", explainHe: "אחרי has באה הצורה השלישית: gone." },
      { id: "g-present-perfect-16", type: "fix", prompt: "Have you ever saw a whale?", answer: "Have you ever seen a whale?", errorType: "verb-form", explainHe: "Have + הצורה השלישית: seen." },
      { id: "g-present-perfect-17", type: "fix", prompt: "We know each other since 2010.", answer: "We have known each other since 2010.", errorType: "tense", explainHe: "since מסמן התחלה בעבר שנמשכת עד היום: have known." },
      { id: "g-present-perfect-18", type: "transform", prompt: "I started working here in 2020. I still work here.", keyword: "since", answer: "I have worked here since 2020.", accept: ["I have been working here since 2020."], explainHe: "התחלה בעבר + נמשך עכשיו = Present Perfect + since." },
      { id: "g-present-perfect-19", type: "transform", prompt: "This is my first time in Rome.", keyword: "never", answer: "I have never been to Rome before.", accept: ["I have never been to Rome.", "I have never been in Rome before."], explainHe: "פעם ראשונה = מעולם לא הייתי: have never been." },
      { id: "g-present-perfect-20", type: "transform", prompt: "She doesn't have her wallet. She lost it.", keyword: "has", answer: "She has lost her wallet.", explainHe: "תוצאה בהווה (אין לה ארנק) = has lost." },
      { id: "g-present-perfect-21", type: "order", words: ["have", "you", "ever", "been", "to", "Paris?"], answer: "Have you ever been to Paris?", explainHe: "Have + נושא + ever + been + to + מקום." },
      { id: "g-present-perfect-22", type: "order", words: ["we", "haven't", "seen", "him", "for", "years"], answer: "We haven't seen him for years.", explainHe: "haven't seen + for + משך זמן." },
      { id: "g-present-perfect-23", type: "translate", he: "אני גר פה חמש שנים.", answer: "I have lived here for five years.", accept: ["I have been living here for five years."], explainHe: "הווה בעברית, Present Perfect באנגלית: התחיל בעבר ונמשך." },
      { id: "g-present-perfect-24", type: "translate", he: "מעולם לא אכלתי סושי.", answer: "I have never eaten sushi.", explainHe: "עבר בעברית, אבל ניסיון חיים עד עכשיו = have never eaten." },
    ],
  },

  // ---------------------------------------------------------------------------
  // 5. Present perfect vs past simple
  // ---------------------------------------------------------------------------
  {
    id: "g-present-perfect-vs-past",
    title: "Present perfect vs past simple",
    titleHe: "הווה מושלם מול עבר פשוט",
    strand: "tenses",
    order: 5,
    prereqs: ["g-present-perfect"],
    lesson: {
      explanationHe: [
        "שני הזמנים מדברים על משהו שקרה. ההבדל הוא בשאלה 'מתי': Past Simple מספר על זמן שנגמר (yesterday, last year, in 2018, two hours ago, when I was a child). Present Perfect לא אומר מתי, כי מה שחשוב הוא הקשר להווה.",
        "כלל זהב: אם יש במשפט ביטוי זמן שנגמר – Past Simple. תמיד. 'I saw him yesterday', לא 'I have seen him yesterday'. ואם השאלה היא When? – גם Past Simple: 'When did you arrive?'.",
        "לעומת זאת, ביטויי זמן שעדיין נמשכים (today, this week, this year, so far) ומילים כמו ever, never, yet, already, just, since, for מושכים ל-Present Perfect.",
        "שיחה טיפוסית מתחילה ב-Present Perfect ועוברת ל-Past Simple ברגע שנכנסים לפרטים: 'Have you ever been to Rome? – Yes, I have. – When did you go? – I went in 2018. It was amazing.'",
        "אנשים שכבר לא חיים, ותקופות שנגמרו, תמיד ב-Past Simple: 'Shakespeare wrote many plays'. 'I lived in Haifa for two years' = כבר לא גר שם. 'I have lived in Haifa for two years' = עדיין גר.",
      ],
      form: [
        { label: "Past Simple", example: "I visited Rome in 2018. When did you go?" },
        { label: "Present Perfect", example: "I have visited Rome twice. Have you ever been there?" },
        { label: "זמן שנגמר", example: "yesterday, last week, in 2015, ago, when I was young" },
        { label: "זמן פתוח / קשר להווה", example: "today, this week, ever, never, yet, already, just, since, for" },
        { label: "מעבר בשיחה", example: "I've been to Paris. — Really? When did you go? — Two years ago." },
      ],
      examples: [
        { en: "I visited Rome in 2018.", he: "ביקרתי ברומא ב-2018." },
        { en: "I have visited Rome twice.", he: "ביקרתי ברומא פעמיים (עד היום)." },
        { en: "She moved to Berlin last year.", he: "היא עברה לברלין בשנה שעברה." },
        { en: "She has lived in Berlin since then.", he: "מאז היא גרה בברלין." },
        { en: "When did you talk to the boss?", he: "מתי דיברת עם הבוס?" },
        { en: "Have you talked to the boss yet?", he: "כבר דיברת עם הבוס?" },
        { en: "My grandfather died ten years ago.", he: "סבא שלי נפטר לפני עשר שנים." },
        { en: "We haven't seen each other since the wedding.", he: "לא נפגשנו מאז החתונה." },
      ],
      contrastHe: [
        "בעברית 'ראיתי אותו' משמש לשני המקרים. באנגלית: 'I saw him yesterday' (מתי – ידוע), 'I have seen him' (אי פעם / לאחרונה, בלי מתי).",
        "'עוד לא סיימתי' → 'I haven't finished yet' (Present Perfect). 'לא סיימתי אתמול' → 'I didn't finish yesterday' (Past Simple).",
        "'מתי הגעת?' תמיד 'When did you arrive?'. עם when לא משתמשים ב-Present Perfect.",
      ],
      commonErrors: [
        { wrong: "I have seen him yesterday.", right: "I saw him yesterday.", whyHe: "yesterday = זמן שנגמר = Past Simple." },
        { wrong: "When have you arrived?", right: "When did you arrive?", whyHe: "שאלת when = Past Simple." },
        { wrong: "I lived here since 2010.", right: "I have lived here since 2010.", whyHe: "since + עדיין גר = Present Perfect." },
        { wrong: "She has finished school in 2015.", right: "She finished school in 2015.", whyHe: "in 2015 = תאריך בעבר = Past Simple." },
        { wrong: "We have met at a party three years ago.", right: "We met at a party three years ago.", whyHe: "ago תמיד עם Past Simple." },
      ],
    },
    items: [
      { id: "g-present-perfect-vs-past-01", type: "gap", prompt: "I ___ (visit) Rome in 2018.", answer: "visited", explainHe: "in 2018 = זמן שנגמר = Past Simple." },
      { id: "g-present-perfect-vs-past-02", type: "gap", prompt: "I ___ (visit) Rome twice so far.", answer: "have visited", explainHe: "so far = עד עכשיו, בלי 'מתי' = Present Perfect." },
      { id: "g-present-perfect-vs-past-03", type: "gap", prompt: "She ___ (move) to Berlin last year.", answer: "moved", explainHe: "\"בשנה שעברה\" הוא זמן סגור, ולכן עבר פשוט ולא הווה מושלם." },
      { id: "g-present-perfect-vs-past-04", type: "gap", prompt: "She ___ (live) in Berlin since then.", answer: "has lived", accept: ["has been living"], explainHe: "since then + עדיין שם = Present Perfect." },
      { id: "g-present-perfect-vs-past-05", type: "gap", prompt: "___ (you/talk) to the boss yet?", answer: "Have you talked", explainHe: "yet שייך להווה מושלם: haven't finished yet." },
      { id: "g-present-perfect-vs-past-06", type: "gap", prompt: "When ___ (you/talk) to the boss?", answer: "did you talk", explainHe: "when שואל מתי בדיוק = Past Simple." },
      { id: "g-present-perfect-vs-past-07", type: "gap", prompt: "My grandfather ___ (die) ten years ago.", answer: "died", explainHe: "המילה ago מציינת נקודה בעבר, ולכן עבר פשוט." },
      { id: "g-present-perfect-vs-past-08", type: "gap", prompt: "We ___ (not/see) each other since the wedding.", answer: "haven't seen", explainHe: "since + עד עכשיו = Present Perfect בשלילה." },
      {
        id: "g-present-perfect-vs-past-09", type: "mcq", prompt: "I ___ my keys yesterday, but I found them.",
        options: [
          { text: "lost" },
          { text: "have lost", errorType: "tense", whyHe: "yesterday = זמן שנגמר; וגם אין תוצאה בהווה (מצאתי אותם)." },
          { text: "lose", errorType: "tense", whyHe: "צריך עבר: lost." },
          { text: "had lost", errorType: "tense", whyHe: "אין כאן 'עבר לפני עבר', רק סיפור פשוט." },
        ],
        answerIndex: 0, explainHe: "yesterday + הסיפור נגמר = Past Simple.",
      },
      {
        id: "g-present-perfect-vs-past-10", type: "mcq", prompt: "I ___ my keys! I can't open the door.",
        options: [
          { text: "have lost" },
          { text: "lost", errorType: "tense", whyHe: "אין זמן במשפט והתוצאה עכשיו (לא יכול לפתוח) היא העיקר: Present Perfect." },
          { text: "losed", errorType: "verb-form", whyHe: "lose לא רגיל: lost." },
          { text: "am lost", errorType: "word-choice", whyHe: "I am lost = אני אבוד, לא המפתחות." },
        ],
        answerIndex: 0, explainHe: "תוצאה בהווה בלי זמן = have lost.",
      },
      {
        id: "g-present-perfect-vs-past-11", type: "mcq", prompt: "When ___ the results?",
        options: [
          { text: "did you get" },
          { text: "have you got", errorType: "tense", whyHe: "when לא הולך עם Present Perfect." },
          { text: "did you got", errorType: "verb-form", whyHe: "אחרי did פועל בסיסי." },
          { text: "you got", errorType: "question-form", whyHe: "חסר did בשאלה." },
        ],
        answerIndex: 0, explainHe: "When + did + נושא + פועל בסיסי.",
      },
      {
        id: "g-present-perfect-vs-past-12", type: "mcq", prompt: "Shakespeare ___ many plays.",
        options: [
          { text: "wrote" },
          { text: "has written", errorType: "tense", whyHe: "שייקספיר מת; חייו נגמרו, אז Past Simple." },
          { text: "has wrote", errorType: "verb-form", whyHe: "has דורש written, ובכל מקרה כאן צריך Past Simple." },
          { text: "writes", errorType: "tense", whyHe: "הוא לא כותב עכשיו." },
        ],
        answerIndex: 0, explainHe: "תקופה שנגמרה (אדם שכבר לא חי) = Past Simple.",
      },
      {
        id: "g-present-perfect-vs-past-13", type: "mcq", prompt: "I ___ him this week, but I saw him last week.",
        options: [
          { text: "haven't seen" },
          { text: "didn't see", errorType: "tense", whyHe: "this week עוד לא נגמר: Present Perfect. last week נגמר: saw." },
          { text: "don't see", errorType: "tense", whyHe: "הווה פשוט = הרגל, לא מה שקרה השבוע." },
          { text: "not seen", errorType: "verb-form", whyHe: "חסר haven't." },
        ],
        answerIndex: 0, explainHe: "this week (פתוח) מול last week (סגור).",
      },
      { id: "g-present-perfect-vs-past-14", type: "fix", prompt: "I have seen him yesterday.", answer: "I saw him yesterday.", errorType: "tense", explainHe: "yesterday = Past Simple, תמיד." },
      { id: "g-present-perfect-vs-past-15", type: "fix", prompt: "She has finished school in 2015.", answer: "She finished school in 2015.", errorType: "tense", explainHe: "תאריך בעבר = Past Simple." },
      { id: "g-present-perfect-vs-past-16", type: "fix", prompt: "When have you arrived?", answer: "When did you arrive?", errorType: "tense", explainHe: "when = מתי בדיוק = Past Simple." },
      { id: "g-present-perfect-vs-past-17", type: "fix", prompt: "I lived here since 2010.", answer: "I have lived here since 2010.", accept: ["I have been living here since 2010."], errorType: "tense", explainHe: "since + עדיין גר = Present Perfect." },
      { id: "g-present-perfect-vs-past-18", type: "transform", prompt: "The last time I saw her was in May.", keyword: "since", answer: "I haven't seen her since May.", explainHe: "'הפעם האחרונה הייתה ב...' = 'לא ראיתי מאז...': haven't seen since." },
      { id: "g-present-perfect-vs-past-19", type: "transform", prompt: "I have been to Madrid. It was in 2019.", keyword: "went", answer: "I went to Madrid in 2019.", explainHe: "ברגע שיש תאריך, עוברים ל-Past Simple: went." },
      { id: "g-present-perfect-vs-past-20", type: "transform", prompt: "I started learning English ten years ago. I still learn it.", keyword: "for", answer: "I have been learning English for ten years.", accept: ["I have learned English for ten years.", "I have been studying English for ten years.", "I have studied English for ten years."], explainHe: "ago + started → for + Present Perfect: משך הזמן עד עכשיו." },
      { id: "g-present-perfect-vs-past-21", type: "order", words: ["did", "you", "finish", "the", "report", "yesterday?"], answer: "Did you finish the report yesterday?", explainHe: "yesterday = Past Simple: Did + נושא + פועל בסיסי." },
      { id: "g-present-perfect-vs-past-22", type: "order", words: ["I", "have", "already", "seen", "this", "movie"], answer: "I have already seen this movie.", explainHe: "already נכנס בין have ל-seen." },
      { id: "g-present-perfect-vs-past-23", type: "translate", he: "ראיתי את הסרט הזה בשבוע שעבר.", answer: "I saw this movie last week.", accept: ["I saw that movie last week.", "I watched this movie last week.", "I watched that movie last week.", "Last week I saw this movie.", "I saw this film last week."], explainHe: "\"בשבוע שעבר\" הוא זמן סגור, ולכן עבר פשוט: saw." },
      { id: "g-present-perfect-vs-past-24", type: "translate", he: "עוד לא אכלתי ארוחת בוקר.", answer: "I haven't had breakfast yet.", accept: ["I haven't eaten breakfast yet.", "I have not had breakfast yet.", "I have not eaten breakfast yet."], explainHe: "'עוד לא' = not yet = Present Perfect. בעברית זה עבר, באנגלית לא." },
    ],
  },

  // ---------------------------------------------------------------------------
  // 6. for / since / ago / already / yet / just
  // ---------------------------------------------------------------------------
  {
    id: "g-for-since",
    title: "for / since / ago / already / yet / just",
    titleHe: "for, since, ago, yet, already",
    strand: "tenses",
    order: 6,
    prereqs: ["g-present-perfect"],
    lesson: {
      explanationHe: [
        "שש מילים קטנות שמארגנות את הזמן סביב Present Perfect. הן לא רק אוצר מילים – כל אחת מהן 'מושכת' זמן מסוים, ולכן כשבוחרים נכון את המילה, הזמן מסתדר מעצמו.",
        "for = משך: for two hours, for ten years, for a long time. since = נקודת התחלה: since Monday, since 2015, since I was a child. שתיהן עונות על How long? ובאות עם Present Perfect. הטעות הכי נפוצה של דוברי עברית היא since עם משך ('since five years') – זה תמיד for.",
        "ago = לפני X זמן, ותמיד עם Past Simple: 'two years ago', 'an hour ago'. בעברית אומרים 'לפני שנתיים', אבל באנגלית ago בא אחרי משך הזמן, לא לפניו: לא 'before two years'.",
        "already = כבר, במשפט חיובי, בין have לפועל: 'I have already eaten'. yet = עדיין/כבר, בשלילה ובשאלה, בסוף המשפט: 'I haven't eaten yet', 'Have you eaten yet?'. just = הרגע, בין have לפועל: 'She has just left'.",
        "בקצרה: How long? → for/since + Present Perfect. When? → ago + Past Simple. already / just באמצע, yet בסוף.",
      ],
      form: [
        { label: "for + משך", example: "for three days, for a week, for years, for a long time" },
        { label: "since + נקודה", example: "since Monday, since 2015, since breakfast, since I was ten" },
        { label: "ago + Past Simple", example: "I moved here two years ago. She left an hour ago." },
        { label: "already (+)", example: "I have already finished. She has already seen it." },
        { label: "yet (- / ?)", example: "I haven't finished yet. Have you finished yet?" },
        { label: "just", example: "He has just arrived. I've just eaten." },
      ],
      examples: [
        { en: "We have been friends for ten years.", he: "אנחנו חברים כבר עשר שנים." },
        { en: "I haven't eaten anything since breakfast.", he: "לא אכלתי כלום מאז ארוחת הבוקר." },
        { en: "She moved to Haifa three years ago.", he: "היא עברה לחיפה לפני שלוש שנים." },
        { en: "Have you finished yet?", he: "כבר סיימת?" },
        { en: "I've already finished, so I can help you.", he: "כבר סיימתי, אז אני יכול לעזור לך." },
        { en: "He has just left. If you run, you can catch him.", he: "הוא הרגע יצא. אם תרוץ, תתפוס אותו." },
        { en: "How long have you known each other?", he: "כמה זמן אתם מכירים?" },
      ],
      contrastHe: [
        "'מזה חמש שנים' / 'כבר חמש שנים' = for five years, לא since five years. since רק עם נקודת זמן.",
        "'לפני שנתיים' = two years ago. המילה ago באה אחרי המספר: לא before two years.",
        "'כבר' בעברית משמש גם לחיוב וגם לשאלה. באנגלית: already בחיוב, yet בשאלה ובשלילה. 'כבר אכלת?' = Have you eaten yet?",
        "'אנחנו נשואים מ-2010' → We have been married since 2010. הפועל חייב להיות Present Perfect, לא are.",
      ],
      commonErrors: [
        { wrong: "I have known him since five years.", right: "I have known him for five years.", whyHe: "משך זמן = for." },
        { wrong: "She came here before two years.", right: "She came here two years ago.", whyHe: "'לפני X' = X ago." },
        { wrong: "I haven't finished already.", right: "I haven't finished yet.", whyHe: "בשלילה משתמשים ב-yet, בסוף המשפט." },
        { wrong: "We are married since 2010.", right: "We have been married since 2010.", whyHe: "since דורש Present Perfect: have been." },
        { wrong: "I already have eaten.", right: "I have already eaten.", whyHe: "already נכנס בין have לפועל." },
      ],
    },
    items: [
      { id: "g-for-since-01", type: "gap", prompt: "We have been friends ___ ten years. (for/since)", answer: "for", explainHe: "ten years = משך זמן = for." },
      { id: "g-for-since-02", type: "gap", prompt: "I haven't eaten anything ___ breakfast. (for/since)", answer: "since", explainHe: "breakfast = נקודת התחלה = since." },
      { id: "g-for-since-03", type: "gap", prompt: "She moved to Haifa three years ___. (ago/before)", answer: "ago", explainHe: "'לפני שלוש שנים' = three years ago, עם Past Simple." },
      { id: "g-for-since-04", type: "gap", prompt: "Have you finished ___? (yet/already)", answer: "yet", explainHe: "בשאלה משתמשים ב-yet, בסוף המשפט." },
      { id: "g-for-since-05", type: "gap", prompt: "I've ___ finished, so I can help you. (already/yet)", answer: "already", explainHe: "משפט חיובי + 'כבר' = already, בין have לפועל." },
      { id: "g-for-since-06", type: "gap", prompt: "He has ___ left. If you run, you can catch him. (just/yet)", answer: "just", explainHe: "הרגע = just, בין has לפועל." },
      { id: "g-for-since-07", type: "gap", prompt: "They ___ (know) each other since college.", answer: "have known", explainHe: "since מושך Present Perfect: have known." },
      { id: "g-for-since-08", type: "gap", prompt: "I ___ (start) this job two months ago.", answer: "started", explainHe: "ago מושך Past Simple: started." },
      {
        id: "g-for-since-09", type: "mcq", prompt: "I have lived here ___ 2015.",
        options: [
          { text: "since" },
          { text: "for", errorType: "preposition", whyHe: "2015 היא נקודת זמן, לא משך." },
          { text: "from", errorType: "interference", whyHe: "בעברית 'מ-2015', אבל עם Present Perfect אומרים since." },
          { text: "ago", errorType: "word-choice", whyHe: "ago בא אחרי משך זמן ועם Past Simple." },
        ],
        answerIndex: 0, explainHe: "נקודת התחלה = since.",
      },
      {
        id: "g-for-since-10", type: "mcq", prompt: "She has been sick ___ three days.",
        options: [
          { text: "for" },
          { text: "since", errorType: "preposition", whyHe: "three days = משך, לא נקודה." },
          { text: "ago", errorType: "word-choice", whyHe: "ago לא הולך עם Present Perfect." },
          { text: "from", errorType: "interference", whyHe: "'מזה שלושה ימים' = for three days." },
        ],
        answerIndex: 0, explainHe: "משך זמן = for.",
      },
      {
        id: "g-for-since-11", type: "mcq", prompt: "We met ___.",
        options: [
          { text: "two years ago" },
          { text: "before two years", errorType: "interference", whyHe: "תרגום מילולי של 'לפני שנתיים'. באנגלית ago בא אחרי המספר." },
          { text: "since two years", errorType: "preposition", whyHe: "since לא הולך עם משך ולא עם Past Simple." },
          { text: "two years before", errorType: "word-choice", whyHe: "'before' מסמן לפני אירוע אחר, לא לפני עכשיו." },
        ],
        answerIndex: 0, explainHe: "משך זמן + ago.",
      },
      {
        id: "g-for-since-12", type: "mcq", prompt: "Has the movie started ___?",
        options: [
          { text: "yet" },
          { text: "already", errorType: "word-choice", whyHe: "בשאלה ניטרלית משתמשים ב-yet. already בשאלה מביע הפתעה." },
          { text: "just", errorType: "word-choice", whyHe: "just נכנס בין has לפועל, לא בסוף." },
          { text: "still", errorType: "word-choice", whyHe: "still = עדיין (נמשך), לא מתאים כאן." },
        ],
        answerIndex: 0, explainHe: "שאלה על 'כבר' = yet בסוף המשפט.",
      },
      {
        id: "g-for-since-13", type: "mcq", prompt: "The bus ___. We'll have to wait for the next one.",
        options: [
          { text: "has just left" },
          { text: "just has left", errorType: "word-order", whyHe: "just נכנס בין has לפועל." },
          { text: "has left just", errorType: "word-order", whyHe: "just לא בא בסוף." },
          { text: "has already leave", errorType: "verb-form", whyHe: "אחרי has באה הצורה השלישית: left." },
        ],
        answerIndex: 0, explainHe: "has + just + הצורה השלישית.",
      },
      { id: "g-for-since-14", type: "fix", prompt: "I have known him since five years.", answer: "I have known him for five years.", errorType: "preposition", explainHe: "משך זמן = for. since רק עם נקודת התחלה." },
      { id: "g-for-since-15", type: "fix", prompt: "She came here before two years.", answer: "She came here two years ago.", errorType: "interference", explainHe: "'לפני שנתיים' = two years ago." },
      { id: "g-for-since-16", type: "fix", prompt: "I haven't finished already.", answer: "I haven't finished yet.", errorType: "word-choice", explainHe: "בשלילה: yet, בסוף המשפט." },
      { id: "g-for-since-17", type: "fix", prompt: "We are married since 2010.", answer: "We have been married since 2010.", errorType: "tense", explainHe: "since דורש Present Perfect: have been married." },
      { id: "g-for-since-18", type: "transform", prompt: "The last time I ate meat was in 2020.", keyword: "since", answer: "I haven't eaten meat since 2020.", explainHe: "'הפעם האחרונה הייתה ב-2020' = 'לא אכלתי מאז 2020'." },
      { id: "g-for-since-19", type: "transform", prompt: "She started working here six months ago.", keyword: "for", answer: "She has worked here for six months.", accept: ["She has been working here for six months."], explainHe: "פעולה שהתחילה לפני זמן מה ונמשכת: הווה מושלם עם for." },
      { id: "g-for-since-20", type: "transform", prompt: "I finished the report a minute ago.", keyword: "just", answer: "I have just finished the report.", accept: ["I just finished the report."], explainHe: "'לפני רגע' = have just + הצורה השלישית." },
      { id: "g-for-since-21", type: "order", words: ["how", "long", "have", "you", "been", "here?"], answer: "How long have you been here?", explainHe: "How long + have + נושא + been." },
      { id: "g-for-since-22", type: "order", words: ["they", "haven't", "called", "us", "yet"], answer: "They haven't called us yet.", explainHe: "yet תמיד בסוף המשפט." },
      { id: "g-for-since-23", type: "translate", he: "אנחנו גרים כאן משנת 2015.", answer: "We have lived here since 2015.", accept: ["We have been living here since 2015."], explainHe: "'מ-2015' = since 2015, והפועל ב-Present Perfect." },
      { id: "g-for-since-24", type: "translate", he: "הוא עזב לפני שעה.", answer: "He left an hour ago.", accept: ["He left one hour ago."], explainHe: "'לפני שעה' = an hour ago + Past Simple." },
    ],
  },

  // ---------------------------------------------------------------------------
  // 7. Present perfect continuous
  // ---------------------------------------------------------------------------
  {
    id: "g-present-perfect-continuous",
    title: "Present perfect continuous",
    titleHe: "הווה מושלם ממושך",
    strand: "tenses",
    order: 7,
    prereqs: ["g-present-perfect-vs-past"],
    lesson: {
      explanationHe: [
        "Present Perfect Continuous מדגיש את הפעילות עצמה ואת משך הזמן שלה: משהו התחיל בעבר, ואנחנו מסתכלים על התהליך שנמשך עד עכשיו. 'I've been waiting for an hour' – אני באמצע ההמתנה, וזה כבר שעה. 'It's been raining all day' – ועדיין יורד.",
        "שימוש שני: פעילות שהרגע נגמרה ורואים את הסימנים שלה. 'You're out of breath. Have you been running?' 'Her eyes are red. She's been crying.' התוצאה בהווה נובעת מהפעילות, לא מהסיום שלה.",
        "מול Present Perfect הרגיל: Simple מדגיש תוצאה, השלמה או כמות ('I've written three emails' – שלושה, סיימתי). Continuous מדגיש את הפעילות ואת הזמן ('I've been writing emails all morning' – כל הבוקר, אולי עוד לא סיימתי).",
        "הצורה: have/has + been + פועל עם ing. שלילה: haven't/hasn't been + ing. שאלה: Have you been waiting? How long has she been working here?",
        "פעלי מצב (know, like, have במובן 'יש', be) לא מקבלים ing גם כאן: 'I have known her for years', לא 'I have been knowing'. עם live ו-work שתי הצורות טובות: 'I've lived here / I've been living here for ten years'.",
      ],
      form: [
        { label: "(+)", example: "I have been waiting — she has been working" },
        { label: "(-)", example: "I haven't been sleeping well — he hasn't been studying" },
        { label: "(?)", example: "Have you been running? — How long has it been raining?" },
        { label: "משך", example: "I've been learning English for ten years / since I was six." },
        { label: "סימנים בהווה", example: "You look tired. Have you been working all night?" },
        { label: "Simple מול Continuous", example: "I've read three books. / I've been reading all day." },
      ],
      examples: [
        { en: "I've been waiting for you for an hour!", he: "אני מחכה לך כבר שעה!" },
        { en: "She has been learning English since she was six.", he: "היא לומדת אנגלית מאז שהייתה בת שש." },
        { en: "You're out of breath. Have you been running?", he: "אתה חסר נשימה. רצת?" },
        { en: "It has been raining all day.", he: "יורד גשם כל היום." },
        { en: "How long have they been living here?", he: "כמה זמן הם גרים פה?" },
        { en: "He hasn't been sleeping well lately.", he: "הוא לא ישן טוב לאחרונה." },
        { en: "We've been working on this project for three months.", he: "אנחנו עובדים על הפרויקט הזה שלושה חודשים." },
      ],
      contrastHe: [
        "'אני מחכה כבר שעה' – בעברית הווה. באנגלית: I have been waiting for an hour. לא 'I am waiting for an hour'.",
        "'כמה זמן את לומדת אנגלית?' → How long have you been learning English? לא 'How long are you learning'.",
        "בעברית 'ישבתי' ו'אני יושב כבר שעה' הן שתי צורות שונות; באנגלית מוסיפים שכבה שלישית: have been sitting, שמחברת עבר להווה.",
      ],
      commonErrors: [
        { wrong: "I am waiting here for two hours.", right: "I have been waiting here for two hours.", whyHe: "משך זמן עד עכשיו = Present Perfect Continuous, לא Present Continuous." },
        { wrong: "She has been knowing him for years.", right: "She has known him for years.", whyHe: "know הוא פועל מצב, בלי ing." },
        { wrong: "How long are you learning English?", right: "How long have you been learning English?", whyHe: "How long + עד עכשיו = have been + ing." },
        { wrong: "I've been finish my homework.", right: "I've finished my homework.", whyHe: "been דורש ing; אם מדגישים סיום – Present Perfect Simple." },
        { wrong: "It's raining since morning.", right: "It's been raining since morning.", whyHe: "since מסמן משך עד עכשיו: has been raining." },
      ],
    },
    items: [
      { id: "g-present-perfect-continuous-01", type: "gap", prompt: "I ___ (wait) for you for an hour!", answer: "have been waiting", explainHe: "פעילות שנמשכת כבר שעה = have been waiting." },
      { id: "g-present-perfect-continuous-02", type: "gap", prompt: "She ___ (learn) English since she was six and she's still learning.", answer: "has been learning", accept: ["has learned"], explainHe: "התחיל בילדות ונמשך = has been learning." },
      { id: "g-present-perfect-continuous-03", type: "gap", prompt: "You're out of breath. ___ (you/run)?", answer: "Have you been running", explainHe: "סימנים בהווה של פעילות שהרגע נגמרה = Have you been running?" },
      { id: "g-present-perfect-continuous-04", type: "gap", prompt: "It ___ (rain) all day and it hasn't stopped.", answer: "has been raining", explainHe: "פעילות שנמשכת כל היום = has been raining." },
      { id: "g-present-perfect-continuous-05", type: "gap", prompt: "How long ___ (they/live) here?", answer: "have they been living", accept: ["have they lived"], explainHe: "How long + עד עכשיו: have they been living (גם have they lived נכון)." },
      { id: "g-present-perfect-continuous-06", type: "gap", prompt: "He ___ (not/sleep) well lately.", answer: "hasn't been sleeping", explainHe: "lately = תקופה אחרונה שנמשכת: hasn't been sleeping." },
      { id: "g-present-perfect-continuous-07", type: "gap", prompt: "We ___ (work) on this project for three months, and it's still not done.", answer: "have been working", explainHe: "הדגש על התהליך שנמשך ולא הסתיים = have been working." },
      { id: "g-present-perfect-continuous-08", type: "gap", prompt: "I ___ (read) this book for weeks, but I'm only on page 50.", answer: "have been reading", explainHe: "פעילות ממושכת שלא הסתיימה = have been reading." },
      {
        id: "g-present-perfect-continuous-09", type: "mcq", prompt: "Her eyes are red. She ___.",
        options: [
          { text: "has been crying" },
          { text: "has cried", errorType: "aspect", whyHe: "הסימנים בהווה מצביעים על הפעילות עצמה: Continuous." },
          { text: "is crying", errorType: "tense", whyHe: "היא לא בוכה עכשיו; רואים את התוצאה של הבכי." },
          { text: "cried", errorType: "tense", whyHe: "Past Simple מנתק מההווה; כאן הקשר להווה הוא העיקר." },
        ],
        answerIndex: 0, explainHe: "סימנים בהווה של פעילות שהרגע נגמרה = has been + ing.",
      },
      {
        id: "g-present-perfect-continuous-10", type: "mcq", prompt: "I ___ three emails so far this morning.",
        options: [
          { text: "have written" },
          { text: "have been writing", errorType: "aspect", whyHe: "כשיש כמות (three), מדגישים תוצאה: Present Perfect Simple." },
          { text: "write", errorType: "tense", whyHe: "הווה פשוט = הרגל." },
          { text: "am writing", errorType: "aspect", whyHe: "שלושה מיילים כבר נכתבו; זה לא בתהליך." },
        ],
        answerIndex: 0, explainHe: "כמות שהושלמה עד עכשיו = Present Perfect Simple.",
      },
      {
        id: "g-present-perfect-continuous-11", type: "mcq", prompt: "How long ___ each other?",
        options: [
          { text: "have you known" },
          { text: "have you been knowing", errorType: "aspect", whyHe: "know הוא פועל מצב, לא מקבל ing." },
          { text: "do you know", errorType: "tense", whyHe: "How long + עד עכשיו = Present Perfect." },
          { text: "are you knowing", errorType: "aspect", whyHe: "know לא בא ב-Continuous." },
        ],
        answerIndex: 0, explainHe: "פועל מצב: Present Perfect Simple גם עם How long.",
      },
      {
        id: "g-present-perfect-continuous-12", type: "mcq", prompt: "They ___ tennis for two hours and they're exhausted.",
        options: [
          { text: "have been playing" },
          { text: "played", errorType: "tense", whyHe: "הקשר להווה (עייפים עכשיו) + משך = Present Perfect Continuous." },
          { text: "are playing", errorType: "tense", whyHe: "for two hours מחייב Perfect." },
          { text: "have play", errorType: "verb-form", whyHe: "חסר been + ing." },
        ],
        answerIndex: 0, explainHe: "משך + תוצאה עכשיו = have been playing.",
      },
      {
        id: "g-present-perfect-continuous-13", type: "mcq", prompt: "I ___ for this company since March.",
        options: [
          { text: "have been working" },
          { text: "am working", errorType: "tense", whyHe: "since March = התחלה בעבר; חייב Perfect." },
          { text: "work", errorType: "tense", whyHe: "בעברית 'אני עובד מאז מרץ', באנגלית have been working." },
          { text: "have working", errorType: "verb-form", whyHe: "חסר been." },
        ],
        answerIndex: 0, explainHe: "since + פעילות שנמשכת = have been working.",
      },
      { id: "g-present-perfect-continuous-14", type: "fix", prompt: "I am waiting here for two hours.", answer: "I have been waiting here for two hours.", errorType: "tense", explainHe: "for two hours עד עכשיו = have been waiting." },
      { id: "g-present-perfect-continuous-15", type: "fix", prompt: "She has been knowing him for years.", answer: "She has known him for years.", errorType: "aspect", explainHe: "know הוא פועל מצב: has known." },
      { id: "g-present-perfect-continuous-16", type: "fix", prompt: "I've been finish my homework.", answer: "I have finished my homework.", accept: ["I've finished my homework."], errorType: "verb-form", explainHe: "סיום = Present Perfect Simple: have finished." },
      { id: "g-present-perfect-continuous-17", type: "fix", prompt: "How long are you learning English?", answer: "How long have you been learning English?", accept: ["How long have you learned English?"], errorType: "tense", explainHe: "How long על משהו שנמשך עד עכשיו = have been learning." },
      { id: "g-present-perfect-continuous-18", type: "transform", prompt: "I started studying at 9. It's 12 now and I'm still studying.", keyword: "for", answer: "I have been studying for three hours.", explainHe: "מ-9 עד 12 = שלוש שעות, ועדיין ממשיך: have been studying for." },
      { id: "g-present-perfect-continuous-19", type: "transform", prompt: "She began working here in January. She still works here.", keyword: "since", answer: "She has been working here since January.", accept: ["She has worked here since January."], explainHe: "התחלה + עדיין נמשך = has been working since." },
      { id: "g-present-perfect-continuous-20", type: "transform", prompt: "He is tired because he ran.", keyword: "been", answer: "He is tired because he has been running.", explainHe: "התוצאה עכשיו (עייף) מוסברת בפעילות: has been running." },
      { id: "g-present-perfect-continuous-21", type: "order", words: ["how", "long", "have", "you", "been", "waiting?"], answer: "How long have you been waiting?", explainHe: "How long + have + נושא + been + ing." },
      { id: "g-present-perfect-continuous-22", type: "order", words: ["it", "has", "been", "snowing", "since", "morning"], answer: "It has been snowing since morning.", explainHe: "has been + ing + since + נקודת התחלה." },
      { id: "g-present-perfect-continuous-23", type: "translate", he: "אני מחכה לך כבר שעה!", answer: "I have been waiting for you for an hour!", accept: ["I have been waiting for you for one hour!", "I have been waiting for you for an hour already!", "I have been waiting an hour for you!"], explainHe: "הווה בעברית, אבל משך עד עכשיו = have been waiting." },
      { id: "g-present-perfect-continuous-24", type: "translate", he: "כמה זמן את לומדת עברית?", answer: "How long have you been learning Hebrew?", accept: ["How long have you been studying Hebrew?", "How long have you learned Hebrew?", "How long have you studied Hebrew?"], explainHe: "How long + פעילות שנמשכת = have you been learning." },
    ],
  },

  // ---------------------------------------------------------------------------
  // 8. Past perfect
  // ---------------------------------------------------------------------------
  {
    id: "g-past-perfect",
    title: "Past perfect",
    titleHe: "עבר מושלם (Past Perfect)",
    strand: "tenses",
    order: 8,
    prereqs: ["g-present-perfect-vs-past"],
    lesson: {
      explanationHe: [
        "Past Perfect הוא 'העבר של העבר'. כשאנחנו כבר בתוך סיפור בעבר ורוצים לקפוץ אחורה למשהו שקרה עוד קודם, משתמשים בו. 'When I got to the station, the train had already left' – ההגעה בעבר, והרכבת יצאה לפני כן.",
        "הוא כמעט תמיד מופיע ליד Past Simple: הפעולה המאוחרת ב-Past Simple, המוקדמת ב-Past Perfect. מילות מפתח: when, by the time, before, after, because, already, never...before, וגם פעלים כמו realized, found out, knew.",
        "שימוש טיפוסי הוא הסבר של סיבה: 'I couldn't get in because I had lost my keys'. וניסיון עד נקודה בעבר: 'She had never flown before that trip'.",
        "הצורה: had + הצורה השלישית, לכל הגופים. שלילה: hadn't. שאלה: Had you met him before? already ו-never נכנסים בין had לפועל.",
        "לא להגזים: אם הסיפור מתקדם בסדר כרונולוגי, הכל ב-Past Simple. 'I woke up, had coffee and left'. Past Perfect רק כשקופצים אחורה. ועם after/before הסדר כבר ברור, אז Past Simple מקובל גם כן.",
      ],
      form: [
        { label: "(+)", example: "I had finished — she had gone — they had already left" },
        { label: "(-)", example: "I hadn't eaten — he hadn't seen it" },
        { label: "(?)", example: "Had you met him before? — What had happened?" },
        { label: "עם when / by the time", example: "By the time we arrived, the movie had started." },
        { label: "סיבה", example: "She was tired because she hadn't slept." },
      ],
      examples: [
        { en: "When I got to the station, the train had already left.", he: "כשהגעתי לתחנה, הרכבת כבר יצאה." },
        { en: "She had never flown before that trip.", he: "היא מעולם לא טסה לפני הטיול ההוא." },
        { en: "I couldn't get in because I had lost my keys.", he: "לא יכולתי להיכנס כי איבדתי את המפתחות." },
        { en: "By the time we arrived, the movie had started.", he: "עד שהגענו, הסרט כבר התחיל." },
        { en: "He hadn't eaten all day, so he was starving.", he: "הוא לא אכל כל היום, אז הוא גווע מרעב." },
        { en: "Had you met him before the wedding?", he: "הכרת אותו לפני החתונה?" },
        { en: "They had known each other for years before they got married.", he: "הם הכירו שנים לפני שהתחתנו." },
      ],
      contrastHe: [
        "בעברית יש רק עבר אחד: 'כשהגעתי, הם כבר הלכו'. המילה 'כבר' עושה את העבודה. באנגלית 'כבר' + סדר הזמנים = had already left.",
        "'איבדתי את המפתחות' יכול להיות have lost (עכשיו אין לי), lost (סיפור), או had lost (לפני משהו אחר בעבר). ההקשר קובע.",
        "אין צורך ב-Past Perfect כשמספרים לפי הסדר. 'קמתי, שתיתי קפה ויצאתי' = Past Simple בלבד.",
      ],
      commonErrors: [
        { wrong: "When I arrived, the meeting has already started.", right: "When I arrived, the meeting had already started.", whyHe: "כל הסיפור בעבר: had, לא has." },
        { wrong: "I had went home before the storm.", right: "I had gone home before the storm.", whyHe: "had + הצורה השלישית: gone." },
        { wrong: "By the time he came, we finished dinner.", right: "By the time he came, we had finished dinner.", whyHe: "by the time = הפעולה השנייה כבר הושלמה לפני כן." },
        { wrong: "Yesterday I had visited my grandmother.", right: "Yesterday I visited my grandmother.", whyHe: "אין עבר לפני עבר כאן; סיפור פשוט = Past Simple." },
        { wrong: "I never had seen snow before.", right: "I had never seen snow before.", whyHe: "never נכנס בין had לפועל." },
      ],
    },
    items: [
      { id: "g-past-perfect-01", type: "gap", prompt: "When I got to the station, the train ___ (already/leave).", answer: "had already left", explainHe: "הרכבת יצאה לפני שהגעתי: had already left." },
      { id: "g-past-perfect-02", type: "gap", prompt: "She ___ (never/fly) before that trip.", answer: "had never flown", explainHe: "ניסיון עד נקודה בעבר: had never flown." },
      { id: "g-past-perfect-03", type: "gap", prompt: "I couldn't get in because I ___ (lose) my keys.", answer: "had lost", explainHe: "האובדן קרה לפני הניסיון להיכנס: had lost." },
      { id: "g-past-perfect-04", type: "gap", prompt: "By the time we arrived, the movie ___ (start).", answer: "had started", explainHe: "by the time = הפעולה כבר הושלמה קודם: had started." },
      { id: "g-past-perfect-05", type: "gap", prompt: "He ___ (not/eat) all day, so he was starving.", answer: "hadn't eaten", explainHe: "הסיבה קדמה לרעב: hadn't eaten." },
      { id: "g-past-perfect-06", type: "gap", prompt: "___ (you/meet) him before the wedding?", answer: "Had you met", explainHe: "שאלה על מה שקרה לפני נקודה בעבר: Had you met?" },
      { id: "g-past-perfect-07", type: "gap", prompt: "They ___ (know) each other for years before they got married.", answer: "had known", explainHe: "משך זמן עד נקודה בעבר (החתונה): had known." },
      { id: "g-past-perfect-08", type: "gap", prompt: "After she ___ (finish) her degree, she moved to London.", answer: "had finished", accept: ["finished"], explainHe: "הסיום קדם למעבר: had finished. (עם after גם finished מקובל.)" },
      {
        id: "g-past-perfect-09", type: "mcq", prompt: "When we got home, someone ___ into the house.",
        options: [
          { text: "had broken" },
          { text: "broke", errorType: "tense", whyHe: "הפריצה קרתה לפני שהגענו: עבר של העבר." },
          { text: "has broken", errorType: "tense", whyHe: "הסיפור כולו בעבר: had, לא has." },
          { text: "was breaking", errorType: "aspect", whyHe: "זה לא היה בתהליך כשהגענו; זה כבר נגמר." },
        ],
        answerIndex: 0, explainHe: "פעולה שהושלמה לפני נקודה בעבר = had + הצורה השלישית.",
      },
      {
        id: "g-past-perfect-10", type: "mcq", prompt: "I ___ the film before, so I knew the ending.",
        options: [
          { text: "had seen" },
          { text: "saw", errorType: "tense", whyHe: "before + ידעתי את הסוף: הצפייה קדמה לידיעה." },
          { text: "have seen", errorType: "tense", whyHe: "knew בעבר; הכל צריך להיות בעבר." },
          { text: "had saw", errorType: "verb-form", whyHe: "had + seen." },
        ],
        answerIndex: 0, explainHe: "ניסיון לפני נקודה בעבר = had seen.",
      },
      {
        id: "g-past-perfect-11", type: "mcq", prompt: "By the time I called, he ___.",
        options: [
          { text: "had already left" },
          { text: "already left", errorType: "tense", whyHe: "by the time מחייב Past Perfect: had left." },
          { text: "has already left", errorType: "tense", whyHe: "called בעבר; לא has." },
          { text: "was already leaving", errorType: "aspect", whyHe: "already + הושלם = Perfect, לא Continuous." },
        ],
        answerIndex: 0, explainHe: "המבנה הנכון: by the time + already = had already left.",
      },
      {
        id: "g-past-perfect-12", type: "mcq", prompt: "When I got to the store, I realized I ___ my wallet at home.",
        options: [
          { text: "had left" },
          { text: "have left", errorType: "tense", whyHe: "realized בעבר: had, לא have." },
          { text: "was leaving", errorType: "aspect", whyHe: "הארנק כבר נשאר בבית; זה לא בתהליך." },
          { text: "had leave", errorType: "verb-form", whyHe: "had + left." },
        ],
        answerIndex: 0, explainHe: "realized + מה שקרה קודם = had left.",
      },
      {
        id: "g-past-perfect-13", type: "mcq", prompt: "They ___ dinner by the time I arrived.",
        options: [
          { text: "had already eaten" },
          { text: "already ate", errorType: "tense", whyHe: "by the time = הושלם לפני: had eaten." },
          { text: "have already eaten", errorType: "tense", whyHe: "arrived בעבר; לא have." },
          { text: "were already eating", errorType: "aspect", whyHe: "'כבר אכלו' = סיימו, לא באמצע." },
        ],
        answerIndex: 0, explainHe: "by the time + פעולה שהושלמה = had already eaten.",
      },
      { id: "g-past-perfect-14", type: "fix", prompt: "When I arrived, the meeting has already started.", answer: "When I arrived, the meeting had already started.", errorType: "tense", explainHe: "סיפור בעבר: had, לא has." },
      { id: "g-past-perfect-15", type: "fix", prompt: "I had went home before the storm.", answer: "I had gone home before the storm.", errorType: "verb-form", explainHe: "had + הצורה השלישית: gone." },
      { id: "g-past-perfect-16", type: "fix", prompt: "By the time he came, we finished dinner.", answer: "By the time he came, we had finished dinner.", errorType: "tense", explainHe: "by the time = הושלם קודם = had finished." },
      { id: "g-past-perfect-17", type: "fix", prompt: "Yesterday I had visited my grandmother.", answer: "Yesterday I visited my grandmother.", errorType: "tense", explainHe: "אין כאן עבר לפני עבר: Past Simple." },
      { id: "g-past-perfect-18", type: "transform", prompt: "First I finished work. Then I called her.", keyword: "after", answer: "After I had finished work, I called her.", accept: ["I called her after I had finished work.", "After I finished work, I called her.", "I called her after I finished work."], explainHe: "הפעולה הראשונה ב-Past Perfect, השנייה ב-Past Simple." },
      { id: "g-past-perfect-19", type: "transform", prompt: "The bus left. Then we got to the stop.", keyword: "already", answer: "When we got to the stop, the bus had already left.", accept: ["The bus had already left when we got to the stop.", "By the time we got to the stop, the bus had already left.", "The bus had already left by the time we got to the stop."], explainHe: "היציאה קדמה להגעה: had already left." },
      { id: "g-past-perfect-20", type: "transform", prompt: "It was my first time on a plane.", keyword: "never", answer: "I had never been on a plane before.", accept: ["I had never flown before.", "I had never been in a plane before.", "I had never been on a plane."], explainHe: "פעם ראשונה בעבר = had never + before." },
      { id: "g-past-perfect-21", type: "order", words: ["she", "had", "never", "seen", "snow", "before"], answer: "She had never seen snow before.", explainHe: "had + never + הצורה השלישית + before." },
      { id: "g-past-perfect-22", type: "order", words: ["had", "the", "movie", "started", "when", "you", "arrived?"], answer: "Had the movie started when you arrived?", explainHe: "Had + נושא + הצורה השלישית; when + Past Simple." },
      { id: "g-past-perfect-23", type: "translate", he: "כשהגעתי, הם כבר הלכו.", answer: "When I arrived, they had already left.", accept: ["When I arrived, they had already gone.", "When I got there, they had already left.", "They had already left when I arrived.", "When I came, they had already left."], explainHe: "'כבר' + לפני ההגעה = had already left." },
      { id: "g-past-perfect-24", type: "translate", he: "היא הייתה רעבה כי היא לא אכלה כל היום.", answer: "She was hungry because she hadn't eaten all day.", accept: ["She was hungry because she had not eaten all day.", "She was hungry because she hadn't eaten anything all day."], explainHe: "הסיבה קדמה לרעב: hadn't eaten." },
    ],
  },
];
