import type { GrammarTopic } from "@/lib/types";

export const TENSES_FUTURE: GrammarTopic[] = [
  // ---------------------------------------------------------------------------
  // 9. Future: will, going to, present continuous
  // ---------------------------------------------------------------------------
  {
    id: "g-future-forms",
    title: "Future: will, going to, present continuous",
    titleHe: "צורות עתיד",
    strand: "tenses",
    order: 9,
    prereqs: ["g-present-simple-continuous"],
    lesson: {
      explanationHe: [
        "בעברית יש עתיד אחד: 'אתקשר', 'אסע', 'אעשה'. באנגלית יש כמה צורות, והבחירה ביניהן היא לפי המשמעות – מה עומד מאחורי המשפט – ולא לפי הזמן. השאלה היא תמיד: זו החלטה של הרגע? תוכנית שכבר קיימת? סידור סגור? או לוח זמנים רשמי?",
        "will = החלטה שנולדת ברגע הדיבור, הצעה, הבטחה, וגם ניחוש או דעה על העתיד. 'The phone's ringing – I'll get it' (החלטתי עכשיו). 'I promise I'll help you'. 'I think it'll be hot tomorrow'. מילים כמו I think, probably, maybe, I'm sure מושכות ל-will.",
        "going to = תוכנית או כוונה שכבר החלטתי עליה קודם, וגם חיזוי שמבוסס על משהו שרואים עכשיו. 'I'm going to look for a new job' (כבר החלטתי). 'Look at those clouds – it's going to rain' (העדות מול העיניים).",
        "Present Continuous = סידור סגור עם אנשים, זמן או מקום: פגישה ביומן, כרטיס שנקנה. 'We're meeting the lawyer at four'. Present Simple = לוחות זמנים רשמיים: טיסות, רכבות, סרטים, שיעורים. 'The train leaves at 6:40'.",
        "הצורה: will + פועל בסיסי, בלי to לעולם ('I will call', ולא 'I will to call'). קיצור: I'll, שלילה: won't. going to: am/is/are + going to + פועל בסיסי, שלילה: isn't going to. Present Continuous: am/is/are + ing.",
      ],
      form: [
        { label: "will (+)", example: "I'll call you — she will help — they'll be here soon" },
        { label: "will (-) / (?)", example: "I won't be late — Will you help me?" },
        { label: "going to (+)", example: "I'm going to study medicine — it's going to rain" },
        { label: "going to (-)", example: "We aren't going to sell the car." },
        { label: "סידור (Present Continuous)", example: "We're meeting Dana on Sunday at eight." },
        { label: "לוח זמנים (Present Simple)", example: "The flight leaves at 6:40 tomorrow." },
      ],
      examples: [
        { en: "Don't worry, I'll call you tomorrow morning.", he: "אל תדאג, אתקשר אליך מחר בבוקר." },
        { en: "Look at those clouds! It's going to rain.", he: "תראה את העננים האלה! עוד רגע יורד גשם." },
        { en: "I'm going to look for a new job this year.", he: "אני הולך לחפש עבודה חדשה השנה." },
        { en: "We're flying to Rome on Sunday. We've got the tickets.", he: "אנחנו טסים לרומא ביום ראשון. יש לנו כבר כרטיסים." },
        { en: "The meeting starts at nine sharp.", he: "הפגישה מתחילה בתשע בדיוק." },
        { en: "That bag looks heavy. I'll help you.", he: "התיק הזה נראה כבד. אני אעזור לך." },
        { en: "I don't think they'll win the game.", he: "אני לא חושב שהם ינצחו במשחק." },
        { en: "What are you doing this weekend?", he: "מה את עושה בסוף השבוע?" },
      ],
      contrastHe: [
        "בעברית 'אעשה את זה' מכסה הכול. באנגלית צריך לבחור: I'll do it (החלטתי עכשיו), I'm going to do it (החלטתי קודם), I'm doing it (זה כבר קבוע ביומן).",
        "'אני הולך ל...' בעברית זה לפעמים הליכה ממש ולפעמים כוונה. going to באנגלית הוא רק כוונה או חיזוי – 'I'm going to the gym' פירושו שאני נוסע/הולך לשם, ו-'I'm going to train' פירושו שהתכוונתי להתאמן.",
        "דוברי עברית מוסיפים to אחרי will, כי בעברית אומרים 'אני עומד לעשות'. באנגלית: will + פועל בסיסי, בלי to.",
        "לוחות זמנים בעברית נאמרים בעתיד: 'הרכבת תצא בשש'. באנגלית משתמשים בהווה פשוט: 'The train leaves at six'.",
      ],
      commonErrors: [
        { wrong: "I will to call you tonight.", right: "I'll call you tonight.", whyHe: "אחרי will בא פועל בסיסי, בלי to." },
        { wrong: "Tomorrow I will go to the dentist, I have an appointment.", right: "Tomorrow I'm going to the dentist, I have an appointment.", whyHe: "יש תור – זה סידור סגור, ולכן Present Continuous." },
        { wrong: "Look at the sky, it will rain.", right: "Look at the sky, it's going to rain.", whyHe: "יש עדות מול העיניים עכשיו, ולכן going to." },
        { wrong: "That's the doorbell. I am going to get it.", right: "That's the doorbell. I'll get it.", whyHe: "החלטה שנולדת ברגע הדיבור = will." },
        { wrong: "The train will leave at eight every morning.", right: "The train leaves at eight every morning.", whyHe: "לוח זמנים קבוע = Present Simple." },
      ],
    },
    items: [
      { id: "g-future-forms-01", type: "gap", prompt: "Look at those clouds! It ___ (rain).", answer: "is going to rain", accept: ["'s going to rain"], explainHe: "יש עדות מול העיניים ברגע הזה, ולכן going to ולא will." },
      { id: "g-future-forms-02", type: "gap", prompt: "I promise I ___ (call) you tonight.", answer: "will call", accept: ["'ll call"], explainHe: "הבטחה = will." },
      { id: "g-future-forms-03", type: "gap", prompt: "We ___ (meet) the lawyer at four tomorrow. It's in the calendar.", answer: "are meeting", accept: ["'re meeting", "are going to meet", "'re going to meet"], explainHe: "סידור סגור ביומן = Present Continuous." },
      { id: "g-future-forms-04", type: "gap", prompt: "The train ___ (leave) at 6:40 tomorrow morning.", answer: "leaves", accept: ["is leaving", "'s leaving"], explainHe: "לוח זמנים רשמי = Present Simple: leaves." },
      { id: "g-future-forms-05", type: "gap", prompt: "The phone is ringing. Don't get up, I ___ (get) it.", answer: "will get", accept: ["'ll get"], explainHe: "החלטה ברגע הדיבור = will." },
      { id: "g-future-forms-06", type: "gap", prompt: "She has already bought the paint. She ___ (paint) the kitchen this weekend.", answer: "is going to paint", accept: ["'s going to paint", "is painting", "'s painting"], explainHe: "כוונה שכבר הוחלטה (הצבע נקנה) = going to." },
      { id: "g-future-forms-07", type: "gap", prompt: "I don't think they ___ (win) the game.", answer: "will win", accept: ["'ll win"], explainHe: "I think / I don't think = דעה על העתיד = will." },
      { id: "g-future-forms-08", type: "gap", prompt: "___ (you/come) to the party on Friday?", answer: "Are you coming", accept: ["Are you going to come"], explainHe: "שאלה על סידור לסוף השבוע = Present Continuous." },
      {
        id: "g-future-forms-09", type: "mcq", prompt: "I can't come tonight. I ___ my parents at the airport.",
        options: [
          { text: "am meeting" },
          { text: "will meet", errorType: "tense", whyHe: "זה סידור שכבר קבוע, לא החלטה של הרגע." },
          { text: "meet", errorType: "tense", whyHe: "הווה פשוט לעתיד רק בלוחות זמנים (טיסות, סרטים)." },
          { text: "am meet", errorType: "verb-form", whyHe: "אחרי am חייב לבוא ing: am meeting." },
        ],
        answerIndex: 0, explainHe: "סידור אישי סגור לזמן מסוים = Present Continuous.",
      },
      {
        id: "g-future-forms-10", type: "mcq", prompt: "That bag looks heavy. I ___ you with it.",
        options: [
          { text: "'ll help" },
          { text: "'m going to help", errorType: "tense", whyHe: "going to = החלטה שכבר קיימת. כאן ההצעה נולדת ברגע הזה." },
          { text: "help", errorType: "tense", whyHe: "הווה פשוט לא מביע הצעה לעתיד." },
          { text: "will to help", errorType: "verb-form", whyHe: "אחרי will אין to." },
        ],
        answerIndex: 0, explainHe: "הצעת עזרה ספונטנית = will.",
      },
      {
        id: "g-future-forms-11", type: "mcq", prompt: "Look out! We ___ into that car!",
        options: [
          { text: "are going to crash" },
          { text: "will crash", errorType: "tense", whyHe: "יש עדות מול העיניים ממש עכשיו, ולכן going to ולא ניחוש." },
          { text: "crash", errorType: "tense", whyHe: "הווה פשוט לא מתאר עתיד מיידי כזה." },
          { text: "are going to crashing", errorType: "verb-form", whyHe: "אחרי going to בא פועל בסיסי: crash." },
        ],
        answerIndex: 0, explainHe: "חיזוי שמבוסס על מה שרואים עכשיו = going to.",
      },
      {
        id: "g-future-forms-12", type: "mcq", prompt: "Don't wait for me. I ___ home before ten.",
        options: [
          { text: "won't be" },
          { text: "don't be", errorType: "verb-form", whyHe: "שלילה בעתיד = won't, לא don't." },
          { text: "am not going to being", errorType: "verb-form", whyHe: "אחרי going to בא פועל בסיסי: be." },
          { text: "will not to be", errorType: "verb-form", whyHe: "אחרי will אין to." },
        ],
        answerIndex: 0, explainHe: "שלילה של will: won't + פועל בסיסי.",
      },
      {
        id: "g-future-forms-13", type: "mcq", prompt: "— We're out of milk. — Really? I ___ some on my way home.",
        options: [
          { text: "'ll buy" },
          { text: "'m buying", errorType: "aspect", whyHe: "אין כאן סידור מראש; שמעתי עכשיו והחלטתי." },
          { text: "'m going to buy", errorType: "tense", whyHe: "going to = החלטה שכבר הייתה. כאן היא נולדה ברגע הזה." },
          { text: "buy", errorType: "tense", whyHe: "הווה פשוט אינו עתיד כאן." },
        ],
        answerIndex: 0, explainHe: "תגובה מיידית למידע חדש = will.",
      },
      { id: "g-future-forms-14", type: "fix", prompt: "I will to call you tonight.", answer: "I will call you tonight.", accept: ["I'll call you tonight."], errorType: "verb-form", explainHe: "אחרי will בא פועל בסיסי, בלי to." },
      { id: "g-future-forms-15", type: "fix", prompt: "Tomorrow I will go to the dentist. I have an appointment.", answer: "Tomorrow I am going to the dentist. I have an appointment.", accept: ["Tomorrow I'm going to the dentist. I have an appointment."], errorType: "tense", explainHe: "יש תור – סידור סגור – ולכן Present Continuous." },
      { id: "g-future-forms-16", type: "fix", prompt: "Look at the sky. It will rain.", answer: "Look at the sky. It is going to rain.", accept: ["Look at the sky. It's going to rain."], errorType: "tense", explainHe: "עדות מול העיניים = going to." },
      { id: "g-future-forms-17", type: "fix", prompt: "That's the doorbell. I am going to get it.", answer: "That's the doorbell. I will get it.", accept: ["That's the doorbell. I'll get it."], errorType: "tense", explainHe: "החלטה ברגע הדיבור = will." },
      { id: "g-future-forms-18", type: "transform", prompt: "I've decided to look for a new job.", keyword: "going", answer: "I am going to look for a new job.", accept: ["I'm going to look for a new job."], explainHe: "כוונה שכבר הוחלטה = am going to + פועל בסיסי." },
      { id: "g-future-forms-19", type: "transform", prompt: "My flight is at seven tomorrow morning.", keyword: "leaves", answer: "My flight leaves at seven tomorrow morning.", explainHe: "לוח זמנים של טיסה = Present Simple." },
      { id: "g-future-forms-20", type: "transform", prompt: "We have arranged to meet Dana on Sunday.", keyword: "meeting", answer: "We are meeting Dana on Sunday.", accept: ["We're meeting Dana on Sunday."], explainHe: "סידור סגור עם אדם ובזמן מסוים = Present Continuous." },
      { id: "g-future-forms-21", type: "order", words: ["what", "are", "you", "doing", "on", "Saturday?"], answer: "What are you doing on Saturday?", explainHe: "שאלה על סידור: מילת שאלה + are + נושא + ing." },
      { id: "g-future-forms-22", type: "order", words: ["I", "don't", "think", "he", "will", "come"], answer: "I don't think he will come.", explainHe: "באנגלית השלילה יושבת על think: I don't think he will come." },
      { id: "g-future-forms-23", type: "translate", he: "אני חושב שירד גשם מחר.", answer: "I think it will rain tomorrow.", accept: ["I think it'll rain tomorrow.", "I think that it will rain tomorrow.", "I think it is going to rain tomorrow."], explainHe: "I think + דעה על העתיד = will." },
      { id: "g-future-forms-24", type: "translate", he: "מה את עושה מחר בערב?", answer: "What are you doing tomorrow evening?", accept: ["What are you doing tomorrow night?", "What are you doing tomorrow in the evening?"], explainHe: "שאלה על תוכניות סגורות = Present Continuous, לא will." },
    ],
  },

  // ---------------------------------------------------------------------------
  // 10. used to / would / be used to
  // ---------------------------------------------------------------------------
  {
    id: "g-used-to-would",
    title: "used to / would / be used to",
    titleHe: "used to ו-be used to",
    strand: "tenses",
    order: 10,
    prereqs: ["g-past-simple"],
    lesson: {
      explanationHe: [
        "used to + פועל בסיסי מתאר הרגל בעבר או מצב בעבר שכבר לא נכון היום. 'I used to smoke' = פעם עישנתי, והיום לא. זה מה שעושה בעברית המילה 'פעם': 'פעם גרתי בחיפה', 'פעם לא אהבתי דגים'.",
        "would + פועל בסיסי גם הוא מתאר הרגל בעבר, אבל רק פעולות חוזרות בתוך תקופה שאנחנו נזכרים בה: 'When I was a kid, we would go to my grandmother's every Saturday'. עם מצבים – live, be, have, know, like – would לא עובד. אומרים 'I used to live in Haifa', לא 'I would live in Haifa'.",
        "be used to הוא מבנה אחר לגמרי, ומשמעותו 'רגיל ל...'. אחריו בא שם עצם או פועל עם ing: 'I'm used to the noise', 'I'm used to getting up early'. וגם get used to = 'להתרגל ל': 'You'll get used to it'.",
        "הצורה: במשפט חיובי used to (עם d), אבל בשלילה ובשאלה ה-d עובר ל-did: 'I didn't use to like fish', 'Did you use to smoke?'. would פשוט יותר: would / wouldn't + פועל בסיסי.",
        "אפשר תמיד גם Past Simple: 'I smoked for ten years'. ההבדל הוא ש-used to מוסיף את המסר 'וזה נגמר'. כשמדובר במספר מוגדר של פעמים – 'I went to Eilat three times last year' – חייבים Past Simple.",
      ],
      form: [
        { label: "used to (+)", example: "I used to smoke — she used to live here" },
        { label: "used to (-)", example: "I didn't use to like fish." },
        { label: "used to (?)", example: "Did you use to play the piano?" },
        { label: "would (פעולה חוזרת)", example: "Every summer we would drive to the Galilee." },
        { label: "be used to + שם עצם / ing", example: "I'm used to the heat — I'm used to working nights." },
        { label: "get used to (להתרגל)", example: "You'll get used to the new system." },
      ],
      examples: [
        { en: "I used to smoke a pack a day, but I quit.", he: "פעם עישנתי קופסה ביום, אבל הפסקתי." },
        { en: "There used to be a bookstore here.", he: "פעם הייתה פה חנות ספרים." },
        { en: "When I was a kid, we would go to my grandmother's every Saturday.", he: "כשהייתי ילד, היינו נוסעים לסבתא כל שבת." },
        { en: "She used to have long hair.", he: "פעם היה לה שיער ארוך." },
        { en: "I didn't use to like fish, but now I eat everything.", he: "פעם לא אהבתי דגים, והיום אני אוכל הכול." },
        { en: "Did you use to work in a bank?", he: "עבדת פעם בבנק?" },
        { en: "I'm not used to driving on the left.", he: "אני לא רגיל לנהוג בצד שמאל." },
        { en: "After a month, I got used to the noise.", he: "אחרי חודש התרגלתי לרעש." },
      ],
      contrastHe: [
        "'הייתי הולך' בעברית הוא דו-משמעי: הרגל בעבר ('הייתי הולך לשם כל יום' = I used to go / I would go) או תנאי ('הייתי הולך אם היה לי זמן' = I would go if I had time). ההקשר מכריע.",
        "'פעם' בעברית = used to. 'רגיל ל' בעברית = be used to. שתי המילים דומות באנגלית ולכן מתבלבלות: 'I used to get up early' (פעם קמתי מוקדם) מול 'I'm used to getting up early' (אני רגיל לקום מוקדם).",
        "בעברית 'הייתי גר בחיפה' זה מצב, ובאנגלית מצב לא מקבל would. אומרים used to live, used to be, used to have, used to know.",
        "אחרי be used to בא ing, כי to כאן היא מילת יחס ולא חלק מהפועל: 'I'm used to working', ולא 'I'm used to work'.",
      ],
      commonErrors: [
        { wrong: "I am used to go to the beach every summer when I was a child.", right: "I used to go to the beach every summer when I was a child.", whyHe: "הרגל בעבר = used to, בלי am." },
        { wrong: "Did you used to smoke?", right: "Did you use to smoke?", whyHe: "אחרי did הפועל בצורה הבסיסית: use to." },
        { wrong: "I'm used to get up early.", right: "I'm used to getting up early.", whyHe: "אחרי be used to בא ing." },
        { wrong: "We would have a big house in Ramat Gan.", right: "We used to have a big house in Ramat Gan.", whyHe: "have כאן הוא מצב (בעלות), ולמצבים משתמשים ב-used to." },
        { wrong: "I use to play football when I was young.", right: "I used to play football when I was young.", whyHe: "במשפט חיובי חייבים d: used to." },
      ],
    },
    items: [
      { id: "g-used-to-would-01", type: "gap", prompt: "When I was a kid, we ___ (go) to my grandmother's every Saturday.", answer: "used to go", accept: ["would go"], explainHe: "הרגל חוזר בעבר: used to go, וגם would go מתאים לפעולה חוזרת." },
      { id: "g-used-to-would-02", type: "gap", prompt: "There ___ (be) a bookstore here, but it closed last year.", answer: "used to be", explainHe: "מצב בעבר שכבר לא קיים: used to be. עם be אי אפשר would." },
      { id: "g-used-to-would-03", type: "gap", prompt: "I ___ (not/like) fish, but now I eat it every week.", answer: "didn't use to like", accept: ["never used to like"], explainHe: "שלילה: didn't + use to (בלי d) + פועל בסיסי." },
      { id: "g-used-to-would-04", type: "gap", prompt: "___ (you/smoke) when you were younger?", answer: "Did you use to smoke", accept: ["Did you smoke"], explainHe: "שאלה: Did + נושא + use to + פועל בסיסי." },
      { id: "g-used-to-would-05", type: "gap", prompt: "I'm not ___ (drive) on the left. It really scares me.", answer: "used to driving", explainHe: "be used to = רגיל ל..., ואחריו פועל עם ing." },
      { id: "g-used-to-would-06", type: "gap", prompt: "After a month I got used to ___ (work) nights.", answer: "working", explainHe: "אחרי get used to בא ing, כי to היא מילת יחס." },
      { id: "g-used-to-would-07", type: "gap", prompt: "My father ___ (drive) us to school every morning before he sold the car.", answer: "used to drive", accept: ["would drive"], explainHe: "פעולה חוזרת בעבר: used to drive או would drive." },
      { id: "g-used-to-would-08", type: "gap", prompt: "She ___ (have) long hair when she was in high school.", answer: "used to have", explainHe: "have כאן הוא מצב, ולכן used to have ולא would have." },
      {
        id: "g-used-to-would-09", type: "mcq", prompt: "When we were students, we ___ stay up all night before exams.",
        options: [
          { text: "would" },
          { text: "are used to", errorType: "word-choice", whyHe: "be used to פירושו 'רגיל ל', ומדבר על ההווה." },
          { text: "use to", errorType: "verb-form", whyHe: "במשפט חיובי חייבים d: used to." },
          { text: "would to", errorType: "verb-form", whyHe: "אחרי would בא פועל בסיסי, בלי to." },
        ],
        answerIndex: 0, explainHe: "פעולה חוזרת בתקופה שנזכרים בה = would + פועל בסיסי.",
      },
      {
        id: "g-used-to-would-10", type: "mcq", prompt: "My grandparents ___ in a small village near Safed.",
        options: [
          { text: "used to live" },
          { text: "would live", errorType: "word-choice", whyHe: "would לא מתאים למצבים כמו live, be, have, know." },
          { text: "are used to live", errorType: "word-choice", whyHe: "be used to פירושו 'רגילים ל', ואחריו בא ing." },
          { text: "used to living", errorType: "verb-form", whyHe: "used to + פועל בסיסי: used to live." },
        ],
        answerIndex: 0, explainHe: "מצב בעבר שכבר לא נכון = used to + פועל בסיסי.",
      },
      {
        id: "g-used-to-would-11", type: "mcq", prompt: "Sorry, I'm exhausted. I ___ getting up this early.",
        options: [
          { text: "'m not used to" },
          { text: "didn't use to", errorType: "tense", whyHe: "הבעיה היא עכשיו – אני לא רגיל – ולא 'פעם לא'." },
          { text: "'m not use to", errorType: "spelling", whyHe: "במבנה be used to ה-d תמיד נשארת." },
          { text: "don't used to", errorType: "verb-form", whyHe: "אין צורה כזאת; השלילה של ההרגל היא didn't use to." },
        ],
        answerIndex: 0, explainHe: "'אני לא רגיל ל...' = I'm not used to + ing.",
      },
      {
        id: "g-used-to-would-12", type: "mcq", prompt: "___ live in Jerusalem?",
        options: [
          { text: "Did you use to" },
          { text: "Did you used to", errorType: "verb-form", whyHe: "אחרי did הפועל בצורה הבסיסית: use to." },
          { text: "Were you used to", errorType: "word-choice", whyHe: "זה שואל אם היית רגיל למשהו, לא אם גרת פעם." },
          { text: "Use you to", errorType: "question-form", whyHe: "שאלה בעבר נבנית עם did." },
        ],
        answerIndex: 0, explainHe: "שאלה על הרגל בעבר: Did + נושא + use to.",
      },
      {
        id: "g-used-to-would-13", type: "mcq", prompt: "I ___ to Eilat three times last year.",
        options: [
          { text: "went" },
          { text: "used to go", errorType: "tense", whyHe: "מספר מוגדר של פעמים בזמן מוגדר = Past Simple." },
          { text: "would go", errorType: "tense", whyHe: "would מתאר הרגל כללי, לא שלוש פעמים ספציפיות." },
          { text: "was used to go", errorType: "word-choice", whyHe: "be used to פירושו 'הייתי רגיל', ואחריו ing." },
        ],
        answerIndex: 0, explainHe: "כמות מוגדרת של פעמים בעבר = Past Simple.",
      },
      { id: "g-used-to-would-14", type: "fix", prompt: "I am used to go to the beach every summer when I was a child.", answer: "I used to go to the beach every summer when I was a child.", errorType: "word-choice", explainHe: "הרגל בעבר = used to, בלי am." },
      { id: "g-used-to-would-15", type: "fix", prompt: "Did you used to play the piano?", answer: "Did you use to play the piano?", errorType: "verb-form", explainHe: "אחרי did הפועל בצורה הבסיסית: use to." },
      { id: "g-used-to-would-16", type: "fix", prompt: "I'm used to get up at six every day.", answer: "I'm used to getting up at six every day.", accept: ["I am used to getting up at six every day."], errorType: "verb-form", explainHe: "אחרי be used to בא ing." },
      { id: "g-used-to-would-17", type: "fix", prompt: "We would have a big house in Ramat Gan.", answer: "We used to have a big house in Ramat Gan.", errorType: "word-choice", explainHe: "בעלות היא מצב, ולמצבים משתמשים ב-used to." },
      { id: "g-used-to-would-18", type: "transform", prompt: "I smoked for ten years, but I stopped.", keyword: "used", answer: "I used to smoke, but I stopped.", accept: ["I used to smoke, but I quit."], explainHe: "used to מוסיף את המסר 'וזה נגמר'." },
      { id: "g-used-to-would-19", type: "transform", prompt: "Every summer we drove to the Galilee.", keyword: "would", answer: "Every summer we would drive to the Galilee.", accept: ["We would drive to the Galilee every summer."], explainHe: "פעולה חוזרת בעבר = would + פועל בסיסי." },
      { id: "g-used-to-would-20", type: "transform", prompt: "Driving in Tel Aviv doesn't bother me anymore.", keyword: "used", answer: "I am used to driving in Tel Aviv.", accept: ["I'm used to driving in Tel Aviv."], explainHe: "'אני רגיל ל...' = be used to + ing." },
      { id: "g-used-to-would-21", type: "order", words: ["there", "used", "to", "be", "a", "cinema", "here"], answer: "There used to be a cinema here.", explainHe: "There used to be = פעם היה. אחרי used to פועל בסיסי." },
      { id: "g-used-to-would-22", type: "order", words: ["I", "didn't", "use", "to", "like", "coffee"], answer: "I didn't use to like coffee.", explainHe: "בשלילה ה-d עוברת ל-did: didn't use to." },
      { id: "g-used-to-would-23", type: "translate", he: "פעם עישנתי, אבל הפסקתי לפני שנתיים.", answer: "I used to smoke, but I quit two years ago.", accept: ["I used to smoke, but I stopped two years ago.", "I used to smoke, but I gave up two years ago."], explainHe: "'פעם' + זה נגמר = used to smoke." },
      { id: "g-used-to-would-24", type: "translate", he: "אני עדיין לא רגיל למזג האוויר פה.", answer: "I'm still not used to the weather here.", accept: ["I am still not used to the weather here.", "I'm not used to the weather here yet."], explainHe: "'רגיל ל' = be used to, ואחריו שם עצם: the weather." },
    ],
  },

  // ---------------------------------------------------------------------------
  // 11. Time clauses: when / until / as soon as + present
  // ---------------------------------------------------------------------------
  {
    id: "g-future-time-clauses",
    title: "Time clauses: when / until / as soon as + present",
    titleHe: "משפטי זמן בעתיד",
    strand: "tenses",
    order: 11,
    prereqs: ["g-future-forms"],
    lesson: {
      explanationHe: [
        "זהו אחד הכללים שהכי קל לשכוח, וגם הטעות הכי נפוצה של דוברי עברית. אחרי מילות הזמן when, until, till, as soon as, before, after, by the time, once, the moment – משתמשים בזמן הווה, גם כשמדובר בעתיד. אין will בתוך פסוקית הזמן.",
        "ה-will (או going to, או ציווי) יושב במשפט העיקרי: 'When I get home, I'll call you'. שימו לב לחלוקה: החצי עם when בהווה, החצי השני בעתיד. 'I'll wait here until the rain stops'. 'As soon as she lands, she'll text us'.",
        "אפשר להפוך את הסדר בלי לשנות את המשמעות. כשפסוקית הזמן פותחת את המשפט – שמים פסיק: 'Before you leave, turn off the lights'. כשהיא באה בסוף – בלי פסיק: 'Turn off the lights before you leave'.",
        "אחרי after, once ו-until אפשר גם Present Perfect כשחשוב להדגיש שהפעולה הושלמה: 'After we've eaten, we'll go out'. זו אפשרות, לא חובה – 'After we eat' גם נכון.",
        "שימו לב לחריג: כש-when היא מילת שאלה, will חוזר והוא נכון. 'When will you get here?' – זו שאלה על העתיד, לא פסוקית זמן. הכלל 'הווה אחרי when' חל רק כשהמשפט מחובר לחלק אחר.",
      ],
      form: [
        { label: "when + הווה / will", example: "When I get home, I'll call you." },
        { label: "until + הווה", example: "I'll wait here until the rain stops." },
        { label: "as soon as + הווה", example: "As soon as she lands, she'll text us." },
        { label: "before / after + הווה", example: "Before you leave, turn off the lights." },
        { label: "by the time + הווה", example: "By the time we get there, the store will be closed." },
        { label: "when כמילת שאלה", example: "When will you get here?" },
      ],
      examples: [
        { en: "When I get home tonight, I'll call you.", he: "כשאגיע הביתה הערב, אתקשר אליך." },
        { en: "I'll wait for you here until you finish.", he: "אחכה לך פה עד שתסיים." },
        { en: "As soon as they land, they'll let us know.", he: "ברגע שהם ינחתו, הם יודיעו לנו." },
        { en: "I'll send you the file before I leave the office.", he: "אשלח לך את הקובץ לפני שאצא מהמשרד." },
        { en: "After we finish eating, we'll go see a movie.", he: "אחרי שנסיים לאכול, נלך לראות סרט." },
        { en: "By the time we get there, everything will be closed.", he: "עד שנגיע לשם, הכול יהיה סגור." },
        { en: "I won't decide anything until I hear from them.", he: "לא אחליט כלום עד שאשמע מהם." },
        { en: "When will the results come out?", he: "מתי יצאו התוצאות?" },
      ],
      contrastHe: [
        "בעברית אומרים 'כשאגיע' – פועל בעתיד. באנגלית אותו חצי משפט הוא בהווה: 'when I arrive'. זו הטעות מספר אחת: 'When I will arrive' פשוט לא קיים באנגלית.",
        "'עד ש...' בעברית גורר עתיד: 'עד שתסיים'. באנגלית: 'until you finish', בהווה פשוט.",
        "בעברית שני חלקי המשפט בעתיד: 'כשאסיים, אתקשר'. באנגלית רק אחד: 'When I finish, I'll call'. חשוב לזכור שגם החצי השני צריך will – לא להשאיר את שניהם בהווה.",
        "when כמילת שאלה שומרת על will: 'מתי תגיע?' = 'When will you arrive?'. ההבדל הוא בין שאלה לבין פסוקית זמן בתוך משפט.",
      ],
      commonErrors: [
        { wrong: "When I will arrive, I will call you.", right: "When I arrive, I will call you.", whyHe: "אחרי when לא בא will, גם כשהכוונה לעתיד." },
        { wrong: "I'll wait until you will finish.", right: "I'll wait until you finish.", whyHe: "until + הווה פשוט." },
        { wrong: "As soon as she get home, she'll eat.", right: "As soon as she gets home, she'll eat.", whyHe: "הווה פשוט, ו-she דורשת s." },
        { wrong: "After I will finish work, I'll come.", right: "After I finish work, I'll come.", whyHe: "after + הווה, ו-will רק במשפט העיקרי." },
        { wrong: "When I finish, I call you.", right: "When I finish, I'll call you.", whyHe: "בפסוקית הזמן הווה, אבל במשפט העיקרי כן צריך will." },
      ],
    },
    items: [
      { id: "g-future-time-clauses-01", type: "gap", prompt: "As soon as she ___ (finish), we'll eat.", answer: "finishes", explainHe: "אחרי as soon as הווה פשוט, ו-she דורשת s." },
      { id: "g-future-time-clauses-02", type: "gap", prompt: "I'll call you when I ___ (get) home.", answer: "get", explainHe: "אחרי when בא הווה פשוט, גם כשהמשמעות עתידית." },
      { id: "g-future-time-clauses-03", type: "gap", prompt: "We won't start until everyone ___ (arrive).", answer: "arrives", explainHe: "until + הווה פשוט. everyone הוא יחיד ולכן arrives." },
      { id: "g-future-time-clauses-04", type: "gap", prompt: "Before you ___ (leave), please turn off the lights.", answer: "leave", explainHe: "before + הווה פשוט; במשפט העיקרי יש כאן ציווי." },
      { id: "g-future-time-clauses-05", type: "gap", prompt: "By the time we ___ (get) there, the store will be closed.", answer: "get", explainHe: "by the time + הווה, וה-will נמצא בחצי השני." },
      { id: "g-future-time-clauses-06", type: "gap", prompt: "When the rain ___ (stop), we'll go for a walk.", answer: "stops", explainHe: "the rain = it, ולכן stops. אחרי when אין will." },
      { id: "g-future-time-clauses-07", type: "gap", prompt: "After I ___ (finish) my shift, I'll come straight over.", answer: "finish", accept: ["have finished"], explainHe: "after + הווה. עם after אפשר גם Present Perfect." },
      { id: "g-future-time-clauses-08", type: "gap", prompt: "Once you taste this cake, you ___ (want) more.", answer: "will want", accept: ["'ll want"], explainHe: "כאן החסר הוא במשפט העיקרי, ושם דווקא כן שמים will." },
      {
        id: "g-future-time-clauses-09", type: "mcq", prompt: "I'll text you as soon as I ___.",
        options: [
          { text: "land" },
          { text: "will land", errorType: "tense", whyHe: "אחרי as soon as לא בא will, גם כשמדובר בעתיד." },
          { text: "am landing", errorType: "aspect", whyHe: "פעולה נקודתית עתידית = הווה פשוט." },
          { text: "will be landing", errorType: "tense", whyHe: "בתוך פסוקית זמן אין will בכלל." },
        ],
        answerIndex: 0, explainHe: "as soon as + הווה פשוט; ה-will נשאר במשפט העיקרי.",
      },
      {
        id: "g-future-time-clauses-10", type: "mcq", prompt: "We'll wait here until the rain ___.",
        options: [
          { text: "stops" },
          { text: "will stop", errorType: "tense", whyHe: "until אף פעם לא לוקח will." },
          { text: "stop", errorType: "agreement", whyHe: "the rain = it, וצריך s." },
          { text: "is stopping", errorType: "aspect", whyHe: "לא תהליך שקורה עכשיו, אלא נקודה בעתיד: הווה פשוט." },
        ],
        answerIndex: 0, explainHe: "until + הווה פשוט, בהתאמה לנושא.",
      },
      {
        id: "g-future-time-clauses-11", type: "mcq", prompt: "When I see her tomorrow, I ___ her about the job.",
        options: [
          { text: "'ll ask" },
          { text: "ask", errorType: "tense", whyHe: "בפסוקית הזמן הווה, אבל במשפט העיקרי כן צריך will." },
          { text: "am asking", errorType: "aspect", whyHe: "אין כאן סידור קבוע; זו כוונה לעתיד." },
          { text: "will asking", errorType: "verb-form", whyHe: "אחרי will בא פועל בסיסי: will ask." },
        ],
        answerIndex: 0, explainHe: "החלוקה: when + הווה, ובמשפט העיקרי will.",
      },
      {
        id: "g-future-time-clauses-12", type: "mcq", prompt: "When ___ this project?",
        options: [
          { text: "will we finish" },
          { text: "we will finish", errorType: "question-form", whyHe: "בשאלה will עובר לפני הנושא." },
          { text: "do we finish", errorType: "tense", whyHe: "אין כאן לוח זמנים קבוע; שאלה על העתיד = will." },
          { text: "we finish", errorType: "question-form", whyHe: "זה סדר של משפט חיווי, לא של שאלה." },
        ],
        answerIndex: 0, explainHe: "כש-when היא מילת שאלה, will חוזר והוא נכון.",
      },
      {
        id: "g-future-time-clauses-13", type: "mcq", prompt: "The moment the doors ___, everyone will run in.",
        options: [
          { text: "open" },
          { text: "will open", errorType: "tense", whyHe: "the moment היא מילת זמן, ואחריה אין will." },
          { text: "opens", errorType: "agreement", whyHe: "the doors = they, ולכן בלי s." },
          { text: "are opening", errorType: "aspect", whyHe: "נקודה בעתיד, לא תהליך שקורה עכשיו." },
        ],
        answerIndex: 0, explainHe: "the moment = as soon as, ואחריו הווה פשוט בהתאמה לנושא.",
      },
      { id: "g-future-time-clauses-14", type: "fix", prompt: "When I will arrive, I will call you.", answer: "When I arrive, I will call you.", accept: ["When I arrive, I'll call you."], errorType: "tense", explainHe: "אחרי when הווה פשוט; ה-will נשאר רק במשפט העיקרי." },
      { id: "g-future-time-clauses-15", type: "fix", prompt: "I'll wait until you will finish.", answer: "I'll wait until you finish.", accept: ["I will wait until you finish."], errorType: "tense", explainHe: "until + הווה פשוט." },
      { id: "g-future-time-clauses-16", type: "fix", prompt: "As soon as she get home, she'll call us.", answer: "As soon as she gets home, she'll call us.", errorType: "agreement", explainHe: "הווה פשוט בגוף שלישי יחיד: gets." },
      { id: "g-future-time-clauses-17", type: "fix", prompt: "We'll leave when everyone will be ready.", answer: "We'll leave when everyone is ready.", errorType: "tense", explainHe: "אחרי when הווה: is ready." },
      { id: "g-future-time-clauses-18", type: "transform", prompt: "First I'll finish this email. Then I'll help you.", keyword: "when", answer: "I'll help you when I finish this email.", accept: ["When I finish this email, I'll help you.", "I will help you when I finish this email.", "When I finish this email, I will help you."], explainHe: "הפעולה הראשונה נכנסת לפסוקית when בהווה, השנייה מקבלת will." },
      { id: "g-future-time-clauses-19", type: "transform", prompt: "Don't open the door. Wait for the train to stop.", keyword: "until", answer: "Don't open the door until the train stops.", explainHe: "until + הווה פשוט: stops." },
      { id: "g-future-time-clauses-20", type: "transform", prompt: "The moment I hear from her, I'll let you know.", keyword: "as soon as", answer: "As soon as I hear from her, I'll let you know.", accept: ["I'll let you know as soon as I hear from her.", "As soon as I hear from her, I will let you know."], explainHe: "as soon as = the moment, ואחרי שניהם בא הווה פשוט." },
      { id: "g-future-time-clauses-21", type: "order", words: ["I'll", "let", "you", "know", "as", "soon", "as", "I", "hear", "from", "her"], answer: "I'll let you know as soon as I hear from her.", explainHe: "המשפט העיקרי עם will, ופסוקית as soon as בהווה." },
      { id: "g-future-time-clauses-22", type: "order", words: ["we", "won't", "leave", "until", "the", "rain", "stops"], answer: "We won't leave until the rain stops.", explainHe: "won't במשפט העיקרי, ו-until + הווה." },
      { id: "g-future-time-clauses-23", type: "translate", he: "כשאגיע הביתה, אתקשר אליך.", answer: "When I get home, I'll call you.", accept: ["When I get home, I will call you.", "I'll call you when I get home.", "I will call you when I get home."], explainHe: "'כשאגיע' = when I get, בהווה. ה-will רק בחצי השני." },
      { id: "g-future-time-clauses-24", type: "translate", he: "אני אחכה עד שתסיים.", answer: "I'll wait until you finish.", accept: ["I will wait until you finish.", "I'll wait until you're done.", "I'll wait until you have finished."], explainHe: "'עד שתסיים' = until you finish, בהווה פשוט." },
    ],
  },

  // ---------------------------------------------------------------------------
  // 12. State verbs (know, like, belong...)
  // ---------------------------------------------------------------------------
  {
    id: "g-state-verbs",
    title: "State verbs (know, like, belong...)",
    titleHe: "פעלי מצב",
    strand: "tenses",
    order: 12,
    prereqs: ["g-present-simple-continuous"],
    lesson: {
      explanationHe: [
        "יש פעלים שמתארים מצב ולא פעולה, ולכן בדרך כלל אין להם צורת ing – גם כשמדובר ברגע הזה ממש. הקבוצות העיקריות: ידיעה ומחשבה (know, understand, remember, forget, believe, mean), רגש ורצון (like, love, hate, prefer, want, need), ובעלות והשתייכות (have, own, belong, cost, contain).",
        "אליהם מצטרפים פעלים כמו seem, look (=נראה), sound, matter, depend. אומרים 'I know the answer', 'She wants a coffee', 'This bag belongs to Dana' – תמיד בהווה פשוט, גם אם בעברית זה נשמע כמו משהו שקורה עכשיו.",
        "עם חושים – see, hear – משתמשים בדרך כלל ב-can: 'I can see the sea from here', 'Can you hear that noise?'. זה הרבה יותר טבעי מ-'I am seeing' או 'I am hearing'.",
        "כמה פעלים הם דו-משמעיים: במשמעות של מצב אין ing, ובמשמעות של פעולה יש. have (יש לי / לאכול, לעשות): 'I have a car' מול 'He's having a shower'. think (דעה / תהליך): 'I think you're right' מול 'Be quiet, I'm thinking'. see (לראות / להיפגש): 'I see what you mean' מול 'I'm seeing the doctor at four'.",
        "יש חריגים שבאמת שומעים – 'I'm loving this song', 'I'm feeling great' – אבל הם ברמת סלנג ולא כדאי לבנות עליהם. הכלל הבטוח: פועל מצב = הווה פשוט, עם s בגוף שלישי יחיד.",
      ],
      form: [
        { label: "ידיעה ומחשבה", example: "know, understand, remember, believe, mean — I know the answer." },
        { label: "רגש ורצון", example: "like, love, hate, want, need, prefer — She wants a coffee." },
        { label: "בעלות והשתייכות", example: "have, own, belong, cost, contain — This bag belongs to Dana." },
        { label: "חושים עם can", example: "I can see the sea. — Can you hear that?" },
        { label: "have: מצב מול פעולה", example: "I have a car. — He's having a shower." },
        { label: "think: דעה מול תהליך", example: "I think you're right. — Be quiet, I'm thinking." },
      ],
      examples: [
        { en: "I don't understand what you're saying.", he: "אני לא מבין מה אתה אומר." },
        { en: "Do you know that guy? He looks familiar.", he: "אתה מכיר את הבחור הזה? הוא נראה מוכר." },
        { en: "This bag belongs to Dana.", he: "התיק הזה שייך לדנה." },
        { en: "I want a coffee. Let's stop here.", he: "אני רוצה קפה. בוא נעצור פה." },
        { en: "She has two brothers and a sister.", he: "יש לה שני אחים ואחות." },
        { en: "Where's Dan? He's having a shower.", he: "איפה דן? הוא מתקלח." },
        { en: "What do you think about the new manager?", he: "מה דעתך על המנהל החדש?" },
        { en: "Listen — can you hear that noise?", he: "תקשיב – אתה שומע את הרעש הזה?" },
      ],
      contrastHe: [
        "בעברית ההווה נראה תמיד אותו דבר: 'אני יודע', 'אני רוצה', 'אני עובד'. זה דוחף לתרגם הכול ל-ing ולומר 'I am knowing', 'I am wanting'. אבל פעלי מצב באנגלית לא מקבלים ing.",
        "'יש לי אוטו' = 'I have a car', ולעולם לא 'I'm having a car'. 'I'm having' פירושו לאכול, לשתות, או לעבור חוויה.",
        "'אני רואה אותו' ברגע הזה = 'I can see him', ולא 'I am seeing him' (שפירושו נפגש איתו או יוצא איתו).",
        "'מה אתה חושב?' כשואלים על דעה = 'What do you think?'. 'What are you thinking?' שואל מה עובר לך בראש עכשיו – משמעות אחרת לגמרי.",
      ],
      commonErrors: [
        { wrong: "I am knowing the answer.", right: "I know the answer.", whyHe: "know הוא פועל מצב, ואין לו ing." },
        { wrong: "I am wanting a coffee.", right: "I want a coffee.", whyHe: "want הוא פועל מצב: הווה פשוט." },
        { wrong: "I'm having a new car.", right: "I have a new car.", whyHe: "have במשמעות בעלות = מצב, בלי ing." },
        { wrong: "This book is belonging to my sister.", right: "This book belongs to my sister.", whyHe: "belong הוא פועל מצב: belongs." },
        { wrong: "I am not understanding you.", right: "I don't understand you.", whyHe: "understand הוא פועל מצב, ולכן שלילה עם don't." },
        { wrong: "I am seeing the sea from my window.", right: "I can see the sea from my window.", whyHe: "עם חושים משתמשים ב-can see." },
      ],
    },
    items: [
      { id: "g-state-verbs-01", type: "gap", prompt: "Sorry, I ___ (not/understand) the question.", answer: "don't understand", explainHe: "understand הוא פועל מצב: שלילה עם don't, בלי ing." },
      { id: "g-state-verbs-02", type: "gap", prompt: "This bag ___ (belong) to Dana.", answer: "belongs", explainHe: "belong הוא פועל מצב, ובגוף שלישי יחיד מקבל s." },
      { id: "g-state-verbs-03", type: "gap", prompt: "___ (you/have) lunch right now, or can you talk?", answer: "Are you having", explainHe: "have כאן במשמעות של לאכול = פעולה, ולכן דווקא כן ing." },
      { id: "g-state-verbs-04", type: "gap", prompt: "She ___ (have) two brothers and a sister.", answer: "has", explainHe: "have במשמעות בעלות = מצב: has, בלי ing." },
      { id: "g-state-verbs-05", type: "gap", prompt: "Be quiet for a second, I ___ (think) about it.", answer: "am thinking", accept: ["'m thinking"], explainHe: "think כתהליך שקורה עכשיו = am thinking." },
      { id: "g-state-verbs-06", type: "gap", prompt: "What ___ (you/think) about the new manager?", answer: "do you think", explainHe: "think במשמעות דעה = מצב: What do you think?" },
      { id: "g-state-verbs-07", type: "gap", prompt: "I ___ (want) a coffee. Let's stop at that place.", answer: "want", explainHe: "want הוא פועל מצב: הווה פשוט, גם אם זה הרצון שלי ברגע הזה." },
      { id: "g-state-verbs-08", type: "gap", prompt: "This soup ___ (taste) amazing.", answer: "tastes", explainHe: "taste במשמעות 'יש לו טעם' = מצב: tastes." },
      {
        id: "g-state-verbs-09", type: "mcq", prompt: "I ___ exactly what you mean.",
        options: [
          { text: "know" },
          { text: "am knowing", errorType: "aspect", whyHe: "know הוא פועל מצב ואין לו ing." },
          { text: "knowing", errorType: "verb-form", whyHe: "צורת ing לבדה אינה פועל במשפט." },
          { text: "am know", errorType: "verb-form", whyHe: "אין מבנה של be + פועל בסיסי." },
        ],
        answerIndex: 0, explainHe: "פועל מצב = הווה פשוט: I know.",
      },
      {
        id: "g-state-verbs-10", type: "mcq", prompt: "Where's Dan? He ___ a shower.",
        options: [
          { text: "'s having" },
          { text: "has", errorType: "aspect", whyHe: "have a shower = פעולה שקורה עכשיו, ולכן ing." },
          { text: "is have", errorType: "verb-form", whyHe: "אחרי is חייב לבוא ing: is having." },
          { text: "having", errorType: "verb-form", whyHe: "חסר הפועל be לפני having." },
        ],
        answerIndex: 0, explainHe: "have במשמעות פעולה (להתקלח, לאכול) כן מקבל ing.",
      },
      {
        id: "g-state-verbs-11", type: "mcq", prompt: "We ___ a car, so we go everywhere by bus.",
        options: [
          { text: "don't have" },
          { text: "aren't having", errorType: "aspect", whyHe: "have במשמעות בעלות הוא מצב, בלי ing." },
          { text: "don't having", errorType: "verb-form", whyHe: "אחרי don't בא פועל בסיסי: have." },
          { text: "don't has", errorType: "agreement", whyHe: "אחרי don't הפועל בצורה הבסיסית: have." },
        ],
        answerIndex: 0, explainHe: "בעלות = פועל מצב, ולכן שלילה עם don't have.",
      },
      {
        id: "g-state-verbs-12", type: "mcq", prompt: "This laptop ___ four thousand shekels.",
        options: [
          { text: "costs" },
          { text: "is costing", errorType: "aspect", whyHe: "cost הוא פועל מצב ואין לו ing." },
          { text: "cost", errorType: "agreement", whyHe: "this laptop = it, וצריך s." },
          { text: "is cost", errorType: "verb-form", whyHe: "אין מבנה של be + פועל בסיסי." },
        ],
        answerIndex: 0, explainHe: "cost הוא פועל מצב: costs בהווה פשוט.",
      },
      {
        id: "g-state-verbs-13", type: "mcq", prompt: "Listen — ___ that noise?",
        options: [
          { text: "can you hear" },
          { text: "are you hearing", errorType: "aspect", whyHe: "עם חושים אומרים can you hear, ולא ing." },
          { text: "do you hearing", errorType: "verb-form", whyHe: "אחרי do בא פועל בסיסי: hear." },
          { text: "you hear", errorType: "question-form", whyHe: "בשאלה צריך פועל עזר לפני הנושא." },
        ],
        answerIndex: 0, explainHe: "hear ו-see נאמרים עם can כשמדובר ברגע הזה.",
      },
      { id: "g-state-verbs-14", type: "fix", prompt: "I am knowing the answer.", answer: "I know the answer.", errorType: "aspect", explainHe: "know הוא פועל מצב: הווה פשוט, בלי am ובלי ing." },
      { id: "g-state-verbs-15", type: "fix", prompt: "I am wanting a coffee.", answer: "I want a coffee.", errorType: "aspect", explainHe: "want הוא פועל מצב ואין לו ing." },
      { id: "g-state-verbs-16", type: "fix", prompt: "I'm having a new car.", answer: "I have a new car.", accept: ["I have got a new car."], errorType: "aspect", explainHe: "have במשמעות בעלות = מצב, בלי ing." },
      { id: "g-state-verbs-17", type: "fix", prompt: "This book is belonging to my sister.", answer: "This book belongs to my sister.", errorType: "aspect", explainHe: "belong הוא פועל מצב: belongs." },
      { id: "g-state-verbs-18", type: "transform", prompt: "Is this yours?", keyword: "belong", answer: "Does this belong to you?", explainHe: "belong הוא פועל מצב, ולכן שאלה עם does + פועל בסיסי." },
      { id: "g-state-verbs-19", type: "transform", prompt: "In my opinion, he's right.", keyword: "think", answer: "I think he's right.", accept: ["I think he is right.", "I think that he's right.", "I think that he is right."], explainHe: "דעה = I think, בהווה פשוט ולא am thinking." },
      { id: "g-state-verbs-20", type: "transform", prompt: "She is taking a break at the moment.", keyword: "having", answer: "She is having a break at the moment.", accept: ["She's having a break at the moment."], explainHe: "have a break הוא פעולה, ולכן מותר ing." },
      { id: "g-state-verbs-21", type: "order", words: ["I", "don't", "believe", "a", "word", "of", "it"], answer: "I don't believe a word of it.", explainHe: "believe הוא פועל מצב: שלילה עם don't ובלי ing." },
      { id: "g-state-verbs-22", type: "order", words: ["what", "does", "this", "word", "mean?"], answer: "What does this word mean?", explainHe: "mean הוא פועל מצב: שאלה עם does + פועל בסיסי." },
      { id: "g-state-verbs-23", type: "translate", he: "יש לי שתי אחיות.", answer: "I have two sisters.", accept: ["I've got two sisters.", "I have got two sisters."], explainHe: "'יש לי' = I have. אף פעם לא 'I'm having'." },
      { id: "g-state-verbs-24", type: "translate", he: "אני לא מבין מה אתה אומר.", answer: "I don't understand what you're saying.", accept: ["I don't understand what you are saying.", "I don't understand what you mean."], explainHe: "understand הוא פועל מצב (don't understand), אבל say בהמשך הוא פעולה שקורה עכשיו." },
    ],
  },
];
