import type { GrammarTopic } from "@/lib/types";

export const VERB_PATTERNS: GrammarTopic[] = [
  // ------------------------------------------------------------------
  // 37. Gerund vs infinitive
  // ------------------------------------------------------------------
  {
    id: "g-gerund-infinitive",
    title: "Gerund vs infinitive (enjoy doing / want to do)",
    titleHe: "ing- או to",
    strand: "verb-patterns",
    order: 37,
    prereqs: [],
    lesson: {
      explanationHe: [
        "בעברית כמעט תמיד באה ל+שם פועל: 'אני נהנה לקרוא', 'אני מנסה לישון', 'הפסקתי לעשן'. לכן דוברי עברית שמים to על הכול ואומרים I enjoy to read. באנגלית הפועל הראשון הוא זה שקובע: יש פעלים שדורשים -ing, יש פעלים שדורשים to, ואת זה פשוט לומדים לפי רשימה.",
        "פעלים שדורשים -ing: enjoy, avoid, finish, mind, suggest, practice, keep, imagine, consider, miss, can't stand, give up. הקבוצה הזאת מדברת בעיקר על חוויה, הרגל או הפסקה: I enjoy cooking. He avoided answering. Do you mind waiting?",
        "פעלים שדורשים to + infinitive: want, need, decide, hope, plan, promise, agree, offer, refuse, manage, learn, seem, afford, pretend, expect. הקבוצה הזאת מדברת בעיקר על כוונה, החלטה או משהו שעדיין לא קרה: She decided to move. We can't afford to buy it.",
        "חמישה פעלים לוקחים את שניהם עם שינוי משמעות: stop smoking (הפסקתי לעשן) מול stop to smoke (עצרתי כדי לעשן); remember to lock (לזכור לנעול, לפני) מול remember locking (לזכור שנעלת, אחרי); forget אותו דבר; try to open (להתאמץ) מול try opening (לנסות שיטה); regret to tell (מצטער לבשר) מול regret telling (מתחרט שסיפרתי).",
        "כלל הזהב האחרון: אחרי כל מילת יחס בא -ing, בלי יוצא מן הכלל. good at cooking, instead of waiting, before leaving, interested in learning, thanks for helping. שימו לב שגם ה-to של look forward to ושל be used to הוא מילת יחס, ולכן: I'm looking forward to seeing you, I'm used to working late.",
      ],
      form: [
        { label: "פועל + ing", example: "enjoy / avoid / finish / mind / suggest / keep / practice + doing" },
        { label: "פועל + to + infinitive", example: "want / need / decide / hope / promise / refuse / manage + to do" },
        { label: "שניהם, אותה משמעות", example: "like, love, hate, start, begin: I like swimming = I like to swim." },
        { label: "שניהם, משמעות שונה", example: "stop / remember / forget / try / regret" },
        { label: "מילת יחס + ing", example: "good at cooking, before leaving, instead of waiting, interested in learning" },
        { label: "to שהוא מילת יחס", example: "look forward to seeing, be used to working, get used to living" },
        { label: "שלילה", example: "He decided not to go. I enjoy not working on Fridays." },
        { label: "כתיב ה-ing", example: "make - making, plan - planning, study - studying" },
      ],
      examples: [
        { en: "I enjoy cooking on weekends.", he: "אני נהנה לבשל בסופי שבוע." },
        { en: "She avoids driving downtown at rush hour.", he: "היא נמנעת מלנהוג במרכז העיר בשעת עומס." },
        { en: "We decided to move to a bigger place.", he: "החלטנו לעבור לדירה גדולה יותר." },
        { en: "I can't afford to buy a car right now.", he: "אני לא יכול להרשות לעצמי לקנות אוטו עכשיו." },
        { en: "He stopped smoking two years ago.", he: "הוא הפסיק לעשן לפני שנתיים." },
        { en: "Remember to lock the door, please.", he: "תזכור לנעול את הדלת, בבקשה." },
        { en: "My sister is really good at fixing things.", he: "אחותי ממש טובה בתיקון דברים." },
        { en: "I'm looking forward to seeing you next month.", he: "אני מצפה לראות אותך בחודש הבא." },
      ],
      contrastHe: [
        "בעברית 'אני נהנה לקרוא' עם ל'. באנגלית enjoy תמיד עם -ing: I enjoy reading. הצורה to אחרי enjoy פשוט לא קיימת.",
        "בעברית 'אני מצפה לפגוש אותך'. באנגלית ה-to של look forward to הוא מילת יחס: looking forward to meeting you, לא to meet.",
        "בעברית 'היא טובה בבישול' (שם פעולה). באנגלית אחרי at חייבים -ing: good at cooking, לא good at cook.",
        "בעברית 'הפסקתי לעשן' ו'עצרתי כדי לעשן' נשמעים דומה. באנגלית ההבדל קריטי: stopped smoking מול stopped to smoke.",
      ],
      commonErrors: [
        { wrong: "I enjoy to read at night.", right: "I enjoy reading at night.", whyHe: "enjoy תמיד עם -ing. זה תרגום ישיר של 'נהנה לקרוא'." },
        { wrong: "He avoided to answer my question.", right: "He avoided answering my question.", whyHe: "avoid שייך לקבוצת ה-ing." },
        { wrong: "I'm looking forward to see you.", right: "I'm looking forward to seeing you.", whyHe: "ה-to כאן הוא מילת יחס, ואחרי מילת יחס בא -ing." },
        { wrong: "She's good at cook.", right: "She's good at cooking.", whyHe: "אחרי at (מילת יחס) חייבים -ing, אף פעם לא צורת בסיס." },
        { wrong: "I stopped to smoke two years ago.", right: "I stopped smoking two years ago.", whyHe: "stopped to smoke = עצרתי כדי לעשן. הפסקה מעישון היא stopped smoking." },
        { wrong: "We decided going home early.", right: "We decided to go home early.", whyHe: "decide הוא פועל של החלטה, ולכן to + infinitive." },
      ],
    },
    items: [
      {
        id: "g-gerund-infinitive-01",
        type: "gap",
        prompt: "I really enjoy ___ (cook) on weekends.",
        answer: "cooking",
        explainHe: "enjoy שייך לקבוצת ה-ing: enjoy cooking. 'נהנה לבשל' לא הופך ל-to cook.",
      },
      {
        id: "g-gerund-infinitive-02",
        type: "gap",
        prompt: "We can't afford ___ (buy) a new car this year.",
        answer: "to buy",
        explainHe: "afford שייך לקבוצת ה-to: can't afford to buy.",
      },
      {
        id: "g-gerund-infinitive-03",
        type: "gap",
        prompt: "She avoids ___ (drive) downtown during rush hour.",
        answer: "driving",
        explainHe: "avoid תמיד עם -ing: avoid driving.",
      },
      {
        id: "g-gerund-infinitive-04",
        type: "gap",
        prompt: "He finally managed ___ (finish) the report on time.",
        answer: "to finish",
        hint: "manage = הצליח, פועל של תוצאה",
        explainHe: "manage שייך לקבוצת ה-to: managed to finish. שימו לב ש-finish עצמו לוקח -ing, אבל כאן הפועל הראשון הוא manage.",
      },
      {
        id: "g-gerund-infinitive-05",
        type: "gap",
        prompt: "I'm looking forward to ___ (see) you next month.",
        answer: "seeing",
        hint: "ה-to הזה הוא מילת יחס",
        explainHe: "look forward to הוא ביטוי עם מילת יחס, ולכן -ing: looking forward to seeing you.",
      },
      {
        id: "g-gerund-infinitive-06",
        type: "gap",
        prompt: "My brother is really good at ___ (fix) computers.",
        answer: "fixing",
        explainHe: "אחרי מילת היחס at בא -ing: good at fixing.",
      },
      {
        id: "g-gerund-infinitive-07",
        type: "gap",
        prompt: "Dana suggested ___ (take) the train instead of driving.",
        answer: "taking",
        explainHe: "suggest שייך לקבוצת ה-ing: suggested taking. לא suggested to take.",
      },
      {
        id: "g-gerund-infinitive-08",
        type: "gap",
        prompt: "Please remember ___ (turn off) the lights before you leave.",
        answer: "to turn off",
        explainHe: "remember to do = לזכור לעשות משהו בעתיד. remember turning off היה אומר 'אני זוכר שכיביתי'.",
      },
      {
        id: "g-gerund-infinitive-09",
        type: "mcq",
        prompt: "I enjoy ___ to podcasts while I run.",
        options: [
          { text: "listening" },
          { text: "to listen", errorType: "verb-form", whyHe: "תרגום ישיר של 'נהנה להאזין'. enjoy אף פעם לא לוקח to." },
          { text: "listen", errorType: "verb-form", whyHe: "אחרי enjoy לא באה צורת בסיס, אלא -ing." },
        ],
        answerIndex: 0,
        explainHe: "enjoy דורש -ing: I enjoy listening to podcasts.",
      },
      {
        id: "g-gerund-infinitive-10",
        type: "mcq",
        prompt: "Have a coffee before ___ the house.",
        options: [
          { text: "to leave", errorType: "verb-form", whyHe: "before היא מילת יחס, ואחרי מילת יחס אף פעם אין to + infinitive." },
          { text: "leaving" },
          { text: "leave", errorType: "verb-form", whyHe: "אחרי מילת יחס חייבים -ing, לא צורת בסיס." },
        ],
        answerIndex: 1,
        explainHe: "before היא מילת יחס, ולכן -ing: before leaving the house.",
      },
      {
        id: "g-gerund-infinitive-11",
        type: "mcq",
        prompt: "He refused ___ the contract without a lawyer.",
        options: [
          { text: "signing", errorType: "verb-form", whyHe: "refuse שייך לקבוצת ה-to, לא לקבוצת ה-ing." },
          { text: "sign", errorType: "verb-form", whyHe: "אחרי refuse חייבים to לפני הפועל." },
          { text: "to sign" },
        ],
        answerIndex: 2,
        explainHe: "refuse שייך לקבוצת ה-to: He refused to sign.",
      },
      {
        id: "g-gerund-infinitive-12",
        type: "mcq",
        prompt: "She kept ___ me the same question all evening.",
        options: [
          { text: "asking" },
          { text: "to ask", errorType: "verb-form", whyHe: "keep doing = להמשיך לעשות, תמיד עם -ing." },
          { text: "ask", errorType: "verb-form", whyHe: "keep דורש -ing, לא צורת בסיס." },
        ],
        answerIndex: 0,
        explainHe: "keep + ing = להמשיך או לעשות שוב ושוב: She kept asking.",
      },
      {
        id: "g-gerund-infinitive-13",
        type: "mcq",
        prompt: "I ___ two years ago, and now I feel much healthier.",
        options: [
          { text: "stopped to smoke", errorType: "word-choice", whyHe: "stop to smoke = עצרתי כדי לעשן. זה בדיוק ההפך מהמשמעות כאן." },
          { text: "stopped smoking" },
          { text: "stopped smoke", errorType: "verb-form", whyHe: "אחרי stop לא באה צורת בסיס לבד." },
        ],
        answerIndex: 1,
        explainHe: "stop + ing = להפסיק את הפעולה. stop + to = לעצור במטרה לעשות משהו.",
      },
      {
        id: "g-gerund-infinitive-14",
        type: "fix",
        prompt: "I enjoy to read before I go to sleep.",
        answer: "I enjoy reading before I go to sleep.",
        errorType: "verb-form",
        explainHe: "enjoy + ing. זו הטעות הקלאסית של דוברי עברית: 'נהנה לקרוא' הופך ל-enjoy to read.",
      },
      {
        id: "g-gerund-infinitive-15",
        type: "fix",
        prompt: "She's interested in learn Spanish.",
        answer: "She's interested in learning Spanish.",
        errorType: "verb-form",
        explainHe: "אחרי מילת היחס in בא -ing: interested in learning.",
      },
      {
        id: "g-gerund-infinitive-16",
        type: "fix",
        prompt: "He decided going back to university.",
        answer: "He decided to go back to university.",
        errorType: "verb-form",
        explainHe: "decide שייך לקבוצת ה-to: decided to go.",
      },
      {
        id: "g-gerund-infinitive-17",
        type: "fix",
        prompt: "I'm looking forward to meet you.",
        answer: "I'm looking forward to meeting you.",
        errorType: "verb-form",
        explainHe: "ה-to של look forward to הוא מילת יחס, ולכן meeting.",
      },
      {
        id: "g-gerund-infinitive-18",
        type: "fix",
        prompt: "We finished to clean the kitchen at midnight.",
        answer: "We finished cleaning the kitchen at midnight.",
        errorType: "verb-form",
        explainHe: "finish תמיד עם -ing: finished cleaning.",
      },
      {
        id: "g-gerund-infinitive-19",
        type: "transform",
        prompt: "I really don't like waiting in line.",
        keyword: "stand",
        answer: "I can't stand waiting in line.",
        accept: ["I cannot stand waiting in line."],
        explainHe: "can't stand הוא ביטוי חזק ל'לא סובל', ואחריו תמיד -ing: can't stand waiting.",
      },
      {
        id: "g-gerund-infinitive-20",
        type: "transform",
        prompt: "She said she would help me move, and I didn't even ask her.",
        keyword: "offered",
        answer: "She offered to help me move.",
        explainHe: "offer שייך לקבוצת ה-to: offered to help.",
      },
      {
        id: "g-gerund-infinitive-21",
        type: "order",
        words: ["I'm", "thinking", "of", "moving", "to", "a", "bigger", "apartment"],
        answer: "I'm thinking of moving to a bigger apartment.",
        explainHe: "think of הוא פועל עם מילת יחס, ולכן moving. ה-to שאחריו שייך ל-move to a place.",
      },
      {
        id: "g-gerund-infinitive-22",
        type: "order",
        words: ["he", "promised", "to", "call", "me", "back", "this", "evening"],
        answer: "He promised to call me back this evening.",
        explainHe: "promise שייך לקבוצת ה-to: promised to call.",
      },
      {
        id: "g-gerund-infinitive-23",
        type: "translate",
        he: "אני נהנה לבשל בסופי שבוע.",
        answer: "I enjoy cooking on weekends.",
        accept: ["I enjoy cooking on the weekends.", "I enjoy cooking at weekends.", "I enjoy cooking on weekends"],
        explainHe: "בעברית 'לבשל', באנגלית enjoy cooking. שימו לב: on weekends, בלי in.",
      },
      {
        id: "g-gerund-infinitive-24",
        type: "translate",
        he: "היא החליטה ללמוד ספרדית.",
        answer: "She decided to learn Spanish.",
        accept: ["She decided to study Spanish."],
        explainHe: "אותה ל' בעברית, אבל כאן decide דורש to: decided to learn. הפועל הראשון קובע.",
      },
    ],
  },

  // ------------------------------------------------------------------
  // 38. Verb + object + infinitive; make / let
  // ------------------------------------------------------------------
  {
    id: "g-verb-object-infinitive",
    title: "want / ask / tell someone to do; make / let someone do",
    titleHe: "want someone to do, make/let",
    strand: "verb-patterns",
    order: 38,
    prereqs: ["g-gerund-infinitive"],
    lesson: {
      explanationHe: [
        "בעברית אומרים 'אני רוצה שתבוא' — משפט ש' עם פועל מוטה. באנגלית המבנה הזה פשוט לא קיים אחרי want, ולכן I want that you come הוא שגוי לגמרי. במקומו יש מבנה אחד קבוע: פועל + מושא + to + פועל בסיס: I want you to come.",
        "הפעלים שעובדים ככה: want, ask, tell, advise, expect, allow, remind, teach, encourage, persuade, need, would like. She asked me to wait. They allowed us to park here. He reminded me to send the file. המושא הוא כינוי מושא (me, him, her, us, them), אף פעם לא I/he/she.",
        "יוצאי הדופן החשובים: make ו-let לוקחים פועל בסיס בלי to. He made me wait an hour. Let me help you. גם help מותר בלי to: She helped me carry the boxes (וגם to carry נכון). לכן let me to go ו-he made me to wait הן טעויות.",
        "עוד בלבול קלאסי: say מול tell. אחרי tell בא בן אדם (tell me, tell him), אחרי say לא. לכן She said me to come שגוי, והנכון הוא She told me to come. אם רוצים דווקא say, צריך משפט that: She said that I should come.",
        "לשלילה שמים not לפני ה-to: The doctor told me not to drive. My boss asked us not to be late. בפסיבי של make חוזר ה-to: We were made to wait outside.",
      ],
      form: [
        { label: "פועל + מושא + to + פועל", example: "want / ask / tell / advise / expect / allow / remind + someone + to do" },
        { label: "make / let + מושא + פועל בסיס", example: "She made me wait. They let us leave. (בלי to)" },
        { label: "help + מושא + (to) + פועל", example: "He helped me move. = He helped me to move." },
        { label: "שלילה", example: "She told me not to worry. They asked us not to smoke." },
        { label: "say מול tell", example: "She told me to come. / She said that I should come." },
        { label: "would like", example: "I'd like you to meet my sister." },
        { label: "פסיבי של make", example: "We were made to wait for an hour." },
      ],
      examples: [
        { en: "I want you to come early tomorrow.", he: "אני רוצה שתבוא מוקדם מחר." },
        { en: "She asked me to wait outside.", he: "היא ביקשה ממני לחכות בחוץ." },
        { en: "My boss told me to send the file again.", he: "הבוס שלי אמר לי לשלוח את הקובץ שוב." },
        { en: "They don't allow us to park here.", he: "הם לא מרשים לנו לחנות פה." },
        { en: "He made me wait for an hour.", he: "הוא הכריח אותי לחכות שעה." },
        { en: "Let me help you with those bags.", he: "תן לי לעזור לך עם התיקים האלה." },
        { en: "Remind me to call the bank tomorrow.", he: "תזכיר לי להתקשר לבנק מחר." },
        { en: "My father taught me to drive.", he: "אבא שלי לימד אותי לנהוג." },
      ],
      contrastHe: [
        "בעברית 'אני רוצה שתבוא' עם משפט ש'. באנגלית אין that אחרי want: I want you to come.",
        "בעברית 'תן לי ללכת' עם ל'. באנגלית let בלי to: Let me go, ולא Let me to go.",
        "בעברית 'הוא הכריח אותי לחכות' עם ל'. באנגלית make בלי to: He made me wait.",
        "בעברית 'היא אמרה לי לבוא'. באנגלית אחרי say אין בן אדם: told me to come, לא said me to come.",
      ],
      commonErrors: [
        { wrong: "I want that you come with me.", right: "I want you to come with me.", whyHe: "תרגום ישיר של 'רוצה שתבוא'. אחרי want אין משפט that, אלא מושא + to." },
        { wrong: "She said me to come at eight.", right: "She told me to come at eight.", whyHe: "אחרי say לא בא בן אדם. עם בן אדם משתמשים ב-tell." },
        { wrong: "Let me to go, please.", right: "Let me go, please.", whyHe: "let לוקח פועל בסיס בלי to." },
        { wrong: "He made me to wait outside.", right: "He made me wait outside.", whyHe: "גם make לוקח פועל בסיס בלי to." },
        { wrong: "My parents don't allow me going out late.", right: "My parents don't allow me to go out late.", whyHe: "allow someone to do. הצורה -ing באה רק בלי מושא: They don't allow smoking here." },
        { wrong: "I asked to him to help me.", right: "I asked him to help me.", whyHe: "ask לוקח מושא ישיר בלי to: ask him, ask her, ask me." },
      ],
    },
    items: [
      {
        id: "g-verb-object-infinitive-01",
        type: "gap",
        prompt: "My boss told me ___ (wait) outside his office.",
        answer: "to wait",
        explainHe: "המבנה הוא tell + בן אדם + to: told me to wait.",
      },
      {
        id: "g-verb-object-infinitive-02",
        type: "gap",
        prompt: "My parents let me ___ (borrow) their car on Fridays.",
        answer: "borrow",
        hint: "let הוא יוצא דופן",
        explainHe: "let + מושא + פועל בסיס, בלי to: let me borrow.",
      },
      {
        id: "g-verb-object-infinitive-03",
        type: "gap",
        prompt: "The teacher made us ___ (stay) ten minutes after class.",
        answer: "stay",
        explainHe: "make + מושא + פועל בסיס, בלי to: made us stay.",
      },
      {
        id: "g-verb-object-infinitive-04",
        type: "gap",
        prompt: "She reminded me ___ (bring) my passport to the airport.",
        answer: "to bring",
        explainHe: "remind + מושא + to: reminded me to bring.",
      },
      {
        id: "g-verb-object-infinitive-05",
        type: "gap",
        prompt: "I want you ___ (meet) my sister tonight.",
        answer: "to meet",
        explainHe: "want someone to do. בעברית 'אני רוצה שתפגוש', באנגלית I want you to meet.",
      },
      {
        id: "g-verb-object-infinitive-06",
        type: "gap",
        prompt: "We all encouraged her ___ (apply) for the job.",
        answer: "to apply",
        explainHe: "encourage + מושא + to: encouraged her to apply.",
      },
      {
        id: "g-verb-object-infinitive-07",
        type: "gap",
        prompt: "My roommate helped me ___ (carry) the boxes upstairs.",
        answer: "carry",
        accept: ["to carry"],
        explainHe: "אחרי help מותרות שתי הצורות: helped me carry וגם helped me to carry.",
      },
      {
        id: "g-verb-object-infinitive-08",
        type: "gap",
        prompt: "The guide advised us ___ (book) the tickets online.",
        answer: "to book",
        explainHe: "advise + מושא + to: advised us to book.",
      },
      {
        id: "g-verb-object-infinitive-09",
        type: "mcq",
        prompt: "I want ___ with me tomorrow.",
        options: [
          { text: "that you come", errorType: "interference", whyHe: "תרגום ישיר של 'שתבוא'. אחרי want אין משפט that באנגלית." },
          { text: "you to come" },
          { text: "you come", errorType: "verb-form", whyHe: "חסר to. המבנה הוא want + מושא + to + פועל." },
        ],
        answerIndex: 1,
        explainHe: "want + מושא + to, בלי that: I want you to come with me.",
      },
      {
        id: "g-verb-object-infinitive-10",
        type: "mcq",
        prompt: "She ___ me to call her back after six.",
        options: [
          { text: "told" },
          { text: "said", errorType: "word-choice", whyHe: "אחרי say לא בא בן אדם. said me אף פעם לא נכון." },
          { text: "spoke", errorType: "word-choice", whyHe: "speak לא לוקח מושא + to: אומרים speak to me, ולא spoke me to call." },
        ],
        answerIndex: 0,
        explainHe: "tell + בן אדם + to: told me to call. עם say היינו אומרים She said that I should call her.",
      },
      {
        id: "g-verb-object-infinitive-11",
        type: "mcq",
        prompt: "They let us ___ early on Friday.",
        options: [
          { text: "to leave", errorType: "verb-form", whyHe: "let אף פעם לא לוקח to. זו הטעות let me to go." },
          { text: "leaving", errorType: "verb-form", whyHe: "אחרי let באה צורת בסיס, לא -ing." },
          { text: "leave" },
        ],
        answerIndex: 2,
        explainHe: "let + מושא + פועל בסיס: let us leave.",
      },
      {
        id: "g-verb-object-infinitive-12",
        type: "mcq",
        prompt: "My manager made me ___ the whole report.",
        options: [
          { text: "redo" },
          { text: "to redo", errorType: "verb-form", whyHe: "make בפעיל בלי to: made me redo." },
          { text: "redoing", errorType: "verb-form", whyHe: "אחרי make באה צורת בסיס, לא -ing." },
        ],
        answerIndex: 0,
        explainHe: "make + מושא + פועל בסיס: made me redo it. רק בפסיבי חוזר ה-to: I was made to redo it.",
      },
      {
        id: "g-verb-object-infinitive-13",
        type: "mcq",
        prompt: "He asked ___ the window because it was noisy.",
        options: [
          { text: "to me to close", errorType: "preposition", whyHe: "ask לוקח מושא ישיר: ask me, בלי to לפני בן האדם." },
          { text: "me closing", errorType: "verb-form", whyHe: "אחרי ask + מושא באה צורת to, לא -ing." },
          { text: "me to close" },
        ],
        answerIndex: 2,
        explainHe: "ask + מושא + to, בלי to לפני בן האדם: asked me to close the window.",
      },
      {
        id: "g-verb-object-infinitive-14",
        type: "fix",
        prompt: "I want that you come with me.",
        answer: "I want you to come with me.",
        errorType: "interference",
        explainHe: "'אני רוצה שתבוא' הופך ל-want + מושא + to, ולא למשפט that.",
      },
      {
        id: "g-verb-object-infinitive-15",
        type: "fix",
        prompt: "She said me to wait outside.",
        answer: "She told me to wait outside.",
        errorType: "word-choice",
        explainHe: "עם בן אדם משתמשים ב-tell: told me to wait.",
      },
      {
        id: "g-verb-object-infinitive-16",
        type: "fix",
        prompt: "Let me to explain what happened.",
        answer: "Let me explain what happened.",
        errorType: "verb-form",
        explainHe: "let + פועל בסיס בלי to: Let me explain.",
      },
      {
        id: "g-verb-object-infinitive-17",
        type: "fix",
        prompt: "He made me to wait for an hour.",
        answer: "He made me wait for an hour.",
        errorType: "verb-form",
        explainHe: "make בפעיל בלי to: made me wait.",
      },
      {
        id: "g-verb-object-infinitive-18",
        type: "fix",
        prompt: "My parents don't allow me going out late.",
        answer: "My parents don't allow me to go out late.",
        errorType: "verb-form",
        explainHe: "allow someone to do. עם -ing זה רק בלי מושא: allow smoking.",
      },
      {
        id: "g-verb-object-infinitive-19",
        type: "transform",
        prompt: "\"Please close the window,\" I said to him.",
        keyword: "asked",
        answer: "I asked him to close the window.",
        explainHe: "בקשה הופכת ל-ask + מושא + to: asked him to close.",
      },
      {
        id: "g-verb-object-infinitive-20",
        type: "transform",
        prompt: "\"You have to finish it today,\" my manager said.",
        keyword: "told",
        answer: "My manager told me to finish it today.",
        explainHe: "הוראה הופכת ל-tell + מושא + to: told me to finish.",
      },
      {
        id: "g-verb-object-infinitive-21",
        type: "order",
        words: ["my", "boss", "wants", "me", "to", "work", "from", "the", "office"],
        answer: "My boss wants me to work from the office.",
        explainHe: "want + מושא + to: wants me to work. בעברית 'רוצה שאעבוד'.",
      },
      {
        id: "g-verb-object-infinitive-22",
        type: "order",
        words: ["they", "didn't", "let", "us", "take", "any", "photos"],
        answer: "They didn't let us take any photos.",
        explainHe: "let + מושא + פועל בסיס, גם בשלילה: didn't let us take.",
      },
      {
        id: "g-verb-object-infinitive-23",
        type: "translate",
        he: "אני רוצה שתבוא איתי.",
        answer: "I want you to come with me.",
        accept: ["I'd like you to come with me.", "I would like you to come with me."],
        explainHe: "משפט ש' בעברית הופך למושא + to באנגלית: want you to come.",
      },
      {
        id: "g-verb-object-infinitive-24",
        type: "translate",
        he: "המורה נתנה לנו לצאת מוקדם.",
        answer: "The teacher let us leave early.",
        accept: ["The teacher let us go early.", "The teacher allowed us to leave early."],
        explainHe: "let בלי to (let us leave), אבל אם משתמשים ב-allow צריך to: allowed us to leave.",
      },
    ],
  },
];
