// Rapid oral translation drills, set 2: Hebrew -> spoken American English.
// 15 grammar topics x 6 sentences (articles, nouns, prepositions, verb patterns,
// clauses, word order), each forcing the target structure and, where possible,
// containing a classic Hebrew-speaker interference trap.
import type { OralTranslation } from "@/lib/types";

export const ORAL_TRANSLATIONS_2: OralTranslation[] = [
  // ---------- g-articles-a-an-the ----------
  {
    id: "ot2-articles-a-an-the-1",
    he: "הוא רופא, והאישה שלו מורה בבית ספר יסודי.",
    en: "He's a doctor, and his wife's a teacher at an elementary school.",
    alt: ["He is a doctor, and his wife is a teacher in an elementary school."],
    topic: "g-articles-a-an-the",
  },
  {
    id: "ot2-articles-a-an-the-2",
    he: "יש לי פגישה עם מנהל חדש בעוד שעה בערך.",
    en: "I have a meeting with a new manager in about an hour.",
    alt: ["I've got a meeting with a new manager in an hour or so."],
    topic: "g-articles-a-an-the",
  },
  {
    id: "ot2-articles-a-an-the-3",
    he: "קניתי מכונית חדשה, אבל המכונית כבר במוסך כמעט שבוע.",
    en: "I bought a new car, but the car's been in the shop for almost a week.",
    alt: ["I bought a new car, but it's already been at the garage for nearly a week."],
    topic: "g-articles-a-an-the",
  },
  {
    id: "ot2-articles-a-an-the-4",
    he: "פעם בשבוע אני הולך לחדר כושר ליד המשרד.",
    en: "Once a week I go to the gym next to my office.",
    alt: ["I go to the gym near my office once a week."],
    topic: "g-articles-a-an-the",
  },
  {
    id: "ot2-articles-a-an-the-5",
    he: "הילד ששיחק בגינה הוא הבן של השכן שלי.",
    en: "The kid who was playing in the yard is my neighbor's son.",
    alt: ["The boy playing in the garden is the son of my neighbor."],
    topic: "g-articles-a-an-the",
  },
  {
    id: "ot2-articles-a-an-the-6",
    he: "זו הפעם הראשונה שאני מנסה אוכל הודי אמיתי.",
    en: "This is the first time I've tried real Indian food.",
    alt: ["It's the first time I'm trying real Indian food."],
    topic: "g-articles-a-an-the",
  },

  // ---------- g-articles-zero-general ----------
  {
    id: "ot2-articles-zero-1",
    he: "אני אוהב את הכלבים, אבל את החתולים אני לא סובל.",
    en: "I love dogs, but I can't stand cats.",
    alt: ["I like dogs, but I really don't like cats."],
    topic: "g-articles-zero-general",
  },
  {
    id: "ot2-articles-zero-2",
    he: "החיים בישראל יקרים, אבל האנשים כאן חמים מאוד.",
    en: "Life in Israel is expensive, but people here are really warm.",
    alt: ["Life in Israel is expensive, but the people here are very warm."],
    topic: "g-articles-zero-general",
  },
  {
    id: "ot2-articles-zero-3",
    he: "הילדים שלי הולכים לבית ספר ברגל וחוזרים הביתה בצהריים.",
    en: "My kids walk to school and come home at noon.",
    alt: ["My children go to school on foot and come back home around noon."],
    topic: "g-articles-zero-general",
  },
  {
    id: "ot2-articles-zero-4",
    he: "הכסף לא קונה אושר, אבל הוא בהחלט עוזר קצת.",
    en: "Money doesn't buy happiness, but it definitely helps a little.",
    alt: ["Money can't buy happiness, but it sure helps a bit."],
    topic: "g-articles-zero-general",
  },
  {
    id: "ot2-articles-zero-5",
    he: "אחרי העבודה אני הולך לישון מוקדם כי אני קם בשש.",
    en: "After work I go to bed early because I get up at six.",
    alt: ["I go to bed early after work because I get up at six."],
    topic: "g-articles-zero-general",
  },
  {
    id: "ot2-articles-zero-6",
    he: "אני חושב שהטכנולוגיה משנה את החינוך יותר מדי מהר.",
    en: "I think technology is changing education way too fast.",
    alt: ["I think that technology is changing education too quickly."],
    topic: "g-articles-zero-general",
  },

  // ---------- g-countable-uncountable ----------
  {
    id: "ot2-countable-uncountable-1",
    he: "אני צריך עצה טובה לפני שאני מחליט משהו.",
    en: "I need some good advice before I decide anything.",
    alt: ["I need good advice before I make any decision."],
    topic: "g-countable-uncountable",
  },
  {
    id: "ot2-countable-uncountable-2",
    he: "יש לי הרבה עבודה השבוע ומעט מאוד זמן פנוי.",
    en: "I have a lot of work this week and very little free time.",
    alt: ["I've got tons of work this week and hardly any free time."],
    topic: "g-countable-uncountable",
  },
  {
    id: "ot2-countable-uncountable-3",
    he: "אתה יכול לתת לי מידע נוסף על הקורס הזה?",
    en: "Can you give me some more information about this course?",
    alt: ["Could you give me a bit more information about the course?"],
    topic: "g-countable-uncountable",
  },
  {
    id: "ot2-countable-uncountable-4",
    he: "החדשות אתמול היו ממש מדכאות, אז כיביתי את הטלוויזיה.",
    en: "The news yesterday was really depressing, so I turned off the TV.",
    alt: ["Yesterday's news was so depressing that I turned the TV off."],
    topic: "g-countable-uncountable",
  },
  {
    id: "ot2-countable-uncountable-5",
    he: "קנינו רהיטים חדשים לסלון והם עלו לנו הרבה כסף.",
    en: "We bought new furniture for the living room, and it cost us a lot of money.",
    alt: ["We got some new furniture for the living room, and it cost us a fortune."],
    topic: "g-countable-uncountable",
  },
  {
    id: "ot2-countable-uncountable-6",
    he: "לא היה לי מספיק זמן לעשות את כל שיעורי הבית.",
    en: "I didn't have enough time to do all my homework.",
    alt: ["There wasn't enough time for me to do all the homework."],
    topic: "g-countable-uncountable",
  },

  // ---------- g-quantifiers ----------
  {
    id: "ot2-quantifiers-1",
    he: "יש הרבה אנשים בחוץ, אז בוא ניקח שולחן בפנים.",
    en: "There are a lot of people outside, so let's take a table inside.",
    alt: ["There are lots of people outside, so let's get a table indoors."],
    topic: "g-quantifiers",
  },
  {
    id: "ot2-quantifiers-2",
    he: "לא נשאר לנו הרבה חלב, אבל יש קצת קפה.",
    en: "We don't have much milk left, but there's a little coffee.",
    alt: ["There isn't much milk left, but we do have some coffee."],
    topic: "g-quantifiers",
  },
  {
    id: "ot2-quantifiers-3",
    he: "כמה זמן זה ייקח, וכמה אנשים צריכים להגיע?",
    en: "How long will it take, and how many people need to come?",
    alt: ["How much time will this take, and how many people are supposed to come?"],
    topic: "g-quantifiers",
  },
  {
    id: "ot2-quantifiers-4",
    he: "יש לי רק כמה דקות פנויות, אז בוא נדבר מהר.",
    en: "I only have a few minutes free, so let's talk fast.",
    alt: ["I've only got a couple of minutes, so let's make it quick."],
    topic: "g-quantifiers",
  },
  {
    id: "ot2-quantifiers-5",
    he: "רוב החברים שלי לא שותים קפה אחרי שבע בערב.",
    en: "Most of my friends don't drink coffee after seven in the evening.",
    alt: ["Most of my friends don't have coffee after seven p.m."],
    topic: "g-quantifiers",
  },
  {
    id: "ot2-quantifiers-6",
    he: "כמעט אף אחד לא בא לפגישה, ולא הרבה אנשים התנצלו.",
    en: "Almost nobody came to the meeting, and not many people apologized.",
    alt: ["Hardly anyone came to the meeting, and not many of them apologized."],
    topic: "g-quantifiers",
  },

  // ---------- g-there-is-it-is ----------
  {
    id: "ot2-there-is-1",
    he: "יש בעיה עם המזגן, והוא לא עובד מאתמול.",
    en: "There's a problem with the AC, and it hasn't worked since yesterday.",
    alt: ["There's an issue with the air conditioner, and it hasn't been working since yesterday."],
    topic: "g-there-is-it-is",
  },
  {
    id: "ot2-there-is-2",
    he: "אין חלב במקרר, אבל יש כמה ביצים וגבינה.",
    en: "There's no milk in the fridge, but there are a few eggs and some cheese.",
    alt: ["There isn't any milk in the fridge, but there are some eggs and cheese."],
    topic: "g-there-is-it-is",
  },
  {
    id: "ot2-there-is-3",
    he: "זה לא קל למצוא חניה כאן בשעות הערב.",
    en: "It's not easy to find parking here in the evening.",
    alt: ["It isn't easy to find a parking spot around here in the evenings."],
    topic: "g-there-is-it-is",
  },
  {
    id: "ot2-there-is-4",
    he: "יש הרבה תיירים בעיר בקיץ, וזה קצת מעצבן.",
    en: "There are a lot of tourists in the city in the summer, and it's a little annoying.",
    alt: ["There are tons of tourists in town in the summer, and it's kind of annoying."],
    topic: "g-there-is-it-is",
  },
  {
    id: "ot2-there-is-5",
    he: "הייתה תאונה בכביש, ולכן היה פקק ענק הבוקר.",
    en: "There was an accident on the road, so there was a huge traffic jam this morning.",
    alt: ["There was a crash on the highway, so there was massive traffic this morning."],
    topic: "g-there-is-it-is",
  },
  {
    id: "ot2-there-is-6",
    he: "אין טעם להתקשר עכשיו, כי אין אף אחד במשרד.",
    en: "There's no point calling now, because there's nobody in the office.",
    alt: ["It's not worth calling now, because there isn't anyone at the office."],
    topic: "g-there-is-it-is",
  },

  // ---------- g-prepositions-time-place ----------
  {
    id: "ot2-prep-time-place-1",
    he: "הפגישה תתחיל בתשע בבוקר ביום שני, במשרד החדש.",
    en: "The meeting starts at nine in the morning on Monday, at the new office.",
    alt: ["The meeting begins at nine a.m. on Monday at the new office."],
    topic: "g-prepositions-time-place",
  },
  {
    id: "ot2-prep-time-place-2",
    he: "אני גר ברחוב הרצל, בבניין הגדול מול הפארק.",
    en: "I live on Herzl Street, in the big building across from the park.",
    alt: ["I live on Herzl Street, in the big building opposite the park."],
    topic: "g-prepositions-time-place",
  },
  {
    id: "ot2-prep-time-place-3",
    he: "נולדתי ב-1990, ובקיץ אנחנו תמיד נוסעים לצפון לשבוע.",
    en: "I was born in 1990, and in the summer we always go up north for a week.",
    alt: ["I was born in 1990, and in the summer we always drive up north for a week."],
    topic: "g-prepositions-time-place",
  },
  {
    id: "ot2-prep-time-place-4",
    he: "הגעתי לתחנה בזמן, אבל האוטובוס כבר יצא בלעדיי.",
    en: "I got to the station on time, but the bus had already left without me.",
    alt: ["I arrived at the station on time, but the bus was already gone."],
    topic: "g-prepositions-time-place",
  },
  {
    id: "ot2-prep-time-place-5",
    he: "ביום שישי בערב אנחנו בדרך כלל אוכלים אצל ההורים שלי.",
    en: "On Friday night we usually eat at my parents' place.",
    alt: ["On Friday evenings we usually have dinner at my parents' house."],
    topic: "g-prepositions-time-place",
  },
  {
    id: "ot2-prep-time-place-6",
    he: "חיכיתי לך בפינה של הרחוב במשך עשרים דקות בגשם.",
    en: "I waited for you on the corner of the street for twenty minutes in the rain.",
    alt: ["I was waiting for you at the corner for twenty minutes in the rain."],
    topic: "g-prepositions-time-place",
  },

  // ---------- g-dependent-prepositions ----------
  {
    id: "ot2-dependent-prep-1",
    he: "זה תלוי במזג האוויר, אז נחליט רק מחר בבוקר.",
    en: "It depends on the weather, so we'll only decide tomorrow morning.",
    alt: ["That depends on the weather, so we'll decide in the morning."],
    topic: "g-dependent-prepositions",
  },
  {
    id: "ot2-dependent-prep-2",
    he: "אני מחכה לתשובה מהם כבר שבועיים ומתחיל לדאוג.",
    en: "I've been waiting for an answer from them for two weeks, and I'm starting to worry.",
    alt: ["I've been waiting for their answer for two weeks now, and I'm getting worried."],
    topic: "g-dependent-prepositions",
  },
  {
    id: "ot2-dependent-prep-3",
    he: "היא מאוד טובה במתמטיקה, אבל היא לא אוהבת ללמד.",
    en: "She's really good at math, but she doesn't like teaching.",
    alt: ["She's very good at math, but she doesn't enjoy teaching."],
    topic: "g-dependent-prepositions",
  },
  {
    id: "ot2-dependent-prep-4",
    he: "אחותי התחתנה עם רופא מחיפה והם גרים ליד הים.",
    en: "My sister got married to a doctor from Haifa, and they live near the sea.",
    alt: ["My sister married a doctor from Haifa, and they live by the beach."],
    topic: "g-dependent-prepositions",
  },
  {
    id: "ot2-dependent-prep-5",
    he: "אני לא מקשיב למוזיקה בעבודה כי זה מפריע לי להתרכז.",
    en: "I don't listen to music at work because it stops me from concentrating.",
    alt: ["I don't listen to music at work because it makes it hard for me to concentrate."],
    topic: "g-dependent-prepositions",
  },
  {
    id: "ot2-dependent-prep-6",
    he: "הוא התנצל על האיחור והסביר שהוא חיכה לאוטובוס בגשם.",
    en: "He apologized for being late and explained that he'd been waiting for the bus in the rain.",
    alt: ["He apologized for the delay and explained that he was waiting for a bus in the rain."],
    topic: "g-dependent-prepositions",
  },

  // ---------- g-gerund-infinitive ----------
  {
    id: "ot2-gerund-infinitive-1",
    he: "אני נהנה לבשל, אבל אני שונא לשטוף כלים אחר כך.",
    en: "I enjoy cooking, but I hate doing the dishes afterward.",
    alt: ["I love cooking, but I hate washing the dishes afterwards."],
    topic: "g-gerund-infinitive",
  },
  {
    id: "ot2-gerund-infinitive-2",
    he: "סיימתי לעבוד בשמונה בערב והחלטתי ללכת ישר הביתה.",
    en: "I finished working at eight and decided to go straight home.",
    alt: ["I got done working at eight p.m. and decided to head straight home."],
    topic: "g-gerund-infinitive",
  },
  {
    id: "ot2-gerund-infinitive-3",
    he: "הוא הפסיק לעשן לפני שנה, וזה שינה לו את החיים.",
    en: "He quit smoking a year ago, and it changed his life.",
    alt: ["He stopped smoking a year ago, and it's changed his life."],
    topic: "g-gerund-infinitive",
  },
  {
    id: "ot2-gerund-infinitive-4",
    he: "אכפת לך לחכות בחוץ כמה דקות עד שאסיים?",
    en: "Do you mind waiting outside for a few minutes until I finish?",
    alt: ["Would you mind waiting outside a few minutes until I'm done?"],
    topic: "g-gerund-infinitive",
  },
  {
    id: "ot2-gerund-infinitive-5",
    he: "אני מנסה להימנע מלאכול מתוקים בערב, אבל זה קשה.",
    en: "I try to avoid eating sweets in the evening, but it's hard.",
    alt: ["I'm trying to avoid eating sweets at night, but it's not easy."],
    topic: "g-gerund-infinitive",
  },
  {
    id: "ot2-gerund-infinitive-6",
    he: "הוא הציע לצאת לארוחת ערב, ואני הבטחתי לחשוב על זה.",
    en: "He suggested going out for dinner, and I promised to think about it.",
    alt: ["He suggested that we go out for dinner, and I promised to think it over."],
    topic: "g-gerund-infinitive",
  },

  // ---------- g-verb-object-infinitive ----------
  {
    id: "ot2-verb-object-inf-1",
    he: "אני רוצה שתתקשר אליי אחרי שאתה מגיע הביתה.",
    en: "I want you to call me after you get home.",
    alt: ["I'd like you to call me once you get home."],
    topic: "g-verb-object-infinitive",
  },
  {
    id: "ot2-verb-object-inf-2",
    he: "ההורים שלי רוצים שאני אלמד רפואה, אבל אני לא בטוח.",
    en: "My parents want me to study medicine, but I'm not sure.",
    alt: ["My parents would like me to study medicine, but I'm not sure about it."],
    topic: "g-verb-object-infinitive",
  },
  {
    id: "ot2-verb-object-inf-3",
    he: "ביקשתי ממנו לשלוח לי את הקובץ, והוא שכח לגמרי.",
    en: "I asked him to send me the file, and he completely forgot.",
    alt: ["I asked him to email me the file, and he totally forgot."],
    topic: "g-verb-object-infinitive",
  },
  {
    id: "ot2-verb-object-inf-4",
    he: "תגידי לילדים לסדר את החדר לפני שהאורחים מגיעים.",
    en: "Tell the kids to clean up their room before the guests get here.",
    alt: ["Tell the kids to tidy their room before the guests arrive."],
    topic: "g-verb-object-infinitive",
  },
  {
    id: "ot2-verb-object-inf-5",
    he: "המנהל שלי לא נותן לנו לעבוד מהבית ביום שישי.",
    en: "My manager doesn't let us work from home on Fridays.",
    alt: ["My boss won't let us work from home on Friday."],
    topic: "g-verb-object-infinitive",
  },
  {
    id: "ot2-verb-object-inf-6",
    he: "הייתי רוצה שהם יגידו לי מראש אם משהו משתנה.",
    en: "I'd like them to tell me in advance if something changes.",
    alt: ["I want them to let me know ahead of time if anything changes."],
    topic: "g-verb-object-infinitive",
  },

  // ---------- g-relative-clauses ----------
  {
    id: "ot2-relative-clauses-1",
    he: "האיש שגר לידי עובד בבית חולים בתל אביב.",
    en: "The guy who lives next to me works at a hospital in Tel Aviv.",
    alt: ["The man who lives next door to me works in a hospital in Tel Aviv."],
    topic: "g-relative-clauses",
  },
  {
    id: "ot2-relative-clauses-2",
    he: "הסרט שראינו אתמול היה ארוך מדי, אבל הסוף היה מפתיע.",
    en: "The movie we saw yesterday was too long, but the ending was surprising.",
    alt: ["The film that we watched yesterday was too long, but the ending was a surprise."],
    topic: "g-relative-clauses",
  },
  {
    id: "ot2-relative-clauses-3",
    he: "זה המקום שבו נפגשנו בפעם הראשונה לפני עשר שנים.",
    en: "This is the place where we first met ten years ago.",
    alt: ["This is where we met for the first time ten years ago."],
    topic: "g-relative-clauses",
  },
  {
    id: "ot2-relative-clauses-4",
    he: "האנשים שאיתם עבדתי בפרויקט הזה היו ממש מקצועיים.",
    en: "The people I worked with on this project were really professional.",
    alt: ["The people that I worked with on this project were very professional."],
    topic: "g-relative-clauses",
  },
  {
    id: "ot2-relative-clauses-5",
    he: "יש לי חבר שאחותו עובדת בחברה שאליה הגשתי מועמדות.",
    en: "I have a friend whose sister works at the company I applied to.",
    alt: ["I've got a friend whose sister works for the company that I applied to."],
    topic: "g-relative-clauses",
  },
  {
    id: "ot2-relative-clauses-6",
    he: "הדירה שקנינו בשנה שעברה, שנמצאת ליד הים, עלתה הון.",
    en: "The apartment we bought last year, which is near the beach, cost a fortune.",
    alt: ["The apartment that we bought last year, which is right by the sea, cost us a fortune."],
    topic: "g-relative-clauses",
  },

  // ---------- g-linking-words ----------
  {
    id: "ot2-linking-words-1",
    he: "איחרתי לעבודה בגלל הפקק הענק בכניסה לעיר הבוקר.",
    en: "I was late for work because of the huge traffic jam coming into the city this morning.",
    alt: ["I got to work late because of all the traffic at the entrance to the city this morning."],
    topic: "g-linking-words",
  },
  {
    id: "ot2-linking-words-2",
    he: "הוא לא בא לפגישה, ולכן החלטנו להתחיל בלעדיו.",
    en: "He didn't come to the meeting, so we decided to start without him.",
    alt: ["He didn't show up to the meeting, so we decided to start without him."],
    topic: "g-linking-words",
  },
  {
    id: "ot2-linking-words-3",
    he: "למרות שהיה גשם חזק, יצאנו לטיול והיה ממש כיף.",
    en: "Even though it was raining hard, we went on a hike and had a great time.",
    alt: ["Although it was raining heavily, we went out for a hike and it was really fun."],
    topic: "g-linking-words",
  },
  {
    id: "ot2-linking-words-4",
    he: "בזמן שאני מבשל, אשתי עוזרת לילדים עם שיעורי הבית.",
    en: "While I'm cooking, my wife helps the kids with their homework.",
    alt: ["While I cook, my wife helps the kids with the homework."],
    topic: "g-linking-words",
  },
  {
    id: "ot2-linking-words-5",
    he: "הדירה יפה מאוד; עם זאת, המחיר גבוה מדי בשבילנו.",
    en: "The apartment's really nice; however, the price is too high for us.",
    alt: ["The place is very nice; however, it's too expensive for us."],
    topic: "g-linking-words",
  },
  {
    id: "ot2-linking-words-6",
    he: "למרות המחיר הגבוה, קנינו את המכונית כי היינו צריכים אותה.",
    en: "In spite of the high price, we bought the car because we needed it.",
    alt: ["Despite the high price, we bought the car because we needed one."],
    topic: "g-linking-words",
  },

  // ---------- g-comparatives-superlatives ----------
  {
    id: "ot2-comparatives-1",
    he: "הבית החדש שלנו גדול יותר, אבל רחוק יותר מהעבודה.",
    en: "Our new house is bigger, but it's farther from work.",
    alt: ["Our new place is bigger, but it's further away from work."],
    topic: "g-comparatives-superlatives",
  },
  {
    id: "ot2-comparatives-2",
    he: "אחי הצעיר גבוה ממני, למרות שהוא צעיר בחמש שנים.",
    en: "My younger brother is taller than me, even though he's five years younger.",
    alt: ["My little brother is taller than I am, even though he's five years younger."],
    topic: "g-comparatives-superlatives",
  },
  {
    id: "ot2-comparatives-3",
    he: "העברית שלי הרבה יותר טובה מהאנגלית שלי, לצערי.",
    en: "My Hebrew is much better than my English, unfortunately.",
    alt: ["Unfortunately, my Hebrew is a lot better than my English."],
    topic: "g-comparatives-superlatives",
  },
  {
    id: "ot2-comparatives-4",
    he: "זאת המסעדה הכי טובה בעיר, אבל גם היקרה ביותר.",
    en: "It's the best restaurant in town, but it's also the most expensive.",
    alt: ["This is the best restaurant in the city, and also the priciest one."],
    topic: "g-comparatives-superlatives",
  },
  {
    id: "ot2-comparatives-5",
    he: "הוא לא עובד קשה כמוני, אבל הוא מרוויח יותר.",
    en: "He doesn't work as hard as I do, but he makes more money.",
    alt: ["He doesn't work as hard as me, but he earns more."],
    topic: "g-comparatives-superlatives",
  },
  {
    id: "ot2-comparatives-6",
    he: "ככל שאני מתאמן יותר, כך קל לי יותר לרוץ.",
    en: "The more I train, the easier it is for me to run.",
    alt: ["The more I work out, the easier running gets."],
    topic: "g-comparatives-superlatives",
  },

  // ---------- g-so-such-too-enough ----------
  {
    id: "ot2-so-such-too-enough-1",
    he: "הקפה חם מדי, אני לא יכול לשתות אותו עכשיו.",
    en: "The coffee's too hot; I can't drink it right now.",
    alt: ["This coffee is too hot for me to drink right now."],
    topic: "g-so-such-too-enough",
  },
  {
    id: "ot2-so-such-too-enough-2",
    he: "הוא היה כל כך עייף שהוא נרדם מול הטלוויזיה.",
    en: "He was so tired that he fell asleep in front of the TV.",
    alt: ["He was so tired he fell asleep watching TV."],
    topic: "g-so-such-too-enough",
  },
  {
    id: "ot2-so-such-too-enough-3",
    he: "אין לנו מספיק זמן לעשות את זה כמו שצריך.",
    en: "We don't have enough time to do it properly.",
    alt: ["There isn't enough time for us to do this the right way."],
    topic: "g-so-such-too-enough",
  },
  {
    id: "ot2-so-such-too-enough-4",
    he: "אני לא מבוגר מספיק כדי לשכור מכונית בארצות הברית.",
    en: "I'm not old enough to rent a car in the States.",
    alt: ["I'm still not old enough to rent a car in the US."],
    topic: "g-so-such-too-enough",
  },
  {
    id: "ot2-so-such-too-enough-5",
    he: "זאת הייתה ארוחה כל כך טעימה שביקשנו את המתכון.",
    en: "It was such a good meal that we asked for the recipe.",
    alt: ["It was such a tasty dinner that we asked them for the recipe."],
    topic: "g-so-such-too-enough",
  },
  {
    id: "ot2-so-such-too-enough-6",
    he: "הרעש בחוץ היה חזק מדי בשביל להירדם, אז לקחתי אטמים.",
    en: "The noise outside was too loud to fall asleep, so I put in earplugs.",
    alt: ["It was too noisy outside for me to fall asleep, so I used earplugs."],
    topic: "g-so-such-too-enough",
  },

  // ---------- g-adverb-position ----------
  {
    id: "ot2-adverb-position-1",
    he: "אני תמיד הולך ברגל לעבודה בבוקר, גם בחורף.",
    en: "I always walk to work in the morning, even in the winter.",
    alt: ["In the morning I always walk to work, even in winter."],
    topic: "g-adverb-position",
  },
  {
    id: "ot2-adverb-position-2",
    he: "הוא כמעט אף פעם לא עונה לטלפון בשעות הערב.",
    en: "He almost never answers the phone in the evening.",
    alt: ["He hardly ever picks up the phone in the evenings."],
    topic: "g-adverb-position",
  },
  {
    id: "ot2-adverb-position-3",
    he: "אני מאוד אוהב את העבודה שלי, למרות הלחץ.",
    en: "I really like my job, in spite of the pressure.",
    alt: ["I like my job a lot, despite the stress."],
    topic: "g-adverb-position",
  },
  {
    id: "ot2-adverb-position-4",
    he: "היא בדרך כלל מגיעה מוקדם, אבל היום היא איחרה קצת.",
    en: "She usually gets in early, but today she was a little late.",
    alt: ["She usually arrives early, but she was a bit late today."],
    topic: "g-adverb-position",
  },
  {
    id: "ot2-adverb-position-5",
    he: "כבר סיימתי את הדוח, אבל עוד לא שלחתי אותו למנהל.",
    en: "I've already finished the report, but I haven't sent it to my manager yet.",
    alt: ["I already finished the report, but I still haven't sent it to my boss."],
    topic: "g-adverb-position",
  },
  {
    id: "ot2-adverb-position-6",
    he: "אני בקושי רואה אותו לאחרונה, כי הוא עובד עד מאוחר.",
    en: "I barely see him these days because he works late.",
    alt: ["I hardly ever see him lately, because he works until late."],
    topic: "g-adverb-position",
  },

  // ---------- g-adjective-order ----------
  {
    id: "ot2-adjective-order-1",
    he: "קניתי חולצה כחולה חדשה בשביל החתונה של אחי.",
    en: "I bought a new blue shirt for my brother's wedding.",
    alt: ["I got myself a new blue shirt for my brother's wedding."],
    topic: "g-adjective-order",
  },
  {
    id: "ot2-adjective-order-2",
    he: "יש לנו שולחן עץ גדול במטבח, וכולם אוהבים אותו.",
    en: "We have a big wooden table in the kitchen, and everybody loves it.",
    alt: ["We've got a large wooden table in the kitchen, and everyone loves it."],
    topic: "g-adjective-order",
  },
  {
    id: "ot2-adjective-order-3",
    he: "פגשתי בחורה איטלקייה צעירה ונחמדה בקורס של יום ראשון.",
    en: "I met a nice young Italian girl in the Sunday class.",
    alt: ["I met a lovely young Italian woman in the Sunday course."],
    topic: "g-adjective-order",
  },
  {
    id: "ot2-adjective-order-4",
    he: "קיבלתי במתנה שעון שוויצרי שחור יקר ליום ההולדת שלי.",
    en: "I got an expensive black Swiss watch for my birthday.",
    alt: ["I was given an expensive black Swiss watch for my birthday."],
    topic: "g-adjective-order",
  },
  {
    id: "ot2-adjective-order-5",
    he: "הם גרים בבית אבן קטן ויפה בכפר ליד ירושלים.",
    en: "They live in a beautiful little stone house in a village near Jerusalem.",
    alt: ["They live in a lovely little stone house in a village outside Jerusalem."],
    topic: "g-adjective-order",
  },
  {
    id: "ot2-adjective-order-6",
    he: "הוא נהג במכונית ספורט אדומה ישנה שהייתה של אבא שלו.",
    en: "He was driving an old red sports car that used to be his dad's.",
    alt: ["He drove an old red sports car that had belonged to his father."],
    topic: "g-adjective-order",
  },
];
