// Rapid oral translation drills: Hebrew -> spoken American English.
// 44 grammar topics x 6 sentences, each forcing the target structure and,
// where possible, containing a classic Hebrew-speaker interference trap.
import type { OralTranslation } from "@/lib/types";

export const ORAL_TRANSLATIONS: OralTranslation[] = [
  // ---------- g-present-simple-continuous ----------
  {
    id: "ot-present-simple-cont-1",
    he: "אני בדרך כלל שותה קפה בבוקר, אבל היום אני שותה תה.",
    en: "I usually drink coffee in the morning, but today I'm drinking tea.",
    alt: ["I usually have coffee in the morning, but today I'm having tea."],
    topic: "g-present-simple-continuous",
  },
  {
    id: "ot-present-simple-cont-2",
    he: "מה אתה עושה עכשיו? אני מכין ארוחת ערב לילדים.",
    en: "What are you doing right now? I'm making dinner for the kids.",
    alt: ["What are you doing now? I'm cooking dinner for the kids."],
    topic: "g-present-simple-continuous",
  },
  {
    id: "ot-present-simple-cont-3",
    he: "היא לא עובדת בימי שישי, אבל השבוע היא עובדת.",
    en: "She doesn't work on Fridays, but this week she's working.",
    alt: ["She doesn't work Fridays, but this week she is working."],
    topic: "g-present-simple-continuous",
  },
  {
    id: "ot-present-simple-cont-4",
    he: "הילדים כבר ישנים עכשיו, אז אנחנו מדברים בשקט.",
    en: "The kids are already asleep now, so we're talking quietly.",
    alt: ["The kids are sleeping now, so we're speaking quietly."],
    topic: "g-present-simple-continuous",
  },
  {
    id: "ot-present-simple-cont-5",
    he: "אני לא מבין למה הוא תמיד מאחר לפגישות.",
    en: "I don't understand why he's always late for meetings.",
    alt: ["I don't get why he's always late to meetings."],
    topic: "g-present-simple-continuous",
  },
  {
    id: "ot-present-simple-cont-6",
    he: "אחי גר בחיפה, אבל כרגע הוא גר אצלי.",
    en: "My brother lives in Haifa, but right now he's staying with me.",
    alt: ["My brother lives in Haifa, but at the moment he's living at my place."],
    topic: "g-present-simple-continuous",
  },

  // ---------- g-past-simple ----------
  {
    id: "ot-past-simple-1",
    he: "אתמול הלכתי לים עם כמה חברים ונהניתי מאוד.",
    en: "Yesterday I went to the beach with some friends and had a great time.",
    alt: ["I went to the beach with a few friends yesterday and really enjoyed it."],
    topic: "g-past-simple",
  },
  {
    id: "ot-past-simple-2",
    he: "היא לא באה לפגישה אתמול כי היא הייתה חולה.",
    en: "She didn't come to the meeting yesterday because she was sick.",
    alt: ["She didn't show up to the meeting yesterday because she was ill."],
    topic: "g-past-simple",
  },
  {
    id: "ot-past-simple-3",
    he: "מתי חזרת מהטיול בחו\"ל? חזרתי לפני שבועיים בערך.",
    en: "When did you get back from your trip abroad? I got back about two weeks ago.",
    alt: ["When did you come back from the trip abroad? I came back around two weeks ago."],
    topic: "g-past-simple",
  },
  {
    id: "ot-past-simple-4",
    he: "קניתי את הדירה הזאת לפני חמש שנים, ממש בזול.",
    en: "I bought this apartment five years ago, really cheap.",
    alt: ["I bought this apartment five years ago at a really good price."],
    topic: "g-past-simple",
  },
  {
    id: "ot-past-simple-5",
    he: "למה לא התקשרת אליי אתמול בערב? חיכיתי לך שעה.",
    en: "Why didn't you call me last night? I waited for you for an hour.",
    alt: ["Why didn't you call me yesterday evening? I waited an hour for you."],
    topic: "g-past-simple",
  },
  {
    id: "ot-past-simple-6",
    he: "בילדות גרנו בכפר קטן, ואבא שלי עבד בחקלאות.",
    en: "When we were kids, we lived in a small village, and my dad worked in farming.",
    alt: ["As kids we lived in a small village, and my father was a farmer."],
    topic: "g-past-simple",
  },

  // ---------- g-past-continuous ----------
  {
    id: "ot-past-cont-1",
    he: "כשהתקשרת אליי אתמול, בדיוק אכלתי ארוחת צהריים עם אמא.",
    en: "When you called me yesterday, I was just having lunch with my mom.",
    alt: ["When you called yesterday, I was eating lunch with my mom."],
    topic: "g-past-continuous",
  },
  {
    id: "ot-past-cont-2",
    he: "מה עשית אתמול בשמונה בערב? צפיתי בטלוויזיה עם אשתי.",
    en: "What were you doing at eight last night? I was watching TV with my wife.",
    alt: ["What were you doing yesterday at eight p.m.? I was watching television with my wife."],
    topic: "g-past-continuous",
  },
  {
    id: "ot-past-cont-3",
    he: "ירד גשם חזק כל היום, אז נשארנו בבית.",
    en: "It was raining hard all day, so we stayed home.",
    alt: ["It rained hard all day, so we stayed at home."],
    topic: "g-past-continuous",
  },
  {
    id: "ot-past-cont-4",
    he: "הוא נהג הביתה כשפתאום המכונית נעצרה באמצע הכביש.",
    en: "He was driving home when suddenly the car stopped in the middle of the road.",
    alt: ["He was driving home when the car suddenly died in the middle of the road."],
    topic: "g-past-continuous",
  },
  {
    id: "ot-past-cont-5",
    he: "בזמן שהיא בישלה במטבח, הילדים שיחקו בחצר האחורית.",
    en: "While she was cooking in the kitchen, the kids were playing in the backyard.",
    alt: ["While she was cooking, the kids were playing out in the backyard."],
    topic: "g-past-continuous",
  },
  {
    id: "ot-past-cont-6",
    he: "לא שמעתי את הטלפון כי התקלחתי באותו רגע.",
    en: "I didn't hear the phone because I was in the shower at that moment.",
    alt: ["I didn't hear the phone because I was taking a shower right then."],
    topic: "g-past-continuous",
  },

  // ---------- g-present-perfect ----------
  {
    id: "ot-present-perfect-1",
    he: "אני גר בתל אביב כבר שלוש שנים וחצי.",
    en: "I've lived in Tel Aviv for three and a half years.",
    alt: ["I've been living in Tel Aviv for three and a half years."],
    topic: "g-present-perfect",
  },
  {
    id: "ot-present-perfect-2",
    he: "כבר אכלת? לא, עוד לא אכלתי כלום היום.",
    en: "Have you eaten yet? No, I haven't eaten anything today.",
    alt: ["Have you eaten already? No, I haven't had anything to eat today."],
    topic: "g-present-perfect",
  },
  {
    id: "ot-present-perfect-3",
    he: "היית פעם ביפן? כן, הייתי שם כבר פעמיים.",
    en: "Have you ever been to Japan? Yes, I've been there twice.",
    alt: ["Have you ever been to Japan? Yeah, I've already been there twice."],
    topic: "g-present-perfect",
  },
  {
    id: "ot-present-perfect-4",
    he: "איבדתי את המפתחות שלי ואני לא מוצא אותם.",
    en: "I've lost my keys and I can't find them.",
    alt: ["I lost my keys and I can't find them."],
    topic: "g-present-perfect",
  },
  {
    id: "ot-present-perfect-5",
    he: "הוא עוד לא סיים את העבודה, אז הוא לא יכול לבוא.",
    en: "He hasn't finished the work yet, so he can't come.",
    alt: ["He still hasn't finished his work, so he can't make it."],
    topic: "g-present-perfect",
  },
  {
    id: "ot-present-perfect-6",
    he: "אנחנו מכירים אחד את השני כבר עשרים שנה, מאז התיכון.",
    en: "We've known each other for twenty years, since high school.",
    alt: ["We've known each other for twenty years now, ever since high school."],
    topic: "g-present-perfect",
  },

  // ---------- g-present-perfect-vs-past ----------
  {
    id: "ot-pp-vs-past-1",
    he: "ראית את הסרט החדש? כן, ראיתי אותו בשבוע שעבר.",
    en: "Have you seen the new movie? Yes, I saw it last week.",
    alt: ["Have you seen the new film? Yeah, I saw it last week."],
    topic: "g-present-perfect-vs-past",
  },
  {
    id: "ot-pp-vs-past-2",
    he: "היא כבר הייתה בלונדון פעמיים; בפעם האחרונה זה היה ב-2019.",
    en: "She's been to London twice; the last time was in 2019.",
    alt: ["She's already been to London twice. The last time was in 2019."],
    topic: "g-present-perfect-vs-past",
  },
  {
    id: "ot-pp-vs-past-3",
    he: "אבא שלי עבד בבנק ארבעים שנה, עד שיצא לפנסיה.",
    en: "My dad worked at a bank for forty years, until he retired.",
    alt: ["My father worked in a bank for forty years until he retired."],
    topic: "g-present-perfect-vs-past",
  },
  {
    id: "ot-pp-vs-past-4",
    he: "שברתי את היד לפני חודש, ועדיין לא החלמתי לגמרי.",
    en: "I broke my arm a month ago, and I still haven't fully recovered.",
    alt: ["I broke my arm a month ago, and I haven't completely recovered yet."],
    topic: "g-present-perfect-vs-past",
  },
  {
    id: "ot-pp-vs-past-5",
    he: "עוד לא דיברתי עם המנהל, אבל אתמול שלחתי לו מייל.",
    en: "I haven't talked to the manager yet, but I sent him an email yesterday.",
    alt: ["I haven't spoken to the manager yet, but I emailed him yesterday."],
    topic: "g-present-perfect-vs-past",
  },
  {
    id: "ot-pp-vs-past-6",
    he: "היום עוד לא הספקתי לאכול, אבל אתמול אכלתי המון.",
    en: "I haven't had time to eat yet today, but yesterday I ate a ton.",
    alt: ["I haven't gotten around to eating today, but I ate a lot yesterday."],
    topic: "g-present-perfect-vs-past",
  },

  // ---------- g-for-since ----------
  {
    id: "ot-for-since-1",
    he: "אני לומד אנגלית באפליקציה הזאת כבר שנתיים בערך.",
    en: "I've been learning English on this app for about two years.",
    alt: ["I've been studying English with this app for around two years."],
    topic: "g-for-since",
  },
  {
    id: "ot-for-since-2",
    he: "לא ראיתי את יוסי מאז החתונה של אחותך.",
    en: "I haven't seen Yossi since your sister's wedding.",
    topic: "g-for-since",
  },
  {
    id: "ot-for-since-3",
    he: "היא עובדת בחברה הזאת מאז 2018, כמעט שמונה שנים.",
    en: "She's worked at this company since 2018, almost eight years.",
    alt: ["She's been working at this company since 2018, nearly eight years."],
    topic: "g-for-since",
  },
  {
    id: "ot-for-since-4",
    he: "כמה זמן אתם נשואים? בערך חמש עשרה שנה.",
    en: "How long have you been married? About fifteen years.",
    alt: ["How long have you two been married? Around fifteen years."],
    topic: "g-for-since",
  },
  {
    id: "ot-for-since-5",
    he: "לא דיברנו מאז הריב ההוא, כבר יותר מחודש.",
    en: "We haven't talked since that fight, for over a month now.",
    alt: ["We haven't spoken since that argument, more than a month now."],
    topic: "g-for-since",
  },
  {
    id: "ot-for-since-6",
    he: "הוא מחכה לתשובה מהבנק מאז יום שני, כלומר כבר ארבעה ימים.",
    en: "He's been waiting for an answer from the bank since Monday, so four days now.",
    alt: ["He's been waiting for a reply from the bank since Monday, that's four days already."],
    topic: "g-for-since",
  },

  // ---------- g-present-perfect-continuous ----------
  {
    id: "ot-pp-cont-1",
    he: "אני מחכה לך פה בחוץ כבר חצי שעה!",
    en: "I've been waiting for you out here for half an hour!",
    alt: ["I've been waiting out here for you for thirty minutes!"],
    topic: "g-present-perfect-continuous",
  },
  {
    id: "ot-pp-cont-2",
    he: "כמה זמן אתה עובד על הפרויקט הזה? מאז ינואר.",
    en: "How long have you been working on this project? Since January.",
    topic: "g-present-perfect-continuous",
  },
  {
    id: "ot-pp-cont-3",
    he: "היא מדברת בטלפון כבר שעתיים, עם מי היא מדברת?",
    en: "She's been talking on the phone for two hours; who's she talking to?",
    alt: ["She's been on the phone for two hours. Who is she talking to?"],
    topic: "g-present-perfect-continuous",
  },
  {
    id: "ot-pp-cont-4",
    he: "יורד גשם מאז הבוקר בלי הפסקה, והכביש כבר מוצף.",
    en: "It's been raining nonstop since this morning, and the road's already flooded.",
    alt: ["It's been raining since morning without a break, and the road is already flooded."],
    topic: "g-present-perfect-continuous",
  },
  {
    id: "ot-pp-cont-5",
    he: "הם מנסים למכור את הבית כבר חצי שנה בלי הצלחה.",
    en: "They've been trying to sell the house for six months without any luck.",
    alt: ["They've been trying to sell the house for half a year with no success."],
    topic: "g-present-perfect-continuous",
  },
  {
    id: "ot-pp-cont-6",
    he: "אתה נראה עייף, מה עשית? רצתי, בגלל זה אני מזיע.",
    en: "You look tired, what have you been doing? I've been running, that's why I'm sweating.",
    alt: ["You look tired. What have you been up to? I've been running, that's why I'm all sweaty."],
    topic: "g-present-perfect-continuous",
  },

  // ---------- g-past-perfect ----------
  {
    id: "ot-past-perfect-1",
    he: "כשהגענו לתחנה עם כל המזוודות, הרכבת כבר יצאה.",
    en: "When we got to the station with all the suitcases, the train had already left.",
    alt: ["By the time we got to the station with all our luggage, the train had left."],
    topic: "g-past-perfect",
  },
  {
    id: "ot-past-perfect-2",
    he: "לא זיהיתי אותו כי לא ראיתי אותו עשר שנים.",
    en: "I didn't recognize him because I hadn't seen him in ten years.",
    alt: ["I didn't recognize him because I hadn't seen him for ten years."],
    topic: "g-past-perfect",
  },
  {
    id: "ot-past-perfect-3",
    he: "כשחזרתי הביתה, ראיתי שמישהו פרץ לדירה.",
    en: "When I got home, I saw that someone had broken into the apartment.",
    alt: ["When I came back home, I saw somebody had broken into the apartment."],
    topic: "g-past-perfect",
  },
  {
    id: "ot-past-perfect-4",
    he: "עד גיל שלושים הוא כבר ביקר בארבעים מדינות.",
    en: "By the age of thirty, he had already visited forty countries.",
    alt: ["By thirty, he'd already been to forty countries."],
    topic: "g-past-perfect",
  },
  {
    id: "ot-past-perfect-5",
    he: "הם הבינו שהם שכחו את הדרכונים רק כשהגיעו לשדה התעופה.",
    en: "They only realized they'd forgotten their passports when they got to the airport.",
    alt: ["They didn't realize they had forgotten their passports until they got to the airport."],
    topic: "g-past-perfect",
  },
  {
    id: "ot-past-perfect-6",
    he: "אחרי שסיימנו לאכול, יצאנו לטייל בעיר העתיקה.",
    en: "After we'd finished eating, we went for a walk in the Old City.",
    alt: ["After we finished eating, we went out for a walk in the Old City."],
    topic: "g-past-perfect",
  },

  // ---------- g-future-forms ----------
  {
    id: "ot-future-1",
    he: "אל תדאג, אני אתקשר אליך מחר בבוקר, בסדר?",
    en: "Don't worry, I'll call you tomorrow morning, okay?",
    alt: ["Don't worry, I'll give you a call tomorrow morning, all right?"],
    topic: "g-future-forms",
  },
  {
    id: "ot-future-2",
    he: "תראה את העננים השחורים האלה, תכף ירד גשם.",
    en: "Look at those black clouds, it's going to rain any minute.",
    alt: ["Look at those dark clouds. It's about to rain."],
    topic: "g-future-forms",
  },
  {
    id: "ot-future-3",
    he: "אנחנו טסים לרומא בקיץ, כבר קנינו את הכרטיסים.",
    en: "We're flying to Rome this summer; we've already bought the tickets.",
    alt: ["We're going to Rome in the summer. We already bought the tickets."],
    topic: "g-future-forms",
  },
  {
    id: "ot-future-4",
    he: "הפגישה מתחילה מחר בתשע בדיוק, אז אל תאחר.",
    en: "The meeting starts at nine sharp tomorrow, so don't be late.",
    alt: ["The meeting starts tomorrow at exactly nine, so don't be late."],
    topic: "g-future-forms",
  },
  {
    id: "ot-future-5",
    he: "מה אתה עושה בסוף השבוע? עוד לא החלטתי, אולי אשאר בבית.",
    en: "What are you doing this weekend? I haven't decided yet, maybe I'll stay home.",
    alt: ["What are you up to this weekend? I haven't decided yet, I might just stay home."],
    topic: "g-future-forms",
  },
  {
    id: "ot-future-6",
    he: "החלטתי, אני הולך ללמוד תואר שני בשנה הבאה.",
    en: "I've decided, I'm going to do a master's degree next year.",
    alt: ["I've made up my mind: I'm going to get a master's next year."],
    topic: "g-future-forms",
  },

  // ---------- g-used-to-would ----------
  {
    id: "ot-used-to-1",
    he: "פעם עישנתי קופסה ביום, אבל הפסקתי לפני שנתיים.",
    en: "I used to smoke a pack a day, but I quit two years ago.",
    alt: ["I used to smoke a pack a day, but I stopped two years ago."],
    topic: "g-used-to-would",
  },
  {
    id: "ot-used-to-2",
    he: "כשהייתי ילד, היינו נוסעים לסבתא כל שבת בצהריים.",
    en: "When I was a kid, we would go to Grandma's every Saturday for lunch.",
    alt: ["When I was a kid, we used to go to my grandma's every Saturday at lunchtime."],
    topic: "g-used-to-would",
  },
  {
    id: "ot-used-to-3",
    he: "פעם לא אהבתי דגים, היום אני אוכל הכול.",
    en: "I didn't use to like fish; these days I eat everything.",
    alt: ["I never used to like fish. Now I eat everything."],
    topic: "g-used-to-would",
  },
  {
    id: "ot-used-to-4",
    he: "פה הייתה פעם חנות ספרים, עכשיו זה בית קפה.",
    en: "There used to be a bookstore here; now it's a coffee shop.",
    alt: ["This used to be a bookstore. Now it's a café."],
    topic: "g-used-to-would",
  },
  {
    id: "ot-used-to-5",
    he: "הוא היה מתקשר אליי כל ערב, ואז פתאום הפסיק.",
    en: "He used to call me every evening, and then suddenly he stopped.",
    alt: ["He would call me every night, and then all of a sudden he stopped."],
    topic: "g-used-to-would",
  },
  {
    id: "ot-used-to-6",
    he: "בתור סטודנט הייתי לומד כל הלילה לפני מבחן.",
    en: "As a student, I would study all night before an exam.",
    alt: ["When I was a student, I used to study all night before a test."],
    topic: "g-used-to-would",
  },

  // ---------- g-future-time-clauses ----------
  {
    id: "ot-future-time-1",
    he: "כשאני אגיע הביתה הערב, אני אתקשר אליך.",
    en: "When I get home tonight, I'll call you.",
    alt: ["I'll call you when I get home this evening."],
    topic: "g-future-time-clauses",
  },
  {
    id: "ot-future-time-2",
    he: "אל תמהר, אני אחכה לך פה עד שתסיים.",
    en: "Take your time, I'll wait for you here until you're done.",
    alt: ["No rush, I'll wait here until you finish."],
    topic: "g-future-time-clauses",
  },
  {
    id: "ot-future-time-3",
    he: "אני אשלח לך את הקובץ לפני שאני יוצא מהמשרד.",
    en: "I'll send you the file before I leave the office.",
    alt: ["I'll send the file over before I head out of the office."],
    topic: "g-future-time-clauses",
  },
  {
    id: "ot-future-time-4",
    he: "ברגע שהם ינחתו בניו יורק, הם יודיעו לנו.",
    en: "As soon as they land in New York, they'll let us know.",
    alt: ["The moment they land in New York, they'll let us know."],
    topic: "g-future-time-clauses",
  },
  {
    id: "ot-future-time-5",
    he: "אחרי שנסיים לאכול, נלך לראות סרט בקניון, בסדר?",
    en: "After we finish eating, we'll go see a movie at the mall, okay?",
    alt: ["After we've finished eating, we'll go watch a movie at the mall, all right?"],
    topic: "g-future-time-clauses",
  },
  {
    id: "ot-future-time-6",
    he: "אני לא אחליט כלום עד שאשמע מה יש להם להגיד.",
    en: "I won't decide anything until I hear what they have to say.",
    alt: ["I'm not going to decide anything until I've heard what they have to say."],
    topic: "g-future-time-clauses",
  },

  // ---------- g-state-verbs ----------
  {
    id: "ot-state-verbs-1",
    he: "אני לא מבין מה אתה אומר, תדבר לאט יותר.",
    en: "I don't understand what you're saying, speak more slowly.",
    alt: ["I don't understand what you're saying. Talk slower."],
    topic: "g-state-verbs",
  },
  {
    id: "ot-state-verbs-2",
    he: "אתה מכיר את הבחור הזה? הוא נראה לי מוכר.",
    en: "Do you know that guy? He looks familiar to me.",
    alt: ["Do you know this guy? He looks familiar."],
    topic: "g-state-verbs",
  },
  {
    id: "ot-state-verbs-3",
    he: "אני לא מאמין שהיא אמרה את זה, זה נשמע נורא.",
    en: "I can't believe she said that; it sounds awful.",
    alt: ["I don't believe she said that. That sounds terrible."],
    topic: "g-state-verbs",
  },
  {
    id: "ot-state-verbs-4",
    he: "עכשיו אני סוף סוף מבין למה היא לא רצתה לבוא.",
    en: "Now I finally understand why she didn't want to come.",
    alt: ["Now I finally get why she didn't want to come."],
    topic: "g-state-verbs",
  },
  {
    id: "ot-state-verbs-5",
    he: "הדירה הזאת שייכת להורים שלי, אני רק גר פה.",
    en: "This apartment belongs to my parents; I just live here.",
    alt: ["This apartment is my parents'. I'm just living here."],
    topic: "g-state-verbs",
  },
  {
    id: "ot-state-verbs-6",
    he: "אני חושב על להחליף עבודה, מה אתה חושב על זה?",
    en: "I'm thinking about changing jobs, what do you think about it?",
    alt: ["I'm thinking of changing jobs. What do you think?"],
    topic: "g-state-verbs",
  },

  // ---------- g-modals-ability ----------
  {
    id: "ot-ability-1",
    he: "אני יודע לשחות, אבל האמת שלא טוב במיוחד.",
    en: "I can swim, but honestly, not very well.",
    alt: ["I know how to swim, but to be honest, not that well."],
    topic: "g-modals-ability",
  },
  {
    id: "ot-ability-2",
    he: "אתה יכול לעזור לי להרים את זה? זה כבד.",
    en: "Can you help me lift this? It's heavy.",
    alt: ["Could you help me lift this? It's heavy."],
    topic: "g-modals-ability",
  },
  {
    id: "ot-ability-3",
    he: "כשהייתי רק בן חמש, כבר ידעתי לקרוא לבד.",
    en: "When I was only five, I could already read by myself.",
    alt: ["When I was just five, I was already able to read on my own."],
    topic: "g-modals-ability",
  },
  {
    id: "ot-ability-4",
    he: "היא לא יכלה לבוא אתמול כי לא היה לה עם מי להשאיר את הילדים.",
    en: "She couldn't come yesterday because she didn't have anyone to leave the kids with.",
    alt: ["She couldn't come yesterday because she had no one to leave the kids with."],
    topic: "g-modals-ability",
  },
  {
    id: "ot-ability-5",
    he: "לא הצלחתי לפתוח את הדלת, אז קראתי לשכן.",
    en: "I couldn't open the door, so I called the neighbor.",
    alt: ["I wasn't able to open the door, so I called the neighbor."],
    topic: "g-modals-ability",
  },
  {
    id: "ot-ability-6",
    he: "אחרי הניתוח הוא הצליח ללכת שוב בלי מקל.",
    en: "After the surgery, he was able to walk again without a cane.",
    alt: ["After the operation, he managed to walk again without a cane."],
    topic: "g-modals-ability",
  },

  // ---------- g-modals-obligation ----------
  {
    id: "ot-obligation-1",
    he: "אני חייב ללכת, יש לי פגישה בעוד עשר דקות.",
    en: "I have to go, I've got a meeting in ten minutes.",
    alt: ["I've got to go, I have a meeting in ten minutes."],
    topic: "g-modals-obligation",
  },
  {
    id: "ot-obligation-2",
    he: "אתה לא חייב לבוא אם אתה עייף, באמת.",
    en: "You don't have to come if you're tired, really.",
    alt: ["You don't need to come if you're tired, seriously."],
    topic: "g-modals-obligation",
  },
  {
    id: "ot-obligation-3",
    he: "אסור לעשן פה בפנים, אתה יודע שזה בית חולים.",
    en: "You can't smoke in here, you know it's a hospital.",
    alt: ["You're not allowed to smoke in here. You know this is a hospital.", "You mustn't smoke in here, you know it's a hospital."],
    topic: "g-modals-obligation",
  },
  {
    id: "ot-obligation-4",
    he: "הייתי צריך לקום בחמש בבוקר כדי להספיק לטיסה.",
    en: "I had to get up at five in the morning to make my flight.",
    alt: ["I had to get up at five a.m. to catch the flight."],
    topic: "g-modals-obligation",
  },
  {
    id: "ot-obligation-5",
    he: "לא היינו צריכים לשלם על החניה, זה היה חינם.",
    en: "We didn't have to pay for parking; it was free.",
    alt: ["We didn't need to pay for the parking, it was free."],
    topic: "g-modals-obligation",
  },
  {
    id: "ot-obligation-6",
    he: "המורה אמרה שאנחנו חייבים להגיש את העבודה עד יום שישי.",
    en: "The teacher said we have to hand in the assignment by Friday.",
    alt: ["The teacher said we need to submit the paper by Friday."],
    topic: "g-modals-obligation",
  },

  // ---------- g-modals-advice ----------
  {
    id: "ot-advice-1",
    he: "אתה נראה ממש חולה, כדאי לך ללכת לרופא.",
    en: "You look really sick, you should see a doctor.",
    alt: ["You look really sick. You should go to the doctor."],
    topic: "g-modals-advice",
  },
  {
    id: "ot-advice-2",
    he: "לא כדאי לך לאכול כל כך הרבה סוכר.",
    en: "You shouldn't eat so much sugar.",
    alt: ["You shouldn't be eating that much sugar."],
    topic: "g-modals-advice",
  },
  {
    id: "ot-advice-3",
    he: "מה לדעתך אני צריך לעשות? להתקשר אליה או לחכות?",
    en: "What do you think I should do? Call her or wait?",
    alt: ["What should I do, in your opinion? Call her or wait?"],
    topic: "g-modals-advice",
  },
  {
    id: "ot-advice-4",
    he: "במקומך הייתי מדבר איתו ישירות, לא דרך המנהל.",
    en: "If I were you, I'd talk to him directly, not through the manager.",
    alt: ["If I were you, I would speak to him directly, not through the boss."],
    topic: "g-modals-advice",
  },
  {
    id: "ot-advice-5",
    he: "היית צריך להגיד לי שאתה מאחר, דאגתי לך.",
    en: "You should've told me you were running late, I was worried about you.",
    alt: ["You should have told me you'd be late. I was worried about you."],
    topic: "g-modals-advice",
  },
  {
    id: "ot-advice-6",
    he: "עדיף שתקנה כרטיסים מראש, בסוף השבוע תמיד מלא.",
    en: "You'd better buy tickets in advance; it's always packed on weekends.",
    alt: ["You'd better book tickets ahead of time, it's always full on the weekend."],
    topic: "g-modals-advice",
  },

  // ---------- g-modals-deduction ----------
  {
    id: "ot-deduction-1",
    he: "האור בדירה שלו דלוק, אז הוא בטח בבית.",
    en: "The light in his apartment is on, so he must be home.",
    alt: ["His light's on, so he must be at home."],
    topic: "g-modals-deduction",
  },
  {
    id: "ot-deduction-2",
    he: "זה לא יכול להיות דני, הוא בחו\"ל עכשיו.",
    en: "It can't be Danny, he's abroad right now.",
    alt: ["That can't be Danny. He's out of the country right now."],
    topic: "g-modals-deduction",
  },
  {
    id: "ot-deduction-3",
    he: "היא לא ענתה לטלפון, אולי היא עוד ישנה.",
    en: "She didn't answer the phone; she might still be asleep.",
    alt: ["She didn't pick up. Maybe she's still sleeping.", "She didn't answer the phone, she may still be sleeping."],
    topic: "g-modals-deduction",
  },
  {
    id: "ot-deduction-4",
    he: "הם בטח עשירים, תראה איזה בית יש להם.",
    en: "They must be rich, look at the house they've got.",
    alt: ["They must be rich. Look at what a house they have."],
    topic: "g-modals-deduction",
  },
  {
    id: "ot-deduction-5",
    he: "אתה בטח צוחק, אין מצב שהוא קנה את זה.",
    en: "You must be joking, there's no way he bought that.",
    alt: ["You've got to be kidding. There's no way he bought that."],
    topic: "g-modals-deduction",
  },
  {
    id: "ot-deduction-6",
    he: "הם בטח לא בבית, המכונית לא בחניה.",
    en: "They can't be home, the car isn't in the driveway.",
    alt: ["They must not be home. The car's not in the parking spot."],
    topic: "g-modals-deduction",
  },

  // ---------- g-modals-past ----------
  {
    id: "ot-modals-past-1",
    he: "לא הייתי צריך להגיד לה את זה, היא נעלבה.",
    en: "I shouldn't have told her that; she got offended.",
    alt: ["I shouldn't have said that to her. She was hurt."],
    topic: "g-modals-past",
  },
  {
    id: "ot-modals-past-2",
    he: "יכולת לפחות להתקשר! חיכינו לך שעתיים במסעדה.",
    en: "You could've at least called! We waited two hours for you at the restaurant.",
    alt: ["You could have at least called! We waited for you for two hours at the restaurant."],
    topic: "g-modals-past",
  },
  {
    id: "ot-modals-past-3",
    he: "הוא בטח פספס את האוטובוס, בגלל זה הוא מאחר.",
    en: "He must've missed the bus; that's why he's late.",
    alt: ["He must have missed the bus. That's why he's running late."],
    topic: "g-modals-past",
  },
  {
    id: "ot-modals-past-4",
    he: "לא הייתי חייב לבוא היום, אבל רציתי לעזור.",
    en: "I didn't have to come today, but I wanted to help.",
    alt: ["I didn't need to come today, but I wanted to help out."],
    topic: "g-modals-past",
  },
  {
    id: "ot-modals-past-5",
    he: "היא לא יכלה לראות אותנו, היא לא הייתה שם בכלל.",
    en: "She can't have seen us, she wasn't even there.",
    alt: ["She couldn't have seen us. She wasn't there at all."],
    topic: "g-modals-past",
  },
  {
    id: "ot-modals-past-6",
    he: "הייתם צריכים לצאת מוקדם יותר, אמרתי לכם שיהיו פקקים.",
    en: "You should've left earlier; I told you there'd be traffic.",
    alt: ["You guys should have left earlier. I told you there was going to be traffic."],
    topic: "g-modals-past",
  },

  // ---------- g-conditional-0-1 ----------
  {
    id: "ot-cond-0-1-1",
    he: "אם יורד גשם, אני בדרך כלל נוסע לעבודה באוטובוס.",
    en: "If it rains, I usually take the bus to work.",
    alt: ["When it rains, I usually take the bus to work."],
    topic: "g-conditional-0-1",
  },
  {
    id: "ot-cond-0-1-2",
    he: "אם אין לי זמן לבשל, אני מזמין אוכל.",
    en: "If I don't have time to cook, I order food.",
    alt: ["When I don't have time to cook, I order in."],
    topic: "g-conditional-0-1",
  },
  {
    id: "ot-cond-0-1-3",
    he: "אם תגמור מוקדם, תתקשר אליי ונלך לאכול משהו.",
    en: "If you finish early, call me and we'll go grab something to eat.",
    alt: ["If you're done early, give me a call and we'll go get something to eat."],
    topic: "g-conditional-0-1",
  },
  {
    id: "ot-cond-0-1-4",
    he: "אם לא תמהר, אתה תפספס את הרכבת האחרונה.",
    en: "If you don't hurry, you'll miss the last train.",
    alt: ["If you don't hurry up, you're going to miss the last train."],
    topic: "g-conditional-0-1",
  },
  {
    id: "ot-cond-0-1-5",
    he: "מה תעשה אם לא תקבל את העבודה?",
    en: "What will you do if you don't get the job?",
    alt: ["What are you going to do if you don't get the job?"],
    topic: "g-conditional-0-1",
  },
  {
    id: "ot-cond-0-1-6",
    he: "היא לא תבוא אם לא תזמין אותה באופן אישי.",
    en: "She won't come unless you invite her personally.",
    alt: ["She won't come if you don't invite her personally."],
    topic: "g-conditional-0-1",
  },

  // ---------- g-conditional-2 ----------
  {
    id: "ot-cond-2-1",
    he: "אם היה לי יותר זמן, הייתי לומד ספרדית.",
    en: "If I had more time, I'd learn Spanish.",
    alt: ["If I had more time, I would study Spanish."],
    topic: "g-conditional-2",
  },
  {
    id: "ot-cond-2-2",
    he: "מה היית עושה אם היית זוכה במיליון דולר בלוטו?",
    en: "What would you do if you won a million dollars in the lottery?",
    topic: "g-conditional-2",
  },
  {
    id: "ot-cond-2-3",
    he: "אם הייתי במקומך, לא הייתי חותם על החוזה הזה.",
    en: "If I were you, I wouldn't sign that contract.",
    alt: ["If I were in your shoes, I wouldn't sign this contract."],
    topic: "g-conditional-2",
  },
  {
    id: "ot-cond-2-4",
    he: "היא הייתה עוזרת לך בשמחה אם רק היית מבקש.",
    en: "She'd gladly help you if you just asked.",
    alt: ["She would be happy to help you if you only asked."],
    topic: "g-conditional-2",
  },
  {
    id: "ot-cond-2-5",
    he: "לו הייתי גר קרוב לים, הייתי הולך לחוף כל יום.",
    en: "If I lived near the sea, I'd go to the beach every day.",
    alt: ["If I lived close to the beach, I would go every day."],
    topic: "g-conditional-2",
  },
  {
    id: "ot-cond-2-6",
    he: "לא הייתי מתלונן אם המשכורת הייתה קצת יותר גבוהה.",
    en: "I wouldn't complain if the salary were a little higher.",
    alt: ["I wouldn't complain if the pay was a bit higher."],
    topic: "g-conditional-2",
  },

  // ---------- g-conditional-3-mixed ----------
  {
    id: "ot-cond-3-1",
    he: "אם היית אומר לי אתמול, הייתי עוזר לך בשמחה.",
    en: "If you'd told me yesterday, I would've gladly helped you.",
    alt: ["If you had told me yesterday, I would have been happy to help."],
    topic: "g-conditional-3-mixed",
  },
  {
    id: "ot-cond-3-2",
    he: "לא היינו מאחרים לטיסה אם היינו יוצאים מוקדם יותר.",
    en: "We wouldn't have been late for the flight if we'd left earlier.",
    alt: ["We wouldn't have been late for the flight if we had left earlier."],
    topic: "g-conditional-3-mixed",
  },
  {
    id: "ot-cond-3-3",
    he: "אם היא הייתה לומדת יותר, היא הייתה עוברת את המבחן.",
    en: "If she'd studied harder, she would've passed the exam.",
    alt: ["If she had studied more, she would have passed the test."],
    topic: "g-conditional-3-mixed",
  },
  {
    id: "ot-cond-3-4",
    he: "הוא לא היה מפוטר אם היה מקשיב לעצות שלי.",
    en: "He wouldn't have been fired if he'd listened to my advice.",
    alt: ["He wouldn't have gotten fired if he had listened to my advice."],
    topic: "g-conditional-3-mixed",
  },
  {
    id: "ot-cond-3-5",
    he: "אם לא הייתי פוגש אותה במסיבה ההיא, לא היינו נשואים היום.",
    en: "If I hadn't met her at that party, we wouldn't be married today.",
    alt: ["If I had never met her at that party, we wouldn't be married now."],
    topic: "g-conditional-3-mixed",
  },
  {
    id: "ot-cond-3-6",
    he: "אם הייתי יודע לנהוג, הייתי לוקח אותך אתמול לשדה התעופה.",
    en: "If I knew how to drive, I would've taken you to the airport yesterday.",
    alt: ["If I could drive, I would have driven you to the airport yesterday."],
    topic: "g-conditional-3-mixed",
  },

  // ---------- g-wish-if-only ----------
  {
    id: "ot-wish-1",
    he: "הלוואי שהיה לי יותר זמן פנוי בשביל הילדים.",
    en: "I wish I had more free time for the kids.",
    alt: ["I wish I had more time off for the kids."],
    topic: "g-wish-if-only",
  },
  {
    id: "ot-wish-2",
    he: "חבל שאתה לא גר קרוב יותר אלינו.",
    en: "I wish you lived closer to us.",
    alt: ["It's a shame you don't live closer to us."],
    topic: "g-wish-if-only",
  },
  {
    id: "ot-wish-3",
    he: "הלוואי שהייתי יודע לנגן על פסנתר כמו אחותי.",
    en: "I wish I could play the piano like my sister.",
    alt: ["I wish I knew how to play the piano like my sister does."],
    topic: "g-wish-if-only",
  },
  {
    id: "ot-wish-4",
    he: "הלוואי שלא הייתי מוכר את המכונית ההיא, היא הייתה מעולה.",
    en: "I wish I hadn't sold that car, it was great.",
    alt: ["I wish I hadn't sold that car. It was an excellent car."],
    topic: "g-wish-if-only",
  },
  {
    id: "ot-wish-5",
    he: "הלוואי שתפסיק כבר לעשן, זה מדאיג אותי.",
    en: "I wish you'd stop smoking already, it worries me.",
    alt: ["I wish you would quit smoking already. It worries me."],
    topic: "g-wish-if-only",
  },
  {
    id: "ot-wish-6",
    he: "אם רק הייתי מקשיב לאמא שלי, לא הייתי מסתבך ככה.",
    en: "If only I'd listened to my mom, I wouldn't have gotten into this mess.",
    alt: ["If only I had listened to my mother, I wouldn't be in this mess."],
    topic: "g-wish-if-only",
  },

  // ---------- g-passive-present-past ----------
  {
    id: "ot-passive-1",
    he: "הבית הישן הזה נבנה לפני יותר ממאה שנה.",
    en: "This old house was built more than a hundred years ago.",
    alt: ["This old house was built over a hundred years ago."],
    topic: "g-passive-present-past",
  },
  {
    id: "ot-passive-2",
    he: "הדואר מחולק פה כל בוקר בערך בתשע.",
    en: "The mail is delivered here every morning around nine.",
    alt: ["The mail gets delivered here every morning at about nine."],
    topic: "g-passive-present-past",
  },
  {
    id: "ot-passive-3",
    he: "גנבו לי את האופניים אתמול ליד תחנת הרכבת.",
    en: "My bike was stolen near the train station yesterday.",
    alt: ["Someone stole my bike near the train station yesterday.", "My bike got stolen yesterday by the train station."],
    topic: "g-passive-present-past",
  },
  {
    id: "ot-passive-4",
    he: "מדברים אנגלית בהרבה מדינות, לא רק באמריקה ובאנגליה.",
    en: "English is spoken in many countries, not just in America and England.",
    alt: ["English is spoken in a lot of countries, not only in the US and the UK."],
    topic: "g-passive-present-past",
  },
  {
    id: "ot-passive-5",
    he: "הזמינו אותנו לחתונה, אבל לא יכולנו להגיע.",
    en: "We were invited to the wedding, but we couldn't make it.",
    alt: ["We got invited to the wedding, but we couldn't come."],
    topic: "g-passive-present-past",
  },
  {
    id: "ot-passive-6",
    he: "הפגישה של הבוקר בוטלה ברגע האחרון בגלל מזג האוויר.",
    en: "This morning's meeting was canceled at the last minute because of the weather.",
    alt: ["The morning meeting was canceled at the last minute due to the weather."],
    topic: "g-passive-present-past",
  },

  // ---------- g-passive-other ----------
  {
    id: "ot-passive-other-1",
    he: "הכביש ייסגר מחר לכמה שעות בגלל המרתון.",
    en: "The road will be closed tomorrow for a few hours because of the marathon.",
    alt: ["The road is going to be closed for a few hours tomorrow due to the marathon."],
    topic: "g-passive-other",
  },
  {
    id: "ot-passive-other-2",
    he: "הדירה שלנו משופצת עכשיו, אז אנחנו אצל ההורים.",
    en: "Our apartment is being renovated right now, so we're staying with my parents.",
    alt: ["Our apartment is being remodeled at the moment, so we're at my parents' place."],
    topic: "g-passive-other",
  },
  {
    id: "ot-passive-other-3",
    he: "עוד לא תיקנו לי את המחשב, כבר שבוע.",
    en: "My computer hasn't been fixed yet; it's been a week.",
    alt: ["My computer still hasn't been repaired. It's already been a week."],
    topic: "g-passive-other",
  },
  {
    id: "ot-passive-other-4",
    he: "צריך להגיש את כל הטפסים עד סוף החודש.",
    en: "All the forms have to be submitted by the end of the month.",
    alt: ["All the forms must be handed in by the end of the month.", "You have to submit all the forms by the end of the month."],
    topic: "g-passive-other",
  },
  {
    id: "ot-passive-other-5",
    he: "כשהגענו למשרד, מסתבר שהבעיה כבר טופלה.",
    en: "When we got to the office, it turned out the problem had already been taken care of.",
    alt: ["When we arrived at the office, it turned out the problem had already been dealt with."],
    topic: "g-passive-other",
  },
  {
    id: "ot-passive-other-6",
    he: "אני לא אוהב שאומרים לי מה לעשות כל הזמן.",
    en: "I don't like being told what to do all the time.",
    alt: ["I don't like it when people tell me what to do all the time."],
    topic: "g-passive-other",
  },

  // ---------- g-reported-statements ----------
  {
    id: "ot-reported-1",
    he: "היא אמרה לי שהיא עייפה ושהיא הולכת לישון.",
    en: "She told me she was tired and was going to bed.",
    alt: ["She told me that she was tired and that she was going to sleep."],
    topic: "g-reported-statements",
  },
  {
    id: "ot-reported-2",
    he: "הוא אמר לי שהוא יתקשר אליי מחר בבוקר.",
    en: "He told me he'd call me tomorrow morning.",
    alt: ["He said he would call me tomorrow morning."],
    topic: "g-reported-statements",
  },
  {
    id: "ot-reported-3",
    he: "אמרתי לך שאני לא יכול לבוא ביום שישי.",
    en: "I told you I couldn't come on Friday.",
    alt: ["I told you I can't come on Friday."],
    topic: "g-reported-statements",
  },
  {
    id: "ot-reported-4",
    he: "הם אמרו שהם כבר ראו את הסרט הזה.",
    en: "They said they'd already seen that movie.",
    alt: ["They said they had already seen this movie."],
    topic: "g-reported-statements",
  },
  {
    id: "ot-reported-5",
    he: "המנהל הודיע לכולם שהמשרד יהיה סגור בשבוע הבא.",
    en: "The manager told everyone the office would be closed next week.",
    alt: ["The manager announced to everyone that the office would be closed the following week."],
    topic: "g-reported-statements",
  },
  {
    id: "ot-reported-6",
    he: "היא הבטיחה לי שהיא לא תספר לאף אחד על זה.",
    en: "She promised me she wouldn't tell anyone about it.",
    alt: ["She promised me that she wouldn't tell anybody about this."],
    topic: "g-reported-statements",
  },

  // ---------- g-reported-questions-requests ----------
  {
    id: "ot-reported-q-1",
    he: "הוא ביקש ממני בנימוס לסגור את הדלת בשקט.",
    en: "He politely asked me to close the door quietly.",
    alt: ["He asked me nicely to shut the door quietly."],
    topic: "g-reported-questions-requests",
  },
  {
    id: "ot-reported-q-2",
    he: "אמא שלי אמרה לי לא לחזור הביתה מאוחר.",
    en: "My mom told me not to come home late.",
    alt: ["My mother told me not to get home late."],
    topic: "g-reported-questions-requests",
  },
  {
    id: "ot-reported-q-3",
    he: "היא שאלה אותי איפה אני גר ובמה אני עובד.",
    en: "She asked me where I lived and what I did for a living.",
    alt: ["She asked me where I live and what I do for a living."],
    topic: "g-reported-questions-requests",
  },
  {
    id: "ot-reported-q-4",
    he: "שאלתי אותו אם הוא רוצה לבוא איתנו.",
    en: "I asked him if he wanted to come with us.",
    alt: ["I asked him whether he wanted to come along with us."],
    topic: "g-reported-questions-requests",
  },
  {
    id: "ot-reported-q-5",
    he: "הרופא אמר לו להפסיק לעשן ולעשות יותר ספורט.",
    en: "The doctor told him to quit smoking and exercise more.",
    alt: ["The doctor told him to stop smoking and to get more exercise."],
    topic: "g-reported-questions-requests",
  },
  {
    id: "ot-reported-q-6",
    he: "הם שאלו מתי הטיסה יוצאת ואיפה עושים צ'ק-אין.",
    en: "They asked when the flight was leaving and where to check in.",
    alt: ["They asked what time the flight left and where they could check in."],
    topic: "g-reported-questions-requests",
  },

  // ---------- g-question-formation ----------
  {
    id: "ot-questions-1",
    he: "בן כמה אתה, אגב? אני בן שלושים ושתיים.",
    en: "How old are you, by the way? I'm thirty-two.",
    topic: "g-question-formation",
  },
  {
    id: "ot-questions-2",
    he: "איפה גרים ההורים שלך היום? הם עדיין גרים ברעננה.",
    en: "Where do your parents live these days? They still live in Ra'anana.",
    alt: ["Where do your parents live now? They're still in Ra'anana."],
    topic: "g-question-formation",
  },
  {
    id: "ot-questions-3",
    he: "מה היא אמרה על התוכנית החדשה שלנו? היא אהבה?",
    en: "What did she say about our new plan? Did she like it?",
    topic: "g-question-formation",
  },
  {
    id: "ot-questions-4",
    he: "כמה זמן לוקח להגיע מפה לירושלים ברכבת?",
    en: "How long does it take to get from here to Jerusalem by train?",
    alt: ["How long does the train take from here to Jerusalem?"],
    topic: "g-question-formation",
  },
  {
    id: "ot-questions-5",
    he: "למה לא אמרת לי שאתה לא מרגיש טוב?",
    en: "Why didn't you tell me you weren't feeling well?",
    alt: ["Why didn't you tell me you didn't feel well?"],
    topic: "g-question-formation",
  },
  {
    id: "ot-questions-6",
    he: "עם מי דיברת בטלפון כל כך הרבה זמן?",
    en: "Who were you talking to on the phone for so long?",
    alt: ["Who were you on the phone with for so long?"],
    topic: "g-question-formation",
  },

  // ---------- g-indirect-questions ----------
  {
    id: "ot-indirect-q-1",
    he: "סליחה, אתה במקרה יודע איפה תחנת האוטובוס הקרובה?",
    en: "Excuse me, do you happen to know where the nearest bus stop is?",
    alt: ["Excuse me, do you know where the closest bus stop is?"],
    topic: "g-indirect-questions",
  },
  {
    id: "ot-indirect-q-2",
    he: "אתה יכול להגיד לי מתי החנות נפתחת מחר?",
    en: "Can you tell me what time the store opens tomorrow?",
    alt: ["Could you tell me when the store opens tomorrow?"],
    topic: "g-indirect-questions",
  },
  {
    id: "ot-indirect-q-3",
    he: "אני לא יודע למה היא לא ענתה לי.",
    en: "I don't know why she didn't answer me.",
    alt: ["I don't know why she didn't get back to me."],
    topic: "g-indirect-questions",
  },
  {
    id: "ot-indirect-q-4",
    he: "אין לי מושג כמה זה עולה, תשאל את המוכר.",
    en: "I have no idea how much it costs, ask the salesperson.",
    alt: ["I have no idea how much this costs. Ask the guy at the counter."],
    topic: "g-indirect-questions",
  },
  {
    id: "ot-indirect-q-5",
    he: "מעניין אם הם יגיעו בזמן עם הפקקים האלה.",
    en: "I wonder if they'll make it on time with this traffic.",
    alt: ["I wonder whether they'll arrive on time with all this traffic."],
    topic: "g-indirect-questions",
  },
  {
    id: "ot-indirect-q-6",
    he: "אתה יכול להסביר לי איך המכונה הזאת עובדת?",
    en: "Can you explain to me how this machine works?",
    alt: ["Could you explain how this machine works?"],
    topic: "g-indirect-questions",
  },

  // ---------- g-question-tags ----------
  {
    id: "ot-tags-1",
    he: "אתה יוסי, נכון? נפגשנו בחתונה של דנה.",
    en: "You're Yossi, aren't you? We met at Dana's wedding.",
    alt: ["You're Yossi, right? We met at Dana's wedding."],
    topic: "g-question-tags",
  },
  {
    id: "ot-tags-2",
    he: "היא לא באה היום לפגישה, נכון?",
    en: "She isn't coming to the meeting today, is she?",
    alt: ["She's not coming to the meeting today, is she?"],
    topic: "g-question-tags",
  },
  {
    id: "ot-tags-3",
    he: "אתה לא אוכל בשר, נכון? אז הכנתי לך משהו אחר.",
    en: "You don't eat meat, do you? So I made you something else.",
    alt: ["You don't eat meat, right? So I made something else for you."],
    topic: "g-question-tags",
  },
  {
    id: "ot-tags-4",
    he: "אתה תעזור לי עם המעבר דירה בשבת, נכון?",
    en: "You'll help me with the move on Saturday, won't you?",
    alt: ["You're going to help me move on Saturday, aren't you?"],
    topic: "g-question-tags",
  },
  {
    id: "ot-tags-5",
    he: "כבר סגרת את החלונות, נכון? הולך לרדת גשם.",
    en: "You've already closed the windows, haven't you? It's going to rain.",
    alt: ["You closed the windows already, didn't you? It's going to rain."],
    topic: "g-question-tags",
  },
  {
    id: "ot-tags-6",
    he: "לא ניסית להתקשר אליי אתמול, נכון? לא ראיתי שיחה.",
    en: "You didn't try to call me yesterday, did you? I didn't see a call.",
    alt: ["You didn't try calling me yesterday, did you? I didn't see a missed call."],
    topic: "g-question-tags",
  },

  // ---------- g-subject-object-questions ----------
  {
    id: "ot-subj-obj-q-1",
    he: "מי התקשר אליך עכשיו? זה נשמע דחוף.",
    en: "Who just called you? It sounded urgent.",
    alt: ["Who called you just now? That sounded urgent."],
    topic: "g-subject-object-questions",
  },
  {
    id: "ot-subj-obj-q-2",
    he: "למי התקשרת עכשיו? התקשרתי לאחותי בשביל לבדוק משהו.",
    en: "Who did you just call? I called my sister to check something.",
    alt: ["Who did you call just now? I called my sister to check on something."],
    topic: "g-subject-object-questions",
  },
  {
    id: "ot-subj-obj-q-3",
    he: "מה קרה פה? מי שבר את החלון במטבח?",
    en: "What happened here? Who broke the kitchen window?",
    alt: ["What happened here? Who broke the window in the kitchen?"],
    topic: "g-subject-object-questions",
  },
  {
    id: "ot-subj-obj-q-4",
    he: "מה שברת? שברתי את הכוס האהובה על אמא.",
    en: "What did you break? I broke Mom's favorite glass.",
    alt: ["What did you break? I broke Mom's favorite cup."],
    topic: "g-subject-object-questions",
  },
  {
    id: "ot-subj-obj-q-5",
    he: "מי גר בדירה מעליכם? הם עושים המון רעש.",
    en: "Who lives in the apartment above you? They make so much noise.",
    alt: ["Who lives upstairs from you? They're so noisy."],
    topic: "g-subject-object-questions",
  },
  {
    id: "ot-subj-obj-q-6",
    he: "כמה אנשים באו למסיבה? וכמה אנשים אתה הזמנת?",
    en: "How many people came to the party? And how many people did you invite?",
    alt: ["How many people showed up to the party? And how many did you invite?"],
    topic: "g-subject-object-questions",
  },
];
