import type { ChunkItem } from "@/lib/types";

export const CHUNKS: ChunkItem[] = [
  // ---------- opinion (14) ----------
  {
    id: "c-in-my-opinion",
    text: "in my opinion,",
    he: "לדעתי,",
    useHe: "פתיח ניטרלי להבעת דעה. מתאים לכל מצב, גם רשמי. אל תשתמשו בו בכל משפט.",
    example: "In my opinion, the new office is much better than the old one.",
    group: "opinion",
  },
  {
    id: "c-i-think-that",
    text: "I think that",
    he: "אני חושב ש...",
    useHe: "הדרך הכי פשוטה להביע דעה. אפשר להשמיט את that בדיבור.",
    example: "I think that we should leave early to avoid the traffic.",
    group: "opinion",
  },
  {
    id: "c-to-be-honest",
    text: "to be honest,",
    he: "האמת היא ש..., בכנות,",
    useHe: "כשאומרים משהו שאולי לא נעים לשמוע, או דעה אישית מאוד. דיבורי.",
    example: "To be honest, I didn't really enjoy the movie.",
    group: "opinion",
  },
  {
    id: "c-personally-i",
    text: "personally, I",
    he: "אני אישית...",
    useHe: "מדגיש שזו דעתך הפרטית ולא עובדה. טוב כשאחרים חושבים אחרת.",
    example: "Personally, I prefer working from home two days a week.",
    group: "opinion",
  },
  {
    id: "c-if-you-ask-me",
    text: "if you ask me,",
    he: "אם אתה שואל אותי,",
    useHe: "דעה חזקה בטון חברי ולא רשמי. לא לשימוש במייל עסקי.",
    example: "If you ask me, the restaurant is way too expensive for what you get.",
    group: "opinion",
  },
  {
    id: "c-id-say",
    text: "I'd say",
    he: "הייתי אומר ש...",
    useHe: "דעה או הערכה עדינה, לא מוחלטת. מצוין להערכות: מספרים, זמן, איכות.",
    example: "I'd say the whole project will take about three months.",
    group: "opinion",
  },
  {
    id: "c-as-far-as-im-concerned",
    text: "as far as I'm concerned,",
    he: "מבחינתי,",
    useHe: "דעה אישית מוחלטת, לפעמים קצת תקיפה. 'מבחינתי - נגמר הדיון'.",
    example: "As far as I'm concerned, the meeting was a complete waste of time.",
    group: "opinion",
  },
  {
    id: "c-the-way-i-see-it",
    text: "the way I see it,",
    he: "כמו שאני רואה את זה,",
    useHe: "מציג את הפרשנות שלך למצב, בדרך כלל לפני הסבר קצר. דיבורי.",
    example: "The way I see it, we have two options: wait or start again.",
    group: "opinion",
  },
  {
    id: "c-im-not-sure-but",
    text: "I'm not sure, but",
    he: "אני לא בטוח, אבל...",
    useHe: "מרכך דעה או ניחוש. שימושי מאוד כשאין לך את כל המידע.",
    example: "I'm not sure, but I think the store closes at nine.",
    group: "opinion",
  },
  {
    id: "c-it-seems-to-me-that",
    text: "it seems to me that",
    he: "נראה לי ש...",
    useHe: "דעה זהירה ומנומסת, קצת יותר רשמית מ-I think. טוב בפגישות.",
    example: "It seems to me that nobody actually read the report.",
    group: "opinion",
  },
  {
    id: "c-mixed-feelings",
    text: "I have mixed feelings about",
    he: "יש לי רגשות מעורבים לגבי",
    useHe: "כשאתה גם בעד וגם נגד. אחריו בא שם עצם או פועל ב-ing.",
    example: "I have mixed feelings about moving to a bigger city.",
    group: "opinion",
  },
  {
    id: "c-big-fan-of",
    text: "I'm a big fan of",
    he: "אני מאוד אוהב את...",
    useHe: "דרך טבעית ודיבורית להגיד שאתה אוהב משהו, לא רק ספורט.",
    example: "I'm a big fan of Italian food, especially fresh pasta.",
    group: "opinion",
  },
  {
    id: "c-not-really-into",
    text: "I'm not really into",
    he: "אני לא כל כך בקטע של...",
    useHe: "דרך מנומסת ורכה להגיד שמשהו לא מעניין אותך. אחריו שם עצם או ing.",
    example: "I'm not really into video games, but my brother loves them.",
    group: "opinion",
  },
  {
    id: "c-i-cant-stand",
    text: "I can't stand",
    he: "אני לא סובל את...",
    useHe: "שנאה חזקה, דיבורי. אחריו שם עצם או פועל ב-ing (I can't stand waiting).",
    example: "I can't stand people who talk loudly on the train.",
    group: "opinion",
  },

  // ---------- hedge (10) ----------
  {
    id: "c-kind-of",
    text: "kind of",
    he: "די, במידה מסוימת, סוג של",
    useHe: "מרכך תואר או פועל: it's kind of cold. דיבורי מאוד, נשמע kinda.",
    example: "The hotel was kind of small, but it was clean and quiet.",
    group: "hedge",
  },
  {
    id: "c-sort-of",
    text: "sort of",
    he: "סוג של, די",
    useHe: "כמו kind of, מרכך ומעמעם. גם תשובה לבד: 'Are you tired?' 'Sort of.'",
    example: "I sort of understand the rules, but I need more practice.",
    group: "hedge",
  },
  {
    id: "c-more-or-less",
    text: "more or less",
    he: "פחות או יותר",
    useHe: "בערך, כמעט לגמרי. מתאים לזמן, כמות, הסכמה: 'Finished?' 'More or less.'",
    example: "The apartment is more or less ready, we just need a sofa.",
    group: "hedge",
  },
  {
    id: "c-i-guess",
    text: "I guess",
    he: "אני מניח, כנראה",
    useHe: "הסכמה או דעה לא בטוחה, קצת חסרת התלהבות. אמריקאי ודיבורי.",
    example: "I guess we could try the new place, if you really want to.",
    group: "hedge",
  },
  {
    id: "c-probably",
    text: "probably",
    he: "כנראה, סביר להניח",
    useHe: "אחרי will או לפני הפועל: I'll probably stay. הכי נפוץ מבין מילות ההסתברות.",
    example: "She'll probably call you back after lunch.",
    group: "hedge",
  },
  {
    id: "c-it-depends-on",
    text: "it depends on",
    he: "זה תלוי ב...",
    useHe: "כשאין תשובה אחת. תמיד depends ON, לא of. לבד: 'It depends.'",
    example: "It depends on the weather, but we'll probably go to the beach.",
    group: "hedge",
  },
  {
    id: "c-in-a-way",
    text: "in a way,",
    he: "במובן מסוים,",
    useHe: "כשמשהו נכון רק מזווית אחת. טוב לדעות מורכבות.",
    example: "In a way, losing that job was the best thing that happened to me.",
    group: "hedge",
  },
  {
    id: "c-to-some-extent",
    text: "to some extent,",
    he: "במידה מסוימת,",
    useHe: "הסכמה חלקית, קצת יותר רשמי מ-kind of. מצוין לדיונים.",
    example: "To some extent, I agree with you, but the price is still too high.",
    group: "hedge",
  },
  {
    id: "c-roughly",
    text: "roughly",
    he: "בערך, בקירוב",
    useHe: "לפני מספרים וכמויות: roughly ten people. חלופה טובה ל-about.",
    example: "It takes roughly forty minutes to get there by bus.",
    group: "hedge",
  },
  {
    id: "c-or-something-like-that",
    text: "or something like that",
    he: "או משהו כזה",
    useHe: "בסוף משפט כשלא זוכרים או לא רוצים לדייק. דיבורי מאוד.",
    example: "He works in marketing or something like that, I'm not sure.",
    group: "hedge",
  },

  // ---------- story (12) ----------
  {
    id: "c-the-other-day",
    text: "the other day,",
    he: "לפני כמה ימים,",
    useHe: "פתיח קלאסי לסיפור קצר מהחיים. לא צריך להגיד תאריך מדויק.",
    example: "The other day, I ran into my old teacher at the supermarket.",
    group: "story",
  },
  {
    id: "c-couple-of-years-ago",
    text: "a couple of years ago,",
    he: "לפני שנתיים-שלוש,",
    useHe: "a couple of = שניים או קצת יותר, לא מדויק. תמיד עם past simple.",
    example: "A couple of years ago, we spent a month traveling around Greece.",
    group: "story",
  },
  {
    id: "c-at-first",
    text: "at first,",
    he: "בהתחלה,",
    useHe: "פותח את השלב הראשון בסיפור, בדרך כלל לפני שינוי: at first... but then.",
    example: "At first, I didn't like the city, but now I love it.",
    group: "story",
  },
  {
    id: "c-out-of-nowhere",
    text: "then, out of nowhere,",
    he: "ואז, משום מקום,",
    useHe: "מכניס הפתעה או תפנית לסיפור. יוצר מתח ועניין.",
    example: "Then, out of nowhere, a huge dog jumped over the fence.",
    group: "story",
  },
  {
    id: "c-in-the-end",
    text: "in the end,",
    he: "בסופו של דבר,",
    useHe: "סוגר סיפור אחרי בעיות או ספקות. שימו לב: לא at the end (שזה 'בסוף של' משהו).",
    example: "In the end, we decided to take the train instead of driving.",
    group: "story",
  },
  {
    id: "c-it-turned-out-that",
    text: "it turned out that",
    he: "התברר ש...",
    useHe: "כשמגלים משהו שלא ידעתם קודם, לרוב מפתיע. חובה בסיפורים.",
    example: "It turned out that the keys were in my jacket the whole time.",
    group: "story",
  },
  {
    id: "c-the-thing-is",
    text: "the thing is,",
    he: "העניין הוא ש...",
    useHe: "מציג את הבעיה או הנקודה המרכזית, לרוב לפני תירוץ או הסבר. דיבורי מאוד.",
    example: "I'd love to come, but the thing is, I have to work on Saturday.",
    group: "story",
  },
  {
    id: "c-long-story-short",
    text: "long story short,",
    he: "בקיצור,",
    useHe: "כשמדלגים על פרטים ועוברים ישר לסוף. אפשר גם to make a long story short.",
    example: "Long story short, we missed the flight and stayed another night.",
    group: "story",
  },
  {
    id: "c-what-happened-was",
    text: "what happened was",
    he: "מה שקרה זה ש...",
    useHe: "פתיח להסבר של אירוע, במיוחד כשצריך להסביר תקלה או איחור.",
    example: "What happened was, the bus broke down halfway to the airport.",
    group: "story",
  },
  {
    id: "c-all-of-a-sudden",
    text: "and then, all of a sudden,",
    he: "ואז, פתאום,",
    useHe: "מסמן רגע הפתעה. חלופה טבעית ל-suddenly בסיפור מדובר.",
    example: "We were walking home, and then, all of a sudden, it started to pour.",
    group: "story",
  },
  {
    id: "c-by-the-time",
    text: "by the time",
    he: "עד ש..., כשכבר...",
    useHe: "מחבר שני אירועים: by the time we arrived, it had ended. לרוב עם past perfect.",
    example: "By the time we got to the party, most people had already left.",
    group: "story",
  },
  {
    id: "c-looking-back",
    text: "looking back,",
    he: "במבט לאחור,",
    useHe: "סוגר סיפור עם מסקנה או לקח. נשמע בוגר ורפלקטיבי.",
    example: "Looking back, I should have asked for help much earlier.",
    group: "story",
  },

  // ---------- agree (10) ----------
  {
    id: "c-i-totally-agree",
    text: "I totally agree.",
    he: "אני לגמרי מסכים.",
    useHe: "הסכמה מלאה וחמה. שימו לב: I agree, לא I am agree.",
    example: "I totally agree. We need more time before we decide.",
    group: "agree",
  },
  {
    id: "c-thats-a-good-point",
    text: "that's a good point.",
    he: "זו נקודה טובה.",
    useHe: "מכיר בטיעון של הצד השני, גם אם לא מסכימים לגמרי. מנומס ומקצועי.",
    example: "That's a good point. I hadn't thought about the cost.",
    group: "agree",
  },
  {
    id: "c-i-see-what-you-mean-but",
    text: "I see what you mean, but",
    he: "אני מבין למה אתה מתכוון, אבל...",
    useHe: "הדרך המנומסת הקלאסית להתנגד: קודם מכירים, אחר כך חולקים.",
    example: "I see what you mean, but I still think it's too risky.",
    group: "agree",
  },
  {
    id: "c-not-so-sure-about-that",
    text: "I'm not so sure about that.",
    he: "אני לא כל כך בטוח בזה.",
    useHe: "אי-הסכמה עדינה בלי לומר 'אתה טועה'. מאוד אנגלי ומנומס.",
    example: "I'm not so sure about that. Last year the same plan failed.",
    group: "agree",
  },
  {
    id: "c-fair-enough",
    text: "fair enough.",
    he: "בסדר, מקובל עליי.",
    useHe: "מקבל טיעון או הסבר גם אם לא בהתלהבות. דיבורי, שתי מילים שסוגרות ויכוח.",
    example: "Fair enough. If you're tired, let's meet tomorrow instead.",
    group: "agree",
  },
  {
    id: "c-exactly",
    text: "exactly!",
    he: "בדיוק!",
    useHe: "הסכמה נלהבת בזמן שהצד השני מדבר. מראה שאתם באותו ראש.",
    example: "Exactly! That's what I've been saying all week.",
    group: "agree",
  },
  {
    id: "c-couldnt-agree-more",
    text: "I couldn't agree more.",
    he: "אני מסכים לחלוטין.",
    useHe: "ההסכמה הכי חזקה. שימו לב לשלילה: couldn't ... more = אי אפשר להסכים יותר.",
    example: "I couldn't agree more. The service there is terrible.",
    group: "agree",
  },
  {
    id: "c-not-how-i-see-it",
    text: "that's not how I see it.",
    he: "אני לא רואה את זה ככה.",
    useHe: "אי-הסכמה ברורה אבל לא תוקפנית, ואז מסבירים את הזווית שלכם.",
    example: "That's not how I see it. I think he was trying to help.",
    group: "agree",
  },
  {
    id: "c-youve-got-a-point",
    text: "you've got a point there.",
    he: "יש לך נקודה.",
    useHe: "מודה שהצד השני צודק בעניין מסוים. דיבורי וידידותי.",
    example: "You've got a point there. It would be cheaper to rent.",
    group: "agree",
  },
  {
    id: "c-id-have-to-disagree",
    text: "I'd have to disagree.",
    he: "אני חייב לא להסכים.",
    useHe: "אי-הסכמה מנומסת ורשמית יחסית. I'd have to מרכך את המכה.",
    example: "I'd have to disagree. The old system was actually faster.",
    group: "agree",
  },

  // ---------- time (8) ----------
  {
    id: "c-at-the-moment",
    text: "at the moment,",
    he: "כרגע,",
    useHe: "מצב זמני עכשווי, מתאים ל-present continuous: at the moment, I'm working on...",
    example: "At the moment, I'm looking for a new apartment.",
    group: "time",
  },
  {
    id: "c-these-days",
    text: "these days,",
    he: "בימים אלה, היום,",
    useHe: "התקופה הנוכחית לעומת העבר. חלופה טבעית ל-nowadays בדיבור.",
    example: "These days, most people pay with their phone.",
    group: "time",
  },
  {
    id: "c-in-the-meantime",
    text: "in the meantime,",
    he: "בינתיים,",
    useHe: "מה עושים בזמן ההמתנה למשהו אחר. תמיד מתייחס לזמן שכבר הוזכר.",
    example: "The food will take twenty minutes. In the meantime, let's order drinks.",
    group: "time",
  },
  {
    id: "c-sooner-or-later",
    text: "sooner or later,",
    he: "במוקדם או במאוחר,",
    useHe: "משהו שבטוח יקרה, רק לא ברור מתי. לרוב עם will.",
    example: "Sooner or later, you'll have to tell her the truth.",
    group: "time",
  },
  {
    id: "c-every-now-and-then",
    text: "every now and then,",
    he: "מדי פעם,",
    useHe: "תדירות נמוכה ולא קבועה. יכול לבוא גם בסוף המשפט.",
    example: "Every now and then, I call my grandmother just to chat.",
    group: "time",
  },
  {
    id: "c-once-in-a-while",
    text: "once in a while,",
    he: "פעם ב..., לעיתים רחוקות,",
    useHe: "כמו every now and then. גם: every once in a while. מתאים לתחביבים ופינוקים.",
    example: "Once in a while, we treat ourselves to a fancy dinner.",
    group: "time",
  },
  {
    id: "c-from-time-to-time",
    text: "from time to time,",
    he: "מפעם לפעם,",
    useHe: "מדי פעם, קצת יותר ניטרלי ורשמי מ-every now and then.",
    example: "From time to time, my boss asks me to work on weekends.",
    group: "time",
  },
  {
    id: "c-in-the-long-run",
    text: "in the long run,",
    he: "בטווח הארוך,",
    useHe: "תוצאה לאורך זמן, לעומת עכשיו. מצוין לטיעונים על כסף, בריאות, לימודים.",
    example: "In the long run, buying a house is cheaper than renting.",
    group: "time",
  },

  // ---------- explain (12) ----------
  {
    id: "c-what-i-mean-is",
    text: "what I mean is",
    he: "מה שאני מתכוון זה...",
    useHe: "מתקן או מחדד משהו שלא הובן. מציל שיחות.",
    example: "No, what I mean is, we should call them before we go.",
    group: "explain",
  },
  {
    id: "c-in-other-words",
    text: "in other words,",
    he: "במילים אחרות,",
    useHe: "מנסח מחדש בצורה פשוטה יותר. מצוין אחרי הסבר מסובך.",
    example: "In other words, we can't afford it right now.",
    group: "explain",
  },
  {
    id: "c-let-me-put-it-this-way",
    text: "let me put it this way:",
    he: "בוא אגיד את זה ככה:",
    useHe: "לפני ניסוח פשוט או ישיר, לפעמים לפני אמת לא נעימה.",
    example: "Let me put it this way: if we don't leave now, we'll miss the train.",
    group: "explain",
  },
  {
    id: "c-for-example",
    text: "for example,",
    he: "לדוגמה,",
    useHe: "הדרך הכי בסיסית להביא דוגמה. אפשר גם באמצע או בסוף המשפט.",
    example: "Some jobs, for example, nursing, require a lot of patience.",
    group: "explain",
  },
  {
    id: "c-for-instance",
    text: "for instance,",
    he: "למשל,",
    useHe: "בדיוק כמו for example, קצת יותר מגוון. שימושי כדי לא לחזור על אותה מילה.",
    example: "There are cheaper options, for instance, taking the night bus.",
    group: "explain",
  },
  {
    id: "c-such-as",
    text: "such as",
    he: "כגון, כמו",
    useHe: "מביא דוגמאות באמצע משפט, אחרי שם עצם: sports such as tennis. ללא פסיק אחריו.",
    example: "I enjoy outdoor activities such as hiking and cycling.",
    group: "explain",
  },
  {
    id: "c-the-reason-is-that",
    text: "the reason is that",
    he: "הסיבה היא ש...",
    useHe: "מציג סיבה בצורה ברורה. שימו לב: the reason is that, לא the reason is because.",
    example: "I left early. The reason is that I had a doctor's appointment.",
    group: "explain",
  },
  {
    id: "c-thats-why",
    text: "that's why",
    he: "בגלל זה, לכן",
    useHe: "מקשר סיבה לתוצאה בדיבור. אחריו משפט מלא: that's why I left.",
    example: "The traffic was terrible. That's why I was late.",
    group: "explain",
  },
  {
    id: "c-the-main-thing-is",
    text: "the main thing is",
    he: "העיקר הוא ש..., מה שחשוב זה...",
    useHe: "ממקד את השיחה בנקודה החשובה ביותר, לרוב אחרי פרטים קטנים.",
    example: "It's not perfect, but the main thing is that everyone is safe.",
    group: "explain",
  },
  {
    id: "c-what-im-trying-to-say",
    text: "what I'm trying to say is",
    he: "מה שאני מנסה להגיד זה...",
    useHe: "כשמתקשים לנסח ורוצים להגיע לנקודה. קונה זמן ומבהיר.",
    example: "What I'm trying to say is, I think you deserve a better job.",
    group: "explain",
  },
  {
    id: "c-to-give-you-an-idea",
    text: "to give you an idea,",
    he: "כדי שתבין בערך,",
    useHe: "לפני מספר או דוגמה שממחישים גודל או כמות.",
    example: "To give you an idea, the apartment costs twice what I pay now.",
    group: "explain",
  },
  {
    id: "c-basically",
    text: "basically,",
    he: "בעיקרון, בעצם,",
    useHe: "מסכם את המהות בפשטות. נפוץ מאוד בדיבור, אבל לא להגזים.",
    example: "Basically, the app helps you plan your meals for the week.",
    group: "explain",
  },

  // ---------- question (8) ----------
  {
    id: "c-what-do-you-think-about",
    text: "what do you think about",
    he: "מה אתה חושב על...",
    useHe: "השאלה הבסיסית לבקשת דעה. אחריה שם עצם או ing. שימו לב: about, לא on.",
    example: "What do you think about the new manager?",
    group: "question",
  },
  {
    id: "c-how-do-you-feel-about",
    text: "how do you feel about",
    he: "איך אתה מרגיש לגבי...",
    useHe: "שואל על דעה או רגש, קצת יותר אישי. גם להצעות: how do you feel about pizza?",
    example: "How do you feel about working on Sundays?",
    group: "question",
  },
  {
    id: "c-have-you-ever",
    text: "have you ever",
    he: "האם אי פעם...",
    useHe: "שאלה על חוויית חיים, תמיד עם present perfect: have you ever been to...?",
    example: "Have you ever tried sushi?",
    group: "question",
  },
  {
    id: "c-whats-your-take-on",
    text: "what's your take on",
    he: "מה העמדה שלך לגבי...",
    useHe: "בקשת דעה בסגנון דיבורי-מודרני. take = זווית ראייה. אחריו שם עצם.",
    example: "What's your take on the new parking rules?",
    group: "question",
  },
  {
    id: "c-do-you-mind-if-i",
    text: "do you mind if I",
    he: "אכפת לך אם אני...",
    useHe: "בקשת רשות מנומסת. תשובה חיובית היא 'No, go ahead' (לא אכפת לי).",
    example: "Do you mind if I open the window? It's really hot in here.",
    group: "question",
  },
  {
    id: "c-would-you-rather",
    text: "would you rather",
    he: "היית מעדיף...",
    useHe: "בחירה בין שתי אפשרויות: would you rather A or B? אחריו פועל בסיסי בלי to.",
    example: "Would you rather live in the city or in the countryside?",
    group: "question",
  },
  {
    id: "c-how-come",
    text: "how come",
    he: "איך זה ש..., למה?",
    useHe: "why דיבורי. שימו לב: אחריו סדר מילים רגיל, לא של שאלה: how come you left?",
    example: "How come you didn't tell me about the party?",
    group: "question",
  },
  {
    id: "c-what-about-you",
    text: "what about you?",
    he: "ומה איתך?",
    useHe: "מחזיר את השאלה לצד השני ושומר על השיחה זורמת. חובה בשיחות חולין.",
    example: "I usually get up at six. What about you?",
    group: "question",
  },

  // ---------- link (14) ----------
  {
    id: "c-on-the-other-hand",
    text: "on the other hand,",
    he: "מצד שני,",
    useHe: "מציג את הצד ההפוך של טיעון. לא חייבים להגיד קודם on the one hand.",
    example: "The job pays well. On the other hand, the hours are terrible.",
    group: "link",
  },
  {
    id: "c-even-so",
    text: "even so,",
    he: "ובכל זאת,",
    useHe: "מודה בעובדה ואז מוסיף משהו שסותר אותה. קצר ואלגנטי.",
    example: "It was raining hard. Even so, we went for a walk.",
    group: "link",
  },
  {
    id: "c-apart-from-that",
    text: "apart from that,",
    he: "חוץ מזה,",
    useHe: "אחרי שהזכרת בעיה או חריג אחד: apart from that, everything was fine.",
    example: "The room was a bit noisy. Apart from that, the hotel was great.",
    group: "link",
  },
  {
    id: "c-besides",
    text: "besides,",
    he: "חוץ מזה, ובנוסף,",
    useHe: "מוסיף טיעון נוסף, לרוב חזק יותר, לתמיכה בדעה. דיבורי.",
    example: "I don't want to go out tonight. Besides, it's freezing outside.",
    group: "link",
  },
  {
    id: "c-as-a-result",
    text: "as a result,",
    he: "כתוצאה מכך,",
    useHe: "מקשר סיבה לתוצאה, מעט רשמי. טוב להסבר של תהליכים.",
    example: "He forgot to set the alarm. As a result, he missed the exam.",
    group: "link",
  },
  {
    id: "c-because-of-that",
    text: "because of that,",
    he: "בגלל זה,",
    useHe: "תוצאה של משהו שנאמר. שימו לב: because of + שם עצם, because + משפט.",
    example: "The flight was canceled. Because of that, we lost a whole day.",
    group: "link",
  },
  {
    id: "c-in-addition",
    text: "in addition,",
    he: "בנוסף,",
    useHe: "מוסיף נקודה, מעט רשמי. חלופה ל-also בתחילת משפט.",
    example: "The course is cheap. In addition, it's completely online.",
    group: "link",
  },
  {
    id: "c-however",
    text: "however,",
    he: "עם זאת, אבל",
    useHe: "ניגוד בתחילת משפט חדש, תמיד עם פסיק. יותר רשמי מ-but.",
    example: "I wanted to help. However, I didn't have the time.",
    group: "link",
  },
  {
    id: "c-on-top-of-that",
    text: "on top of that,",
    he: "ועוד על זה, בנוסף לכל זה,",
    useHe: "מוסיף עוד פרט, לרוב עוד בעיה או עוד יתרון. דיבורי ורגשי.",
    example: "The car broke down, and on top of that, it started to rain.",
    group: "link",
  },
  {
    id: "c-anyway",
    text: "anyway,",
    he: "בכל אופן, בקיצור,",
    useHe: "חוזר לנושא המרכזי או סוגר נושא. חובה בשיחות ארוכות.",
    example: "Anyway, as I was saying, we need to book the tickets soon.",
    group: "link",
  },
  {
    id: "c-as-well-as",
    text: "as well as",
    he: "וגם, בנוסף ל...",
    useHe: "מחבר שני דברים באותו משפט: coffee as well as tea. מגוון את and.",
    example: "She speaks French as well as Spanish.",
    group: "link",
  },
  {
    id: "c-instead-of",
    text: "instead of",
    he: "במקום",
    useHe: "אחריו שם עצם או פועל ב-ing: instead of driving. לא instead of to drive.",
    example: "Let's walk instead of taking a taxi.",
    group: "link",
  },
  {
    id: "c-in-spite-of-that",
    text: "in spite of that,",
    he: "למרות זאת,",
    useHe: "כמו even so, מעט רשמי יותר. in spite of + שם עצם; in spite of that = למרות זה.",
    example: "The reviews were bad. In spite of that, the place was packed.",
    group: "link",
  },
  {
    id: "c-otherwise",
    text: "otherwise,",
    he: "אחרת,",
    useHe: "מה יקרה אם לא תעשו את זה. גם 'מלבד זה': it's small, otherwise it's fine.",
    example: "Leave now. Otherwise, you'll get stuck in traffic.",
    group: "link",
  },

  // ---------- feeling (12) ----------
  {
    id: "c-im-really-into",
    text: "I'm really into",
    he: "אני ממש בקטע של...",
    useHe: "אהבה חזקה לתחביב או תחום. אחריו שם עצם או פועל ב-ing.",
    example: "I'm really into cooking these days, especially Asian food.",
    group: "feeling",
  },
  {
    id: "c-fed-up-with",
    text: "I'm fed up with",
    he: "נמאס לי מ...",
    useHe: "כעס ועייפות ממשהו שנמשך זמן רב. אחריו שם עצם או ing.",
    example: "I'm fed up with waiting for the bus every morning.",
    group: "feeling",
  },
  {
    id: "c-looking-forward-to",
    text: "I'm looking forward to",
    he: "אני מצפה ל..., אני מחכה בקוצר רוח ל...",
    useHe: "ציפייה חיובית. שימו לב: אחרי to בא שם עצם או ing, לא פועל בסיסי.",
    example: "I'm looking forward to seeing you next week.",
    group: "feeling",
  },
  {
    id: "c-cant-wait-to",
    text: "I can't wait to",
    he: "אני מת כבר ל...",
    useHe: "ציפייה נלהבת ודיבורית. אחריו פועל בסיסי: I can't wait to start.",
    example: "I can't wait to see the new apartment.",
    group: "feeling",
  },
  {
    id: "c-sick-of",
    text: "I'm sick of",
    he: "נמאס לי מ..., אני חולה מ...",
    useHe: "כמו fed up with אבל חזק יותר. דיבורי מאוד. אחריו שם עצם או ing.",
    example: "I'm sick of hearing the same excuses every week.",
    group: "feeling",
  },
  {
    id: "c-blown-away-by",
    text: "I was blown away by",
    he: "נדהמתי מ..., זה הפיל אותי",
    useHe: "התרשמות עצומה וחיובית. טוב למופעים, נופים, ביצועים.",
    example: "I was blown away by the view from the top of the mountain.",
    group: "feeling",
  },
  {
    id: "c-drives-me-crazy",
    text: "it drives me crazy when",
    he: "זה משגע אותי כש...",
    useHe: "עצבנות ממשהו שחוזר על עצמו. אחריו משפט מלא.",
    example: "It drives me crazy when people are late without calling.",
    group: "feeling",
  },
  {
    id: "c-relieved-that",
    text: "I'm relieved that",
    he: "הוקל לי ש...",
    useHe: "הקלה אחרי דאגה. שימו לב: relieved, לא relaxed (רגוע).",
    example: "I'm relieved that the test results came back fine.",
    group: "feeling",
  },
  {
    id: "c-dying-to",
    text: "I'm dying to",
    he: "אני מת ל...",
    useHe: "רצון עז ודיבורי. אחריו פועל בסיסי. גם dying for + שם עצם: dying for a coffee.",
    example: "I'm dying to know what happened at the meeting.",
    group: "feeling",
  },
  {
    id: "c-not-in-the-mood-for",
    text: "I'm not in the mood for",
    he: "לא בא לי..., אין לי מצב רוח ל...",
    useHe: "הדרך הטבעית להגיד 'לא בא לי'. אחריו שם עצם או ing. לא 'it doesn't come to me'.",
    example: "I'm not in the mood for a big party tonight.",
    group: "feeling",
  },
  {
    id: "c-means-a-lot-to-me",
    text: "it means a lot to me",
    he: "זה חשוב לי מאוד, זה אומר לי הרבה",
    useHe: "הכרת תודה או חשיבות רגשית. מצוין אחרי שמישהו עזר לך.",
    example: "Thanks for coming. It means a lot to me.",
    group: "feeling",
  },
  {
    id: "c-over-the-moon",
    text: "I was over the moon",
    he: "הייתי בעננים, שמחתי מאוד",
    useHe: "שמחה גדולה, דיבורי. לרוב עם about או when: over the moon when I got the job.",
    example: "I was over the moon when they offered me the job.",
    group: "feeling",
  },
];
