import type { InterferenceTrap } from "@/lib/types";

/**
 * Hebrew -> English interference traps.
 * `pattern` is a JS regex source used with the "i" flag on the learner's own free writing:
 * it must match `wrong` and must NOT match `right`. Patterns are deliberately narrow
 * (word boundaries, closed alternations, negative lookaheads) to keep false positives low.
 */
export const TRAPS: InterferenceTrap[] = [
  // ---------------------------------------------------------------------------
  // Age: be, not have
  // ---------------------------------------------------------------------------
  {
    id: "i-have-years-age",
    titleHe: "גיל: I'm 30, לא I have 30 years",
    wrong: "I have 30 years and I still live with my parents.",
    right: "I'm 30 years old and I still live with my parents.",
    explainHe: "בעברית 'אני בן 30' או 'יש לי 30', ולכן יוצא have. באנגלית הגיל נאמר עם be: I'm 30 (years old).",
    pattern: "\\b(i|you|he|she|we|they)\\s+(have|has|had)\\s+\\d+\\s+years?\\b(?!\\s+(old|of\\s+experience))",
    drills: [
      { id: "i-have-years-age-01", type: "fix", prompt: "My brother has 25 years.", answer: "My brother is 25.", accept: ["My brother is 25 years old."], errorType: "interference", explainHe: "גיל באנגלית עם be: he is 25. have שייך לרכוש, לא לגיל." },
      {
        id: "i-have-years-age-02",
        type: "mcq",
        prompt: "___ 42 years old and she runs every morning.",
        options: [
          { text: "She has", errorType: "interference", whyHe: "תרגום ישיר של 'יש לה 42'." },
          { text: "She is" },
          { text: "She has got", errorType: "interference", whyHe: "have got מתאים לרכוש, לא לגיל." },
        ],
        answerIndex: 1,
        explainHe: "she is 42 years old. באנגלית הגיל הוא תכונה של האדם, ולכן be.",
      },
      { id: "i-have-years-age-03", type: "fix", prompt: "How many years do you have?", answer: "How old are you?", errorType: "interference", explainHe: "'בן כמה אתה?' באנגלית זה How old are you?, לא שאלה על מספר שנים." },
      { id: "i-have-years-age-04", type: "translate", he: "אני בן שלושים ושתיים.", answer: "I'm 32.", accept: ["I am 32 years old.", "I'm 32 years old."], explainHe: "I'm 32 (years old). אפשר גם בלי years old, אבל אף פעם לא I have 32." },
    ],
  },

  // ---------------------------------------------------------------------------
  // make / do / take collocations
  // ---------------------------------------------------------------------------
  {
    id: "i-make-a-party",
    titleHe: "make a party במקום have / throw a party",
    wrong: "We want to make a party for her birthday.",
    right: "We want to throw a party for her birthday.",
    explainHe: "בעברית 'עושים מסיבה', ולכן יוצא make. באנגלית אומרים have a party או throw a party.",
    pattern: "\\b(make|makes|made|making)\\s+(a|an|the)\\s+(big\\s+|small\\s+|surprise\\s+)?part(y|ies)\\b",
    drills: [
      { id: "i-make-a-party-01", type: "fix", prompt: "They made a party last Friday.", answer: "They had a party last Friday.", accept: ["They threw a party last Friday."], errorType: "word-choice", explainHe: "have a party / throw a party. make a party נשמע כאילו מייצרים מסיבה." },
      {
        id: "i-make-a-party-02",
        type: "mcq",
        prompt: "Let's ___ a party when the exams finish.",
        options: [
          { text: "make", errorType: "word-choice", whyHe: "תרגום של 'לעשות מסיבה'." },
          { text: "have" },
          { text: "do", errorType: "word-choice", whyHe: "do a party לא קיים באנגלית." },
        ],
        answerIndex: 1,
        explainHe: "have a party הוא הצירוף הרגיל בדיבור; throw a party קצת יותר חגיגי.",
      },
      { id: "i-make-a-party-03", type: "fix", prompt: "I'm making a surprise party for my sister.", answer: "I'm throwing a surprise party for my sister.", accept: ["I'm having a surprise party for my sister."], errorType: "word-choice", explainHe: "throw a surprise party – זה הצירוף הקבוע למסיבת הפתעה." },
      {
        id: "i-make-a-party-04",
        type: "mcq",
        prompt: "Who's ___ the party this year?",
        options: [
          { text: "making", errorType: "word-choice", whyHe: "make לא מתחבר ל-party." },
          { text: "throwing" },
          { text: "doing", errorType: "word-choice", whyHe: "do a party לא נאמר." },
        ],
        answerIndex: 1,
        explainHe: "throw a party = לארגן ולהעביר מסיבה.",
      },
    ],
  },
  {
    id: "i-make-sport",
    titleHe: "make sport / make exercise",
    wrong: "I make sport three times a week.",
    right: "I work out three times a week.",
    explainHe: "בעברית 'עושים ספורט', ולכן יוצא make. באנגלית do sports, play sports או work out – אף פעם לא make sport.",
    pattern: "\\b(make|makes|made|making)\\s+(sports?|exercise|yoga|pilates|gym|training)\\b",
    drills: [
      { id: "i-make-sport-01", type: "fix", prompt: "My father makes sport every morning.", answer: "My father does sports every morning.", accept: ["My father works out every morning."], errorType: "word-choice", explainHe: "do sports / work out. make אף פעם לא מתחבר לספורט." },
      {
        id: "i-make-sport-02",
        type: "mcq",
        prompt: "She ___ yoga twice a week.",
        options: [
          { text: "makes", errorType: "word-choice", whyHe: "'עושה יוגה' בעברית, אבל לא make באנגלית." },
          { text: "does" },
          { text: "plays", errorType: "word-choice", whyHe: "play שמור למשחקי כדור: play football." },
        ],
        answerIndex: 1,
        explainHe: "do yoga, do Pilates, do karate. play שמור למשחקים תחרותיים.",
      },
      { id: "i-make-sport-03", type: "fix", prompt: "I want to make exercise after work.", answer: "I want to exercise after work.", accept: ["I want to work out after work.", "I want to get some exercise after work."], errorType: "word-choice", explainHe: "exercise הוא גם פועל: to exercise. אפשר גם get exercise או work out." },
      {
        id: "i-make-sport-04",
        type: "mcq",
        prompt: "I'm trying to ___ more exercise this year.",
        options: [
          { text: "make", errorType: "word-choice", whyHe: "make exercise לא קיים." },
          { text: "get" },
          { text: "take", errorType: "word-choice", whyHe: "take exercise נשמע ישן ומאוד פורמלי." },
        ],
        answerIndex: 1,
        explainHe: "get more exercise = להתאמן יותר. צירוף טבעי בדיבור יומיומי.",
      },
    ],
  },
  {
    id: "i-make-an-exam",
    titleHe: "make an exam במקום take an exam",
    wrong: "I have to make an exam on Thursday.",
    right: "I have to take an exam on Thursday.",
    explainHe: "בעברית 'עושים מבחן', ולכן make. באנגלית התלמיד take an exam, והמורה give an exam. make an exam פירושו לחבר את המבחן.",
    pattern: "\\b(make|makes|made|making)\\s+(a|an|the|my|his|her|their)\\s+(final\\s+|big\\s+|driving\\s+)?(exam|test|quiz)\\b",
    drills: [
      { id: "i-make-an-exam-01", type: "fix", prompt: "She made the test yesterday and passed.", answer: "She took the test yesterday and passed.", errorType: "word-choice", explainHe: "take a test = לגשת למבחן. make a test = לכתוב את המבחן בשביל אחרים." },
      {
        id: "i-make-an-exam-02",
        type: "mcq",
        prompt: "I'm ___ my driving test next month.",
        options: [
          { text: "making", errorType: "word-choice", whyHe: "תרגום ישיר של 'עושה טסט'." },
          { text: "taking" },
          { text: "giving", errorType: "word-choice", whyHe: "give a test זה מה שהבוחן עושה, לא הנבחן." },
        ],
        answerIndex: 1,
        explainHe: "take a driving test. give שייך לצד שמעביר את המבחן.",
      },
      { id: "i-make-an-exam-03", type: "fix", prompt: "We make an exam every Friday in this course.", answer: "We take an exam every Friday in this course.", errorType: "word-choice", explainHe: "הסטודנטים take an exam. שימו לב גם ל-every Friday = הווה פשוט." },
      {
        id: "i-make-an-exam-04",
        type: "mcq",
        prompt: "The teacher ___ us a test at the end of the unit.",
        options: [
          { text: "makes", errorType: "word-choice", whyHe: "make a test = לחבר אותו, ואז אין us." },
          { text: "gives" },
          { text: "takes", errorType: "word-choice", whyHe: "take שייך לנבחן." },
        ],
        answerIndex: 1,
        explainHe: "give somebody a test = להעביר להם מבחן. שני הפעלים הפוכים בין המורה לתלמיד.",
      },
    ],
  },
  {
    id: "i-make-homework",
    titleHe: "make homework במקום do homework",
    wrong: "I need to make my homework before dinner.",
    right: "I need to do my homework before dinner.",
    explainHe: "בעברית 'עושים שיעורי בית', ובאנגלית הצירוף הוא do homework. חוץ מזה homework תמיד ביחיד ובלי a.",
    pattern: "\\b(make|makes|made|making)\\s+((my|your|his|her|our|their|the)\\s+)?homework\\b",
    drills: [
      { id: "i-make-homework-01", type: "fix", prompt: "He never makes his homework on time.", answer: "He never does his homework on time.", errorType: "word-choice", explainHe: "do homework. make שמור ליצירה של משהו חדש." },
      {
        id: "i-make-homework-02",
        type: "mcq",
        prompt: "Have you ___ your homework yet?",
        options: [
          { text: "made", errorType: "word-choice", whyHe: "'עשית שיעורים' מתורגם בטעות ל-make." },
          { text: "done" },
          { text: "did", errorType: "verb-form", whyHe: "אחרי have צריך צורה שלישית: done." },
        ],
        answerIndex: 1,
        explainHe: "do homework, ואחרי have באה הצורה השלישית: done.",
      },
      { id: "i-make-homework-03", type: "fix", prompt: "The kids are making homework in the kitchen.", answer: "The kids are doing homework in the kitchen.", errorType: "word-choice", explainHe: "do homework גם בזמן ממושך: are doing homework." },
      {
        id: "i-make-homework-04",
        type: "mcq",
        prompt: "We got ___ homework this week.",
        options: [
          { text: "a lot of" },
          { text: "many", errorType: "countability", whyHe: "homework לא ספירה, ולכן לא many." },
          { text: "much of", errorType: "countability", whyHe: "much of דורש the אחריו." },
        ],
        answerIndex: 0,
        explainHe: "homework לא ספירה: a lot of homework, ואף פעם לא homeworks או many homework.",
      },
    ],
  },

  // ---------------------------------------------------------------------------
  // Verb patterns / word choice
  // ---------------------------------------------------------------------------
  {
    id: "i-am-agree",
    titleHe: "I am agree במקום I agree",
    wrong: "I am agree with you about the price.",
    right: "I agree with you about the price.",
    explainHe: "בעברית 'אני מסכים' הוא בינוני ומרגיש כמו שם תואר, ולכן נוסף am. באנגלית agree הוא פועל רגיל: I agree, she agrees.",
    pattern: "\\b(i\\s*'m|(i|you|we|they|he|she)\\s+(am|is|are|was|were))\\s+(not\\s+|totally\\s+|really\\s+)?agree\\b",
    drills: [
      { id: "i-am-agree-01", type: "fix", prompt: "She is agree with the new plan.", answer: "She agrees with the new plan.", errorType: "verb-form", explainHe: "agree הוא פועל, ובגוף שלישי מקבל s: she agrees." },
      {
        id: "i-am-agree-02",
        type: "mcq",
        prompt: "___ that the movie was too long.",
        options: [
          { text: "I'm agree", errorType: "verb-form", whyHe: "אין be לפני agree." },
          { text: "I agree" },
          { text: "I am agreed", errorType: "verb-form", whyHe: "agree לא בפסיב." },
        ],
        answerIndex: 1,
        explainHe: "I agree. הפועל עומד לבד, בלי am ובלי סביל.",
      },
      { id: "i-am-agree-03", type: "fix", prompt: "We are not agree with this decision.", answer: "We don't agree with this decision.", accept: ["We disagree with this decision."], errorType: "verb-form", explainHe: "שלילה של פועל רגיל: don't agree, או המילה disagree." },
      { id: "i-am-agree-04", type: "translate", he: "אני לא מסכים איתך.", answer: "I don't agree with you.", accept: ["I disagree with you."], explainHe: "agree with somebody. השלילה עם don't, לא עם am not." },
    ],
  },
  {
    id: "i-explain-me",
    titleHe: "explain me במקום explain to me",
    wrong: "Can you explain me this rule again?",
    right: "Can you explain this rule to me again?",
    explainHe: "בעברית 'תסביר לי משהו', והאדם בא ראשון. באנגלית explain something TO somebody – האדם תמיד אחרי to.",
    pattern: "\\b(explain|explains|explained|explaining)\\s+(me|him|her|us|them|you)\\b",
    drills: [
      { id: "i-explain-me-01", type: "fix", prompt: "He explained us the whole story.", answer: "He explained the whole story to us.", errorType: "word-order", explainHe: "explain + מה + to + למי. אי אפשר לשים את האדם ישר אחרי הפועל." },
      {
        id: "i-explain-me-02",
        type: "mcq",
        prompt: "Could you ___ how it works?",
        options: [
          { text: "explain me", errorType: "word-order", whyHe: "explain לא לוקח אדם ישירות." },
          { text: "explain to me" },
          { text: "explain for me", errorType: "preposition", whyHe: "אחרי explain באה to ולא for." },
        ],
        answerIndex: 1,
        explainHe: "explain to me how it works. אפשר גם פשוט explain how it works.",
      },
      { id: "i-explain-me-03", type: "fix", prompt: "Please explain me why you were late.", answer: "Please explain to me why you were late.", accept: ["Please explain why you were late."], errorType: "word-order", explainHe: "או explain to me why..., או פשוט explain why... בלי האדם." },
      {
        id: "i-explain-me-04",
        type: "mcq",
        prompt: "The doctor ___ the results to my mother.",
        options: [
          { text: "explained" },
          { text: "explained to", errorType: "word-order", whyHe: "to כבר מופיע לפני my mother." },
          { text: "said", errorType: "word-choice", whyHe: "say לא מתאים כאן: say something to somebody בלי הסבר." },
        ],
        answerIndex: 0,
        explainHe: "explained the results to my mother – קודם מה הוסבר, אחר כך to + האדם.",
      },
    ],
  },
  {
    id: "i-discuss-about",
    titleHe: "discuss about",
    wrong: "We discussed about the budget for two hours.",
    right: "We discussed the budget for two hours.",
    explainHe: "בעברית 'דיברנו על', ומכאן about. אבל discuss כבר כולל את 'על': discuss something. עם talk כן אומרים talk about.",
    pattern: "\\bdiscuss(es|ed|ing)?\\s+about\\b",
    drills: [
      { id: "i-discuss-about-01", type: "fix", prompt: "Let's discuss about it tomorrow.", answer: "Let's discuss it tomorrow.", errorType: "preposition", explainHe: "discuss it – בלי about." },
      {
        id: "i-discuss-about-02",
        type: "mcq",
        prompt: "They ___ the problem at the meeting.",
        options: [
          { text: "discussed about", errorType: "preposition", whyHe: "about מיותר אחרי discuss." },
          { text: "discussed" },
          { text: "discussed on", errorType: "preposition", whyHe: "discuss לא לוקח מילת יחס בכלל." },
        ],
        answerIndex: 1,
        explainHe: "discuss something – פועל יוצא, בלי מילת יחס.",
      },
      { id: "i-discuss-about-03", type: "fix", prompt: "We are discussing about moving to a bigger office.", answer: "We are discussing moving to a bigger office.", errorType: "preposition", explainHe: "discuss + שם פועל בצורת ing, בלי about." },
      {
        id: "i-discuss-about-04",
        type: "mcq",
        prompt: "I want to ___ about my salary with my manager.",
        options: [
          { text: "discuss", errorType: "preposition", whyHe: "אם משאירים about, צריך פועל אחר." },
          { text: "talk" },
          { text: "mention", errorType: "word-choice", whyHe: "mention something, בלי about." },
        ],
        answerIndex: 1,
        explainHe: "talk about something – כאן about דווקא חובה. השוו: discuss something.",
      },
    ],
  },
  {
    id: "i-depend-of",
    titleHe: "depend of / depend from",
    wrong: "It depends of the weather on Saturday.",
    right: "It depends on the weather on Saturday.",
    explainHe: "בעברית 'תלוי ב־', ומכאן of או from. באנגלית תמיד depend ON, וגם be dependent on.",
    pattern: "\\bdepend(s|ed|ing)?\\s+(of|from|in)\\b",
    drills: [
      { id: "i-depend-of-01", type: "fix", prompt: "The price depends from the size.", answer: "The price depends on the size.", errorType: "preposition", explainHe: "depend on – מילת היחס קבועה." },
      {
        id: "i-depend-of-02",
        type: "mcq",
        prompt: "Everything ___ him now.",
        options: [
          { text: "depends of", errorType: "preposition", whyHe: "of לא בא אחרי depend." },
          { text: "depends on" },
          { text: "depends from", errorType: "preposition", whyHe: "תרגום של 'תלוי מ־' בשפות אחרות." },
        ],
        answerIndex: 1,
        explainHe: "depend on somebody = גם 'תלוי בו' וגם 'סומך עליו'.",
      },
      { id: "i-depend-of-03", type: "fix", prompt: "My plans depend of my boss.", answer: "My plans depend on my boss.", errorType: "preposition", explainHe: "depend on. גם depending on the weather באותה מילת יחס." },
      { id: "i-depend-of-04", type: "translate", he: "זה תלוי בך.", answer: "It depends on you.", accept: ["That depends on you.", "It's up to you."], explainHe: "It depends on you. בדיבור אפשר גם It's up to you = ההחלטה שלך." },
    ],
  },
  {
    id: "i-married-with",
    titleHe: "married with במקום married to",
    wrong: "My sister is married with a lawyer from Haifa.",
    right: "My sister is married to a lawyer from Haifa.",
    explainHe: "בעברית 'נשואה עם', ומכאן with. באנגלית married TO somebody. שימו לב: married with two kids פירושו 'נשוי ויש לו שני ילדים'.",
    pattern: "\\bmarried\\s+with\\s+(?!(two|three|four|five|\\d+|children|kids|a\\s+child))(a|an|the|my|his|her|our|their|him|me|us|someone)\\b",
    drills: [
      { id: "i-married-with-01", type: "fix", prompt: "He got married with his girlfriend last summer.", answer: "He got married to his girlfriend last summer.", errorType: "preposition", explainHe: "get married to somebody. with מתאים רק ל-married with kids (ילדים)." },
      {
        id: "i-married-with-02",
        type: "mcq",
        prompt: "She's been married ___ him for ten years.",
        options: [
          { text: "with", errorType: "preposition", whyHe: "תרגום של 'נשואה עם'." },
          { text: "to" },
          { text: "on", errorType: "preposition", whyHe: "on לא מתחבר ל-married." },
        ],
        answerIndex: 1,
        explainHe: "married to somebody – מילת היחס קבועה, ואחריה for + משך זמן.",
      },
      { id: "i-married-with-03", type: "fix", prompt: "Are you married with someone from here?", answer: "Are you married to someone from here?", errorType: "preposition", explainHe: "married to somebody, גם בשאלה." },
      {
        id: "i-married-with-04",
        type: "mcq",
        prompt: "My cousin is getting married ___ a guy she met at work.",
        options: [
          { text: "with", errorType: "preposition", whyHe: "'מתחתנת עם' בעברית, אבל לא with באנגלית." },
          { text: "to" },
          { text: "for", errorType: "preposition", whyHe: "for לא שייך כאן." },
        ],
        answerIndex: 1,
        explainHe: "get married to somebody. הפועל marry לבד גם הוא בלי מילת יחס: she married him.",
      },
    ],
  },
  {
    id: "i-angry-on",
    titleHe: "angry on במקום angry with",
    wrong: "My boss was angry on me because I came late.",
    right: "My boss was angry with me because I came late.",
    explainHe: "בעברית 'כועס על', ומכאן on. באנגלית angry WITH somebody (או angry AT), ועל מצב או דבר angry ABOUT.",
    pattern: "\\b(angry|mad|upset|annoyed)\\s+on\\s+(me|him|her|us|them|you|my|his|their|your|our)\\b",
    drills: [
      { id: "i-angry-on-01", type: "fix", prompt: "Don't be angry on me, it was an accident.", answer: "Don't be angry with me, it was an accident.", accept: ["Don't be angry at me, it was an accident."], errorType: "preposition", explainHe: "angry with me / angry at me – שניהם טבעיים, on אף פעם לא." },
      {
        id: "i-angry-on-02",
        type: "mcq",
        prompt: "She's still angry ___ her brother.",
        options: [
          { text: "on", errorType: "preposition", whyHe: "תרגום ישיר של 'כועסת על'." },
          { text: "with" },
          { text: "of", errorType: "preposition", whyHe: "of לא בא אחרי angry." },
        ],
        answerIndex: 1,
        explainHe: "angry with + אדם. זו מילת היחס הנפוצה ביותר בדיבור.",
      },
      { id: "i-angry-on-03", type: "fix", prompt: "He was very upset on his team after the game.", answer: "He was very upset with his team after the game.", errorType: "preposition", explainHe: "גם upset עובד כמו angry: upset with somebody." },
      {
        id: "i-angry-on-04",
        type: "mcq",
        prompt: "I'm angry ___ the whole situation.",
        options: [
          { text: "on", errorType: "preposition", whyHe: "on לא משמש עם רגשות." },
          { text: "about" },
          { text: "in", errorType: "preposition", whyHe: "in לא מתחבר ל-angry." },
        ],
        answerIndex: 1,
        explainHe: "על אדם – angry with. על מצב או דבר – angry about.",
      },
    ],
  },
  {
    id: "i-arrive-to",
    titleHe: "arrive to במקום arrive at / in",
    wrong: "We arrived to the airport two hours early.",
    right: "We arrived at the airport two hours early.",
    explainHe: "בעברית 'הגענו לשדה התעופה', וה־'ל' הופכת ל-to. באנגלית arrive AT (מקום ספציפי), arrive IN (עיר או מדינה), ו-arrive home בלי מילת יחס.",
    pattern: "\\barriv(e|es|ed|ing)\\s+to\\s+(the|a|an|my|his|her|our|their|work|school|home|israel|london)\\b",
    drills: [
      { id: "i-arrive-to-01", type: "fix", prompt: "The train arrives to the station at nine.", answer: "The train arrives at the station at nine.", errorType: "preposition", explainHe: "arrive at + מקום מוגדר: at the station, at the office." },
      {
        id: "i-arrive-to-02",
        type: "mcq",
        prompt: "They arrived ___ Berlin on Monday morning.",
        options: [
          { text: "to", errorType: "preposition", whyHe: "arrive לא לוקח to אף פעם." },
          { text: "in" },
          { text: "on", errorType: "preposition", whyHe: "on שייך לתאריכים, לא למקום." },
        ],
        answerIndex: 1,
        explainHe: "ערים ומדינות מקבלות in: arrive in Berlin, arrive in Israel.",
      },
      { id: "i-arrive-to-03", type: "fix", prompt: "I arrived to home very late last night.", answer: "I arrived home very late last night.", accept: ["I got home very late last night."], errorType: "preposition", explainHe: "עם home אין מילת יחס בכלל: arrive home, go home, get home." },
      {
        id: "i-arrive-to-04",
        type: "mcq",
        prompt: "What time did you ___ at the office?",
        options: [
          { text: "arrive" },
          { text: "arrive to", errorType: "preposition", whyHe: "to מיותר, ובנוסף at כבר מופיע." },
          { text: "reach", errorType: "preposition", whyHe: "reach the office – בלי at." },
        ],
        answerIndex: 0,
        explainHe: "arrive at the office. reach עובד בלי מילת יחס: reach the office.",
      },
    ],
  },
  {
    id: "i-go-to-home",
    titleHe: "go to home במקום go home",
    wrong: "After work I go to home and cook dinner.",
    right: "After work I go home and cook dinner.",
    explainHe: "בעברית 'הולך הביתה' עם ה' המגמה, ודוברי עברית מתרגמים אותה ל-to. עם home אין מילת יחס: go home, come home, get home.",
    pattern: "\\b(go|goes|going|went|gone)\\s+to\\s+home\\b(?!\\s*page)",
    drills: [
      { id: "i-go-to-home-01", type: "fix", prompt: "She went to home early because she felt sick.", answer: "She went home early because she felt sick.", errorType: "preposition", explainHe: "went home. home מתנהג כאן כמו תיאור מקום, בלי to." },
      {
        id: "i-go-to-home-02",
        type: "mcq",
        prompt: "I usually ___ around six.",
        options: [
          { text: "go to home", errorType: "preposition", whyHe: "to מיותר לפני home." },
          { text: "go home" },
          { text: "go at home", errorType: "preposition", whyHe: "at home = נמצא בבית, לא תנועה." },
        ],
        answerIndex: 1,
        explainHe: "go home = תנועה הביתה. at home = להיות בבית: I'm at home now.",
      },
      { id: "i-go-to-home-03", type: "fix", prompt: "Are you going to home now?", answer: "Are you going home now?", errorType: "preposition", explainHe: "going home. שימו לב שעם מקומות אחרים כן צריך to: going to the office." },
      {
        id: "i-go-to-home-04",
        type: "mcq",
        prompt: "He got ___ after midnight.",
        options: [
          { text: "to home", errorType: "preposition", whyHe: "get home בלי to." },
          { text: "home" },
          { text: "at home", errorType: "preposition", whyHe: "at home מתאר מצב, לא הגעה." },
        ],
        answerIndex: 1,
        explainHe: "get home = להגיע הביתה. אותו כלל כמו go home ו-come home.",
      },
    ],
  },
  {
    id: "i-in-the-bus",
    titleHe: "in the bus במקום on the bus",
    wrong: "I read the news in the bus every morning.",
    right: "I read the news on the bus every morning.",
    explainHe: "בעברית 'באוטובוס', ולכן in. באנגלית בתחבורה ציבורית גדולה אומרים ON: on the bus, on the train, on a plane. in נשמר לרכב פרטי ולמונית.",
    pattern: "\\bin\\s+the\\s+(bus|train|plane|subway|metro|tram)\\b(?!\\s+(station|stop|terminal|ride))",
    drills: [
      { id: "i-in-the-bus-01", type: "fix", prompt: "We met in the train to Haifa.", answer: "We met on the train to Haifa.", errorType: "preposition", explainHe: "on the train. הכלל: אם אפשר לקום וללכת בפנים – on." },
      {
        id: "i-in-the-bus-02",
        type: "mcq",
        prompt: "I left my bag ___ the bus.",
        options: [
          { text: "in", errorType: "preposition", whyHe: "תרגום ישיר של 'באוטובוס'." },
          { text: "on" },
          { text: "at", errorType: "preposition", whyHe: "at the bus stop כן, at the bus לא." },
        ],
        answerIndex: 1,
        explainHe: "on the bus. שימו לב: at the bus stop – שם דווקא at.",
      },
      { id: "i-in-the-bus-03", type: "fix", prompt: "She slept in the plane the whole flight.", answer: "She slept on the plane the whole flight.", errorType: "preposition", explainHe: "on the plane, on the flight. גם כלי טיס גדולים מקבלים on." },
      {
        id: "i-in-the-bus-04",
        type: "mcq",
        prompt: "He was already ___ the car when I called.",
        options: [
          { text: "on", errorType: "preposition", whyHe: "on שמור לכלים גדולים." },
          { text: "in" },
          { text: "at", errorType: "preposition", whyHe: "at לא מתאר להיות בתוך רכב." },
        ],
        answerIndex: 1,
        explainHe: "רכב פרטי ומונית דווקא מקבלים in: in the car, in a taxi.",
      },
    ],
  },
  {
    id: "i-listen-music",
    titleHe: "listen music במקום listen to music",
    wrong: "I listen music when I clean the house.",
    right: "I listen to music when I clean the house.",
    explainHe: "בעברית 'שומע מוזיקה' בלי מילת יחס. באנגלית listen תמיד עם to: listen to music, listen to me.",
    pattern: "\\blisten(s|ed|ing)?\\s+(the\\s+|a\\s+)?(music|radio|songs?|podcasts?|news)\\b",
    drills: [
      { id: "i-listen-music-01", type: "fix", prompt: "He was listening the radio in the kitchen.", answer: "He was listening to the radio in the kitchen.", errorType: "preposition", explainHe: "listen to the radio. to לא נעלם גם בזמן ממושך." },
      {
        id: "i-listen-music-02",
        type: "mcq",
        prompt: "Do you ___ podcasts on your way to work?",
        options: [
          { text: "listen", errorType: "preposition", whyHe: "חסר to." },
          { text: "listen to" },
          { text: "hear to", errorType: "preposition", whyHe: "hear לא לוקח to בכלל." },
        ],
        answerIndex: 1,
        explainHe: "listen to something. השוו: hear something, בלי מילת יחס.",
      },
      { id: "i-listen-music-03", type: "fix", prompt: "Listen me for one minute, please.", answer: "Listen to me for one minute, please.", errorType: "preposition", explainHe: "listen to me. גם עם אנשים חייבים to." },
      {
        id: "i-listen-music-04",
        type: "mcq",
        prompt: "I ___ a strange noise last night.",
        options: [
          { text: "listened", errorType: "preposition", whyHe: "חסר to, ובנוסף רעש פתאומי לא 'מקשיבים' לו." },
          { text: "heard" },
          { text: "listened to", errorType: "word-choice", whyHe: "listen = הקשבה מכוונת; רעש פתאומי פשוט שומעים." },
        ],
        answerIndex: 1,
        explainHe: "hear = לשמוע במקרה. listen to = להקשיב בכוונה.",
      },
    ],
  },
  {
    id: "i-good-in-english",
    titleHe: "good in English במקום good at",
    wrong: "She is very good in English and math.",
    right: "She is very good at English and math.",
    explainHe: "בעברית 'טובה באנגלית', ומכאן in. באנגלית good AT something. good in נכון רק לציון מקום: the best restaurant in town.",
    pattern: "\\b(good|bad|better|best|great|weak|terrible|excellent)\\s+in\\s+(english|hebrew|arabic|math|maths|sports?|physics|chemistry|history|cooking|languages)\\b",
    drills: [
      { id: "i-good-in-english-01", type: "fix", prompt: "I'm not very good in math.", answer: "I'm not very good at math.", errorType: "preposition", explainHe: "good at + תחום או פעולה." },
      {
        id: "i-good-in-english-02",
        type: "mcq",
        prompt: "He's really good ___ fixing things.",
        options: [
          { text: "in", errorType: "preposition", whyHe: "תרגום של 'טוב ב־'." },
          { text: "at" },
          { text: "on", errorType: "preposition", whyHe: "on לא בא אחרי good." },
        ],
        answerIndex: 1,
        explainHe: "good at + פועל בצורת ing: good at fixing, good at cooking.",
      },
      { id: "i-good-in-english-03", type: "fix", prompt: "My son is bad in sports.", answer: "My son is bad at sports.", errorType: "preposition", explainHe: "גם bad, weak ו-terrible עובדים עם at." },
      {
        id: "i-good-in-english-04",
        type: "mcq",
        prompt: "Are you good ___ cooking?",
        options: [
          { text: "in", errorType: "preposition", whyHe: "in לא מתאים ליכולת." },
          { text: "at" },
          { text: "of", errorType: "preposition", whyHe: "of לא בא אחרי good." },
        ],
        answerIndex: 1,
        explainHe: "good at cooking. (good with שמור לאנשים או כלים: good with kids.)",
      },
    ],
  },

  // ---------------------------------------------------------------------------
  // Nouns, agreement, countability, articles
  // ---------------------------------------------------------------------------
  {
    id: "i-people-is",
    titleHe: "people is במקום people are",
    wrong: "In my city people is very friendly.",
    right: "In my city people are very friendly.",
    explainHe: "בעברית 'אנשים' מרגיש כמו שם קיבוצי ביחיד. באנגלית people הוא הרבים של person, ולכן תמיד are, were, have.",
    pattern: "\\bpeople\\s+(is|was|isn't|wasn't|has|does|doesn't)\\b",
    drills: [
      { id: "i-people-is-01", type: "fix", prompt: "People is talking about it everywhere.", answer: "People are talking about it everywhere.", errorType: "agreement", explainHe: "people = רבים, ולכן are talking." },
      {
        id: "i-people-is-02",
        type: "mcq",
        prompt: "A lot of people ___ already left.",
        options: [
          { text: "has", errorType: "agreement", whyHe: "people תמיד רבים." },
          { text: "have" },
          { text: "is", errorType: "agreement", whyHe: "גם is לא מתאים לרבים." },
        ],
        answerIndex: 1,
        explainHe: "a lot of people have left. הנושא הוא people, לא a lot.",
      },
      { id: "i-people-is-03", type: "fix", prompt: "Most people doesn't like waiting.", answer: "Most people don't like waiting.", errorType: "agreement", explainHe: "most people don't. אין s בפועל אחרי רבים." },
      {
        id: "i-people-is-04",
        type: "mcq",
        prompt: "The police ___ still looking for him.",
        options: [
          { text: "is", errorType: "agreement", whyHe: "police מתנהג כרבים באנגלית." },
          { text: "are" },
          { text: "was", errorType: "agreement", whyHe: "גם ביחיד וגם בזמן הלא נכון." },
        ],
        answerIndex: 1,
        explainHe: "כמו people, גם police מקבל פועל ברבים: the police are.",
      },
    ],
  },
  {
    id: "i-uncountable-plural",
    titleHe: "advices / informations / furnitures",
    wrong: "He gave me some good advices and a lot of informations.",
    right: "He gave me some good advice and a lot of information.",
    explainHe: "בעברית 'עצות', 'רהיטים' – ברבים. באנגלית advice, information, furniture, equipment הן מילים לא ספירות: בלי s ובלי a. סופרים אותן עם piece of.",
    pattern: "\\b(advices|informations|furnitures|equipments|homeworks|luggages|softwares|knowledges)\\b",
    drills: [
      { id: "i-uncountable-plural-01", type: "fix", prompt: "I need some advices about my CV.", answer: "I need some advice about my CV.", errorType: "countability", explainHe: "advice לא ספירה: some advice, a piece of advice." },
      {
        id: "i-uncountable-plural-02",
        type: "mcq",
        prompt: "We bought new ___ for the living room.",
        options: [
          { text: "furnitures", errorType: "countability", whyHe: "furniture לא מקבל s." },
          { text: "furniture" },
          { text: "a furniture", errorType: "countability", whyHe: "אין a לפני שם עצם לא ספיר." },
        ],
        answerIndex: 1,
        explainHe: "furniture תמיד ביחיד. פריט אחד: a piece of furniture.",
      },
      { id: "i-uncountable-plural-03", type: "fix", prompt: "The website has many useful informations.", answer: "The website has a lot of useful information.", accept: ["The website has plenty of useful information."], errorType: "countability", explainHe: "information לא ספירה, ולכן גם many הופך ל-a lot of." },
      {
        id: "i-uncountable-plural-04",
        type: "mcq",
        prompt: "Can I give you ___ of advice?",
        options: [
          { text: "a piece" },
          { text: "an item", errorType: "word-choice", whyHe: "item לא משמש עם advice." },
          { text: "a part", errorType: "word-choice", whyHe: "a part of advice לא נאמר." },
        ],
        answerIndex: 0,
        explainHe: "a piece of advice = עצה אחת. אותו מבנה: a piece of information, a piece of furniture.",
      },
    ],
  },
  {
    id: "i-the-life",
    titleHe: "the life / the people בהכללות",
    wrong: "The life in Israel is expensive but interesting.",
    right: "Life in Israel is expensive but interesting.",
    explainHe: "בעברית אומרים 'החיים יקרים' ו'האנשים נחמדים' עם ה' הידיעה. באנגלית הכללה היא בלי the: Life is short, People are nice, Money isn't everything.",
    pattern: "\\bthe\\s+(life|nature|society|happiness|freedom|love)\\s+(is|was|in|makes|gives|teaches|can)\\b",
    drills: [
      { id: "i-the-life-01", type: "fix", prompt: "The people are more relaxed in the south.", answer: "People are more relaxed in the south.", errorType: "article", explainHe: "הכללה על אנשים בכלל – בלי the. (the people נכון רק כשמדובר בקבוצה מסוימת שהוזכרה.)" },
      {
        id: "i-the-life-02",
        type: "mcq",
        prompt: "___ is short, so enjoy it.",
        options: [
          { text: "The life", errorType: "article", whyHe: "תרגום של 'החיים'." },
          { text: "Life" },
          { text: "A life", errorType: "article", whyHe: "a life = חיים אחדים מתוך רבים, לא הכללה." },
        ],
        answerIndex: 1,
        explainHe: "Life is short – מושג כללי, בלי תווית יידוע.",
      },
      { id: "i-the-life-03", type: "fix", prompt: "I think the money doesn't buy happiness.", answer: "I think money doesn't buy happiness.", errorType: "article", explainHe: "money כמושג כללי – בלי the. the money = כסף מסוים שדיברנו עליו." },
      {
        id: "i-the-life-04",
        type: "mcq",
        prompt: "___ are getting more expensive every year.",
        options: [
          { text: "The flights", errorType: "article", whyHe: "the מצביע על טיסות מסוימות." },
          { text: "Flights" },
          { text: "A flight", errorType: "article", whyHe: "יחיד לא מתאים להכללה עם are." },
        ],
        answerIndex: 1,
        explainHe: "רבים בהכללה – בלי the: Flights are expensive, Cars are cheaper now.",
      },
    ],
  },

  // ---------------------------------------------------------------------------
  // Word order and question forms
  // ---------------------------------------------------------------------------
  {
    id: "i-embedded-question",
    titleHe: "I don't know what is it",
    wrong: "I don't know what is it in English.",
    right: "I don't know what it is in English.",
    explainHe: "בעברית סדר המילים בשאלה משועבדת זהה לשאלה רגילה. באנגלית אחרי know/tell/wonder חוזרים לסדר של משפט רגיל: קודם הנושא ואז הפועל.",
    pattern: "\\b(know|knows|tell|told|remember|understand|wonder|wondering|sure|ask|asked)\\b[^.?!]*\\b(what|where|when|why|who|how)\\s+(is|are|was|were|do|does|did|can|will)\\s+(it|he|she|they|you|we|i|the\\s+\\w+)\\b",
    drills: [
      { id: "i-embedded-question-01", type: "fix", prompt: "Do you know where is the station?", answer: "Do you know where the station is?", errorType: "word-order", explainHe: "בתוך שאלה משועבדת: where + נושא + פועל. השאלה הישירה היא Where is the station?" },
      {
        id: "i-embedded-question-02",
        type: "mcq",
        prompt: "Can you tell me ___?",
        options: [
          { text: "what time is it", errorType: "word-order", whyHe: "זה סדר של שאלה ישירה." },
          { text: "what time it is" },
          { text: "what is time", errorType: "word-order", whyHe: "גם הסדר וגם המשמעות שגויים." },
        ],
        answerIndex: 1,
        explainHe: "Can you tell me what time it is? הפועל is עובר אחרי הנושא.",
      },
      { id: "i-embedded-question-03", type: "fix", prompt: "I'm not sure why is she angry.", answer: "I'm not sure why she is angry.", accept: ["I'm not sure why she's angry."], errorType: "word-order", explainHe: "אחרי I'm not sure הסדר רגיל: why she is angry." },
      {
        id: "i-embedded-question-04",
        type: "mcq",
        prompt: "She asked me where ___.",
        options: [
          { text: "do I live", errorType: "question-form", whyHe: "do לא נכנס לשאלה משועבדת." },
          { text: "I live" },
          { text: "am I living", errorType: "word-order", whyHe: "היפוך של נושא ופועל שייך לשאלה ישירה." },
        ],
        answerIndex: 1,
        explainHe: "בשאלה משועבדת אין do/does/did ואין היפוך: where I live.",
      },
    ],
  },
  {
    id: "i-missing-auxiliary",
    titleHe: "Where you live? – שאלה בלי do",
    wrong: "Where you live now?",
    right: "Where do you live now?",
    explainHe: "בעברית שואלים 'איפה אתה גר?' בלי מילת עזר. באנגלית שאלה בהווה או בעבר פשוט חייבת do/does/did.",
    pattern: "(?:^|[.!?]\\s*)(where|what|when|why|how)\\s+(i|you|he|she|we|they)\\s+(live|lives|lived|work|works|go|goes|come|comes|study|studies|want|wants|eat|eats|learn|learns|finish|finished|went|said|bought|watch|watches)\\b[^.!?]*\\?",
    drills: [
      { id: "i-missing-auxiliary-01", type: "fix", prompt: "What time you finish work?", answer: "What time do you finish work?", errorType: "question-form", explainHe: "שאלה בהווה פשוט: do + נושא + פועל בסיסי." },
      {
        id: "i-missing-auxiliary-02",
        type: "mcq",
        prompt: "___ she work in the same office?",
        options: [
          { text: "Does" },
          { text: "Do", errorType: "agreement", whyHe: "עם she צריך does." },
          { text: "Is", errorType: "question-form", whyHe: "is דורש פועל עם ing: Is she working?" },
        ],
        answerIndex: 0,
        explainHe: "Does she work? – אחרי does הפועל בצורה הבסיסית, בלי s.",
      },
      { id: "i-missing-auxiliary-03", type: "fix", prompt: "Why he said that to you?", answer: "Why did he say that to you?", errorType: "question-form", explainHe: "בעבר: did + פועל בסיסי. ה-did כבר נושא את הזמן, ולכן say ולא said." },
      {
        id: "i-missing-auxiliary-04",
        type: "mcq",
        prompt: "Where ___ last summer?",
        options: [
          { text: "you went", errorType: "question-form", whyHe: "חסרה מילת העזר did." },
          { text: "did you go" },
          { text: "you did go", errorType: "word-order", whyHe: "מילת העזר צריכה לבוא לפני הנושא." },
        ],
        answerIndex: 1,
        explainHe: "Where did you go? – מילת העזר לפני הנושא, והפועל בצורה הבסיסית.",
      },
    ],
  },
  {
    id: "i-very-like",
    titleHe: "I very like במקום I really like",
    wrong: "I very like this song.",
    right: "I really like this song.",
    explainHe: "בעברית 'אני מאוד אוהב' – 'מאוד' לפני הפועל. באנגלית very לא מתאר פעלים: אומרים I really like it או I like it a lot.",
    pattern: "\\b(i|you|we|they|he|she)\\s+(very|very\\s+much)\\s+(like|likes|love|loves|want|wants|enjoy|enjoys|hate|hates|miss|misses)\\b",
    drills: [
      { id: "i-very-like-01", type: "fix", prompt: "She very likes her new job.", answer: "She really likes her new job.", accept: ["She likes her new job a lot."], errorType: "word-order", explainHe: "very לא יכול לתאר פועל. really likes או likes it a lot." },
      {
        id: "i-very-like-02",
        type: "mcq",
        prompt: "I ___ enjoyed the trip.",
        options: [
          { text: "very", errorType: "word-order", whyHe: "very מתאר רק שמות תואר ותארי פועל." },
          { text: "really" },
          { text: "much", errorType: "word-order", whyHe: "much לבד לא בא לפני הפועל במשפט חיובי." },
        ],
        answerIndex: 1,
        explainHe: "really + פועל. very עובד רק עם תואר: very happy, very tired.",
      },
      { id: "i-very-like-03", type: "fix", prompt: "We very want to see you.", answer: "We really want to see you.", accept: ["We'd really like to see you."], errorType: "word-order", explainHe: "really want. very לפני פועל אף פעם לא תקין." },
      { id: "i-very-like-04", type: "translate", he: "אני מאוד אוהב את העבודה שלי.", answer: "I really like my job.", accept: ["I like my job a lot.", "I love my job."], explainHe: "'מאוד אוהב' = really like / like a lot / love. לא very like." },
    ],
  },
  {
    id: "i-like-very-much-it",
    titleHe: "I like very much it – מיקום המושא",
    wrong: "I like very much this restaurant.",
    right: "I like this restaurant very much.",
    explainHe: "בעברית התיאור בא לפני המושא: 'אני מאוד אוהב את המקום'. באנגלית המושא צמוד לפועל, ו-very much עובר לסוף המשפט.",
    pattern: "\\b(like|likes|liked|love|loves|enjoy|enjoys|hate|hates|want|wants|miss|misses)\\s+very\\s+much\\s+(it|this|that|these|those|him|her|them|the|my|your|his|our|their)\\b",
    drills: [
      { id: "i-like-very-much-it-01", type: "fix", prompt: "She loves very much her grandchildren.", answer: "She loves her grandchildren very much.", errorType: "word-order", explainHe: "פועל + מושא + very much. אסור להפריד בין הפועל למושא." },
      {
        id: "i-like-very-much-it-02",
        type: "mcq",
        prompt: "Which sentence sounds natural?",
        options: [
          { text: "I enjoyed very much the concert.", errorType: "word-order", whyHe: "very much מפריד בין הפועל למושא." },
          { text: "I enjoyed the concert very much." },
          { text: "I very enjoyed the concert.", errorType: "word-order", whyHe: "very לא מתאר פועל." },
        ],
        answerIndex: 1,
        explainHe: "המושא נשאר צמוד לפועל, והתיאור הולך לסוף.",
      },
      { id: "i-like-very-much-it-03", type: "fix", prompt: "We liked very much it.", answer: "We liked it very much.", errorType: "word-order", explainHe: "עם כינוי גוף זה בולט במיוחד: liked it very much." },
      {
        id: "i-like-very-much-it-04",
        type: "mcq",
        prompt: "He misses ___.",
        options: [
          { text: "very much his family", errorType: "word-order", whyHe: "התיאור לפני המושא." },
          { text: "his family very much" },
          { text: "much very his family", errorType: "word-order", whyHe: "סדר לא קיים באנגלית." },
        ],
        answerIndex: 1,
        explainHe: "misses his family very much – קודם את מי, ואז כמה.",
      },
    ],
  },

  // ---------------------------------------------------------------------------
  // -ed / -ing adjectives and false friends
  // ---------------------------------------------------------------------------
  {
    id: "i-am-boring",
    titleHe: "I am boring במקום I am bored",
    wrong: "The lecture was long and I was boring the whole time.",
    right: "The lecture was long and I was bored the whole time.",
    explainHe: "בעברית 'משועמם' ו'משעמם' קרובים, ובאנגלית ההבדל חד: ed- מתאר מה אני מרגיש (I was bored), ו-ing- מתאר את מה שגורם לתחושה. I am boring פירושו שאני אדם משעמם.",
    pattern: "\\b((i\\s*'m)|(you\\s*'re)|(he\\s*'s)|(she\\s*'s)|(we\\s*'re)|(they\\s*'re)|((i|you|he|she|we|they)\\s+(am|is|are|was|were)))\\s+((so|very|really|quite|a\\s+bit|totally)\\s+)?boring\\b",
    drills: [
      { id: "i-am-boring-01", type: "fix", prompt: "I'm boring, there's nothing to do here.", answer: "I'm bored, there's nothing to do here.", errorType: "word-choice", explainHe: "I'm bored = משועמם. I'm boring = אני אדם משעמם." },
      {
        id: "i-am-boring-02",
        type: "mcq",
        prompt: "The kids were ___ during the long drive.",
        options: [
          { text: "boring", errorType: "word-choice", whyHe: "אז הילדים הם המשעממים." },
          { text: "bored" },
          { text: "bore", errorType: "verb-form", whyHe: "צורת פועל, לא שם תואר." },
        ],
        answerIndex: 1,
        explainHe: "התחושה של האנשים – ed: bored, tired, excited.",
      },
      { id: "i-am-boring-03", type: "fix", prompt: "She was very surprising when she heard the news.", answer: "She was very surprised when she heard the news.", errorType: "word-choice", explainHe: "אותו כלל: surprised = הופתעה. surprising = מפתיע." },
      {
        id: "i-am-boring-04",
        type: "mcq",
        prompt: "The end of the film was really ___.",
        options: [
          { text: "confused", errorType: "word-choice", whyHe: "confused מתאר אדם מבולבל." },
          { text: "confusing" },
          { text: "confuse", errorType: "verb-form", whyHe: "פועל, לא שם תואר." },
        ],
        answerIndex: 1,
        explainHe: "הדבר שגורם לתחושה – ing: confusing, interesting, exciting.",
      },
    ],
  },
  {
    id: "i-interesting-in",
    titleHe: "I am interesting in במקום interested in",
    wrong: "I'm very interesting in history and politics.",
    right: "I'm very interested in history and politics.",
    explainHe: "אותו כלל כמו bored/boring: ed- לתחושה שלי (I'm interested in), ו-ing- למה שמעניין. I'm interesting פירושו שאני אדם מעניין.",
    pattern: "\\binteresting\\s+in\\b",
    drills: [
      { id: "i-interesting-in-01", type: "fix", prompt: "Are you interesting in the job?", answer: "Are you interested in the job?", errorType: "word-choice", explainHe: "interested IN something – זו התחושה של האדם." },
      {
        id: "i-interesting-in-02",
        type: "mcq",
        prompt: "She's really ___ in learning Arabic.",
        options: [
          { text: "interesting", errorType: "word-choice", whyHe: "אז היא עצמה מעניינת." },
          { text: "interested" },
          { text: "interest", errorType: "verb-form", whyHe: "פועל או שם עצם, לא שם תואר." },
        ],
        answerIndex: 1,
        explainHe: "be interested in + שם עצם או פועל עם ing.",
      },
      { id: "i-interesting-in-03", type: "fix", prompt: "He is not interesting in sports at all.", answer: "He is not interested in sports at all.", errorType: "word-choice", explainHe: "interested in sports. מילת היחס תמיד in." },
      {
        id: "i-interesting-in-04",
        type: "mcq",
        prompt: "The lecture was ___, I learned a lot.",
        options: [
          { text: "interested", errorType: "word-choice", whyHe: "הרצאה לא מרגישה." },
          { text: "interesting" },
          { text: "interest", errorType: "verb-form", whyHe: "לא שם תואר." },
        ],
        answerIndex: 1,
        explainHe: "כאן ההרצאה היא המקור לתחושה, ולכן ing: interesting.",
      },
    ],
  },
  {
    id: "i-close-the-light",
    titleHe: "close / open the light",
    wrong: "Please close the light before you leave.",
    right: "Please turn off the light before you leave.",
    explainHe: "בעברית 'סוגרים אור' ו'פותחים טלוויזיה'. באנגלית מכשירי חשמל נדלקים ונכבים: turn on / turn off (או switch on/off). close ו-open שמורים לדלת ולחלון.",
    pattern: "\\b(close|closes|closed|closing|open|opens|opened|opening)\\s+the\\s+(light|lights|tv|television|radio|air\\s+conditioner|computer|heater)\\b",
    drills: [
      { id: "i-close-the-light-01", type: "fix", prompt: "Can you open the air conditioner? It's hot.", answer: "Can you turn on the air conditioner? It's hot.", accept: ["Can you switch on the air conditioner? It's hot."], errorType: "word-choice", explainHe: "turn on / switch on למכשירים. open רק לדלת, חלון או קופסה." },
      {
        id: "i-close-the-light-02",
        type: "mcq",
        prompt: "Don't forget to ___ the TV.",
        options: [
          { text: "close", errorType: "word-choice", whyHe: "תרגום של 'לסגור טלוויזיה'." },
          { text: "turn off" },
          { text: "shut", errorType: "word-choice", whyHe: "shut שייך לדלת: shut the door." },
        ],
        answerIndex: 1,
        explainHe: "turn off the TV. אפשר גם switch off.",
      },
      { id: "i-close-the-light-03", type: "fix", prompt: "He closed the computer and went to sleep.", answer: "He turned off the computer and went to sleep.", accept: ["He shut down the computer and went to sleep."], errorType: "word-choice", explainHe: "turn off או shut down למחשב. close the computer נשמע כאילו סגרו את המכסה." },
      {
        id: "i-close-the-light-04",
        type: "mcq",
        prompt: "It's dark in here. ___ the light, please.",
        options: [
          { text: "Open", errorType: "word-choice", whyHe: "'תפתח את האור' בעברית בלבד." },
          { text: "Turn on" },
          { text: "Light", errorType: "word-choice", whyHe: "light כפועל שייך לנר או לאש." },
        ],
        answerIndex: 1,
        explainHe: "turn on the light. שימו לב שאפשר גם turn the light on.",
      },
    ],
  },
  {
    id: "i-has-right",
    titleHe: "he has right במקום he's right",
    wrong: "You have right, the meeting is at ten.",
    right: "You're right, the meeting is at ten.",
    explainHe: "בעברית 'יש לך צדק' או 'אתה צודק', ומכאן have. באנגלית 'צודק' הוא שם תואר: You're right. (have the right to = יש לך זכות.)",
    pattern: "\\b(i|you|he|she|we|they)\\s+(have|has|had)\\s+right\\b",
    drills: [
      { id: "i-has-right-01", type: "fix", prompt: "He has right about the price.", answer: "He's right about the price.", accept: ["He is right about the price."], errorType: "interference", explainHe: "be right, לא have right. גם be wrong באותו מבנה." },
      {
        id: "i-has-right-02",
        type: "mcq",
        prompt: "I think ___ about this one.",
        options: [
          { text: "you have right", errorType: "interference", whyHe: "תרגום של 'יש לך צדק'." },
          { text: "you're right" },
          { text: "you have reason", errorType: "interference", whyHe: "תרגום משפות אחרות, לא קיים באנגלית." },
        ],
        answerIndex: 1,
        explainHe: "you're right / you were right. השורש הוא be.",
      },
      { id: "i-has-right-03", type: "fix", prompt: "She had right and I was wrong.", answer: "She was right and I was wrong.", errorType: "interference", explainHe: "was right מול was wrong – אותו פועל be בשני הצדדים." },
      {
        id: "i-has-right-04",
        type: "mcq",
        prompt: "Everyone ___ the right to complain.",
        options: [
          { text: "is", errorType: "word-choice", whyHe: "כאן מדובר בזכות, ולכן have." },
          { text: "has" },
          { text: "have", errorType: "agreement", whyHe: "everyone הוא יחיד." },
        ],
        answerIndex: 1,
        explainHe: "have THE right to = יש זכות. שימו לב ל-the: זה מה שמבדיל מהטעות have right.",
      },
    ],
  },
  {
    id: "i-take-a-decision",
    titleHe: "take a decision במקום make a decision",
    wrong: "We need to take a decision before Sunday.",
    right: "We need to make a decision before Sunday.",
    explainHe: "בעברית 'מקבלים החלטה', ודוברי עברית בוחרים take. הצירוף באנגלית הוא make a decision (וגם reach a decision).",
    pattern: "\\b(take|takes|taking|took|taken)\\s+(a|the)\\s+(\\w+\\s+)?decisions?\\b",
    drills: [
      { id: "i-take-a-decision-01", type: "fix", prompt: "She took a difficult decision last week.", answer: "She made a difficult decision last week.", errorType: "word-choice", explainHe: "make a decision. take שייך למבחן, לתמונה או למונית." },
      {
        id: "i-take-a-decision-02",
        type: "mcq",
        prompt: "Who ___ the final decision here?",
        options: [
          { text: "takes", errorType: "word-choice", whyHe: "'מקבל החלטה' בעברית, אבל לא take." },
          { text: "makes" },
          { text: "does", errorType: "word-choice", whyHe: "do a decision לא קיים." },
        ],
        answerIndex: 1,
        explainHe: "make the decision. הצירוף קבוע ולא ניתן להחלפה.",
      },
      { id: "i-take-a-decision-03", type: "fix", prompt: "They are taking the decision tomorrow.", answer: "They are making the decision tomorrow.", errorType: "word-choice", explainHe: "make a decision גם בזמן ממושך: are making." },
      {
        id: "i-take-a-decision-04",
        type: "mcq",
        prompt: "It took us a week to ___ a decision.",
        options: [
          { text: "take", errorType: "word-choice", whyHe: "take לא מתחבר ל-decision." },
          { text: "reach" },
          { text: "give", errorType: "word-choice", whyHe: "give a decision לא נאמר." },
        ],
        answerIndex: 1,
        explainHe: "reach a decision = להגיע להחלטה אחרי דיון. גם make a decision מתאים כאן.",
      },
    ],
  },
  {
    id: "i-learn-me",
    titleHe: "learn me במקום teach me",
    wrong: "My uncle learned me how to drive.",
    right: "My uncle taught me how to drive.",
    explainHe: "בעברית 'ללמד' ו'ללמוד' דומים, ובאנגלית אלה שני פעלים שונים: teach = ללמד מישהו, learn = ללמוד בעצמך.",
    pattern: "\\b(learn|learns|learned|learnt|learning)\\s+(me|him|her|us|them)\\b",
    drills: [
      { id: "i-learn-me-01", type: "fix", prompt: "Can you learn me this song?", answer: "Can you teach me this song?", errorType: "word-choice", explainHe: "teach somebody something. learn אף פעם לא לוקח אדם כמושא." },
      {
        id: "i-learn-me-02",
        type: "mcq",
        prompt: "She ___ us English for three years.",
        options: [
          { text: "learned", errorType: "word-choice", whyHe: "learn = ללמוד, ולכן אי אפשר us." },
          { text: "taught" },
          { text: "studied", errorType: "word-choice", whyHe: "study = ללמוד בעצמו." },
        ],
        answerIndex: 1,
        explainHe: "teach – taught – taught. פועל לא רגיל.",
      },
      { id: "i-learn-me-03", type: "fix", prompt: "He is learning his little brother to swim.", answer: "He is teaching his little brother to swim.", errorType: "word-choice", explainHe: "teach somebody to do something – ללמד מישהו לעשות משהו. learn לא יכול לקחת אדם." },
      {
        id: "i-learn-me-04",
        type: "mcq",
        prompt: "I want to ___ how to cook.",
        options: [
          { text: "teach", errorType: "word-choice", whyHe: "teach פירושו ללמד אחרים." },
          { text: "learn" },
          { text: "study to", errorType: "verb-form", whyHe: "study לא לוקח to לפני how." },
        ],
        answerIndex: 1,
        explainHe: "learn how to do something – כשאני זה שלומד.",
      },
    ],
  },
  {
    id: "i-said-him",
    titleHe: "I said him במקום I told him",
    wrong: "I said him that the meeting was cancelled.",
    right: "I told him that the meeting was cancelled.",
    explainHe: "בעברית 'אמרתי לו', והאדם בא מיד אחרי הפועל. באנגלית say לא לוקח אדם ישירות: או tell somebody something, או say something TO somebody.",
    pattern: "\\b(say|says|said|saying)\\s+(me|him|her|us|them)\\b",
    drills: [
      { id: "i-said-him-01", type: "fix", prompt: "She said me the truth.", answer: "She told me the truth.", errorType: "word-choice", explainHe: "tell + אדם + מה. say לא עובד עם אדם ישירות." },
      {
        id: "i-said-him-02",
        type: "mcq",
        prompt: "He ___ me he was tired.",
        options: [
          { text: "said", errorType: "word-choice", whyHe: "say לא לוקח מושא אדם." },
          { text: "told" },
          { text: "said to", errorType: "word-order", whyHe: "said to me he was tired נשמע מסורבל." },
        ],
        answerIndex: 1,
        explainHe: "tell me / tell him / tell them – tell תמיד עם אדם.",
      },
      { id: "i-said-him-03", type: "fix", prompt: "What did he say you about the job?", answer: "What did he tell you about the job?", errorType: "word-choice", explainHe: "tell you. אם רוצים say, צריך to: What did he say to you?" },
      {
        id: "i-said-him-04",
        type: "mcq",
        prompt: "Did you ___ anything to your boss?",
        options: [
          { text: "tell", errorType: "word-choice", whyHe: "אחרי tell לא בא to." },
          { text: "say" },
          { text: "told", errorType: "verb-form", whyHe: "אחרי did צריך צורה בסיסית." },
        ],
        answerIndex: 1,
        explainHe: "say something TO somebody. כשיש to – הפועל הוא say.",
      },
    ],
  },
  {
    id: "i-want-that-you",
    titleHe: "I want that you come",
    wrong: "I want that you come with me tomorrow.",
    right: "I want you to come with me tomorrow.",
    explainHe: "בעברית 'אני רוצה שתבוא' עם 'ש'. באנגלית אחרי want, need ו-would like לא בא that אלא מושא + to: I want you to come.",
    pattern: "\\b(want|wants|wanted|need|needs|needed|prefer|prefers|would\\s+like|'d\\s+like|expect|expects)\\s+that\\s+(i|you|he|she|we|they|my|his|her|the)\\b",
    drills: [
      { id: "i-want-that-you-01", type: "fix", prompt: "She wants that we call her tonight.", answer: "She wants us to call her tonight.", errorType: "verb-form", explainHe: "want + מושא + to: wants us to call. שימו לב ש-we הופך ל-us." },
      {
        id: "i-want-that-you-02",
        type: "mcq",
        prompt: "I'd like ___ the report today.",
        options: [
          { text: "that you send", errorType: "verb-form", whyHe: "that לא בא אחרי would like." },
          { text: "you to send" },
          { text: "you send", errorType: "verb-form", whyHe: "חסר to." },
        ],
        answerIndex: 1,
        explainHe: "would like somebody to do something – מבנה קבוע.",
      },
      { id: "i-want-that-you-03", type: "fix", prompt: "They need that I finish it by Friday.", answer: "They need me to finish it by Friday.", errorType: "verb-form", explainHe: "need + מושא + to. I הופך ל-me כי הוא מושא." },
      { id: "i-want-that-you-04", type: "translate", he: "אני רוצה שהוא יעזור לי.", answer: "I want him to help me.", accept: ["I'd like him to help me."], explainHe: "want him to help – בלי that ובלי עתיד." },
    ],
  },

  // ---------------------------------------------------------------------------
  // Tense and aspect
  // ---------------------------------------------------------------------------
  {
    id: "i-living-since-years",
    titleHe: "I am living here since two years",
    wrong: "I am living in this apartment since two years.",
    right: "I have lived in this apartment for two years.",
    explainHe: "בעברית 'אני גר פה שנתיים' בהווה. באנגלית פעולה שהתחילה בעבר ונמשכת דורשת Present Perfect, ומשך זמן מקבל for ולא since.",
    pattern: "\\b(am|is|are)\\s+\\w+ing\\b[^.?!]*\\bsince\\s+(\\d+|a|an|two|three|four|five|six|seven|eight|nine|ten)\\s+(year|month|week|day|hour)s?\\b",
    drills: [
      { id: "i-living-since-years-01", type: "fix", prompt: "She is working here since 2019.", answer: "She has worked here since 2019.", accept: ["She has been working here since 2019."], errorType: "tense", explainHe: "התחיל בעבר ונמשך: Present Perfect. עם 2019 דווקא since, כי זו נקודת התחלה." },
      {
        id: "i-living-since-years-02",
        type: "mcq",
        prompt: "___ in Tel Aviv for six years.",
        options: [
          { text: "I am living", errorType: "tense", whyHe: "הווה ממושך לא מתאר משך שנמשך מאז העבר." },
          { text: "I have lived" },
          { text: "I live", errorType: "tense", whyHe: "הווה פשוט לא מחבר עבר להווה." },
        ],
        answerIndex: 1,
        explainHe: "have lived + for + משך זמן. זה המבנה לפעולה שנמשכת עד עכשיו.",
      },
      { id: "i-living-since-years-03", type: "fix", prompt: "We are waiting for the bus since twenty minutes.", answer: "We have been waiting for the bus for twenty minutes.", errorType: "tense", explainHe: "have been waiting + for. שתי טעויות בבת אחת: הזמן ומילת היחס." },
      { id: "i-living-since-years-04", type: "translate", he: "אני לומד אנגלית שלוש שנים.", answer: "I have been studying English for three years.", accept: ["I've studied English for three years.", "I have studied English for three years."], explainHe: "פעולה שהתחילה בעבר וממשיכה: have been studying, עם for למשך." },
    ],
  },
  {
    id: "i-since-duration",
    titleHe: "since three hours במקום for",
    wrong: "We have been waiting here since three hours.",
    right: "We have been waiting here for three hours.",
    explainHe: "בעברית 'כבר שלוש שעות' – ביטוי אחד לשתי המשמעויות. באנגלית since + נקודת התחלה (since Monday, since 2019), ו-for + משך זמן (for three hours).",
    pattern: "\\b(have|has|had|'ve|'s)\\b[^.?!]*\\bsince\\s+(a|an|\\d+|two|three|four|five|six|seven|eight|nine|ten|twenty|many|several)\\s+(few\\s+)?(second|minute|hour|day|week|month|year|decade)s?\\b",
    drills: [
      { id: "i-since-duration-01", type: "fix", prompt: "I haven't seen him since two months.", answer: "I haven't seen him for two months.", accept: ["I haven't seen him in two months."], errorType: "preposition", explainHe: "two months = משך, ולכן for. בדיבור אמריקאי אפשר גם in two months." },
      {
        id: "i-since-duration-02",
        type: "mcq",
        prompt: "She's been sick ___ a week.",
        options: [
          { text: "since", errorType: "preposition", whyHe: "a week הוא משך, לא נקודת התחלה." },
          { text: "for" },
          { text: "from", errorType: "preposition", whyHe: "from דורש to: from Monday to Friday." },
        ],
        answerIndex: 1,
        explainHe: "for a week = במשך שבוע. since last week = מאז שבוע שעבר.",
      },
      { id: "i-since-duration-03", type: "fix", prompt: "They have known each other since ten years.", answer: "They have known each other for ten years.", errorType: "preposition", explainHe: "ten years = כמה זמן, ולכן for." },
      {
        id: "i-since-duration-04",
        type: "mcq",
        prompt: "We've lived here ___ 2018.",
        options: [
          { text: "for", errorType: "preposition", whyHe: "2018 היא נקודת זמן, לא משך." },
          { text: "since" },
          { text: "from", errorType: "preposition", whyHe: "from לבד לא משמש עם Present Perfect." },
        ],
        answerIndex: 1,
        explainHe: "since 2018 = מאז 2018. שנה מסוימת תמיד מקבלת since.",
      },
    ],
  },
  {
    id: "i-am-born",
    titleHe: "I am born במקום I was born",
    wrong: "I am born in Haifa in 1994.",
    right: "I was born in Haifa in 1994.",
    explainHe: "בעברית 'נולדתי' בעבר, אבל התרגום יוצא בהווה. באנגלית זה תמיד סביל בעבר: I was born, she was born, they were born.",
    pattern: "\\b((i|you|he|she|we|they)\\s+(am|is|are)|i\\s*'m|he\\s*'s|she\\s*'s|they\\s*'re|we\\s*'re|you\\s*'re)\\s+born\\b",
    drills: [
      { id: "i-am-born-01", type: "fix", prompt: "My son is born in 2015.", answer: "My son was born in 2015.", errorType: "tense", explainHe: "was born – אירוע שקרה בעבר, ולכן פסיב בעבר." },
      {
        id: "i-am-born-02",
        type: "mcq",
        prompt: "Where ___ you born?",
        options: [
          { text: "are", errorType: "tense", whyHe: "הלידה כבר קרתה." },
          { text: "were" },
          { text: "did", errorType: "question-form", whyHe: "born הוא צורה שלישית, ודורש be." },
        ],
        answerIndex: 1,
        explainHe: "Where were you born? – שאלה בסביל בעבר.",
      },
      { id: "i-am-born-03", type: "fix", prompt: "They are born in the same year.", answer: "They were born in the same year.", errorType: "tense", explainHe: "were born. רבים בעבר מקבלים were." },
      { id: "i-am-born-04", type: "translate", he: "נולדתי בתל אביב.", answer: "I was born in Tel Aviv.", explainHe: "I was born – זה המבנה הקבוע, אין דרך אחרת לומר את זה." },
    ],
  },
  {
    id: "i-habit-continuous",
    titleHe: "Every day I am going – הרגל בממושך",
    wrong: "Every day I am going to the gym after work.",
    right: "Every day I go to the gym after work.",
    explainHe: "בעברית יש הווה אחד, ולכן 'כל יום אני הולך' יוצא I am going. באנגלית הרגל קבוע הוא Present Simple, והצורה הממושכת שמורה לעכשיו או לתקופה זמנית.",
    pattern: "\\b(am|is|are)\\s+\\w+ing\\b[^.?!]*\\bevery\\s+(day|morning|evening|night|week|weekend)\\b|\\bevery\\s+(day|morning|evening|night|week|weekend)\\b[^.?!]*\\b(am|is|are)\\s+\\w+ing\\b",
    drills: [
      { id: "i-habit-continuous-01", type: "fix", prompt: "He is working every Friday at the restaurant.", answer: "He works every Friday at the restaurant.", errorType: "aspect", explainHe: "every Friday = הרגל, ולכן Present Simple: he works." },
      {
        id: "i-habit-continuous-02",
        type: "mcq",
        prompt: "She ___ her parents every Saturday.",
        options: [
          { text: "is visiting", errorType: "aspect", whyHe: "ממושך מתאר עכשיו או תקופה זמנית." },
          { text: "visits" },
          { text: "visit", errorType: "agreement", whyHe: "she דורש s בסוף הפועל." },
        ],
        answerIndex: 1,
        explainHe: "הרגל קבוע: visits. every Saturday הוא סימן מובהק להווה פשוט.",
      },
      { id: "i-habit-continuous-03", type: "fix", prompt: "We are eating out every weekend.", answer: "We eat out every weekend.", errorType: "aspect", explainHe: "eat out every weekend – שגרה, ולכן הווה פשוט." },
      {
        id: "i-habit-continuous-04",
        type: "mcq",
        prompt: "I ___ coffee three times a day.",
        options: [
          { text: "am drinking", errorType: "aspect", whyHe: "three times a day מסמן הרגל." },
          { text: "drink" },
          { text: "drinks", errorType: "agreement", whyHe: "I לא מקבל s." },
        ],
        answerIndex: 1,
        explainHe: "תדירות (three times a day, usually, often) שולחת אותנו להווה פשוט.",
      },
    ],
  },
  {
    id: "i-yesterday-present",
    titleHe: "Yesterday I go – ציון עבר עם הווה",
    wrong: "Yesterday I go to the mall with my sister.",
    right: "Yesterday I went to the mall with my sister.",
    explainHe: "בעברית מילת הזמן כבר מספרת שזה עבר. באנגלית מילת זמן בעבר (yesterday, last week, two days ago) מחייבת פועל בעבר.",
    pattern: "\\b(yesterday|last\\s+(night|week|month|year|summer|winter|monday|friday)|(two|three|five|ten|\\d+)\\s+(days|weeks|months|years)\\s+ago)\\b[^.?!]*\\b(i|we|you|they|he|she)\\s+(go|goes|come|comes|see|sees|eat|eats|meet|meets|buy|buys|take|takes|get|gets|give|gives|find|finds|walk|walks|watch|watches|talk|talks|call|calls|stay|stays|start|starts|finish|finishes|visit|visits|travel|travels|cook|cooks|clean|cleans|arrive|arrives)\\b",
    drills: [
      { id: "i-yesterday-present-01", type: "fix", prompt: "Last week we meet the new manager.", answer: "Last week we met the new manager.", errorType: "tense", explainHe: "last week = עבר סגור, ולכן met." },
      {
        id: "i-yesterday-present-02",
        type: "mcq",
        prompt: "Two days ago they ___ the tickets.",
        options: [
          { text: "buy", errorType: "tense", whyHe: "ago מחייב עבר." },
          { text: "bought" },
          { text: "have bought", errorType: "tense", whyHe: "Present Perfect לא מסתדר עם ago." },
        ],
        answerIndex: 1,
        explainHe: "ago תמיד עם Past Simple: bought.",
      },
      { id: "i-yesterday-present-03", type: "fix", prompt: "Yesterday she calls me three times.", answer: "Yesterday she called me three times.", errorType: "tense", explainHe: "called. גם אם מספרים סיפור, מילת הזמן קובעת." },
      {
        id: "i-yesterday-present-04",
        type: "mcq",
        prompt: "I ___ him at the conference last year.",
        options: [
          { text: "meet", errorType: "tense", whyHe: "last year הוא עבר סגור." },
          { text: "met" },
          { text: "have met", errorType: "tense", whyHe: "אסור Present Perfect עם last year." },
        ],
        answerIndex: 1,
        explainHe: "last year מסמן עבר סגור, ולכן Past Simple: met.",
      },
    ],
  },
  {
    id: "i-perfect-past-marker",
    titleHe: "I have seen him yesterday",
    wrong: "I have seen him yesterday at the station.",
    right: "I saw him yesterday at the station.",
    explainHe: "בעברית אין הבחנה בין שני הזמנים. באנגלית Present Perfect אסור עם ציון זמן שהסתיים: עם yesterday, last week או ago משתמשים ב-Past Simple.",
    pattern: "\\b(?:(i|we|you|they|he|she|it)\\s+(have|has)|(i|we|you|they)\\s*'ve|(he|she|it)\\s*'s)\\s+(been|seen|gone|done|met|eaten|bought|written|spoken|taken|made|given|come|got|gotten|read|said|told|left|sent|found|heard|lost|won|paid|started|finished|talked|called|visited|watched|worked|played|moved)\\b[^.?!,]*\\b(yesterday|last\\s+(night|week|month|year)|(two|three|five|ten|\\d+)\\s+(days|weeks|months|years)\\s+ago)\\b",
    drills: [
      { id: "i-perfect-past-marker-01", type: "fix", prompt: "We have finished the project last month.", answer: "We finished the project last month.", errorType: "tense", explainHe: "last month סוגר את הזמן, ולכן Past Simple." },
      {
        id: "i-perfect-past-marker-02",
        type: "mcq",
        prompt: "She ___ to Greece two years ago.",
        options: [
          { text: "has traveled", errorType: "tense", whyHe: "ago לא מסתדר עם Present Perfect." },
          { text: "traveled" },
          { text: "has been traveling", errorType: "tense", whyHe: "גם כאן ago פוסל את הזמן." },
        ],
        answerIndex: 1,
        explainHe: "ago = זמן סגור, ולכן traveled.",
      },
      { id: "i-perfect-past-marker-03", type: "fix", prompt: "He has called me yesterday evening.", answer: "He called me yesterday evening.", errorType: "tense", explainHe: "yesterday evening הסתיים, ולכן called." },
      {
        id: "i-perfect-past-marker-04",
        type: "mcq",
        prompt: "I ___ this movie three times.",
        options: [
          { text: "have seen" },
          { text: "saw", errorType: "tense", whyHe: "אין ציון זמן סגור, והחוויה נמשכת עד עכשיו." },
          { text: "seen", errorType: "verb-form", whyHe: "חסר have." },
        ],
        answerIndex: 0,
        explainHe: "בלי ציון זמן סגור, ניסיון חיים מקבל Present Perfect: I have seen it three times.",
      },
    ],
  },
  {
    id: "i-has-years-old",
    titleHe: "she has 5 years old",
    wrong: "My daughter has five years old.",
    right: "My daughter is five years old.",
    explainHe: "כמו בגיל בכלל: באנגלית הגיל נאמר עם be. אומרים She is five (years old), אף פעם לא she has five years old.",
    pattern: "\\b(have|has|had)\\s+(\\d+|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve)\\s+years?\\s+old\\b",
    drills: [
      { id: "i-has-years-old-01", type: "fix", prompt: "My car has ten years old.", answer: "My car is ten years old.", errorType: "interference", explainHe: "גם לחפצים: the car is ten years old." },
      {
        id: "i-has-years-old-02",
        type: "mcq",
        prompt: "How old ___ your son?",
        options: [
          { text: "has", errorType: "interference", whyHe: "גיל אף פעם לא עם have." },
          { text: "is" },
          { text: "does", errorType: "question-form", whyHe: "old הוא שם תואר ודורש be." },
        ],
        answerIndex: 1,
        explainHe: "How old is he? – שאלת גיל עם be.",
      },
      { id: "i-has-years-old-03", type: "fix", prompt: "She has 30 years old and she has two kids.", answer: "She is 30 years old and she has two kids.", errorType: "interference", explainHe: "הגיל עם is, אבל הילדים דווקא עם has. שימו לב להבדל." },
      { id: "i-has-years-old-04", type: "translate", he: "הבת שלי בת שבע.", answer: "My daughter is seven.", accept: ["My daughter is seven years old."], explainHe: "is seven (years old). אפשר לוותר על years old בדיבור." },
    ],
  },
  {
    id: "i-its-depend",
    titleHe: "it's depend במקום it depends",
    wrong: "It's depend on how much time we have.",
    right: "It depends on how much time we have.",
    explainHe: "'תלוי' בעברית מרגיש כמו שם תואר, ולכן נוסף is. באנגלית depend הוא פועל רגיל: It depends, that depends – בלי be.",
    pattern: "\\b(it|this|that)\\s*(?:'s|\\s+is|\\s+was)\\s+depends?\\b",
    drills: [
      { id: "i-its-depend-01", type: "fix", prompt: "It's depend if I finish early.", answer: "It depends if I finish early.", errorType: "verb-form", explainHe: "It depends – פועל בגוף שלישי, ולכן s בסוף ובלי is." },
      {
        id: "i-its-depend-02",
        type: "mcq",
        prompt: "___ on the traffic.",
        options: [
          { text: "It's depend", errorType: "verb-form", whyHe: "אין be לפני פועל רגיל." },
          { text: "It depends" },
          { text: "It depending", errorType: "verb-form", whyHe: "ing בלי be לא עומד לבד." },
        ],
        answerIndex: 1,
        explainHe: "It depends on something. שימו לב ל-s של גוף שלישי.",
      },
      { id: "i-its-depend-03", type: "fix", prompt: "That is depend on your manager.", answer: "That depends on your manager.", errorType: "verb-form", explainHe: "that depends. גם כאן בלי is." },
      {
        id: "i-its-depend-04",
        type: "mcq",
        prompt: "Are you coming tonight? — ___",
        options: [
          { text: "It's depends.", errorType: "verb-form", whyHe: "גם is וגם s – כפילות." },
          { text: "It depends." },
          { text: "Is depend.", errorType: "verb-form", whyHe: "חסר נושא והפועל שגוי." },
        ],
        answerIndex: 1,
        explainHe: "It depends. זו תשובה שלמה וטבעית בדיבור.",
      },
    ],
  },
  {
    id: "i-more-better",
    titleHe: "more better / most best",
    wrong: "This phone is more better than my old one.",
    right: "This phone is much better than my old one.",
    explainHe: "בעברית 'יותר טוב' תמיד שתי מילים. באנגלית או סיומת er/est או more/most, אף פעם לא שניהם: better (ולא more better), the best (ולא the most best).",
    pattern: "\\b(more|most)\\s+(better|best|worse|worst|bigger|biggest|easier|easiest|cheaper|cheapest|happier|nicer|younger|older|stronger|faster|fastest|higher|smaller)\\b",
    drills: [
      { id: "i-more-better-01", type: "fix", prompt: "She is more older than her husband.", answer: "She is older than her husband.", errorType: "word-choice", explainHe: "older כבר כולל את 'יותר'. more מיותר." },
      {
        id: "i-more-better-02",
        type: "mcq",
        prompt: "This is the ___ restaurant in town.",
        options: [
          { text: "most best", errorType: "word-choice", whyHe: "כפילות: best כבר הפלגה." },
          { text: "best" },
          { text: "more best", errorType: "word-choice", whyHe: "גם כפילות וגם צורה שגויה." },
        ],
        answerIndex: 1,
        explainHe: "the best – צורת הפלגה לא סדירה, בלי most.",
      },
      { id: "i-more-better-03", type: "fix", prompt: "The second exam was more easier.", answer: "The second exam was easier.", errorType: "word-choice", explainHe: "easier לבד. מילים קצרות מקבלות er, ואז אין more." },
      {
        id: "i-more-better-04",
        type: "mcq",
        prompt: "My new job is ___ than the old one.",
        options: [
          { text: "more better", errorType: "word-choice", whyHe: "כפילות של השוואה." },
          { text: "much better" },
          { text: "most better", errorType: "word-choice", whyHe: "most שייך להפלגה, ולא להשוואה בין שניים." },
        ],
        answerIndex: 1,
        explainHe: "כדי לחזק השוואה משתמשים ב-much, far או a lot: much better, far better.",
      },
    ],
  },
];
